// ==UserScript==
// @name         elethor-chs
// @namespace    https://www.g8hh.com/
// @version      0.0.11
// @description  Elethor (https://elethor.com/) 游戏汉化脚本 - 锅巴汉化出品
// @author       麦子、JAR、小蓝、好阳光的小锅巴
// @include      *https://elethor.com/*
// @grant        none
// @website      https://www.gityx.com
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/elethor-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/elethor-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2024/08/30 23:00
 * Author: guoba
 * View: https://www.gityx.com
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "ACTIONS": "行动",
    "ACTIVE": "激活",
    "Chat": "聊天",
    "Close": "关闭",
    "Combat": "战斗",
    "companion": "伙伴",
    "Details": "详情",
    "CRAFT": "制作",
    "Contribute": "贡献",
    "Global Combat Exp": "全局战斗经验",
    "Global Companion Exp": "全局伙伴经验",
    "Global Mining Exp": "全局采矿经验",
    "Global Double Drops": "全局双倍掉落",
    "hours": "小时",
    "Learn To Play": "了解玩法",
    "Log": "日志",
    "Logout": "登出",
    "Lookup": "检查",
    "MINING": "采矿",
    "Mining": "采矿",
    "MINE": "矿井",
    "MARKET": "市场",
    "Manage Cosmetics": "管理装饰品",
    "QUESTS": "冒险",
    "Polls": "投票",
    "SKILLS": "技能",
    "Total": "总计",
    "Today": "今日",
    "View Profile": "查看个人资料",
    "Upgrade your adventure with credits and VIP.": "用积分和VIP升级你的冒险。",
    "VIP Status": "VIP 状态",
    "VIP": "VIP",
    "View More": "查看更多",
    "Yesterday": "昨日",
    "Server Time": "服务器时间",
    "Renown buff costs are now more smoothed out, and Extractor has been buffed 10x.": "声望Buff的成本现在更加平滑，并且提取者被 Buff 增强了 10x。",
    ". They give": ". 它们给予",
    "All unlocked masteries always give their effect. The queue is just for training.": "所有已解锁的精通都能生效。排队只是为了训练。",
    "BEYOND": "转生",
    "Character": "角色",
    "COMBAT": "战斗",
    "CORP": "公司",
    "Cybernetics": "控制论",
    "Data Chips": "数据芯片",
    "Exp.": "经验值",
    "Experience": "经验值",
    "Every level gives a flat 0.1% boost to both purity and density for all nodes. Increases Geodata drop rate by 0.02% per level.": "每一级对所有节点的纯度和密度都有0.1%的提升。每升一级增加地理数据掉落率0.02%。",
    "FAME": "声誉",
    "Feedback": "反馈",
    "FIGHT": "战斗",
    "Gives a flat damage boost in combat.": "在战斗中给予一定的伤害提升。",
    "If you don't have VIP, when you save, only the top 3 masteries will remain.": "如果你没有VIP，当你保存时，只会剩下前3个精通。",
    "Inventory": "存储",
    "Level": "等级",
    "Masteries": "精通",
    "Masteries at the top are trained first.": "最顶端的精通首先被训练。",
    "MAXED": "已最大",
    "Mastery Queue": "精通队列",
    "Masteries in your queue automatically get the Data Chip applied each hour.": "在您的队列中的精通自动获得每小时应用的数据芯片。",
    "Next Level": "下一级",
    "Overview": "概览",
    "Queue is empty": "队列为空",
    "Rankings": "排行榜",
    "Remaining": "剩余",
    "Rules": "规则",
    "remaining actions": "剩余行动",
    "This is your current combat action progress.": "这是你当前的战斗行动进度。",
    "This is your current gather action progress.": "这是你当前的采集行动进度。",
    "Total Mastery Exp": "总计精通经验",
    "Unlock Mastery": "解锁精通",
    "UNMAXED": "未最大",
    "VIP gets +1 BONUS Data Chip. This bonus Token is not automatically applied.": "VIP获得+1奖励数据芯片。此奖励芯片不会自动应用。",
    "VIP:": "VIP:",
    "When the mastery levels up, it rotates off the queue automatically, and the next mastery begins training.": "当精通升级后，它会自动退出队列，下一个精通开始训练。",
    "Buy Global Boosts": "购买全局提升",
    "Increases your ability to contribute to corporations. Each level also increases your combat and mining exp by 0.5%.": "增加你为公司做贡献的能力。每升一级还会增加0.5%的战斗和采矿经验。",
    "Unlock Masteries": "解锁精通",
    "Wealthy": "富有",
    "Waste Not": "不浪费",
    "Yield more ore per gather.": "每次采集矿石产量更高。",
    "You have unlocked all masteries in this category.": "您已解锁此类别中的所有精通。",
    "Zoology": "动物学",
    "Prevail": "获胜",
    "Petrification": "僵化",
    "OTHER": "其它",
    "Omninode Booster": "Omni节点助推器",
    "Mummification": "木乃伊化",
    "Multitasking": "多任务处理",
    "Advanced Archaeology": "高级考古学",
    "Multiplies your multikill debuff gained from compendium.": "增加你从概要中获得的多重击杀减益。",
    "Buffer Efficiency": "增益效率",
    "Chipper": "",
    "Skilled Extraction": "熟练提取",
    "FILTERS": "过滤器",
    "Requires": "要求",
    "Slayer": "杀手",
    "Brainiac": "聪明而勤奋的人",
    "Buffer Efficiency": "缓冲效率",
    "Chipper": "切磋者",
    "Decreases the effectiveness of the fatigue timer multiplier for combat actions.": "降低战斗动作的疲劳计时乘数的效果。",
    "Decreases the effectiveness of the fatigue timer multiplier for mining actions.": "降低采矿行动的疲劳计时器倍增器的有效性。",
    "Decreases the required number of points to get Spire Vaults each month.": "减少每个月获得尖顶穹窿所需的点数。",
    "Depth Mining": "深度挖掘",
    "Earn Action Buffer cheaper and easier. Levels reduce the required number of actions to earn a single Buffer action.": "获得动作缓冲更便宜，更容易。关卡减少了获得一个缓冲行动所需的行动数量。",
    "Effortless": "毫不费力",
    "Environmentalism": "环境保护论",
    "Fossilized": "化石",
    "Gain a chance to gain one additional data chip every hour.": "每小时有机会获得一个额外的数据芯片。",
    "Gives a chance to not reduce remaining actions (including buffer) while in combat.": "在战斗中有机会不减少剩余的动作(包括缓冲)。",
    "Has a chance not to drain a node when gathering.": "收集时有一定几率不消耗节点。",
    "Increase multikill cap based on your total number of kills.": "根据你的总击杀数增加多重击杀上限。",
    "Increase your Fame experience earned from Corporation events.": "增加你从公司活动中获得的声望经验。",
    "Increases base gold per monster kill.": "每杀死一个怪物增加基础金币。",
    "Increases Compendium damage multiplier. Additive with Corp buff.": "增加纲要的伤害乘数。添加军团buff。",
    "Increases exp per gather action by a flat amount.": "每次收集增加一定量的经验值。",
    "Increases exp per gather action by a percentage (applied after all other bonuses).": "每次收集行动增加一定百分比的经验值(在所有其他奖励之后)。",
    "Increases exp per monster killed by a flat amount.": "每杀死一个怪物增加一定量的经验值。",
    "Increases exp per monster killed by a percentage (applied after all other bonuses).": "每杀死一个怪物增加一定百分比的经验值(在所有其他奖励之后)。",
    "Increases gold drops, rounded to the nearest whole number.": "增加金币掉落，四舍五入到最接近的整数。",
    "Increases ore gain while mining from an Omninode.": "从巨怪身上挖矿时增加矿石收益。",
    "Increases the amount of Precognitive Dust earned on a failed Empower.": "增加在一次失败的授权中获得的预知之尘的数量。",
    "Increases the bonus chance for Platinum on Recyclobot by a flat amount.": "增加回收机器人获得白金的几率。",
    "Increases the drop rate of items that drop from monsters and dungeons.": "增加怪物和地下城掉落物品的掉落率。",
    "Increases the effect of base Compendium stats. This is ONLY stats and EXCLUDES % boosts, min/max/damage/debuff.": "增加基本概要属性的效果。这只是统计，不包括%增益，最小/最大/伤害/减益。",
    "Increases the effectiveness of Companion passives.": "增加同伴被动的效果。",
    "Increases your chance to gain +1 Fossil Shop refresh per day.": "增加你每天+1次刷新化石店的机会。",
    "Increases your maximum Fossil Shop refresh capacity.": "增加你的最大化石商店刷新能力。",
    "Knowledge Extraction": "知识抽取",
    "Knowledge Weaponry": "知识武器",
    "Multiplies the effectiveness of all Omninode Modifiers.": "增加所有Omni节点修饰符的效果。",
    "Omnomnomnode": "Omnomnom节点",
    "Pressure Point": "压力点",
    "Purchase masteries to unlock them. Then train them to get their benefits!": "购买大师来解锁它们。然后训练他们获得他们的好处!",
    "Reduces the base multikill buff of the Swarm.": "减少蜂群的基础多杀buff。",
    "Renowned": "大名鼎鼎",
    "Repurposement": "重新利用",
    "Scavenger": "清道夫",
    "Skilled Weaponry": "熟练武器",
    "Spire Coefficient": "尖塔系数",
    "Swarm Management": "集群管理",
    "Teamwork": "团队合作",
    "The multiplier (_x) is how many times more mastery points you need to level up.": "乘数(_x)是指你需要多少精通点才能升级。",
    "The Whole Buffalo": "整头水牛",
    "Queue": "队列",
    "Limitless": "无限",
    "Earn": "获得",
    "Remove": "移除",
    "SAVE QUEUE": "保存队列",
    "Exp automatically every hour.": "经验每小时自动的。",
    "Queue successfully updated": "队列已成功更新",
    "All percentage upgrades to numeric stats in the Cybernetics Skill Tree only affect stats gained from the Cybernetics Skill Tree. For example, % Fortitude only increases the Fortitude gained from Cybernetics. But % Purity is an additive bonus with your other Purity sources.": "控制论技能树中所有数值属性的百分比升级只影响从控制论技能树中获得的属性。例如，%坚韧只能增加从控制论获得的坚韧。但是%纯度是一个附加的奖金与你的其他纯度来源。",
    "At your current level, it is highly advised to not spend Data Chips into Cybernetics.": "当前等级，建议不要在控制论上花费数据芯片。",
    "Buy 1 Points for 12 Data Chips": "购买 1 点数 花费 12 数据芯片",
    "Buy Points": "购买点数",
    "Cybernetics is designed as a late-game investment.": "控制论被设计为游戏后期投资。",
    "RESPEC": "重洗",
    "The stats that you gain from the Cybernetics Skill Tree are flat additions onto the end of your existing stats. The stats gained are not affected by any outside sources.": "你从控制论技能树中获得的属性是你现有属性的基础。获得的统计数据不受任何外部来源的影响。",
    "Use your Data Chips to gain Data Points. Every Data Point costs 12 Data Chips.": "使用你的数据芯片来获得数据点。每个数据点需要12个数据芯片。",
    "Use Data Chips": "使用数据芯片",
    "VIEW STATS": "查看属性",
    "You are able to reset your Data Points, but you will receive Data Points. Data Chips are permanently converted into Data Points.": "您可以重置您的数据点，但您将收到数据点。数据芯片永久转换为数据点。",
    "Buy": "购买",
    "Armor": "护甲",
    "combat Stats": "战斗属性",
    "Fortitude": "坚韧",
    "Pierce": "穿刺",
    "Savagery": "野蛮",
    "Scaling % Fortitude": "缩放 % 坚韧",
    "Scaling % Armor": "缩放 % 护甲",
    "Scaling % Pierce": "缩放 % 穿刺",
    "Scaling % Savagery": "缩放 % 野蛮",
    "Scaling Armor": "缩放 护甲",
    "Scaling Fortitude": "缩放 坚韧",
    "Scaling Pierce": "缩放 穿刺",
    "Scaling Savagery": "缩放 野蛮",
    "% Min Damage": "% 最低伤害",
    "% Damage": "% 伤害",
    "% Pierce": "% 穿刺",
    "% Fortitude": "% 坚韧",
    "% Savagery": "% 野蛮",
    "Base Stats": "基础属性",
    "Health": "生命值",
    "Rat Pelt": "鼠皮",
    "PIERCE": "穿刺",
    "SAVAGERY": "野蛮",
    "SPEED": "速度",
    "Wasteland": "荒地",
    "WASTELAND": "荒地",
    "Gold": "黄金",
    "A weasily nasty little rodent.": "一种狡猾讨厌的小啮齿动物。",
    "ARMOR": "护甲",
    "chance for": "几率为",
    "Drops": "掉落",
    "Dungeons": "地下城",
    "Each stat of Fortitude gives 25 health. Each point of Fortitude also gives +0.001% Health Multiplier.": "每个“坚韧”属性给予25点生命值。每点刚毅也给予+0.001%生命值乘数。",
    "Fighting Rat...": "战斗的老鼠……",
    "FORTITUDE": "坚韧",
    "Gain +0.1 True Damage per Savagery and +0.5 True Damage per Pierce. Then multiplied by +0.02% per Speed. True Damage is additional damage that ignores armor reduction.": "每次野蛮+0.1伤害，每次穿刺+0.5伤害。然后乘以每速度+0.02%。真正伤害是忽略护甲减少的额外伤害。",
    "Goretusk": "戈列塔斯克",
    "Higher speed decreases your attack speed interval, making you attack faster. Every point of Speed gives +0.02% multiplier to True Damage.": "更高的速度减少你的攻击速度间隔，使你攻击更快。每点速度增加0.02%的真实伤害。",
    "If your pierce is higher than the enemy's armor, it increases your damage. Each point also gives 0.5 True Damage.": "如果你的刺穿高于敌人的护甲，它会增加你的伤害。每个点也有0.5的真实伤害。",
    "Increases your damage by 2 damage per point. Each point also gives 0.1 True Damage.": "每点增加2点伤害。每个点也给予0.1的真实伤害。",
    "Incursions": "入侵",
    "Karth Drake": "卡思·德雷克",
    "Lowers damage taken in proportion to enemy pierce. If you have more armor than they have pierce, you take reduced damage.": "降低伤害与敌人刺穿成正比。如果你的护甲比他们的刺穿多，你受到的伤害就会减少。",
    "Monsters": "怪物",
    "Rajak": "拉贾克",
    "Razen Drake": "雷岑·德雷克",
    "Rodent": "啮齿动物",
    "Spire": "尖塔",
    "The monster gives this much combat experience when you kill it.": "当你杀死怪物时，它会给你很多战斗经验。",
    "Thrasher": "打谷机",
    "TRUE DAMAGE": "真实伤害",
    "Warped Tormenter": "扭曲的折磨者",
    "WORG": "狼人",
    "Worg": "狼人",
    "# of Procs": "# 触发次数",
    "Ability": "能力",
    "AVG": "平均",
    "Damage Dealt": "造成的伤害",
    "DETAILS": "详情",
    "Damage Taken": "受到的伤害",
    "Incapacitate": "软弱无力",
    "YOU": "你",
    "MONSTER": "怪物",
    "LAST FIGHT": "最近战斗",
    "Puncture": "穿刺",
    "TOTAL": "总计",
    "YOU GAINED": "你的战利品",
    "TOTAL KILLS": "总计击杀",
    "TOTAL BOOSTS": "总计提升",
    "TOTAL RANK": "总计排名",
    "Uncapped Level": "未上限等级",
    "VICIOUS PUNCTURE": "恶毒穿刺",
    "INACTIVE": "不活跃",
    "Main Hand": "主手",
    "Mastery Exp": "精通经验",
    "MAX DAMAGE": "最大伤害",
    "MIN DAMAGE": "最小伤害",
    "Missions": "任务",
    "Monster Drop": "怪物掉落",
    "FOOT": "脚部",
    "Drone": "无人机",
    "Gathering...": "采集中...",
    "HEAD": "头部",
    "Join Discord": "加入 Discord",
    "You gain": "你获得",
    "Mining Laser": "采矿激光",
    "Nanofiber": "纳米纤维",
    "Merchant": "商人",
    "LEG": "腿部",
    "/ Action": "/ 行动",
    "Iridium": "铱",
    "CHEST": "胸部",
    "COSTS": "成本",
    "Count": "数量",
    "Crafting": "制作",
    "DAMAGE": "伤害",
    "DATA CHIPS": "数据芯片",
    "EARRING": "耳环",
    "EAR AUGMENT": "耳朵增强",
    "BELT": "皮带",
    "xp / Sec": "经验值 / 秒",
    "Get VIP": "获得VIP",
    "GLOVE": "手套",
    "Global Buff:": "全局增益:",
    "HAND AUGMENT": "手部增强",
    "Gear": "装备",
    "GEAR": "装备",
    "FUEL REFINERY": "燃料提炼厂",
    "excited about NEO and what it will mean for the health and future of Elethor, and I want to communicate that clearly in the coming weeks as the system continues to be designed and implemented. As things roll out and posts are written, I want to hear your feedback! What sounds good, what seems iffy, and what needs clarification.": "我对NEO以及它对Elethor的健康和未来意味着什么感到兴奋，我想在未来几周内，随着系统的继续设计和实施，清楚地传达这一点。随着事情的展开和文章的撰写，我想听到你的反馈！什么听起来不错，什么看起来有问题，什么需要澄清。",
    "A functional if ineffective weapon.": "虽然效果不佳，但仍能正常使用。",
    "Accomplishments": "成就",
    "AGONY RESISTANCE": "抗御能力",
    "ALLSTAT": "全属性",
    "An overall damage multiplier that applies before armor.": "整体伤害乘数在加甲前生效。",
    "Attack Speed": "攻击速度",
    "Base Ore x Purity x Density x Ore Multiplier x VIP": "基础矿石x纯度x密度x矿石倍增器x VIP",
    "BRAIN AUGMENT": "大脑增强",
    "Cannot exceed 20% Enhancement": "不能超过20%",
    "CHARACTER": "角色",
    "COMPANIONS": "同伴",
    "Compendium": "纲要",
    "Compendium TR": "纲要TR",
    "Converts Omnium into Fuel": "将Omnium转化为燃料",
    "Discover tips and tricks and learn more about the game in our": "发现提示和技巧，并了解更多关于游戏在我们的",
    "Does an additional percentage (5/12/20/33)% of your damage, ignoring armor.": "对你造成额外百分比（5/12/20/33）的伤害，忽略护甲。",
    "Drake": "德雷克",
    "Each row contains the final calculated stat and the energizement stats, both percentage and per/10.": "每行包含最终计算的统计数据和激活统计数据，包括百分比和每/10。",
    "Elethor wouldn't exist without you all, and as we move into this next season together, I'm incredibly thankful for each and every one of you. Here's to Elethor and the NEO!": "Elethor没有你们就不会存在，在我们一起进入下一季的时候，我非常感谢你们每一个人。敬埃莱托和近地天体！",
    "Enhancement (20% MAX)": "增强（20% MAX）",
    "Exo Filter": "挂式过滤器",
    "EYE AUGMENT": "眼睛增强",
    "Fighting Skrivet...": "与斯克里维特战斗……",
    "FLEET": "舰队",
    "Fleet Core": "舰队核心",
    "Forever": "永远",
    "Fossil Shard Progress": "化石碎片的进展",
    "Fossil Shards Today": "今天的化石碎片",
    "Fossils": "化石",
    "Harvester": "收割机",
    "HEALTH MULTIPLIER": "健康的乘数",
    "Higher purity and density means more Omnium is gathered per action.": "更高的纯度和密度意味着每个行动收集更多的Omnium。",
    "Hunting Rifle": "猎枪",
    "I've written the first in what will be a series of posts about the upcoming T11 patch -- codename NEO (Next Evolutionary Ordinance).": "我已经写了关于即将到来的T11补丁系列的第一篇文章——代号NEO（下一个进化条例）。",
    "Increase Squadron Power Limit": "增加中队动力上限",
    "Increases maximum damage by this percentage. These stats add together (5% + 5% = 10%).": "增加该百分比的最大伤害。这些数据加起来（5% + 5% = 10%）。",
    "Increases Maximum Ships per Squadron": "增加每个中队最大舰船数量",
    "Increases minimum damage by this percentage. These stats add together (5% + 5% = 10%).": "使最小伤害增加这个百分比。这些数据加起来（5% + 5% = 10%）。",
    "Increases Mission Rewards": "增加任务奖励",
    "Increases Omnium->Fuel Efficiency": "提高整体燃油效率",
    "Increases Passive Resource Gain": "增加被动资源增益",
    "Increases Savagery, Fortitude, Speed, Pierce and Armor by a percentage after all other energizements have been applied. 100% is baseline.": "在使用所有其他能量后，增加野性、坚韧、速度、穿刺和护甲的百分比。100%是基线。",
    "Increasing your Speed decreases your attack speed. This is the interval between attacks. A lower attack speed means you attack more frequently. Softcaps at 10 Attack Speed.": "提高你的速度会降低你的攻击速度。这是攻击之间的间隔。较低的攻击速度意味着你的攻击频率更高。软帽攻击速度为10。",
    "Interact with other Elethor players in our Discord channel.": "在我们的Discord频道与其他Elethor玩家互动。",
    "Manage Exo Filter": "管理挂式过滤器",
    "Manage Fleet Core": "管理舰队核心",
    "Manage Hangar": "管理机库",
    "Manage Harvester": "管理收割机",
    "Manage Refinery": "管理炼油厂",
    "Manage Research Bay": "管理科研舱",
    "Manage Stabilizer": "管理稳定器",
    "Manage Teleporter": "管理传送点",
    "Multiplies your health by this number.": "将你的生命值乘以这个数字。",
    "NEO Roadmap - Stat System": "NEO路线图-属性系统",
    "Next Fuel Tick:": "下一个燃料Tick：",
    "OBSERVATION BAY": "观测舱",
    "of every Beyond metal per day.": "每一个超越金属每天。",
    "OFF HAND": "副手",
    "Offsets a monster's Agony stat. Agony adds +5% multikill buff and +1% max health base damage for every point a monster has more than your Agony Resistance.": "抵消怪物的痛苦属性。每增加一点怪物的痛苦抗性，就增加5%的多重杀戮buff和1%的最大生命基础伤害。",
    "OMNINODES": "万向虫",
    "Omnium": "Omnium",
    "Patch Notes": "补丁说明",
    "Prospector": "探勘者",
    "PUNCTURE": "穿刺",
    "Razor Den": "剃刀巢穴",
    "Recyclobot": "回收机器人",
    "Reduces Ship Research Time": "缩短舰船研究时间",
    "Refinery": "炼油厂",
    "Renown": "名望",
    "Research Bay": "研究舱",
    "Resource Nodes": "资源节点",
    "RESOURCES": "资源",
    "Rhenium": "铼",
    "Select a tier to view recipes": "选择一个层来查看食谱",
    "SHIPYARD": "船厂",
    "SHOULDER": "肩部",
    "Show Details": "显示详细信息",
    "Simulate Combat": "模拟战斗",
    "Simulate combat at specific distances.": "模拟特定距离的战斗。",
    "Simulation Chamber": "模拟室",
    "Skill": "技能",
    "Skrivet Pelt": "Skrivet毛皮",
    "Stabilizer": "稳定器",
    "Starbase": "母星",
    "Start Gathering": "开始采集",
    "Surveying": "测量",
    "Swarm": "蜂群",
    "Teleporter": "传送器",
    "The experience gained per second. You only gain exp per action.": "每秒钟获得的经验值。你每次行动只能获得经验值。",
    "The first post is all about the stat system. To read it, please click on 'Patch Notes' below, and then 'Roadmap' in the sidebar.": "第一篇文章是关于统计系统的。要阅读它，请点击下面的“补丁说明”，然后点击侧边栏中的“路线图”。",
    "The percentage of the enemy's damage reduction you ignore when you attack. Stacks multiplicatively.": "当你攻击时，你忽略的敌人伤害减少的百分比。栈用乘法。",
    "The Pit": "矿坑",
    "This process will be a conversation! I'm": "这个过程将是一次对话！我",
    "Thursday, October 31st, 2024 at 11:59 PM": "2024年10月31日星期四晚上11点59分",
    "Travel": "旅行",
    "Tungsten": "钨",
    "UNCOVER": "发现",
    "Upcoming Events": "即将举办的活动",
    "very": "非常",
    "Very fast, and is that a second row of teeth?": "非常快，那是第二排牙齿吗？",
    "View Prospector": "视图探勘者",
    "FILTER": "过滤器",
    "Foot": "脚部",
    "Head": "头部",
    "Item": "物品",
    "Leg": "腿部",
    "Off Hand": "副手",
    "Price": "价格",
    "POST": "发送",
    "MY LISTINGS": "我的清单",
    "NEW RAT PELT LISTING": "新的鼠皮清单",
    "INVENTORY": "库存",
    "Sell": "出售",
    "Sell Listings": "出售清单",
    "Upgrade": "升级",
    "Vault": "金库",
    "TIER": "层级",
    "ENTER SHOP": "进入商店",
    "Chest": "胸部",
    "Credit": "信用点",
    "Abyssal Essence": "深海精华",
    "Azure Tusk": "青牙",
    "Basic Energizing Shard": "基本激活碎片",
    "Basic Reinforcement": "基本的强化",
    "Bat Claw": "蝙蝠爪",
    "Belt": "皮带",
    "Black Ink": "黑色的墨水",
    "Broken Shackle": "破碎的卸扣",
    "Broken Shovel": "破碎的铲",
    "Buy Listings": "购买清单",
    "Condensed Vapor": "冷凝汽",
    "Cracked Chestpiece": "破胸",
    "Crimson Tusk": "深红色的长牙",
    "Crooked Leg": "弯曲的腿",
    "Currency": "货币",
    "Cursed Bane": "被诅咒的祸害",
    "Curved Blade": "弯曲的叶片",
    "Dark Delve": "黑暗的探究",
    "Dark Tusk": "黑斯克",
    "Data Chip": "芯片的数据",
    "Decomposing Mask": "分解的面具",
    "Deepwrought Energizing Shard": "深度锻造能量碎片",
    "Deepwrought Reinforcement": "深锻援军",
    "Drop of Aether": "以太滴",
    "Earring": "耳环",
    "Fame Token": "声誉令牌",
    "Fire Scale": "火灾规模",
    "Fireproof Tongue": "防火的舌头",
    "Fractured Rocket": "断裂的火箭",
    "Fragment of Silence": "沉默的片段",
    "Glove": "手套",
    "gold each.": "黄金。",
    "Gory Tusk": "血淋淋的象牙",
    "Growg Arm": "成长手臂",
    "I want to": "我想",
    "Imprinted Skull": "印的头骨",
    "Improved Energizing Shard": "强化能量碎片",
    "Improved Reinforcement": "改进的强化",
    "Injection": "注射",
    "Karth Plate": "Karth板",
    "Lava Worm Tooth": "熔岩虫牙",
    "Mechanoid Energizing Shard": "机械人能量碎片",
    "Mechanoid Reinforcement": "机械强化",
    "Mutagen": "诱变剂",
    "Mutated Energizing Shard": "变异的能量碎片",
    "Mutated Reinforcement": "变异强化",
    "Pierced Voicebox": "穿的喉",
    "Pincered Talon": "螯爪",
    "Platinum": "铂",
    "Poisonous Barb": "有毒的刺",
    "Precognitive Dust": "预知的尘埃",
    "Quality Energizing Shard": "质量激励碎片",
    "Quality Reinforcement": "强化质量",
    "Quantity": "数量",
    "Razen Hide": "Razen隐藏",
    "Redeeming Coin": "兑换硬币",
    "Rippling Scale": "涟漪规模",
    "Scarred Fang": "方伤痕累累",
    "Serrated Thorn": "锯齿状的刺",
    "Severed Claw": "切断了爪",
    "Shattered Larynx": "破碎的喉",
    "Shattered Shield": "破碎的盾",
    "Shimmering Spearhead": "闪闪发光的先锋",
    "Shoulder": "肩膀",
    "Slimy Tentacle": "虚伪的触须",
    "Slotted Talon": "开槽爪",
    "Spine Fragment": "脊柱的片段",
    "Spyglass": "小望远镜",
    "Standard Energizing Shard": "标准激活碎片",
    "Standard Reinforcement": "标准的强化",
    "Synthetic Tar": "合成沥青",
    "T'Chek Incisor": "特切门牙",
    "Tormented Scale": "折磨的规模",
    "Torn Shadow": "撕裂的影子",
    "Translucent Scale": "半透明的规模",
    "Unhinged Jawbone": "精神错乱的颚骨",
    "Unholy Remainder": "邪恶的剩余部分",
    "Unsorted Valuables": "未分类的贵重物品",
    "Venom Sample": "毒液样本",
    "Void Fragment": "无效的片段",
    "Volatile Dust": "挥发性粉尘",
    "Worg Claw": "狼人爪",
    "Worg Tooth": "狼人牙",
    "Refresh": "刷新",
    "Rarity": "稀有度",
    "Rare": "稀有",
    "RECENT MISSION VICTORIES": "近期任务胜利",
    "Next Attempt:": "下一次尝试：",
    "Nassul": "纳苏尔",
    "MISSIONS": "任务",
    "Modules": "模块",
    "Mission Reward": "任务奖励",
    "Maximum": "最大",
    "Research": "搜索",
    "Plasma": "等离子体",
    "RESEARCH FACILITY": "研究机构",
    "NEW BLACK INK LISTING": "新的黑色墨水清单",
    "Epic": "史诗",
    "Enemies": "敌人",
    "Distance": "距离",
    "Common": "普通",
    "Blueprints": "蓝图",
    "Faction": "派系",
    "Laser": "激光",
    "When": "当",
    "Uncommon": "罕见",
    "Unique": "独特",
    "SHIPS": "飞船",
    "Select Ship": "选择飞船",
    "Last 20 Missions": "最近20个任务",
    "Wins": "获胜",
    "Workshop": "作坊",
    "Kin of the Void": "虚空之王",
    "Andromeda Sweep": "仙女座扫",
    "Andromeda Trek": "仙女座长途跋涉",
    "Blueprint rarity chances at current distance.": "蓝图稀有几率在当前距离。",
    "Earn an Incursion Map every 7 Beyond Missions. The Distance of your map will be the average distance of your last 7 missions.": "每完成7次任务获得一张入侵地图你的地图距离将是你过去7个任务的平均距离。",
    "Edit ship modules in squadrons.": "编辑舰队中的舰船模块。",
    "FACTION STATS": "派系统计数据",
    "Filter Squadron": "过滤器中队",
    "Filter Weapon": "过滤器的武器",
    "Found exclusively in small asteroids.": "只在小行星上发现。",
    "Gain +2 attempts daily. One every 12 hours.": "每天增加2次尝试。每12小时一次。",
    "Galactic Chase": "银河追逐",
    "Go to your Workshop to assemble some starter ships.": "去你的车间组装一些初始船。",
    "Hangar": "机库",
    "How far you are from Elethor.": "你离埃莱瑟有多远。",
    "Incursion Map Progress": "入侵地图进度",
    "Kinetic": "动能",
    "Legendary": "传说",
    "Less-efficient bays give fractional Quantics. So Bay 2 at 75% efficiency will give 0.75 Quantics per hour.": "效率较低的海湾给出分数量化。所以效能为75%的Bay 2每小时输出0.75个量。",
    "Lifetime Stats": "生命周期数据",
    "Missile": "导弹",
    "Most starships cannot be constructed without this.": "没有这个，大多数星际飞船都无法建造。",
    "Research time (\"quantics\") increment every hour, on the hour.": "研究时间（“量”）每小时递增，按小时计算。",
    "Research time is never wasted. Any excess time will get applied to the next research you do in that research bay.": "研究时间从不浪费。任何多余的时间都将被应用到你在那个研究中心做的下一个研究中。",
    "Researching ships permanently increases their damage, hull, and shields. Each Mk upgrade gives +5% of base values.": "研究船只永久增加其伤害，船体和护盾。每次Mk升级给予+5%的基础值。",
    "Scarlet Brigade": "猩红兵团",
    "Show Rewards": "给奖励",
    "Squadrons": "中队",
    "Strong Defensive Reinforcements": "强大的防御援军",
    "The Scarlet Brigade believes it's the leftover material of ancient stars.": "猩红旅认为这是远古恒星的残余物质。",
    "You can still use ships that are researching!": "你仍然可以使用正在进行研究的船只！",
    "You haven't assembled any ships yet.": "你还没有组装任何船。",
    "Iridium.": "铱。",
    "Nanofiber.": "纳米纤维。",
    "Rhenium.": "铼。",
    "Tungsten.": "钨。",
    "Scraps of ship modules. Useful to improve the technology of your modules. You gain 1 Nanofiber hourly while active.": "飞船模块的残片。有助于改进模块的技术。活动时每小时获得1个纳米纤维。",
    "Fuel Refinery": "燃料提炼厂",
    "Fleet": "舰队",
    "CURRENT": "当前",
    "CONSUMED": "消耗",
    "and": "和",
    "(VIP Bonus)": "(VIP加成)",
    "VIP Only": "仅限VIP",
    "Calculate how many passive resources you gain per day at your current Exo Filter multiplier.": "计算你每天在当前的输出过滤器乘数下获得多少被动资源。",
    "Check this box to force the simulator to generate a new encounter at this distance.": "选中此框可强制模拟器在此距离生成新的遭遇战。",
    "New Encounter": "新的相遇",
    "NEXT LEVEL": "下一级",
    "Observation Bay": "观景台",
    "Omnium is converted into Fuel every 4 hours, starting at 00:00 server time.": "Omnium每4小时转换为燃料，从服务器时间00:00开始。",
    "Omnium is converted into Fuel every 4 hours, starting at 00:00 server time. If you do not have enough Omnium for the full conversion, no Fuel will be produced.": "Omnium每4小时转换为燃料，从服务器时间00:00开始。如果你没有足够的Omnium进行完全转换，就不会产生燃料。",
    "Passive Resources": "被动资源",
    "PRODUCED": "产出",
    "Shipyard": "船厂",
    "Simulate combat against random encounters at specific distances. Get a feel for the power of your squadrons!": "模拟在特定距离随机遭遇的战斗。感受一下你的中队的力量吧！",
    "Simulation Distance": "模拟的距离",
    "The Exo Filter increases your daily passive resource gain, based on your distance.": "Exo过滤器增加你的每日被动资源增益，基于你的距离。",
    "The Fleet Core increases the maximum power you can have in a single squadron.": "舰队核心增加了你在一个中队的最大力量。",
    "The Hangar increases the maximum number of ships you can have in a single squadron.": "机库增加了你在一个中队中可以拥有的最大船只数量。",
    "The Harvester increases the rewards you get from missions.": "收割机增加你从任务中获得的奖励。",
    "The Refinery increases the efficiency at which you convert Omnium into Fuel. A higher refinery rate means more fuel is produced for the same input of Omnium.": "精炼厂提高了你将Omnium转化为燃料的效率。更高的精炼率意味着相同的Omnium投入可以生产更多的燃料。",
    "The Research Bay reduces the base amount of time it takes to research a new ship tier. This applies before you spend resources to further reduce the timer.": "研究湾减少了研究一艘新船所需的基本时间。这适用于在您花费资源以进一步减少计时器之前。",
    "The Stabilizer increases how effective your resources are when contributing raw resources to ship research.": "稳定器增加了你的资源在为船舶研究贡献原始资源时的效率。",
    "The Teleporter increases the rate at which you convert Omnium into Fuel.": "传送器可以提高你将Omnium转化为燃料的速度。",
    "CC Effects": "CC 效果",
    "Defenses": "防御",
    "Damage Type": "伤害类型",
    "Damage Types": "伤害类型",
    "Chance": "几率",
    "Almost all CC Effects are cleansed every 15 ticks in combat. The exception is Corrosion. Every 15 ticks, a ship will reduce its CC effects by the \"Cleansed Stacks\" amount defined below.": "几乎所有的CC效果在战斗中每15秒被清除一次。腐蚀是例外。每隔15秒，一艘船将减少其CC效果的“已清理堆栈”的数量如下所述。",
    "Combat is handled in \"ticks\". Think of each tick like a single second passing. At certain \"tick intervals\", different things happen. For example, Kinetic weapons attack every 10 ticks, while Plasma weapons attack every 45 ticks.": "战斗是以“tick”来处理的。把每一个 tick 想象成一秒的流逝。每隔一段时间，不同的事情就会发生。例如，动能武器每 10 ticks 攻击一次，而等离子武器每 45 ticks 攻击一次。",
    "Having a CC Trigger chance of >100% means the CC effect may apply multiple times. So at 100% chance, you apply 1 stack of the effect. At 250% chance, you apply 2 stacks with a 50% chance of +1.": "CC触发几率 > 100%意味着CC效果可以多次使用。所以在100%的概率下，你应用1层效果。在250%的几率下，你使用2层，50%的几率为+1。",
    "Shields always absorb damage before Hull. Shields also regenerate a specific amount every 25 ticks. When a ship's shields are reduced to 0, they are \"broken\" and will not regenerate any more during that combat.": "护盾总是在船体之前吸收伤害。护盾每隔25秒回复一定数量的能量。当一艘船的护盾减少到0时，它们就会“破碎”，并且在战斗中不会再恢复。",
    "Sometimes it's worth doing a risky fight. Losses don't change which modules are offered, they only reduce the metal you get. If it takes 4 tries to get an important module it might be worth it. If you fail you can always use a refresh to wipe away the losses!": "有时候冒险一搏是值得的。损耗不会改变所提供的模块，它们只会减少你所获得的金属。如果需要4次尝试才能获得一个重要的模块，那么它可能是值得的。如果你失败了，你可以用刷新来抹去损失！",
    "Slow": "慢",
    "Tick Interval": "Tick间隔",
    "Weapons": "武器",
    "Kinetic Damage": "动能伤害",
    "Laser Damage": "激光伤害",
    "Plasma Damage": "等离子伤害",
    "Max": "最大",
    "Miscellaneous Tips": "杂项提示",
    "Lowest-Hull Target": "最低船体目标",
    "Shield": "护盾",
    "Quality": "质量",
    "Targeting": "目标定位",
    "Beyond takes vast amounts of gold, omni, and platinum. Depending on your income it might be wise to focus on increasing your production of these core game resources before pushing for progress in beyond.": "转生 需要大量的黄金、omni和铂金。根据你的收入情况，你最好先专注于提高这些核心游戏资源的产量，然后再推进其他内容。",
    "All CC effects apply on-hit.": "所有CC效果在命中时生效。",
    "All ships have Hull. Think of it like the ship's health. When a ship's Hull reaches 0, it is destroyed.": "所有的船都有船体。就像船的健康一样。当一艘船的船体达到0时，它就被摧毁了。",
    "Applies 1% of the damage done as Corrosion. The ship takes this damage every 15 ticks. This damage cannot be mitigated with evasion.": "造成伤害的1%为腐蚀。船每隔15秒受到此伤害。这种伤害不能通过闪避来减轻。",
    "Assemble a squadron of ships that are sufficiently powered.": "组建一支有足够动力的舰队。",
    "Attacks 5 times in rapid succession every 10 ticks. Every attack applies on-hit effects.": "每10秒快速连续攻击5次。每次攻击都有命中效果。",
    "Being further from Elethor increases your opportunity for loot, but also increases the strength of enemies.": "离Elethor更远会增加你获得战利品的机会，但也会增加敌人的力量。",
    "Build a Power Module with your Nanofiber. Click the blueprint in Hangar > Blueprints.": "用你的纳米纤维做一个电源模块。在“机库>蓝图”中单击蓝图。",
    "Build your starter ships (in the Hangar > Workshop)": "建造你的初始船（在机库>工作室）",
    "Certain rarities of blueprints can be found starting at roughly these distances:": "某些罕见的蓝图可以从以下距离开始：",
    "Cleansed": "洁净",
    "Corrosion": "腐蚀",
    "Cripple": "削弱",
    "Defeating Factions in missions gives you progress toward finding Incursion Maps for that Faction.": "在任务中击败派系会让你在寻找该派系的入侵地图上取得进展。",
    "Disrupt": "破坏",
    "Does a large amount of damage all at once.": "一次性造成大量伤害。",
    "Don't craft every module you see. Once you run out of your initial nanofiber it comes pretty slow.": "不要制作你看到的每个模块。一旦你用完最初的纳米纤维，它就会变得很慢。",
    "Each Faction has a 50% higher chance of giving you module mission rewards associated with that faction.": "每个阵营都有50%的机会给你与该阵营相关的模块任务奖励。",
    "Each stack gives a 50% chance for attacks to take 1 extra tick.": "每一层都有50%的几率使攻击时间增加1秒。",
    "Each weapon type has its own type of CC. You can get \"CC Trigger\" stat to increase the chance of applying CC effects to enemies.": "每种武器类型都有自己的CC类型，你可以获得“CC触发”属性来增加对敌人施加CC效果的几率。",
    "Each weapon type in Beyond has unique strengths and weaknesses depending on the situation. But before we break that down, let's look at the most fundamental part of combat -- ticks.": "《Beyond》中的每种武器类型都有独特的优势和劣势，这取决于具体情况。但在此之前，让我们先看看战斗的最基本部分——滴答声。",
    "Equip your new Power Module to your ship. Click your Ship in the Hangar, click the Power Module slot, and equip your module.": "为你的飞船装备新的动力模块。在机库点击你的飞船，点击电源模块插槽，装备你的模块。",
    "Evasion": "逃避",
    "Evasion gives a ship a percentage chance to avoid a hit. Please note that because Kinetic weapons attack 5 times in rapid succession, each hit must be evaded separately.": "闪避使船有一定的几率避免命中。请注意，因为动能武器连续攻击5次，所以每次攻击都必须单独躲避。",
    "Extra power does nothing. There is no reason to upgrade power cores and fleet core beyond what is needed to power your ships and fleets.": "额外的能量没有任何作用。没有理由升级动力核心和舰队核心，除非是为了给你的飞船和舰队提供动力。",
    "Factions": "派系",
    "Factions in Beyond are important for a few reasons.": "《Beyond》中的派系之所以重要，有几个原因。",
    "Focuses down and finishes off low-hull ships.": "专注并完成低船体的船只。",
    "For each successful evasion, your ship's evasion is reduced by 20% of current (this is multiplicative). Whenever it takes a hit, the evasion is reset back to the maximum.": "每成功闪避一次，你的船的闪避减少20%的电流（这是乘法）。当它受到攻击时，闪避被重置为最大值。",
    "Get some Power Module Blueprints (Hangar > Blueprints > Get Power Blueprint). Power Module Blueprints are free!": "获取一些电源模块蓝图（机库>蓝图>获取电源蓝图）。电源模块图纸免费！",
    "Harvest and Exo Filter are expensive long term purchases. They probably aren't worth it until you travel far enough to have a good base resource income.": "收割和Exo过滤器是昂贵的长期购买。在你旅行到足够远的地方获得良好的基础资源收入之前，它们可能并不值得你这么做。",
    "Hull": "船体",
    "If multiple weapons are ready to attack at the same time, the attacker will always attack first.": "如果多个武器同时准备攻击，攻击者总是先攻击。",
    "If you are upgrading a module from one rarity to a higher rarity, you only pay the difference in Nanofiber.": "如果您要将一个模块从一种稀缺性升级到更高的稀缺性，则只需支付Nanofiber的差异。",
    "If you lose the random encounter, you won't move forward and 80% of the fuel cost will be refunded.": "如果你输掉了随机遭遇战，你将无法继续前进，80%的燃料费用将被退还。",
    "Initial Distance": "最初的距离",
    "Missile Damage": "导弹的伤害",
    "Module Quality": "模块质量",
    "Module quality is broken down into 6 categories:": "模块质量分为6类：",
    "Module quality is randomly determined when generating a Blueprint. These are the rough chances you have of getting each type of quality.": "模块质量是在生成蓝图时随机确定的。这些是你获得每种质量的粗略机会。",
    "Module Rarity": "模块罕见",
    "Module rarity is broken down into 6 categories:": "模块稀缺性分为6类：",
    "Nanofiber Cost": "纳米纤维成本",
    "Nanofiber Upgrade Cost": "纳米纤维升级成本",
    "Need some Nanofiber? Buy it in the Star Smuggler Shop (Market > Shop > Star Smuggler)": "需要一些纳米纤维吗？在星际走私者商店购买（市场>商店>星际走私者）",
    "No Squadrons?": "没有中队吗?",
    "Once you start getting higher tier modules, it's worth considering getting modules to recycle them just for the nanofiber.": "一旦你开始获得更高层次的模块，就值得考虑回收这些模块，只为了纳米纤维。",
    "Pick up to 6 random targets and attacks each of them once.": "捡起6个随机目标，攻击每个目标一次。",
    "Random Target": "随机目标",
    "Reduces the damage of the ship's attacks by 1.25% per stack.": "每层降低战舰的攻击伤害1.25%。",
    "Set your Refinery Conversion to start producing Fuel.": "设置你的炼油厂转换开始生产燃料。",
    "Ship levels are extremely important. If you find yourself not using a beyond resource very much you should use it to stabilize.": "船的水平是非常重要的。如果你发现自己不经常使用超出资源，你应该使用它来稳定。",
    "Specialty": "专业",
    "Stacks": "栈",
    "Starter squads can typically handle distance 35. But have little chance past distance 50.": "首发阵容通常可以处理35英里的距离。但超过50英里的几率很小。",
    "Starting Tips": "开始提示",
    "Take on a mission 😄": "接受任务😄",
    "Teleporter is extremely important, especially at early levels.": "传送是非常重要的，特别是在早期关卡。",
    "Tertiary modules are the most powerful modules in the game. But they take a lot of power. And most ships focused on tertiary modules have very weak offense (and sometimes defense).": "第三模块是游戏中最强大的模块。但它们需要很大的能量。大多数专注于第三模块的飞船都有非常弱的进攻（有时是防御）。",
    "The Patrol/Cussion combo is good at fighting multiple ships. The Cussion/Assassin combo is good at fighting few strong ships.": "巡逻/攻击组合擅长对抗多艘船。卡森/刺客组合很擅长对付一些强大的船。",
    "The ship takes 5% per stack more damage from all attacks.": "船每层受到的所有攻击伤害增加5%。",
    "There are key defensive stats that almost all ships have. This increases the survivability of ships.": "几乎所有船只都有一些关键的防御属性。这增加了舰船的生存能力。",
    "Traveling from 1 to 1 distance will cost you": "从1到1的距离将花费你",
    "Upgrading Modules": "升级模块",
    "Upgrading modules of the same rarity to a higher quality only costs the Blueprint.": "将同样稀有的模块升级到更高的质量只需要消耗蓝图。",
    "Upgrading modules to a higher rarity always costs Nanofiber.": "将模块升级到更高的稀缺性总是要花费纳米纤维。",
    "Useful Starting Tips": "有用的入门技巧",
    "When you travel to a further distance, you will need to defeat a random encounter to stay at that distance.": "当你旅行到更远的距离时，你将需要击败一个随机遭遇战来保持那个距离。",
    "You almost always want to be at the maximum distance you can handle.": "你总是想要保持在你能承受的最大距离上。",
    "You are currently at distance 1.": "你现在的距离是1。",
    "You can earn higher-rarity modules as you venture further into space. The quality of modules you can get is randomized.": "当你在太空中探险时，你可以获得更稀有的模块。你可以得到的模块的质量是随机的。",
    "You craft modules using Blueprints and Nanofiber. You can also upgrade existing modules using Blueprints.": "你用蓝图和纳米纤维制作模块。您还可以使用蓝图升级现有模块。",
    "You earn modules by completing missions and defeating enemies. Modules can be used to upgrade your ships and starbase.": "你通过完成任务和击败敌人来获得模块。模块可以用来升级你的飞船和基地。",
    "You must use Blueprints to upgrade modules.": "升级模块必须使用蓝图。",
    "You need to do a bit of setup to get your starter ships ready for prime time.": "你需要做一些设置，让你的首发船为黄金时间做好准备。",
    "You will be spending a lot of resources on your fleet core and power cores as you get stronger, plan ahead.": "当你变得更强大时，你将在你的舰队核心和动力核心上花费大量资源，提前计划。",
    "Your first strategic choice will come early. Do you want a bigger squadron with weaker modules? Or a smaller squadron with strong modules. Both are viable.": "你的第一个战略选择将会提前到来。你想要一个更大的中队和更弱的模块吗？或者是一个拥有强大模块的小型中队。两者都是可行的。",
    "Exp / Sec": "经验值 / 秒",
    "Started gathering Omnium": "开始采集Omnium",
    "Switching to gathering from Razor Den...": "切换到 剃刀巢穴 进行采集…",
    "You aren't gathering anything.": "你没有采集任何东西。",
    "ABILITIES": "能力",
    "BASE": "基础",
    "CACHE FINDER": "缓存探测器",
    "EXCAVATION": "挖掘",
    "GEODATA DETECTION": "地质数据检测",
    "MOMENTUM": "动量",
    "OMNIFIER": "万能机",
    "ORE": "矿石",
    "PASSIVES": "被动",
    "PURITY": "纯度",
    "PROSPECTOR": "勘探者",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Ticks": "Ticks",
    "CC": "CC",
    "for": "对",
    // 怪物
    "Rat": "老鼠",
    "Large Rat": "大鼠",
    "Azure Giant": "蔚蓝巨人",
    "Crimson Giant": "深红巨人",
    "Ore Snatcher": "矿石掠夺者",
    "Sailfin": "赛芬",
    "Skrivet": "小鹰",
    "Pelt Grifter": "毛皮骗子",
    "Lava Worm": "熔岩虫",
    "Tormented Serpent": "折磨之蛇",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "DR": "DR",
    "ELETHOR": "ELETHOR",
    "May": "5月",

    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    "Gityx": "Gityx",
    "Gz": "Gz",
    "O": "O",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "The highest Mastery exp is currently ": "目前最高的精通经验是 ",
    "I: -": "I: -",
    "II: -": "II: -",
    "III: -": "III: -",
    "IV: -": "IV: -",
    "V: -": "V: -",
    "I: +": "I: +",
    "II: +": "II: +",
    "III: +": "III: +",
    "IV: +": "IV: +",
    "V: +": "V: +",
    "Unlock for ": "解锁成本 ",
    "I: ": "I: ",
    "II: ": "II: ",
    "III: ": "III: ",
    "IV: ": "IV: ",
    "V: ": "V: ",
    "Successfully unlocked ": "成功解锁了 ",
    "Mining (": "采矿 (",
    "Wealthy (": "富有 (",
    "Combat (": "战斗 (",
    "Zoology (": "动物学 (",
    "Prevail (": "获胜 (",
    "Fossilized (": "石化 (",
    "Petrification (": "僵化 (",
    "Multitasking (": "多任务处理 (",
    "Omnomnomnode (": "Omnomnom节点 (",
    "Limitless (": "无限 (",
    "Scavenger (": "清道夫 (",
    "The Whole Buffalo (": "整头水牛 (",
    "Skilled Weaponry (": "熟练武器 (",
    "Skilled Extraction (": "熟练提取 (",
    "% Armor ": "% 护甲 ",
    "% Health ": "% 生命值 ",
    "% Max Damage ": "% 最大伤害 ",
    "Famous ": "卓越的",
    "Base: ": "基础: ",
    "Unlocks at Lv": "解锁于等级 ",
    "Unlocked at DRAKE Lv": "解锁于 德雷克 等级 ",
    "Unlocked at DRONE Lv": "解锁于 德罗纳 等级 ",
    "Unlocked at MERCHANT Lv": "解锁于 商人 等级 ",
    "Unlocked at PROSPECTOR Lv": "解锁于 勘探者 等级 ",
    "(Lv": "(等级",
    "Next Capacity: ": "下一容量: ",
    "Current Capacity: ": "当前容量: ",
    "Next Multiplier: ": "下一乘数: ",
    "Current Multiplier: ": "当前乘数: ",
    "Next Power Limit: ": "下一动力上限: ",
    "Current Power Limit: ": "当前动力上限: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " Points": " 点数",
    " SPENT POINTS": " 花费点数",
    " I": " I",
    " II": " II",
    " III": " III",
    " IV": " IV",
    " V": " V",
    " VI": " VI",
    " Attempts": " 尝试",
    " ore multiplier per level.": "矿石乘数每级。",
    " base ore per level.": "基础矿石每级。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+)x\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^(.+) \-\> (.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) Ticks$/,
    /^T([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You decimated (.+) Rat!$/, '你击杀了 $1 老鼠!'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Gathered (.+) Omnium$/, '收集 $1 Omnium'],
    [/^(.+) \/ (.+) to Lv(.+)$/, '$1 \/ $2 到 等级$3'],
    [/^Nov ([\d\.,]+) ([\d\.,]+):([\d\.,]+) pm$/, '11月$1日 下午 $2:$3'],
    [/^Nov ([\d\.,]+) ([\d\.,]+):([\d\.,]+) am$/, '11月$1日 上午 $2:$3'],
    [/^(.+) drop rate per level.$/, '$1 掉率 每级.'],
    [/^(.+) contributions to next level.$/, '$1 贡献 到下一级。'],
    [/^Gain (.+) Armor per whichever is lower between your Fame level and Combat level.$/, '声誉等级与战斗等级之间以低者为单位, 护甲 $1。'],
    [/^Gain (.+) Fortitude per whichever is lower between your Fame level and Combat level.$/, '声誉等级与战斗等级之间以低者为单位, 坚韧 $1。'],
    [/^Gain (.+) Pierce per whichever is lower between your Fame level and Combat level.$/, '声誉等级与战斗等级之间以低者为单位, 穿刺 $1。'],
    [/^Gain (.+) Savagery per whichever is lower between your Fame level and Combat level.$/, '声誉等级与战斗等级之间以低者为单位, 野蛮 $1。'],
    [/^Gain (.+) Savagery per level.$/, '每级增加 $1 野蛮.'],
    [/^Gain (.+) Damage Reduction per level.$/, '每级增加 $1 伤害减免.'],
    [/^Gain (.+) Fortitude per level.$/, '每级增加 $1 坚韧.'],
    [/^Gain (.+) Pierce per level.$/, '每级增加 $1 穿刺.'],
    [/^Gain (.+) Min Damage per level.$/, '每级增加 $1 最低伤害.'],
    [/^Gain (.+) Max Damage per level.$/, '每级增加 $1 最高伤害.'],
    [/^Gain (.+) Damage per level.$/, '每级增加 $1 伤害.'],
    [/^Gain (.+) Health Multiplier per level.$/, '每级增加 $1 生命值乘数.'],
    [/^Gain (.+) Armor per level.$/, '每级增加 $1 护甲.'],
    [/^Gain (.+) Armor per Combat level.$/, '每级战斗增加 $1 护甲.'],
    [/^Gain (.+) Pierce per Combat level.$/, '每级战斗增加 $1 穿刺.'],
    [/^Gain (.+) Savagery per Combat level.$/, '每级战斗增加 $1 野蛮.'],
    [/^Gain (.+) Fortitude per Combat level.$/, '每级战斗增加 $1 坚韧.'],
    [/^Earn (.+) Data Chip automatically every hour.$/, '每小时自动获得 $1 数据芯片'],
    [/^Sep ([\d\.,]+) ([\d\.,]+):([\d\.,]+) am$/, '9月 $1 上午午 $2:$3'],
    [/^Sep ([\d\.,]+) ([\d\.,]+):([\d\.,]+) pm$/, '9月 $1 下午 $2:$3'],
    [/^Killed (.+) over (.+) actions.$/, '击杀 $1 花费了 $2 行动。'],
    [/^If you have less than (.+), you will get (.+) exp.$/, '如果少于 $1 ，你将获得 $2 的经验。'],
    [/^If you have (.+) of the highest Mastery exp, you will get (.+) exp per chip.$/, '如果你有 $1 的最高精通经验，你将获得 $2 经验每个芯片。'],
    [/^If you have (.+), you will get (.+) exp.$/, '如果你拥有 $1，你将获得 $2 经验值。'],
    [/^Data Chips give a default of (.+) exp.$/, '数据芯片默认 $1 经验值。'],
    [/^You have (.+) kills required for Rank (.+).$/, '等级 $2 需要 $1 击杀。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)x Multi$/, '$1x 乘数'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) online$/, '$1 在线'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Lv([\d\.,]+)$/, '等级 $1'],
    [/^Lv([\d\.,]+) \% Armor$/, '等级$1 \% 护甲'],
    [/^Lv([\d\.,]+) \% Damage$/, '等级$1 \% 伤害'],
    [/^Lv([\d\.,]+) \% Max Damage$/, '等级$1 \% 最大伤害'],
    [/^Lv([\d\.,]+) \% Min Damage$/, '等级$1 \% 最小伤害'],
    [/^Lv([\d\.,]+) \% Pierce$/, '等级$1 \% 穿刺'],
    [/^Lv([\d\.,]+) \% Savagery$/, '等级$1 \% 野蛮'],
    [/^Lv([\d\.,]+) \% Fortitude$/, '等级$1 \% 坚韧'],
    [/^Lv([\d\.,]+) \% Health$/, '等级$1 \% 生命值'],
    [/^Lv([\d\.,]+) Scaling \% Armor$/, '等级$1 缩放 \% 护甲'],
    [/^Lv([\d\.,]+) Scaling \% Fortitude$/, '等级$1 缩放 \% 坚韧'],
    [/^Lv([\d\.,]+) Scaling \% Pierce$/, '等级$1 缩放 \% 穿刺'],
    [/^Lv([\d\.,]+) Scaling \% Savagery$/, '等级$1 缩放 \% 野蛮'],
    [/^Lv([\d\.,]+) Pierce$/, '等级$1 穿刺'],
    [/^Lv([\d\.,]+) Scaling Pierce$/, '等级$1 缩放穿刺'],
    [/^Lv([\d\.,]+) Fortitude$/, '等级$1 坚韧'],
    [/^Lv([\d\.,]+) Scaling Fortitude$/, '等级$1 缩放坚韧'],
    [/^Lv([\d\.,]+) Savagery$/, '等级$1 野蛮'],
    [/^Lv([\d\.,]+) Scaling Savagery$/, '等级$1 缩放野蛮'],
    [/^Lv([\d\.,]+) Teleporter$/, '等级$1 传送器'],
    [/^Lv([\d\.,]+) Stabilizer$/, '等级$1 稳定器'],
    [/^Lv([\d\.,]+) Research Bay$/, '等级$1 研究舱'],
    [/^Lv([\d\.,]+) Fleet Core$/, '等级$1 舰队核心'],
    [/^Lv([\d\.,]+) Exo Filter$/, '等级$1 挂式过滤器'],
    [/^Lv([\d\.,]+) Harvester$/, '等级$1 收割机'],
    [/^Lv([\d\.,]+) Refinery$/, '等级$1 炼油厂'],
    [/^Lv([\d\.,]+) Hangar$/, '等级$1 机库'],
    [/^Lv([\d\.,]+) Armor$/, '等级$1 护甲'],
    [/^Lv([\d\.,]+) Scaling Armor$/, '等级$1 缩放护甲'],
    [/^\+([\d\.,]+)\% Lootcap$/, '\+$1\% 战利品上限'],
    [/^\+([\d\.,]+)\% Gold$/, '\+$1\% 黄金'],
    [/^\+([\d\.,]+)\% Health$/, '\+$1\% 生命值'],
    [/^\+([\d\.,]+)\% Combat Exp$/, '\+$1\% 战斗经验'],
    [/^\+([\d\.,]+)\% Multikill Debuff$/, '\+$1\% 多杀减益'],
    [/^\+([\d\.,]+) ARMOR$/, '\+$1 护甲'],
    [/^\+([\d\.,]+) SAVAGERY$/, '\+$1 野蛮'],
    [/^\+([\d\.,]+) Max Levels$/, '\+$1 最高等级'],
    [/^\+([\d\.,]+) SPEED$/, '\+$1 野蛮'],
    [/^\+([\d\.,]+) PIERCE$/, '\+$1 穿刺'],
    [/^\+([\d\.,]+) Data Chip every hour.$/, '每小时 \+$1 数据芯片。'],
    [/^\+([\d\.,]+) for ([\d\.,]+)$/, '每小时 \+$1 花费 $2'],
    [/^([\d\.,]+) DISTANCE$/, '$1 距离'],
    [/^\(([\d\.,]+) total\)$/, '(总计 $1)'],
    [/^Lv([\d\.,]+) Stasis Injection$/, '等级$1 停滞注射'],
    [/^Puncture ([\d\.,]+) Essence$/, '穿刺 $1 精华'],
    [/^You are currently at ([\d\.,]+) Distance.$/, '你现在的距离是 $1。'],
    [/^([\d\.,]+) Random Targets$/, '$1 随机目标'],
    [/^([\d\.,]+) Exp$/, '$1 经验值'],
    [/^([\d\.,]+) Gold$/, '$1 黄金'],
    [/^([\d\.,]+) exp$/, '$1 经验值'],
    [/^([\d\.,]+) Distance$/, '$1 距离'],
    [/^([\d\.,]+) Total$/, '总计 $1'],
    [/^([\d\.,]+) Action$/, '$1 行动'],
    [/^([\d\.,]+) Actions$/, '$1 行动'],
    [/^([\d\.,]+) per (.+) kills$/, '$1 每 $2 击杀'],
    [/^([\d\.,]+)x Fatigue Timer$/, '$1x 疲劳计时器'],
    [/^([\d\.,]+)\% drop chance$/, '$1\% 掉落几率'],
    [/^([\d\.,]+)\% drop rate$/, '$1\% 掉率'],
    [/^([\d\.,]+)\% Ore$/, '$1\% 矿石'],
    [/^([\d\.,]+)\% Total Effectiveness$/, '$1\% 总效率'],
    [/^([\d\.,]+)\% Effect$/, '$1\% 效果'],
    [/^([\d\.,]+)\% Omnium$/, '$1\% Omnium'],
    [/^([\d\.,]+)\% Dust$/, '$1\% 尘埃'],
    [/^([\d\.,]+)\% Multiplier$/, '$1\% 乘数'],
    [/^([\d\.,]+)\% exp$/, '$1\% 经验值'],
    [/^([\d\.,]+)\% Chance$/, '$1\% 几率'],
    [/^([\d\.,]+)\% Reduction$/, '$1\% 减益'],
    [/^([\d\.,]+)\% chance$/, '$1\% 几率'],
    [/^([\d\.,]+)\% Difficulty$/, '$1\% 难度'],
    [/^([\d\.,]+)\% Efficiency$/, '$1\% 效率'],
    [/^([\d\.,]+)\% Reward$/, '$1\% 奖励'],
    [/^([\d\.,]+)\% Conversion$/, '$1\% 转化'],
    [/^([\d\.]+) Reactor Core$/, '$1 反应堆核心'],
    [/^([\d\.]+)\% Purity$/, '$1\% 纯度'],
    [/^\-([\d\.]+)\% Reward$/, '\-$1\% 奖励'],
    [/^\+([\d\.]+)\% purity per level.$/, '每级 \+$1\% 纯度。'],
    [/^Last ([\d\.,]+) Days$/, '持续 $1 天'],
    [/^to Lv([\d\.,]+)$/, '到等级 $1'],
    [/^Refresh Lv([\d\.,]+)$/, '刷新等级 $1'],
    [/^Bay ([\d\.,]+)$/, '舱 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^([\d\.,]+) Available Research Bays$/, '$1 可用的研究舱'],
    [/^T([\d\.,]+) Scrap$/, 'T$1 废料'],
    [/^x([\d\.,]+) Used$/, 'x$1 已使用'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                            transTaskMgr.doTask();
                        }
                    }
                }
            }
        }
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();