// ==UserScript==
// @name         Endless 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.60
// @description  网页游戏 Endless (https://dev.ghost-team.top/endless/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Endless.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://dev.ghost-team.top/favicon.ico
// @license      MIT
// @include      https://www.ghost-team.top/endless
// @include     *https://endless.ghost-team.top/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/endless-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/endless-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/06/13 17:19
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten": "获得里程碑",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Email": "邮箱",
    "Feedback": "反馈",
    "Games": "游戏",
    "Login": "登录",
    "Logout": "登出",
    "Password": "密码",
    "Register": "注册",
    "Don't have an account?": "还没有账号？",
    "About": "关于",
    "Confirm Password": "确认密码",
    "Name": "用户名",
    "Already have an account?": "已经有账号了？",
    "admin": "管理员",
    "Comments": "评论",
    "Endless": "无尽的RPG",
    "Featured Games": "推荐游戏",
    "Game ID: 2": "游戏ID: 2",
    "Game not found.": "游戏未找到。",
    "Jun 6, 04:02 AM": "6月6日04:02 AM",
    "Loading comments...": "加载评论...",
    "Loading game details...": "加载游戏细节...",
    "Loading games...": "加载游戏...",
    "Logging in...": "登录...",
    "No comments yet. Be the first to comment": "目前还没有评论。第一个发表评论吧",
    "Play Now": "立即开始",
    "Post": "帖子",
    "The best game you will ever encounter": "这是你遇到过的最棒的游戏",
    "Welcome": "欢迎",
    "Elemental Damage": "元素伤害",
    "EXP:": "经验值:",
    "Explore": "探索",
    "MAX": "最大",
    "Misc": "其它",
    "Quests": "任务",
    "Open Building Map": "打开建筑地图",
    "MISS": "未命中",
    "Offense": "进攻",
    "Rarity": "稀有度",
    "Rogue": "流氓",
    "Reset Attributes": "重置属性",
    "Reset All Progress": "重置所有进度",
    "Resources": "资源",
    "Stats": "属性",
    "Total Cost:": "总成本:",
    "Total Total Cost::": "总加成:",
    "Stop": "停止",
    "Normal Items": "普通物品",
    "Vampire": "吸血鬼",
    "Training": "训练",
    "Skill Tree": "技能树",
    "Soul Shop": "灵魂商店",
    "Saving...": "保存中...",
    "Salvage Item": "回收物品",
    "Salvage": "回收",
    "Progress:": "进度:",
    "First Blood": "第一滴血",
    "Gold (": "金币 (",
    "Gold bonus:": "金币加成:",
    "Highest Stage:": "最高关卡:",
    "Infinite Void": "无限虚空",
    "Inventory": "背包",
    "Items": "物品",
    "Kills": "击杀",
    "Level:": "等级:",
    "Life": "生命值",
    "Life Steal": "生命偷取",
    "Load from Cloud": "加载云存档",
    "Mana": "法力",
    "Mana Per Hit": "法力每击",
    "Massacre": "大屠杀",
    "Materials": "材料",
    "Max": "最大",
    "Mythic Items & Below": "神话物品及以下",
    "Magic Items & Below": "魔法物品及以下",
    "Rare Items & Below": "稀有物品及以下",
    "Auto Spell Cast": "自动施放法术",
    "先驱者": "战斗",
    "Harbinger": "先驱者",
    "Checking login...": "检查登录...",
    "Extra Life": "额外生命值",
    "Extra Material Drop %": "额外材料掉落 %",
    "Fight": "战斗",
    "Elementalist": "元素使",
    "Defense": "防御",
    "Crystal Cave": "水晶洞穴",
    "Crystal Shop": "水晶商店",
    "Current Level:": "当前等级:",
    "Arena": "竞技场",
    "Cloud Save Info:": "云存档信息:",
    "Buy": "购买",
    "Are you sure you want to overwrite your local save with this cloud save? This cannot be undone.": "您确定要用此云存档覆盖本地保存吗？这是无法挽回的。",
    "Total Bonus:": "总加成:",
    "Unlock Level:": "解锁等级:",
    "Universal Threat": "宇宙威胁",
    "Unique Items & Below": "独特物品及以下",
    "Warrior": "战士",
    "World Ender": "世界末日",
    "Save to Cloud": "保存到云存储",
    "Reset Skill Tree": "重置技能树",
    "Join our Discord": "加入我们的 Discord",
    "Extinction Event": "灭绝事件",
    "Holy warrior specializing in defense and vitality": "圣战士，专攻防御和活力",
    "Legendary Items & Below": "传说物品及以下",
    "Enchanted Forest": "魔法森林",
    "Swift and deadly, focusing on critical hits and attack speed": "迅速而致命，专注于暴击和攻击速度",
    "Progression": "进度",
    "Reality Breaker": "现实破坏者",
    "Reset Arena Level": "重置竞技场等级",
    "Next Level Bonus:": "下一级加成:",
    "Bonus Skill Points": "奖励技能点",
    " multiplier on critical hits.": " 乘数当暴击时。",
    "Cosmic Terror": "宇宙恐怖",
    "Destroyer": "破坏者",
    "Element Strengths:": "元素力量:",
    "Effectiveness against enemy elements:": "对敌方元素的效果: ",
    "Death Incarnate": "死亡化身",
    "Frenzied fighter focusing on raw damage output": "狂热战士专注于原始伤害输出",
    "Master of elemental damage types": "精通元素伤害类型",
    "Master of life-stealing and critical strikes": "精通窃取生命和致命一击",
    "Material Drop bonus:": "材料掉落加成:",
    "No buildings constructed yet.": "暂无已建造的建筑物。",
    "Paladin": "圣骑士",
    "Percentage of damage dealt recovered as life.": "造成伤害的百分比恢复为生命。",
    "Refund all allocated attribute points": "退还所有已经分配的属性点",
    "Refund all skill points and reset path": "退还所有技能点并重置职业路径",
    "🌍 Mossback": "🌍 苔藓虫",
    "A mighty warrior specializing in heavy armor and raw strength": "精于重甲和原始力量的强大战士",
    "A shimmering cave filled with crystalized rocks.": "充满结晶岩石的闪闪发光的洞穴。",
    "Apocalypse": "启示录",
    "Auto-continue after death": "死亡后自动继续",
    "Automatically casts instant and buff skills": "自动施放即时和Buff技能",
    "Berserker": "狂战士",
    "Continuous Play": "自动推进",
    "Current Bonuses:": "当前加成：",
    "Gain 1 resurrection per run": "每轮获得1点复活",
    "☁️ Sylvan Wisp": "☁️ 森林精灵",
    "🌍 Thornling": "🌍 荆棘",
    "Drag and drop an item here to salvage it.": "拖放一个物品到这里回收它。",
    "Sort materials": "材料排序",
    "Sorted materials by quantity, then id": "先按数量分类，再按编号分类",
    "☁️ Air → 🌍 Earth": "☁️ 气 → 🌍 土",
    "❄️ Cold → 🔥 Fire": "❄️ 冰 → 🔥 火",
    "🌍 Earth → ❄️ Cold": "🌍 土 → ❄️ 冰",
    "🔥 Fire → ☁️ Air": "🔥 火 → ☁️ 气",
    "🔥 Wildfire Spirit": "🔥 野火精灵",
    "Amount of life recovered per second.": "每秒恢复的生命量。",
    "Amount of mana recovered per second.": "每秒恢复的法力值。",
    "Are you sure you want to change to arena? That will reset your stage progress and will find you a new enemy": "你确定要换到竞技场吗？这将重置你的关卡进度，并为你找到一个新的敌人",
    "Base physical damage dealt to enemies.": "对敌人造成的基础物理伤害。",
    "Chance to block incoming attacks.": "有几率格挡来袭攻击。",
    "Chance to deal critical damage.": "有几率造成致命伤害。",
    "Critical Strike Chance": "暴击几率",
    "Critical Strike Damage": "暴击伤害",
    "Determines hit chance against enemies.": "决定对敌人的命中几率。",
    "Each point increases:": "每点增加：",
    "Effectiveness decreases in higher stages.": "在更高的关卡，效果会降低。",
    "Higher stages require more Attack Rating.": "更高的关卡需要更高的攻击等级。",
    "Increased by Strength and equipment.": "由力量和装备增加。",
    "Increased by Vitality and level ups.": "由活力和等级增加。",
    "Increased by Wisdom and level ups.": "由智慧和等级增加。",
    "Maximum life points.": "最大生命值。",
    "Maximum mana points.": "最大法力值。",
    "Number of attacks per second.": "每秒攻击次数。",
    "Reduces incoming damage.": "减少传入的伤害。",
    "🌍 Barkhide": "🌍 树皮怪",
    "Crystals": "水晶",
    "Souls": "灵魂",
    "Souls (": "灵魂 (",
    "Crystals (": "水晶 (",
    "Cost:": "成本:",
    "Claimed": "已领取",
    "Claim Reward": "领取奖励",
    "CritDamage": "暴击伤害",
    "CritChance": "暴击几率",
    "FireDamage": "火系伤害",
    "AirDamage": "气系伤害",
    "ColdDamage": "冰系伤害",
    "BlockChance": "格挡几率",
    "AttackSpeed": "攻击速度",
    "AttackRating": "攻击准确率",
    "LifeSteal": "生命偷取",
    "LifeRegen": "生命回复",
    "ManaRegen": "法力回复",
    "Reach level 10 to select a class path": "达到10级可选择职业路径",
    "A mystical forest teeming with elemental creatures.": "一个充满自然生物的神秘森林。",
    "Explorer": "探险家",
    "First Steps": "第一步",
    "Experienced Fighter": "经验丰富的战士",
    "Master Hero": "英雄大师",
    "Midas Touch": "点石成金",
    "Millionaire": "百万富翁",
    "Pathfinder": "开拓者",
    "Reward:": "奖励:",
    "Rookie": "新手",
    "Voyager": "远航者",
    "Wanderer": "流浪者",
    "Ascended One": "转生一",
    "Big Hit": "大受打击",
    "Cataclysmic Blow": "灾难性的打击",
    "Category: Kills": "类别：击杀",
    "Category: Progression": "类别：进度",
    "Crystal Collector": "水晶收藏家",
    "Crystal Emperor": "水晶皇帝",
    "Crystal God": "水晶神",
    "Crystal Hoarder": "水晶囤积者",
    "Crystal Master": "水晶大师",
    "Crystal Merchant": "水晶商人",
    "Crystal Seeker": "寻晶者",
    "Devastating Strike": "毁灭性打击",
    "Dimensional Walker": "次元行者",
    "EarthDamage": "土系伤害",
    "Elite Champion": "精英冠军",
    "Epic Annihilator": "史诗歼灭者",
    "Epic Bane": "史诗之祸",
    "Epic Destroyer": "史诗破坏者",
    "Epic Slayer": "史诗杀手",
    "Epic Vanquisher": "史诗征服者",
    "Gold Baron": "黄金男爵",
    "Gold Hoarder": "黄金囤积者",
    "Golden Emperor": "黄金皇帝",
    "Infinite Wealth": "无限财富",
    "Legendary Being": "传说之人",
    "Legendary Conqueror": "传说征服者",
    "Legendary Destroyer": "传说破坏者",
    "Legendary Hunter": "传说猎人",
    "Legendary Nightmare": "传说噩梦",
    "Legendary Slayer": "传说杀手",
    "Mythic Apocalypse": "神话天启",
    "Mythic Bane": "神话克星",
    "Mythic Destroyer": "神话破坏者",
    "Mythic Hunter": "神话猎人",
    "Mythic Slayer": "神秘杀手",
    "Need 10 crystals for this upgrade": "这次升级需要10颗水晶",
    "Novice Adventurer": "新手冒险家",
    "Pocket Change": "零花钱",
    "Rare Apocalypse": "稀有天启",
    "Rare Exterminator": "稀有灭虫者",
    "Rare Hunter": "稀有猎人",
    "Rare Nemesis": "稀有克星",
    "Rare Specialist": "稀有专家",
    "Reality Hopper": "现实跳跃者",
    "Reality Shattering": "打破现实",
    "Rich Merchant": "富有的商人",
    "Seasoned Hero": "经验丰富的英雄",
    "Small Fortune": "小财富",
    "Transcendent": "超凡脱俗",
    "Treasure God": "宝神",
    "Treasure Tycoon": "宝藏大亨",
    "Veteran Warrior": "经验丰富的战士",
    "Wealthy Adventurer": "富有的冒险家",
    "World Traveler": "环球旅行家",
    "BLOCKED": "格挡",
    "Earned from killing monsters.": "通过杀死怪物获得。",
    "Not enough souls": "没有足够的灵魂",
    "Gold": "金币",
    "Category: Rarity": "类别: 稀有度",
    "Category: Resources": "类别: 资源",
    "Not enough souls": "没有足够的灵魂",
    "Used to buy upgrades.": "用于购买升级。",
    "Rare currency for powerful upgrades and skill resets.": "用于强大升级和技能重置的稀有货币。",
    "Not logged in": "未登录",
    "Log in": "登录",
    "Purchased": "已购买",
    "Choose Path": "选择此职业道路",
    "Current Effects:": "当前效果:",
    "Choose Path": "选择路径",
    "Effects": "影响",
    "Next Level Effects:": "下一级效果：",
    "Permanently increases armor": "永久增加护甲",
    "Skill Point Cost:": "技能点成本：",
    "While active, increases damage but costs mana per attack": "激活时，增加伤害，但每次攻击消耗法力值",
    "Slot Display Settings": "槽位显示设置",
    "TOGGLE": "切换",
    "and cannot be undone.": "而且无法撤销。",
    "Are you sure you want to reset all allocated attribute points?": "您确定要重置所有分配的属性点吗？",
    "Are you sure you want to reset your boss level to 1?": "你确定要将你的Boss等级重置为1吗？",
    "This will cost": "这将花费",
    "Are you sure you want to reset your class and refund all skill points?": "你确定要重置你的职业并退还所有技能点吗？",
    "A quick dance from the shadows, increasing your damage.": "从暗影中快速起舞，增加你的伤害。",
    "Additionally, when blocking, you also recover life equal to 5% of your maximum life.": "另外，格挡时，你还能恢复相当于你最大生命值5%的生命值。",
    "Class has been reset and all points refunded.": "等级已重置，所有分数已退还。",
    "Evasion": "闪避",
    "Increases armor and block chance.": "增加护甲和格挡几率。",
    "Shadow Dance": "影之舞",
    "Cancel": "取消",
    "Crystalized Rock": "结晶岩石",
    "Grants 1000 experience when used.": "使用时给予1000经验值。",
    "Large Gold Coins": "大金币",
    "Medium Gold Coins": "中金币",
    "Enormous Gold Coins": "巨金币",
    "Potion of Strength": "力量药水",
    "Potion of Wisdom": "智慧药水",
    "Quantity:": "数量:",
    "RARE RING": "稀有戒指",
    "Use": "使用",
    "Frozen Tundra": "冰冻苔原",
    "Increases agility by 1.": "增加1点敏捷",
    "Increases endurance by 1.": "增加1点耐力。",
    "Sort items by rarity then level": "根据稀有性和等级排序物品",
    "A land of ice and snow, home to cold and air enemies.": "冰雪之地，是寒冷和空中敌人的家园。",
    "XP bonus:": "经验加成:",
    "🌍 Shardling": "🌍 碎片",
    "🌍 Gem Guardian": "🌍 宝石守护者",
    "🌍 Grimspike": "🌍 魔刺",
    "🌍 Crystal Golem": "🌍 水晶魔像",
    " increases crit chance, life steal and dexterity (crit damage).": "增加暴击几率，生命偷取和敏捷（暴击伤害）。",
    "Applies physical damage to your attacks.": "应用物理伤害到你的攻击。",
    "Are you sure you want to change region? That will reset your stage progress and will find you a new enemy": "您确定要更改区域吗？这将重置你的关卡进度，并为你找到一个新的敌人",
    "Auto-Cast Settings": "自动施法设置",
    "BUFF": "BUFF",
    "Poison Dagger": "淬毒匕首",
    "Shadow form increases crit chance, life steal and dexterity (crit damage).": "暗影形态增加暴击几率，生命偷取和敏捷（暴击伤害）。",
    "A powerful strike that restores life.": "恢复生命的强力一击。",
    "Blood Siphon": "血液虹吸",
    "Dark Aura": "黑暗光环",
    "Increases damage at night.": "在夜间增加伤害。",
    "Increases life steal and damage temporarily.": "暂时增加生命偷取和伤害。",
    "Night Stalker": "夜行者",
    "Steal life from enemies with each attack.": "每次攻击都从敌人身上偷取生命。",
    "Experience Potion": "经验药水",
    "INSTANT": "即时",
    "Potion of Agility": "敏捷药水",
    "Potion of Endurance": "耐力药水",
    "Upgrade the level of an equipped jewelry item by 1.": "将装备的珠宝物品的等级提高1。",
    "Jewelry Upgrade Gem": "珠宝升级宝石",
    "UNIQUE": "独特",
    "MAGIC": "魔法",
    "NORMAL": "普通",
    "RARE": "稀有",
    "Upgrade": "升级",
    " Upgrade Stone": " 升级石",
    "Select an equipped item to upgrade:": "选择要升级的装备：",
    "Not enough mana": "没有足够的法力",
    "Scorching Desert": "灼热沙漠",
    "Tough Skin": "铁肤",
    "Frenzy": "狂热",
    "Battle Cry": "战斗呐喊",
    "A powerful strike that sacrifices life for damage.": "以牺牲生命换取伤害的强力打击。",
    "A vast desert with relentless heat and dangerous creatures.": "一片巨大的沙漠，有着无情的酷热和危险的生物。",
    "Berserker's Rage": "狂战士之怒",
    "Boosts damage and attack speed temporarily.": "暂时提高伤害和攻击速度。",
    "Further enhances attack speed and damage.": "进一步提高攻击速度和伤害。",
    "Greater Frenzy": "更大的疯狂",
    "Greatly increases damage but lowers defense.": "大大增加伤害，但降低防御。",
    "Increases armor and reduces damage taken.": "增加护甲并减少伤害。",
    "Increases attack speed and damage while active.": "激活时增加攻击速度和伤害。",
    "Reckless Swing": "鲁莽摇摆",
    "Scorching Desert": "灼热沙漠",
    "Sorted items by rarity, then level": "按稀有度排序，然后是等级",
    "Upgrade the level of an equipped armor item by 1.": "将一件装备的防具升级1级。",
    "Upgrade the level of an equipped weapon by 1.": "使已装备的武器等级提升1级",
    "Weapon Upgrade Core": "武器升级核心",
    "❄️ Frostweaver": "❄️ 霜织者",
    "A burst of holy light that heals allies and damages enemies.": "一道神圣之光的爆发，治疗盟友并伤害敌人。",
    "Blesses the ground, dealing holy damage to enemies.": "祝福大地，对敌人造成神圣伤害。",
    "Consecration": "献祭",
    "Divine Protection": "神佑",
    "es an enemy with your shield, stunning them.": "用你的盾牌攻击敌人，击昏他们。",
    "Greater Healing": "更大的治疗",
    "Greatly increases armor and block chance.": "大幅提升护甲和格挡概率",
    "Heals a large amount of life instantly.": "立即治疗大量生命。",
    "Holy Light": "圣光",
    "Shield Bash": "圣盾",
    "Potion of Dexterity": "灵巧药水",
    "Increases dexterity by 1.": "增加1灵巧。",
    "❄️ Frost Giant": "❄️ 冰霜巨人",
    "❄️ Tide Guardian": "❄️ 潮汐守护者",
    "❄️ Depths Leviathan": "❄️ 深海利维坦",
    "❄️ Frostbite": "❄️ 霜狼",
    "❄️ Frostfury": "❄️ 霜怒",
    "❄️ Ice Wraith": "❄️ 冰幽灵",
    "Fire Drake": "火龙",
    "Goblin King": "哥布林之王",
    "Stone Golem": "石魔像",
    "Potion of Vitality": "活力药水",
    "All attribute points have been refunded.": "所有属性点数都已退还。",
    "Arcane Wisdom": "奥术智慧",
    "Blizzard": "暴风雪",
    "Boss level has been reset to 1.": "Boss等级已重置为1级",
    "Elemental Mastery": "元素精通",
    "Encases the caster in frost, increasing armor.": "将施法者包裹在冰霜中，增加护甲。",
    "Fire Shield": "火盾",
    "Fireball": "火球",
    "Frost Armor": "冰霜护甲",
    "Increases all elemental damage.": "增加所有元素伤害。",
    "Increases mana and mana regeneration": "增加法力和法力回复",
    "Increases mana and mana regeneration.": "增加法力和法力回复。",
    "Launches a fireball that deals fire damage.": "发射一个火球造成火焰伤害。",
    "Lightning Strike": "雷击",
    "Strikes an enemy with a bolt of lightning.": "用雷电击中敌人。",
    "Summons a blizzard, covering the battlefield in frost.": "召唤一场暴风雪，将战场覆盖在冰霜中。",
    "Surrounds the caster with a shield of fire. Deals only fire damage.": "用火焰之盾包围施法者。只造成火焰伤害。",
    "Warmth": "温暖",
    "🌍 Dunewraith": "🌍 邓布利多",
    "🌍 Boglurker": "🌍 保镖",
    "🌍 Sandstalker": "🌍 沙语者",
    "🌍 Toxictoad": "🌍 毒蟾蜍",
    "🌍 Venomspitter": "🌍 喷吐者",
    "🌍 Coral Sentinel": "🌍 珊瑚哨兵",
    "No normal or lower items to salvage": "没有普通或更低的物品可回收",
    "🔥 Dune Blazer": "🔥 丘陵开拓者",
    "🔥 Scorching Salamander": "🔥 火蜥蜴",
    "A dark and damp swamp filled with poisonous creatures.": "黑暗潮湿的沼泽，到处都是有毒的生物。",
    "A floating realm high above the clouds, home to air and lightning creatures.": "一个漂浮在云层之上的王国，是空气和雷电生物的家园。",
    "Earthquake": "地震",
    "Elixir": "长生不老药",
    "Increases critical chance and critical damage.": "增加暴击几率和暴击伤害。",
    "Item Drop bonus:": "物品掉落奖励：",
    "Murky Swamp": "黑暗沼泽",
    "MYTHIC": "神话",
    "Rage Mastery": "愤怒控制",
    "Skyrealm Peaks": "天境之峰",
    "Smashes the ground, dealing earth damage.": "粉碎地面，造成地面伤害。",
    "A dark and mysterious region filled with ancient horrors.": "一个黑暗而神秘的地区，充满了古老的恐怖。",
    "A searing landscape of molten rock and fire elementals.": "熔岩和火元素组成的灼热景观。",
    "Abyssal Depths": "深海深处",
    "Ancient ruins submerged beneath the waves, teeming with aquatic mysteries.": "古老的废墟淹没在海浪下，充满了水生的奥秘。",
    "Blood Lust": "嗜血",
    "Haunted Moor": "鬼影沼地",
    "Provides a chance to survive fatal damage.": "有一定几率躲过致命伤害。",
    "Significantly increases all combat stats.": "大幅提升所有战斗属性",
    "Sunken Ruins": "沉没废墟",
    "Unbridled Fury": "狂怒",
    "Undying Rage": "不朽之怒",
    "Volcanic Rift": "火山裂谷",
    "Warlord": "战神",
    "Bonus Material Drop %": "奖励材料掉落 %",
    "View Changelog": "查看更新日志",
    "View Upcoming Changes": "即将到来的更新",
    "Backup your save, if you want to keep it. Contact me on Discord if you need help with that. An update will happen on Monday 16th of June 2025, which may result in data loss. (hopefully not). THIS IS NOT RESET OF ALL DATA.": "备份你的存档，如果你想保存的话。如果你需要帮助，请在Discord上联系我。更新将于2025年6月16日星期一进行，这可能会导致数据丢失。(希望)。这不是重置所有数据。",
    " will be nerfed, as items currently give too much dexterity, causing crit damage to be extremely high.": "将会被削弱，因为现在的物品提供了太多的敏捷，导致暴击伤害非常高。",
    "*not guaranteed to be in the next update": "*不能保证在下一次更新中",
    "Enemies will deal physical and elemental damage based on their type.": "敌人将根据其类型造成物理和元素伤害。",
    "Item scaling will be reduced; lower-level items will become more useful.": "物品缩放将减少；低级物品将变得更有用。",
    "Mana will be reworked, since after a few hours of play, you get so much mana it never runs out.": "法力会被重制，因为玩了几个小时后，你会得到很多法力，永远不会用完。",
    "Most skills will get level caps, especially the strongest ones.": "大多数技能都有等级上限，尤其是最强的技能。",
    "New stats will be added: evasion, elemental resistances.": "新的属性将被添加：闪避，元素抗性。",
    "Percentage-based damage and crit damage will be capped for items.": "基于百分比的伤害和暴击伤害将被限制。",
    "Skill level-ups will be capped to your hero's level.": "技能升级将根据你的英雄等级而定。",
    "Upcoming Changes": "即将到来的变化",
    "Upcoming reset of all data. Will notify a few days before it happens.": "即将重置所有数据。会提前几天通知你的。",
    "Are you sure you want to change to explore? That will reset your stage progress and will find you a new enemy": "确定要切换为探索吗？这将重置你的关卡进度，并为你找到一个新的敌人",
    "Elemental Affinity": "元素亲和力",
    "Elemental Storm": "元素风暴",
    "Increases resistance to elemental damage.": "增加对元素伤害的抵抗。",
    "Unleashes a storm of fire, ice, and lightning.": "释放出火，冰和雷电的风暴。",
    "Drops": "掉落",
    "No cloud save found": "未找到云存档",
    "Buildings for offline production will be added.": "将增加用于离线生产的建筑。",
    ", Tier:": ", 层级:",
    "Category: Drops": "类别：掉落",
    "Epic Hoarder": "史诗囤积者",
    "First Find": "首次发现",
    "First Material": "第一个材料",
    "legendary": "传说",
    "Legendary Gatherer": "传说采集者",
    "Loot Collector": "战利品收集者",
    "Material Gatherer": "材料收集者",
    "Materialist": "材料专家",
    "mythic": "神话",
    "Mythic Collector": "神话收集者",
    "Mythic Prospector": "神话探勘者",
    "Random Item (Rarity:": "随机道具(稀有度：",
    "rare": "稀有",
    "Relic Seeker": "遗物搜寻者",
    "Resourceful": "足智多谋",
    "Treasure Hunter": "寻宝猎人",
    "unique": "独特",
    "(current)": "(当前)",
    "Claim": "领取",
    "Claimable Quests": "可领取奖励的任务",
    "": "",
    "No quests ready to claim.": "暂无可领取奖励的任务",
    "3rd fight method apart from \"Explore\" and \"Arena\".": "除了“探索”和“竞技场”之外的第三种打法。",
    "Auto salvage. Will also be able to choose gold/materials for salvage method.": "自动回收。也将能够选择黄金/材料的回收方法。",
    "Companions will be added. They will have their own stats and abilities, and will help you in battles. (will be able to equip items and gain xp)": "同伴将被添加。他们将有自己的属性和能力，并将在战斗中帮助你。（将能够装备物品并获得经验值）",
    "New skils for all classes.": "所有职业的新技能。",
    "Prestige system will be added. Will reset all progress to give you some new resource that will be persistent across prestiges.": "声望系统将被添加。将重置所有的进度，给你一些新的资源，将持续跨越声望。",
    "Apply": "同意",
    "OK": "确定",
    " reduction from armor is now based on region as well.": "护甲减少现在也基于区域。",
    "📊 UI & Stats": "📊 界面 & 统计",
    "🛠️ Fixes": "🛠️ 修复",
    "✨ New Features": "✨ 新功能",
    "⚖️ Balance Changes": "⚖️ 平衡性更改",
    "4–8× lower": "4–8× 降低",
    "Added more stats to the": "增加了更多的统计",
    "Bonuses now display correctly.": "奖励现在正确显示。",
    "Building Map for Offline Production:": "线下生产建设图：",
    "Buildings": "建筑",
    "Costs now increase by a flat amount per level.": "成本现在每升一级增加一个固定的数量。",
    "Crystal Lab": "水晶实验室",
    "Double Damage Chance": "双倍伤害几率",
    "Game Data Reset": "游戏数据重置",
    "Gold Mine": "金矿",
    "Improved performance for stat allocation.": "改进了状态分配的性能。",
    "Item tier bonuses are now": "物品层奖励现在",
    "Item Tier Scaling:": "物品层缩放：",
    "Life Per Hit": "命中生命值",
    "Lower values for damage percent increases and similar stats.": "较低的伤害百分比增加值和类似的属性。",
    "Material Tracking:": "材料跟踪:",
    "Now counts all materials found, not just +1 per find.": "现在计算所有发现的材料，而不是每次发现+1。",
    "now generate resources over time, both in-game and offline.": "现在生成资源随着时间的推移，无论是在游戏中还是离线。",
    "Open Buildings Map": "打开建筑地图",
    "Percentage Stat Scaling:": "百分比属性缩放：",
    "Please add your suggestions for changes in the game in the discord channel :)": "请在Discord频道中添加你对游戏改动的建议：)",
    "Quest Item Rewards:": "任务项目奖励：",
    "Resurrection Chance": "复活的机会",
    "Rewards are now one tier lower than before.": "奖励现在比以前低了一级。",
    "Soul Forge": "灵魂打造",
    "Soul Shop Bonuses:": "灵魂商店奖励：",
    "Soul Shop Upgrades:": "灵魂商店升级：",
    "tab for display.": "用于显示的标签。",
    "than before.": "比以前。",
    "Your game data has been fully reset due to an update or migration. We apologize for any inconvenience. Thank you for your understanding": "由于更新或迁移，您的游戏数据已完全重置。给您带来的不便，我们深表歉意。谢谢您的理解",
    "Bonus After Upgrade:": "升级后奖励：",
    "Choose a building to place": "选择一个建筑来放置",
    "Converts resources into souls.": "将资源转化为灵魂。",
    "Generates crystals over time.": "随着时间的推移产生水晶。",
    "Produces gold every few minutes.": "每隔几分钟就会产生黄金。",
    "Total Upgrade Cost:": "升级总成本：",
    "Upgrade Amount:": "升级数量：",
    "Leaderboard system. Will show top players based on their level and other stats.": "排行榜系统。将根据玩家的等级和其他属性显示顶级玩家。",
    "Live fight. Fight versus other players.": "实时对战。与其他玩家战斗。",
    "☁️ Air Res:": "☁️ 气系抗性：",
    "☁️ Air:": "☁️ 气:",
    "⚡ Lightning Res:": "⚡ 雷系抗性：",
    "⚡ Lightning:": "⚡ 雷电:",
    "❄️ Cold Res:": "❄️ 冰系抗性：",
    "❄️ Cold:": "❄️ 冰:",
    "🌍 Earth Res:": "🌍 土系抗性：",
    "🌍 Earth:": "🌍 土:",
    "💧 Water Res:": "💧 水系抗性：",
    "💧 Water:": "💧 水:",
    "🔥 Fire Res:": "🔥 火系抗性：",
    "🔥 Fire:": "🔥 火:",
    "🪲 Bug fixes": "🪲 Bug修复",
    "🪲 Bug Fixes": "🪲 Bug修复",
    "Added a crystal upgrade for auto consumption of materials.": "增加了一个自动消耗材料的水晶升级。",
    "Air Resistance": "气系抗性",
    "Auto-Consume Materials": "自动消耗材料",
    "Automatically salvage selected rarities": "自动回收选定的稀有物品",
    "Automatically uses all consumable materials on pickup": "自动使用所有可消耗材料的拾取",
    "Boss:": "Boss:",
    "elemental damages for bosses not incrementing per boss level": "boss的元素伤害不会随着boss级别而增加",
    "elemental resistances not showing correctly for bosses": "元素抗性对boss显示不正确",
    "Evasion:": "闪避：",
    "Few adjustments, increased xp/gold gains.": "少量调整，增加经验/金币收益。",
    "Killing a boss was giving the rewards for the next boss": "杀死一个boss可以为下一个boss提供奖励",
    "Lightning Damage": "雷系伤害",
    "Materials Auto consume:": "自动消耗：",
    "New Elements:": "新元素:",
    "Select Class": "选择职业",
    "Show Enemy Stats:": "显示敌人属性：",
    "Water and Lightning elements added. (No new skills or interactions yet)": "增加了水和雷电元素。（还没有新的技能或互动）",
    "Water Damage": "水系伤害",
    "• Evasion by 4": "• 闪避 4",
    "Auto-Salvage": "自动回收",
    "Automatically salvage items of selected rarities": "自动回收选中稀有度的物品",
    "Chance to dodge enemy attacks completely.": "有机会完全躲避敌人的攻击。",
    "EVADED": "闪避",
    "Higher evasion reduces enemy hit chance.": "更高的闪避降低敌人的命中几率。",
    "Included in base hit damage. Reduced by enemy resistances.": "包含在基础命中伤害中。被敌人的抗性降低。",
    "Next Level Cost:": "下一级成本：",
    "New skills for all classes.": "全部职业的新技能。",
    "Will also be able to choose gold/materials for salvage method.": "也将能够选择黄金/材料的回收方法。",
    "Your tooltip content here": "这里是你的提示内容",
    "Cloud save failed": "云存储失败",
    "Next update coming on 15/07/2025 and will include a full reset. A production build will be available right after the reset, and this will be used for testing purposes only. Full game on": "下一次更新将在2025年7月15日，将包括一个完整的重置。产品版本将在重置后立即可用，并且仅用于测试目的。完整游戏在",
    "✨ Features & Improvements": "✨功能与改进",
    "Added in-house login and logout functionality, including logout button.": "增加内部登录和注销功能，包括注销按钮。",
    "Added minimum cooldown (20% of total) and new cooldown calculation": "增加了最小冷却时间（总冷却时间的20%）和新的冷却时间计算方法",
    "Adjusted blockChance training cost and max level.": "调整了格挡几率的训练费用和最高等级。",
    "Allows salvaging items for upgrade materials instead of gold": "允许回收物品升级材料而不是黄金",
    "anywhere in the browser to access developer options.": "在浏览器的任何地方访问开发人员选项。",
    "Catastrophic Annihilator": "灾难性的歼灭者",
    "edev": "edev",
    "Endless Slaughter": "无尽的杀戮",
    "Fixed damage calculation for hero: % damage bonus and % total damage bonus were stacking incorrectly, causing very\n    high values.": "修正了英雄的伤害计算：%伤害加成和%总伤害加成叠加不正确，导致数值非常高。",
    "ghost-team.top": "ghost-team.top",
    "Hotfix: after killing a boss, the next was unable to be defeated.": "修复：杀死一个boss后，下一个无法被击败。",
    "In this test version, type": "在这个测试版本中，键入",
    "Increased boss scaling per level.": "每级增加boss缩放。",
    "Increased HP regen from Perseverance": "增加毅力的生命回复",
    "Infinite Destroyer": "无限的驱逐舰",
    "Intelligence:": "智力：",
    "Leaderboard": "排行榜",
    "Log out": "注销",
    "Lowered enemy scaling overall. Higher stages will have weaker enemies. Especially on higher tiers.": "降低了敌人的整体缩放。更高的关卡会有更弱的敌人。特别是在更高的级别。",
    "No prestige bonuses yet.": "目前还没有声望加成。",
    "Perseverance:": "毅力:",
    "Prestige": "声望",
    "Prestige Now": "现在声望",
    "Reduced damage bonus from Soul Shop by half.": "灵魂商店的伤害加成减半。",
    "Reduced overall damage bonuses for all damage sources.": "降低了所有伤害源的整体伤害加成。",
    "Reduced overall xp gained by enemies (which is somewhat mitigated by reaching higher stages).": "减少敌人获得的总经验值（游戏邦注：这在一定程度上可以通过达到更高的关卡而得到缓解）。",
    "Reduced prestige bonuses by nearly half.": "减少近一半的声望奖励。",
    "Reduced souls obtained by killing bosses by a factor of ~3.": "杀死boss获得的灵魂减少约3倍。",
    "Reduced XP and gold per level for bosses and monsters.": "减少每级boss和怪物的经验值和金币。",
    "Rogue nerfs.": "盗贼削弱。",
    "Salvage Materials": "回收材料",
    "Thornling": "荆刺",
    "Rank": "排名",
    "Skill Effects": "技能效果",
    "Highest Level": "最高等级",
    "Crystal Deity": "水晶神",
    "Crystal Titan": "水晶泰坦",
    "Dimensional Master": "次元大师",
    "Dimensional Ruin": "次元遗迹",
    "Divine Hero": "神圣英雄",
    "Endless Destruction": "无尽破坏",
    "Epic Cataclysm": "史诗大灾难",
    "Epic Extinction": "史诗绝迹",
    "Epic Obliterator": "史诗毁灭者",
    "Infinite Prospector": "无限勘探者",
    "Infinite Vault": "无限拱顶",
    "Infinite Voyager": "无限航行者",
    "Legendary Apocalypse": "天启传说",
    "Legendary Extinction": "传说灭绝",
    "Legendary Oblivion": "传说忘境",
    "Limitless Fortune": "无限财富",
    "Master Prospector": "采矿大师",
    "Mythic Cataclysm": "神话大灾变",
    "Mythic Extinction": "神话灭绝",
    "Mythic Legend": "神话传说",
    "Mythic Nightmare": "神话梦魇",
    "Mythic Oblivion": "神话遗忘",
    "Rare Cataclysm": "罕见的灾难",
    "Rare Extinction": "稀有灭绝",
    "Rare Obliteration": "罕见的毁灭",
    "Sylvan Wisp": "森林的缕",
    "Ultimate Hoarder": "最终的收藏者",
    "Username": "用户名",
    "Wealth Beyond Measure": "无尽的财富",
    "Worldly Collector": "世俗收藏家",
    "Worldly Prospector": "世俗勘探者",
    "Wielder of nature magic and animal allies": "自然魔法和动物盟友的持用者",
    "Master of arcane spells and destructive magic": "奥术法术和破坏性魔法的大师",
    "Mage": "法师",
    "Mossback": "绿毛龟",
    "Companions will be added. They will have their own stats and abilities, and will help you in battles. (will be\n    able to equip items and gain xp)": "同伴将被添加。他们将有自己的属性和能力，并将在战斗中帮助你。（将能够装备物品并获得经验）",
    "Druid": "德鲁伊",
    "A shimmering cave filled with rocks. Has a high chance of dropping crystalized rocks.": "一个充满岩石的闪闪发光的洞穴。很有可能掉下结晶岩石。",
    "Barkhide": "树皮",
    "Elemental Resistance. Reduces elemental damage taken from enemies by a %.": "元素抵抗。减少敌人的元素伤害%。",
    "Intelligence": "智力",
    "Perseverance": "毅力",
    "Magic Missile": "魔法飞弹",
    "Launches a missile of arcane energy.": "发射一枚奥术能量飞弹。",
    "Increases mana and wisdom.": "增加魔法和智慧。",
    "Arcane Intellect": "奥术智慧",
    "Blasts the target with fire.": "用火焰轰击目标。",
    "Fire Blast": "烈焰爆裂",
    "Fires a bolt of frost at the enemy.": "向敌人发射一道冰霜。",
    "Frost Bolt": "冰霜霹雳",
    "STAFF": "法杖",
    "WAND": "魔杖",
    "Auto": "自动",
    "Rare Items": "稀有物品",
    "Legendary Items": "传说物品",
    "Mythic Items": "神话物品",
    "Magic Items": "魔法物品",
    "Mana Shield": "法力护盾",
    "A land of ice and snow, home to cold and air enemies. Has increased chance of dropping potions.": "冰雪之地，是寒冷和空中敌人的家园。增加了掉落药水的几率。",
    "A vast desert with relentless heat and dangerous creatures. Has a chance to drop elixirs.": "一片巨大的沙漠，有着无情的酷热和危险的生物。有机会掉落长生不老药。",
    "Absorbs damage using mana.": "使用法力吸收伤害。",
    "Arcane Focus": "奥术聚焦",
    "Crystal Golem": "水晶魔像",
    "Drag item here": "拖动物品在这里",
    "Engulfs the area in flames.": "将整个区域吞没在火焰中。",
    "Frost Giant": "冰霜巨人",
    "Frostbite": "冻伤",
    "Frostfury": "霜怒",
    "Gem Guardian": "宝石守护者",
    "Greatly increases attack speed for a short time.": "在短时间内大幅提高攻击速度。",
    "Grimspike": "魔刺",
    "Ice Storm": "冰雪风暴",
    "Ice Wraith": "冰之魔灵",
    "Improves spell damage and hit rate.": "提高法术伤害和命中率。",
    "Infuses yourself with magical energy. Greatly increases mana regeneration.": "给自己注入魔法能量。大大提高法力回复。",
    "Instantly move to a nearby location.": "立即移动到附近的位置。",
    "Mind Control": "精神控制",
    "Pyroclasm": "火山喷发",
    "Resource Infusion": "资源注入",
    "Salvage Options": "救助方案",
    "Salvage reward": "回收奖励",
    "Salvage Value:": "回收价值：",
    "Shardling": "分片",
    "Summons a storm of ice around you.": "在你周围召唤一场冰暴。",
    "Time Warp": "时空扭曲",
    "Unique Items": "独特物品",
    "Upgrade materials": "升级材料",
    "Upgraded Auto-Salvage by 1 level": "自动回收提升1级",
    "Dune Blazer": "沙丘开拓者",
    "Dunewraith": "杜尼格拉斯",
    "Grants 5% experience when used.": "使用时增加5%的经验值。",
    "Increases intelligence by 1.": "增加1点智力。",
    "Increases perseverance by 1.": "增加毅力1点。",
    "Re-rolls the value of one random stat on an equipped item.": "重新掷出已装备物品上的随机一项属性值。",
    "Sandstalker": "沙行者",
    "Scorching Salamand": "灼热蝾螈",
    "Ancient Serpent": "上古巨蛇",
    "Ogre Chieftain": "食人魔酋长",
    "Scorching Salamander": "火蜥蜴",
    "A dark and damp swamp filled with poisonous creatures. Has increased chance of dropping gold coins.": "黑暗潮湿的沼泽，到处都是有毒的生物。增加了掉落金币的几率。",
    "Boglurker": "博格鲁克",
    "Frostweaver": "寒霜编织者",
    "Toxictoad": "毒蟾蜍",
    "Venomspitter": "毒液喷射器",
    "Arcane Power": "奥术之力",
    "Ressurected": "复活",
    "Summon Stats": "召唤统计信息",
    "Summon Stats:": "召唤统计:",
    "Summons an elemental ally.": "召唤元素伙伴",
    "Unleash arcane power, increasing spell damage.": "释放奥术能量，增加法术伤害。",
    "Upgraded Extra Material Drop Chance % by 1 levels": "额外材料掉落几率提高1级",
    "Upgraded Extra Material Drop Max by 1 levels": "额外材料掉落上限提升1级",
    "\n      Please add your suggestions for changes in the game in the discord channel :)": "请在discord频道添加您对游戏的修改建议：)",
    "Bonuses were earned while you were away": "您不在的时候获得了奖励",
    "Collect": "收集",
    "Equip": "装备",
    "HERE": "这里",
    "Highest Stages:": "最高关卡：",
    "Item Drop Quantity %": "物品掉落数量%",
    "Item Drop Rarity %": "物品掉落稀有度%",
    "Life Regen Of Total %": "生命回复总量的%",
    "Offline Building Rewards": "离线建筑奖励",
    "Skip +1 stage per kill": "每次击杀跳过+1关卡",
    "Sound Volume:": "音量:",
    "Stage Skip per Kill:": "每次击杀跳过关卡：",
    "Stages": "关卡",
    "Upgraded Life Regen Of Total % by 1 levels": "生命回复提升1级",
    "Upgraded Mana regeneration % of total mana by 1 levels": "法力回复占总法力的百分比提升1级",
    "You can download desktop application (Windows only!) from": "您可以下载桌面应用程序(仅限Windows ！",
    "Counters Period (sec):": "计数器周期（秒）：",
    "Enemies Killed by Rarity:": "按稀有度击杀敌人：",
    "Enemies Killed by Zone:": "被区域杀死的敌人：",
    "History": "历史",
    "Items Found by Rarity:": "按稀有度找到的物品：",
    "Reset Stage Skip": "重置关卡跳过",
    "Reset Stage Skip At:": "重置关卡跳过于：",
    "Show Advanced Attribute Tooltips:": "显示高级属性工具提示：",
    "Show Advanced Item Tooltips:": "显示高级物品工具提示：",
    "Show All Stats:": "显示所有统计：",
    "Show Counters Bar:": "显示计数器栏:",
    "Unlocks reset stage skip option": "解锁重置跳过关卡选项",
    "Mana regeneration % of total mana": "法力回复占总法力的%",
    "Sort": "排序",
    "Sort by:": "排序方式:",
    "Total %:": "总计 %:",
    "Stage": "关卡",
    "Stage Lock": "关卡锁定",
    "Stage Skip per Kill": "每次击杀跳过关卡",
    "Stage skip per kill": "每次击杀跳过关卡",
    "Combat": "战斗",
    "DMG": "伤害",
    "All Items": "所有物品",
    "Air Res": "气系抗性",
    "Air": "气系",
    "Air Reduction": "空气减少",
    "Top (Center)": "上部 (中间)",
    "Right (Center)": "右侧 (中间)",
    "Left (Center)": "左侧 (中间)",
    "Bottom (Center)": "底部 (中间)",
    "Language": "语言",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "DPS": "DPS",
    "LEGENDARY": "传说",
    "SWORD": "剑",
    "HELMET": "头盔",
    "AXE": "斧子",
    "BELT": "腰带",
    "SHIELD": "盾牌",
    "ARMOR": "护甲",
    "BOOTS": "靴子",
    "MACE": "权杖",
    "PANTS": "裤子",
    "AMULET": "护身符",
    "GLOVES": "手套",
    "RING": "戒指",

    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "© 2025 GT Platform. All rights reserved.": "© 2025 GT Platform. All rights reserved.",
    "☁️": "☁️",
    "☠️": "☠️",
    "⚔️": "⚔️",
    "✨": "✨",
    "❄️": "❄️",
    "⭐": "⭐",
    "🌌": "🌌",
    "🌍": "🌍",
    "🌟": "🌟",
    "🎗️": "🎗️",
    "🏆": "🏆",
    "👑": "👑",
    "👕": "👕",
    "👖": "👖",
    "👢": "👢",
    "👤": "👤",
    "👻": "👻",
    "💀": "💀",
    "💍": "💍",
    "💎": "💎",
    "💢": "💢",
    "💥": "💥",
    "💰": "💰",
    "📿": "📿",
    "🔃": "🔃",
    "🔥": "🔥",
    "🔴": "🔴",
    "🔵": "🔵",
    "🔷": "🔷",
    "🗑️": "🗑️",
    "🗺️": "🗺️",
    "🦸": "🦸",
    "🧙": "🧙",
    "🧤": "🧤",
    "🪖": "🪖",
    "🛡️": "🛡️",
    "🟠": "🟠",
    "🟣": "🟣",
    "🎯": "🎯",
    "👚": "👚",
    "🔨": "🔨",
    "🔹": "🔹",
    "🧠": "🧠",
    "🧪": "🧪",
    "🪙": "🪙",
    "🪨": "🪨",
    "+": "+",
    "×": "×",
    "∞": "∞",
    "⚡": "⚡",
    "❌": "❌",
    "☰": "☰",
    "🌠": "🌠",
    "💧": "💧",
    "💫": "💫",
    "✅": "✅",
    "❤️": "❤️",
    "🏃": "🏃",
    "💪": "💪",
    "🔄": "🔄",
    "🥤": "🥤",
    "🦯": "🦯",
    "🪄": "🪄",
    "🪓": "🪓",
    "—": "—",
    "?": "?",
    "(": "(",
    "▾": "▾",
    "✖": "✖",
    ")": ")",
    "💾": "💾",
    " %": " %",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    ":": ":",
    "/": "/",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    "Gityx": "Gityx",
    "Gz": "Gz",
    "O": "O",
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "What's up, ": "怎么了，",
    "Earth Damage: ": "土系伤害: ",
    "Elemental Damage: ": "元素伤害: ",
    "Stage: ": "关卡: ",
    "Total Time In Fights: ": "战斗总时长: ",
    "Bonus Experience": "奖励经验",
    "Extra Material Drop Chance": "额外材料掉落几率",
    "Extra Material Drop Max": "额外材料掉落上限",
    "Bonus Gold": "奖励金币",
    "Crit Chance": "暴击几率",
    "Crit Damage": "暴击伤害",
    "Damage Boost": "伤害提升",
    "Attack Rating": "攻击准确率",
    "Attack Speed": "攻击速度",
    "Cold Damage": "冰系伤害",
    "Earth Damage": "土系伤害",
    "Fire Damage": "火系伤害",
    "Air Damage": "气系伤害",
    "Mana Boost": "法力提升",
    "Life Boost": "生命提升",
    "Life Steal": "生命偷取",
    "Life Steal: ": "生命偷取: ",
    "Life: ": "生命值: ",
    "Agility": "敏捷",
    "Cold Damage: ": "冰系伤害: ",
    "Earth Damage: ": "土系伤害: ",
    "Fire Damage: ": "火系伤害: ",
    "Air Damage: ": "气系伤害: ",
    "Armor": "护甲",
    "Current Bonus:": "当前加成:",
    "Attributes (": "属性 (",
    "Highest Damage Dealt: ": "造成的最高伤害: ",
    "Block Chance": "格挡几率",
    "Attack Speed": "攻击速度",
    "Damage": "伤害",
    "Crystals: ": "水晶: ",
    "Gold: ": "金币: ",
    "Level: ": "等级: ",
    "Souls: ": "灵魂: ",
    "Vitality": "活力",
    "Total Time Played: ": "总游戏时长: ",
    "Total Items Found: ": "总计发现的物品: ",
    "Total Souls Earned: ": "总计赚取的灵魂: ",
    "Total Gold Earned: ": "总计赚取的金币: ",
    "Total Crystals Earned: ": "总计赚取的水晶: ",
    "Total Enemies Killed: ": "总计击杀的敌人: ",
    "Starting Stage": "开始关卡",
    "Highest Stage Reached: ": "达到的最高关卡: ",
    "Last save: ": "最近保存: ",
    "(Equipped) ": "(已装备) ",
    "Dexterity": "灵巧",
    "Endurance": "耐力",
    "Strength": "力量",
    "Maximum: ": "最大: ",
    "Bosses Defeated: ": "击败的Boss: ",
    "Reset Arena Level to ": "重置竞技场等级为 ",
    "Reset Arena level to ": "重置竞技场等级为 ",
    "Increases starting stage by ": "增加初始关卡 ",
    "LEVEL UP! ": "升级! ",
    "Wisdom": "智慧",
    "Last cloud save: ": "最近一次云存储 ",
    "Mana (Lvl ": "法力 (等级 ",
    "Life (Lvl ": "生命值 (等级 ",
    "Life Regeneration": "生命回复",
    "Mana Regeneration": "法力回复",
    "Quest \"": "任务 \"",
    "Found: ": "发现: ",
    "Purchased ": "已购买 ",
    "🧠 Potion of Wisdom": "🧠 智慧药水",
    "Mana Cost:": "法力成本:",
    "Max (": "最大 (",
    "Available Skill Points:": "可用技能点数:",
    "Available Points:": "可用点数:",
    "Bash": "重击",
    "Toughness": "坚韧",
    "Resurrection Chance:": "复活几率:",
    "Mana:": "法力:",
    "💥 -": "💥 -",
    "Life %: ": "生命值 %: ",
    "💎 Crystalized Rock": "💎 水晶岩石",
    "💥 Potion of Strength": "💥 力量药水",
    "🪙 Large Gold Coins": "🪙 大金币",
    "🪙 Medium Gold Coins": "🪙 中金币",
    "🪙 Enormous Gold Coins": "🪙 巨金币",
    "🪙 Freaky Gold Coins": "🪙 异金币",
    "🧪 Experience Potion": "🧪 经验药水",
    "🛡️ Potion of Endurance": "🛡️ 耐力药水",
    "🏃 Potion of Agility": "🏃 敏捷药水",
    "Cooldown:": "冷却时间:",
    "Duration:": "持续时间:",
    "Shadow Form": "影子形态",
    "Mana %: ": "法力 %: ",
    "LEGENDARY ": "传说",
    "UNIQUE ": "独特",
    "MYTHIC ": "神话",
    "MAGIC ": "魔法",
    "NORMAL ": "普通",
    "RARE ": "稀有",
    "Life Per Hit: ": "生命值每次命中: ",
    "Vampiric Strike": "吸血鬼打击",
    "💍 Jewelry Upgrade Gem": "💍 珠宝升级宝石",
    "🪨 Armor Upgrade Stone": "🪨 护甲升级石",
    "Upgrade the level of an equipped armor item by ": "升级一件已装备护甲物品等级 ",
    "Double Damage Chance:": "双倍伤害几率:",
    "Elemental Damage %:": "元素伤害 %:",
    "🎯 Potion of Dexterity": "🎯 灵巧药水",
    "Thorns Damage %:": "荆棘伤害 %:",
    "⚡ Weapon Upgrade Core": "⚡ 武器升级核心",
    "Boss Level: ": "Boss等级: ",
    "❤️ Potion of Vitality": "❤️ 活力药水",
    "Reflect Fire Damage:": "反射火焰伤害:",
    "🥤 Elixir": "🥤 万灵药",
    "Mana Per Hit: ": "法力每击: ",
    "Total Materials Found: ": "总计发现的材料: ",
    "Auto-Salvage (Lvl": "自动回收 (等级 ",
    "Evasion (Lvl": "闪避 (等级 ",
    "Water Damage (Lvl": "水系伤害 (等级 ",
    "Lightning Damage (Lvl": "雷系伤害 (等级 ",
    "Double Damage Chance (Lvl": "双倍伤害几率 (等级 ",
    "Evasion: ": "闪避: ",
    "Air Resistance": "气系抗性",
    "Cold Resistance": "冰系抗性",
    "Earth Resistance": "土系抗性",
    "Fire Resistance": "火系抗性",
    "Lightning Resistance": "雷系抗性",
    "Water Resistance": "水系抗性",
    "Intelligence: +": "智力: +",
    "Life Regen: +": "生命值回复: +",
    "Mana Regen: +": "法力回复: +",
    "Water Damage: +": "水系伤害: +",
    "• Evasion by ": "• 闪避 ",
    "• Mana Regeneration by ": "• 法力回复 ",
    "• Life Regeneration by ": "• 生命值回复 ",
    "• Elemental Damage by ": "• 元素伤害 ",
    "Intelligence %: ": "智力 %: ",
    "Perseverance %: ": "毅力 %: ",
    "Mana Regen %: ": "法力回复 %: ",
    "Lightning Damage %: ": "雷系伤害 %: ",
    "Lightning Damage: ": "雷系伤害: ",
    "Water Damage %: ": "水系伤害 %: ",
    "Water Damage: ": "水系伤害: ",
    "Evasion %: ": "闪避 %: ",
    "Intelligence: ": "智力: ",
    "Perseverance: ": "毅力: ",
    " taken from mana before life %: ": " 从生命前的法力中获得 %：",
    "Mana regeneration % of total mana: ": "法力回复总法力的 %: ",
    "🪙 Gold Coins": "🪙 金币",
    "💪 Potion of Perseverance": "💪 毅力药水",
    "🔄 Alternation Orb": "🔄 交替宝珠",
    "🧠 Potion of Intelligence": "🧠 智力药水",
    "🧪 Greater Experience Potion": "🧪 高级经验药水",
    "🧪 Huge Experience Potion": "🧪 巨型经验药水",
    "% of your total damage: ": "% 你的总伤害: ",
    "Summon Elemental": "召唤元素",
    "Stage Skip (Lvl": "跳过关卡 (等级 ",
    "Life Regen Of Total % (Lvl": "生命回复对于总计 % (等级 ",
    "Mana regeneration % of total mana (Lvl": "法力回复对于总计 % (等级 ",
    "Current version: ": "当前版本: ",
    "Next bonus: ": "下一个加成: ",
    "Mythic: ": "神话: ",
    "Epic: ": "史诗: ",
    "Legendary: ": "传说: ",
    "Rare: ": "稀有: ",
    "Mythic: ": "稀有: ",
    "Normal: ": "普通: ",
    "Life Regen Boost % (Lvl": "生命值回复提升 % (等级 ",
    "Evasion Boost % (Lvl": "闪避提升 % (等级 ",
    "Highest Boss Level: ": "最高Boss等级: ",
    "All Elemental Resistance Boost % (Lvl": "所有元素抗性提升 % (等级 ",
    " Boost % (Lvl ": " 提升 % (等级 ",
    "Starting Crystals: ": "起始水晶：",
    "All Resistance % (Lvl": "所有抗性 % (等级",
    "Max Mana % (Lvl": "最大法力值 % (等级",
    "Max Life % (Lvl": "最大生命值 % (等级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    "!": "!",
    "% damage vs same element": "% 伤害对同一元素",
    "% damage vs opposite element": "% 伤害对相反元素",
    "% damage vs other elements": "% 伤害对其它元素",
    "\" claimed": "\" 奖励已领取",
    " [TOGGLE]": " [切换]",
    " [PASSIVE]": " [被动]",
    " [BUFF]": " [BUFF]",
    " [INSTANT]": " [即时]",
    " SP)": " 技能点)",
    " Bonus Experience %": " 奖励经验 %",
    " Bonus Gold %": " 奖励金币 %",
    " Damage Boost %": " 伤害提升 %",
    " Life Boost %": " 生命提升 %",
    " Mana Boost %": " 法力提升 %",
    " Extra Material Drop Max": " 额外材料掉落上限",
    " / Max)": " / 最大)",
    " [SUMMON]": " [召唤]",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^: \+([\d\.]+)$/,
    /^: ([\d\.]+)$/,
    /^• ([\d\.]+)$/,
    /^\(\+([\d\.]+)\)$/,
    /^\(\-([\d\.]+)\)$/,
    /^: ([\d\.]+) \(\+([\d\.]+)\)$/,
    /^ ([\d\.]+)s \(([\d\.]+)s\)$/,
    /^ \%: ([\d\.]+) \(\+([\d\.]+)\)$/,
    /^ \%: \+([\d\.]+)$/,
    /^ \%: ([\d\.]+)\%$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+) \(([\d\.]+)\%\)$/,
    /^: \+([\d\.]+)\%$/,
    /^([\d\.]+)\)$/,
    /^ ([\d\.]+)s \(\+([\d\.]+)s\)$/,
    /^: ([\d\.]+)\%$/,
    /^ \+([\d\.]+)$/,
    /^ ([\d\.]+)\%$/,
    /^ × ([\d\.]+)$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\~([\d\.]+)$/,
    /^ ([\d\.]+)$/,
    /^💥 ([\d\.]+)$/,
    /^🔒 ([\d\.]+)$/,
    /^💥  \-([\d\.]+)$/,
    /^ ([\d\.]+) \(\+([\d\.]+)\)$/,
    /^\+([\d\.]+) \(([\d\.]+)$/,
    /^\+([\d\.]+)\)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)\%$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \((80%)\%\)$/,
    /^T([\d\.,]+): ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Reach level 500 \((.+) more levels\) and Defeat boss level 200 \((.+) more boss levels\) to prestige.$/, '等级达到500级（还差$1级），击败boss等级达到200级（还差$2级），可进行声望。'],
    [/^(.+) Extra Material Drop Chance \%$/, '$1 额外材料掉落几率 %'],
    [/^Need (.+) crystals for this upgrade$/, '本次升级需要 $1 个水晶'],
    [/^Boss defeated! (.+) gold, (.+) crystals, (.+) souls$/, 'Boss已被击败! $1 金币, $2 水晶, $3 灵魂'],
    [/^Boss defeated! (.+) souls.$/, 'Boss已被击败! $1 灵魂。'],
    [/^Adds (.+) gold per coin to your total.$/, '每枚币提供 $1 金币。'],
    [/^Upgraded Water Damage by (.+) levels$/, '升级 水系伤害 $1 级'],
    [/^Upgraded Lightning Damage by (.+) levels$/, '升级 雷系伤害 $1 级'],
    [/^Upgraded Double Damage Chance by (.+) levels$/, '升级 双倍伤害几率 $1 级'],
    [/^Upgraded Starting Stage by (.+) levels$/, '升级起始等级 $1 级'],
    [/^Upgraded Bonus Gold by (.+) levels$/, '升级奖励金币 $1 级'],
    [/^Upgraded Bonus Experience by (.+) levels$/, '升级奖励经验 $1 级'],
    [/^Upgraded Life Steal by (.+) levels$/, '你把 生命偷取 升级了 $1 级'],
    [/^Upgraded Evasion by (.+) levels$/, '你把 闪避 升级了 $1 级'],
    [/^Upgraded Armor by (.+) levels$/, '你把 护甲 升级了 $1 级'],
    [/^Upgraded Damage by (.+) levels$/, '你把 伤害 升级了 $1 级'],
    [/^Upgraded Earth Damage by (.+) levels$/, '你把 土系伤害 升级了 $1 级'],
    [/^Upgraded Crit Damage by (.+) levels$/, '你把 暴击伤害 升级了 $1 级'],
    [/^Upgraded Attack Rating by (.+) levels$/, '你把 攻击准确率 升级了 $1 级'],
    [/^Upgraded Attack Speed by (.+) levels$/, '你把 攻击速度 升级了 $1 级'],
    [/^Upgraded Block Chance by (.+) levels$/, '你把 格挡几率 升级了 $1 级'],
    [/^Upgraded Crit Chance by (.+) levels$/, '你把 暴击几率 升级了 $1 级'],
    [/^Upgraded Air Damage by (.+) levels$/, '你把 气系伤害 升级了 $1 级'],
    [/^Upgraded Cold Damage by (.+) levels$/, '你把 冰系伤害 升级了 $1 级'],
    [/^Upgraded Fire Damage by (.+) levels$/, '你把 火系伤害 升级了 $1 级'],
    [/^Upgraded Mana by (.+) levels$/, '你把 法力 升级了 $1 级'],
    [/^Upgraded Life by (.+) levels$/, '你把 生命值 升级了 $1 级'],
    [/^Upgraded Life Regeneration by (.+) levels$/, '你把 生命值回复 升级了 $1 级'],
    [/^Upgraded Mana Regeneration by (.+) levels$/, '你把 法力回复 升级了 $1 级'],
    [/^Upgraded Air Resistance by (.+) levels$/, '你把 气系抗性 升级了 $1 级'],
    [/^Upgraded Cold Resistance by (.+) levels$/, '你把 冰系抗性 升级了 $1 级'],
    [/^Upgraded Earth Resistance by (.+) levels$/, '你把 土系抗性 升级了 $1 级'],
    [/^Upgraded Fire Resistance by (.+) levels$/, '你把 火系抗性 升级了 $1 级'],
    [/^Upgraded Lightning Resistance by (.+) levels$/, '你把 雷系抗性 升级了 $1 级'],
    [/^Upgraded Water Resistance by (.+) levels$/, '你把 水系抗性 升级了 $1 级'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Salvaged (.+) normal item, gained (.+) gold$/, '回收 $1 件普通物品，获得 $2 金币'],
    [/^Salvaged (.+) normal items, gained (.+) gold$/, '回收 $1 件普通物品，获得 $2 金币'],
    [/^Salvaged (.+) magic item, gained (.+) gold$/, '回收 $1 件魔法物品，获得 $2 金币'],
    [/^Salvaged (.+) magic items, gained (.+) gold$/, '回收 $1 件魔法物品，获得 $2 金币'],
    [/^Salvaged (.+) legendary item, gained (.+) gold$/, '回收 $1 件传说物品，获得 $2 金币'],
    [/^Salvaged (.+) legendary items, gained (.+) gold$/, '回收 $1 件传说物品，获得 $2 金币'],
    [/^Salvaged (.+) unique item, gained (.+) gold$/, '回收 $1 件独特物品，获得 $2 金币'],
    [/^Salvaged (.+) unique items, gained (.+) gold$/, '回收 $1 件独特物品，获得 $2 金币'],
    [/^Salvaged (.+) mythic item, gained (.+) gold$/, '回收 $1 件神话物品，获得 $2 金币'],
    [/^Salvaged (.+) mythic items, gained (.+) gold$/, '回收 $1 件神话物品，获得 $2 金币'],
    [/^Salvaged (.+) rare item, gained (.+) gold$/, '回收 $1 件稀有物品，获得 $2 金币'],
    [/^Salvaged (.+) rare items, gained (.+) gold$/, '回收 $1 件稀有物品，获得 $2 金币'],
    [/^Salvaged (.+) normal or lower items, gained (.+) gold$/, '回收 $1 件普通或更低的物品，获得 $2 金币'],
    [/^Salvaged (.+) magic or lower items, gained (.+) gold$/, '回收 $1 件魔法或更低的物品，获得 $2 金币'],
    [/^Salvaged (.+) legendary or lower items, gained (.+) gold$/, '回收 $1 件传说或更低的物品，获得 $2 金币'],
    [/^Salvaged (.+) unique or lower items, gained (.+) gold$/, '回收 $1 件独特或更低的物品，获得 $2 金币'],
    [/^Salvaged (.+) mythic or lower items, gained (.+) gold$/, '回收 $1 件神话或更低的物品，获得 $2 金币'],
    [/^Salvaged (.+) rare or lower items, gained (.+) gold$/, '回收 $1 件稀有或更低的物品，获得 $2 金币'],
    [/^Earn a total of (.+) gold.$/, '总计赚取 $1 金币。'],
    [/^Earn a total of (.+) crystals.$/, '总计赚取 $1 水晶。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^ ([\d\.]+)s$/, ' $1秒'],
    [/^• Critical Damage by ([\d\.]+)$/, '• 暴击伤害 $1'],
    [/^• Attack Rating by ([\d\.]+)$/, '• 攻击准确率 $1'],
    [/^• Armor by ([\d\.]+)$/, '• 护甲 $1'],
    [/^• Damage by ([\d\.]+)$/, '• 伤害 $1'],
    [/^• Life by ([\d\.]+)$/, '• 生命值 $1'],
    [/^• Mana by ([\d\.]+)$/, '• 法力 $1'],
    [/^\+([\d\.]+)\% Extra Material Drop Chance$/, '\+$1\% 额外材料掉落几率'],
    [/^\+([\d\.]+)\% Damage Boost$/, '\+$1\% 伤害提升'],
    [/^\+([\d\.]+)\% Life Boost$/, '\+$1\% 生命提升'],
    [/^\+([\d\.]+)\% Mana Boost$/, '\+$1\% 法力提升'],
    [/^\+([\d\.]+)\% Bonus Gold$/, '\+$1\% 奖励金币'],
    [/^\+([\d\.]+)\% Bonus Experience$/, '\+$1\% 奖励经验值'],
    [/^\+([\d\.]+) souls\/min$/, '\+$1 灵魂\/分钟'],
    [/^\+([\d\.]+) crystals\/min$/, '\+$1 水晶\/分钟'],
    [/^\+([\d\.]+) gold\/min$/, '\+$1 金币\/分钟'],
    [/^\+([\d\.]+) Life Steal$/, '\+$1 生命偷取'],
    [/^\+([\d\.]+) Damage$/, '\+$1 伤害'],
    [/^\+([\d\.]+) Extra Material Drop Max$/, '\+$1 额外材料掉落上限'],
    [/^\+([\d\.]+) Cold Resistance$/, '\+$1 冰系抗性'],
    [/^\+([\d\.]+) Earth Resistance$/, '\+$1 土系抗性'],
    [/^\+([\d\.]+) Fire Resistance$/, '\+$1 火系抗性'],
    [/^\+([\d\.]+) Water Resistance$/, '\+$1 水系抗性'],
    [/^\+([\d\.]+) Lightning Resistance$/, '\+$1 电系抗性'],
    [/^\+([\d\.]+) Air Resistance$/, '\+$1 气系抗性'],
    [/^\+([\d\.]+) Mana Boost$/, '\+$1 法力提升'],
    [/^\+([\d\.]+) Life Boost$/, '\+$1 生命提升'],
    [/^\+([\d\.]+) Damage Boost$/, '\+$1 伤害提升'],
    [/^\+([\d\.]+) Bonus Gold$/, '\+$1 奖励的金币'],
    [/^\+([\d\.]+) Attack Speed$/, '\+$1 攻击速度'],
    [/^\+([\d\.]+) Bonus Experience$/, '\+$1 奖励的经验值'],
    [/^\+([\d\.]+) Crit Chance$/, '\+$1 暴击几率'],
    [/^\+([\d\.]+) Crit Damage$/, '\+$1 暴击伤害'],
    [/^\+([\d\.]+) Air Damage$/, '\+$1 气系 伤害'],
    [/^\+([\d\.]+) Cold Damage$/, '\+$1 冰系 伤害'],
    [/^\+([\d\.]+) Earth Damage$/, '\+$1 土系 伤害'],
    [/^\+([\d\.]+) Fire Damage$/, '\+$1 火系 伤害'],
    [/^\+([\d\.]+) Attack Rating$/, '\+$1 攻击准确率'],
    [/^\+([\d\.,]+) Attack Rating$/, '\+$1 攻击准确率'],
    [/^: \+([\d\.,]+) soul$/, ': \+$1 灵魂'],
    [/^: \+([\d\.,]+) gold$/, ': \+$1 金币'],
    [/^: \+([\d\.,]+) crystal$/, ': \+$1 水晶'],
    [/^\+([\d\.]+) Block Chance$/, '\+$1 格挡几率'],
    [/^\+([\d\.]+) Mana Regeneration$/, '\+$1 法力回复'],
    [/^\+([\d\.]+) Life Regeneration$/, '\+$1 生命回复'],
    [/^\+([\d\.]+) Extra Material Drop Chance$/, '\+$1 额外材料掉落几率'],
    [/^\+([\d\.]+) Extra Material Drop Max$/, '\+$1 额外材料掉落上限'],
    [/^\+([\d\.]+) Armor$/, '\+$1 护甲'],
    [/^\+([\d\.]+) Mana$/, '\+$1 法力'],
    [/^\+([\d\.]+) Lightning Damage$/, '\+$1 雷系伤害'],
    [/^\+([\d\.]+) Water Damage$/, '\+$1 水系伤害'],
    [/^\+([\d\.]+) Double Damage Chance$/, '\+$1 双倍伤害几率'],
    [/^\+([\d\.]+) Life Regen Boost \%$/, '\+$1 生命回复提升 \%'],
    [/^\+([\d\.]+) All Elemental Resistance Boost \%$/, '\+$1 所有元素抵抗提升 \%'],
    [/^\+([\d\.]+) Armor Boost \%$/, '\+$1 护甲提升 \%'],
    [/^\+([\d\.]+) Evasion Boost \%$/, '\+$1 闪避提升 \%'],
    [/^\+([\d\.]+) Attack Rating Boost \%$/, '\+$1 攻击率提升 \%'],
    [/^\+([\d\.]+) Evasion$/, '\+$1 闪避'],
    [/^\+([\d\.]+) Life$/, '\+$1 生命值'],
    [/^\+([\d\.]+) Life Regen Of Total \%$/, '\+$1 生命回复对于总计 %'],
    [/^\+([\d\.]+) Mana regeneration % of total mana$/, '\+$1 法力回复对于总法力'],
    [/^\+([\d\.]+) crystal per hour$/, '每小时 \+$1 水晶'],
    [/^\+([\d\.]+) soul per hour$/, '每小时 \+$1 灵魂'],
    [/^\+([\d\.]+) gold per minute$/, '每分钟 \+$1 金币'],
    [/^\+([\d\.]+) Starting Stage$/, '\+$1 初始关卡'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/, '$1小时 $2分 $3秒'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^ \(Lvl ([\d\.,]+)\)$/, ' (等级 $1)'],
    [/^\(for ([\d\.,]+) hours\)$/, '(持续 $1 小时)'],
    [/^\(for ([\d\.,]+) minutes\)$/, '(持续 $1 分钟)'],
    [/^([\d\.,]+) Souls$/, '$1 灵魂'],
    [/^([\d\.,]+) Crystals$/, '$1 水晶'],
    [/^([\d\.,]+) attacks\/second$/, '$1 攻击/秒'],
    [/^([\d\.,]+) Gold$/, '$1 金币'],
    [/^([\d\.,]+) \/ ([\d\.,]+) XP$/, '$1 / $2 经验值'],
    [/^Lvl ([\d\.,]+)\/([\d\.,]+)$/, '等级 $1/$2'],
    [/^Points: ([\d\.,]+) \/ ([\d\.,]+)$/, '点数: $1 / $2'],
    [/^([\d\.,]+) gold, ([\d\.,]+) crystal, ([\d\.,]+) soul$/, '$1 金币，$2 水晶，$3 灵魂'],
    [/^Sell \/ Refund \(\+([\d\.,]+) gold\)$/, '出售 / 退款 (\+$1 金币)'],
    [/^Sell \/ Refund \(\+([\d\.,]+) gold, ([\d\.,]+) crystal\)$/, '出售 / 退款 (\+$1 金币, $2 水晶)'],
    [/^Sell \/ Refund \(\+([\d\.,]+) gold, ([\d\.,]+) crystal, ([\d\.,]+) soul\)$/, '出售 / 退款 (\+$1 金币, $2 水晶，$3 灵魂)'],
    [/^([\d\.,]+) crystals$/, '$1 水晶'],
    [/^ \% \(Lvl ([\d\.,]+)\)$/, ' \% \(等级 $1\)'],
    [/^([\d\.,]+) SP$/, '$1 技能点'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) gold$/, '$1 金币'],
    [/^([\d\.,]+) gold, ([\d\.,]+) soul$/, '$1 金币，$2 灵魂'],
    [/^([\d\.,]+) gold, ([\d\.,]+) crystal$/, '$1 金币，$2 水晶'],
    [/^([\d\.,]+) characters left$/, '剩余 $1 字符'],
    [/^Cannot upgrade Starting Stage above ([\d\.,]+). Reach a higher stage to unlock more.$/, '初始关卡不能升级到 $1 以上。到达更高的关卡以解锁更多。'],
    [/^Requires Level ([\d\.,]+)$/, '要求等级 $1'],
    [/^Requires Level ([\d\.,]+) \& ([\d\.,]+) Crystals$/, '要求等级 $1 \& $2 水晶'],
    [/^Slot ([\d\.,]+) \- Empty$/, '槽位 $1 - 空'],
    [/^Slot ([\d\.,]+) \- Peasant Lv ([\d\.,]+) \(Current\)$/, '槽位 $1 - 农民 $2 级（当前）'],
    [/^Cost: ([\d\.,]+)$/, '成本: $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Tier ([\d\.,]+)$/, '层级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Level ([\d\.,]+), Tier ([\d\.,]+)$/, '等级 $1，层级 $2'],
    [/^\(Lvl ([\d\.,]+)\)$/, '（等级 $1）'],
    [/^\(\+([\d\.,]+) soul\)$/, '（\+$1 灵魂'],
    [/^\(\+([\d\.,]+) gold\)$/, '（\+$1 金币'],
    [/^\(\+([\d\.,]+) crystal\)$/, '（\+$1 水晶）'],
    [/^Buy ([\d\.,]+) for ([\d\.,]+) SP$/, '购买 $1 花费 $2 技能点'],
    [/^Increases strength by ([\d\.,]+).$/, '提高 力量 $1。'],
    [/^Increases wisdom by ([\d\.,]+).$/, '提高 智慧 $1。'],
    [/^Increases vitality by ([\d\.,]+).$/, '提高 活力 $1。'],
    [/^Increases dexterity by ([\d\.,]+).$/, '提高 灵巧 $1。'],
    [/^Deal ([\d\.,]+) damage in a single hit.$/, '在一次攻击中造成 $1 伤害。'],
    [/^Reach level ([\d\.,]+).$/, '达到等级 $1。'],
    [/^Reach stage ([\d\.,]+).$/, '达到关卡 $1。'],
    [/^Reach stage ([\d\.,]+) \(Tier ([\d\.,]+)\)$/, '达到关卡 $1 (层 $2)'],
    [/^Reach stage ([\d\.,]+) in tier ([\d\.,]+)$/, '在层级 $2 达到关卡 $1'],
    [/^Defeat ([\d\.,]+) mythic enemies.$/, '击败 $1 神话 敌人。'],
    [/^Defeat ([\d\.,]+) epic enemies.$/, '击败 $1 史诗 敌人。'],
    [/^Defeat ([\d\.,]+) rare enemies.$/, '击败 $1 稀有 敌人。'],
    [/^Defeat ([\d\.,]+) legendary enemies.$/, '击败 $1 传说 敌人。'],
    [/^Defeat ([\d\.,]+) legendary enemie.$/, '击败 $1 传说 敌人。'],
    [/^Defeat ([\d\.,]+) legendary enemy.$/, '击败 $1 传说 敌人。'],
    [/^Defeat ([\d\.,]+) mythic enemie.$/, '击败 $1 神话 敌人。'],
    [/^Defeat ([\d\.,]+) mythic enemy.$/, '击败 $1 神话 敌人。'],
    [/^Defeat ([\d\.,]+) epic enemie.$/, '击败 $1 史诗 敌人。'],
    [/^Defeat ([\d\.,]+) rare enemie.$/, '击败 $1 稀有 敌人。'],
    [/^Defeat ([\d\.,]+) enemies.$/, '击败 $1 敌人。'],
    [/^Grants ([\d\.,]+) skill point.$/, '给予 $1 技能点。'],
    [/^Upgraded SWORD \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 剑 (等级 $1 → $2)'],
    [/^Upgraded GLOVES \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 手套 (等级 $1 → $2)'],
    [/^Upgraded BELT \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 腰带 (等级 $1 → $2)'],
    [/^Upgraded SHIELD \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 盾牌 (等级 $1 → $2)'],
    [/^Upgraded BOOTS \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 靴子 (等级 $1 → $2)'],
    [/^Upgraded ARMOR \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 护甲 (等级 $1 → $2)'],
    [/^Upgraded AXE \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 斧子 (等级 $1 → $2)'],
    [/^Upgraded HELMET \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 头盔 (等级 $1 → $2)'],
    [/^Upgraded PANTS \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 裤子 (等级 $1 → $2)'],
    [/^Upgraded MACE \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 权杖 (等级 $1 → $2)'],
    [/^Upgraded RING \(Lvl ([\d\.,]+) → ([\d\.,]+)\)$/, '升级 戒指 (等级 $1 → $2)'],
    [/^Used ([\d\.,]+) Elixirs$/, '使用了 $1 万灵药'],
    [/^Used ([\d\.,]+) Crystalized Rock$/, '使用了 $1 结晶岩石'],
    [/^Used ([\d\.,]+) Crystalized Rocks$/, '使用了 $1 结晶岩石'],
    [/^Used ([\d\.,]+) Experience Potions$/, '使用了 $1 经验药水'],
    [/^Used ([\d\.,]+) Experience Potion$/, '使用了 $1 经验药水'],
    [/^Used ([\d\.,]+) Medium Gold Coin$/, '使用了 $1 中金币'],
    [/^Used ([\d\.,]+) Medium Gold Coins$/, '使用了 $1 中金币'],
    [/^Used ([\d\.,]+) Large Gold Coins$/, '使用了 $1 大金币'],
    [/^Used ([\d\.,]+) Enormous Gold Coins$/, '使用了 $1 巨金币'],
    [/^Used ([\d\.,]+) Potion of Wisdom$/, '使用了 $1 智慧药水'],
    [/^Used ([\d\.,]+) Potion of Wisdoms$/, '使用了 $1 智慧药水'],
    [/^Used ([\d\.,]+) Potion of Vitality$/, '使用了 $1 活力药水'],
    [/^Used ([\d\.,]+) Potion of Vitalitys$/, '使用了 $1 活力药水'],
    [/^Used ([\d\.,]+) Potion of Dexterity$/, '使用了 $1 灵巧药水'],
    [/^Used ([\d\.,]+) Potion of Dexteritys$/, '使用了 $1 灵巧药水'],
    [/^Used ([\d\.,]+) Potion of Endurance$/, '使用了 $1 灵巧药水'],
    [/^Used ([\d\.,]+) Potion of Endurances$/, '使用了 $1 耐力药水'],
    [/^Used ([\d\.,]+) Potion of Strength$/, '使用了 $1 力量药水'],
    [/^Used ([\d\.,]+) Potion of Strengths$/, '使用了 $1 力量药水'],
    [/^Used ([\d\.,]+) Potion of Agilitys$/, '使用了 $1 敏捷药水'],
    [/^Used ([\d\.,]+) Potion of Agility$/, '使用了 $1 敏捷药水'],
    [/^Used ([\d\.,]+) Medium Gold Coinss$/, '使用了 $1 中金币'],
    [/^Used ([\d\.,]+) Large Gold Coinss$/, '使用了 $1 大金币'],
    [/^Gives ([\d\.,]+) crystal.$/, '给予 $1 水晶。'],
    [/^Gives ([\d\.,]+) crystal.$/, '给予 $1 水晶。'],
    [/^Collect ([\d\.,]+) materials.$/, '收集 $1 材料。'],
    [/^Find ([\d\.,]+) items.$/, '发现 $1 物品。'],
    [/^Upgraded Life Boost \% by ([\d\.,]+) levels$/, '已升级 生命提升 \% $1 级。'],
    [/^Upgraded Mana Boost \% by ([\d\.,]+) levels$/, '已升级 法力提升 \% $1 级。'],
    [/^Upgraded Damage Boost \% by ([\d\.,]+) levels$/, '已升级 伤害提升 \% $1 级。'],
    [/^Upgraded Bonus Experience \% by ([\d\.,]+) levels$/, '已升级 奖励经验 \% $1 级。'],
    [/^Upgraded Bonus Gold \% by ([\d\.,]+) levels$/, '已升级 奖励金币 \% $1 级。'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Total Earned: (.+) crystal$/, '总计赚取：$1 水晶'],
    [/^Total Earned: (.+) gold$/, '总计赚取：$1 金币'],
    [/^Total Earned: (.+) soul$/, '总计赚取：$1 灵魂'],
    [/^Base: (.+) damage$/, '基础：$1 伤害'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();