// ==UserScript==
// @name         Galactic Tycoons 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.5
// @description  网页游戏 Galactic Tycoons (https://galactictycoons.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Galactic Tycoons.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://galactictycoons.com/favicon.ico
// @license      MIT
// @include      *galactictycoons.com*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/galactic-tycoons-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/galactic-tycoons-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/10/10 12:56
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Accept": "同意",
    "Your entrepreneur journey begins with a single base on a strategically chosen planet – your first foothold in a vast galaxy brimming with opportunity. From this modest foundation, you'll expand your operations, carefully planning each step as you build, produce, and strategize your way to the top.": "您的创业之旅始于一个战略选择的星球上的单一基地-您的第一个立足点在一个巨大的星系充满机会。从这个适度的基础上，您将扩展您的业务，仔细规划您构建，生产和战略的每一步，以达到顶峰。",
    "No single player can master every industry in this space tycoon game. Choose your specializations wisely, focusing on key areas to become a dominant force in your chosen field. Will you control the flow of vital resources, become a manufacturing powerhouse, or a pioneer of cutting-edge technology?": "在这个太空大亨的游戏中，没有一个玩家可以精通每个行业。明智地选择你的专业，专注于关键领域，成为你所选择领域的主导力量。你会控制重要资源的流动，成为制造业强国，还是尖端技术的先驱？",
    "Mastering the flow of goods is paramount. A well-optimized logistics system will keep your factories humming, your workforce supplied, and your treasury overflowing. Neglect it, and your empire will face stagnation.": "掌握货物的流动是最重要的。一个优化的物流系统将使你的工厂保持运转，你的劳动力供应充足，你的资金充裕。忽视它，你的帝国将面临停滞。",
    "Colonization is a crucial strategic element. Carefully analyze resource yields, calculate transport routes, and optimize the layout of your bases. The right location can be the cornerstone of a thriving empire.": "殖民化是一个至关重要的战略要素。仔细分析资源产量，计算运输路线，优化你的基地布局。合适的地点可以成为一个繁荣帝国的基石。",
    "Colonize new worlds, increase your industrial output, and optimize your production processes. With each successful venture, your wealth and influence will grow, transforming your fledgling outpost into a major economic power.": "开拓新世界，增加你的工业产出，优化你的生产流程。随着每一次成功的冒险，你的财富和影响力将会增长，把你羽翼未丰的前哨变成一个主要的经济力量。",
    "Craft a complex industrial network spanning multiple specialized industries. Mine raw ores, refine them into valuable metals, and manufacture everything from essential tools to advanced starship components. The interconnected production chains offer endless opportunities for optimization and strategic planning.": "打造一个跨越多个专业行业的复杂产业网络。开采矿石，提炼成有价值的金属，制造从基本工具到先进的星际飞船部件的一切。相互关联的生产链为优化和战略规划提供了无限的机会。",
    "Explore a vast and diverse galaxy, teeming with planets, each possessing unique resource distributions and environmental challenges. Strategically colonize new worlds, balancing the potential rewards with the logistical hurdles. The further you venture, the greater the riches - and the greater the risks.": "探索一个巨大而多样的星系，充满了行星，每个行星都拥有独特的资源分布和环境挑战。战略性地开拓新世界，平衡潜在的回报和后勤障碍。你越冒险，财富就越多，风险也越大。",
    "Galactic Tycoons is a persistent, multiplayer, free browser strategy game where you build and manage your interstellar industrial corporation. Build bases across a diverse galaxy, manage intricate production chains, and compete in a truly player-driven economy.": "银河大亨是一个持久的，多人，免费的浏览器策略游戏，你建立和管理你的星际工业公司。在不同的星系中建立基地，管理复杂的生产链，并在真正的玩家驱动的经济中竞争。",
    "Galactic Tycoons is a universe of both cooperation and competition. Forge alliances with other players by joining or creating powerful Guilds. Collaborate on large-scale projects, share resources, and unlock exclusive guild benefits.": "银河大亨是一个既合作又竞争的宇宙。通过加入或创建强大的公会与其他玩家结成联盟。合作大型项目，共享资源，并解锁专属公会利益。",
    "Stay ahead of the technological curve to gain a decisive advantage. Discover rare resources, develop advanced technologies, and secure your place at the forefront of galactic progress.": "在技术曲线上保持领先，获得决定性的优势。发现稀有的资源，发展先进的技术，并确保你在银河进步的最前沿。",
    "The Galactic Exchange is the beating heart of the game's player-driven economy. Here, you'll trade resources, components, and finished goods with other players, setting your own prices and reacting to the ever-shifting forces of supply and demand.": "银河交易所是游戏中玩家驱动经济的核心。在这里，你将与其他玩家交易资源、组件和成品，设定自己的价格，并对不断变化的供需力量做出反应。",
    "The path to galactic dominance is paved with technological innovation. Invest in research to unlock new buildings, more efficient production methods, and access to previously unreachable corners of the galaxy.": "称霸银河系的道路是由技术创新铺就的。投资研究以解锁新建筑，更有效的生产方法，并进入以前无法到达的银河系角落。",
    "Your empire's success hinges on a robust and efficient interstellar logistics network. Build and upgrade a fleet of transport ships to move goods between your bases and the central Galactic Exchange. Invest in larger cargo capacities and advanced engines to maximize profits and extend your reach.": "你的帝国的成功取决于一个强大而高效的星际物流网络。建造并升级一支运输船舰队，在你的基地和银河中央交易所之间运送货物。投资更大的货物容量和先进的引擎，以最大限度地提高利润和扩大业务范围。",
    "Become a master of the market. Anticipate trends, negotiate profitable deals, and outmaneuver your competitors to amass wealth and power. Every transaction you make shapes the economic landscape of the galaxy.": "成为市场的主人。预测趋势，谈判有利可图的交易，智取你的竞争对手来积累财富和权力。你所做的每一笔交易都会影响银河系的经济格局。",
    "Begin your cosmic journey and build a sprawling empire from a single planetary outpost. Mine resources, manufacture goods, and trade your way to dominance in a dynamic, player-driven economy. Forge your legacy among the stars!": "开始你的宇宙之旅，从一个单一的行星前哨建立一个庞大的帝国。挖掘资源，制造商品，在一个动态的，玩家驱动的经济中以你的方式统治。在群星间打造你的传奇！",
    "A Galaxy Ripe for the Taking": "一个成熟的星系",
    "Alliances and Conflicts": "联盟与冲突",
    "BUILD": "建造",
    "BUILD. PRODUCE. TRADE. PROSPER.": "建造。生产。贸易。繁荣。",
    "But remember, the galaxy is also a place of fierce competition. Rivalries will emerge, and only the most cunning and adaptable tycoons will rise to the top.": "但请记住，银河系也是一个竞争激烈的地方。竞争将会出现，只有最狡猾、适应性最强的大亨才会上升到顶端。",
    "Construct bases, factories, and infrastructure across multiple planets.": "在多个星球上建造基地、工厂和基础设施。",
    "Cookie Policy": "Cookie策略",
    "Decline": "拒绝",
    "Forge Your Industrial Empire": "打造你的工业帝国",
    "Galactic Tycoons": "银河大亨",
    "GALACTIC TYCOONS": "银河大亨",
    "Grow your wealth and dominate the galactic economy.": "增长你的财富，主宰银河经济。",
    "Humble Beginnings, Galactic Ambitions": "卑微的开始，银河的野心",
    "Interstellar Logistics": "星际物流",
    "PLAY FOR FREE": "免费试玩",
    "Privacy Policy": "隐私政策",
    "PRODUCE": "生产",
    "Produce goods and manage interstellar logistics.": "生产货物和管理星际物流。",
    "PROSPER": "繁荣",
    "Reach for the Stars": "摘星",
    "RYNEDA": "RYNEDA",
    "Space Economy Game": "太空经济游戏",
    "Specialize your production, compete, trade, and cooperate with other players to grow your empire from a single outpost to a major economic power.": "专业化你的生产，竞争，贸易，并与其他玩家合作，发展你的帝国从一个单一的前哨到一个主要的经济力量。",
    "Terms & Conditions": "条款与条件",
    "This site uses cookies for analytics to improve your experience.": "本网站使用cookie进行分析，以改善您的体验。",
    "TRADE": "贸易",
    "Trade and Prosper": "贸易与繁荣",
    "Trade goods in a dynamic, player-driven market.": "在一个动态的、玩家驱动的市场中交易商品。",
    "WHAT IS": "是什么",
    "Already have an account?": "已经有账户了？",
    "and": "和",
    "Continue": "继续",
    "Create Account": "创建账户",
    "Don't have an account yet?": "还没有账户？",
    "Forgot your password?": "忘记密码了？",
    "I accept": "我接受",
    "or": "或",
    "Password cannot be the same as email.": "密码不能与电子邮件相同。",
    "Please enter a valid email address.": "请输入有效的电子邮件地址。",
    "Sign In": "登录",
    "Sign In with Facebook": "使用Facebook登录",
    "Sign In with Google": "使用谷歌账号登录",
    "Terms of Service": "服务条款",
    "You must accept the terms of service.": "你必须接受服务条款。",
    "Passwords must match.": "密码必须匹配。",
    "We've sent you an activation email. Click the \"Activate Account\" button in the email to finish registration.": "我们已经给你发了一封激活邮件。点击电子邮件中的“激活帐户”按钮完成注册。",
    "Establish iron mining operations and smelting facilities to produce metal ingots crucial for manufacturing and construction.": "建立铁矿开采和冶炼设施，以生产对制造业和建筑业至关重要的金属锭。",
    "Distance from Exchange": "距离交易所的距离",
    "Dark Matter": "暗物质",
    "Create Company": "创建公司",
    "Create company": "创建公司",
    "Exchange Station": "交换站",
    "Farming buildings (Farm, Orchard, Aquaponics Farm) cannot be built on planets with 0% fertility.": "农业建筑（农场、果园、水培农场）不能建造在肥力为0%的星球上。",
    "Fertility of 100% represents the baseline speed. ": "100%的肥沃度代表基准速度。",
    "Food Production": "食物生产",
    "Starting Buildings": "初始建筑",
    "Starting Resources": "初始资源",
    "Small, lifeless planet with jagged peaks and deep chasms scarring its barren rocky surface.": "这颗小而无生命的星球有着参差不齐的山峰，在贫瘠的岩石表面留下了深深的裂缝。",
    "This planet has high concentrations of resources needed for your starting package. Extraction will be very efficient.": "这个星球高度集中了你的启动包所需的资源。提取将非常有效。",
    "Titanium Ore": "钛矿石",
    "Transporting will be fast and won't use much fuel.": "运输速度很快，而且不会消耗太多燃料。",
    "Uranium Ore": "铀矿石",
    "fertility impacts farming production speed.": "肥力影响农耕生产速度",
    "Select Package": "选择启动包",
    "Select your starting package.": "选择你的启动包。",
    "Select starting package": "选择启动包",
    "Select starting planet": "选择初始星球",
    "This choice determines your initial resources and home planet. Don't worry - you'll be able to pursue any specialization later in the game.": "这个选择决定了你最初的资源和母星。别担心-你可以在游戏后期追求任何专业。",
    "Company name": "公司名称",
    "Construction Vehicle": "工程车辆",
    "Constructor": "建造者",
    "Gas Collector": "气体收集器",
    "Mine": "矿井",
    "Smelter": "冶炼厂",
    "Abundance percentage (number on the left) determines extraction speed of the resource. Abundance of 100% represents the baseline speed.": "丰度百分比（左边的数字）决定了资源的提取速度。丰度为100%表示基线速度。",
    "Available resources on this planet.": "当前星球可用资源。",
    "Distance": "距离",
    "Fertility": "肥沃度",
    "Tier": "等阶",
    "Medium-sized, lifeless planet with jagged peaks and deep chasms scarring its barren rocky surface.": "中等大小，没有生命的星球，有参差不齐的山峰，在贫瘠的岩石表面留下深深的裂缝。",
    "Tiny, lifeless planet with jagged peaks and deep chasms scarring its barren rocky surface.": "这颗行星很小，没有生命，参差不齐的山峰和深深的裂缝在它贫瘠的岩石表面留下伤痕。",
    "Small lifeless planet with rocky landscapes, expansive water bodies and a thin atmosphere.": "一个没有生命的小星球，有岩石地貌，广阔的水体和稀薄的大气层。",
    "Manufacturing": "制造业",
    "Metallurgist": "冶金家",
    "Refining": "精炼",
    "Base": "基地",
    "Bases": "基地",
    "Buildings": "建筑",
    "Comms": "通讯",
    "Click 'Next' to continue.": "点击“下一步”继续。",
    "Company": "公司",
    "Exchange": "交易所",
    "FAQ": "FAQ",
    "Galaxy": "星系",
    "Gityx": "Gityx",
    "Guild": "公会",
    "Headquarters": "总部",
    "Join Discord": "加入 Discord",
    "Minimize": "最小化",
    "Missions": "任务",
    "Next": "下一步",
    "Production": "生产",
    "Research": "研究",
    "Return to Lobby": "返回大厅",
    "Ships": "飞船",
    "Skip Tutorial": "跳过教程",
    "Introduction": "介绍",
    "Warehouse": "仓库",
    "Welcome to": "欢迎来到",
    "Workforce": "劳动力",
    "! This quick tutorial will help you set up your base and start production.": "!这个快速教程将帮助您建立您的基地，并开始生产。",
    "Accelerating": "加速",
    "Acceleration": "加速",
    "Acceleration:": "加速:",
    "Add ship slot": "增加船位",
    "Advanced Efficient": "高级高效",
    "Advanced Long Range": "高级远程",
    "Advanced Short Range": "高级近程",
    "Antimatter": "反物质",
    "Antimatter Reactor": "反物质反应堆",
    "Avg Speed": "平均速度",
    "Basic": "基础",
    "Cargo": "货物",
    "Cargo:": "货物:",
    "Cargo Bay": "货舱",
    "Cargo bay size": "货舱大小",
    "Characteristics": "特性",
    "Chosen ship modifications require no additional materials.": "所选飞船的改装不需要额外的材料。",
    "Construct Ship": "建造飞船",
    "Construction Cost": "建造成本",
    "Damage reduction": "伤害减免",
    "Efficiency": "效率",
    "Energy draw:": "能源消耗:",
    "Fission Fuel": "裂变燃料",
    "Fission Reactor": "裂变反应堆",
    "FTL Capacity": "超光速容量",
    "FTL Emitters": "超光速发射器",
    "FTL type": "超光速类型",
    "Fuel": "燃料",
    "Fuel Capacity": "燃料容量",
    "Fuel Tank": "燃料罐",
    "Fuel tank size": "燃料罐大小",
    "Fuel:": "燃料:",
    "Heat shielding": "隔热护盾",
    "Light": "轻型",
    "Heavy": "重型",
    "Hydrogen Fuel": "氢燃料",
    "Large": "大",
    "Layout": "布局",
    "Linear Emitter": "线性发射器",
    "ly": "光年",
    "ly/h": "光年/小时",
    "ly/h²": "光年/小时²",
    "ly/h² (max speed reached after 1.27 hours traveled)": "光年/小时²（行驶1.27小时后达到的最高速度）",
    "Max. Speed:": "最大速度:",
    "Maximum Speed": "最大速度",
    "Medium": "中",
    "Name": "名称",
    "Power": "动力",
    "Power:": "动力:",
    "Radiation shielding": "辐射护盾",
    "Reactor": "反应堆",
    "Reactors": "反应堆",
    "Simulation": "模拟",
    "Small": "小",
    "Superior Efficient": "卓越高效",
    "Superior Long Range": "卓越远程",
    "Superior Short Range": "卓越近程",
    "Travel Time": "旅行时间",
    "Weight empty": "空载重量",
    "Weight full": "满载重量",
    "Click on the 'Buildings' tab.": "点击“建筑”选项卡。",
    "Colony Barracks": "殖民地兵营",
    "Demolish Base": "拆除基地",
    "Fly here": "飞到这里",
    "Great job! You've built all recommended buildings. Let's start production.": "干得好！你已经建造了所有推荐的建筑。让我们开始生产。",
    "chat": "聊天",
    "Let's build the essential buildings for your base.": "让我们为你的基地建造一些重要的建筑。",
    " Buildings": "建筑",
    "Rename base": "重命名基地",
    "Resources": "资源",
    "Get more": "获取更多",
    "Tutorial": "教程",
    "Click on any empty building plot to construct a new building.": "点击任何一个空的建筑地块来建造一个新的建筑。",
    "Your base has empty plots for buildings. For basic production, you'll need Colony Barracks for your workforce and production buildings. You already have all required materials.": "你的基地有空地用来建造建筑。对于基本的生产，你需要殖民地兵营作为你的劳动力和生产建筑。你已经有了所有需要的材料。",
    "Advanced Assembly Plant": "高级装配厂",
    "Advanced Gas Collector": "高级气体收集器",
    "Advanced Materials Lab": "高级材料研究室",
    "Advanced Prefab Plant": "高级预制工厂",
    "Agriculture": "农业",
    "Apex Prefab Plant": "极品预制工厂",
    "Aquaponics Farm": "水培农场",
    "Assembly Plant": "装配厂",
    "Build": "建造",
    "Chemical Plant": "化工厂",
    "Click the 'Build' button next to a building to construct it.": "点击建筑物旁边的“建造”按钮来建造它。",
    "Comfort Quarters": "舒适的宿舍",
    "Construction": "建筑",
    "Culinary Studio": "烹饪工作室",
    "Electronics": "电子产品",
    "Electronics Factory": "电子厂",
    "Exotic Matter Lab": "奇异物质实验室",
    "Extracts gaseous resources.": "提取气体资源。",
    "Extracts liquid resources.": "提取液体资源。",
    "Extracts solid resources.": "提取固体资源。",
    "Farm": "农场",
    "Farming is not possible on this planet.": "农业在这个星球上是不可能的。",
    "Food Processing Plant": "食品加工厂",
    "Foundry": "铸造厂",
    "Housing": "住房",
    "Increases base warehouse capacity by 1500t per level": "每级增加基地仓库容量1500吨",
    "Laboratory": "实验室",
    "Metallurgy": "冶金",
    "Micronics Factory": "微型工厂",
    "Nanomaterial Lab": "纳米材料实验室",
    "New building": "新建筑",
    "Orchard": "果园",
    "Polymer Plant": "聚合物工厂",
    "Prefab Plant": "预制工厂",
    "Pump": "泵",
    "Quantum Factory": "量子工厂",
    "Quantum Nexus": "量子枢纽",
    "Quarry Complex": "采石场综合体",
    "Ranch": "牧场",
    "Refinery": "炼油厂",
    "Residential Complex": "住宅综合体",
    "Resource Extraction": "资源提取",
    "Robotics Facility": "机器人设施",
    "Science": "科学",
    "Science Institute": "科学研究所",
    "Semiconductor Foundry": "半导体",
    "Shipyard": "船厂",
    "Stellar Suites": "恒星套房",
    "Survey Station": "测量站",
    "Textile Mill": "纺织厂",
    "There are no gases to extract from this planet.": "这个星球上没有气体可以提取。",
    "There are no liquids to extract from this planet.": "这个星球上没有液体可以提取。",
    "There are no resources to mine on this planet.": "这个星球上没有可供开采的资源。",
    "Welding Plant": "焊接工厂",
    "Idle - Start production": "空闲 - 开始生产",
    "Level": "等级",
    "Description": "介绍",
    "Your": "你的",
    "Upgrade cost": "升级成本",
    "Upgrade": "升级",
    "Repair": "修理",
    "Bases slots": "基地槽位",
    "Condition -": "条件-",
    "headquarters": "总部",
    "Producing": "生产",
    "Recovered materials": "回收材料",
    "Repair cost": "维修成本",
    "Repair is only possible after condition drops bellow 90%.": "只有在状态下降到90%以下时才能进行维修。",
    "Scrap": "废料",
    "serves as the foundation of your interstellar corporation.": "作为你星际公司的基础。",
    "Specialization": "专业化",
    "This screen shows your workforce details. You can click on the Worker row to see details. Essential consumables are critical for maintaining workforce satisfaction, which affects production speed. The 'Total consumption' table shows how long each supply will last. You can acquire consumables on the exchange.": "此屏幕显示您的员工详细信息。您可以单击工人行以查看详细信息。基本消耗品对于维持员工满意度至关重要，这影响到生产速度。“总消耗”表显示了每次供应的持续时间。你可以在交易所购买消耗品。",
    "Consider increasing production capacity by constructing more buildings at your base. You likely have enough cash to buy the needed construction materials via the exchange - just remember they have to be shipped to your base after purchase before you can begin building.": "考虑通过在你的基地建造更多的建筑来增加生产能力。你可能有足够的现金通过交易所购买所需的建筑材料-只是记住，他们必须在购买后运到你的基地，然后你才能开始建造。",
    "Claim": "领取",
    "CLAIMED": "已领取",
    "Create order": "创建订单",
    "Daily": "日常",
    "Daily production": "日常生产",
    "Daily Production": "日常生产",
    "Daily Login": "日常登录",
    "Daily Login reward.": "日常登录奖励。",
    "Defense pack": "防御包",
    "Jobs": "工作",
    "Input": "输入",
    "Hydrogen": "氢气",
    "Have fun!": "玩得开心!",
    "Free": "空闲",
    "No Task": "暂无任务",
    "Order": "订单",
    "Orders": "订单",
    "Output": "输出",
    "Pie": "馅饼",
    "Time": "时间",
    "to": "到",
    "Tools": "工具",
    "Medicine": "药品",
    "Let's check your workers.": "我们看看你的工人。",
    "Add Order": "添加订单",
    "Build or upgrade 1 building.": "建造或升级一座建筑。",
    "Build or upgrade building.": "建造或升级建筑。",
    "Build or upgrade buildings.": "建造或升级建筑。",
    "Build new bases.": "建造新基地。",
    " Ore": "矿石",
    "Ale": "啤酒",
    "Choose later": "稍后选择",
    "Explore": "探索",
    "Exploration": "勘探",
    "Exploration Mission": "勘探任务",
    "Drinking Water": "饮用水",
    "Flux": "通量",
    "Food Shipment": "粮食运输",
    "Rewards:": "奖励:",
    "Workwear": "工作服",
    "Reserve": "储备",
    "Tech": "科技",
    "Select": "选择",
    "Select a factory without orders.": "选择一个没有订单的工厂。",
    "Research new technologies.": "研究新技术。",
    "Reroll choices": "重新选择",
    "Provisions": "供应",
    "Rations": "给养",
    "Maintenance": "维持",
    "Chart the unexplored corners of the galaxy.": "绘制出银河系未被探索过的角落。",
    "Check the Missions tab for any available missions that offer valuable rewards.": "检查任务选项卡中任何提供有价值奖励的任务。",
    "Click on the 'Production' tab.": "点击“生产”选项卡。",
    "Click on the 'Workforce' tab.": "点击“劳动力”选项卡。",
    "Click the 'Add Order' button.": "点击“添加订单”按钮。",
    "Complete missions.": "完成任务。",
    "Complete Tutorial": "完成教程",
    "Congratulations on finishing the tutorial!": "恭喜你完成了教程！",
    "Deliver": "交付",
    "Development": "发展",
    "Donate materials to a guild project.": "向公会项目捐赠材料。",
    "Donations": "捐赠",
    "Expansion": "扩张",
    "Expansion overhead:": "扩张开销:",
    "Expansion Project": "扩建项目",
    "Extend your corporate footprint across the stars by constructing or upgrading your buildings.": "通过建造或升级你的建筑来扩展你的企业足迹。",
    "Factories": "工厂",
    "Fine-tune your production orders.": "调整你的生产订单。",
    "Here are some ideas for your next steps:": "以下是你下一步的一些建议：",
    "Monitor your warehouse regularly, purchase inputs when needed, and transport finished goods to the exchange for profit.": "定期监控您的仓库，在需要时购买输入，并将成品运输到交易所以获取利润。",
    "New Mission Available": "新任务可用",
    "New mission available.": "新任务可用。",
    "Now let's set up production orders for all your factories.": "现在让我们为你们所有的工厂建立生产订单。",
    "Produce materials.": "生产材料。",
    "Production underway! Your economic cycle is now active: materials are consumed → products are created → profits can be made.": "生产进行中!你的经济周期现在是活跃的：材料被消耗→产品被创造→利润被创造。",
    "Productivity": "生产力",
    "Provide your workforce with substantial amounts of consumables.": "为你的员工提供大量的消耗品。",
    "Repair buildings.": "修理建筑物。",
    "Requires technology:": "需要科技:",
    "Review the exchange to find the most profitable materials you can produce.": "查看交易所，找到你能生产的最赚钱的材料。",
    "Satisfaction": "满意度",
    "Select a recipe to produce.": "选择要生产的配方。",
    "Select how many times to produce the selected recipe (10+ recommended to keep factory running).": "选择所选配方的生产次数（建议生产10次以上，以保证工厂正常运行）。",
    "Select one new mission": "选择一个新任务",
    "Special Delivery Contract": "特殊交付合同",
    "Terraform building plots.": "地形建筑地块。",
    "Terraforming": "地形改造",
    "Total consumption": "总消耗",
    "Transport priority-tagged resources to the specified planet under exclusive contract.": "根据独家合同将优先标记的资源运输到指定的星球。",
    "Travel vast cosmic distances with your fleet.": "带着你的舰队穿越浩瀚的宇宙。",
    "There are no production buildings in this base.": "该基地暂无生产建筑。",
    "An advanced energy conversion system that utilizes hydrogen fuel cells to generate electricity.": "利用氢燃料电池发电的先进能源转换系统。",
    "Unable to establish a connection. Retrying shortly...": "无法建立连接。正在重试...",
    " condition:": " 条件:",
    "Calculated from": "计算从",
    "Daily login reward.": "每日登录奖励。",
    "If insufficient input materials are available, factories will skip production or work on other orders.": "如果输入材料不足，工厂将停止生产或生产其他订单。",
    "in the exchange, dont just get any prefabs, get the Poe's PREMIER prefabs!": "在交换中，不要只是得到任何预制件，得到坡的首要预制件！",
    "Notifications": "通知",
    "Poes Premier Prefabs:": "坡的首要预制件：",
    "Produce": "生产",
    "Production Contract": "生产合同",
    "production order completed.": "生产订单已完成。",
    "Production speed:": "生产速度:",
    "Required workforce:": "所需人力：",
    "Technology multiplier:": "技术乘数:",
    "Theoretical daily material inputs and outputs at current productivity.": "按当前生产率计算的理论每日材料投入和产出。",
    "Transform raw materials into finished products to meet the insatiable demands of rapidly expanding frontier colonies.": "将原材料转化为成品，以满足迅速扩张的边疆殖民地的永不满足的需求。",
    "Workforce satisfaction:": "员工满意度:",
    "Consumables": "消耗品",
    "Desktop": "桌面",
    "In-game": "游戏内",
    "Reset company": "重置公司",
    "Resets your company progress.": "重置你的公司进度。",
    "Sound": "声音",
    "This will delete your: Company, Cash, Bases, Ships, Technologies, Warehouses, etc.": "这将删除你的：公司，现金，基地，船舶，科技，仓库等。",
    "Trade": "贸易",
    "Volume:": "体积:",
    "Warehouses": "仓库",
    "Your stars will not be removed.": "你的星星不会被移除。",
    "Scientific Shipment": "科学运输",
    "Connection failed": "连接失败",
    "Connection attempt failed.": "连接尝试失败。",
    "To complete the objective, simply fly one of your ships to the specified planet.": "要完成目标，只需驾驶你的一艘船到指定的星球。",
    "You will receive the materials needed to complete this mission to your exchange warehouse.": "您将收到完成此任务所需的材料到您的交换仓库。",
    "Meteor": "流星",
    "Milkyway": "银河系",
    "Mimosa": "含羞草",
    "Nocturne": "夜曲",
    "Kentaurus": "肯塔鲁斯",
    "Kaleidoscope": "万花筒",
    "Amethyst": "紫水晶",
    "Reverie": "幻想",
    "Amalthea": "木卫五",
    "Channels": "频道",
    "Contacts": "联系人",
    "Help": "帮助",
    "Global": "全局",
    "Add contact": "添加联系人",
    "has established a base": "建立了一个基地",
    "Add": "添加",
    "Advanced Research": "高级研究",
    "Current Level": "当前等级",
    "Next Level": "下一级",
    "Research Time": "研究时长",
    "Research Data": "研究数据",
    "Research Cost": "研究成本",
    "Research in progress": "进行中的研究",
    "Reset Technologies": "重置科技",
    "Technologies": "科技",
    "Technology": "科技",
    "Used in research": "用于研究",
    "Used for reseaching new technologies.": "用于研究新科技。",
    "Apply to join": "申请加入",
    "Create guild": "创建公会",
    "Create Guild": "创建公会",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "?": "?",
    "©": "©",
    "%": "%",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Tutorial -  ": "教程 -  ",
    "- Kentaurus ": "- 肯塔鲁斯",
    "Efficiency: ": "效率: ",
    "t (weight ratio: ": "t (重量比: ",
    "Companies": "公司",
    "Planet ": "星球",
    "Energy: ": "能源: ",
    "Cargo Bay Segment": "货舱片段",
    "Fuel Tank Segment": "燃料罐片段",
    "Hull Plate": "船体板",
    "Hydrogen Generator": "氢气发生器",
    "Linear FTL Emitter": "线性超光速发射器",
    "Shuttle Bridge": "航天桥",
    "Welding Kit": "焊接套件",
    "Ship Interior Kit": "飞船内部套件",
    "Advanced Amenities": "高级设施",
    "Advanced Constr. Kit": "高级施工套件",
    "Advanced Construction Kit": "高级施工套件",
    "Advanced Prefab Kit": "高级预制套件",
    "Amenities": "便利设施",
    "Apex Prefab Kit": "极品预制套件",
    "Construction Kit": "建造套件",
    "Apex Structural Elements": "极品结构元素",
    "Apex Struct. Elements": "极品结构元素",
    "Modern Prefab Kit": "现代预制套件",
    "Industrial Machinery": "工业机械",
    "Structural Elements": "结构元素",
    "Prefab Kit": "预制套件",
    "Engineer": "工程师",
    "Recommended": "推荐",
    "Scientist": "科学家",
    "Worker": "工人",
    "Technician": "技术员",
    "Manufacturing - Level ": "制造业 - 等级 ",
    "Upgrade - Level ": "升级 - 等级 ",
    "Metallurgy - level ": "冶金 - 等级 ",
    "Steel": "钢",
    "New Mission in: ": "距离新任务到来: ",
    "Resource Extraction - level ": "资源提取 - 等级 ",
    "Glass": "玻璃",
    "Iron Ore": "铁矿石",
    "Iron": "铁",
    "Oxygen": "氧气",
    "Advanced Circuit Board": "高级电路板",
    "Average Price": "平均价格",
    "Battery": "电池",
    "Building": "建筑",
    "Color Compound": "颜色化合物",
    "Concrete": "混凝土",
    "Construction Tools": "建造工具",
    "Cooling": "冷却",
    "Cooling System": "冷却系统",
    "Cotton": "棉花",
    "Cows": "牛",
    "Current Price": "当前价格",
    "Drill": "钻",
    "Encyclopedia": "百科全书",
    "Engine": "引擎",
    "Ethanol": "乙醇",
    "Fabric": "织物",
    "Fruits": "水果",
    "Furniture": "家具",
    "Grain": "粮食",
    "Leather": "皮革",
    "Lubricant": "润滑剂",
    "Materials": "材料",
    "Meat": "肉",
    "Nitrogen": "氮气",
    "Office Supplies": "办公用品",
    "Pipes": "管道",
    "Polyethylene": "聚乙烯",
    "Pressure Sealant": "压力密封剂",
    "Pressure Sealant Kit": "压力密封剂套件",
    "Repair Kit": "维修工具",
    "Rubber": "橡胶",
    "Ship Parts": "船部分",
    "Source": "源",
    "Truss": "桁架",
    "Used in production": "用于生产",
    "Used in ship construction": "用于船舶建造",
    "Vegetables": "蔬菜",
    "Water": "水",
    "Wood": "木材",
    "Aluminium": "铝",
    "Carbon": "碳",
    "Silica": "硅",
    "Limestone": "石灰岩",
    "Copper": "铜",
    "Science - level ": "科学 - 等级 ",
    "Construction - level ": "建筑 - 等级 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    "Close to exchange": "靠近交易所",
    "Abundant resources": "丰富的资源",
    "/hr)": "/小时)",
    " - Order": " - 订单",
    " Gas Collector is out of work.": " 气体收集器已停止工作。",
    " Mine is out of work.": " 矿井已停止工作。",
    " Smelter is out of work.": " 冶炼厂已停止工作。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^\(([\d\.]+)$/,
    /^([\d\.]+)\)$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\/ ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)\$$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^ \(([\d\.,]+)\)$/,
    /^ \(([\d\.,]+)\/([\d\.,]+)\)$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d$/, '$1天'],
    [/^([\d\.]+)d ([\d\.]+)h$/, '$1天 $2小时'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.,]+)h ([\d\.,]+)m$/, '$1小时 $2分钟'],
    [/^([\d\.,]+)m ([\d\.,]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Engineers$/, '$1 工程师'],
    [/^([\d\.,]+) Technicians$/, '$1 技术员'],
    [/^([\d\.,]+) Workers$/, '$1 工人'],
    [/^([\d\.,]+) Scientists$/, '$1 科学家'],
    [/^([\d\.,]+) day ago$/, '$1 天前'],
    [/^([\d\.,]+) days ago$/, '$1 天前'],
    [/^([\d\.,]+) hours ago$/, '$1 小时前'],
    [/^([\d\.,]+) hour ago$/, '$1 小时前'],
    [/^([\d\.,]+) minutes ago$/, '$1 分钟前'],
    [/^([\d\.,]+) minute ago$/, '$1 分钟前'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) \/ ([\d\.,]+)ly$/, '$1 / $2 光年'],
    [/^\+([\d\.,]+) production quantity$/, '+$1 生产数量'],
    [/^\+([\d\.,]+) Workers$/, '+$1 工人'],
    [/^\+([\d\.,]+) Worker jobs$/, '+$1 工人工作'],
    [/^\(level ([\d\.,]+) building\)$/, '($1 级建筑)'],
    [/^Zephyr ([\d\.,]+)$/, '和风 $1'],
    [/^Empyrea ([\d\.,]+)$/, '九天神 $1'],
    [/^Amalthea ([\d\.,]+)$/, '木卫五 $1'],
    [/^Galmora ([\d\.,]+)$/, '加尔莫拉 $1'],
    [/^Myriad ([\d\.,]+)$/, '无数 $1'],
    [/^Tidal ([\d\.,]+)$/, '潮汐 $1'],
    [/^Cepheus ([\d\.,]+)$/, '仙王座 $1'],
    [/^Zicigawa ([\d\.,]+)$/, '滋加川 $1'],
    [/^Reverie ([\d\.,]+)$/, '幻想 $1'],
    [/^Kentaurus ([\d\.,]+)$/, '肯塔鲁斯 $1'],
    [/^Amethyst ([\d\.,]+)$/, '紫水晶 $1'],
    [/^Base ([\d\.,]+):$/, '基地 $1: '],
    [/^Ship ([\d\.,]+)$/, '飞船 $1'],
    [/^Tier ([\d\.,]+)$/, '等阶 $1'],
    [/^Base ([\d\.,]+)$/, '基地 $1'],
    [/^Void ([\d\.,]+)$/, '虚空 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();