// ==UserScript==
// @name         Idle Artisan 2 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.1
// @description  网页游戏 Idle Artisan 2 (https://idleartisan.com/myGameHome2.html) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Idle Artisan 2.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://idleartisan.com/favicon.ico
// @license      MIT
// @include      *https://idleartisan.com/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/idle-artisan2-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/idle-artisan2-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2026/03/03 13:21
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Email": "邮箱",
    "Password": "密码",
    "Forgot Password?": "忘记密码?",
    "Login": "登录",
    "or": "或",
    "Play as Guest": "以游客身份进行游戏",
    "Register": "注册",
    "Sign in with Google": "使用 Google 账户授权登录",
    "alchemy": "炼金",
    "Alchemy": "炼金",
    "Cooking": "烹饪",
    "cooking": "烹饪",
    "firemaking": "生火",
    "Firemaking": "生火",
    "fishing": "钓鱼",
    "Fishing": "钓鱼",
    "Woodcutting": "伐木",
    "woodcutting": "伐木",
    "crafting": "制作",
    "Crafting": "制作",
    "hunting": "狩猎",
    "Hunting": "狩猎",
    "Mining": "采矿",
    "mining": "采矿",
    "Monsters": "怪物",
    "You": "你",
    "⚠️ Warning:": "⚠️ 警告:",
    "🌽 Corn": "🌽 玉米",
    "🍎 Apples": "🍎 苹果",
    "1st Place": "位置1",
    "2nd Place": "位置2",
    "3rd Place": "位置3",
    "All Status": "所有状态",
    "All Items": "所有物品",
    "Apples": "苹果",
    "🐟 Fishing": "🐟 钓鱼",
    "-- Select a tool --": "-- 选择一个工具 --",
    "-- Select Building --": "-- 选择建筑 --",
    "-- Select Item --": "-- 选择物品 --",
    "-- Gathering --": "-- 采集 --",
    "-- Misc --": "-- 杂项 --",
    "-- Artisan --": "-- 工匠 --",
    "🪨 Mining": "🪨 采矿",
    "🥔 Potatoes": "🥔 土豆",
    "🦌 Hunting": "🦌 狩猎",
    "🪙 Battling": "🪙 战斗",
    "🪵 Woodcutting": "🪵 伐木",
    "🚪 Cut Planks": "🚪 切割木板",
    "🟨 Refine Gold": "🟨 精炼黄金",
    "Actions": "行动",
    "Action": "行动",
    "Active Jobs": "活跃工作",
    "Active": "活跃",
    "Active Contracts": "活跃合同",
    "Bolts": "箭头",
    "Base Level:": "基础等级:",
    "Boss Tokens": "Boss 代币",
    "Buffs": "增益状态",
    "Cancel": "取消",
    "Clear": "清除",
    "Common": "普通",
    "Community": "社区",
    "Community Buildings": "社区建筑",
    "Community Donations": "社区捐献",
    "Confirm": "确认",
    "Confirm Equipment Change": "确认装备更改",
    "Confirm Password:": "确认密码:",
    "Confirm Purchase": "确认购买",
    "Corn": "玉米",
    "Contract Type:": "合同类型:",
    "Data": "数据",
    "Date (UTC)": "日期 (UTC)",
    "Cut Planks": "切割木板",
    "Duration:": "持续时间:",
    "Dungeons": "地下城",
    "Dungeon": "地下城",
    "Dungeons 🏰": "地下城 🏰",
    "Eat to Full": "吃到满血",
    "Epic": "史诗",
    "Event": "事件",
    "Event Name": "事件名称",
    "Event Active": "事件活跃",
    "Fish": "鱼",
    "Filters": "过滤器",
    "Feedback": "反馈",
    "Farming Level": "农场等级",
    "Farming": "农场",
    "Farming & Consumables": "农场 & 消耗品",
    "Food Buff": "食物增益状态",
    "Fishing (Fish)": "钓鱼 (鱼)",
    "Global": "全局",
    "Gold": "金币",
    "Gold Bars": "金锭",
    "gold reward": "金币奖励",
    "Goldforge": "黄金熔炉",
    "Got it!": "知道了!",
    "Guide": "指南",
    "Harvest All 🚜": "收获全部 🚜",
    "Hide": "隐藏",
    "History": "历史",
    "How It Works:": "工作原理:",
    "How to Play": "玩法",
    "Hunger": "饥饿",
    "Marketplace": "市场",
    "Market": "市场",
    "Mastery": "精通",
    "Mastery Boosts": "精通提升",
    "Mastery Level:": "精通等级:",
    "Max": "最大",
    "Meat": "肉",
    "Planks": "木板",
    "Potatoes": "土豆",
    "Post": "发送",
    "Rare": "稀有",
    "Rare Resources": "稀有资源",
    "Rare Finds": "稀有发现",
    "Rarity:": "稀有度:",
    "Public:": "公开:",
    "Rank": "排名",
    "Repair": "修理",
    "Repair Market": "修理市场",
    "Repair Log (Session)": "修理日志 (季节)",
    "Remove All 🗑️": "移除全部 🗑️",
    "Resets:": "重置:",
    "Reset": "重置",
    "Reset All Masteries (90% Refund)": "重置所有精通（返还 90%）",
    "Rewards": "奖励",
    "Reward:": "奖励:",
    "Return to Login": "返回到登录",
    "Resources": "资源",
    "Resource Display": "资源显示",
    "Send": "发送",
    "Send Feedback": "发送反馈",
    "Send Message": "发送消息",
    "Sell Orders": "出售订单",
    "Select Tool to Sell": "选择工具以出售",
    "Select a tool:": "选择一个工具:",
    "Stats": "统计",
    "Start Game": "开始游戏",
    "Start Auto-Farm": "开始自动耕作",
    "Tool Enhancement": "工具强化",
    "Tool:": "工具:",
    "Tool Rarity:": "工具稀有度:",
    "Tool Type:": "工具类型:",
    "Tool Level:": "工具等级:",
    "Tools/Food": "工具/食物",
    "Total": "总计",
    "Total Mastery": "总计精通",
    "Total XP:": "总计经验值:",
    "Total Lvl": "总计等级",
    "Total Dungeons": "总计地下城",
    "Tool Sharpening": "工具打磨",
    "Tool & Gathering": "工具 & 采集",
    "Trade": "交易",
    "Uncommon": "罕见",
    "Users": "用户",
    "View Profile": "查看个人资料",
    "Workshop": "工坊",
    "Worker:": "工人:",
    "Wood": "木头",
    "Generating your unique identity...": "生成您的独特身份...",
    "Normal Server Active": "普通服务器活跃",
    "Normal:": "普通:",
    "No data available yet.": "暂无数据可用。",
    "Orders": "订单",
    "Open Game Guide in new Tab": "在新标签页打开指南",
    "Pickaxe": "镐子",
    "Potato-Blaster": "炸土豆机",
    "Poor": "劣质",
    "Points": "点数",
    "Refining": "精炼",
    "Refining & Preparing:": "精炼 & 准备:",
    "Refine Gold": "精炼黄金",
    "Refine Iron": "精炼铁",
    "Receive your": "收到你的",
    "Rebirths:": "重生:",
    "Raw Materials": "原材料",
    "Recent History": "最近历史",
    "Refined Materials": "精炼材料",
    "Repair your own tools using Salvage and your Tinkering skill. Maximize efficiency by upgrading your Repair Bench in Personal Buildings. Tools that are level 6 and above take durability loss whenever they are used.": "利用拾荒和你的修理技能来修理自己的工具。通过升级个人建筑中的修理台来提高效率。等级为 6 及以上的工具在使用时会损耗其耐久度。",
    "Welcome to Idle Artisan 2": "欢迎来到 工匠放置2",
    "where the": "当",
    "This server enforces Normal rules.": "该服务器执行正常规则。",
    "Trading and multiplayer features enabled.": "交易和多人游戏功能已启用。",
    "To play Ironman mode, visit": "要玩铁人模式，请访问",
    "Please wait while the scribes update your journal...": "请稍等，记录员正在更新您的日志...",
    "to play.": "以进行游戏。",
    "All players start as an Apprentice. This allows you to try the game instantly without an email or password. Your progress is saved on the server. You can create a permanent account later from the in-game Options menu to secure your progress and unlock all features (like the Market and Conclaves).": "所有玩家初始状态均为“学徒”。这样您无需输入电子邮件或密码即可立即开始游戏。您的游戏进度会保存在服务器上。之后您可以在游戏内的“选项”菜单中创建一个永久性账号，以确保您的游戏进度安全，并解锁所有功能（如市场和议会）。",
    "Back to Login": "返回到登录",
    "Enter your email address to receive a reset link.": "请输入您的电子邮件地址以获取重置链接。",
    "Go to Ironman Server": "前往铁人服务器",
    "https://idleartisan.com": "https://idleartisan.com",
    "Idle Artisan": "工匠放置",
    "Ironman accounts are now played on another instance of the game:": "铁人账户现在可以在游戏的另一个实例上玩了：",
    "Reset Password": "重置密码",
    "Send Link": "发送链接",
    "Set New Password": "设置新密码",
    "Start as Apprentice": "以学徒身份开始",
    "What is an Apprentice account?": "什么是学徒账户？",
    "You are using an insecure connection. Please go to": "您正在使用不安全的连接。请前往",
    "User not found.": "用户未找到。",
    "Ironman:": "铁人:",
    "Legendary": "传说",
    "Level": "等级",
    "Level:": "等级:",
    "Kitchen": "厨房",
    "Join": "加入",
    "--- Idle & Automation ---": "--- 放置 & 自动化 ---",
    "--- Tools ---": "--- 工具 ---",
    "--- Sigils ---": "--- 符文 ---",
    "--- Refining ---": "--- 精炼 ---",
    "--- Other ---": "--- 其他 ---",
    "--- Foods ---": "--- 食物 ---",
    "--- Ammo ---": "--- 弹药 ---",
    "--- Amulets ---": "--- 护身符 ---",
    "--- Core ---": "--- 核心 ---",
    "--- Gathering ---": "--- 采集 ---",
    "--- Artisan ---": "--- 工匠 ---",
    "--- Misc ---": "--- 杂项 ---",
    "Crafted by:": "制作者:",
    "Crafting Bonus": "制作加成",
    "Crafting Cost:": "制作成本:",
    "Current Bid": "当前出价",
    "Please use a permanent email address. Disposable or temporary email services are not permitted.": "请使用永久性的电子邮箱地址。不允许使用一次性或临时性的电子邮件服务。",
    "XP:": "经验值:",
    "Loading history...": "正在加载历史...",
    "Loading players...": "正在加载玩家...",
    "Loading users...": "正在加载用户...",
    "Hide Dungeon": "隐藏地下城",
    "Hide Farm": "隐藏农场",
    "Hide Gathering": "隐藏采集",
    "Hide Info": "隐藏信息",
    "Hide Market": "隐藏市场",
    "Hide Rare Finds": "隐藏稀有发现",
    "Hide Mercenary": "隐藏雇佣兵",
    "Hide Offline": "隐藏发现",
    "Hide Repair": "隐藏修理",
    "Hide Refining": "隐藏精炼",
    "Hide Events": "隐藏事件",
    "You gathered": "你采集了",
    "Verify Email": "验证邮箱",
    "Verify Your Account": "验证你的账户",
    "Please click the button below to complete verification.": "请点击下方的按钮以完成验证。",
    "Username:": "用户名:",
    "⚔️ Mercenary Post": "⚔️ 佣兵站",
    "▼ Equipped": "▼ 已装备",
    "+1 lvl=+1%": "+1 等级=+1%",
    "+ Post Order": "+ 发布订单",
    "Your Email:": "你的邮箱:",
    "Your Conclave:": "你的议会:",
    "Skill": "技能",
    "Skills": "技能",
    "Skill Level:": "技能等级:",
    "Skip (Use Standard)": "跳过（使用标准设置）",
    "Skip Lobby": "跳过大厅",
    "Success Rate": "成功率",
    "Scrap All": "打磨所有",
    "Sawmill": "锯木厂",
    "Recent Activity": "近期活动",
    "Ready for planting": "准备播种",
    "Prestige to reset your progress and gain permanent power. The XP requirement increases by 25% per prestige. Total XP excludes Crafting XP. Slag point costs increase by 10% with each level.": "声望重置你的进度并获得永久力量。每增加一次声望，经验要求增加25%。总经验值不包括制作经验值。每升一级，熔炼点消耗会增加 10%。",
    "Plain Color:": "纯色：",
    "Prep Fish": "腌鱼",
    "Prep Meat": "腌肉",
    "Price (Gold/Salvage)": "价格 (金币/回收)",
    "Price: High to Low": "价格: 从高到低",
    "Price: Low to High": "价格: 从低到高",
    "Preferred Crop:": "首选作物：",
    "🔥 Slag Pit": "🔥 矿渣坑",
    "Woodcutting Bonus": "伐木加成",
    "Woodcutting Bonus Begins": "伐木加成开始",
    "Woodcutting Bonus Ended": "伐木加成结束",
    "You are": "你",
    "Food": "食物",
    "Four Leaf Clover": "四叶草",
    "Highest Lvl": "最高等级",
    "Highest Dungeon": "最高地下城",
    "Hide Crafting": "隐藏制作",
    "Hunter": "猎人",
    "Hunters Harvest": "猎人收获",
    "Hunters Harvest Begins": "猎人收获开始",
    "Hunters Harvest Ended": "猎人收获结束",
    "Idle Artisan 2": "工匠放置2",
    "Info/Spam": "信息/垃圾邮件",
    "Inner Circle Fallback": "内圈撤退",
    "Inventory": "库存",
    "Take All 📦": "全部拿走 📦",
    "Sushi": "寿司",
    "Supplies & Misc": "供应 & 杂项",
    "Starving": "饥饿",
    "Starfall Ore": "星陨矿石",
    "Special": "特殊",
    "Sort:": "排序:",
    "Select resources to pin to the top bar.": "选择要固定在顶部栏中的资源。",
    "Select an activity to see session statistics.": "选择一项活动以查看相关会话统计数据。",
    "Sharpen Tool": "打磨工具",
    "XP Gained:": "获得的经验值:",
    "Yield Per Tick:": "产出每Tick:",
    "Your Message:": "你的消息:",
    "Your storage locker is empty.": "你的储物柜是空的。",
    "XP, Total Level, Resources, Items (Stash, Locker, Equipped), Buildings, Recipes, Market/Repair Listings & Active Jobs, NPC Contracts, Mailbox, Mastery Levels, Dungeon Cooldowns, Active Buffs, Active Contracts (Merc/Farm), Farm Plots, Hunger, Active Event Contributions & Votes, Offline Time, Conclave Applications, Current Activity.": "经验、总等级、资源、物品（储藏、储物柜、装备）、建筑、食谱、市场/维修清单和活跃工作、NPC合同、邮箱、精通等级、副本冷却、主动增益、主动合同（佣兵团/农场）、农场地块、饥饿、活动贡献和投票、离线时间、秘密会议申请、当前活跃度。",
    "Message:": "消息:",
    "My Active Contracts": "我的活跃合同",
    "My Contracts": "我的合同",
    "My Listings": "我的挂单",
    "Name": "名称",
    "Mining Bonus Ended": "采矿加成已结束",
    "Next Enhance Cost:": "下一级强化成本:",
    "Tinkering": "修补",
    "Tinker's Kit": "修补匠的工具包",
    "Trash Visible 🗑️": "丢弃可见 🗑️",
    "Unique": "独特",
    "Unpin all": "全部取消固定",
    "View Roster": "查看名单",
    "Fishing Frenzy": "钓鱼狂热",
    "Fishing Frenzy Begins": "钓鱼狂热已开始",
    "Fishing Frenzy Ended": "钓鱼狂热已结束",
    "Battling": "战斗",
    "Building:": "建筑:",
    "Building Type:": "建筑类型:",
    "Building Level:": "建筑等级:",
    "Building Enhancement:": "建筑强化:",
    "Boss Events 👹": "Boss事件 👹",
    "Boss Materials": "Boss材料",
    "Boss Priorities (Inner Circle):": "老板优先事项 (核心圈子):",
    "Auto-Delete Mail Types:": "自动删除邮件类型:",
    "Auto-switch when idle/finished": "空闲/完成时自动切换",
    "Attachment (Optional):": "附件（可选）：",
    "At any time, and for any reason, you can delete your account which will permanently delete all of this information from the server. This action can be completed under the in-game Options menu.": "在任何时候，出于任何原因，您都可以删除您的账户，这将永久从服务器中删除所有相关信息。此操作可在游戏内的“选项”菜单中完成。",
    "As your Mayor, I welcome your correspondence. Please share your thoughts, suggestions for our growing town, or report any civic matters that require my attention. Your voice helps shape the future of our community. Posting to the Discord is best for a two way conversation, but for quick thoughts (or not able to join Discord) this can be used to send me a personal letter.": "作为你们的市长，我欢迎你们的来信。请分享你们的想法、对我们这个不断发展的城镇的建议，或者报告任何需要我关注的市政事务。你们的声音有助于塑造我们社区的未来。在 Discord 上发布信息最适合进行双向交流，但如果您有快速的想法（或者无法加入 Discord）的话，也可以通过这种方式给我发送一封私人信件。",
    "Assign artisan to:": "分配工匠到:",
    "Artisan": "工匠",
    "Artisan's Marks": "工匠徽章",
    "Anvil": "铁砧",
    "Antlers": "鹿角",
    "Amulet of Scrapper:": "拾荒者的护身符：",
    "⚙ Scavenging": "⚙ 拾荒",
    "🌱 Empty Soil": "🌱 空地",
    "🍣 Prep Fish": "🍣 腌鱼",
    "📅 Mail Retention Policy:": "📅 邮件保留策略:",
    "🏚️ Soilwarden's Tithe Barn": "🏚️ 土壤守护者的圣俸谷仓",
    "🍀 Four Leaf Clovers": "🍀 四叶草",
    ". All your items, resources, and progress will be deleted forever.": "。你所有的物品、资源和进度都将被永远删除。",
    "Glimmerwood Sap": "微光木树液",
    "Most Popular Item": "最受欢迎物品",
    "Net Trap": "网状陷阱",
    "Newest First": "最新的优先",
    "No active buffs.": "暂无激活的增益状态。",
    "No artisans found.": "未找到工匠。",
    "No bids yet": "暂无出价。",
    "No Tool": "暂无工具",
    "Note: Enhancement levels will reset to 0 if the building's base level is upgraded.": "注意：如果建筑物的基础等级升级，则强化等级将重置为0。",
    "No Botting or Automation:": "没有机器人或自动化：",
    "Note: Enhancement levels will reset to 0 if the tool is replaced.": "注意：更换工具后，强化等级将重置为0。",
    "Nothing Equipped": "暂无已装备",
    "Oceanic Essence": "海洋精华",
    "Offline Summary": "离线汇总",
    "NPC Contracts": "NPC 合同",
    "Other players": "其他玩家",
    "Permanent challenge. No trading, no market, no joining parties/conclaves. Self-sufficient only.": "永恒的挑战。没有交易，没有市场，也无法加入队伍/议会。只能自给自足。",
    "permanent": "永久",
    "Personal Repair Bench": "个人维修工作台",
    "Personal Workshop": "工人工坊",
    "Place Bid": "出价",
    "PLACEHOLDER DESCRIPTION": "占位符描述",
    "PERFORM REBIRTH": "执行重生",
    "A monstrous shadow darkens the coastal waters. The Leviathan has returned! Its scales shimmer with the wealth of the abyss, a tempting prize for the fleet of fishers who dare to face it.": "一片巨大的阴影笼罩在沿海水域之上。利维坦又现身了！它的鳞片闪耀着深渊的财富光芒，对于那些敢于面对它的捕鱼队伍来说，这无疑是一份诱人的战利品。",
    "About NPC Contracts": "关于 NPC 合同",
    "Abyssal Eel": "深海鳗鱼",
    "Account Security:": "账户安全:",
    "Account Limit:": "账户限制:",
    "active": "活跃",
    "Alchemist Guild:": "炼金术士公会：",
    "All mail (no attachments): Deleted after 30 days": "所有邮件（不含附件）：30 天后删除",
    "Alpha Wolf": "阿尔法狼",
    "Apple Cider": "苹果酒",
    "A chilling howl echoes across the plains, silencing the birds and sending a shiver down your spine. The Alpha Wolf has begun its hunt, and all who dwell in the wild are now its prey.": "一阵令人毛骨悚然的嚎叫声在平原上回荡，将鸟儿们吓得噤声，也让人脊背发凉。首领狼已经开始了它的捕猎行动，而所有生活在野外的生物如今都成了它的猎物。",
    "A cacophony of grinding gears and screeching metal erupts from the scrapyard. Clatter-Gnash, a monstrosity of animated junk, has assembled itself and threatens to dismantle everything in sight!": "从废品场里传出一阵嘈杂的齿轮摩擦声和金属的嘎吱声。一个由各种废旧物品组成的庞大怪物“咔咔牙”已经自行组合起来，正准备将眼前的一切都摧毁！",
    "Calculating...": "计算中...",
    "Clatter-Gnash": "咔咔牙",
    "Competition Type": "竞赛类型",
    "Competitions": "竞赛",
    "Conclave Competitions": "议会竞赛",
    "Consumption:": "消耗:",
    "Conclave:": "议会:",
    "Conclaves": "议会",
    "Conclave Only": "仅议会",
    "Conclave Points": "议会点数",
    "Conclave Tithe:": "议会税收:",
    "Contract Notifications": "合同通知",
    "Cost Est (G)": "成本估算 (金币)",
    "Crafting Bench": "制作工作台",
    "Scavenging Surge": "拾荒狂潮",
    "Scavenging Surge Begins": "拾荒狂潮已开始",
    "Scavenging Surge Ended": "拾荒狂潮已结束",
    "Mining Bonus Begins": "采矿加成已开始",
    "Battling Bonus Begins": "战斗加成已开始",
    "Crafting Bonus Begins": "制作加成已开始",
    "Battling Bonus Ended": "战斗加成已结束",
    "Crafting Bonus Ended": "制作加成已结束",
    "Cross-trade guidance:": "交叉交易指引：",
    "Crystallized Anima": "结晶灵魂",
    "Delete Account": "删除账户",
    "DELETE FOREVER": "永久删除",
    "The Artisan Tournament for Woodcutting has begun! Join now to compete!": "工匠伐木锦标赛开始了！现在就加入，一展身手吧！",
    "The Dungeon Delve event has ended. Rewards return to normal.": "地下城探险事件已经结束。奖励恢复正常。",
    "The Great Smeltdown has begun! The master smiths are calling for Iron Ore to fuel the pyre!": "大熔炉已经开始了！铁匠大师在找铁矿石来做柴堆的燃料！",
    "The Great Smeltdown has ended. The forges cool and fall silent.": "大熔炉已经结束。熔炉冷却下来，寂静无声。",
    "The Town Watch arrested the Thief! The Thieves' Den has been located! Join the Raid in the Dungeon Lobby!": "守城人逮捕了小偷！盗贼巢穴已被找到！在地下城大厅加入突袭！",
    "Quality": "质量",
    "Quantity": "数量",
    "Read mail (no attachments): Deleted after 7 days": "阅读邮件（不含附件）：7 天后删除",
    "Required Sharpening Stone:": "所需磨刀石：",
    "Recipient:": "收件人：",
    "Required: 'The Anti-Glyph'": "所需：“反雕文”",
    "Respectful Conduct:": "礼貌行为：",
    "Rewards are distributed to Conclave buildings in the form of refined resources (Iron Bars, Planks, Gold Bars, Sushi, Meat), Rune Shards, and Salvage.": "奖励将以精炼资源（铁条、木板、金条、寿司、肉类）、符文碎片以及回收物的形式分配到议会建筑中。",
    "Rune Shards": "符文碎片",
    "Rules": "规则",
    "Runic Golem": "符文魔像",
    "Privacy Policy": "隐私政策",
    "Production Bonus:": "生产加成:",
    "Production:": "生产:",
    "Profiles": "个人资料",
    "Public Profiles": "公开个人资料",
    "Load Equipped": "加载已装备",
    "Loading conclaves...": "正在加载议会...",
    "Logout": "登出",
    "Level Up!": "升级!",
    "Your": "你的",
    "level is now": "等级现在是",
    "A low hum echoes from the quarry. The earth trembles as a Runic Golem, larger and more powerful than any seen before, rises from the depths! Its core pulses with raw energy, daring artisans to test their mettle.": "远处的采石场传来低沉的轰鸣声。大地微微颤抖，一个比以往所见的任何造物都要庞大、强大的瑞文魔法石像从地下升腾而起！它的核心散发着原始的能量，激起了技艺高超的工匠们一探究竟的勇气。",
    "A war horn, deeper and more menacing than any heard before, sounds from the wastelands. A legendary Warlord and their elite guard have appeared, seeking to challenge the town's greatest champions!": "从荒原上传来了一个声音，那是一声比以往任何声音都要低沉且更具威胁性的战角声。一位传说中的战将及其精锐卫队出现了，他们前来挑战这座城镇最杰出的勇士们！",
    "The ancient forest groans. A colossal Treant, its bark as thick as a castle wall and its branches like siege weapons, has awoken! Its heartwood thrums with a primal power, challenging all who would dare to swing an axe.": "古老的森林发出低沉的呻吟声。一棵巨大的树精现身了，它的树皮厚得像城堡的外墙，树枝则像攻城的武器。它苏醒了！它的心材散发着一种原始的力量，向所有敢于挥动斧头的人发出挑战。",
    "Tax Free Weekend Begins": "免税的周末开始了",
    "Tax Free Weekend Ended": "免税的周末结束了",
    "Iron Ore": "铁矿石",
    "Iron Bars": "铁锭",
    "Ironforge": "铁熔炉",
    "Public Repair Market": "公开修理市场",
    "Prime Cut": "精品切割",
    "Tools": "工具",
    "Failed": "失败",
    "Fair Play:": "公平竞争:",
    "The Mayor has declared a week of exploration! Brave the depths and earn double Artisan's Marks for every room cleared.": "市长宣布开启为期一周的探险活动！勇敢深入地下，每清理完一个房间就能获得双倍的工匠徽章奖励。",
    "Scavenging": "拾荒",
    "The Great Smeltdown has begun! The master smiths are calling for Iron Ore to fuel the pyre!": "大熔炉已经开始了！铁匠大师在找 铁矿石 来做柴堆的燃料！",
    "The Great Smeltdown has begun! The master smiths are calling for Sushi to fuel the pyre!": "大熔炉已经开始了！铁匠大师在找 寿司 来做柴堆的燃料！",
    "Slag Power:": "炉渣动力：",
    "Slag Rebirth": "炉渣重生",
    "A magical rainbow has touched down! The Leprechaun's Wager has begun! Join quickly to find the pot of luck!": "一道神奇的彩虹降临了！小精灵的赌局已经开始了！快来加入，找到幸运之罐！",
    "A thief is lurking in the shadows...": "一个小偷正潜伏在暗处...",
    "You caught an Abyssal Eel!": "你捕获了一条深渊鳗鱼！",
    "Merchant": "商人",
    "Warlord": "战神",
    "Warning: This action is permanent and cannot be undone. Each tool can only be sharpened once.": "警告：此操作为永久性操作，无法撤销。每把工具只能打磨一次。",
    "Battling Bonus": "战斗加成",
    "Mining Bonus": "采矿加成",
    "Durability:": "耐久性：",
    "Enable Ironman Mode 🛡️": "启用铁人模式 🛡️",
    "Enhancement:": "强化:",
    "Enhancement Cost:": "强化成本:",
    "Enhance Building": "强化建筑",
    "Game Rules & Code of Conduct": "游戏规则与行为准则",
    "▶ Equipped": "▶ 已装备",
    "Carcass gain is doubled and you get 2 extra Hunting XP during this event.": "在此活动中，动物的体重增长幅度将翻倍，并且您还将额外获得 2 点狩猎经验值。",
    "The wind is right, and the tracks are fresh. A good day for a hunt.": "风势正佳，足迹清晰可见。今天是个绝佳的狩猎日。",
    "Dungeon Delve": "地下城探险",
    "Salvage gain is doubled and you get 2 extra Tinkering XP during this event.": "此次事件中，拾荒所得的奖励将翻倍，并且您还将额外获得 2 点制造经验值。",
    "One artisan's trash is another's treasure. Today, the pickings are rich!": "一位工匠的废料对于另一个人来说可能是宝贝。今天，收获丰厚！",
    "Great Smeltdown": "大熔炉",
    "The echoes of the deep call to you.": "那深沉的呼唤之声仍在回荡，向你传来。",
    "your bid amount": "您的出价金额",
    "You must join a Conclave to access the Strongbox.": "你必须加入议会才能访问保险箱。",
    "The Great Smeltdown has begun! The master smiths are calling for Salvage to fuel the pyre!": "大熔炉已经开始了！铁匠大师们正在召集拾荒人员来给火堆加油！",
    "Leprechaun's Wager": "小妖精的赌注",
    "Leave": "离开",
    "Leather": "皮革",
    "Leaderboard": "排行榜",
    "Joining...": "正在加入...",
    "Join": "加入",
    "The Thief": "小偷",
    "The Artisan Tournament for Crafting has begun! Join now to compete!": "工匠制作锦标赛已经开始了！现在就加入，一展身手吧！",
    "Total Slag Upgrades": "总炉渣升级",
    "Total SOMs Spent:": "总消费金额(SOMs)：",
    "Tournaments": "锦标赛",
    "Unsocket": "拔出",
    "Unsocket Glyph": "拔出符文",
    "Time to grow new crops:": "种植新作物时间：",
    "Time Left": "时间剩余",
    "Time Est": "时间估计",
    "📧 Spam Filter:": "📧 垃圾邮件过滤：",
    "🔩 Iron Bars": "🔩 铁锭",
    "🔩 Refine Iron": "🔩 精炼铁",
    "🥩 Prep Meat": "🥩 腌肉",
    "🚪 Planks": "🚪 木板",
    "🛡️Continent:": "🛡️ 大陆:",
    "Refresh Now": "立即刷新",
    "A new version of the game is ready. Refresh to get the latest updates.": "一个新版本的游戏准备好了。刷新页面即可获取最新更新内容。",
    "Game Update Available!": "游戏更新可用!",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "[Mayor]": "[Mayor]",
    "N/A": "N/A",
    "idleartisan.com/ironman": "idleartisan.com/ironman",
    "Pop:": "Pop:",
    "SP": "SP",
    "Buckler": "圆盾",
    "Amulet": "护符",
    "Wraps": "外衣",
    "Skirt": "裙子",
    "Sandals": "凉鞋",
    "Robe": "长袍",
    "Hat": "帽子",
    "Pants": "裤子",
    "Hood": "兜帽",
    "Vest": "背心",
    "Shield": "盾牌",
    "Ring": "戒指",
    "Platelegs": "板腿",
    "Platebody": "板甲",
    "Helmet": "头盔",
    "Gloves": "手套",
    "Boots": "靴子",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "Gityx": "Gityx",
    "G8hh": "G8hh",
    "⚠️": "⚠️",
    "⚙️": "⚙️",
    "⚔️": "⚔️",
    "⛮": "⛮",
    "✅": "✅",
    "✨": "✨",
    "🍎": "🍎",
    "🍖": "🍖",
    "🍞": "🍞",
    "🍣": "🍣",
    "💎": "💎",
    "💠": "💠",
    "⭐": "⭐",
    "🎖️": "🎖️",
    "🐍": "🐍",
    "🐟": "🐟",
    "🏹": "🏹",
    "🎩": "🎩",
    "🎫": "🎫",
    "☰": "☰",
    "📌": "📌",
    "📜": "📜",
    "📦": "📦",
    "🔫": "🔫",
    "🥅": "🥅",
    "🥘": "🥘",
    "🥘": "🥘",
    "🥩": "🥩",
    "🥔": "🥔",
    "🔩": "🔩",
    "🔥": "🔥",
    "🌊": "🌊",
    "🌕": "🌕",
    "🦌": "🦌",
    "🌽": "🌽",
    "🧃": "🧃",
    "🧺": "🧺",
    "🪵": "🪵",
    "🚫": "🚫",
    "🛑": "🛑",
    "🪨": "🪨",
    "🪝": "🪝",
    "🫎": "🫎",
    "🟨": "🟨",
    "🚪": "🚪",
    "×": "×",
    "•": "•",
    "→": "→",
    "🪙": "🪙",
    "🌿": "🌿",
    "🍀": "🍀",
    "-- / --": "-- / --",
    "--": "--",
    "!": "!",
    "🥘:": "🥘:",
    "📜": "📜",
    "♥": "♥",
    "❤️": "❤️",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    ">>": ">>",
    ">": ">",
    "<<": "<<",
    "<": "<",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "🏹Bolts: ": "🏹 箭头: ",
    "🪝Hooks: ": "🪝 鱼钩: ",
    "Dungeon Cooldown: ": "地下城冷却时间: ",
    "Manual Dungeons: ": "手动地下城: ",
    "Plant 🌽: ": "种植 🌽: ",
    "Plant 🍎: ": "种植 🍎: ",
    "Plant 🥔: ": "种植 🥔: ",
    "Sword": "剑",
    "Pickaxe": "镐",
    "Axe": "斧子",
    "Fishing Hooks": "鱼钩",
    "Fishing Rod": "鱼竿",
    "Crossbow": "弩",
    "Next: ": "下一个: ",
    "Left: ": "剩余: ",
    "Lvl: ": "等级: ",
    "Gain since reset: ": "自重置后增益: ",
    "[Gathering] ": "[采集] ",
    "[Rare] ": "[稀有] ",
    "[Event] ": "[事件] ",
    "Tinkers Kit": "修补工具包",
    "Up Next: ": "接下来: ",
    "⭐ Starfall: ": "⭐ 星陨: ",
    "🌊 Essence: ": "🌊 精华: ",
    "✨ Sap: ": "✨ 树液: ",
    "🐍 Eel: ": "🐍 鳗鱼: ",
    "💎 Anima: ": "💎 灵魂: ",
    "🍖 Prime Cut: ": "🍖 精品切割: ",
    "[Dungeon] ": "[地下城] ",
    "Current Mercenary Cut: ": "当前雇佣兵削减：",
    "Scrolls of Mastery: ": "精通卷轴: ",
    "Ticks: ": "Ticks: ",
    "Tournament: ": "锦标赛: ",
    "📦 Shipment: ": "📦 运货: ",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " (Locked)": " (未解锁)",
    " (No crops ready)": " (暂无成熟作物)",
    " (Carcass)": " (尸体)",
    " (No crops)": " (无作物)",
    " (Gold)": " (黄金)",
    " (Battling)": " (战斗)",
    " (Salvage)": " (拾荒)",
    " (Mining)": " (采矿)",
    " (Hunting)": " (狩猎)",
    " (Tinkering)": " (修补)",
    " (Wood)": " (木头)",
    " (Iron Ore)": " (铁矿石)",
    " ▲": " ▲",
    " ▼": " ▼",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+)\]$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+) \|$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Time spent: (.+) • Ticks spent: (.+)$/, '花费时间: $1 • 花费 Tick: $2'],
    [/^🏰 \*\*Dungeon Party Formed\*\*\n\n(.+) has created a Level (.+) Dungeon Party! Join them in the Dungeon Lobby.$/, '🏰 **地下城队伍已创建**\n\n$1 创建了一个 等级 $2 地下城队伍! 请前往地下城大厅加入他们。'],
    [/^The rainbow has faded! (.+) found the pot of gold and won 1$/, '彩虹已经消失了！$1 找到了一罐金币，并赢得了1'],
    [/^The Thief struck! A Epic Axe \(Lvl (.+)\) was stolen from (.+)\'s stash!$/, '小偷下手了！一把史诗斧子（$1级）从 $2 的储藏中被偷走了！'],
    [/^The Merchant has arrived! A Poor Fishing Rod \(Lvl (.+)\) is up for auction!$/, '商人已经到来! 一根劣质鱼竿（等级 $1）正在进行拍卖！'],
    [/^Tournament Results \(Crafting\): (.+)$/, '锦标赛结果 (制作): $1'],
    [/^You placed \#(.+) in the Crafting Tournament! You have been awarded: (.+) Rations.$/, '你在制作锦标赛的排名是第 $1! 你获得了: $2 物资.'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^▼ Conclave Strongbox \((.+) items\)$/, '▼ 议会保险箱（$1 物品）'],
    [/^▼ Stash \((.+) items\)$/, '▼ 储藏（$1 物品）'],
    [/^▼ Storage Locker \((.+) items\)$/, '▼ 储物柜 ($1 物品)'],
    [/^▶ Conclave Strongbox \((.+) items\)$/, '▶ 议会保险箱（$1 物品）'],
    [/^▶ Stash \((.+) items\)$/, '▶ 储藏（$1 物品）'],
    [/^▶ Storage Locker \((.+) items\)$/, '▶ 储物柜 ($1 物品)'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)\% Power$/, '$1% 动力'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)s$/, '$1秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^([\d\.,]+) SP$/, '$1 SP'],
    [/^([\d\.,]+) gold$/, '$1 金币'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+) Woodcutting XP$/, '+$1 伐木经验值'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\-([\d\.,]+) elves$/, '-$1 精灵'],
    [/^\[⚔️Stage ([\d\.,]+)⚔️\]$/, '[⚔️ 关卡 $1⚔️]'],
    [/^Apprentice\_([\d\.,]+)$/, '学徒_$1'],
    [/^: \[Common\] Level ([\d\.,]+)$/, ': [普通] 等级 $1'],
    [/^: \[Common\] Level ([\d\.,]+)  $/, ': [普通] 等级 $1  '],
    [/^Time to storage cap: ([\d\.,]+)d:([\d\.,]+)h:([\d\.,]+)m:([\d\.,]+)s$/, '到达存储容量上限还剩: $1天 $2小时 $3分钟 $4秒'],
    [/^Time to storage cap: (.+)$/, '到达存储容量上限还剩: $1'],
    [/^XP\/tick: (.+) • XP\/hr: (.+) • XP\/day: (.+) • Time to Lvl: ([\d\.,]+)d:([\d\.,]+)h:([\d\.,]+)m:([\d\.,]+)s$/, '经验值/tick: $1 • 经验值/小时: $2 • 经验值/天: $3 • 时间到等级: $4天 $5小时 $6分钟 $7秒'],
    [/^XP\/tick: (.+) • XP\/hr: (.+) • XP\/day: (.+) • Time to Lvl: (.+)$/, '经验值/tick: $1 • 经验值/小时: $2 • 经验值/天: $3 • 时间到等级: $4'],
    [/^⚙️ Salvage, earning ([\d\.,]+) Tinkering XP$/, '⚙️ 拾荒, 获得了 $1 修补经验'],
    [/^🪵 Wood, earning ([\d\.,]+) Woodcutting XP$/, '🪵 木头, 获得了 $1 伐木经验'],
    [/^🪨 Iron Ore, earning ([\d\.,]+) Mining XP$/, '🪨 铁矿石, 获得了 $1 采矿经验'],
    [/^Active Bidders \(([\d\.,]+)\):$/, '活跃竞拍者 ( $1):'],
    [/^Tinkering \(Lvl ([\d\.,]+)\)$/, '修补 (等级 $1)'],
    [/^Fishing \(Lvl ([\d\.,]+)\)$/, '钓鱼 (等级 $1)'],
    [/^Mining \(Lvl ([\d\.,]+)\)$/, '采矿 (等级 $1)'],
    [/^Scavenging \(Lvl ([\d\.,]+)\)$/, '拾荒 (等级 $1)'],
    [/^Woodcutting \(Lvl ([\d\.,]+)\)$/, '伐木 (等级 $1)'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Eat ([\d\.,]+)$/, '吃 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Rare finds: (.+) • Rare finds\/hr: (.+)$/, '稀有发现: $1 • 稀有发现/小时: $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^XP: (.+) \/ (.+)$/, '经验值：$1 \/ $2'],
    [/^Gain\/tick: (.+) • Gain\/hr: (.+) • Gain\/day: (.+)$/, '增益/tick: $1 • 增益/小时: $2 • 增益/天: $3'],
    [/^In: (.+) \| Out: (.+)$/, '输入: $1 | 输出: $2'],
    [/^Lvl ([\d\.,]+) \((.+) \/ (.+)\)$/, '等级 $1 ($2 \/ $3)'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^(.+) \/ (.+)$/, '$1 \/ $2'],
    [/^(.+) Leather: ([\d\.]+)\%$/, '$1 皮革: $2%'],
    [/^(.+) exp left$/, '$1 经验值剩余'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();