// ==UserScript==
// @name         idle-mmo-chs
// @namespace    https://www.g8hh.com/
// @version      0.0.98
// @description  Idle MMO（https://web.idle-mmo.com/）游戏汉化脚本 - 锅巴汉化出品
// @author       麦子、JAR、小蓝、好阳光的小锅巴
// @include      *https://web.idle-mmo.com/*
// @resource customCSS https://g8hh.com.cn/zh/tampermonkey/idle-mmo.css?time=183118
// @grant        GM_addStyle
// @grant        GM_getResourceText
// @website      https://www.gityx.com
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/idle-mmo-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/idle-mmo-chs.user.js
// ==/UserScript==

/* ↓旅行界面样式调整，适合摸鱼↓ */
/* ========摸鱼时删除此行注释，即可看到效果=======
let weburl=unsafeWindow.location.href
if(weburl.indexOf('web.idle-mmo.com')!=-1)
{
    // 引入css文件并加入html中
    const css = GM_getResourceText("customCSS");
    GM_addStyle(css);
}
if(weburl.indexOf('web.idle-mmo.com/i-am-not-a-bot')!=-1)
{
   // 保留人机校验验证码
   GM_addStyle('img{display:initial !important}')
}
========摸鱼时删除此行注释，即可看到效果======== */
/* ↑旅行界面样式调整，适合摸鱼↑ */

/**
 * ---------------------------
 * Time: 2023/12/08 09:32
 * Author: guoba
 * View: http://www.gityx.com
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    "Save": "保存",
    "Export": "导出",
    "Import": "导入",
    "Milking": "挤奶",
    "Loading...": "加载中...",
    "Open user menu": "打开用户菜单",
    "Chat": "聊天",
    "Battle": "战斗",
    "Close": "关闭",
    "Dismiss": "解雇",
    "* required": "* 必需的",
    "© 2023 Galahad Creative Ltd. All rights reserved.": "© 2023 Galahad Creative Ltd. 保留所有权利。",
    "<": "<",
    "<<": "<<",
    ">": ">",
    ">>": ">>",
    "Agree to our": "同意我们的",
    "Agree to receiving": "同意接收",
    "Already have an account?": "已经有帐户？",
    "Already have an account?": "已有帐户？",
    "An": "一个",
    "and": "和",
    "Back": "返回",
    "Character Name": "角色名字",
    "Checking...": "正在检查...",
    "Class": "职业",
    "Code of Conduct": "行为准则",
    "Company": "公司",
    "Cookie Policy": "Cookie 政策",
    "Cookie Policy": "Cookie 策略",
    "Effects": "效果",
    "Equipment": "装备",
    "Forsaken": "被遗忘者",
    "From the creators of SimpleMMO": "来自 SimpleMMO 的创建者",
    "Galahad Creative Ltd.": "Galahad Creative Ltd.",
    "Go on an epic adventure, hunt diverse enemies, embark on dungeons expeditions and defeat world bosses even while taking a nap!": "踏上史诗般的冒险，追捕不同的敌人，踏上地下城探险之旅，甚至在小睡的时候也能击败世界首领！",
    "I have a referral code": "我有推荐码",
    "idle": "放置",
    "Join Us On Discord": "加入我们的 Discord",
    "Log in": "登录",
    "Login": "登录",
    "Marketing Emails": "营销电子邮件",
    "Master of Archery and Dexterity.": "射箭和敏捷大师。",
    "Master of Daggers and Speed.": "匕首与速度大师。",
    "Master of Strength.": "力量大师。",
    "MMORPG experience": "大型多人在线角色扮演游戏体验",
    "Next": "下一个",
    "Play Now": "开始游戏",
    "Play the game on hard mode.": "在困难模式下玩游戏。",
    "Privacy Policy": "隐私政策",
    "Privacy Policy": "隐私政策",
    "Publishing deep and extensive digital products under the veneer of an effortless user experience since 2020.": "自 2020 年以来，在轻松的用户体验的幌子下发布深入而广泛的数字产品。",
    "Ranger": "游侠",
    "Read more.": "阅读更多。",
    "Shadowblade": "暗影之刃",
    "Starting Skin": "起始皮肤",
    "Talents": "人才",
    "Terms of Service": "服务条款",
    "Terms of Service": "服务条款",
    "The open beta is now available!": "公开测试版现已推出！",
    "This is what your character will be known as. It must be unique and alphanumeric only.": "这就是您的角色的名称。 它必须是唯一的且仅由字母数字组成。",
    "This name is available": "该名称可用",
    "Warrior": "战士",
    "Wiki": "维基",
    "The name field must be at least 4 characters.": "名称字段必须至少包含 4 个字符。",
    "The name field must only contain letters and numbers.": "名称字段只能包含字母和数字。",
    "Alchemy": "炼金",
    "ALT + .": "ALT + .",
    "ALT + /": "ALT+/",
    "BETA": "测试版",
    "Campaign": "活动",
    "Character": "角色",
    "Character ID": "角色ID",
    "Click to copy": "点击复制",
    "Close sidebar": "关闭侧边栏",
    "Community": "社区",
    "community is ready to assist. Join us there, and benefit from the support and advice of our friendly and knowledgeable player base.": "社区已准备好提供协助。 加入我们，并从我们友好且知识渊博的玩家群的支持和建议中受益。",
    "Cooking": "烹饪",
    "Feed": "喂养",
    "Fishing": "钓鱼",
    "For every friend you refer, you will receive": "您推荐的每一位朋友，您都会收到",
    "Forge": "锻造",
    "Friends": "朋友",
    "Getting Started": "入门",
    "here": "这里",
    "How many do you want to use?": "您想使用多少个？",
    "Inventory": "仓库",
    "Invite your friends and receive rewards": "邀请好友并获得奖励",
    "It looks like you have no friends.": "看上去你还没有朋友。",
    "Leaderboard": "排行榜",
    "Log out": "登出",
    "Map": "地图",
    "Market": "市场",
    "Membership": "会员",
    "Mining": "采矿",
    "More": "更多",
    "No Friends": "暂无朋友",
    "Open profile": "打开个人资料",
    "Pets": "宠物",
    "Play": "游戏",
    "Please enter 3 or more characters.": "请输入 3 个或更多字符。",
    "Press": "按",
    "Press and hold to drag": "按住可拖动",
    "Received": "收到的",
    "Refer a friend": "邀请好友",
    "Sent": "已发送",
    "Settings": "设置",
    "Should you need further assistance or find the guide lacking, our": "如果您需要进一步帮助或发现缺少指南，我们的",
    "Skills": "技能",
    "Smelting": "冶炼",
    "Switch Character": "切换角色",
    "The rewards will be distributed when your friend has confirmed their email address.": "当您的朋友确认了他们的电子邮件地址后，奖励将会发放。",
    "to get started.": "开始。",
    "to help you get started. is essentially a straightforward manual that covers many of the need-to-knows.": "帮助您入门。 本质上是一本简单明了的手册，涵盖了许多需要了解的内容。",
    "Vendor": "商店",
    "View notifications": "查看通知",
    "We're excited to announce the launch of the IdleMMO beta! Our team has put in tremendous effort to craft this game, and we can't wait for you to dive into it.": "我们很高兴地宣布推出 IdleMMO 测试版！ 我们的团队为制作这款游戏付出了巨大的努力，我们迫不及待地想让您投入其中。",
    "We've created a handy": "我们创建了一个方便的",
    "Welcome!": "欢迎！",
    "Woodcutting": "伐木",
    "You": "你",
    "You don't have any food items in your inventory.": "您的仓库中没有任何食品。",
    "You have no notifications": "您没有任何通知",
    "Your friends will also receive": "您的好友也会收到",
    "Your invitation link:": "您的邀请链接：",
    "Your referral code:": "您的邀请码：",
    "Account": "帐户",
    "Adjust your profile settings.": "调整您的个人资料设置。",
    "Any settings you adjust here only apply to your current character": "您在此处调整的任何设置仅适用于您当前的角色",
    "Appear Offline": "显示为离线",
    "Character Preferences": "角色偏好",
    "Character Settings": "角色设定",
    "Display Active Action": "显示主动动作",
    "Display the amount of tokens you have on your profile.": "显示您的个人资料中拥有的代币数量。",
    "Display Tokens": "显示代币",
    "Enable/disable membership boosts.": "启用/禁用会员提升。",
    "Have your status display as offline.": "将您的状态显示为离线。",
    "Membership Boosts": "会员提升",
    "Profile": "个人资料",
    "Show/hide your active action on your profile to other players.": "在您的个人资料中向其他玩家显示/隐藏您的主动操作。",
    "About": "关于",
    "Accuracy": "精准度",
    "Active Effects": "主动效果",
    "Activity": "活动",
    "Additional Stats": "附加属性",
    "Agility": "敏捷",
    "All Time": "整天",
    "Attack Power": "攻击力",
    "Bartering": "物物交换",
    "Combat": "战斗",
    "Combat Level": "战斗等级",
    "Core Stats": "核心属性",
    "Critical Chance": "暴击几率",
    "Critical Damage": "暴击伤害",
    "Daily Reward": "每日奖励",
    "Damage": "伤害",
    "Defence": "防御",
    "Dexterity": "灵巧",
    "Dexterity increases your accuracy.": "灵巧可以提高你的准确性。",
    "Edit": "编辑",
    "EXP until next level": "经验值到达下一级",
    "Felling Axe": "伐木斧",
    "Fishing Rod": "钓竿",
    "Gold": "黄金",
    "Health": "生命值",
    "Hunting Mastery": "狩猎精通",
    "Level": "等级",
    "Movement Speed": "移动速度",
    "No Data": "无数据",
    "Obtained via Class": "通过职业获得",
    "of": "",
    "Online": "在线",
    "Permanent": "永久",
    "Pickaxe": "镐子",
    "Protection": "防护",
    "Quick Heal": "快速治愈",
    "Redeem": "领取",
    "Redeem Daily Reward": "领取每日奖励",
    "Shadow Mastery": "暗影精通",
    "Simple Felling Axe": "简易伐木斧",
    "Simple Fishing Rod": "简易钓鱼竿",
    "Simple Pickaxe": "简单的镐",
    "Skins": "皮肤",
    "Speed": "速度",
    "Speed increases your agility.": "速度可以提高你的敏捷。",
    "Status": "状态",
    "Strength": "力量",
    "This character has no bio.": "该角色没有简介。",
    "This character has not played enough for their data to be tracked.": "该角色游戏时长太短，无法追踪其数据。",
    "This decreases your damage you receive against opponents.": "这会减少对手对你造成的伤害。",
    "This increases your damage against opponents.": "这会增加你对对手的伤害。",
    "Tokens": "代币",
    "Update Bio": "更新简介",
    "Your daily reward is ready.": "您的每日奖励已准备好。",
    "Yule Mastery": "圣诞精通",
    "Cancel": "取消",
    "EXP": "经验值",
    "Inspect Item": "查看物品",
    "Items Gathered": "收集的物品",
    "Next item in": "下个物品还有",
    "Seconds": "秒",
    "Start": "开始",
    "strength": "力量",
    "Time Spent": "花费的时间",
    "Total Experience": "总经验",
    "woodcutting": "伐木",
    "Your Progress": "您的进度",
    "(including": "（包括",
    "% tax on every item sold.": "% 的税费。",
    "% tax)": "％ 税）",
    "Actions": "行动",
    "Create Market Listing": "创建市场清单",
    "Create Purchase Order": "创建收购订单",
    "Duration": "持续时间",
    "Each": "每个",
    "Extremely Common": "极其常见",
    "Gathered via Mining": "通过采矿收集",
    "How Much": "多少钱",
    "Information": "信息",
    "It looks like no items have been placed on the market.": "市场上似乎还没有任何商品。",
    "Listed by": "卖家",
    "listings.": "清单。",
    "Market Listings": "市场清单",
    "Max": "最大",
    "NO ITEM TIER HAS BEEN SET.": "尚未设置任何物品等级。",
    "No Listings": "没有清单",
    "Ore": "矿石",
    "Price": "价格",
    "Purchase Orders": "收购订单",
    "purchase orders.": "收购订单。",
    "Quality": "质量",
    "Quantity": "数量",
    "Rarity": "稀有度",
    "Standard": "标准",
    "This listing will incur a": "此清单的每个物品出售时都会收取",
    "Tier": "等级",
    "Total Cost": "总成本",
    "Type": "类型",
    "Vendor Value": "商店价值",
    "View more listings": "查看更多清单",
    "You can create a maximum of": "您最多可以创建",
    "Your Character": "你的角色",
    "A bustling and opulent metropolis filled with towering spires, grand architecture, and vibrant markets. The city is a hub of culture, commerce, and diverse inhabitants.": "一座繁华富丽的大都市，充满了高耸的尖塔、宏伟的建筑和充满活力的市场。 这座城市是文化、商业和多元化居民的中心。",
    "A dense and enchanted forest shrouded in mystery. The trees seem to whisper secrets, and magical creatures dwell within. The atmosphere is ethereal and filled with wonders.": "一片茂密而迷人的森林笼罩在神秘之中。 树木似乎在低声诉说秘密，神奇的生物居住在其中。 气氛空灵而充满奇迹。",
    "A hidden sanctuary nestled deep within a mystical desert, where a shimmering pool reflects the moonlight, granting eternal life and bestowing visitors with rejuvenating magic.": "一个隐藏在神秘沙漠深处的圣地，波光粼粼的水池反射着月光，赋予游客永恒的生命，并赋予游客恢复活力的魔法。",
    "A humble and peaceful countryside farm. It is filled with green fields, a cozy farmhouse, and friendly farm animals.": "一个简陋而宁静的乡村农场。 这里充满了绿色的田野、舒适的农舍和友善的农场动物。",
    "A mystical island enveloped in perpetual fog. Eerie whispers and strange apparitions can be encountered here, hinting at ancient secrets and hidden treasures.": "一座永远笼罩在迷雾之中的神秘岛屿。 在这里可以遇到令人毛骨悚然的低语和奇怪的幽灵，暗示着古老的秘密和隐藏的宝藏。",
    "A remote mountaintop observatory where the player can gaze into the cosmos. It offers a mesmerizing view of the stars, planets, and other celestial phenomena.": "一个偏远的山顶天文台，玩家可以在那里凝视宇宙。 它提供了恒星、行星和其他天体现象的迷人视角。",
    "A subterranean wonderland adorned with glittering crystals of various colors. The caves are home to luminescent creatures and rare minerals, creating a breathtaking sight.": "一个地下仙境，装饰着各种颜色的闪闪发光的水晶。 这些洞穴是发光生物和稀有矿物的家园，创造出令人惊叹的景象。",
    "A towering mountain peak that scrapes the heavens. Climbing it is a challenge, but reaching the summit rewards the player with breathtaking views of the world below.": "一座高耸入云的山峰。 攀登它是一项挑战，但到达顶峰后玩家可以欣赏到下面世界的壮丽景色。",
    "Air Elemental": "空气元素",
    "An ethereal realm suspended in the sky, where lush, vibrant gardens hover amidst wisps of mist, their radiant flora nourished by the mystical energy of the floating islands.": "这是一个悬浮在天空中的空灵境界，郁郁葱葱、生机勃勃的花园盘旋在缕缕薄雾中，它们的光彩照人的植物群受到漂浮岛屿的神秘能量的滋养。",
    "An immense fortress floating high above the clouds, accessible only by airships or powerful magic. It serves as a seat of power for the realm's rulers and houses a repository of arcane knowledge.": "一座巨大的堡垒漂浮在云层之上，只能通过飞艇或强大的魔法才能进入。 它是王国统治者的权力宝座，也是神秘知识的宝库。",
    "Arboreal Labyrinth": "树栖迷宫",
    "Bank": "银行",
    "Basillisk": "蛇怪",
    "Black Bear": "黑熊",
    "Bloodmoon Manor": "血月庄园",
    "Boar": "野猪",
    "Buffalo": "水牛",
    "Celestial Enclave": "天界",
    "Chromite Ore": "铬铁矿矿",
    "Copper Ore": "铜矿",
    "Crystal Forge": "水晶熔炉",
    "Cultist": "邪教徒",
    "Cursed Asylum": "被诅咒的庇护所",
    "Deer": "鹿",
    "Distance": "距离",
    "Djinn": "神灵",
    "Duck": "鸭子",
    "Dungeons": "地下城",
    "Dwarven Warrior": "矮人战士",
    "Earth Elemental": "土元素",
    "Eden's Embrace": "伊甸园的拥抱",
    "Elephant": "大象",
    "Elk": "麋鹿",
    "Enemies": "敌人",
    "ENOZI": "伊诺兹",
    "Fire Elemental": "火元素",
    "Forgotten Archives": "被遗忘的档案",
    "Frostbite Spire": "霜冻尖塔",
    "Goblin": "哥布林",
    "Goblin King": "哥布林之王",
    "Golem": "魔像",
    "Gorgon": "蛇发女怪",
    "Griffon": "狮鹫",
    "Harpy": "鹰身女妖",
    "Iron Ore": "铁矿",
    "Isadora": "伊莎多拉",
    "Lion": "狮子",
    "Lurka Stonefist": "卢卡·石拳",
    "Malgazar": "马尔加扎尔",
    "Minotaur": "牛头怪",
    "Mirage Citadel": "幻影城堡",
    "Moose": "驼鹿",
    "Nethrax": "奈斯拉克斯",
    "Ogre": "食人魔",
    "Petrok the Guardian": "守护者佩特洛克",
    "Reaper": "收割者",
    "Recommended Level": "推荐等级",
    "Rogoth": "罗戈特",
    "Ruins of Old Ranhor": "老兰霍尔遗址",
    "Serayne2": "塞雷恩2",
    "Shadow Beast": "暗影兽",
    "Shadowmire": "暗影泥沼",
    "Siren": "塞壬",
    "Skarn the Dreadwake": "恐惧之痕斯卡恩",
    "Skeleton Warrior": "骷髅战士",
    "Skill Items": "技能物品",
    "Slimeball": "粘液球",
    "Spectre": "幽灵",
    "Sylvan Sanctum": "森林圣所",
    "Teleport for": "传送成本",
    "Thal'guth": "萨尔古斯",
    "The Nexus": "枢纽",
    "Time to Travel": "旅行时间",
    "Tloc": "特洛克",
    "Travel": "旅行",
    "Undead Knight": "不死骑士",
    "Verdant Veil": "翠绿面纱",
    "Vineyard Labyrinth": "葡萄园迷宫",
    "Volcanic Depths": "火山深处",
    "Voragor": "沃拉戈尔",
    "Water Elemental": "水元素",
    "Werewolf": "狼人",
    "Whispering Catacombs": "低语地下墓穴",
    "WinterRose": "冬日玫瑰",
    "Witch": "巫婆",
    "Wizard of the South": "南方巫师",
    "Wolf": "狼",
    "World Bosses": "世界首领",
    "Wraith": "幽灵",
    "Zenith's Sanctum": "天顶圣殿",
    "Zombie": "僵尸",
    "Travelling": "旅行中",
    "The daily reward has been redeemed.": "每日奖励已领取。",
    "Bow": "弓",
    "Bar": "锭",
    "Boots": "靴子",
    "Chestplate": "胸甲",
    "Dagger": "匕首",
    "Gauntlets": "护手",
    "Greaves": "护腿",
    "Helmet": "头盔",
    "Shield": "盾",
    "Sword": "剑",
    "Banyan Bow": "榕木弓",
    "Birch Bow": "桦木弓",
    "Mahogany Bow": "桃花心木弓",
    "Maple Bow": "枫木弓",
    "Mystical Bow": "神秘木弓",
    "Oak Bow": "橡木弓",
    "Requirements": "要求",
    "Spruce Bow": "云杉木弓",
    "times.": "次。",
    "Willow Bow": "柳木弓",
    "Yew Bow": "紫杉木弓",
    "You can perform this skill": "你最多可以施展这个技能",
    "You have": "你有",
    "Cooked ": "煮熟的",
    "Thank you for verifing your account.": "感谢您验证您的帐户。",
    "s": "秒",
    "m": "m",
    "h": "小时",
    "d": "天",
    "Eldritch Bait": "怪异诱饵",
    "Elemental Bait": "元素诱饵",
    "Tarnished Bait": "变色的诱饵",
    "The bio field format is invalid.": "简介字段格式无效，不能用中文。",
    "You have arrived at your destination.": "您已到达目的地。",
    "Accuracy determines your chance of landing successive hits against your opponent": "精准度决定了你连续击中对手的机会",
    "Dungeons Nearby": "附近的地下城",
    "Enemies Nearby": "附近的敌人",
    "Hunt": "狩猎",
    "Primary Stats": "主要统计数据",
    "Secondary Stats": "次要统计数据",
    "Start a hunt to find nearby enemies.": "开始狩猎寻找附近的敌人。",
    "Start Hunt": "开始狩猎",
    "Stats": "统计数据",
    "The amount of damage that is applied on the end of every attack regardless of stats.": "每次攻击结束时施加的伤害量，无论统计数据如何。",
    "The bonus that is applied when you land a critical strike.": "当你造成致命一击时应用的奖励。",
    "The chance that you will hit a critical strike.": "你受到致命一击的几率。",
    "The total attack power from your equipment and strength.": "总攻击力来自于你的装备和力量。",
    "This determines how many enemies you encounter after a successful hunt. You can increase this by completing hunts.": "这决定了成功狩猎后您遇到的敌人数量。 您可以通过完成狩猎来增加这一点。",
    "This dictates how fast you can travel and hunt.": "这决定了你旅行和狩猎的速度。",
    "World Bosses Nearby": "附近的世界首领",
    "You can increase up your combat level by defeating enemies.": "你可以通过击败敌人来提高你的战斗等级。",
    "Your agility gained from your speed skill and equipment.": "你的敏捷是从你的速度技能和装备中获得的。",
    "Your total protection gained from your defence skill and equipment.": "你的总计防护来自于你的防御技能和装备。",
    "You have successfully updated your bio.": "您已成功更新您的个人简介。",
    "Log": "原木",
    "Gathered via Woodcutting": "通过伐木收集",
    "List on Market": "上架到市场",
    "Sell to Vendor": "出售给商店",
    "Empty": "空",
    "Equipped": "已装备",
    "Select an item": "选择一个物品",
    "Chest": "宝箱",
    "Hands": "手部",
    "Head": "头部",
    "Legs": "腿部",
    "Missing Special": "缺少特殊装备",
    "Missing Boots": "缺少靴子",
    "Missing Chest": "缺少胸甲",
    "Missing Hands": "缺少手部",
    "Missing Head": "缺少头部",
    "Missing Legs": "缺少腿部",
    "Missing Off Hand": "缺少副手",
    "Missing Primary Hand": "缺少主手",
    "Off Hand": "副手",
    "Primary Hand": "主手",
    "Please travel to a city to access your bank.": "请前往一个城市才能访问您的银行。",
    "There are no banks nearby.": "附近没有银行。",
    "All": "全部",
    "Bait": "诱饵",
    "Anglers Essence Crystal": "垂钓精华水晶",
    "Boar Tusk": "野猪獠牙",
    "Cheap Bait": "便宜的诱饵",
    "Cheap Vial": "便宜的小瓶",
    "Fish": "鱼",
    "Hat": "帽子",
    "Item Type": "物品类型",
    "Listings": "订单",
    "Maximum Price": "最高价",
    "Minimum Price": "最低价",
    "Maximum Tier": "最高等级",
    "Minimum Tier": "最低等级",
    "Metal Bar": "金属锭",
    "Pet Egg": "宠物蛋",
    "Search": "搜索",
    "Potion": "药水",
    "Skin": "皮肤",
    "Special": "特殊",
    "Upgrade Stone": "升级石",
    "Swamp Juice": "沼泽果汁",
    "Snakes Head": "蛇头",
    "Smelting Essence Crystal": "冶炼精华水晶",
    "Shelly Egg": "雪莉蛋",
    "Recipe": "配方",
    "Ruined Robes": "破损的长袍",
    "Not Equipable": "不可装备",
    " Recipe": "配方",
    "Crown": "王冠",
    "Pouch": "小袋",
    "Scraps": "废料",
    "Totem": "图腾",
    "Aquastar": "海星",
    "Aquastar Egg": "海星蛋",
    "Campaign Item": "活动物品",
    "Crafting Material": "工艺材料",
    "Djinn's Bottle": "巨灵之瓶",
    "Ducks Mouth": "鸭嘴",
    "Essence Crystal": "精华水晶",
    "Essence of Shadows": "暗影精华",
    "Filter": "筛选",
    "Food": "食物",
    "Lucky Rabbit Foot": "幸运兔脚",
    "to": "到",
    "Totem": "图腾",
    "Vial": "瓶子",
    "Yours": "你的",
    "Aquarion Egg": "阿奎里翁蛋",
    "Attack Power Potion Recipe": "攻击力药水配方",
    "Battle Potion": "战斗药水",
    "Bladeburst Elixir Recipe": "剑刃爆裂药剂配方",
    "Bone Fragment": "骨头碎片",
    "Buffalo Horn": "水牛角",
    "Chefs Essence Crystal": "厨师精华水晶",
    "Chest of Scraps": "废料箱",
    "Cursed Talisman": "被诅咒的护身符",
    "Deer Antler": "鹿茸",
    "Dungeon Potion": "地下城药水",
    "Felling Essence Recipe": "伐木精华配方",
    "Fluffy Egg": "毛茸茸蛋",
    "Forbidden Tome": "禁书",
    "Fortified Protection Recipe": "强化防护配方",
    "Improved Pickaxe": "改进的镐",
    "Improved Pickaxe Recipe": "改进的镐配方",
    "Ironclad Tonic Recipe": "铁定补品配方",
    "Long Forgotten Necklace": "被遗忘已久的项链",
    "Lumberjack Essence Crystal": "伐木工精华水晶",
    "Merfolk Essence Recipe": "人鱼精华配方",
    "Miners Essence Crystal": "矿工精华水晶",
    "Molten Core Tonic Recipe": "熔火之心补品配方",
    "Oreseeker Potion Recipe": "矿石探索者药水配方",
    "Parchment": "羊皮纸",
    "Pirates Code": "海盗法典",
    "Precision Potion Recipe": "精准药水配方",
    "Protection Potion Recipe": "防护药水配方",
    "Quickstep Potion": "快步药水",
    "Quickstep Potion Recipe": "快步药水配方",
    "Raw Onion": "生洋葱",
    "Rivertamer": "河驯者（鱼竿）",
    "Rivertamer Recipe": "河驯者配方（鱼竿）",
    "Seasong's Lure Recipe": "季节的诱饵配方（鱼竿）",
    "Slime Extract": "史莱姆提取物",
    "Spicefinder": "香料发现者",
    "Spicefinder Potion Recipe": "香料发现者药水配方",
    "Timberfall Essence Crystal": "木落精华水晶",
    "Timberfall Talon": "伐木之爪（斧子）",
    "Timberfall Talon Recipe": "伐木之爪配方（斧子）",
    "Titan Power Brew Recipe": "泰坦力量酿造配方",
    "Token": "代币",
    "Vial of Spectre Ectoplasm": "一瓶幽灵灵质",
    "Vortex Brew Recipe": "涡旋酿造配方",
    "Wildwood Chopper Recipe": "野木伐木斧配方",
    "Hammerfell Essence Crystal": "落锤精华水晶",
    "Venom Extract": "毒液提取物",
    "By @": "卖家 @",
    "Seller": "卖家",
    "Purchase Item": "购买物品",
    "It looks like you have no friend requests.": "您没有收到好友请求。",
    "No Friend Requests": "无好友请求",
    "Idling": "放置中",
    "It looks like you have not sent any friend requests.": "您没有发送过好友请求。",
    "Activate": "进行中",
    "At the farm festival, folks gather for good tunes, tasty food, and a bit of dancing between the cornrows. As night falls, everyone chills under the stars, swapping stories and enjoying the simple joys of farm life.": "在农场节日期间，人们聚集在一起聆听美妙的音乐、享用美味的食物，并在玉米穗间跳舞。 夜幕降临，大家在星空下闲聊，交换故事，享受农家生活的简单乐趣。",
    "Bluebell Festival": "蓝铃花节",
    "Chest of Upgrade Stones": "升级石宝箱",
    "Daily": "日常",
    "Divinius Skin": "迪维尼斯皮肤",
    "Item": "物品",
    "Monthly": "月常",
    "Points": "点数",
    "Preview": "预览",
    "Progress:": "进度：",
    "Seraphina": "塞拉菲娜",
    "Seraphina Skin": "塞拉菲娜皮肤",
    "Switch Campaign": "切换活动",
    "Tasks": "任务",
    "Time Limited": "限时",
    "Weekly": "周常",
    "Whispers of Daybreak Background": "黎明的低语背景",
    "Yule Fest": "圣诞节",
    "Hunting": "狩猎中",
    "Hunting Enemies": "狩猎敌人",
    "The hunt begins.": "狩猎开始了。",
    "Pro Tip:": "专家提示：",
    "in total).": "总计).",
    "enemies (": "敌人 (",
    "Hunt Again": "再试一次",
    "You can chain an additional": "您可以链接额外",
    "Potential Drops": "潜在掉落",
    "Experience": "经验值",
    "Run Away": "逃离",
    "The battle has started": "战斗开始了",
    "Join Lobby": "加入大厅",
    "Cost": "成本",
    "Success Chance": "成功几率",
    "You are not a high enough level to do this.": "你的等级还不够高，没法这样做。",
    "The action has been cancelled.": "该动作已被取消。",
    "Completed": "已完成",
    "A token pack is an item that can be sold or traded. The tokens will be bound to your character upon use of the item.": "代币包是可以出售或交易的物品。 使用该物品时，代币将与您的角色绑定。",
    "Arcane Bait": "奥术诱饵",
    "Arcane Vial": "奥术瓶",
    "Backgrounds": "背景",
    "Eldritch Vial": "怪异之瓶",
    "Elemental Vial": "元素瓶",
    "Elfina": "埃尔菲娜",
    "Elfirma": "埃尔菲尔玛",
    "Empty Crystal": "空水晶",
    "Feron": "费隆",
    "Freya": "芙蕾雅",
    "Gleaming Bait": "闪闪发光的诱饵",
    "Gleaming Vial": "闪闪发光的小瓶",
    "How many do you want to purchase?": "您想购买多少个？",
    "Isolde": "伊索尔德",
    "Items": "物品",
    "Katiyara": "卡蒂亚拉",
    "Leilatha": "莱拉萨",
    "Looking for some tokens? Buy some here.": "正在寻找一些代币？ 在这里买一些。",
    "Lucian": "卢西恩",
    "Mircus": "米尔库斯",
    "Most popular": "最受欢迎",
    "Pricing displayed in USD": "定价以美元显示",
    "Purchase": "购买",
    "Purchase for": "购买花费",
    "Purchase Tokens": "购买代币",
    "Slots": "槽位",
    "Svernom": "斯韦尔诺姆",
    "Tanished Vial": "晒黑的小瓶",
    "Used to catch fish.": "用来抓鱼。",
    "Your purchase was successful.": "您已成功购买。",
    "Select a pet": "选择一个宠物",
    "\" for 50% off your first month when subscribing for the first time!": "\" 首次开会员可享受第一个月 50% 的折扣！",
    "/item": "/物品",
    "/month": "/月",
    "/year": "/年",
    "+10% boost in skill efficiency.": "+10% 技能效率提升。",
    "100 tokens every month": "每月 100 个代币",
    "200 tokens on sign-up": "注册即可获得 200 个代币",
    "200 tokens on sign-up.": "注册时可获得 200 个代币。",
    "A single item entitles the user to 30 days of membership.": "单个物品使用户有权获得 30 天的会员资格。",
    "All of the listed benefits apply to every character.": "所有列出的好处都适用于每个角色。",
    "Always running out of space? No problem. Membership gives you an additional 7 inventory slots.": "总是空间不足？ 没问题。 会员资格为您提供额外 7 个仓库位。",
    "And so much more...": "还有更多...",
    "Benefits apply to every character": "福利适用于每个角色",
    "Benefits apply to every character.": "好处适用于每个角色。",
    "Better daily rewards.": "更好的每日奖励。",
    "Create longer purchase orders.": "创建更长的采购订单。",
    "Create purchase orders that can last up to 14 days instead of 3 days.": "创建可持续长达 14 天而不是 3 天的采购订单。",
    "Double your friends list.": "将你的朋友名单加倍。",
    "Every one of your characters will obtain 100 tokens on the 15th of every month.": "您的每一位角色都会在每月 15 日获得 100 代币。",
    "Featured": "精选",
    "Find out more": "了解更多",
    "Get 7 more pet slots on top of your existing slots.": "在现有宠物槽位的基础上再增加 7 个宠物槽位。",
    "Get a small 10% boost in efficiency for all skills.": "所有技能的效率小幅提升 10%。",
    "Get a unique membership badge for your profile.": "为您的个人资料获取独特的会员徽章。",
    "Get improved rewards every day for every character.": "每个角色每天都会获得更好的奖励。",
    "Gradient on your character name": "你的角色名字的渐变",
    "Have too many friends? Membership allows you to add even more friends.": "有太多朋友吗？ 会员资格可以让您添加更多朋友。",
    "Increase your maximum idle time": "增加最长空闲时间",
    "Increase your maximum idle time from 80 minutes to 120 minutes.": "将最长空闲时间从 80 分钟增加到 120 分钟。",
    "Increase your maximum idle time.": "增加最大空闲时间。",
    "Increase your maximum listings from 10 to 25.": "将最大列表数量从 10 个增加到 25 个。",
    "Increase your maximum purchase orders from 10 to 25.": "将最大采购订单数从 10 增加到 25。",
    "Less tax on market sales.": "减少市场销售税。",
    "Level up your IdleMMO experience with our membership subscription. Gain access to exclusive benefits, discover new locations, and embark on thrilling adventures like never before.": "通过我们的会员订阅提升您的 IdleMMO 体验。 获得独家优惠，发现新地点，并开始前所未有的惊险冒险。",
    "Membership Benefits": "会员福利",
    "More listings": "更多房源",
    "More orders": "更多订单",
    "Obtain 200 tokens immediately when you subscribe for the very first time.": "首次订阅即刻获得200代币。",
    "Obtain 7 more inventory slots.": "获得 7 个以上的仓库槽位。",
    "Obtain 7 more pet slots": "获得另外 7 个宠物槽位",
    "Obtain an addtional +15% EXP on every action you perform and enemy you defeat": "你执行的每一个动作和你击败的敌人都会获得额外的 +15% EXP",
    "Pricing displayed in USD": "定价以美元显示",
    "Purchase": "购买",
    "Reduce the tax incured on any sales you make on the market.": "减少您在市场上进行的任何销售所产生的税款。",
    "Stand out from the crowd with a gradient character name.": "用渐变的角色名称从人群中脱颖而出。",
    "Support the games continuous development by upgrading your account.": "通过升级您的帐户来支持游戏的持续发展。",
    "Support the games development": "支持游戏开发",
    "Take it to the next level": "将其提升到一个新的水平",
    "Unique Badge": "独特徽章",
    "US$6.99": "$6.99 美元",
    "Use promo code \"": "使用促销代码\"",
    "Want to purchase for a friend?": "想帮朋友购买吗？",
    "WELCOME50": "WELCOME50",
    "Yearly": "每年",
    "You can purchase membership packs as items. You can send them to your friends or trade them on the market.": "您可以购买会员包作为物品。 您可以将它们发送给您的朋友或在市场上进行交易。",
    "King": "之王",
    "Filters": "过滤器",
    "Global": "全局",
    "Show Filters": "显示过滤器",
    "Deepsea Essence Crystal": "深海精华水晶",
    "Dungeon Master's Tonic": "地下城主的补品",
    "Flavorburst Essence Crystal": "爆香精华水晶",
    "Lions Teeth": "狮子的牙齿",
    "Rocksplitter Essence Crystal": "裂岩精华水晶",
    "You have completed a monthly task": "你完成了一个月常任务",
    "You have completed a weekly task": "你完成了一个周常任务",
    "You have completed a daily task": "你完成了一个日常任务",
    "Additional Bank Slot": "额外的银行槽位",
    "Additional Inventory Slot": "额外的仓库槽位",
    "Additional Pet Slot": "额外的宠物槽位",
    "Character Slot": "角色槽位",
    "Your skill has finished.": "你的技能已完成。",
    "Currently equipped": "当前已装备",
    "Equip": "装备",
    "Gathered via Smelting": "通过冶炼收集",
    "Inspect": "查看",
    "level": "等级",
    "List On Market": "上架到市场",
    "Upgrade": "升级",
    "Value": "价值",
    "You have equipped the item.": "您已装备该物品。",
    "Missing Felling Axe": "缺失的伐木斧",
    "Missing Fishing Rod": "缺失的鱼竿",
    "Missing Pickaxe": "缺失的镐子",
    "You have unequipped the item.": "你已经脱下了这个物品。",
    "Unequip": "脱下",
    "Craftable Item": "可加工物品",
    "Felling Essence Crystal": "掉落精华水晶",
    "Premium": "优质",
    "Recipe Requirements": "配方要求",
    "Used for alchemy.": "用于炼金。",
    "Finishes in": "距离完成还有",
    "Processing...": "加工中...",
    "Your Forge action is complete.": "你的锻造动作已完成。",
    "Your Smelting action is complete.": "你的冶炼动作已完成。",
    "Your Cooking action is complete.": "你的烹饪动作已完成。",
    "Your Mining action is complete.": "你的采矿动作已完成。",
    "Your Alchemy action is complete.": "你的炼金动作已完成。",
    "Your Fishing action is complete.": "你的钓鱼动作已完成。",
    "Your Woodcutting action is complete.": "你的伐木动作已完成。",
    "Open": "进行中",
    "Expires in": "距离过期",
    "Bladeburst Elixir": "剑刃爆裂药剂",
    "Cosmic Crystal": "宇宙水晶",
    "Fulfill": "卖给他",
    "Price Per Item": "单个物品价格",
    "Sell Item": "出售物品",
    "Your Inventory": "你的仓库",
    "Buyer": "收购者",
    "How many do you want to sell?": "你想出售多少个？",
    "Refined": "精致",
    "Used to forge a standard pickaxe.": "用于锻造标准镐。",
    "Equipable": "是否可装备",
    "Unremarkable": "平淡无奇",
    "Your class does not support this item.": "您的职业不能装备此物品。",
    "Stats and Effects": "属性和效果",
    "Now": "现在",
    "You have joined the lobby.": "你已加入大厅。",
    "You are already battling this enemy": "你已经在与这个敌人作战了",
    "Accept": "同意",
    "Deny": "拒绝",
    "Offline": "离线",
    "You have accepted the friend request.": "你已同意该好友请求。",
    "This character is a member.": "这个角色是会员。",
    "Add Friend": "加好友",
    "Obtained via Membership": "通过会员获取",
    "Obtained via Equipment": "通过装备获取",
    "You do not fulfill the requirements.": "你不满足要求。",
    "Away": "离开",
    "They have already sent you a friend request.": "对方已经向您发送了好友请求。",
    "Your health increases": "你恢复了一些生命值",
    "You are already on a hunt": "你已经在狩猎了",
    "You have successfully defeated a world boss.\n\nYou have obtained:": "您已成功击败世界首领。\n\n您获得了：",
    "You cannot join World Boss that has not started yet.": "尚未开始的世界Boss无法加入。",
    "You are already in the process of performing another action.": "您已经在执行另一项操作，请停止后重试。",
    "Wildwood Chopper": "野木伐木斧",
    "premium": "高级",
    "refined": "精致",
    "You do not fulfill the items requirements.": "您不符合物品要求。",
    "Gathered via Hunting": "通过狩猎收集",
    "Increase your pet slots by 1.": "将你的宠物槽位增加 1 个。",
    "Increase your bank slots by 1.": "将你的银行槽位增加 1 个。",
    "Increase your inventory slots by 1.": "将你的仓库槽位增加 1 个。",
    "Increase your character slots by 1.": "将你的角色槽位增加 1 个。",
    "Inventory Slot": "仓库槽位",
    "Pet Slot": "宠物槽位",
    "Bank Slot": "银行槽位",
    "Background Skin": "背景皮肤",
    "Skins are for cosmetic purposes only and provide no additional bonuses.": "皮肤仅用于装饰目的，不提供任何额外奖励。",
    "A serene expanse of ice and snow, where nature sleeps beneath a crystalline blanket. Stark, tranquil, and unyielding in its frozen beauty.": "一片宁静的冰天雪地，大自然在水晶毯下沉睡。 其冰冷之美中鲜明、宁静、不屈。",
    "Frozen Mirror": "冰冻之镜（Frozen Mirror）",
    "Alpine": "阿尔卑斯山（Alpine）",
    "A riot of warm hues, where the world dons a tapestry of reds and golds. Leaves fall like confetti, whispering the arrival of autumn's embrace.": "缤纷的暖色调，世界披上了红色和金色的挂毯。树叶像五彩纸屑一样飘落，悄无声息地宣告着秋天拥抱的到来。",
    "Character Skin": "角色皮肤",
    "Isolde exudes shyness. Her eyes, often downcast, hide untold stories. The red fabric of her dress flows gracefully, symbolizing a quiet strength. Isolde's unobtrusive presence belies a deep, thoughtful personality, inviting curiosity and intrigue.": "伊索尔德流露出羞涩。她的眼睛常常低垂，隐藏着不为人知的故事。她连衣裙的红色布料优雅地流动着，象征着一种安静的力量。伊索尔德不引人注目的存在掩盖了他深沉、体贴的个性，吸引了好奇心和阴谋。",
    "Freya, a sneaky blonde baby-faced assassin with a swift demeanor and an obsession for cats. Her movements are quick and graceful, mirroring the felines she adores. Her light-footedness and agility make her a cunning presence.": "芙雷娅，一个狡猾的金发娃娃脸杀手，举止敏捷，痴迷于猫。她的动作敏捷优美，与她所喜爱的猫科动物如出一辙。她轻盈的脚步和敏捷的动作使她成为一个狡猾的存在。",
    "Lucian, a man shrouded in mystery, is always masked, embracing the shadows as his ally. His sneaky and cunning nature is honed by his devotion to the shadowblades' secretive arts. Lucian's presence is barely felt, yet his influence is profound, a silent guardian of the night.": "卢西恩，一个笼罩在神秘中的人，总是戴着面具，拥抱着阴影作为他的盟友。他狡猾狡诈的本性是由他对黑影术的执着所磨练出来的。卢西安的存在几乎没有人感觉到，但他的影响是深远的，是夜晚的无声守护者。",
    "Ankhotep, a name steeped in wisdom and intellect, was once an esteemed advisor to an emperor. However, his unwavering commitment to family led him to choose a humble life in the desert. A paragon of familial devotion, he embodies both the brilliance of the mind and the warmth of the heart.\n\n\n\n\n": "",
    "Your dungeon expedition is complete.\n\nYou have obtained:": "你的地下城探险已经完成。\n\n您已获得：",
    "A male embodiment of darkness, marked by evil and a haunting past of making a deal with the devil. This untrustworthy warrior of the night roams with a lost soul, a shadow amongst shadows. His resolve is chilling, stopping at nothing to achieve his sinister goals, a testament to his ominous pact.": "黑暗的男性化身，以邪恶和与魔鬼交易的难忘过去为标志。这个不可信任的夜晚战士带着一个迷失的灵魂漫游，一个阴影中的影子。他的决心令人不寒而栗，不遗余力地实现他的险恶目标，这证明了他不祥的约定。",
    "Astaroth, the royal wizard of the underworld, wields dark magic with a sinister finesse. His presence is commanding, and his knowledge of the arcane is vast and forbidding. In his quest for power, he manipulates and schemes, a master of shadowy arts, feared by many for his ruthless ambition.": "阿斯塔罗斯，地下世界的皇家巫师，以邪恶的手法施展着黑暗魔法。他的存在是威严的，他对奥术的了解是广阔而令人生畏的。在追求权力的过程中，他操纵和策划，是一位神秘艺术大师，因其无情的野心而受到许多人的恐惧。",
    "Celestria, cloaked in starlight, wields ancient magic with a grace that transcends time. Her eyes, pools of mystic wisdom, illuminate paths in darkness. A guardian of peace, her presence soothes troubled souls, and her touch heals the deepest of wounds. Celestria embodies the pure essence of benevolence.": "披着星光的Celestria以超越时间的优雅施展着古老的魔法。她的眼睛，神秘智慧的源泉，照亮了黑暗中的道路。作为和平的守护者，她的出现抚慰了陷入困境的灵魂，她的触摸治愈了最深的创伤。Celestria体现了仁爱的纯粹精华。",
    "Gerrin, a warrior of the night, grapples with his innate goodness and the evil he's come to embody. As Feron's brother, his naivety led him astray, born into circumstances that darkened his path. Yet, beneath his hardened exterior lies a heart yearning for redemption, hinting at a future where he might right his wrongs.": "Gerrin，一个夜晚的战士，与他天生的善良和邪恶作斗争。作为费隆的哥哥，他的天真让他误入歧途，出生在黑暗的环境中。然而，在他坚硬的外表下，隐藏着一颗渴望救赎的心，暗示着他可能会纠正错误的未来。",
    "Ravenna, having struck a dark bargain with the devil, has become a fearsome manifestation of death. Her presence is chilling, and her gaze pierces souls, leaving a trail of dread. She wields her newfound powers with a malevolent grace, embodying the very essence of demise and despair.": "拉文娜与魔鬼达成了一项黑暗的交易，成为了死亡的可怕表现。她的出现令人不寒而栗，她的凝视穿透了灵魂，留下了恐惧的痕迹。她以恶毒的优雅运用她新发现的力量，体现了死亡和绝望的本质。",
    "Groloth, despite his imposing appearance, exudes a passive \"go with the flow\" demeanor. He lost the capacity to care about the world's affairs after the loss of his son. Neither inherently good nor evil, he perceives the world with unfiltered clarity, detached yet profoundly aware of its true nature.": "格罗洛斯，尽管外表威严，却散发出一种被动的“随波逐流”的风度。失去儿子后，他失去了关心世界事务的能力。他既不是天生的善，也不是天生的恶，他以未经过滤的清晰感知世界，超然但深刻地意识到它的真实本质。",
    "Katiyara, a woman of ethereal beauty, possesses blonde hair and captivating blue eyes. Celebrated as the world's most powerful healer, her kindness resonates deeply in her every action. As a direct descendant of a god, she embodies both celestial allure and unparalleled healing gifts, embodying grace and compassion.": "Katiyara，一个空灵美丽的女人，拥有金色的头发和迷人的蓝眼睛。被誉为世界上最强大的治疗师，她的善良在她的每一个行动中都产生了深刻的共鸣。作为一个神的直系后裔，她体现了天堂的诱惑和无与伦比的治愈天赋，体现了优雅和同情。",
    "Mircus, a templar knight and valiant warrior, stands as a bastion of unwavering devotion to the church and the worship of Odith. His life is dedicated to protecting the innocent, embodying the virtues of courage and righteousness. His presence is a symbol of hope and steadfast faith.": "密尔库斯是一位圣殿骑士和英勇的战士，是坚定不移地献身于教堂和崇拜奥迪斯的堡垒。他的一生致力于保护无辜者，体现了勇气和正义的美德。他的出现是希望和坚定信念的象征。",
    "Fendral, a young and ambitious man, has a bright spark in his eyes, showing his eagerness to make a difference. Quick-thinking and always ready to learn, he approaches challenges with a mix of youthful energy and a strong sense of right and wrong, driven to improve the world around him.": "芬德拉尔，一个年轻而雄心勃勃的人，他的眼睛里有一个明亮的火花，显示出他渴望有所作为。思维敏捷，随时准备学习，他以年轻的活力和强烈的是非意识来应对挑战，并致力于改善周围的世界。",
    "Elfina, a cunning yet loyal elf, boasts striking blonde hair and vivid green eyes. Her trust is hard-won, reflecting her cautious nature. Once committed, she's unwaveringly reliable. Her elven heritage adds grace to her astute mannerisms, making her a dependable ally with a depth of wisdom.\n\n\n\n\n": "埃尔芬娜是一个狡猾但忠诚的小精灵，拥有引人注目的金发和生动的绿色眼睛。她的信任来之不易，这反映了她谨慎的天性。一旦承诺，她就坚定不移地可靠。她的精灵血统为她精明的举止增添了优雅，使她成为一个有着深厚智慧的可靠盟友。\n \n \n \n",
    "Leilatha, with her striking silver hair, exudes energy and humor. Her ever-positive attitude enables her to overcome adversity with grace. Known for her exceptional friendliness and welcoming nature, she radiates warmth and resilience, making her a cherished presence in any circle.": "莱莱塔留着一头引人注目的银发，散发着活力和幽默。她一贯积极的态度使她能够优雅地克服逆境。她以其非凡的友好和热情好客而闻名，散发着温暖和坚韧，使她在任何圈子里都是一个值得珍惜的存在。",
    "Svernom, a male with horrific facial injuries, possesses a stoic demeanor and a perspective that sees the world in its truest form. Beneath his hardened exterior lies a good heart, rarely revealed. Once a member of the royal guards of the underworld, his defiance against the king led to his exile.": "Svernom是一名面部严重受伤的男性，他有着坚忍的风度，有着最真实的视角来看待世界。在他坚硬的外表下，隐藏着一颗善良的心，很少被人发现。他曾经是黑社会的皇家卫队成员，对国王的反抗导致了他的流亡。",
    "Melriel, with her luminous blonde hair and captivating blue eyes, presents an enigmatic blend of stunning beauty and intricate character. Stubborn and often cold, her actions teeter on the edge of moral ambiguity. Despite her allure, Melriel's untrustworthy nature weaves a complex web around her true intentions.": "Melriel有着一头明亮的金发和迷人的蓝眼睛，呈现出迷人的美丽和复杂的性格的神秘融合。她的行为固执而冷漠，在道德模糊的边缘摇摇欲坠。尽管梅尔里尔很有魅力，但她不可信任的天性围绕着她的真实意图编织了一张复杂的网。",
    "Orcenzum, an orc warrior, embodies the raw essence of evil yet remains a simple and loyal follower. As a commander of a small group, he grapples with the nuances of leadership, often finding himself at odds with the complexities of command. His straightforward nature contrasts with the responsibilities of his role.\n\n\n\n\n\n": "奥肯祖姆，一个兽人战士，体现了邪恶的原始本质，但仍然是一个简单而忠诚的追随者。作为一个小团体的指挥官，他努力处理领导的细微差别，经常发现自己与指挥的复杂性不一致。他直率的本性与他所扮演角色的责任形成鲜明对比。\n \n \n \n",
    "Sheira, the dark haired prince, harbors a grand ambition to conquer the world. Driven by a deep-seated desire to impress his father, the king of the underworld, his path is marked by ruthless decisions and the tragic cost of many innocent lives.": "黑头发的王子希拉怀有征服世界的雄心壮志。在一种根深蒂固的欲望的驱使下，他想给他的父亲，黑社会之王留下深刻印象，他的道路上有着无情的决定和许多无辜生命的悲惨代价。",
    "Thorgarr, a typical grunt in the ranks of malevolence, exudes an aura of brute force. His name is synonymous with brutality, and his actions are driven solely by obedience to a sinister cause. With a hulking physique and a lack of individuality, he serves as a faceless enforcer of darkness.": "Thorgarr，一个典型的恶毒的咕哝者，散发着一种暴力的气息。他的名字是残暴的代名词，他的行为完全是出于对邪恶事业的服从。他身材魁梧，缺乏个性，是一个默默无闻的黑暗执行者。",
    "Onroth, an Oakenra, akin to a cunning trickster, possesses a sly demeanor reminiscent of mischievous deities. Skillful in the art of deception, they expertly weave intricate webs of lies, cultivating an expansive network of spies to further their enigmatic agenda.\n\n\n\n\n": "奥肯拉的昂罗斯，类似于一个狡猾的骗子，拥有一种让人想起恶作剧神的狡猾举止。他们精通欺骗艺术，熟练地编织错综复杂的谎言网，培养了一个庞大的间谍网络，以推进他们神秘的议程。\n \n \n \n",
    "Vandellian, the commander of the royal guards of the underworld, stands as the formidable successor to Svernom, who was exiled for disobedience. His nature is steeped in evil, a stark contrast to his predecessor. Adorned in remarkable armor of black and red, Vandellian embodies the fearsome authority and dark elegance of his position.": "范德利安是冥界皇家卫队的指挥官，他是因不服从命令而被流放的斯维尔诺姆的强大继承者。 他本性邪恶，与他的前任形成鲜明对比。 范德尔利安身穿引人注目的黑色和红色盔甲，体现了他的地位的可怕权威和黑暗优雅。",
    "Elfirma, a strong warrior with blonde hair, is a paragon of strength and valor. Adorned in heavy armor, she stands unyielding in the face of adversity. Her warrior spirit is as formidable as her armor, symbolizing her unbreakable resolve and exemplary courage.": "艾尔菲尔玛是一位金发强壮的战士，是力量和勇气的典范。 她身披重甲，在逆境中不屈不挠。 她的战士精神就像她的盔甲一样令人畏惧，象征着她坚不可摧的决心和堪称典范的勇气。",
    "Thornrend, a young and enigmatic figure, embodies the essence of a wild card. Their unpredictable nature keeps others guessing. Remarkably, despite their wooden form, they possess an unusual fondness for fire, a paradox within their very being.\n\n\n\n\n": "索伦德是一个年轻而神秘的人物，体现了外卡的本质。 他们不可预测的天性让其他人不断猜测。 值得注意的是，尽管它们是木制的，但它们对火有着不同寻常的喜爱，这在它们的存在中是一个悖论。\n\n\n\n\n",
    "Ankhotep": "安科特普",
    "Astaroth": "阿斯塔罗斯",
    "Bronn": "布隆",
    "Bronn, a traveler known for his extreme versatility and skill in sailing, was once a trader of exotic goods. His journey took a decisive turn when he embarked on a quest to defeat the witch Isodora.": "波隆是一位旅行家，以其多才多艺和航海技巧而闻名，他曾经是一名异国货物贸易商。 当他开始寻求击败女巫伊索多拉时，他的旅程发生了决定性的转折。",
    "Celestria": "塞莱斯蒂亚",
    "Fendral": "芬德拉尔",
    "Gerrin": "杰兰",
    "Groloth": "格罗洛斯",
    "Melriel": "梅尔里尔",
    "Onroth": "翁罗斯",
    "Orcenzum": "奥森祖姆",
    "Ravenna": "拉文纳",
    "Roclus": "罗克洛斯",
    "Roclus, a simple farmer with an air of wisdom, leads a plain and unremarkable life. His neutral stance in a world of contrasting forces is pragmatic; he interacts with both good and evil creatures, motivated by the gold they bring.": "罗克洛斯是一位朴实、充满智慧的农民，过着平淡无奇的生活。 在一个力量对比鲜明的世界中，他的中立立场是务实的。 他与善恶生物互动，受到它们带来的黄金的激励。",
    "Shiera": "希拉",
    "This item will eventually be removed from the store. However, it may return again in the future.": "该商品最终将从商店中删除。 然而，它可能会在未来再次回归。",
    "Thorgarr": "索加尔",
    "Thornrend": "索恩兰德",
    "Vandellian": "范德尔利安",
    "Performing an expedition...": "进行一次探险...",
    "Start Dungeon": "开始探索地下城",
    "You start on your expedition.": "你开始了你的探险。",
    "": "",
    "A small, worn leather pouch that once belonged to the Goblin. It is surprisingly well-crafted, with hidden compartments and a concealed lock.": "一个破旧的小皮包，曾经属于哥布林。 它的制作精良得令人惊讶，有隐藏的隔间和隐藏的锁。",
    "": "",
    "Gathered via Fishing": "通过钓鱼收集",
    "(Experimental)": "（实验性）",
    "Action Pop": "动作提示",
    "Adjust any miscellaneous settings.": "调整任何其他设置。",
    "Adjust your audio settings.": "调整您的音频设置。",
    "Animations": "动画",
    "Announcements": "公告",
    "Are you sure you want to delete your account?": "您确定要删除您的帐户吗？",
    "Audio": "音频",
    "Billing": "计费",
    "Billing Portal": "计费门户",
    "Confirm Password": "确认密码",
    "Current Password": "当前密码",
    "Delete Account": "删除帐户",
    "Email": "电子邮件",
    "Email Marketing": "电子邮件营销",
    "Email Notifications": "电子邮件通知",
    "Enable/disable animations. This may increase performance but cause unintended side-effects.": "启用/禁用动画。 这可能会提高性能，但会导致意想不到的副作用。",
    "Enable/disable the pop sound when obtaining an item.": "启用/禁用获取物品时的弹出声音。",
    "Ensure your account is using a long, random password to stay secure.": "确保您的帐户使用长的随机密码以确保安全。",
    "Go to Billing Portal": "前往计费门户",
    "It will take 21 days for this deletion request to be processed. You can cancel the deletion process any time before this.": "此删除请求需要 21 天才能得到处理。 您可以在此之前随时取消删除过程。",
    "Manage which emails you receive.": "管理您收到的电子邮件。",
    "Manage your membership subscription here.": "在此管理您的会员订阅。",
    "Manage your Web App billing here.": "在此管理您的 Web 应用程序计费。",
    "New Password": "新密码",
    "Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.": "一旦您的帐户被删除，其所有资源和数据将被永久删除。 在删除您的帐户之前，请下载您希望保留的任何数据或信息。",
    "Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.": "一旦您的帐户被删除，其所有资源和数据将被永久删除。 请输入您的密码以确认您想要永久删除您的帐户。",
    "Other": "其他",
    "Password": "密码",
    "Process an account deletion and have all of your data destroyed.": "处理帐户删除并销毁您的所有数据。",
    "Profile Information": "档案信息",
    "Receive any emails related to any marketing or promotions.": "接收与任何营销或促销相关的任何电子邮件。",
    "Recieve any emails related to any account reminders.": "接收与任何帐户提醒相关的任何电子邮件。",
    "Recieve any emails related to important announcements in the game.": "接收与游戏中重要公告相关的任何电子邮件。",
    "Reminders": "提醒事项",
    "The Billing Portal can only modify your Web App billing. You cannot alter your iOS or Android billing here.": "计费门户只能修改您的 Web 应用程序计费。 您无法在此处更改您的 iOS 或 Android 账单。",
    "Update Password": "更新密码",
    "Update your account's profile information and email address.": "更新您帐户的个人资料信息和电子邮件地址。",
    "Use at your own risk.": "使用风险自负。",
    "Why don't you become one?": "你为什么不成为其中一员呢？",
    "You are not a member.": "您还不是会员。",
    "Use": "使用",
    "You have used the item": "你已使用该物品",
    "Claimed": "已领取",
    "Day": "天",
    "Praise the sun!": "赞美太阳！",
    "You have equipped the character.": "你装备了该角色。",
    "Eimir": "埃米尔",
    "Hunger": "饥饿",
    "You cannot join World Boss that has started.": "你不能加入已经开始的世界首领战",
    "Used for Alchemy.": "用于炼金。",
    "How many do you wish to sell?": "你想出售多少个？",
    "Used to upgrade amulets.": "用于升级护身符。",
    "You have successfully listed your item": "你成功上架了物品",
    "You will receive": "您将获得",
    "You do not have enough gold to begin.": "你没有足够的黄金开始。",
    "Furbella Egg": "福贝拉蛋",
    "Acrobatic's Essence Recipe": "杂技的精华配方",
    "Aegis of the Seraph Recipe": "精细的宙斯盾配方",
    "Boulder Breaker Recipe": "巨石破碎机器配方（镐子）",
    "Bulwark Brew Recipe": "Bulwark酿造配方",
    "Dragonheart Plate Recipe": "龙心板甲配方",
    "Earthcore Infusion Recipe": "地核灌输配方",
    "Earthshaker Recipe": "撼地者配方（镐子）",
    "Impenetrable Essence Recipe": "无法穿透的精华配方",
    "Ironbite Recipe": "铁嘴配方（镐子）",
    "Ironclad Gauntlets Recipe": "铁甲护手配方",
    "Leafblade Recipe": "叶片配方（斧子）",
    "Moonshimmer Hook Recipe": "月光钩配方（鱼竿）",
    "Radiant Crest Recipe": "辐射波峰配方",
    "Riverbend Infusion Recipe": "河湾灌输配方",
    "Shadow Helm Recipe": "影子头盔配方",
    "Shadowbane Recipe": "阴影栏配方",
    "Shadowstep Greaves Recipe": "暗影之步护腿配方",
    "Shadowstrike Recipe": "暗影突袭配方",
    "Soulrender Recipe": "裂魂巨剑配方",
    "Stormcaster Recipe": "暴风雨配方",
    "Stormguard Plate Recipe": "风暴卫士板甲配方",
    "Stormguard Shield Recipe": "风暴卫士盾牌配方",
    "Stormstrider Greaves Recipe": "风暴漫游者护腿配方",
    "Strike Essence Recipe": "罢工精华配方",
    "Swiftwind Boots Recipe": "强风之靴配方",
    "Tampering Essence Recipe": "篡改精华配方",
    "Venomfang Recipe": "毒液配方",
    "Whisperwind Recipe": "耳语配方",
    "Windrider Essence Recipe": "风骑士精华配方",
    "Yggdrasil Nectar Recipe": "世界之树花蜜配方",
    "Collect": "收集",
    "Redeemed": "已领取",
    "You have claimed the reward.": "您已领取奖励。",
    "Create": "创建",
    "Purchase this slot for": "购买此槽位需花费",
    "This slot is empty.": "此槽位是空的",
    "Unlock this slot when at least one character reaches combat": "解锁此槽位需至少有一个角色达到战斗",
    "Name": "名称",
    "Complete": "完成",
    "Register your account": "注册你的账号",
    "Select a starting skin": "选择一个初始皮肤",
    "This is what the character will be known as. It must be unique and alphanumeric only.": "这就是角色的名称。它必须是唯一的，并且只能是字母数字组成。",
    "This name is not available. Please try another.": "此名称不可用。请试试其它的。",
    "Too many requests. Please try again later.": "请求过多。请稍后再试。",
    "The ranger, a master of archery, is an agile and precise class that commands the bow with unrivaled expertise. Their exceptional skill with ranged weapons, particularly bows, sets them apart on the battlefield. Whether hidden among the foliage or perched on high vantage points, rangers rain down arrows with deadly accuracy, striking fear into the hearts of their enemies.": "游侠是一位射箭大师，是一个敏捷而精确的级别，以无与伦比的专业知识指挥弓。他们高超的远程武器技能，尤其是弓，使他们在战场上脱颖而出。无论是隐藏在树叶中，还是栖息在高处，护林员都会准确无误地射出箭，让敌人感到恐惧。",
    "Burdened by a dark and ominous fate, the forsaken are destined to walk a path shrouded in despair. Plagued by misfortune and forsaken by fate, they must rely on sheer determination and cunning to navigate a world that offers them no advantages, embodying the essence of a true underdog.": "被遗弃者背负着黑暗和不祥的命运，注定要走上一条笼罩在绝望中的道路。他们被不幸所困扰，被命运所抛弃，必须依靠纯粹的决心和狡猾来驾驭一个没有任何优势的世界，体现真正失败者的本质。",
    "The shadowblade is a cunning and agile class that excels in stealth, precision, and quickness. Masters of subterfuge and deception, shadowblades rely on their exceptional speed and dexterity to outmaneuver their foes and strike from the shadows.": "影刃是一个狡猾而敏捷的职业，擅长隐身、精确和快速。作为诡计和欺骗的大师，影刃依靠其非凡的速度和灵活性来击败敌人并从阴影中进行攻击。",
    "Backstab": "背刺",
    "battle": "战斗",
    "bow": "弓",
    "dagger": "匕首",
    "dungeon": "地牢",
    "Eagles Eye": "鹰眼",
    "efficiency": "效率",
    "experience": "经验",
    "felling axe": "伐木斧",
    "fishing rod": "钓竿",
    "hunt": "狩猎",
    "Mighty Strike": "强力一击",
    "Nature's Aid": "自然的援助",
    "Piercing Shot": "穿刺射击",
    "Rampage": "横冲直撞",
    "ring": "戒指",
    "Shadow Piercer": "暗影刺穿者",
    "Shadow's Veil": "暗影面纱",
    "Shield Wall": "盾墙",
    "skill": "技能",
    "special": "特殊",
    "The warrior is a formidable class that embodies sheer strength, resilience, and raw power on the battlefield. Focused on mastering the art of close-quarters combat, warriors prioritize physical might above all else.": "战士是一个令人敬畏的职业，在战场上体现出纯粹的力量、韧性和原始力量。 战士们专注于掌握近战格斗的艺术，将身体力量置于一切之上。",
    "This class has no talents.": "这个职业没有人才。",
    "Leave": "离开",
    "Waiting in the lobby...": "在大厅等候中...",
    "\" (case sensitive)": "\“ （区分大小写）",
    "Enter your pets name": "输入您的宠物名字",
    "Happiness": "快乐",
    "Hungry": "饥饿",
    "Pet": "宠物",
    "Please enter \"": "请输入 \”",
    "Release Pet": "放生宠物",
    "Rename": "改名",
    "The pet's stats have been reduced. Feed your pet with food to appease its hunger.": "宠物的属性已降低。 给你的宠物喂食以充饥。",
    "The pet's stats have been reduced. Tap on your pet to increase its happiness.": "宠物的属性已降低。 点击你的宠物可以增加它的幸福感。",
    "Unhappy": "不开心",
    "You have successfully equipped the pet.": "您已成功装备该宠物。",
    "You have fed your pet": "你投喂了你的宠物",
    "The effectiveness of this attribute has been greatly reduced.": "这个属性的效果已经大大降低。",
    "Press on your pet to pat it": "按一下你的宠物拍拍它",
    "Press to pat": "点击宠物抚摸它",
    "Your pet becomes happier": "你的宠物变得更快乐了",
    "This feature requires a membership subscription.": "此功能需要开通会员资格。",
    "You do not have enough gold to buy this many.": "你没有足够的黄金买这么多。",
    "Whiskers": "络腮胡",
    "Whiskers Egg": "络腮胡蛋",
    "Shadowscale Egg": "暗影之鳞蛋",
    "Leafy": "叶菜",
    "Leafy Egg": "叶菜蛋",
    "Umbral Claw": "深黯之影爪",
    "The purchase is successful": "你已成功购买",
    "Multiple accounts will lead to a permanent suspension.": "多个帐户将导致永久封停。",
    "This is my only account*": "这是我唯一的账户*",
    "Press here to start!": "点这里注册",
    "Forgot password?": "忘记密码？",
    "Email Address": "邮箱地址",
    "Don't have an account?": "还没有账号？",
    "Legendary": "传说",
    "legendary": "传说",
    "Gathered via Cooking": "通过烹饪收集",
    "A collection of jagged and twisted metal scraps salvaged from the weapons and armor used by the Goblin. They bear the marks of battle and are tinged with a greenish patina.": "从哥布林使用的武器和盔甲中打捞出来的锯齿状和扭曲的金属碎片的集合。它们带有战斗的痕迹，略带绿色的光泽。",
    "It looks like no orders have been placed.": "看起来当前没有收购订单。",
    "No Orders": "无订单",
    "View more orders": "查看更多订单",
    "epic": "史诗",
    "A cursed talisman adorned with sinister symbols and infused with malevolent energies. It radiates a palpable sense of danger and corruption.": "一个被诅咒的护身符，上面装饰着邪恶的符号，注入了恶毒的能量。它散发出明显的危险感和腐败感。",
    "A set of dark and tattered robes worn by the defeated cultist. They are imbued with a sinister aura and bear arcane symbols embroidered with black thread.": "被击败的邪教分子穿的一套又黑又破的长袍。它们充满了邪恶的光环，并带有用黑线绣成的神秘符号。",
    "Attack Power Potion": "攻击力药水",
    "Ivory": "象牙",
    "Merfolk Essence Crystal": "人鱼精华水晶",
    "Nutwhisker Egg": "胡须蛋",
    "Oceanic Essence": "海洋精华",
    "Precision Potion": "精准药水",
    "Protection Potion": "防护药水",
    "Seasong's Lure": "季节的诱惑（鱼竿）",
    "Siren's Scales": "塞壬之鳞",
    "Titan Power Brew": "泰坦之力酿造",
    "No Items": "无物品",
    "Ongoing": "进行中",
    "This World Boss has already started.": "这个世界首领已经开打了。",
    "Remove Listing": "移除清单",
    "The item has been removed from the market": "该商品已从市场上移除",
    "Oreseeker Essence Crystal": "探矿者精华水晶",
    "Oreseeker": "探矿者",
    "Boulder Breaker": "巨石破碎机（镐子）",
    "Moonshimmer Hook": "月光钩（鱼竿）",
    "You have purchased the maximum amount of inventory slots available.": "您已购买了最大数量的可用仓库槽位。",
    "Leafblade": "叶片（斧子）",
    "Used to forge a standard felling axe.": "用来锻造标准的砍伐斧头。",
    "Used to forge a standard fishing rod.": "用来锻造标准的鱼竿。",
    "Available Uses": "可用",
    "You can increase this by consuming more recipes.": "你可以通过消耗更多的配方来增加它。",
    "Elk Antler": "鹿角",
    "This listings no longer exists.": "此订单已不存在。",
    "Siren's Soulstone": "塞壬的灵魂石",
    "Blooplord Egg": "海洋领主蛋",
    "Earthshaker": "撼地者（镐子）",
    "You cannot perform this action until your inventory is under the limit.": "你的仓库满了，您无法执行此操作。",
    "IMPORTANT:": "重要：",
    "Use to receive a upgrade stone.": "使用后可获得升级石。",
    "Used to upgrade helmets.": "用于升级头盔。",
    "Your Listing": "你的订单",
    "Deathgate": "死亡之门",
    "Deathgate Recipe": "死亡之门配方",
    "Fire Agate": "火玛瑙",
    "items": "物品",
    "We couldn't find any results with that term. Please try again.": "我们找不到与您输入内容相关的任何结果。请再试一次。",
    "This no longer exists.": "它已不存在了。",
    "Mythic": "神话",
    "This pack gives you 30 days membership upon use.": "此物品一经使用，即可获得30天会员资格。",
    "You have reached the limit of available listings. Remove or sell some first.": "您已达到可上架订单数量上限。需先移除或卖掉一些。",
    "You have sent a friend request.": "您已发送好友请求。",
    "Used to upgrade shields.": "用来升级护盾。",
    "Bloodmoon Recipe": "血月配方",
    "Branchbane Hatchet Recipe": "布兰克班斧头配方",
    "Celestial Ascenders Recipe": "天体上升者配方",
    "Celestial Edge Recipe": "天缘配方",
    "Celestial Radiance Recipe": "天光配方",
    "Emberfist Recipe": "余烬拳配方",
    "Emberfoot Boots Recipe": "烬足靴配方",
    "Emberfoot Greaves Recipe": "烬足护腿配方",
    "Frenzy Potion Recipe": "疯狂药水配方",
    "Frostbite Guard Recipe": "冻伤防护配方",
    "Ironbark Cuirass Recipe": "铁皮胸甲配方",
    "Moonshot Recipe": "登月配方",
    "Ocean's Whisper": "海洋的低语（鱼竿）",
    "Ocean's Whisper Recipe": "海洋的低语配方（鱼竿）",
    "Quickstrike Recipe": "快速攻击配方",
    "Runeblade Recipe": "符文剑配方",
    "Sentinel's Bulwark Recipe": "哨兵的壁垒配方",
    "Stone Splinter Recipe": "碎石配方",
    "Stormsong Recipe": "斯托颂配方",
    "Thunder Helm Recipe": "雷霆头盔配方",
    "Thunderclash Greaves Recipe": "雷霆冲突护腿配方",
    "Twinstrike Elixir Recipe": "双击药剂配方",
    "Your level is not high enough to join.": "您的等级太低了，无法加入。",
    "Ironbite": "铁嘴（镐子）",
    "Bloodletter Recipe": "放血药配方",
    "Celestial Crown Recipe": "天冠配方",
    "Celestial Striders Recipe": "天行者配方",
    "Celestial Touch Gloves Recipe": "天体之触手套配方",
    "Doomblade Recipe": "末日之刃配方",
    "Dragonfire Grasp Recipe": "龙火掌握配方",
    "Emberfire Helm Recipe": "烬火头盔配方",
    "Flamebreaker Buckler Recipe": "灭焰圆盾配方",
    "Frostbite Gauntlets Recipe": "冻伤护手配方",
    "Frostbite Legguards Recipe": "冻伤护腿配方",
    "Frostbite Plate Recipe": "冻伤板配方",
    "Frostbite Recipe": "冻伤配方",
    "Frostbite Shot Recipe": "冻伤注射配方",
    "Frostbite Walkers Recipe": "冻伤行者配方",
    "Frostguard Visage Recipe": "霜卫面容配方",
    "Grove Cleaver": "格罗夫切肉刀（斧子）",
    "Grove Cleaver Recipe": "格罗夫切肉刀配方（斧子）",
    "Guardian's Stride Recipe": "守护者的步伐配方",
    "Hydra's Coil": "九头蛇的线圈（鱼竿）",
    "Hydra's Coil Recipe": "九头蛇的线圈配方（鱼竿）",
    "Lightning Sprint Recipe": "闪电冲刺配方",
    "Moonshadow Recipe": "月影配方",
    "Sentinel's Embrace Recipe": "哨兵之拥配方",
    "Sentinel's Gaze Recipe": "哨兵的凝视配方",
    "Sentinel's Resolve Recipe": "哨兵的决心配方",
    "Serpent's Arrow Recipe": "蛇箭配方",
    "Serpent's Kiss Recipe": "蛇之吻配方",
    "Serpentstrike Recipe": "蛇击配方",
    "Shadow Shot Recipe": "暗影射击配方",
    "Shadowbound Ward Recipe": "暗影守卫配方",
    "Shadowcloak Vestments Recipe": "暗影斗篷法衣配方",
    "Shadowstep Footwear Recipe": "暗影步鞋子配方",
    "Shadowstrike Grips Recipe": "暗影之击之握配方",
    "Shieldbearer's Infusion Recipe": "持盾者的输液配方",
    "Soulward Barrier Recipe": "灵魂屏障配方",
    "Stoneheart Solution Recipe": "石心溶液配方",
    "Stormbringer Recipe": "风暴使者配方",
    "Titan's Embrace Recipe": "泰坦之拥配方",
    "Unyielding Fortitude Recipe": "不屈的毅力配方",
    "Viper Recipe": "毒蛇配方",
    "Whisperblade Recipe": "低语之刃配方",
    "Deposit to Bank": "存入银行",
    "Deposit To Bank": "存入银行",
    "How many of this item do you want to deposit?": "你想存入多少物品？",
    "An extract of slime from a Slime Ball. It hardens immediately upon extraction.": "黏液球中的黏液提取物。提取后立即变硬。",
    "Withdraw": "取出",
    "Withdraw from Bank": "从银行中取出",
    "How many of this item do you want to withdraw?": "这个你想取出多少个此物品？",
    "A piece of parchment from a treasure map, bearing …hints at hidden riches and forgotten pirate loot.": "一张藏宝图上的羊皮纸，上面写着…暗示着隐藏的财富和被遗忘的海盗战利品。",
    "You can only chain up to 4 enemies.": "你最多只能把4个敌人加入队列。",
    "You are too weak to battle this enemy. Come back when you are stronger.": "你太弱了，无法与这个敌人作战。当你更强壮的时候再来。",
    "You do not have enough available slots to do this.": "您没有足够的可用插槽来执行此操作。",
    "Abyssal Scroll": "深渊卷轴",
    "This was once wrapped around the neck of a woman who walked this earth over a century ago. Bound eternally to the realm of the undead, her spirit lingers as a relentless zombie. This chilling accessory tells a tale of sorrow and survival, radiating an otherworldly aura that sends shivers down the spine": "它曾经缠绕在一个多世纪前行走在地球上的女人的脖子上。 她的灵魂永远被束缚在不死之境，像无情的僵尸一样徘徊。 这个令人毛骨悚然的配饰讲述了一个关于悲伤和生存的故事，散发出一种超凡脱俗的光环，让人脊背发凉。",
    "Obtained via Essence Crystal": "通过精华水晶获得",
    "Used to forge a premium fishing rod.": "用于锻造高级钓鱼竿。",
    "Used to forge a premium pickaxe.": "用于锻造高级镐子。",
    "You cannot use this slot as it has been taken up by another slot.": "您无法使用此插槽，因为它已被另一个插槽占用。",
    "Earthcore Essence Crystal": "地核精华水晶",
    "Fortified Protection": "强化防护",
    "Ironclad Tonic": "铁甲补品",
    "Molten Core Essence Crystal": "熔核精华水晶",
    "Moose Antler": "驼鹿角",
    "Spicefinder Essence Crystal": "香料发现者精华水晶",
    "Stoneheart Core": "石心核心",
    "Vial of Wraith Ectoplasm": "一瓶怨灵灵质",
    "Windrider Essence": "驭风精华",
    "Yggdrasil Essence Crystal": "世界树精华水晶",
    "What will this egg reveal?": "这颗蛋会孵出什么呢？",
    "Max Health": "最大生命值",
    "Max Hunger": "最大饥饿值",
    "Max Happiness": "最大快乐值",
    "What's inside": "里面有什么？",
    "You do not have enough health to start a hunt.": "您没有足够的生命值来开始狩猎。",
    "A vial containing a swirling, shadowy substance extracted from the defeated cultist. It radiates an aura of darkness and whispers faintly when held.": "一个小瓶，里面装着一种旋转的、阴暗的物质，具有黑暗的光环，握在手中时会发出微弱的低语声。",
    "You cannot equip an item while you are currently in a battle.": "当你当前处于战斗中时，你不能装备物品。",
    "This character is already active.": "此角色已处于活动状态。",
    "Please submit a valid quantity": "请提交一个有效数量",
    "You do not have enough material to upgrade this item.": "您没有足够的材料来升级此物品。",
    "Used to forge a refined fishing rod.": "用于锻造精制鱼竿。",
    "Something went wrong. Please try again in a few moments.": "出了点问题。请稍后再试。",
    "No Crystal Selected": "未选择水晶",
    "Remove": "移除",
    "Stardust Egg": "星尘蛋",
    "Fangor": "班戈",
    "Fangor Egg": "班戈蛋",
    "Draconis Egg": "恐龙蛋",
    "Stardust": "星尘",
    "Updating listings...": "正在更新列表...",
    "Draconis": "恐龙",
    "A razor-sharp claw harvested from the defeated Shadow Beast. Its surface is as dark as night and seems to draw in surrounding light.": "从被击败的暗影兽身上夺取的锋利利爪。 它的表面漆黑如夜，似乎吸收了周围的光线。",
    "You are trying to buy more than there is.": "你购买的数量超过挂单数量了。",
    "At Yule Fest, a joyful celebration embraces winter's heart. Amidst frosty realms, folks gather to sculpt snowmen and revel in spirited snowball fights. It's a season of warmth in cold, where sharing moments with family kindles the true spirit of togetherness.": "在圣诞节上，欢乐的庆典拥抱着冬天的心。在冰天雪地里，人们聚在一起雕刻雪人，尽情地打雪仗。这是一个寒冷中充满温暖的季节，在这里，与家人分享时刻会点燃真正的团结精神。",
    "Exchange Items": "兑换物品",
    "Moonlit Winter Whisper": "月光下的冬语",
    "Per Point": "个可兑换1点数",
    "Return back to your campaign": "返回到您的活动",
    "Snowball": "雪球",
    "Snowrunner": "雪地摩托",
    "Snowball Fight Token": "雪球战斗代币",
    "Yeti": "雪人",
    "You are previewing this campaign. It will available on 13th December 2023": "您正在预览此活动。它将于2023年12月13日开放",
    "Yule Gift": "圣诞礼物",
    "Yule Token": "圣诞代币",
    "Yuletide Glades": "圣诞峡谷",
    "Elara": "木卫七",
    "Jinglebeard": "圣诞矮人",
    "Seasonal": "季节性",
    "Snowman": "雪人",
    "Yulewood Glades": "圣诞木峡谷（Yulewood Glades）",
    "Pile of Snow": "一堆雪",
    "Nestled in a winter's embrace, Yulewood Glades is a serene wonderland blanketed in snow. Tall pines, dusted with frost, stand guard over peaceful clearings where soft, twinkling lights dance, creating a magical retreat for all who seek solace and joy.": "坐落在冬天的怀抱中，圣诞木峡谷是一片被雪覆盖的宁静仙境。高高的松树上覆盖着霜，守卫着宁静的空地，那里闪烁着柔和的灯光，为所有寻求慰藉和欢乐的人创造了一个神奇的静修之地。",
    "Location": "位置",
    "Sylvus the Winter Ogre": "冬日食人魔西尔维斯",
    "Winter Scarf": "冬季围巾",
    "Winter Hat": "冬帽",
    "Drops": "掉落",
    "Frozen Carrot": "冷冻胡萝卜",
    "Buttons": "纽扣",
    "Voloris": "沃洛里斯",
    "Winter Wonderland": "冬季仙境",
    "At Yule Fest, a joyful celebration embraces winter's heart. Amidst frosty realms, folks gather to sculpt snowmen and revel in spirited snowball fights.": "在圣诞节，欢乐的庆祝活动拥抱着冬天的心。 在寒冷的国度里，人们聚集在一起堆雪人，享受激烈的打雪仗。",
    "It's a season of warmth in cold, where sharing moments with family kindles the true spirit of togetherness.": "这是一个寒冷中温暖的季节，与家人分享的时刻点燃了真正的团聚精神。",
    "skill. Earn campaign points by completing specific campaign-related skills and tasks.": "技能。 通过完成特定的与活动相关的技能和任务来赚取活动点数。",
    "Travel to": "前往",
    "to unlock the unique": "来解锁独特的",
    "Yulefest has arrived!": "圣诞节到了！",
    "Santa Skin": "圣诞老人皮肤",
    "Whisper of Daybreak": "黎明的低语",
    "Kringle Crown": "克林格尔皇冠",
    "Nobody Has This Yet": "还没有人拥有这个",
    "Sack of Gifts": "一袋礼物",
    "+10% Experience (Yule Mastery)": "+10% 经验（圣诞精通）",
    "+10% Wait Length Efficiency (Yule Mastery)": "+10% 等待时间效率（圣诞精通）",
    "Build a Snowman": "堆一个雪人",
    "Partake in a Snowball Fight": "参加打雪仗",
    "yule-mastery": "圣诞精通",
    "How many points do you want?": "你想要多少点数？",
    "This requires": "这需要",
    "Server Error": "服务器错误",
    "You cannot switch campaigns until you leave the campaign area.": "在离开活动区域之前，您不能切换活动。",
    "You do not have enough available items to do this.": "您没有足够的可用物品来执行此操作。",
    "You cannot buy from your listing.": "您无法从您的挂单中购买物品。",
    "Gelar, a valiant winter knight, mastered the art of frost combat with unwavering bravery. His stance is resolute, his expertise in icy warfare profound and chilling. Under the aurora-lit skies, he battles shadowy threats with a blade as sharp as the winter wind.": "盖拉尔是一位勇敢的冬季骑士，他以坚定不移的勇气掌握了冰霜战斗的艺术。 他的立场坚决，他在冰冷战争方面的专业知识深刻而令人不寒而栗。 在极光照亮的天空下，他用冬风般锋利的利刃对抗阴暗的威胁。",
    "Gwyneira, a noble winter warrior, wielded her glacial staff with graceful strength. Her presence is both inspiring and formidable, her mastery of frost-bound combat deep and awe-inspiring. In her relentless dedication to defend Yulewood Glades, she faces the coldest nights with a heart as fierce as the winter gales, revered by all for her dauntless courage and unyielding determination.": "格温妮拉，一位高贵的冬季战士，以优雅的力量挥舞着她的冰杖。 她的存在既鼓舞人心又令人敬畏，她对冰霜战斗的掌握深刻而令人敬畏。 她坚持不懈地保卫尤尔伍德林地，以冬风般猛烈的心面对最寒冷的夜晚，她无畏的勇气和不屈的决心受到所有人的尊敬。",
    "Gwyneira": "格温妮拉",
    "Gelar": "盖拉尔",
    "Rezthor, a name synonymous with heartlessness, lacks empathy and intellect. His insatiable greed drives him to do anything for gold, without regard for others. Even among a band of ruthless orcs, he stands out for his needless cruelty, a selfish force of malevolence.": "雷兹索尔这个名字就是无情的代名词，缺乏同理心和智慧。 他贪得无厌的贪婪驱使他为了黄金不择手段，不顾他人。 即使在一群残忍的兽人中，他也因其不必要的残忍和自私的恶意力量而引人注目。",
    "Rezthor": "雷兹索尔",
    "A colossal moon looms, casting an eerie glow on the world below. Its enormity dwarfs the landscape, evoking a sense of cosmic insignificance.": "一轮巨大的月亮若隐若现，给下面的世界投射出诡异的光芒。 它的巨大使景观相形见绌，让人产生一种宇宙渺小的感觉。",
    "A desolate expanse, where endless sands stretch to the horizon. Silence reigns, broken only by the whispering wind and the secrets of the dunes.": "一片荒凉，一望无际的沙子一直延伸到地平线。 周围一片寂静，只有低语的风声和沙丘的秘密打破这一切。",
    "A moonlit night of tranquility, where stars adorn the velvety canvas of the sky. Nature rests, cradled in the embrace of the nocturnal stillness.": "月夜宁静，星星点缀着天鹅绒般的天空。 大自然在夜间寂静的怀抱中休息。",
    "A pristine coastline, where the turquoise waves kiss golden sands. The perfect harmony of land and sea, a timeless paradise.": "原始的海岸线，碧绿的海浪亲吻着金色的沙滩。 陆地与海洋的完美和谐，永恒的天堂。",
    "A rugged valley, ensconced by towering peaks. Nature's fortress, where the mountains stand sentinel over the lush, secluded haven below.": "山谷崎岖，山峰高耸。 大自然的堡垒，山峦矗立，守护着下方郁郁葱葱、僻静的避风港。",
    "A swirling vortex of ethereal purple beckons, concealing untold realms. Its enigmatic allure invites brave souls to cross the threshold into the unknown.": "空灵的紫色漩涡在招手，隐藏着无数的领域。 它神秘的魅力邀请勇敢的灵魂跨过门槛进入未知。",
    "A tranquil lake, embraced by majestic mountains. A mirror to the heavens, reflecting the beauty of the world above.": "宁静的湖泊，雄伟的群山环抱。 天空之镜，映照出上方世界的美丽。",
    "Beyond, a realm veiled in mystery beckons. Alien landscapes and surreal wonders await, hinting at the boundless possibilities of the cosmos.": "远处，一个笼罩着神秘面纱的国度在向我们招手。 外星风景和超现实奇观等待着您，暗示着宇宙的无限可能性。",
    "Celestial Horizon": "天界（Celestial Horizon）",
    "Golden Farewell": "金色告别（Golden Farewell）",
    "Golden Silence": "金色沉默（Golden Silence）",
    "In the velvety night, the moon's pale glow casts a silvery spell. Shadows dance, and secrets awaken under its watchful eye.": "柔软的夜色中，月光散发出银色的魅力。 阴影翩翩起舞，秘密在它的注视下苏醒。",
    "Luminous Nocture": "夜光之夜（Luminous Nocture）",
    "Magma's Elegy": "岩浆挽歌（Magma's Elegy）",
    "Moonlit Brilliance": "月夜光辉（月夜光辉）",
    "Natural Disaster": "自然灾害（Natural Disaster）",
    "Nature's fury unleashed, as molten lava spews from the earth. A cataclysmic display of raw power, where the world trembles in the face of the raging inferno.": "当熔岩从大地喷涌而出时，大自然的愤怒被释放出来。 原始力量的灾难性展示，世界在熊熊的地狱面前颤抖。",
    "On the creaking deck of a pirate ship, tension simmers. An enemy vessel emerges from the mist, foreshadowing a clash on the unforgiving seas.": "在一艘吱吱作响的海盗船甲板上，紧张气氛在酝酿。 一艘敌舰从迷雾中出现，预示着无情大海上的冲突。",
    "Peaceful Night": "平安夜（Peaceful Night）",
    "Seafarer's Respite": "海员的喘息（Seafarer's Respite）",
    "Serenity": "静谧（Serenity）",
    "The forest ablaze, flames consuming the emerald kingdom. A stark reminder of nature's fierce and untameable spirit.": "森林着火了，火焰吞噬了翡翠王国。 鲜明地提醒人们大自然的凶猛和不可驯服的精神。",
    "The sun dips low, painting the horizon with fiery reds. Its reflection dances on tranquil waters, as day gracefully surrenders to night.": "夕阳西下，地平线被染上火红色。 它的倒影在平静的水面上翩翩起舞，白昼优雅地向黑夜屈服。",
    "Veiled Voyage": "隐秘的航行（Veiled Voyag）",
    "Veils of the Valley": "山谷的面纱（Veils of the Valley）",
    "Whispers of the Waves": "海浪的低语（Whispers of the Waves）",
    "Rabbit": "兔子",
    "Have you been naughty or nice? Let's see what you get this year for your gift.": "你是淘气还是友善？ 让我们看看今年你会收到什么礼物。",
    "Dragon Soulstone": "龙魂石",
    "Emberwhisp": "飞龙",
    "Emberwhisp Egg": "飞龙蛋",
    "Leovar": "狮子",
    "Leovar Egg": "狮子蛋",
    "Lumi": "幽灵",
    "Lumi Egg": "幽灵蛋",
    "Raptora": "迅猛龙",
    "Raptora Egg": "迅猛龙蛋",
    "Arboreal Ender Recipe": "树栖末影配方",
    "Ashenplate Cuirass Recipe": "灰板胸甲配方",
    "Bloodforged Helm Recipe": "血铸头盔配方",
    "Cosmic Nectar Recipe": "宇宙花蜜配方",
    "Death's Embrace Recipe": "死亡之拥配方",
    "Death's Touch Recipe": "死亡之触配方",
    "Dreadbane Armor Recipe": "恐灾盔甲配方",
    "Fury Recipe": "狂怒配方",
    "Gloves of the Protector Recipe": "保护者手套配方",
    "Grimslayer Recipe": "恐怖杀手配方",
    "Guardian's Soul Recipe": "守护者的灵魂配方",
    "Ironbark Protector Recipe": "铁皮保护者配方",
    "Nightfall Recipe": "夜幕降临配方",
    "Phoenix Greaves Recipe": "凤凰护腿配方",
    "Phoenixclaw Gauntlets Recipe": "凤爪护手配方",
    "Phoenixguard Shield Recipe": "凤凰卫士之盾配方",
    "Soul Recipe": "灵魂配方",
    "Soulshield Legplates Recipe": "灵魂护盾腿甲配方",
    "Soulshield Treads Recipe": "灵魂护盾鞋配方",
    "Verdant Pathfinders Recipe": "翠绿探路者配方",
    "Arcane Starstone": "奥术星石",
    "Cursed Blade Fragment": "诅咒之刃碎片",
    "Fire Elemental Essence": "火元素精华",
    "Orb of Elemental Conjuring": "元素召唤宝珠",
    "Undying Crest": "不朽之冠",
    "Ashenfire Ward Recipe": "灰火守卫配方",
    "Cosmic Tear Recipe": "宇宙之泪配方",
    "Eclipse Recipe": "日食配方",
    "Elixir of Life Recipe": "长生不老药方",
    "Flameguard Gauntlets Recipe": "火焰卫士手套配方",
    "Lunar Radiance Recipe": "月光配方",
    "Moonshadow Guard Recipe": "月影守卫配方",
    "Night's Whisper Recipe": "夜之低语配方",
    "Nightshade Recipe": "茄属植物配方",
    "Phoenix Soulplate Recipe": "凤凰灵魂板甲配方",
    "Serpent Scale Recipe": "蛇鳞配方",
    "Stormbreaker Boots Recipe": "风暴破坏者靴子配方",
    "Stormbreaker Gauntlets Recipe": "风暴破坏者护手配方",
    "Thundershot Recipe": "雷射配方",
    "Thunderstrike Recipe": "雷击配方",
    "Voidwalker Cowl Recipe": "虚空行者兜帽配方",
    "Voidwalker Striders Recipe": "虚空行者踏步者配方",
    "Vulpina": "狐狸",
    "Vulpina Egg": "狐狸蛋",
    "Wrex": "雷克斯",
    "Wrex Egg": "雷克斯蛋",
    "Broken Dwarven Plate": "破碎的矮人板甲",
    "Dwarven Whetstone": "矮人磨刀石",
    "Grimoire of Shadows": "暗影魔典",
    "Polar Bear Pelt": "北极熊皮毛",
    "Void Essence": "虚空精华",
    "Wolf Pelt": "狼皮",
    "Archdemon Recipe": "大恶魔配方",
    "Ashenfire Greaves Recipe": "灰火护腿配方",
    "Ashenwind Recipe": "灰风配方",
    "Balthazar's Head Recipe": "巴尔萨泽的头颅配方",
    "Bloodforged Harness Recipe": "血铸背心配方",
    "Bloodthirst Recipe": "嗜血配方",
    "Bloodthorn Recipe": "血刺配方",
    "Boulder's Bane Recipe": "博尔德之祸配方",
    "Cosmic Barrier Recipe": "宇宙屏障配方",
    "Drakeling": "幼龙",
    "Drakeling Egg": "幼龙蛋",
    "Emberfang Recipe": "余烬之牙配方",
    "Essence of a Kracken Recipe": "海妖的精髓配方",
    "Fatebreaker Recipe": "命运破坏者配方",
    "Flash Velocity Infusion Recipe": "闪速输液配方",
    "Grimwood Recipe": "格林伍德配方",
    "Kraken's Grasp Recipe": "海怪之握配方",
    "Lunarweave Boots Recipe": "月纹靴子配方",
    "Nightshade Grips Recipe": "茄属植物之握配方",
    "Omnipotent Might Infusion Recipe": "万能之力输液配方",
    "Phoenix Ashes Recipe": "凤凰灰烬配方",
    "Phoenix Crown Recipe": "凤冠配方",
    "Pyroflare": "火爆",
    "Pyroflare Egg": "火爆蛋",
    "Runebound Helm Recipe": "符文之缚头盔配方",
    "Sacred Grasp Recipe": "神圣之握配方",
    "Silverthorn Recipe": "银刺配方",
    "Soulguard Armor Recipe": "灵魂卫士护甲配方",
    "Soulshield of Redemption Recipe": "救赎灵魂之盾配方",
    "Soulstring Recipe": "灵魂弦配方",
    "Starglitter Recipe": "星光配方",
    "Suns Light Recipe": "太阳队轻配方",
    "Twilight Veilguards Recipe": "暮光面纱卫士配方",
    "Twilight Veilwalkers Recipe": "暮光帷幕行者配方",
    "Verdant Sentinel Recipe": "翠绿哨兵配方",
    "Vexalia": "维塞利亚",
    "Vexalia Egg": "维塞利亚蛋",
    "Warfists Recipe": "战士配方",
    "Whispersong Recipe": "低语配方",
    "Whisperstep Greaves Recipe": "耳语步护腿配方",
    "Whisperwind Boots Recipe": "风语靴子配方",
    "Widow's Kiss Recipe": "寡妇之吻配方",
    "Windrider Harness Recipe": "驭风者背带配方",
    "Zephyrix": "泽菲瑞克斯",
    "Zephyrix Egg": "泽菲瑞克斯蛋",
    "Aetherial Feather Quill": "虚灵羽毛笔",
    "Basilisk Venom Vial": "蛇怪毒液瓶",
    "Earth Elemental Essence": "土元素精华",
    "Petrifying Gaze Crystal": "石化凝视水晶",
    "Claw of the Alpha": "阿尔法之爪",
    "Moonblood Tincture": "月之血酊",
    "A razor-sharp claw harvested from the defeated Werewolf. It retains the strength and ferocity of the creature, emanating a faint aura of wild energy.": "从被击败的狼人身上夺取的锋利的爪子。 它保留了生物的力量和凶猛，散发着淡淡的狂野能量气息。",
    "A small vial containing a potent elixir derived from rare moonbloom flowers, known for their connection to the lunar energies. It shimmers with a faint, silver glow": "一个小瓶，里面装有从稀有的月光花中提取的强效灵丹妙药，这种花因与月球能量的联系而闻名。 它闪烁着微弱的银色光芒",
    "Used to upgrade gauntlets.": "用于升级护手。",
    "You have equipped the background.": "你已经装备了背景。",
    "You do not have enough inventory slots to start this skill.": "您没有足够的仓库槽位来启动此技能。",
    "Remove Friend": "删除好友",
    "The other characters friends list is full.": "其他角色的好友列表已满。",
    "« Previous": "« 上一页",
    "You have removed the friend.": "您已删除该好友。",
    "Used to upgrade boots.": "用于升级靴子。",
    "You do not have enough points to do this.": "你没有足够的点数来做这件事。",
    "The enemy has ran away. Please start another hunt.": "敌人已经逃跑了。请开始另一次狩猎。",
    "Failed to fetch": "获取失败",
    "You have lost connection to the internet.": "您已失去与互联网的连接。",
    "Bulwark Brew": "壁垒酿造",
    "Enigmatic Stone": "神秘石",
    "Golem Core Fragment": "魔像核心片段",
    "Strike Essence": "强击精华",
    "Used to upgrade chests.": "用于升级胸甲。",
    "You have started playing with snow": "你开始玩雪了",
    "yule mastery": "圣诞精通",
    "Your Yule Mastery action is complete.": "您的圣诞精通动作已完成。",
    "You do not have enough space in your inventory to do this.": "您的仓库中没有足够的空间来执行此操作。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Shelly": "雪莉",
    "Shadowscale": "暗影之鳞",
    "Furbella": "福贝拉",
    "Fluffy": "毛茸茸",
    "Aquarion": "阿奎里翁",
    "Very Rare": "非常稀有",
    "Somewhat Rare": "有点稀有",
    "Extremely Rare": "极为稀有",
    "standard": "标准",
    "warrior": "战士",
    "greaves": "护腿",
    "shield": "盾牌",
    "gauntlets": "护手",
    "boots": "靴子",
    "chestplate": "胸甲",
    "helmet": "头盔",
    "sword": "剑",
    "pickaxe": "镐子",
    "fishing_rod": "fishing_rod",
    "felling_axe": "felling_axe",
    "alchemy": "炼金",
    "skills": "技能",
    "character": "角色",
    "speed": "速度",
    "smelting": "冶炼",
    "defence": "防御",
    "mining": "采矿",
    "dexterity": "灵巧",
    "forge": "锻造",
    "cooking": "烹饪",
    "fishing": "钓鱼",
    "Bluebell Hollow": "蓝铃洞（Bluebell Hollow）",
    "Celestial Observatory": "天体观测站（Celestial Observatory）",
    "Crystal Caverns": "水晶洞（Crystal Caverns）",
    "Eldoria": "埃尔多利亚（Eldoria）",
    "Enchanted Oasis": "魔法绿洲（Enchanted Oasis）",
    "Floating Gardens of Aetheria": "埃瑟里亚漂浮花园（Floating Gardens of Aetheria）",
    "Isle of Whispers": "低语岛（Isle of Whispers）",
    "Skyreach Peak": "通天峰（Skyreach Peak）",
    "The Citadel": "城堡（The Citadel）",
    "Whispering Woods": "低语森林（Whispering Woods）",

    //原样
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",
    "Gityx": "Gityx",
    "O": "O",
    "IMMO2266": "IMMO2266",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "                            ": "                            ",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "              ",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "\n": "\n",
    "Lv.": "等级",
    "https://web.idle-mmo.com?ref=": "https://web.idle-mmo.com?ref=",
    "Iron ": "铁",
    "Copper ": "铜",
    "Tin ": "锡",
    "Uranium ": "铀",
    "Steel ": "钢",
    "Mystic ": "神秘",
    "Mercury ": "汞",
    "Chromite ": "铬",
    "Goblin ": "哥布林",
    "Lead ": "铅",
    "You arrived at ": "您已抵达",
    "You have embarked on your journey to ": "你已经踏上了旅程前往",
    "Improved Fishing Rod": "改进的钓鱼竿",
    "Improved Felling axe": "改进的伐木斧",
    "Veinseeker": "寻血者（镐子）",
    "Galeforce Speed Elixir": "烈风速度药剂",
    "Herculean Strength Elixir": "大力神力量药剂",
    "Bastion Elixir": "堡垒药剂",
    "Falcon's Grace Elixir": "猎鹰的恩典万能药剂",
    "You have started cooking": "你已经开始烹饪",
    "Combat Lv. ": "战斗等级 ",
    "Total Lv. ": "总计等级 ",
    "You have teleported to ": "你已经传送到了 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "\n",
    "/s": "/秒",
    "Banyan Log": "榕树原木",
    "Willow Log": "柳树原木",
    "Birch Log": "桦树原木",
    "Oak Log": "橡树原木",
    "Yew Log": "红豆杉原木",
    "Coal Ore": "煤矿石",
    "Salmon": "三文鱼",
    "Sardines": "沙丁鱼",
    "Obsidianus": "黑曜石",
    "Mystic Ore": "神秘矿石",
    "Mystical Log": "神秘原木",
    "Maple Log": "枫木原木",
    "Mercury Ore": "汞矿石",
    "Millstone Mines": "磨石矿",
    "Mahogany Log": "桃花心木原木",
    "Pirate": "海盗",
    "Polar Bear": "北极熊",
    "Raccoon": "狸",
    "Spruce Log": "云杉树原木",
    "Steel Ore": "钢矿石",
    "Stingray": "黄貂鱼",
    "Tin Ore": "锡矿石",
    "Trout": "鳟鱼",
    "Tuna": "金枪鱼",
    "Turtle": "海龟",
    "Uranium Ore": "铀矿石",
    "Crab": "螃蟹",
    "Cod": "鳕鱼",
    "Lobster": "龙虾",
    "Lead Ore": "铅矿石",
    "Lantern Fish": "灯笼鱼",
    "Herring": "鲱鱼",
    "Great White Shark": "大白鲨",
    "Perch": "鲈鱼",
    "Boots Upgrade Stone": "靴子升级石",
    "Chestplate Upgrade Stone": "胸甲升级石",
    "Gauntlets Upgrade Stone": "护手升级石",
    "Greaves Upgrade Stone": "护腿升级石",
    "Helmet Upgrade Stone": "头盔升级石",
    "Shield Upgrade Stone": "盾牌升级石",
    "Weapon Upgrade Stone": "武器升级石",
    "Amulet Upgrade Stone": "护身符升级石",
    "Ring Upgrade Stone": "戒指升级石",
    " x Fluffy Egg": " x 毛茸茸的蛋",
    " x Chest of Upgrade Stones": " x 升级石箱",
    " Essence Crystal Recipe": "精华水晶配方",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^(.+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+) \- ([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^(.+) ([\d\.]+):([\d\.]+):([\d\.]+) \- ([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^ ([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^([\d\.,]+) $/,
    /^\#([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)\n$/,
    /^BI([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数���的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have started fishing (.+).$/, '你已经开始垂钓 $1。'],
    [/^You have started forging (.+).$/, '你已经开始锻造 $1。'],
    [/^You have exchanged your items for (.+) points$/, '您已将物品兑换为 $2 活动点数'],
    [/^You have deposited (.+) to your bank.$/, '您已将 $1 存入银行。'],
    [/^Your inventory has exceeded its maximum capacity (.+). Please remove some items from your inventory.$/, '您的仓库已超过其最大容量 $1。请从查看中删除一些物品。'],
    [/^You have started transmuting (.+) Essence Crystal.$/, '你已开始炼金制作 $1 精华水晶。'],
    [/^You have started transmuting (.+) Potion.$/, '你已开始炼金制作 $1 药水。'],
    [/^You have started forging (.+) axe.$/, '你已开始锻造 $1 斧。'],
    [/^You have started forging (.+) Fishing Rod.$/, '你已开始锻造 $1 鱼竿。'],
    [/^You have started mining (.+) Ore.$/, '你已开始开采 $1 矿石。'],
    [/^You have started forging (.+) Bow.$/, '你已经开始锻造 $1 弓'],
    [/^You have started forging (.+) Dagger.$/, '你已经开始锻造 $1 匕首'],
    [/^You have started forging (.+) Bar.$/, '你已经开始锻造 $1 锭'],
    [/^You have started forging (.+) Boots.$/, '你已经开始锻造 $1 靴子'],
    [/^You have started forging (.+) Helmet.$/, '你已经开始锻造 $1 头盔'],
    [/^You have started forging (.+) Sword.$/, '你已经开始锻造 $1 剑'],
    [/^You have started forging (.+) Chestplate.$/, '你已经开始锻造 $1 胸甲'],
    [/^You have started forging (.+) Shield.$/, '你已经开始锻造 $1 盾'],
    [/^You have started forging (.+) Greaves.$/, '你已经开始锻造 $1 护腿'],
    [/^You have started forging (.+) Gauntlets.$/, '你已经开始锻造 $1 护手'],
    [/^You have started cutting (.+) Log.$/, '您已开始砍伐 $1 原木。'],
    [/^Patch list \#(.+)$/, '补丁列表 #$1'],
    [/^You have started smelting (.+) Bar.$/, '你开始冶炼 $1 锭。'],
    [/^(.+) has sent you a friend request.$/, '$1 向你发送了一条好友请求。'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)h$/, '$1小时'],
    [/^([\d\.]+)mo$/, '$1个月'],
    [/^([\d\.]+)w$/, '$1周'],
    [/^([\d\.]+)m from now$/, '还有 $1 分钟'],
    [/^([\d\.]+)w from now$/, '还有 $1 周'],
    [/^([\d\.]+)h from now$/, '还有 $1 小时'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% Attack Power$/, '\+$1\% 攻击力'],
    [/^\-([\d\.]+)\% Skill EXP$/, '\-$1\% 技能经验'],
    [/^\-([\d\.]+)\% Battle EXP$/, '\-$1\% 战斗经验'],
    [/^\-([\d\.]+)\% Dungeon EXP$/, '\-$1\% 地下城经验'],
    [/^\+([\d\.]+)\% Speed EXP$/, '\+$1\% 速度经验'],
    [/^\+([\d\.]+)\% Dexterity EXP$/, '\+$1\% 灵巧经验'],
    [/^\+([\d\.]+)\% Skill EXP$/, '\+$1\% 技能经验'],
    [/^\+([\d\.]+)\% Mining EXP$/, '\+$1\% 采矿经验'],
    [/^\+([\d\.]+)\% Fishing EXP$/, '\+$1\% 钓鱼经验'],
    [/^\+([\d\.]+)\% Battle EXP$/, '\+$1\% 战斗经验'],
    [/^\+([\d\.]+)\% Smelting EXP$/, '\+$1\% 冶炼经验'],
    [/^\+([\d\.]+)\% Woodcutting EXP$/, '\+$1\% 伐木经验'],
    [/^\+([\d\.]+)\% Dungeon EXP$/, '\+$1\% 地下城经验'],
    [/^\+([\d\.]+)\% Hunt EXP$/, '\+$1\% 狩猎经验'],
    [/^\+([\d\.]+)\% Cooking EXP$/, '\+$1\% 烹饪经验'],
    [/^\+([\d\.]+)\% Strength EXP$/, '\+$1\% 力量经验'],
    [/^\+([\d\.]+)\% EXP bonus$/, '\+$1\% 经验加成'],
    [/^\+([\d\.]+)\% Efficiency$/, '\+$1\% 效率'],
    [/^\+([\d\.]+)\% Cooking Efficiency$/, '\+$1\% 烹饪效率'],
    [/^\+([\d\.]+)\% Woodcutting Efficiency$/, '\+$1\% 伐木效率'],
    [/^\+([\d\.]+)\% Skill Efficiency$/, '\+$1\% 技能效率'],
    [/^\+([\d\.]+)\% Battle Efficiency$/, '\+$1\% 战斗效率'],
    [/^\+([\d\.]+)\% Smelting Efficiency$/, '\+$1\% 冶炼效率'],
    [/^\+([\d\.]+)\% Hunt Efficiency$/, '\+$1\% 狩猎效率'],
    [/^\+([\d\.]+)\% Dungeon Efficiency$/, '\+$1\% 地下城效率'],
    [/^\+([\d\.]+)\% Mining Efficiency$/, '\+$1\% 采矿效率'],
    [/^\+([\d\.]+)\% Fishing Efficiency$/, '\+$1\% 钓鱼效率'],
    [/^\+([\d\.]+)\% Wait Length Efficiency$/, '\+$1\% 等待时间效率'],
    [/^\+([\d\.]+)\% Wait Length Efficiency \(Mining\)$/, '\+$1\% 等待时间效率（采矿）'],
    [/^([\d\.,]+) week remaining$/, '剩余 $1 周'],
    [/^([\d\.,]+) minutes ago$/, '$1 分钟前'],
    [/^Obtain (.+) items from any skill$/, '通过任意技能获得 $1 物品'],
    [/^Use the Fishing skill (.+) times$/, '使用 $1 次钓鱼技能'],
    [/^Use the Mining skill (.+) times$/, '使用 $1 次采矿技能'],
    [/^Use the Yule Mastery skill (.+) times$/, '使用 $1 次圣诞精通技能'],
    [/^Use the Smelting skill (.+) times$/, '使用 $1 次冶炼技能'],
    [/^Use the Alchemy skill (.+) times$/, '使用 $1 次炼金技能'],
    [/^Use the Woodcutting skill (.+) times$/, '使用 $1 次伐木技能'],
    [/^Use the Forge skill (.+) times$/, '使用 $1 次锻造技能'],
    [/^You have sold (.+). You received$/, '你出售了 $1。你获得了'],
    [/^Hunt (.+) Shadow Beast$/, '狩猎 $1 暗影兽'],
    [/^Hunt (.+) Goblin$/, '狩猎 $1 哥布林'],
    [/^Hunt (.+) Goblin King$/, '狩猎 $1 哥布林之王'],
    [/^Hunt (.+) Elephant$/, '狩猎 $1 大象'],
    [/^Hunt (.+) Moose$/, '狩猎 $1 驼鹿'],
    [/^Hunt (.+) Djinn$/, '狩猎 $1 神灵'],
    [/^Hunt (.+) Skeleton Warrior$/, '狩猎 $1 骷髅战士'],
    [/^Hunt (.+) Rabbit$/, '狩猎 $1 兔子'],
    [/^Hunt (.+) Spectre$/, '狩猎 $1 幽灵'],
    [/^Hunt (.+) Lion$/, '狩猎 $1 狮子'],
    [/^Hunt (.+) Zombie$/, '狩猎 $1 僵尸'],
    [/^Hunt (.+) Deer$/, '狩猎 $1 鹿'],
    [/^Hunt (.+) Cultist$/, '狩猎 $1 邪教徒'],
    [/^Hunt (.+) Duck$/, '狩猎 $1 鸭子'],
    [/^Hunt (.+) Siren$/, '狩猎 $1 塞壬'],
    [/^Hunt (.+) Slimeball$/, '狩猎 $1 粘液球'],
    [/^Hunt (.+) Jinglebeard$/, '狩猎 $1 圣诞矮人'],
    [/^Hunt (.+) Gorgon$/, '狩猎 $1 蛇发女怪'],
    [/^Hunt (.+) Boar$/, '狩猎 $1 野猪'],
    [/^Hunt (.+) Sylvus the Winter Ogre$/, '狩猎 $1 冬日食人魔西尔维斯'],
    [/^Hunt (.+) Ogre$/, '狩猎 $1 食人魔'],
    [/^Hunt (.+) Buffalo$/, '狩猎 $1 水牛'],
    [/^Use the Cooking skill (.+) times$/, '使用 $1 次烹饪技能'],
    [/^Buy ([\d\.,]+) items from the market$/, '从市场购买 $1 物品'],
    [/^Complete ([\d\.,]+) weekly tasks$/, '完成 $1 周常任务'],
    [/^Complete ([\d\.,]+) daily tasks$/, '完成 $1 日常任务'],
    [/^Defeat ([\d\.,]+) enemies$/, '击败 $1 敌人'],
    [/^Upgrade ([\d\.,]+) items$/, '升级 $1 物品'],
    [/^Given ([\d\.,]+) damage$/, '造成 $1 伤害'],
    [/^Received ([\d\.,]+) damage$/, '受到 $1 伤害'],
    [/^([\d\.,]+) Mission credits$/, '$1 任务分'],
    [/^([\d\.,]+) Mission credits\?$/, '$1 任务分?'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^\+([\d\.,]+) EXP$/, '\+$1 经验值'],
    [/^\+([\d\.,]+) (.+) Essence Crystal$/, '\+$1 $2 精华水晶'],
    [/^\+([\d\.,]+) (.+) Bow$/, '\+$1 $2 弓'],
    [/^\+([\d\.,]+) (.+) Dagger$/, '\+$1 $2 匕首'],
    [/^\+([\d\.,]+) (.+) Bar$/, '\+$1 $2 锭'],
    [/^\+([\d\.,]+) (.+) Boots$/, '\+$1 $2 靴子'],
    [/^\+([\d\.,]+) (.+) Helmet$/, '\+$1 $2 头盔'],
    [/^\+([\d\.,]+) (.+) Sword$/, '\+$1 $2 剑'],
    [/^\+([\d\.,]+) (.+) Chestplate$/, '\+$1 $2 胸甲'],
    [/^\+([\d\.,]+) (.+) Shield$/, '\+$1 $2 盾'],
    [/^\+([\d\.,]+) (.+) axe$/, '\+$1 $2 伐木斧'],
    [/^\+([\d\.,]+) (.+) Fishing Rod$/, '\+$1 $2 鱼竿'],
    [/^\+([\d\.,]+) (.+) Greaves$/, '\+$1 $2 护腿'],
    [/^\+([\d\.,]+) (.+) Gauntlets$/, '\+$1 $2 护手'],
    [/^\+([\d\.,]+) Hunger $/, '\+$1 饥饿'],
    [/^\+([\d\.,]+) Cooked $/, '\+$1 煮熟的'],
    [/^\+([\d\.,]+) (.+) Ore $/, '\+$1 $2 矿石'],
    [/^\+([\d\.,]+) Snowball$/, '\+$1 雪球'],
    [/^\+([\d\.,]+) Protection$/, '\+$1 防护'],
    [/^\+([\d\.,]+) Attack Power$/, '\+$1 攻击力'],
    [/^\+([\d\.,]+) Pile of Snow$/, '\+$1 一堆雪'],
    [/^([\d\.,]+) Days Membership Pack$/, '$1 天会员包'],
    [/^([\d\.,]+)x\nTokens$/, '$1x\n代币'],
    [/^([\d\.,]+) days from now$/, '$1 天后'],
    [/^([\d\.,]+) Rewards$/, '$1 奖励'],
    [/^([\d\.,]+) Bartering EXP$/, '$1 以物易物经验值'],
    [/^([\d\.,]+) Points$/, '$1 点数'],
    [/^([\d\.,]+)m away$/, '$1 米远'],
    [/^([\d\.,]+) Use$/, '$1 次性'],
    [/^([\d\.,]+) Token$/, '$1 代币'],
    [/^([\d\.,]+) Tokens$/, '$1 代币'],
    [/^([\d\.,]+) Combat EXP$/, '$1 战斗经验'],
    [/^([\d\.,]+) Gold$/, '$1 黄金'],
    [/^([\d\.,]+) Day$/, '$1 天'],
    [/^([\d\.,]+) weeks remaining$/, '还有 $1 周'],
    [/^([\d\.,]+) minutes from now$/, '还有 $1 分钟'],
    [/^level ([\d\.,]+)$/, '等级 $1'],
    [/^([\d\.,]+) after tax.$/, '$1 在税后。'],
    [/^([\d\.,]+) x (.+) Egg$/, '$1 x $2 蛋'],
    [/^([\d\.,]+)x Yule Token$/, '$1x 圣诞代币'],
    [/^([\d\.,]+) likes$/, '$1 赞'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^([\d\.,]+) Months$/, '$1 月'],
    [/^([\d\.,]+) Hours$/, '$1 小时'],
    [/^([\d\.,]+) Days$/, '$1 天'],
    [/^([\d\.,]+) days$/, '$1 天'],
    [/^([\d\.,]+) EXP$/, '$1 经验值'],
    [/^([\d\.,]+) Playing$/, '$1 玩家在线'],
    [/^([\d\.,]+) Remaining$/, '$1 剩余'],
    [/^([\d\.,]+) tokens$/, '$1 代币'],
    [/^([\d\.,]+) tokens.$/, '$1 代币。'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Token Pack$/, '$1 代币包'],
    [/^([\d\.,]+) Players Here$/, '$1 玩家在这里'],
    [/^([\d\.,]+) hour ago$/, '$1 小时前'],
    [/^([\d\.,]+) hours ago$/, '$1 小时前'],
    [/^([\d\.,]+) minute ago$/, '$1 分钟前'],
    [/^([\d\.,]+) minutes ago$/, '$1 分钟前'],
    [/^([\d\.,]+) second ago$/, '$1 秒前'],
    [/^([\d\.,]+) seconds ago$/, '$1 秒前'],
    [/^([\d\.,]+) Playing Right Now$/, '$1 玩家在线'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                            transTaskMgr.doTask();
                        }
                    }
                }
            }
        }
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();