// ==UserScript==
// @name         Lord Of Idle 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.30
// @description  网页游戏 Lord Of Idle (https://www.lordofidle.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Lord Of Idle.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://www.lordofidle.com/lordofidle1.png
// @license      MIT
// @include      *https://www.lordofidle.com*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/lord-of-idle-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/lord-of-idle-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/12/01 15:07
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Player": "玩家",
    "Mining": "采矿",
    "Crafting": "制作",
    "Loading leaderboard...": "正在加载排行榜...",
    "Lord of Idle": "放置领主",
    "Lvl": "等级",
    "Combat": "战斗",
    "Combat Power": "战力",
    "Inventory": "库存",
    "Holy Knight": "圣骑士",
    "Global Top 50": "全球前 50",
    "Profile": "个人资料",
    "Rank": "等阶",
    "Save & Share": "保存 & 分享",
    "Skills": "技能",
    "Stats": "属性",
    "Upgrade": "升级",
    "Upload your profile in the Spar tab to join the ranks!": "在切磋标签页上传个人资料，即可加入队伍！",
    "View Friend": "查看好友",
    "No records found yet. Be the first!": "还没有找到记录。做第一个！",
    "Dungeon": "地牢",
    "Leaderboard": "排行榜",
    "Level": "等级",
    "Power": "战力",
    "Sparring": "切磋",
    "Wave": "波次",
    "Vendor": "供应商",
    "Stash": "储藏室",
    "Stash Tab": "储藏室标签页",
    "Name": "名称",
    "Items Stored": "已存储物品",
    "all": "全部",
    "Sort by Poison Res": "按 中毒抵抗 排序",
    "Sort by Physical Res": "按 物理抵抗 排序",
    "Sort by Fire Res": "按 火系抵抗 排序",
    "Sort by Cold Res": "按 冰系抵抗 排序",
    "Sort by Dark Res": "按 暗系抵抗 排序",
    "Sort by Rarity": "按 稀有度 排序",
    "Sort by Type": "按 类型 排序",
    "Sort by Value": "按 价值 排序",
    "Sort by Defense": "按 防御 排序",
    "Sort by +All Skills": "按 +全部技能 排序",
    "Sort by HP": "按 生命值 排序",
    "Sort by Crit Chance": "按 暴击几率 排序",
    "Sort by Dodge Chance": "按 闪避几率 排序",
    "Sort by Strength": "按 力量 排序",
    "Sort by Speed": "按 速度 排序",
    "Sort by Lifesteal": "按 生命偷取 排序",
    "Value (High-Low)": "价值 (从高到低)",
    "Value (Low-High)": "价值 (从低到高)",
    "Your bank is empty.": "你的储藏是空的.",
    "Deposit items from your inventory to store them here.": "将库存中的物品存放在这里。",
    "Secure storage for your treasures.": "为你的财富提供安全的存储。",
    "XP /": "经验值 /",
    "XP": "经验值",
    "Stop Mining": "停止采矿",
    "Rune": "符文",
    "Ore": "矿石",
    "ore": "矿石",
    "Mining...": "采矿中...",
    "Mithril": "秘银",
    "Locked": "未解锁",
    "Iron": "铁",
    "Copper": "铜",
    "Adamant": "艾德曼",
    "God Shard": "神之碎片",
    "God Shards": "神之碎片",
    "5% Chance for God Shard While Actively Mining": "主动挖矿时有5%的几率获得 神之碎片",
    "* You must update your profile to appear on the leaderboard (and refresh to see changes).": "*你必须更新你的个人资料才能出现在排行榜上（并刷新以查看更改）。",
    "Collect & Continue": "收集并继续",
    "Gold Gained": "获得金币数",
    "Loot Collected": "已收集战利品",
    "Update Profile": "更新个人资料",
    "Welcome Back!": "欢迎回来!",
    "XP Gained": "获得的经验",
    "You survived the entire duration!": "你挺过了整个过程！",
    "You were away for": "你离开了",
    "Updating...": "更新中...",
    "Enter a 6-digit": "请输入一个6位数字",
    "FIGHT!": "战斗!",
    "Import Save": "导入存档",
    "Load Save": "加载存档",
    "Load Gear": "加载装备",
    "Manual Backup": "手动备份",
    "My Duel Profile": "我的决斗档案",
    "Duel Code": "决斗代码",
    "Delete Character": "删除角色",
    "Defensive Stats": "防御属性",
    "Copy Save String": "复制存档字符串",
    "Challenge a Player": "挑战一个玩家",
    "Offensive Stats": "攻击属性",
    "Uploading...": "上传中...",
    "Updating...": "更新中...",
    "View Friend's Gear": "查看朋友的装备",
    "Note: To gain offline progress when importing this save later, ensure you are actively Mining or Fighting before saving.": "注意：为了在以后导入这个保存时获得离线进度，在保存之前确保你正在积极挖掘或战斗。",
    "Paste a save code here to load it.": "在这里粘贴一个保存代码来加载它。",
    "Permanently delete your character and start over.": "永久删除你的角色并重新开始。",
    "This cannot be undone!": "这是不可撤销的！",
    "to fight a ghost of another player!": "与其他玩家的鬼魂战斗！",
    "to view their equipped gear!": "查看他们穿戴的装备！",
    "Upload your build to get a 6-digit code to share!": "上传你的构建，以获得一个6位数的代码来分享！",
    "Warning: Overwrites current progress!": "警告：覆盖当前进度！",
    "* You will be removed from the leaderboard if you don't update for 14 days.": "* 如果你14天不更新，你将从排行榜上删除。",
    "Click to Copy": "点击以复制",
    "Screenshot this card to share!": "截图分享这张卡片!",
    "Wins": "胜",
    "Losses": "负",
    "Max Wave": "最大波次",
    "🔒 Requires:": "🔒 要求:",
    "Amulet of Accuracy": "精准护身符",
    "Amulet of Defense": "防御护身符",
    "Amulet of Wisdom": "智慧护身符",
    "Amulet of Fury": "狂怒护身符",
    "Cost:": "成本:",
    "Craft Item": "制作物品",
    "HP:": "生命值:",
    "HP": "生命值",
    "Small Relic": "小遗物",
    "Type:": "类型:",
    "XP:": "经验值:",
    "speed": "速度",
    "Crafting...": "制作中...",
    "Crafted:": "已制作:",
    "Stop Crafting": "停止制作",
    "Can roll random bonus stats!": "可以重掷随机加成属性！",
    "A simple but reliable metal. Good for travel.": "一种简单但可靠的金属。适合旅行。",
    "g)": "金币)",
    "Gold Bonus": "金币加成",
    "gold Bonus": "金币加成",
    "Poison Res": "中毒抵抗",
    "poison Res": "中毒抵抗",
    "Cold Res": "冰系抵抗",
    "cold Res": "冰系抵抗",
    "Dark Res": "暗系抵抗",
    "dark Res": "暗系抵抗",
    "Physical Res": "物理抵抗",
    "physical Res": "物理抵抗",
    "physicalRes": "物理抵抗",
    "Fire Res": "火系抵抗",
    "fire Res": "火系抵抗",
    "Equipped Gear": "已穿装备",
    "Equipped Relic": "已装备遗物",
    "Equip": "装备",
    "Item Bag": "物品袋",
    "items": "物品",
    "Lifesteal": "生命偷取",
    "Max HP": "最大生命值",
    "No items found.": "未发现物品。",
    "Normal": "普通",
    "Strength": "力量",
    "strength": "力量",
    "UNEQUIP": "脱下",
    "XP Bonus": "经验值加成",
    "xp Bonus": "经验值加成",
    "Sell": "出售",
    "Sell All (": "出售所有 (",
    "Crit Chance": "暴击几率",
    "Dodge Chance": "闪避几率",
    "Inventory & Equipment": "库存 & 装备",
    "defense": "防御",
    "Defense": "防御",
    "Damage Output": "伤害输出",
    "Attack Speed": "攻击速度",
    "Active Bonuses": "活跃加成",
    "Increases Defense by 50 per point.": "每点提高50防御.",
    "Increases Gold Gain.": "提高金币增益.",
    "Increases XP Gain.": "提高经验增益.",
    "Increases Physical Damage.": "提高物理伤害.",
    "Increases Critical Hit Chance.": "提高暴击率.",
    "Increases Attack Speed.": "提高攻击速度.",
    "Increases Max HP.": "提高最大生命值.",
    "Increases Hit Chance (ignore def).": "提高暴击率 (忽略防御).",
    "Wisdom": "智慧",
    "Next Level:": "下一级:",
    "Combat Arts": "战斗艺术",
    "Current Effect:": "当前效果:",
    "Bonus from Synergies:": "协同加成:",
    "Available Points:": "可用点数:",
    "Chance to attack twice.": "攻击两次的几率.",
    "Chance to Dodge attacks.": "躲避攻击的几率.",
    "Chance to find double loot.": "发现双倍战利品的几率.",
    "Chance to survive a fatal blow.": "躲过致命一击的几率.",
    "Double Strike": "双重攻击",
    "+0.25% Lifesteal per point in Might": "每点实力+0.25%生命偷取",
    "+0.5 DPS per point in Execute": "每点处决 +0.5 DPS",
    "+0.5 Regen per point in Vitality": "每点活力+0.5点回复",
    "+0.5% Crit Chance per point in Lethality": "每点致命+0.5%暴击几率",
    "+0.5% Crit Chance per point in Might": "每点实力+0.5%暴击率",
    "+0.5% Dodge per point in Immortality": "不朽每点增加0.5%闪避",
    "+0.5% Double Loot per point in Greed": "贪婪每点增加0.5%双倍战利品",
    "+0.5% Double Strike per point in Divine Wrath": "每点神怒+0.5%双重攻击",
    "+1 Flat Reduction per point in Thorns": "每点荆棘+1平减",
    "+1 Min Damage per point in Might": "每点实力+1伤害下限",
    "+1% Attack Speed per point in Frenzy": "每点狂乱+1%攻速",
    "+1% Crit Damage per point in Precision": "每点精准+1%暴击伤害",
    "+1% Execute Damage per point in Double Strike": "每点双重攻击+1%的处决伤害",
    "+1% Experience per point in Greed": "每点贪婪+1%经验值",
    "+1% Gold per point in Scavenger": "每点拾荒者+1%金币",
    "+1% Gold per point in Wisdom": "每点智慧+1%金币",
    "+1% Ignore Def per point in Lethality": "每点致命+1%忽略防御",
    "+1% Reflect per point in Stone Skin": "每点石肤+1%反射",
    "+1% Survival per point in Defiance": "每点反抗增加1%的生存",
    "+1% Survival per point in Vitality": "每点活力+1%生存",
    "+10 HP per Kill per point in Haste": "每急速点每击杀增加10点生命",
    "+2% Damage per point in Vampirism": "每点吸血鬼+2%伤害",
    "+25 Defense per point in Stone Skin": "每点石肤+25防御力",
    "+25 Defense per point in Thorns": "每点荆棘+25点防御",
    "+5% Damage per point in Critical Strike": "每点暴击增加5%伤害",
    "+50 HP per point in Immortality": "每点不朽增加50点生命",
    "+50 HP per point in Regeneration": "每点回复增加50点生命",
    "Adds to base 150% crit multiplier.": "增加基础150%暴击乘数。",
    "Critical Strike": "暴击",
    "Deal 1 DPS per skill point.": "每技能点增加1点DPS。",
    "Deal bonus damage to low HP enemies.": "对低血量敌人造成额外伤害。",
    "Defiance": "反抗",
    "Divine Wrath": "神怒",
    "Execute": "处决",
    "Frenzy": "疯狂",
    "Greed": "贪婪",
    "Haste": "急速",
    "Heal for a % of damage dealt.": "造成伤害的%转化为自身生命。",
    "Heal HP on kill.": "击杀时恢复HP。",
    "Immortality": "不朽",
    "Lethality": "致命",
    "Might": "实力",
    "Passive Mastery": "被动精通",
    "points in": "点",
    "Precision": "精度",
    "Reduces incoming damage by a flat amount.": "固定减少受到的伤害",
    "Reflect damage back to attacker.": "将伤害反射给攻击者。",
    "Regenerate HP every tick.": "每tick恢复一次HP。",
    "Regeneration": "回复",
    "Requires:": "要求:",
    "Reset Tree (": "重置树 (",
    "Scavenger": "拾荒者",
    "Skin": "肤。",
    "Stone Skin": "石肤",
    "Thorns": "荆棘",
    "unlocked": "已解锁",
    "Vampirism": "吸血鬼",
    "Vitality": "活力",
    "Health": "生命值",
    "Mine Rock": "开采石头",
    "Potions": "药水",
    "Super": "超级",
    "Ultra": "究级",
    "Mega": "终级",
    "\"The deeper you go, the darker it gets. There is no end, only the inevitable end of you.\"": "“你走得越深，它就越黑暗。没有结局，只有你的结局。”",
    "ENTER CRYPT": "进入地牢",
    "Warning: The Dungeon offers NO loot or XP rewards. You will NOT lose items on death. It is purely for Leaderboard glory!": "警告: 地牢不提供战利品或经验值奖励。死亡时不会丢失物品。这纯粹是为了排行榜的荣耀！",
    "Giant Rat": "巨鼠",
    "Retreat": "撤退",
    "Dismiss": "关闭",
    "Base:": "基础:",
    "Bonus Total:": "总加成:",
    "Breakdown": "细分",
    "Skills:": "技能:",
    "Total:": "总计:",
    "Equipment:": "装备:",
    "A simple but reliable metal. Sharp and ready for battle.": "一种简单但可靠的金属。锋利，随时准备战斗。",
    "A simple but reliable metal. Protects the head.": "一种简单但可靠的金属。保护头部。",
    "A simple but reliable metal. Offers decent protection.": "一种简单但可靠的金属。提供了不错的保护。",
    "% Stats": "% 属性",
    "Body Armor": "身体护甲",
    "Current:": "当前:",
    "Equipment Upgrades": "装备升级",
    "God Shards:": "神之碎片:",
    "No item equipped": "未装备物品",
    "Shard": "碎片",
    "Physical Resistance": "物理抵抗",
    "Equipment": "装备",
    "NEW": "新",
    "Mega Potion": "终级药水",
    "Health Potion": "生命药水",
    "Super Potion": "超级药水",
    "Ultra Potion": "究级药水",
    "Stock up on supplies for your battles.": "为你的战斗储备补给。",
    "Heals": "治疗",
    "Exclusive Items": "专属物品",
    "Buy Amount:": "购买数量:",
    "Buy": "购买",
    "A ring worn by the wealthiest merchants. Obtained only through the vendor.": "最富有的商人戴的戒指。只能通过供应商获得。",
    "A symbol of wealth and prosperity. Obtained only through the vendor.": "财富和繁荣的象征。只能通过供应商获得。",
    "Titan Fist": "泰坦之拳",
    "There are old tales of a fearsome beast that was beyond a magical red portal": "有一个古老的传说，在一个红色的魔法传送门后面有一只可怕的野兽",
    "hp": "生命值",
    "poison": "中毒",
    "physical": "物理",
    "Set": "套装",
    "Select Enemy": "选择敌人",
    "Select an enemy below to start fighting": "请在下面选择一个敌人以开始战斗",
    "Primal Instinct: Deal +30% damage to enemies below your combat level. Heal 250 HP on kill": "原始本能：对低于你战斗等级的敌人造成+30%的伤害。击杀后治疗250点生命值",
    "Possible Drops:": "可能掉落:",
    "Max Hit:": "最大攻击:",
    "Auto-Heal Potion (20s Cooldown)": "自动治疗药水 (20秒 冷却时间)",
    "Acid Slime": "酸性史莱姆",
    "Ancient Blade": "上古之刃",
    "Ancient Wooden Stick": "古老木棒",
    "Band of the Tyrant": "暴君乐队",
    "Berserker's Wrath": "狂暴之怒",
    "Bloodfang Blade": "血牙之刃",
    "Bloodletter's Edge": "血字之刃",
    "Bone Reaper": "骨之收割者",
    "Boots of Lightness": "轻便靴",
    "Breaker": "破坏者",
    "Brimstone Sabatons": "硫磺浴棍",
    "Brood Mother": "育婴之母",
    "Conquerors Amulet": "征服者护身符",
    "Conquerors Ring": "征服者戒指",
    "Cowl": "风帽",
    "Crown of Moo": "哞哞之冠",
    "Crusher Sabatons": "粉碎者萨巴顿",
    "Demonic Visage": "恶魔面容",
    "Dire Wolf": "恐狼",
    "Earthshaker": "地震器",
    "Earthshaker Greaves": "地震护膝",
    "Eye of the Infinite": "无限之眼",
    "Frostbite": "冻伤",
    "Frozen Gaze": "冻结的凝视",
    "Fur Armor": "毛皮盔甲",
    "Goblin": "哥布林",
    "Goblin Crusher": "哥布林粉碎者",
    "Greatsword": "巨剑",
    "Hellfire Scythe": "地狱火长柄大镰刀",
    "Horned Skull Mask": "角骨骷髅面具",
    "Howling Gale": "呼啸疾风",
    "Hunter's Cap": "猎人帽",
    "Hunting Knife": "猎刀",
    "Infernals Fang": "炼狱之牙",
    "Inferno Lord Plate": "地狱领主板甲",
    "Juggernaut Harness": "神像挽具",
    "Mind's Eye Circlet": "心眼之环",
    "Pendant of Domination": "支配吊坠",
    "Psychic Barrier Plate": "精神屏障板甲",
    "Rat Tail Dagger": "鼠尾匕首",
    "Requires Level": "要求等级",
    "Ribcage Plate": "胸廓板甲",
    "Ring of Greed": "贪婪之戒",
    "Ring of Striking": "打击之戒",
    "Rock Golem": "岩石魔像",
    "Roid Ring": "劳德戒指",
    "Rusty Ring": "生锈的戒指",
    "Sanguine Reaver": "血色死神",
    "Savage King's Band": "蛮王乐队",
    "Skeleton Warrior": "骷髅战士",
    "Slime Boots": "史莱姆靴子",
    "Stampede Greaves": "踩踏护膝",
    "Sticky Shiv": "粘刀",
    "Stormfury": "风暴之怒",
    "Sulfur Heart": "硫磺之心",
    "Sulfurion": "硫",
    "Titanic War Plate": "泰坦尼克战争板甲",
    "Toxin Weaver": "毒素编织者",
    "Tracker Boots": "追踪者靴子",
    "Tusked Bandit Helmet": "獠牙强盗头盔",
    "Twin Daggers of Night": "夜之双刃",
    "Venom Fang": "毒牙",
    "Vest": "背心",
    "Vitality Ring": "活力戒指",
    "Voidwalker Boots": "虚空行者靴子",
    "Wandering Eye": "游弋之眼",
    "Warlord's Cleaver": "战神之刀",
    "Widowmaker": "寡妇制造者",
    "Wrath Axe": "愤怒之斧",
    "Damage": "伤害",
    "Damage Type": "伤害类型",
    "CRIT!": "暴击!",
    "Fighting": "战斗中",
    "Gold": "金币",
    "allCombatSkills": "所有战斗技能",
    "allPassiveSkills": "所有被动技能",
    "Normal Hit": "普通攻击",
    "A crystalline blade that freezes enemies with a single glance.": "水晶之刃，一眼就能冻结敌人。",
    "A mysterious relic imbued with magical properties.": "一件充满魔力的神秘遗物。",
    "A worn ring found on an old rat.": "一只老老鼠身上发现的旧戒指。",
    "An incredibly hard alloy, difficult to forge. Good for travel.": "一种极其坚硬的合金，难以锻造。适合旅行。",
    "Armor woven from frozen moments. Impervious to time.": "用冰冻的瞬间编织成的盔甲。不受时间的影响。",
    "Assassin": "刺客",
    "Basic footwear for the road.": "基础款的上路鞋。",
    "Blood Drain: Each attack drains 25 HP as pure damage (ignores defense) and heals you": "吸血：每次攻击吸取25点纯伤害（无视防御），并治疗自身25点生命值",
    "Conceals your presence in the shadows.": "把你的存在隐藏在阴影里。",
    "Est. DPS": "魔法输出",
    "Frozen Perception: 15% chance to freeze enemies for 2s (cannot attack). +2 All Skills. +10% XP. Frozen enemies take +20% damage": "冻结感知：15%的几率冻结敌人2秒（不能攻击）。+2所有技能。+10%经验值。被冰冻的敌人受到的伤害+20%",
    "Gooey.": "粘稠的。",
    "Grants vision beyond sight and accelerates learning.": "赋予视觉之外的视野，加速学习。",
    "Ignore Def": "无视防御",
    "Mental fortitude made manifest as impenetrable armor.": "坚韧不拔的精神表现为坚不可摧的盔甲。",
    "Observer's Dominion": "观察者的领地",
    "Phantom Strike: 10% chance to deal triple damage as shadow damage": "幻影打击：有10%的几率造成3倍暗影伤害",
    "Pierce through time itself with crystalline precision.": "以水晶般的精确度穿透时间。",
    "Rings adorned with sharp beast claws.": "饰有锋利兽爪的戒指。",
    "See all paths. Know all outcomes. Master all futures.": "查看所有路径。了解所有的结果。掌握一切未来。",
    "See all timelines, master all skills.": "查看所有时间线，掌握所有技能。",
    "Silent as shadows, deadly as night.": "沉默如影，致命如夜。",
    "Squishy and sticky, but surprisingly protective.": "又软又粘，但出奇地有保护作用。",
    "Step between dimensions. Nothing can touch you.": "跨越维度。没有什么能撼动你。",
    "Swift as the wind. Dance around your enemies.": "如风般迅捷。围着你的敌人跳舞。",
    "Swift boots worn by creatures of the night.": "暗夜生物穿着的迅捷长靴。",
    "The Eye watches. The Eye knows. The Eye grants power.": "眼睛在看。眼睛知道。眼睛赋予力量。",
    "Twin venomous blades that hunger for critical strikes. Perfect for assassins.": "双生毒刃，渴望暴击。非常适合刺客。",
    "Vampire's Embrace": "吸血鬼的拥抱",
    "Walk between heartbeats. Dance through frozen time.": "走在心跳之间。在凝固的时间里跳舞。",
    "Crit (": "暴击 (",
    "New Item": "新物品",
    "lifesteal": "生命偷取",
    "Fast and sharp.": "又快又锋利。",
    "darkRes": "暗系抵抗",
    "Currently Equipped": "当前装备",
    "critChance": "暴击率",
    "A simple hood made of tanned leather.": "用鞣制皮革制成的简易兜帽。",
    "Parasitic Fur Armor": "寄生毛皮铠甲",
    "Warm armor made from hunted beasts.": "由被猎杀的野兽制成的保暖盔甲。",
    "poisonRes": "中毒抵抗",
    "fireRes": "火系抵抗",
    "dodgeChance": "闪避几率",
    "coldRes": "冰系抵抗",
    "A weathered cap worn by experienced hunters.": "老练猎人佩戴的饱经风霜的帽子。",
    "Elusive Rat Tail Dagger": "鬼魅鼠尾匕首",
    "Leeching Rat Tail Dagger": "吸血鼠尾匕首",
    "Precise Rat Tail Dagger": "精确鼠尾匕首",
    "Quick Hunter's Cap": "快速猎人帽",
    "Speed": "速度",
    "quest": "任务",
    "Res:": "抵抗:",
    "Smashing.": "粉碎。",
    "Your Defense (Flat):": "你的防御 (平):",
    "Xp Bonus": "经验加成",
    "Lightweight.": "轻量级。",
    "Hp": "生命值",
    "Dragon Slayer": "屠龙者",
    "Heavy hitter.": "沉重的打击。",
    "Deadly poison.": "致命毒药。",
    "Damage to You": "伤害对你",
    "Actual:": "实际:",
    "All Combat Skills": "所有战斗技能",
    "All Passive Skills": "所有被动技能",
    "Dominion": "统治",
    "A cursed blade that devours souls in flames.": "一把能在火焰中吞噬灵魂的诅咒之剑。",
    "A cursed blade that thirsts for blood.": "一把渴望鲜血的被诅咒的剑。",
    "A dark amulet that thirsts for blood.": "一个嗜血的黑暗护身符。",
    "A dark helm that feeds on life force.": "一个以生命力为食的黑暗头盔。",
    "A helm forged to withstand dragon fire.": "一顶能抵挡龙火的头盔。",
    "A helm worn by fearless warriors.": "无所畏惧的战士所戴的头盔。",
    "A helmet fashioned from a beast's skull.": "用野兽头骨制成的头盔。",
    "A massive cleaver that cleaves through armor and bone.": "一个巨大的切肉刀，可以切开盔甲和骨头。",
    "A ring that channels pure rage.": "一枚传递纯粹愤怒的戒指。",
    "A ring that drains the life from your foes.": "一枚能吸干敌人生命的戒指。",
    "A sharp blade for tracking beasts.": "用来追踪野兽的锋利刀片。",
    "A sturdy charm of protection.": "坚固的护身符。",
    "Absorbs life with every strike. Converts poison into power.": "每次攻击都吸取生命。将毒素转化为力量。",
    "An ancient wooden stick. Perhaps it holds significance...": "一根古老的木棍。也许有什么意义……",
    "An axe fueled by pure rage.": "一把由愤怒点燃的斧头。",
    "An incredibly hard alloy, difficult to forge. Offers decent protection.": "一种极其坚硬的合金，难以锻造。提供了不错的保护。",
    "An incredibly hard alloy, difficult to forge. Protects the head.": "一种极其坚硬的合金，难以锻造。保护头部。",
    "An incredibly hard alloy, difficult to forge. Sharp and ready for battle.": "一种极其坚硬的合金，难以锻造。敏锐，随时准备战斗。",
    "Armor forged from the essence of vampires.": "用吸血鬼的精华制成的盔甲。",
    "Armor forged in the deepest hells. Radiates power.": "在地狱深处锻造的盔甲。辐射能力。",
    "Berserker's Rage": "狂战士之怒",
    "Blood Rage: Gain +10% damage and +3% crit per 10% HP missing": "血怒：每损失10%生命值增加10%伤害和3%暴击",
    "Boots lined with wolf fur for speed.": "为了加快速度，靴子里衬着狼毛。",
    "Boots made from dragon hide.": "龙皮做的靴子。",
    "Conqueror's Dominion": "征服者的统治",
    "Crown of the demon lords. Grants destructive power.": "恶魔领主的王冠。授予破坏力。",
    "Dominate all who stand before you.": "主宰所有站在你面前的人。",
    "Dragonbane: Deal +20% damage to dragon-type enemies": "龙祸：对龙类敌人造成+20%的伤害",
    "Dragonbone scythe that feeds on flame and blood. Sustain through any battle.": "以火焰和鲜血为食的龙骨镰刀。撑过任何一场战斗。",
    "Every step crushes the ground beneath you.": "每一步都踩碎脚下的土地。",
    "Every strike draws blood. Every kill fuels your power.": "每一次打击都会流血。每次杀戮都能增强你的力量。",
    "Favored by thieves and highwaymen.": "受到小偷和强盗的青睐。",
    "Forged for giants. Impenetrable fortress.": "为巨人打造。令人费解的堡垒。",
    "Forged in the heart of a volcano. Radiates intense heat.": "在火山中心锻造而成。散发出强烈的热量。",
    "Forged with ancient runic magic.": "用古老的符文魔法铸造。",
    "Forged with ancient runic magic. Good for travel.": "用古老的符文魔法铸造。适合旅行。",
    "Forged with ancient runic magic. Offers decent protection.": "用古老的符文魔法铸造。提供了不错的保护。",
    "Forged with ancient runic magic. Protects the head.": "用古老的符文魔法铸造。保护头部。",
    "Forged with ancient runic magic. Sharp and ready for battle.": "用古老的符文魔法铸造。敏锐，随时准备战斗。",
    "Frozen blade that strikes with winter's fury. Embrace the cold.": "冰封之刃，冬日之怒。拥抱寒冷。",
    "Gauntlets of the ancients. Trade speed for overwhelming durability.": "古人的护手。用速度换取压倒性的耐用性。",
    "Gauntlets that channel your fury.": "引导你愤怒的护手。",
    "Gauntlets worn by legendary dragon hunters.": "传说中的猎龙人戴的护腕。",
    "Guides your strikes to weak points.": "引导你的打击弱点。",
    "Harvests souls in flames. Burns eternally.": "在火焰中收获灵魂。永远燃烧。",
    "Harvests the essence of the undead. Death fuels your strength.": "收集不死族的精华。死亡给你力量。",
    "Heavy armor that grows stronger as you bleed.": "随着你的流血，厚重的盔甲会变得更加坚固。",
    "Heavy boots that anchor you to the ground.": "沉重的靴子把你固定在地面上。",
    "Helps you focus on your target.": "帮助你专注于你的目标。",
    "Impenetrable armor crafted from dragon scales.": "由龙鳞制成的坚不可摧的盔甲。",
    "Inferno Immolation: 20% chance to ignite enemies for 5s (5% max HP/sec). +2 All Skills. +15% damage to burning enemies.": "地狱献祭：20%的几率点燃敌人，持续5秒（最大5% /秒）。+2所有技能。对燃烧的敌人造成15%的伤害。",
    "Infinite power. Infinite conquest. The ultimate prize.": "无限的权力。无限的征服。终极大奖。",
    "Leave no trace as you move.": "移动时不留痕迹。",
    "Leave trails of fire with every step.": "每一步都留下火的痕迹。",
    "Legendary blade forged to slay dragons.": "传说中的屠龙之剑。",
    "Lightning-fast blade that becomes a blur in combat. Strike before they can react.": "闪电般快速的剑刃在战斗中变得模糊。在他们反应过来之前发动攻击。",
    "Lightweight yet stronger than steel. Good for travel.": "重量轻，但比钢更坚固。适合旅行。",
    "Lightweight yet stronger than steel. Offers decent protection.": "重量轻，但比钢更坚固。提供了不错的保护。",
    "Lightweight yet stronger than steel. Protects the head.": "重量轻，但比钢更坚固。保护头部。",
    "Lightweight yet stronger than steel. Sharp and ready for battle.": "重量轻，但比钢更坚固。敏锐，随时准备战斗。",
    "Macabre protection.": "可怕的保护。",
    "Massive hammer that grants unbreakable defense. For those who never dodge.": "巨大的锤子，给予坚不可摧的防御。为那些从不躲闪的人。",
    "Massive mace that crushes bones and grants protection. Unstoppable force.": "巨大的狼牙棒可以粉碎骨头并提供保护。不可阻挡的力量。",
    "Moo Moo Moo Moo Moo Moo.": "哞，哞，哞。",
    "Never extinguished, forever burning.": "永不熄灭，永远燃烧。",
    "Pockets everywhere.": "口袋里无处不在。",
    "Pulsates with a gentle life force.": "以柔和的生命力搏动。",
    "Pure unrelenting fury. Crush all opposition.": "纯粹无情的愤怒。粉碎一切反对。",
    "Radiates an intense, angry heat.": "散发出强烈的、愤怒的热量。",
    "Rule with an iron fist. Crush all opposition.": "铁腕统治。粉碎一切反对。",
    "Silent boots for tracking prey.": "追踪猎物的无声靴子。",
    "Stand your ground and fight to the death.": "坚守阵地，决一死战。",
    "Strike fear into all who face you. Channel hellfire.": "让所有面对你的人都感到恐惧。通道地狱之火。",
    "Strike fear into all who see you. Channel primal rage.": "让所有看到你的人都害怕。引导原始愤怒。",
    "Strike from the darkness.": "从黑暗中出击。",
    "Sturdy and dependable. Good for travel.": "坚固可靠。适合旅行。",
    "Sturdy and dependable. Offers decent protection.": "坚固可靠。提供了不错的保护。",
    "Sturdy and dependable. Protects the head.": "坚固可靠。保护头部。",
    "Sturdy and dependable. Sharp and ready for battle.": "坚固可靠。敏锐，随时准备战斗。",
    "The earth trembles with every step you take.": "你每走一步，大地都会震动。",
    "The essence of Sulfurion crystallized. Unleash devastation.": "硫的精华结晶了。释放破坏。",
    "The heart of a titan.Unstoppable endurance.": "泰坦的心脏。不可阻挡的耐力。",
    "The mark of the Bull King. Power flows through you.": "牛王的印记。力量在你身上流动。",
    "Titan's Wrath: Every 5s in combat gain +15% damage & +5% crit (max 10 stacks). Below 30% HP: +40% damage, +30% damage reduction, +20% lifesteal. +2 All Skills. 100% thorns": "泰坦之怒：战斗中每5秒增加15%伤害和5%暴击（最多10层）。生命值低于30%:+40%伤害，+30%减伤，+20%吸血。+2所有技能，100%荆棘",
    "Unstoppable momentum. Nothing breaks this armor.": "不可阻挡的势头。没有什么能打破这层盔甲。",
    "Unstoppable momentum. Trample everything.": "不可阻挡的势头。践踏一切。",
    "Vital Rat Tail Dagger": "重要鼠尾匕首",
    "Walk through infernos. Leave scorched earth.": "穿过地狱。留下焦土。",
    "Whispers ancient secrets to the wearer.": "向佩戴者低语古老的秘密。",
    "Woven from pure darkness.": "由纯粹的黑暗编织而成。",
    "You feel a strange urge to hoard wealth.": "你有一种囤积财富的奇怪冲动。",
    "You feel lighter just holding them.": "抱着它们你会觉得更轻松。",
    "xpBonus": "经验加成",
    "goldBonus": "金币加成",
    "Deadly Fur Armor": "致命的毛皮盔甲",
    "Golden Hunter's Cap": "黄金猎人帽",
    "Fierce Rat Tail Dagger": "猛鼠尾匕首",
    "Agile Rusty Ring": "敏捷生锈戒指",
    "Rich Rat Tail Dagger": "富贵鼠尾匕首",
    "or": "或",
    "Mine": "开采",
    "and": "和",
    "Active Combat": "活跃战斗",
    "Enter the": "进入",
    "Game Loop": "游戏循环",
    "Ores": "矿石",
    "4. Compete": "4. 完成",
    "3. Fight & Grow": "3. 战斗 & 成长",
    "1. Gather & Craft": "1. 采集 & 制作",
    "2. Trade & Prepare": "2. 交易 & 准备",
    "Tip: Stay in": "提示: 待在",
    "to enable Auto-Heal.": "以启用自动治疗。",
    "Combat Power Score": "战力评分",
    "": "",
    ". Upgrade your gear and buy": ". 升级你的装备和购买",
    ". Craft items and chase": "。制作物品和追逐",
    ". Duel other players and climb the global Leaderboard.": "。与其他玩家对决并攀登全球排行榜。",
    "Battle monsters to Level Up and find better loot. Increase your": "与怪物战斗可以提升等级，获得更好的战利品。增加你的",
    "before leaving to gain rewards offline (capped at 24h)!": "在离开之前获得离线奖励（上限24小时）！",
    "or brave the": "或者勇敢面对",
    "Rare Procs": "稀有道具",
    "Sell crafted gear directly from your Inventory for": "在背包中直接出售制作完成的装备获得",
    "Sparring Arena": "切磋场",
    "💀 You Died!": "💀 你挂了!",
    "to": "到",
    "Lost": "失去",
    "Crit Damage": "暴击伤害",
    "Execute Bonus": "处决加成",
    "Poison Resistance": "中毒抵抗",
    "MAX LEVEL": "满级",
    "from gear)": "通过装备)",
    "Quick": "快速的",
    "Living": "生命",
    "Agile": "敏捷",
    "Ancient": "古代",
    "Fierce": "凶猛",
    "Gilded": "镀金",
    "Golden": "金色",
    "Parasitic": "寄生",
    "Sharp": "锋利的",
    "Swift": "迅捷",
    "Vital": "活力",
    "Savage": "野蛮人",
    "Ghostly": "幽灵",
    "Hearty": "结实",
    "Leeching": "吸血",
    "Rich": "富有",
    "Vampiric": "吸血鬼",
    "Learned": "博学的",
    "Deadly": "致命",
    "Sturdy": "坚固",
    "Wise": "智慧",
    "Sage's": "圣人的",
    "Parasitic Goblin Crusher": "寄生哥布林粉碎者",
    "Sage's Amulet of Accuracy": "圣人的精准护身符",
    "Guardian": "守护者",
    "crit Chance": "暴击率",
    "Stone Skin:": "石肤:",
    "Withdraw": "取出",
    "Learned Tracker Boots": "博学的追踪者战靴",
    "all Passive Skills": "所有被动技能",
    "Dark Resistance": "暗系抵抗",
    "Elusive": "鬼魅",
    "Junk": "垃圾的",
    "Evasive": "闪避",
    "Gilded Ring of Striking": "镀金的打击戒指",
    "skill_double_strike": "双重打击技能",
    "skill_greed": "贪婪技能",
    "skill_wisdom": "智慧技能",
    "Sharp Ribcage Plate": "锋利的胸廓板甲",
    "skill_frenzy": "疯狂技能",
    "skill_might": "实力技能",
    "skill_thorns": "荆棘技能",
    "(Base:": "(基础:",
    "all Combat Skills": "所有战斗技能",
    "Divine)": "神圣)",
    "Ancient Skull Helm": "上古骷髅盔",
    "Dodged!": "闪避!",
    "Frenzy!": "疯狂!",
    "Master's Vampire Ring": "大师吸血鬼戒指",
    "Vital Bone Reaper": "活力骨头收割者",
    "Agile Boots of Lightness": "敏捷轻盈战靴",
    "Godly Vital Ring of Greed of Swiftness": "神圣的迅捷贪婪之戒",
    "Tired of selling items manually? Go to": "厌倦了手动出售物品吗？前往",
    "Tip:": "提示:",
    "Profile > Settings": "个人资料 > 设置",
    "to enable the": "以启用",
    "Auto-Sell Filter": "自动出售过滤器",
    "Recovering...": "恢复中...",
    "STRIKE!": "挖掘!",
    "STRIKE THE VEIN!": "挖掘矿脉!",
    "Hearty Tusked Bandit Helmet": "健壮的獠牙强盗头盔",
    "Master's Ring of Greed": "大师的贪婪之戒",
    "Move to stash": "移到储藏室",
    "Automatically sell items of this rarity or lower when obtained (Active & Offline).": "获得后自动出售该稀有度及以下的物品（活跃 & 离线）",
    "Game Settings": "游戏设置",
    "Keep All": "保留全部",
    "Sell Common": "出售普通",
    "Sell Epic": "出售史诗",
    "Sell Legendary": "出售传说",
    "Sell Rare": "出售稀有",
    "Sell Uncommon": "出售罕见",
    "⚠️ Danger Zone": "⚠️ 危险区",
    "1 Random Equipped Item Permanently": "随机获得1件永久装备物品",
    "Dying in combat (Active or Offline) causes you to lose": "在战斗中死亡（在线或离线）会导致你失去",
    "Master's Roid Ring": "大师手环",
    "Decent Merchant's Ring": "体面的商人戒指",
    "Constellation:": "星座:",
    "Celestial Constellations": "天体星座",
    "copper": "铜",
    "adamant": "艾德曼",
    "Heart": "之心",
    "iron": "铁",
    "mithril": "秘银",
    "Next:": "下一个:",
    "Mining Efficiency": "采矿效率",
    "Mastery Node": "专精节点",
    "LOCKED": "未解锁",
    "rune": "符文",
    "Perfect:": "完美:",
    "PERFECT!": "完美!",
    "Will": "之意志",
    "Stardust": "星尘",
    "Upgrade Cost": "升级成本",
    "Sharpened Tips": "打磨提示",
    "Unlock Node": "解锁节点",
    "The Pickaxe": "镐子",
    "Stardust Infusion": "星尘灌注",
    "Stardust (Perfect!)": "星尘 (完美!)",
    "The Titan's Spear": "泰坦之矛",
    "Titan's Strength": "泰坦之力",
    "Not enough copper ore!": "铜矿石不足!",
    "Ore + XP +": "矿石 + 经验值 +",
    "HIT!": "命中!",
    "Hit:": "命中:",
    "Active Mining Cooldown reduced to 0.25s": "主动采矿的冷却时间降低到0.25秒",
    "Celestial Constellations": "天体星座",
    "Celestial Velocity": "天体速度",
    "Channel the power of the stars into your tools and body.": "将星辰的力量注入你的工具和身体。",
    "Constellation:": "星座:",
    "Gain 5 Strength per Mining Level per Upgrade": "每次升级每采矿等级获得5点力量",
    "Muscle": "肌肉",
    "Reinforced Shaft": "加固竖井",
    "Select a star node to view details and upgrades.": "选择星型节点查看详细信息和升级。",
    "Code": "代码",
    "Rec": "战绩",
    "You Lost!": "你输了!",
    "on every attack.": "在每次攻击。",
    "Duel Started!": "切磋开始了!",
    "Combat Log": "战斗日志",
    "Arena Rules": "竞技场规则",
    "±15% Damage Variance": "±15% 伤害方差",
    "applied to prolong fights.": "用于延长战斗时间。",
    "at 30s (Damage +100% every 10s).": "30秒（每10秒伤害+100%）。",
    "'s Equipment": "的装备",
    "Clear": "清除",
    "skill_defiance": "防御技能",
    "Godly Great Merchant's Amulet of the Vampire": "吸血鬼的虔诚大商人之护身符",
    "Upgrade Node": "升级节点",
    "Wolf Pelt Vest": "狼皮背心",
    "Reset Arena": "重置竞技场",
    "Sudden Death": "猝死",
    "You Won!": "你赢了!",
    "Godly Relic Merchant's Amulet of Might": "神圣遗物商人的实力护身符",
    "Godly Savage Bandit Robes of Stone": "神圣野蛮强盗的石头长袍",
    "Godly Vital Shadow Ring of Wealth": "神圣活力阴影财富之戒",
    "Ancient Oberservers Boots": "古代观察者的靴子",
    "Active Mining Cooldown reduced to 0.25s. +1% Chance to find Stardust while Mining.": "主动采矿的冷却时间降低到0.25秒。+1%的几率在采矿时找到星尘。",
    "Master's Berserker Ring": "大师狂战士戒指",
    "You Died!": "你挂了!",
    "Epic": "史诗",
    "Note:": "注意:",
    "Rare": "稀有",
    "Rarity Guide": "稀有度指南",
    "rune_boots": "符文靴",
    "rune_helm": "符文头盔",
    "rune_sword": "符文剑",
    "stone_boots": "石靴",
    "titan_fist": "泰坦之拳",
    "Uncommon": "罕见",
    "Godly": "神圣",
    "Gear (Armor/Weapons)": "装备 (护甲/武器)",
    "Common": "普通",
    "Crit Dmg": "暴击伤害",
    "critDamage": "暴击伤害",
    "adamant_plate": "艾德曼板甲",
    "any Rarity": "任意稀有度",
    "(Color). Equip the full set for unique bonuses!": "(颜色)。穿戴全套可获得专属加成！",
    "(e.g., +1 Might). This is an": "（例如，+1 实力）。这是一个",
    "Agile Granite Boots": "灵活的花岗岩靴子",
    "and does NOT count towards Rarity.": "并且不计入稀有度。",
    "Base stats (Strength, Defense) are determined by the item's material.": "基础属性（力量，防御）由物品的材质决定。",
    "belong to a Set. They can have": "属于一个套装。它们可以",
    "berserker_boots": "狂战士靴子",
    "berserker_gauntlets": "狂战士护手",
    "berserker_helm": "狂战士头盔",
    "berserker_plate": "狂战士板甲",
    "Bonus Stats": "奖励属性",
    "Deadly Rune Boots": "致命符文靴",
    "earthshaker": "地震器",
    "Enhanced Granite Boots": "加强型花岗岩靴",
    "Extra Stat": "额外属性",
    "Fierce Earthshaker": "凶猛的地震者",
    "Fierce Rune Sword": "凶猛的符文剑",
    "Ghostly Granite Boots": "幽灵般的花岗岩靴子",
    "granite_maul": "花岗岩锤",
    "health potion": "生命药水",
    "Higher rarity items have more": "稀有度更高的道具拥有更多",
    "If a Bonus Stat matches a Base Stat, they combine into a single higher value.": "如果奖励属性与基础属性相匹配，它们将组合成一个更高的值。",
    "Item Lost on Death": "死亡丢失物品",
    "Items can roll a": "物品可以掷出",
    "Items with a": "物品有",
    "Jewelry (Rings/Amulets)": "首饰(戒指/项链)",
    "Legendary": "传说",
    "Living Adamant Plate": "活铁甲",
    "Living Berserker Boots": "活狂战士靴子",
    "Potions Consumed": "药水消耗",
    "Ran out of potions while fighting. Simulation stopped early.": "战斗时药水用完了。模拟提前停止。",
    "Savage Granite Boots": "野蛮花岗岩靴子",
    "Savage Rune Helm": "野蛮符文头盔",
    "Set Items": "套装道具",
    "Set Name": "套装名称",
    "Sort by Crit Damage": "按暴击伤害排序",
    "Sort by Gold Bonus": "按金币加成排序",
    "Sort by XP Bonus": "按经验加成排序",
    "Specific Skill Bonus": "特殊技能奖励",
    "Specific Skill Bonuses (Extra)": "特殊技能奖励（额外）",
    "Sturdy Berserker Helm": "坚固的狂战士头盔",
    "Sturdy Rune Boots": "坚固的符文靴",
    "super potion": "超级药水",
    "Swift Rune Boots": "迅捷符文战靴",
    "Vital Earthshaker": "活力地震器",
    "Vital Rune Helm": "活力符文头盔",
    "wrath_axe": "愤怒之斧",
    "Atk Speed": "攻击速度",
    "+20 Speed per point in Frenzy": "疯狂状态下，每点+20速度",
    "Deal 10 DPS per skill point.": "每个技能点造成 10 DPS。",
    "Raw Hit Dmg": "原始攻击伤害",
    "Increases Attack Speed by 40 per point.": "每点增加40攻击速度。",
    "Quest items are protected.": "任务物品会受到保护。",
    "dodge Chance": "闪避几率",
    "Gain 3 Strength per Mining Level per Upgrade": "每升级一次采矿等级获得3点力量",
    "Not enough Gold!": "金币不足!",
    "Start Season": "开始赛季",
    "% Chance for Stardust While Actively Mining": "在主动采矿时，有%的几率获得星尘",
    "A new competitive season has started! To ensure a fair playing field, all participants must start fresh.": "一个新的竞技赛季已经开始！为了确保公平竞争，所有参与者必须重新开始。",
    "Backup Current Save (Recommended before resetting)": "备份当前保存（建议重置前备份）",
    "Casual Play": "休闲玩法",
    "Choose your path carefully.": "小心选择你的道路。",
    "For full patch notes, join our": "完整的补丁说明，加入我们的",
    "Keep your current progress.": "保持当前的进度。",
    "Leaderboard & Dueling DISABLED.": "排行榜和决斗被禁用。",
    "Legacy Mode": "传承模式",
    "NEW SEASON BEGUN": "新赛季开始",
    "Recommended": "推荐",
    "Reset to Level 1. Compete on the Leaderboard.": "重置到1级。参与排行榜竞争",
    "Season: 1 - The Return of the Fallen": "赛季1 -陨落者的回归",
    "Back": "返回",
    "BACKUP SAVE": "备份存档",
    "Season Ends In": "距离赛季结束还有",
    "Copy to Clipboard": "复制到剪贴板",
    "Copy your save string below and store it safely.": "复制下面的存档字符串并安全地存储它。",
    "% Speed Bonus • +1% Efficiency / Level)": "% 速度加成 • +1% 效率 / 等级)",
    "(Lvl": "(等级",
    "Act I: The Beginning": "第1幕：开始",
    "Act II: The Wilds": "第2幕：荒野",
    "Act III: The Depths": "第3幕：深渊",
    "Act IV: The Abyssal Gaze": "第4幕：深渊凝视",
    "Act V: End of Time": "第5幕：时间的尽头",
    "Wolves, Skeletons, and Bandits": "狼，骷髅和强盗",
    "The Unknown": "未知",
    "The Final Confrontation": "最终对决",
    "Spiders, Golems, and Dragons": "蜘蛛，魔像和龙",
    "Dying in combat (Only Active) causes you to lose": "在战斗中死亡（只有主动状态）会导致你失去",
    "Gold:": "金币:",
    "Possible Loot (": "可能的战利品 (",
    "Select Act": "选择幕数",
    "Rats, Slimes, and Goblins": "老鼠、史莱姆和哥布林",
    "thorns": "荆棘",
    "Bull King": "牛魔王",
    "crit Damage": "暴击伤害",
    "Blood Amulet": "血护身符",
    "Blood Drain: Each attack drains 100 HP as pure damage (ignores defense) and heals you": "吸血：每次攻击吸取100点纯伤害（无视防御），并治疗自身",
    "Dragonfire Strike: 15% chance to deal 250% damage and ignite for 1s (5% HP)": "龙火打击：15%的几率造成250%伤害并点燃15秒（5% HP）",
    "Frozen Perception: 15% chance to freeze enemies for 2s (cannot attack). +1 All Skills. +10% XP. Frozen enemies take +20% damage": "冰冻感知：有15%的几率将敌人冻结2s（不能攻击）。+1所有技能+ 10% XP。冰冻的敌人受到+20%的伤害",
    "Inferno Immolation: 5% chance to ignite enemies for 5s (5% max HP/sec). +2 All Skills. +15% damage to burning enemies.": "地狱献祭：5%的几率点燃敌人，持续5秒（每秒最大5% HP）。+2所有技能。对燃烧的敌人造成15%的伤害。",
    "Kali, Ender of Time": "卡莉，时间的终结者",
    "Potion Effect": "药水效果",
    "potion Effectiveness": "药水效果",
    "random Combat Skill": "随机战斗技能",
    "random Passive Skill": "随机被动技能",
    "There are old tales of a fearsome beast that lived beyond a magical red portal": "有一个古老的传说，说有一只可怕的野兽住在一个神奇的红色传送门后面",
    "Titan's Wrath: Every 5s in combat gain +15% damage & +5% crit (max 10 stacks). Below 30% HP: +40% damage, +30% damage reduction, +20% lifesteal. +2 All Skills.": "泰坦之怒：战斗中每5秒增加15%伤害和5%暴击（最多10层）。生命值低于30%:+40%伤害，+30%减伤，+20%吸血。+2所有技能。",
    "⚔️ BEST GEAR": "⚔️ 最佳装备",
    "SAVE": "保存",
    "Equipment Loadouts": "装备预设",
    "Sort by Potion Effect": "按药水效果排序",
    "+0.5% Crit Chance per point in Divine Wrath": "神怒每点增加0.5%的暴击几率",
    "+0.5% Ignore Def per point in Lethality": "每点致命+0.5%无视防御",
    "+1.5% Thorns Lifesteal per point in Defiance": "每点反抗+1.5%荆棘吸取生命",
    "+1% Execute Damage per point in Might": "每点力量+1%的执行伤害",
    "+1% Ignore Defense per point in Iron Skin": "每点铁肤+1%忽视防御",
    "+1% Iron Skin Defense per point in Stone Skin": "每点石肤+1%铁肤防御",
    "+1% Iron Skin Defense per point in Thorns": "每点荆棘+1%铁肤防御",
    "+1% Reduction per point in Thorns": "每点荆棘+1%减少伤害",
    "+1% Regen per point in Vitality": "每点活力+1%回复",
    "+1% Vitality HP per point in Immortality": "不朽每点+1%生命值",
    "+1% Vitality HP per point in Regeneration": "每点回复+1%生命值",
    "+2% Frenzy HP per point in Haste": "急速中每点增加2%狂暴HP",
    "+2% Reflect per point in Stone Skin": "每点石肤+2%反射",
    "+3% Crit Damage per point in Precision": "每点精准增加3%暴击伤害",
    "+5 DPS per point in Execute": "每点执行+5 DPS",
    "+5% Crit Damage per point in Immortality": "不朽每点增加5%暴击伤害",
    "A ring worn by merchant kings. Stronger stats than the standard version.": "商人国王戴的戒指。比标准版本更强的统计。",
    "A symbol of immense wealth. Stronger stats than the standard version.": "巨大财富的象征。比标准版本更强的统计。",
    "Chance to attack twice. (+1% per point)": "有机会攻击两次。（每点+1%）",
    "Chance to survive a fatal blow (1.5% per point).": "在致命一击中幸存的几率（每点1.5%）。",
    "Elusive Copper Boots": "难以捉摸的铜靴",
    "Heal HP on kill (Scales exponentially).": "在击杀时治疗HP（指数级缩放）。",
    "If a Bonus Stat matches a Base Stat, they combine into a single higher value, indicated by a": "如果奖励属性与基础属性相匹配，它们将组合成一个更高的值，用a表示",
    "Increases Defense (Scales exponentially).": "增加防御（指数级增长）。",
    "Increases Max HP (Scales exponentially).": "增加最大生命值（指数级增长）。",
    "Increases Physical Damage by 30 per point.": "每点增加30点物理伤害。",
    "Mythic items (and lucky drops) grant a": "神话物品（和幸运掉落物）给予a",
    "Reduces incoming damage by 1% per point.": "每点减少1%的伤害。",
    "Reflect 5% damage back to attacker per point.": "每点向攻击者反射5%的伤害。",
    "Regenerate HP (Scales exponentially: 2000/s at Level 20).": "回复生命值（指数级增加：20级时2000/s）。",
    "LOAD": "加载",
    "icon.": "图标.",
    "Already wearing best gear!": "身上已经是最佳装备了!",
    "Join our Discord": "加入我们的 Discord",
    "for long-term growth. Increase your": "为了长期增长。增加你的",
    "Battle monsters to Level Up and find better loot. Upgrade": "与怪物战斗以升级并找到更好的战利品。升级",
    "- No Title -": "- 无称号 -",
    "Abyssal Lord": "深渊领主",
    "Atk Spd": "攻击速度",
    "Atk/s": "攻击/秒",
    "Avg Hit": "平均伤害",
    "Dmg Range": "伤害范围",
    "Current Stats": "当前属性",
    "Def": "防御",
    "Dodge": "闪避",
    "Empty": "空",
    "enemies": "敌人",
    "Dropped by Act": "通过幕数掉落",
    "Equipped": "已装备",
    "EQUIPMENT LOADOUTS": "装备预设",
    "Essence": "精华",
    "Warning: The Dungeon offers NO loot or XP rewards. You will NOT lose items on death. It is purely for Leaderboard glory! Titles can be earned based on progress, and some are exclusive to Season 1!": "警告：地下城不提供战利品或经验值奖励。死亡时不会丢失物品。这纯粹是为了排行榜的荣耀！可以根据进度获得头衔，有些是第一赛季独有的！",
    "Potion": "药水",
    "Potion Eff": "药水效果",
    "Upgrade Item": "升级物品",
    "Updates every hour": "每小时更新一次",
    "To auto-sell, go to": "想自动出售，前往",
    "Titan's Edge": "泰坦之刃",
    "ACT": "幕数",
    "Act": "幕数",
    "% Base Stats)": "% 基础属性)",
    "% Craft Speed • +": "% 制作速度 • +",
    "(1% chance per kill)": "(1% 几率在每次击杀时)",
    "(Active Combat Only)": "(仅限主动战斗)",
    "✨ Essence Weapons": "✨ 精华武器",
    "⚔️ Standard Gear": "⚔️ 标准装备",
    "⚔️ Enemy HP, Damage, and Defense scale with each wave. After completing all enemies, they loop with even higher stats.": "⚔️ 敌人的生命值，伤害和防御随每一波而变化。在完成所有敌人后，他们将循环获得更高的属性。",
    "Rare Resources:": "稀有资源:",
    "Resistance": "抵抗",
    "Resistances": "抵抗",
    "Select Title": "选择称号",
    "randomCombatSkill": "随机战斗技能",
    "randomPassiveSkill": "随机被动技能",
    "A blade that tears through reality itself. Infused with cosmic power.": "一把刺穿现实的利刃。注入了宇宙的力量。",
    "A chilling blade that drains the warmth from your enemies.": "一把能吸干敌人体内热量的冷刃。",
    "A savage blade forged from the essence of the wilds. Strikes with primal fury.": "一把由荒野之精锻造而成的野蛮之剑。用原始的愤怒攻击。",
    "A simple but reliable metal. Enhances your grip and strikes.": "一种简单但可靠的金属。提高你的握力和打击。",
    "An incredibly hard alloy, difficult to forge. Enhances your grip and strikes.": "一种极其坚硬的合金，难以锻造。提高你的握力和打击。",
    "Equip an item in this slot to upgrade it at the station.": "在这个槽中装备一件物品可以在车站升级。",
    "Forged from the essence of fallen monsters. Dragons fear this blade.": "由堕落怪物的精华锻造而成。龙害怕这把剑。",
    "Forged with ancient runic magic. Enhances your grip and strikes.": "用古老的符文魔法铸造。提高你的握力和打击。",
    "Frostborn Blade": "霜生之刃",
    "Generate Duel Code": "生成决斗代码",
    "Lightweight yet stronger than steel. Enhances your grip and strikes.": "重量轻，但比钢更坚固。提高你的握力和打击。",
    "Quest items & Relics are protected.": "任务物品和遗物受到保护。",
    "Sturdy and dependable. Enhances your grip and strikes.": "坚固可靠。提高你的握力和打击。",
    "The ultimate weapon, forged from the essence of the apocalypse itself.": "终极武器，由天启本身的精华锻造而成。",
    "Void Reaver": "虚空收割者",
    "Dark": "暗系",
    "Damage Range": "伤害范围",
    "Cold": "冰系",
    "Fire": "火系",
    "Poison": "毒系",
    "Relic": "遗物",
    "Utility": "效用",
    "BEST POTENTIAL": "最佳潜力",
    "Already wearing best gear (if fully upgraded)!": "已经穿上了最好的装备（如果完全升级）！",
    "(Interval:": "(时间间隔:",
    "+50% Stat Strength": "+50% 属性的力量",
    "+Combat Skills": "+战斗技能",
    "+Passive Skills": "+被动技能",
    "20% Chance for Mythic!": "20% 几率获得神话!",
    "Actual DPS:": "实际输出DPS：",
    "Amulets": "护身符",
    "Consumables": "消耗品",
    "Dbl Strike": "双重攻击",
    "Junk (1 Bonus)": "垃圾（1 加成）",
    "Decent (2 Bonuses)": "体面（2 加成）",
    "Great (3 Bonuses)": "伟大（3 加成）",
    "Relic (4 Bonuses)": "遗物（4 加成）",
    "Mythic (5 Bonuses)": "神话（5 加成）",
    "For the elite. Guaranteed": "精英。必得",
    "Great": "伟大",
    "have a chance to roll": "有一定几率掷出",
    "High Risk, High Reward": "高风险，高回报",
    "items guarantee +2 to these skills!": "物品保证+2这些技能！",
    "Merchant items are a gamble! When purchased, they roll a random rarity which determines their stats.": "购买商品是一场赌博！当玩家购买时，他们会随机掷出稀有值来决定自己的属性。",
    "Min Hit:": "最小攻击:",
    "Mythic": "神话",
    "on top of rarity bonuses.": "在稀有度奖励之上。",
    "Rarity Odds": "稀有度概率",
    "rarity or higher.": "稀有度或以上。",
    "Rings": "戒指",
    "Special Bonuses": "特殊加成",
    "Tycoon Items (5M Gold)": "大亨物品（5M 金币）",
    "✨ Stardust": "✨ 星尘",
    "💎 God Shards": "💎 神之碎片",
    "💡 Stuck? Here's how to progress:": "💡 卡住了? 以下是克服困难的方法：",
    "⚔️ Ascension Tokens": "⚔️ 转生代币",
    "Level up!": "升级了!",
    "Loading": "加载中",
    "Mine ores": "开采矿石",
    "Level up Crafting": "升级制作",
    "Help": "帮助",
    "Shop": "商店",
    "Upgrade & Ascend": "升级 & 转生",
    "— craft Essence Weapons for big stat boosts beyond metal gear.": "- 制作精华武器，获得超越金属装备的高额属性加成。",
    "(Dungeon tab) — contribute DPS to the daily boss for up to 300 Ascension Tokens/day.": "（地下城标签页）——为每日首领贡献 DPS，每日最多可领取 **300 枚转生代币**。",
    "(Dungeon tab) to earn up to 200 Ascension Tokens/day for powerful Ascendant Crafting recipes.": "（地下城标签页）每日最多可获取 **200 枚转生代币**，用于解锁强力的转生制作配方。",
    "(Mining page) — upgrade for permanent stat boosts like STR, HP, mining speed, and resistances.": "（采矿页面）——进行升级，可获得力量、生命值、采矿速度、抗性等永久属性提升。",
    "📍 Earn from: Ascendant's Trial & Boss Room": "📍 获取途径：转生试炼 & 首领房间",
    "Cerberus Fangs": "地狱犬尖牙",
    "Characters": "角色",
    "Collection": "图鉴",
    "Complete trial waves or contribute DPS to the daily boss.": "完成试炼波次，或为每日首领输出伤害。",
    "Constellations": "星象",
    "Cosmic energy dropped while manual mining.": "手动采矿时可掉落**宇宙能量**。",
    "Daily Cap: up to 500 tokens/day (200 trials + 300 boss room)": "每日上限：最多 500 枚代币/天（试炼 200 枚 + 首领房间 300 枚）",
    "Drop Rate: 1% base per ore mined (manual mining only, up to 6% with Constellations Upgrades)": "掉落率：每开采一个矿石基础掉落率 1%（仅限手动采矿，星象升级后最高可达 6%）",
    "Drop Rate: 5% per ore mined (manual mining only)": "掉落率：每开采一个矿石 5%（仅限手动采矿）",
    "Enter a 6-character": "输入 6 位字符",
    "Every combat level gives you base HP and Strength.": "每提升一级战斗等级，均可获得基础生命值与力量属性。",
    "Fight the Boss Room": "挑战首领房间",
    "Infuse with Essences": "注入精华",
    "No Effects Owned": "未拥有任何效果",
    "Rare divine fragments dropped while manual mining.": "手动采矿时可掉落稀有**神级碎片**。",
    "Rare fangs torn from the jaws of Cerberus.": "从地狱犬口中撕下的稀有尖牙。",
    "Run Ascendant's Trials": "挑战转生试炼",
    "Source: Cerberus (every 500 kills)": "获取途径：地狱犬（每击杀 500 只掉落）",
    "Spend on: Guaranteed Set Mastery during Divine Ascension, Ascendant Crafting": "用途：在神之转生期间必定获得套装精通效果、用于转生制作",
    "to fuel your crafting and earn God Shards + Stardust.": "为制作提供材料，并获取**神之碎片**与**星尘**。",
    "to unlock higher-tier gear (T1–T8) with the stats you need — HP, Strength, Crit Immunity, Resistances, etc.": "解锁高阶装备（T1–T8），获得所需属性——生命值、力量、暴击免疫、抗性等。",
    "to view their equipped gear, upgrades, and stats!": "查看其穿戴的装备、升级效果与属性！",
    "Used for: Constellation upgrades, Ascendant Crafting": "用途：星象升级、转生制作",
    "Used for: Divine Reforging (re-roll ascension bonuses)": "用途：神之重铸（重roll转生加成）",
    "Used for: Equipment Upgrades, Constellations, Divine Ascension": "用途：装备升级、星象、神之转生",
    "your best Godly items for the biggest power spikes.": "穿戴你最顶级的神级装备，实现战力大幅飞跃。",
    ". Top players optimize DPS skills for maximum rank!": "。顶级玩家优化DPS技能以获得最高排名！",
    "(Join a Season to compete!)": "（加入一个赛季来竞争！）",
    "Update (Disabled)": "更新 (禁用)",
    "Updates roughly every 6 hours • Ranked by Combat Power": "大约每 6 小时更新一次 • 按战力排序",
    "skill allocation": "技能分配",
    "is affected by": "受影响于",
    "View Gear": "查看装备",
    "Ends In:": "距离结束还有:",
    "HP/s": "生命值/秒",
    "HP Total": "总计生命值",
    "Raw DPS": "原始DPS",
    "Pts": "点数",
    "Lv.": "等级",
    "Locked:": "未解锁:",
    "Loadouts": "配装",
    "Load": "加载",
    "Leader": "领袖",
    "Points SPENT in": "点数花费于",
    "Combat (": "战斗 (",
    "% Max HP)": "% 生命值上限)",
    "% Total Speed)": "% 总速度)",
    "% Total Str)": "% 总力量)",
    "% Total Def)": "% 总防御)",
    "% Res)": "% 抵抗)",
    "% All Res": "% 全部抵抗",
    "• Need": "• 需要",
    "• Requires": "• 要求",
    "Reset": "重置",
    "Reset (": "重置 (",
    "Req:": "要求:",
    "Skill Trees": "技能树",
    "Passives (": "被动 (",
    "Cerberus": "地狱犬",
    "The Archmage": "大法师",
    "The Headless Knight": "无头骑士",
    "+0.25% Double Strike per point in Divine Wrath": "每点神怒：双重打击几率 +0.25%",
    "+0.25% Survival per point in Defiance": "每点蔑视：生存几率 +0.25%",
    "+0.25% Survival per point in Vitality": "每点活力：生存几率 +0.25%",
    "+0.25% Total Strength per point in Critical Strike": "每点暴击打击：总力量 +0.25%",
    "+0.5% Bonus Item Chance per point in Greed": "每点贪婪：额外物品掉落几率 +0.5%",
    "+0.5% Min Damage per point in Execute": "每点处决：最小伤害 +0.5%",
    "+0.5% Total Defense per point in Stone Skin": "每点石肤：总防御 +0.5%",
    "+0.5% Total Defense per point in Thorns": "每点荆棘：总防御 +0.5%",
    "+0.5% Total Strength per point in Lethality": "每点致命：总力量 +0.5%",
    "+0.5% Total Strength per point in Vampirism": "每点吸血：总力量 +0.5%",
    "+1% All Res per point in Thorns": "每点荆棘：全元素抗性 +1%",
    "+1% chance per point for a guaranteed bonus item on kill.": "每点：击杀时必定获得额外物品的几率 +1%",
    "+1% chance to Dodge attacks per point.": "每点：闪避攻击几率 +1%",
    "+1% Max HP on kill per point in Haste": "每点急速：击杀后最大生命值 +1%",
    "+10% Gold Gain per point.": "每点：金币获取 +10%",
    "+3% XP Gain per point.": "每点：经验获取 +3%",
    "+30 Speed per point in Frenzy": "每点狂怒：速度 +30",
    "+30 Strength and +3% total Strength per point.": "每点：力量 +30 且总力量 +3%",
    "+5% Gold per point in Scavenger": "每点拾荒：金币获取 +5%",
    "+5% Gold per point in Wisdom": "每点智慧：金币获取 +5%",
    "×0.5% DR,": "伤害减免 ×0.5%",
    "👑 Crypt King": "👑 地穴之王",
    "Adds 10% to base 150% crit multiplier per point.": "每点：在基础150%暴击倍率上额外 +10%",
    "Chance to survive a fatal blow and heal 50% Max HP (1% per point).": "每点：承受致命伤害时存活并恢复50%最大生命值的几率（1%/点）",
    "Deal +15% bonus damage per point to enemies below 30% health.": "每点：对30%血量以下敌人造成额外伤害 +15%",
    "Heal 3% Max HP on kill per point.": "每点：击杀后恢复3%最大生命值",
    "Heal for 0.5% of damage dealt per point. Max heal: 10% max HP/hit.": "每点：造成伤害时恢复0.5%生命值，单次攻击最大治疗量为10%最大生命值",
    "Increases Armor Penetration (+2% Ignore Defense per point).": "每点：护甲穿透提升（无视防御 +2%/点）",
    "Increases Attack Speed by 300 per point and total speed by 2% per point.": "每点：攻击速度 +300 且总速度 +2%",
    "Increases Defense (Scales exponentially) and total defense by 4% per point.": "每点：提升防御（指数成长）且总防御 +4%",
    "Increases Max HP by 150 and +1% per point.": "每点：最大生命值 +150 且额外 +1%",
    "Increases minimum damage by 1% per skill point.": "每技能点：最小伤害 +1%",
    "Kali, Ender of Time": "时间终结者 卡莉",
    "Reduces incoming damage by 0.5% and grants +3% All Resistances per point.": "每点：受到的伤害 -0.5% 且全元素抗性 +3%",
    "Reflect 4% damage back to attacker per point.": "每点：向攻击者反弹4%伤害",
    "Regenerate 100 HP/s + 0.5% Max HP/s per point.": "每点：每秒恢复100生命值 + 0.5%最大生命值",
    "Synergy Bonuses:": "协同加成：",
    "Target Dummy": "训练假人",
    "Upgrade Cost:": "升级花费：",
    "Item Stats": "物品属性",
    "Max All": "全部最大",
    "EQUIPPED": "已装备",
    "Upgrades": "升级",
    "Tokens +": "代币 +",
    "Select an item to reforge": "选择一个物品去重铸",
    "Select an Item": "选择一个物品",
    "Pay": "支付",
    "Passive Skill": "被动技能",
    "✨ 2% chance for Divine Set Mastery!": "✨ 2% 几率获得**神级套装精通**！",
    "✨ Divine Ascension Bonuses": "✨ 神之转生加成",
    "✨ Divine Mastery": "✨ 神级精通",
    "AFTER +25%": "提升后 +25%",
    "Ascendant Blessing:": "转生祝福：",
    "Ascended Items (": "已转生物品（",
    "Available Set Bonuses": "可用套装加成",
    "Blood Drain: Each attack drains 5% of your max HP as pure damage (ignores defense) and heals you. Lifesteal cap: 10% → 25% max HP/hit": "血之汲取：每次攻击汲取你 5% 最大生命值作为真实伤害（无视防御）并为你治疗。吸血上限：10% → 25% 最大生命值/次攻击",
    "Blood Rage: Gain +35% damage and +10% crit per 10% HP missing": "血之狂暴：每缺失 10% 生命值，获得 +35% 伤害与 +10% 暴击率",
    "can be Divinely Ascended for": "可通过神之转生获得",
    "Combat Skill": "战斗技能",
    "Crit Immunity": "暴击免疫",
    "Divine Ascension": "神之转生",
    "Divine Mastery": "神级精通",
    "Divine Mastery:": "神级精通：",
    "Dragonfire Strike: 15% chance to deal 250% damage and mark enemy burning for 1.5s": "龙焰打击：15% 几率造成 250% 伤害，并标记敌人灼烧 1.5 秒",
    "Fortune": "运势",
    "Frozen Perception: 2% chance to freeze enemies for 3.5s (cannot attack). +10% XP. Frozen enemies take +250% damage, -50% base defense, and you attack 50% faster (cap 0.5s). +1 All Skills.": "冰封感知：2% 几率冻结敌人 3.5 秒（无法攻击）。经验值 +10%。被冻结敌人承受 +250% 伤害，基础防御 -50%，你的攻击速度 +50%（上限 0.5 秒）。全技能 +1。",
    "Godly items at": "神级物品",
    "Golden Touch: 2x Godly chance on combat drops & crafting. +1 All Skills.": "黄金之触：战斗掉落与制作时，神级物品几率翻倍。全技能 +1。",
    "guaranteed": "必定获得",
    "Guaranteed Set Mastery + Stat Bonus": "必定获得套装精通 + 属性加成",
    "Hellfire Pact": "地狱火契约",
    "Inferno Immolation: 5% chance to ignite enemies for 5s (100% your max HP/sec = 5x HP total). +100% damage to burning enemies. +1 All Skills.": "炼狱献祭：5% 几率点燃敌人 5 秒（每秒造成 100% 最大生命值伤害，总计 5 倍生命值）。对灼烧敌人伤害 +100%。全技能 +1。",
    "Midas Touch": "迈达斯之触",
    "No ascended items": "无已转生物品",
    "No ascended items found": "未找到已转生物品",
    "on Divine Ascension. Costs:": "在神之转生时。消耗：",
    "Pay to Win: 3% chance on hit to deal bonus damage equal to your Gold Bonus %. +8 Speed per 1% Gold Bonus. +1 All Skills.": "胜者之赏：攻击时有 3% 几率造成等同于金币加成百分比的额外伤害。每 1% 金币加成提供 +8 速度。全技能 +1。",
    "Phantom Strike: 10% chance to multiply your hit by 40% of your Crit Damage": "幻影打击：10% 几率使本次攻击伤害额外增加暴击伤害的 40%",
    "Primal Instinct: Deal +30% damage. Heal 25% max HP on kill": "原始本能：造成伤害 +30%。击杀时恢复 25% 最大生命值",
    "Reforge": "重铸",
    "Replaces the 2% chance from Divine Ascension — always grants both Set Mastery and Stat Bonus.": "替代神之转生的 2% 几率——必定同时获得套装精通与属性加成。",
    "Sacred Restoration": "神圣复苏",
    "Sacred Thorns: Gain bonus Thorns equal to Potion Effectiveness. Consumes potion every 10s. Potion Cooldown now 10s. +1 All Skills.": "神圣荆棘：获得等同于药水效果的额外荆棘反伤。每 10 秒消耗一瓶药水。药水冷却时间现为 10 秒。全技能 +1。",
    "Set Mastery + Stat Bonus!": "套装精通 + 属性加成！",
    "Set Mastery!": "套装精通！",
    "Stardust for": "星尘",
    "Summon Hellfire Imp: Enemies are always burning in active combat. Imp deals 50% your max HP/sec. +1 All Skills.": "召唤地狱火小鬼：主动战斗中敌人始终处于灼烧状态。小鬼每秒造成 50% 最大生命值伤害。全技能 +1。",
    "Swift Winds: +25% Dodge Chance. Each dodge grants +10% damage (stacks infinitely). Resets when hit or on new enemy. +1 All Skills.": "迅捷之风：闪避几率 +25%。每次闪避使伤害 +10%（无限叠加）。被击中或切换敌人时重置。全技能 +1。",
    "The specific set is randomly chosen based on your item's seed.": "具体套装根据物品随机种子随机选取。",
    "Titan's Wrath: Every 5s in combat gain +15% damage & +5% crit (max 10 stacks, resets each enemy). Below 30% HP: +40% damage, +30% damage reduction, +10% lifesteal. +1 All Skills.": "泰坦之怒：战斗中每 5 秒获得 +15% 伤害与 +5% 暴击（最多 10 层，切换敌人重置）。生命值低于 30% 时：伤害 +40%，伤害减免 +30%，吸血 +10%。全技能 +1。",
    "Windwalker's Grace": "风行者之赐",
    "Close": "关闭",
    "Daily Rewards": "日常奖励",
    "Next reward in:": "距离下一个奖励还有:",
    "Tokens": "代币",
    "Hide All": "全部隐藏",
    "empty": "空",
    "enemies (": "敌人 (",
    "epic": "史诗",
    "Dark  Res": "暗系抵抗",
    "Drop iLvl": "掉落 i等级",
    "⛏️ XP": "⛏️ 经验值",
    "⚔️ Avg iLvl:": "⚔️ 平均 i等级:",
    "⏱️ Offline": "⏱️ 离线",
    "(random)": "(随机)",
    "↑ Min Damage": "↑ 最小伤害",
    "↑ Crit Chance": "↑ 暴击率",
    "⚒️ Forge": "⚒️ 锻造",
    "🔒 Locked": "🔒 未解锁",
    "🔒 UNLOCK AT LEVEL": "🔒 解锁于等级",
    "📊 Stat Tiers": "📊 属性等阶",
    "rare": "稀有",
    "Regen": "回复",
    "Requires Lvl": "要求等级",
    "MAX": "最大",
    "Off": "关",
    "Min  Damage": "最小伤害",
    "min Damage": "最小伤害",
    "Metal Tier": "金属层级",
    "My Crits": "我的暴击",
    "My Damage": "我的伤害",
    "Lv": "等级",
    "Materials Required": "材料要求",
    "Speed:": "速度:",
    "Materials:": "材料:",
    "Pickaxe": "镐",
    "s Cooldown)": " 冷却时间)",
    "s Attack": " 攻击",
    "s per craft": " 每次制作",
    "slots available": "槽位可用",
    "total": "总计",
    "View Drops (": "查看掉落 (",
    "legendary": "传说",
    "Lifesteal (LS)": "生命偷取 (LS)",
    "Life  On  Hit": "生命值当命中",
    "Life on Hit": "生命值当命中",
    "life on Hit": "生命值当命中",
    "Hit": "命中",
    "Poison  Res": "毒系抵抗",
    "Physical  Res": "物理抵抗",
    "Fire  Res": "火系抵抗",
    "Cold  Res": "冰系抵抗",
    "Incoming Dmg": "受到伤害",
    "Act I Essence": "幕数 I 精华",
    "Act II Essence": "幕数 II 精华",
    "Act II Essence": "幕数 III 精华",
    "Act IV Essence": "幕数 IV 精华",
    "Crafting Lv.": "制作等级",
    "Crafting Queue": "制作队列",
    "Crit  Chance": "暴击几率",
    "Crit  Damage": "暴击伤害",
    "Crit  Immunity": "暴击免疫",
    "crit Immunity": "暴击免疫",
    "Craft Amount": "制作数量",
    "Base Stats:": "基础统计:",
    "Base Stats": "基础统计",
    "Blood Drain": "饮血",
    "Auto-Heal Potion (": "自动治疗药水 (",
    "Random Combat Skill": "随机战斗技能",
    "Random Passive Skill": "随机被动技能",
    "Requires Mining Lv": "要求采矿等级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "skill_execute": "skill_execute",
    "skill_haste": "skill_haste",
    "skill_precision": "skill_precision",
    "skill_stone_skin": "skill_stone_skin",
    "skill_vitality": "skill_vitality",
    "iLvl": "i等级",
    "pc)": "pc)",
    "Inv": "库存",
    "• iLvl": "• i等级",
    "Skill Points": "技能点",
    "SP:": "技能点:",
    "% DR": "% DR",
    "DR": "DR",
    "CP": "CP",
    "CP:": "CP:",
    "DPS:": "DPS:",
    "HM": "HM",
    "Season 4: Reign of Bones": "第4赛季：骨之统治",
    "Offense": "进攻",
    "Phys": "物理",
    "Physical": "物理",
    "gloves": "手套",
    "Gloves": "手套",
    "DPS": "DPS",
    "fire": "火系",
    "dark": "暗系",
    "cold": "冰系",
    "Maul": "重锤",
    "Gaze": "凝视",
    "Eye": "之眼",
    "Leader": "领袖",
    "Robes": "长袍",
    "Tamer": "驯服者",
    "Sword": "剑",
    "Crown": "王冠",
    "Greaves": "护手",
    "Plate": "板甲",
    "weapon": "武器",
    "Weapon": "武器",
    "ring": "戒指",
    "Ring": "戒指",
    "Helmet": "头盔",
    "helmet": "头盔",
    "Helm": "头盔",
    "boots": "靴子",
    "Boots": "靴子",
    "armor": "盔甲",
    "Armor": "盔甲",
    "amulet": "护身符",
    "Amulet": "护身符",
    "charm": "饰品",
    "Charm": "饰品",
    "Dragon": "龙",
    "dragon": "龙",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "/": "/",
    "#": "#",
    "NaN": "NaN",
    "Gityx": "Gityx",
    "x": "x",
    "%)": "%)",
    "???": "???",
    "\"": "\"",
    "Btc": "Btc",
    "ℹ️": "ℹ️",
    "🔒": "🔒",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "·": "·",
    "~": "~",
    "⏱️": "⏱️",
    "★": "★",
    "☐": "☐",
    "⛏️": "⛏️",
    "⭐": "⭐",
    "💡": "💡",
    "•": "•",
    "(+": "(+",
    "!": "!",
    "✨": "✨",
    "[": "[",
    "]": "]",
    "[+]": "[+]",
    "⚡": "⚡",
    "❄️": "❄️",
    "🌑": "🌑",
    "💪": "💪",
    "🔥": "🔥",
    "☠️": "☠️",
    "⚔️": "⚔️",
    "🛡️": "🛡️",
    "s)": ")",
    "✓": "✓",
    "│": "│",
    "▼": "▼",
    ">>": ">>",
    ">": ">",
    "<<": "<<",
    "<": "<",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': '负',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': '胜',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Owned: ": "拥有: ",
    "Rune ": "符文",
    "rune ": "符文",
    "Mithril ": "秘银",
    "mithril ": "秘银",
    "Copper ": "铜",
    "copper ": "铜",
    "Adamant ": "艾德曼",
    "adamant ": "艾德曼",
    "Iron ": "铁",
    "iron ": "铁",
    "Dungeon Run Ended at Wave ": "地牢运行结束于波次 ",
    "Next Upgrade ": "下一个升级 ",
    "Merchant's ": "商人的",
    "Vampire ": "吸血鬼",
    "Beast ": "野兽",
    "Bandit ": "匪徒",
    "Shadow ": "暗影",
    "Leather ": "皮革",
    "Berserker ": "狂战士",
    "Dragon Slayer ": "屠龙者",
    "Infernal ": "炼狱",
    "Oberservers ": "观察者",
    "Skull ": "骷颅",
    "Wolf Paw ": "狼爪",
    "Granite ": "坚毅",
    "MISS! ": "未命中! ",
    "Max Strike Speed: ": "最大挖掘速度：",
    "ACTIVE MINING: ": "主动挖矿: ",
    "Max Hit Speed: ": "最大命中速度: ",
    "Observer's ": "观察者",
    "Tycoon's ": "大亨",
    "Hard Mode": "困难模式",
    "Essence Weapons": "精华武器",
    "⛏️ Tools": "⛏️ 工具",
    "⚔️ Standard Gear": "⚔️ 标准装备",
    "🔒 UNLOCK AT LEVEL ": "🔒 解锁于等级 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " Upgrades": " 升级",
    " Copper Plate": "铜板甲",
    " Leather Cowl": "皮风帽",
    " Hunting Knife": "猎刀",
    " Leather Boots": "皮靴",
    " Copper Helm": "铜盔",
    " Copper Sword": "铜剑",
    " Merchant's Amulet": "商人护身符",
    " Sticky Shiv": "粘刀",
    " Iron Sword": "铁剑",
    " Mithril Sword": "秘银剑",
    " (Active)": " (主动)",
    " Bandit Robes": "强盗长袍",
    " Mithril Plate": "秘银板甲",
    " Amulet of Wisdom": "智慧护身符",
    " Iron Helm": "铁头盔",
    " Mithril Helm": "秘银头盔",
    " Adamant Helm": "艾德曼头盔",
    " Venom Fang": "毒牙",
    " Adamant Sword": "艾德曼剑",
    " Adamant Boots": "艾德曼靴子",
    " Bloodfang Blade": "血牙之刃",
    " Twin Daggers of Night": "孪生夜之匕首",
    " (CRIT, Execute, Divine Wrath!)": " (暴击, 处决, 神怒!)",
    " (CRIT, Phantom Strike, Divine Wrath!)": " (暴击, 幻影打击, 神怒!)",
    " (Phantom Strike, Divine Wrath!)": " (幻影打击, 神怒!)",
    " (CRIT, Divine Wrath!)": " (暴击, 神怒!)",
    " (Execute, Divine Wrath!)": " (处决, 神怒!)",
    " (Divine Wrath!)": " (神怒!)",
    " Beast Ring": "野兽戒指",
    " Frostbite": "寒霜之咬",
    " Wolf Pelt Vest": "狼皮背心",
    " Wolf Paw Boots": "狼皮靴子",
    " Upgraded!": " 已升级!",
    " Shadow Cowl": "暗影风帽",
    " (A1)": " (A1)",
    " (A2)": " (A2)",
    " (A3)": " (A3)",
    " (A4)": " (A4)",
    " (A5)": " (A5)",
    " cap)": " 上限)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\(\+([\d\.]+)\%\):$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\-([\d\.]+)\%$/,
    /^ \(([\d\.]+)\)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^T([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)\-([\d\.,]+)$/,
    /^([\d\.,]+)\-([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Act (.+) Essences$/, '幕 $1 精华'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/s$/, '$1\/秒'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^Next Tier \(\+([\d\.]+)\%\)$/, '下一层级 (+$1%)'],
    [/^Crit \(([\d\.]+)\%\)$/, '暴击 ($1%)'],
    [/^([\d\.]+)\% drop rate$/, '$1% 掉率'],
    [/^([\d\.]+)\% drop rate in Hard Mode$/, '$1% 掉率在困难模式'],
    [/^([\d\.]+)\% Chance$/, '$1% 几率'],
    [/^Crit ([\d\.]+)\%$/, '暴击 $1%'],
    [/^([\d\.]+)\% God Shard$/, '$1% 神之碎片'],
    [/^([\d\.]+)\% Damage Reduction$/, '$1% 伤害减免'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% Mining Speed per Level$/, '每级 +$1% 采矿速度'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+) Bonus$/, '$1 加成'],
    [/^([\d\.]+) Bonuses$/, '$1 加成'],
    [/^([\d\.]+) Bonuses \+$/, '$1 加成 +'],
    [/^([\d\.,]+) Skill Point$/, '$1 技能点'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Boosted Bonus$/, '$1 已提升加成'],
    [/^([\d\.,]+)x Health Potion$/, '$1x 生命药水'],
    [/^([\d\.,]+)x Mega Potion$/, '$1x 终级药水'],
    [/^([\d\.,]+)x Super Potion$/, '$1x 超级药水'],
    [/^\+([\d\.,]+) to Double Strike$/, '+$1 到 双重攻击'],
    [/^\+([\d\.,]+) to Frenzy$/, '+$1 到 疯狂'],
    [/^\+([\d\.,]+) to Might$/, '+$1 到 实力'],
    [/^\+([\d\.,]+) to Thorns$/, '+$1 到 荆棘'],
    [/^\+([\d\.,]+) to Greed$/, '+$1 到 贪婪'],
    [/^\+([\d\.,]+) to Execute$/, '+$1 到 处决'],
    [/^\+([\d\.,]+) to Wisdom$/, '+$1 到 智慧'],
    [/^\+([\d\.,]+) Iron Ore$/, '+$1 铁矿石'],
    [/^\+([\d\.,]+) Copper Ore$/, '+$1 铜矿石'],
    [/^\+([\d\.,]+) Boosted Bonus$/, '+$1 已提升加成'],
    [/^\+([\d\.,]+) Stardust$/, '+$1 星尘'],
    [/^\+([\d\.,]+) Max HP per Level$/, '每级 +$1 生命值上限'],
    [/^\+([\d\.,]+) Max HP per Mining Level$/, '每级采矿 +$1 生命值上限'],
    [/^\+([\d\.,]+) Combat Skill$/, '+$1 战斗技能'],
    [/^\+([\d\.,]+) Passive Skill$/, '+$1 被动技能'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\-([\d\.,]+) elves$/, '-$1 精灵'],
    [/^Restores ([\d\.,]+) HP.$/, '恢复 $1 生命值。'],
    [/^You healed for ([\d\.,]+)$/, '你 治疗了 $1 生命值'],
    [/^Day ([\d\.,]+) of ([\d\.,]+)$/, '天数 $1 \/ $2'],
    [/^iLvl ([\d\.,]+)\+$/, 'i等级 $1+'],
    [/^Slot ([\d\.,]+)$/, '槽位 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Loadout ([\d\.,]+)$/, '预设 $1'],
    [/^Loadout ([\d\.,]+) Saved!$/, '预设 $1 已保存!'],
    [/^Normal \(([\d\.,]+)\)$/, '正常 ($1)'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Updates every ([\d\.,]+) mins$/, '每 $1 分钟更新一次'],
    [/^Season ([\d\.,]+) Leaderboard$/, '赛季 $1 排行榜'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^You Dodged!$/, '你 躲开了!'],
    [/^You regenerated ([\d\.,]+) HP$/, '你 回复了 $1 生命值'],
    [/^Opponent regenerated ([\d\.,]+) HP$/, '对手 回复了 $1 生命值'],
    [/^Opponent healed for ([\d\.,]+)$/, '对手 治疗了 $1 生命值'],
    [/^Opponent hit You for ([\d\.,]+)$/, '对手 攻击了你并造成了 $1 伤害'],
    [/^You hit Opponent for ([\d\.,]+)$/, '你 攻击了 对手 并造成了 $1 伤害'],
    [/^Opponent Dodged!$/, '对手躲开了!'],
    [/^Your Thorns reflected (.+) damage!$/, '你 的荆棘反射了 $1 伤害!'],
    [/^Opponent\'s Thorns reflected (.+) damage!$/, '对手 的荆棘反射了 $1 伤害!'],
    [/^Cost: (.+) SP$/, '成本：$1 技能点'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Level (.+) \/ (.+)$/, '等级 $1 \/ $2'],
    [/^(.+)\/(.+) upgrades$/, '$1\/$2 升级'],
    [/^([\d\.]+) \/ ([\d\.]+) XP$/, '$1 \/ $2 经验值'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();