// ==UserScript==
// @name         Mirage Online Classic 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.1
// @description  网页游戏 Mirage Online Classic (https://play.mirageonlineclassic.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Mirage Online Classic.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://play.mirageonlineclassic.com/interface/icon2x.png
// @license      MIT
// @include      *mirageonlineclassic.com*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/mirage-online-classic-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/mirage-online-classic-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/08/15 19:33
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Mirage Online Classic": "幻影在线经典版",
    "Successfully verified account! You can now login and play Mirage Online Classic!": "账户验证成功！您现在可以登录并玩幻影在线经典版了！",
    "Item Trades:": "物品交易:",
    "Item Trigger": "物品触发器",
    "Item Repair": "物品修理",
    "Item Selling": "物品出售",
    "Item Bank": "物品银行",
    "Item": "物品",
    "Items": "物品",
    "Item:": "物品:",
    "Jitter:": "抖动:",
    "Jump": "跳",
    "Keep Chat Focus:": "保持聊天焦点:",
    "Layer:": "层:",
    "Key": "钥匙",
    "South": "南",
    "Snow": "下雪",
    "Small": "小",
    "Spin:": "转动:",
    "Start": "开始",
    "Spawn": "生成",
    "Task:": "任务:",
    "Tasks:": "任务:",
    "Level DEF:": "防御等级:",
    "Level HP:": "生命值等级:",
    "Level MP:": "法力值等级:",
    "Level:": "等级:",
    "Location:": "位置:",
    "Login": "登录",
    "Loop Music:": "音乐循环播放:",
    "Initializing game client, one moment please...": "正在初始化游戏客户端，请稍等...",
    "MP:": "法力值:",
    "HP:": "生命值:",
    "Move:": "移动:",
    "Name:": "名称:",
    "Player:": "玩家:",
    "Quest:": "任务:",
    "North": "北",
    "OK": "确定",
    "Option": "选项",
    "Pet": "宠物",
    "Play": "开始",
    "Register": "注册",
    "Recover": "恢复",
    "Custom Data:": "自定义数据:",
    "Damage Stat:": "伤害统计:",
    "Death": "死亡",
    "DEF:": "防御:",
    "DEF Gain (per level):": "防御增益（每级）:",
    "Difficulty:": "难度:",
    "Desert": "Desert",
    "Door": "门",
    "Door Close": "关门",
    "Door Open": "开门",
    "East": "东",
    "Email:": "邮箱:",
    "Effect:": "效果:",
    "Password:": "密码:",
    "Equip Drops:": "装备掉落:",
    "Factory": "工厂",
    "Physical Defense": "物理防御",
    "Physical Defense:": "物理防御:",
    "Physical Defense (DEF):": "物理防御 (防御):",
    "Player Die": "玩家死亡",
    "Player Skills": "玩家技能",
    "Player Stats": "玩家属性",
    "Player Trading": "玩家交易",
    "Player Selection:": "玩家选择:",
    "Player Death Drops:": "玩家死亡掉落:",
    "Required Level:": "要求等级:",
    "Resource": "资源",
    "Resources": "资源",
    "Reward:": "奖励:",
    "Resource:": "资源:",
    "Run Reset": "运行重置",
    "Safe": "安全",
    "Shops": "商店",
    "Shop": "商店",
    "Shop Trading": "商店交易",
    "Shop:": "商店:",
    "Show Item Names:": "显示物品名称:",
    "Sign": "登录",
    "Sign in with Discord": "通过 Discord 登录",
    "Skill Experience:": "技能经验:",
    "Sell Value:": "出售价值:",
    "Skill:": "技能:",
    "Skills": "技能",
    "Required Skill Level:": "要求技能等级:",
    "Reward Amount:": "奖励数量:",
    "Reward Item:": "奖励物品:",
    "Run Start": "运行开始",
    "Run Finish": "运行结束",
    "Sell": "出售",
    "Sort Items:": "物品排序:",
    "Repair": "修理",
    "Request:": "请求:",
    "New Pass:": "新密码:",
    "New Player": "新玩家",
    "Death Map:": "死亡地图:",
    "Death Drop:": "死亡掉落:",
    "Death Sound:": "死亡声音:",
    "Cost:": "成本:",
    "Create": "创建",
    "Credits": "鸣谢",
    "Currency": "货币",
    "Darkness %:": "黑暗 %:",
    "Cooldown (secs):": "冷却时间 (秒):",
    "Cooldown Item:": "冷却物品:",
    "Config Editor": "配置编辑器",
    "Color:": "颜色:",
    "Cancel": "取消",
    "Buyable:": "可购买:",
    "Boss:": "Boss:",
    "Confirm:": "确认密码:",
    "Armor": "护甲",
    "Automatic:": "自动化:",
    "Back": "返回",
    "Chance %:": "几率 %:",
    "Change Email": "更改邮箱",
    "Clear": "清除",
    "Confirm Trade": "确认交易",
    "Change Password": "修改密码",
    "Delete Account": "删除账户",
    "Medium": "中",
    "Members:": "成员:",
    "Min DEF:": "最小防御:",
    "Min ATK:": "最小攻击:",
    "Miss": "未命中",
    "Modify": "修改",
    "Modify Account": "修改账户",
    "Multiplier:": "乘数:",
    "Music:": "音乐:",
    "Music volume:": "音乐音量:",
    "Speed (secs):": "速度 (秒):",
    "Start Map:": "开始地图:",
    "WARNING!": "警告!",
    "Welcome": "欢迎",
    "Toggle Run:": "切换运行:",
    "Reward Chance %:": "奖励几率 %:",
    "Repair Items:": "修理物品:",
    "Remove Data": "移除数据",
    "Remove Drop": "移除掉落",
    "Remove Item": "移除物品",
    "Remove Gathering": "移除采集",
    "Recipe Items:": "配方物品:",
    "Recycle Items:": "回收物品:",
    "Recover Account": "恢复账户",
    "New Account": "新账户",
    "New Email:": "新邮箱:",
    "A verification link will be sent to confirm your email.": "将发送一个验证链接以确认您的电子邮件。",
    "Accept Invite": "接受邀请",
    "Accessory": "配饰",
    "Current Inventory:": "当前库存:",
    "Connecting to game server...": "正在连接到游戏服务器...",
    "Passwords do not match! Please re-type your password.": "密码不匹配！请重新输入密码。",
    "Quit": "退出",
    "Repair Cost:": "修理成本:",
    "XP:": "经验值:",
    "Required Professions:": "要求职业:",
    "Type": "类型",
    "Type:": "类型:",
    "Private": "私聊",
    "Privacy Policy": "隐私政策",
    "Max DEF:": "最大物理防御:",
    "Min DEF:": "最小物理防御:",
    "Max ATK:": "最大物理攻击:",
    "Min ATK:": "最小物理攻击:",
    "Max MAT:": "最大魔法攻击:",
    "Min MAT:": "最小魔法攻击:",
    "Max RAT:": "最大远程攻击:",
    "Min RAT:": "最小远程攻击:",
    "Max RDF:": "最大远程防御:",
    "Min RDF:": "最小远程防御:",
    "Max MDF:": "最大魔法防御:",
    "Min MDF:": "最小魔法防御:",
    "Max HP:": "最大生命值:",
    "Max MP:": "最大法力值:",
    "Max SP:": "最大耐力值:",
    "Min SP:": "最小耐力值:",
    "MDF:": "魔法防御:",
    "MAT:": "魔法攻击:",
    "MOC": "幻影在线经典版",
    "Mirage Online Classic is a remake of the 2001 classic MMORPG Mirage Online using modern web technology and\n            originally inspired by Odyssey Online Classic. It is dedicated to the late Joe Buchanan (Plazmic) and\n            Brandon Sullwold (Darksoul).": "幻影在线经典是2001年经典MMORPG幻影在线使用现代网络技术和\n最初的灵感来自奥德赛在线经典的翻拍。它是献给已故的乔·布坎南（Plazmic）和布兰登·苏沃尔德（Darksoul）。",
    "Large": "大",
    "Invite Member": "邀请成员",
    "Cast": "施放",
    "Add\n            Battle": "增加战斗",
    "Add\n            Ingredient": "增加成分",
    "Patreon Founders: Official, Harley, Zach Ross (XrawrX), Nathan Page (Kronik), Taylor Mitchell (Diabolic),\n            James Ryan (Samurai), camcard, Danny_VVolf, Sephiria, and Matthew Cordero (Broku)": "Patreon创始人：Official, Harley, Zach Ross (XrawrX), Nathan Page (Kronik), Taylor Mitchell (Diabolic),\n            James Ryan (Samurai), camcard, Danny_VVolf, Sephiria, and Matthew Cordero (Broku)",
    "Musical Artists: syncopika, Joseph Gilbert, Bogart VGM, Ted Kerr, Brandon Morris, Alexandr Zhelanov, Johan\n            Brodd, Otto Halmén, remaxim, mrpoly, RandomMind, Philippe Groarke, Matthew Pablo, yd, Muncheybobo, TAD,\n            Cleyton Kauffman, Peter Eastman, Alex McCulloch, and Steven Jones": "音乐艺术家：syncopika, Joseph Gilbert, Bogart VGM, Ted Kerr, Brandon Morris, Alexandr Zhelanov, Johan\n            Brodd, Otto Halmén, remaxim, mrpoly, RandomMind, Philippe Groarke, Matthew Pablo, yd, Muncheybobo, TAD,\n            Cleyton Kauffman, Peter Eastman, Alex McCulloch, and Steven Jones",
    "Special Thanks: Andrew Wheeler (Genusis), Brady O'Keefe (Bradyok), Justin Schumacher (Bugaboo), Kyle Graham\n            (Inde), Todd Klasik (BoinKlasik), and William Heller (BlargusJones)": "特别感谢: Andrew Wheeler (Genusis), Brady O'Keefe (Bradyok), Justin Schumacher (Bugaboo), Kyle Graham\n            (Inde), Todd Klasik (BoinKlasik), and William Heller (BlargusJones)",
    "Weapon": "武器",
    "West": "西",
    "Two-handed:": "双手:",
    "Treasure:": "宝藏",
    "Trap Trigger": "陷阱触发",
    "Trap": "陷阱",
    "Trade": "交易",
    "Trade-": "交易-",
    "Trade+": "交易+",
    "Tiles West:": "地块西边:",
    "Tiles South:": "地块南边:",
    "Tiles East:": "地块东边:",
    "Tiles North:": "地块北边:",
    "Tiles Range:": "地块范围:",
    "Tiles Type": "地块类型",
    "Invalid verification code or account is already verified. You can login to have your verification link sent via email again.": "无效的验证码或帐户已验证。您可以登录以再次通过电子邮件发送验证链接。",
    "This action will delete your account permanently!": "此操作将永久删除您的帐户！",
    "If an account exists for email you provide you'll soon get an email with additional instructions.": "如果您提供的电子邮件存在一个帐户，您将很快收到一封带有附加说明的电子邮件。",
    "Create\n              Guild": "创建公会",
    "Creating new player...": "创建新玩家...",
    "Player Avoid": "玩家避开",
    "Player Guilds": "玩家公会",
    "Player Selection": "玩家选择",
    "Remove": "移除",
    "Receiving game data...": "接收游戏数据...",
    "Remove\n            Battle": "移除战斗",
    "Remove\n            NPC": "移除NPC",
    "Remove\n            Task": "移除任务",
    "Remove Member": "移除成员",
    "Welcome to Mirage Online Classic!": "欢迎来到 幻影在线经典版",
    "Welcome to Mirage Online Classic Release Build 2025.11 developed by yours truly, Consty and Rich!": "欢迎来到幻影在线经典版本Build 2025.11，由你的 truly, Consty and Rich开发！",
    "Success! Please proceed to login with the new password you used.": "成功!请使用您使用的新密码登录。",
    "Show Name:": "显示名称:",
    "Terms of Service": "服务条款",
    "Tag:": "标签:",
    "Your Idling skill has increased!": "你的挂机技能提升了！",
    "Your connection was lost. Attempting to reconnect...": "你的连接中断了。尝试重新连接...",
    "Local": "本地",
    "Gender:": "性别:",
    "Stamina Points (SP):": "耐力点数 (SP):",
    "SP Gain (per level):": "耐力点数(SP) 增益 (每级):",
    "Rotation (angle):": "旋转 (角度):",
    "Ranged Defense (RDF):": "远程防御 (RDF):",
    "Ranged Defense": "远程防御",
    "Ranged Defense:": "远程防御:",
    "RAT Gain (per level):": "远程攻击(RAT) 增益 (每级):",
    "Ranged Damage Reduction %:": "远程伤害减免 %:",
    "Ranged Attack:": "远程攻击:",
    "Ranged Attack": "远程攻击",
    "Ranged Attack (RAT):": "远程攻击 (RAT):",
    "Rain": "下雨",
    "Radius": "半径",
    "Physical Attack": "物理攻击",
    "Physical Attack:": "物理攻击:",
    "Physical Attack (ATK):": "物理攻击 (ATK):",
    "Press Delay (secs):": "按下延时（秒）:",
    "Overworld": "上界",
    "Overworld:": "上界:",
    "Offset": "偏移",
    "NPCs:": "NPCs:",
    "NPC:": "NPC:",
    "Chest:": "宝箱:",
    "NPC": "NPC",
    "NPCs": "NPC",
    "NOTICE!": "注意!",
    "NPC Trigger": "NPC触发",
    "NPC Die": "NPC死亡",
    "NPC Avoid": "NPC避开",
    "Pay\n              Balance": "支付余额",
    "Open HP:": "打开生命值:",
    "Open Item:": "打开物品:",
    "Open Owner:": "打开拥有者:",
    "Open Delay (secs):": "打开延迟 (秒):",
    "Pixel Artists: Greg Dorando (Archbane), Judy Shmidt (Gecky), Vivi, Mousey, Rich, timbojay, GoombaPerron,\n            MikAnimus, Elthen, Necrodeus, Harley, and Bear": "像素艺术家: Greg Dorando (Archbane), Judy Shmidt (Gecky), Vivi, Mousey, Rich, timbojay, GoombaPerron,\n            MikAnimus, Elthen, Necrodeus, Harley, and Bear",
    "Close": "关闭",
    "Drop Amount:": "掉落数量:",
    "Drop Item:": "掉落物品:",
    "Drop Items:": "掉落物品:",
    "Drop Chance %:": "掉率 %:",
    "Drop Chance Max %:": "掉率上限 %:",
    "Filter Chat Badwords:": "过滤聊天恶语：",
    "Type /help to see available commands.": "输入 /help 以查看可用命令.",
    "Did you know you can view any map in game by clicking the map icon in the top right corner of the game screen?": "你知道吗，只要点击游戏界面右上角的地图图标，就可以查看游戏内的任意地图。",
    "Give Amount:": "给出数量:",
    "Give Item:": "给出物品:",
    "Global": "全局",
    "Ground": "土地",
    "Gather Items:": "采集物品:",
    "Gather Item:": "采集物品:",
    "Gather Chance %:": "采集几率 %:",
    "Group": "队伍",
    "Group Battle:": "组队战斗:",
    "<p>Mirage Online Classic requires JavaScript to play! Please allow JavaScript and reload this page.</p>": "<p>幻影在线经典需要JavaScript来玩！请允许使用JavaScript并重新加载此页面。</p>",
    "Acronym:": "缩写：",
    "Add Data": "添加数据",
    "Add Drop": "添加掉落",
    "Add Gathering": "添加采集",
    "Add Item": "添加物品",
    "Add NPC": "添加NPC",
    "Add Task": "添加任务",
    "Advanced": "高级",
    "Aggro Avoid": "避免滋扰",
    "All rights reserved.": "版权所有。",
    "Allow Melee:": "允许近战：",
    "Alpha:": "首领：",
    "Amount:": "金额：",
    "Anim Delay (ms):": "动画延迟（毫秒）：",
    "Anim2 Delay (ms):": "Anim2延迟（毫秒）：",
    "Arena": "竞技场",
    "Assassin": "刺客",
    "ATK Gain (per level):": "攻击力增益（每级）：",
    "ATK:": "攻击：",
    "Attack Delay %:": "攻击延迟%：",
    "Attack On Sight": "瞄准攻击",
    "Attack Say:": "攻击说:",
    "Attack Sound:": "攻击声音：",
    "Attack When Attacked": "被攻击时攻击",
    "Auto Reconnect:": "自动重新连接:",
    "Balance Due:": "应付余额：",
    "Balance Log:": "余额日志：",
    "Balance:": "余额：",
    "Balanced Level:": "平衡等级：",
    "Bank": "银行",
    "Bank Inventory:": "银行库存:",
    "Bank Items:": "银行物品:",
    "Bank:": "银行:",
    "Barbarian": "野蛮人",
    "Bard": "吟游诗人",
    "Battle Chance:": "战斗几率：",
    "Battle Map:": "战斗地图:",
    "Battle Maps:": "战斗地图:",
    "Battle Royale": "大逃杀",
    "Battle Steps:": "战斗步骤：",
    "Battle:": "战斗:",
    "Battles": "战斗",
    "Beginner": "新手",
    "Behavior:": "行为:",
    "Bind Respawn": "绑定复活",
    "Block from East:": "东边地块：",
    "Block from North:": "北边地块：",
    "Block from South:": "南边地块：",
    "Block from West:": "西边地块：",
    "Block Ranged:": "地块范围：",
    "Block to East:": "地块向东：",
    "Block to North:": "地块向北：",
    "Block to South:": "地块向南：",
    "Block to West:": "地块向西：",
    "Blocked": "受阻",
    "Blocked Dir": "阻塞目录",
    "Blocked:": "阻塞：",
    "Boot": "引导",
    "Boot Map:": "引导地图：",
    "Break Chance:": "打破几率：",
    "Brightness %:": "亮度%：",
    "Buy Hall": "购买大厅",
    "Challenging": "挑战",
    "Chest:": "宝箱：",
    "Cleric": "牧师",
    "Closest": "最接近",
    "Clung": "紧紧抓住",
    "Content Contributors: Harley, Gawain, XrawrX, bimpson and Poseidon": "内容贡献者：Harley， Gawain, XrawrX， simpson和Poseidon",
    "Copyright © 2020-2025 Retrelon Games, LLC.": "版权所有©Retrelon Games， LLC",
    "Create\n              Guild": "创建公会",
    "Death Penalty:": "死刑:",
    "Death Say:": "死亡说:",
    "Declarations:": "声明:",
    "Delinquent:": "违约:",
    "Deposit": "存款",
    "Description:": "描述:",
    "Developers: Christopher Kremer (Consty) and Rich Conner (Rich)": "开发商：Christopher Kremer （Consty）和Rich Conner （Rich）",
    "Direction:": "方向:",
    "Disable GvG:": "禁用GvG:",
    "Door Switch": "门开关",
    "Door Trigger": "门触发器",
    "Dragoon": "龙骑士",
    "Dungeons": "地下城",
    "Environment Darkness Step %:": "环境黑暗步骤%：",
    "Environment Max Darkness %:": "环境最大黑暗%：",
    "Experience:": "经验:",
    "Female": "女",
    "Female Alpha:": "女首领：",
    "Female Brightness %:": "女性亮度%：",
    "Female Hue:": "女性肤色：",
    "Female Saturation %:": "女性饱和度%：",
    "Female Sprite:": "女精灵:",
    "Female Visual:": "女性视觉:",
    "Festival": "节日",
    "Fill": "填充",
    "Flee Threshold %:": "逃离阈值%:",
    "Flicker:": "闪烁:",
    "Flip Game Screen:": "翻转游戏画面：",
    "Male": "男",
    "Say-": "说话-",
    "Say+": "说话+",
    "Say:": "说话:",
    "Say": "说话",
    "Says:": "说话:",
    "Shield": "盾牌",
    "SP:": "耐力值:",
    "Soldier": "士兵",
    "Toggle Profession": "切换职业",
    "Timestamp Chat:": "时间戳聊天:",
    "Fog": "迷雾",
    "Font Size:": "字体大小:",
    "Forbid Attack:": "禁止攻击:",
    "Forbid Lights:": "禁止灯光：",
    "Forbid Magical:": "禁止魔法:",
    "Forbid NPC Map Switch:": "禁止NPC地图切换：",
    "Forbid Ranged:": "禁止远程：",
    "Forest": "森林",
    "Founder": "创始人",
    "Friendly": "友好",
    "Friendly Fire:": "友军火力：",
    "Fringe": "流苏",
    "Fringe 2": "流苏2",
    "Fringe 2 Anim": "流苏2动画",
    "Fringe Anim": "流苏动画",
    "Gambling 1": "赌博1",
    "Guard": "守卫",
    "Guild": "公会",
    "Guild\n              Halls": "公会大厅",
    "Guild Halls": "公会大厅",
    "Guild Rank:": "公会排名：",
    "Guild Upkeep (per week per player):": "公会维护（每名玩家每周）：",
    "GvG": "GvG",
    "Hall Cost (per map):": "大厅费用（每张地图）：",
    "Hall Upkeep (per week per map):": "大厅维护（每周每张地图）：",
    "Hall:": "大厅:",
    "Harm": "伤害",
    "Helmet": "头盔",
    "Highest HP": "最高生命",
    "Highest Level": "最高等级",
    "Hit": "命中",
    "Hit Points (HP):": "生命值（HP）：",
    "Hit Points:": "生命值:",
    "Hit Sign": "命中符号",
    "Hostility:": "敌意:",
    "HP Gain (per level):": "生命增益（每级）：",
    "Hue:": "色相：",
    "Huge": "巨大",
    "Ignore Chat Channels:": "忽略聊天频道：",
    "Indoors:": "室内:",
    "Ingredient Amount:": "原料数量:",
    "Ingredient Item:": "配料项目：",
    "Inn": "客栈",
    "Insane": "疯狂",
    "Interface Artists: Jess Triska (Trideka) and Jason Perry (Finalbossblues)": "界面美工：Jess Triska （Trideka）和Jason Perry （finalbosssblues）",
    "Inventory Limit:": "库存限制:",
    "Inventory:": "库存:",
    "Inverted (up right-to-left):": "倒置（从右到左向上）：",
    "Jester": "小丑",
    "Join Say:": "加入说：",
    "Kill Verb:": "杀死动词:",
    "Last Hit": "最后一击",
    "Least Damage": "伤害最小",
    "Least Hits": "最少命中",
    "Leave Hall": "离开大厅",
    "Leave Say:": "离开说:",
    "Level ATK:": "等级攻击：",
    "Level Change Interval:": "等级转换间隔：",
    "Level HP Change %:": "等级生命变化%：",
    "Level MAT:": "等级魔法攻击:",
    "Level MDF:": "等级魔法防御:",
    "Level MP Change %:": "等级魔力值变化%：",
    "Level RAT:": "等级远程攻击:",
    "Level RDF:": "等级远程防御:",
    "Level SP Change %:": "等级耐力值变化%：",
    "Level SP:": "等级耐力值：",
    "Light": "灯光",
    "Local": "本地",
    "Lock East:": "东边锁定：",
    "Lock North:": "北边锁定：",
    "Lock South:": "南边锁定：",
    "Lock West:": "西边锁定：",
    "Lowest HP": "最低生命值",
    "Lowest Level": "最低等级",
    "Lumber": "木材",
    "Magic Points (MP):": "魔法点数（MP）：",
    "Magical Attack": "魔法攻击",
    "Magical Attack (MAT):": "魔法攻击（MAT）：",
    "Magical Attack:": "魔法攻击:",
    "Magical Defense": "魔法防御",
    "Magical Defense (MDF):": "魔法防御（MDF）：",
    "Magical Defense:": "魔法防御:",
    "Magical Points:": "魔法点数：",
    "Male Alpha:": "男首领：",
    "Male Brightness %:": "男性亮度%：",
    "Male Hue:": "男性色调:",
    "Male Saturation %:": "男性饱和度%：",
    "Male Sprite:": "男性精灵:",
    "Male Visual:": "男性视觉:",
    "Map East:": "地图:",
    "Map Editor": "映射编辑器",
    "Map North:": "地图北:",
    "Map Properties": "地图属性",
    "Map Shift": "地图移位",
    "Map Sign": "地图标志",
    "Map South:": "地图南:",
    "Map Switch Radius:": "地图切换半径：",
    "Map West:": "地图西：",
    "Map:": "地图:",
    "Marksman": "神射手",
    "Mask": "面具",
    "Mask 2": "面具2",
    "Mask 2 Anim": "面具2动物",
    "Mask Anim": "面具动物",
    "MAT Gain (per level):": "MAT增益（每级）：",
    "Max Guild Sprite:": "最大公会精灵：",
    "Max IP Logins:": "最大IP登录数：",
    "MDF Gain (per level):": "MDF增益（每级）：",
    "Migrated:": "迁移:",
    "Mine": "矿洞",
    "Mirrored:": "镜像:",
    "Moderators: Harley, Gawain, and Corcoran": "主持人：Harley， Gawain和Corcoran",
    "Moral:": "寓意：",
    "Most Damage": "最大伤害",
    "Most Hits": "最大命中",
    "Movement Amount:": "运动数量:",
    "Movement Chance %:": "移动几率%：",
    "Movement Delay %:": "移动延迟%：",
    "MP Gain (per level):": "法力值增益（每级）：",
    "Necromancer": "死灵法师",
    "Number of Uses:": "使用数量:",
    "Officer": "军官",
    "Open Neighbors:": "打开邻居：",
    "Owner: Retrelon Games, LLC": "所有者：Retrelon Games， LLC",
    "Play Environment Sounds:": "播放环境声音：",
    "Play Transition Sounds:": "播放过渡音：",
    "Player Flee Health %:": "玩家逃离生命%：",
    "Player Guilds": "玩家公会",
    "Player Housing:": "玩家住房：",
    "Player Selection": "玩家选择",
    "Potion": "药水",
    "Pressure Plate": "压力板",
    "Profession:": "职业：",
    "Professions": "职业",
    "Projectile": "投射物",
    "Prompt": "提示符",
    "Props": "支柱",
    "Protect NPCs:": "保护Npc:",
    "Pursue Run:": "追求运行:",
    "Quicksand": "流沙",
    "Ranged Alpha:": "远程首领：",
    "Ranged Brightness %:": "远程亮度%：",
    "Ranged Hue:": "远程色调:",
    "Ranged Saturation %:": "远程饱和%：",
    "Ranged Scale:": "远程比例：",
    "Ranged Sprite:": "远程精灵：",
    "RAT:": "远程攻击:",
    "RDF Gain (per level):": "远程防御增益（每级）：",
    "RDF:": "远程防御:",
    "Rebind\n              Gamepad": "重新绑定手柄",
    "Rebind Keys": "重新绑定按键",
    "Recipe": "配方",
    "Reg Code:": "注册代码:",
    "Regen HP Change %:": "回复生命变化%：",
    "Regen MP Change %:": "回复法力值变化%：",
    "Regen Rate %:": "回复率%：",
    "Regen SP Change %:": "回复耐力值变化%：",
    "Remove\n            Ingredient": "去除成分",
    "Repair\n              All": "修理全部",
    "Repair Cost:": "维修费用:",
    "Replenish Delay:": "补给延迟：",
    "Required Professions:": "所需专业:",
    "Respawn Delay (secs):": "重生延迟（秒）：",
    "Revision:": "修订:",
    "Roof": "屋顶",
    "Safe Combat": "安全战斗",
    "Samurai": "武士",
    "Saturation %:": "饱和%:",
    "Scale:": "比例：",
    "Script Editor": "脚本编辑器",
    "Scripting:": "脚本:",
    "Selectable:": "可选择：",
    "Shop Tile": "商店地块",
    "Shot": "射击",
    "Show Moral Text:": "展示道德文本：",
    "Show Name:": "显示名称:",
    "Show NPC Names:": "显示NPC名称：",
    "Show Player Names:": "显示玩家姓名：",
    "Show Speedrun Timer:": "显示速跑计时器：",
    "Show Target Vitals:": "显示目标生命指标：",
    "Show Weather:": "显示天气:",
    "Sight Range:": "视线范围:",
    "Sign:": "标志:",
    "Skill Level Chance %:": "技能等级几率%：",
    "Skills /\n              Abilities": "技能/能力",
    "Slapish": "草率",
    "Slice": "切片",
    "Slide Ice": "滑冰",
    "Snipe": "狙击",
    "Sound volume:": "音量:",
    "Spawn Avoid": "避免刷出",
    "Spawn Day:": "刷出日：",
    "Spawn Direction:": "刷出方向：",
    "Spawn Night:": "刷出之夜：",
    "Spawn NPC:": "刷出NPC：",
    "Spawn Weather:": "出生天气：",
    "Splish": "飞溅",
    "Split": "分裂",
    "Spooky": "令人毛骨悚然",
    "Sprite Rotation:": "精灵旋转：",
    "Sprite:": "精灵:",
    "Stagger": "摇摇晃晃",
    "Staircase": "楼梯",
    "Stamina Points:": "耐力点:",
    "Swap Sprite": "切换精灵",
    "Swarm": "蜂群",
    "Swish": "嗖嗖",
    "Swoosh": "嗖",
    "Take Amount:": "取出数量：",
    "Take Item:": "取出物品：",
    "Target Cycle NPCs:": "目标周期Npc：",
    "Target Cycle Players:": "目标周期玩家：",
    "Targeting:": "目标:",
    "Temp Chat Size:": "临时聊天大小：",
    "Temp:": "温度:",
    "Their Offer:": "他们的报价:",
    "Thud": "砰",
    "Tileset:": "地块组：",
    "Tiny": "微小",
    "Title": "称号",
    "Toggle\n              Reviewed": "切换\n审阅",
    "Toggle Declaration": "切换声明",
    "Toggle Hostility": "切换敌对状态",
    "Toggle Movement:": "切换移动：",
    "Toggle Rank": "切换排名",
    "Transferable:": "可转让：",
    "Trigger Cooldown (secs):": "触发冷却（秒）：",
    "Upkeep:": "维护：",
    "Vampire": "吸血鬼",
    "Visual:": "视觉:",
    "Walk": "走路",
    "Walk Sign": "行走标志",
    "Walkable": "可行走",
    "Warlock": "术士",
    "Warp": "扭曲",
    "Warp Map:": "扭曲地图：",
    "Weather:": "天气:",
    "Wipe": "擦除",
    "Withdraw": "取出",
    "Your connection was lost. Attempting to reconnect...": "你的连接中断了。试图重新连接…",
    "Your Offer:": "你的报价:",
    "Join our Discord by clicking the icon in the upper right or visit https://discord.com/invite/eZGSS9s.": "通过点击右上角的图标加入我们的 Discord 或访问 https://discord.com/invite/eZGSS9s.",
    "Tile Range:": "地块范围:",
    "Tile Type": "地块类型",
    "🏆 Leaderboard": "🏆 排行榜",
    "🐲 Other": "🐲 其它",
    "👹 Dungeons": "👹 地下城",
    "⚡ Today's High Concurrent Player Count:": "⚡ 今日最高在线人数：",
    "👨‍👦‍👦 Guild": "👨‍👦‍👦 公会",
    "🧔 Player": "🧔 玩家",
    "🧔 Player Menu Home": "🧔 玩家菜单首页",
    "Leaderboard": "排行榜",
    "Main Menu": "主菜单",
    "Moderators Online:": "在线版主：",
    "⌚ Speedruns": "⌚ 速跑",
    "⛏ Skills": "⛏ 技能",
    "🏅 Top Overall": "🏅 整体排名",
    "👨‍👦‍👦 Guild Menu Home": "👨‍👦‍👦 公会菜单首页",
    "💔 Player PvP": "💔 玩家 PvP",
    "💼 Missions": "💼 任务",
    "🔑 Completions": "🔑 完成",
    "🤖 Player Level": "🤖 玩家等级",
    "🦴 Monster Kills": "🦴 怪物击杀",
    "Abilities": "能力",
    "Skills or Abilities?": "技能 或 能力?",
    "Customize your Character": "自定义你的角色",
    "Lost Necklace has been hidden by a Giant Scorpion": "丢失的项链被一只大蝎子藏了起来",
    "Select how your boat looks": "选择你的船的外观",
    "Set auto usage settings": "应用自动使用设置",
    "Boat Visual": "船的视觉",
    "Boat Visual:": "船的视觉:",
    "Counterattack and apply damage overtime to your foe by interacting with yourself.": "通过与自己的互动进行反击，对敌人造成额外伤害。",
    "Samurai Ability:": "武士能力：",
    "Character Customization": "角色自定义",
    "Visit our Patreon page by clicking on the icon in the upper right or visit https://www.patreon.com/mirageonlineclassic.": "点击右上方的图标访问我们的 Patreon 页面或访问 https://www.patreon.com/mirageonlineclassic。",
    "No other items are used.": "没有使用其他物品。",
    "Off": "关闭",
    "Off:": "关闭:",
    "Potion Auto Usage Settings": "药水自动使用设置",
    "If in your inventory and off cooldown, when would you like to use a potion?": "如果在你的库存中并且没有冷却时间，你想在什么时候使用药水？",
    "Auto potion usage disabled": "禁用自动药水使用",
    "Unfound Ring has been hidden by a Nocturnal Visitor": "未被发现的戒指被一个夜间访客藏了起来",
    "Two-handed weapon": "双手武器",
    "Player Info": "玩家信息",
    "Dark Cave": "黑暗洞穴",
    "Dungeon Crawlers": "地下城爬行者",
    "Dungeon Completions": "地下城完成",
    "Disenchant": "祛魅",
    "Found in a one time chest on tutorial island! [ 5% Break chance upon repair ]": "在教学岛的一次性宝箱中发现！[修理时5%破裂几率]",
    "Fort Darkcone": "黑暗锥堡",
    "Hidden": "隐藏",
    "is controlled by": "受控于",
    "Novice Staff": "新手杖",
    "Attack, run & loot": "攻击，奔跑和掠夺",
    "Baby Grizzly": "灰熊宝宝",
    "Item Drops": "物品掉落",
    "Lost Necklace has been hidden by a Even-Bigger Scorpion": "失落的项链被一只更大的蝎子藏起来了",
    "Hidden Lair of the Norax": "诺拉克斯的秘密巢穴",
    "Into the Haunted House": "进入鬼屋",
    "Lord Confuzog": "孔夫佐格大人",
    "Merlock's Maze": "默洛克迷宫",
    "Nightmare Garden of the Wanderer": "流浪者的噩梦花园",
    "Nightmare Haunted House": "噩梦鬼屋",
    "Hall of Heroes": "英雄大厅",
    "Northcoast Lockdown": "北海岸封锁",
    "Learning Hatchet": "学习短斧",
    "Physical Weapon": "物理武器",
    "Droppable upon death": "死亡后掉落",
    "Your Lumberjacking skill has increased!": "你的 伐木 技能升级了！",
    "Underworld of the Sewers": "下水道的地下世界",
    "Venture through the maze": "在迷宫中冒险",
    "Type /event for details": "输入 /event 查看详情",
    "Do you want to destroy this non-transferable item?": "你想销毁这个不可转让的物品吗？",
    "Drop Item": "丢弃物品",
    "Samurai, Cleric, Assassin, Barbarian, Necromancer, Bard, Dragoon, Jester": "武士，牧师，刺客，野蛮人，死灵法师，吟游诗人，龙骑士，小丑",
    "Cleric, Marksman, Necromancer, Bard, Dragoon, Jester": "牧师，射手，死灵法师，吟游诗人，龙骑士，小丑",
    "Warlock, Cleric, Necromancer, Bard, Dragoon, Jester": "术士，牧师，死灵法师，吟游诗人，龙骑士，小丑",
    "Use to carve into useful parts.": "用来雕刻成有用的部分。",
    "Walk in the Cemetery": "墓园漫步",
    "Please consider using the Steam client if you are idling!": "如果您处于挂机状态，请考虑使用Steam客户端！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "/pvp": "/pvp",
    "TP:": "TP:",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "Y:": "Y:",
    "X:": "X:",
    "PvP": "PvP",
    "↑": "↑",
    "↓": "↓",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Players Online ": "在线玩家 ",
    "Auto potion usage when HP is less than ": "自动使用药水当生命值低于 ",
    "Player Menu - ": "玩家菜单 - ",
    "Range Damage:  ": "远程伤害:  ",
    "Magic DMG:  ": "魔法伤害:  ",
    "Magic DEF:  ": "魔法防御:  ",
    "Magic Damage:  ": "魔法伤害:  ",
    "Health:  ": "生命值:  ",
    "Profession:  ": "职业:  ",
    "Stamina:  ": "耐力:  ",
    "Name:  ": "名称:  ",
    "Range DEF:  ": "远程防御:  ",
    "Range DMG:  ": "远程伤害:  ",
    "Physical DMG:  ": "物理伤害:  ",
    "Physical DEF:  ": "物理防御:  ",
    "Professions: ": "职业: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " X:": " X:",
    " Y:": " Y:",
    " X (tiles):": " X (地块):",
    " Y (tiles):": " Y (地块):",
    "Elixir of Pronounced Life is used then Potion of Cavalier Health. ": "使用生命长生不老药，然后使用骑士生命药水。",
    "x Potion of Cavalier Health [50%]": "x 骑士生命药水 [50%]",
    "x Potion of Mana Restoration [50%]": "x 法力恢复药水 [50%]",
    "x Potion of Restored Vivacity [50%]": "x 活力恢复药水 [50%]",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.,]+) \/ ([\d\.,]+) \(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Level (.+) Drops PvP Event$/, '等级 $1 掉落 PvP 事件'],
    [/^Player (.+) was successfully created!$/, '玩家 $1 创建成功！'],
    [/^An email has been sent to (.+) for verification. Please check your inbox\/spam for additional instructions.$/, '已发送电子邮件至 $1 进行验证。请查看您的收件箱/垃圾邮件以获取更多说明。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) to ([\d\.,]+) magical attack$/, '+$1 - $2 魔法攻击'],
    [/^\+([\d\.,]+) to ([\d\.,]+) ranged attack$/, '+$1 - $2 远程攻击'],
    [/^\+([\d\.,]+) to ([\d\.,]+) physical attack$/, '+$1 - $2 物理攻击'],
    [/^\+([\d\.,]+) ranged defense$/, '+$1 远程防御'],
    [/^\+([\d\.,]+) magical defense$/, '+$1 魔法防御'],
    [/^\+([\d\.,]+) physical defense$/, '+$1 物理防御'],
    [/^\+([\d\.,]+) stamina points$/, '+$1 耐力点数'],
    [/^\+([\d\.,]+) hit points$/, '+$1 命中点数'],
    [/^\+([\d\.,]+) magic points$/, '+$1 魔法点数'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) inventory limit$/, '$1 库存上限'],
    [/^([\d\.,]+)s cooldown$/, '$1 秒 冷却时间'],
    [/^Town ([\d\.,]+)$/, '小镇 $1'],
    [/^tiles ([\d\.,]+)$/, '地块 $1'],
    [/^tiles([\d\.,]+)$/, '地块 $1'],
    [/^Sea ([\d\.,]+)$/, '海洋 $1'],
    [/^Victorious ([\d\.,]+)$/, '胜利 $1'],
    [/^Ere ([\d\.,]+)$/, '之前 $1'],
    [/^Castle ([\d\.,]+)$/, '城堡 $1'],
    [/^Mysterious ([\d\.,]+)$/, '神秘 $1'],
    [/^Sadness ([\d\.,]+)$/, '悲伤 $1'],
    [/^Suspenseful ([\d\.,]+)$/, '悬疑 $1'],
    [/^Cave ([\d\.,]+)$/, '洞穴 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Hunting \(([\d\.,]+)\):$/, '狩猎 ($1):'],
    [/^Idling \(([\d\.,]+)\):$/, '挂机 ($1):'],
    [/^Weaving \(([\d\.,]+)\):$/, '编织 ($1):'],
    [/^Turn Hitting \(([\d\.,]+)\):$/, '回合命中 ($1):'],
    [/^Scavenging \(([\d\.,]+)\):$/, '拾荒 ($1):'],
    [/^Woodworking \(([\d\.,]+)\):$/, '木头加工 ($1):'],
    [/^Gathering \(([\d\.,]+)\):$/, '采集 ($1):'],
    [/^Cooking \(([\d\.,]+)\):$/, '烹饪 ($1):'],
    [/^Crafting \(([\d\.,]+)\):$/, '制作 ($1):'],
    [/^Adventurer \(([\d\.,]+)\):$/, '冒险家 ($1):'],
    [/^Alchemy \(([\d\.,]+)\):$/, '炼金 ($1):'],
    [/^Bravery \(([\d\.,]+)\):$/, '勇敢 ($1):'],
    [/^Slaying \(([\d\.,]+)\):$/, '杀戮 ($1):'],
    [/^Prospecting \(([\d\.,]+)\):$/, '勘探 ($1):'],
    [/^Lumberjacking \(([\d\.,]+)\):$/, '伐木 ($1):'],
    [/^Enchanting \(([\d\.,]+)\):$/, '附魔 ($1):'],
    [/^Forging \(([\d\.,]+)\):$/, '锻造 ($1):'],
    [/^Fishing \(([\d\.,]+)\):$/, '钓鱼 ($1):'],
    [/^Gold Coins \(x([\d\.,]+)\)$/, '金币 (x$1)'],
    [/^Potion of Cavalier Health \(x([\d\.,]+)\)$/, '骑士生命药水 (x$1)'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) has been killed by a (.+).$/, '$1 被一个 $2 杀死了。'],
    [/^(.+) has been smashed by a (.+).$/, '$1 被一个 $2 粉碎了。'],
    [/^(.+) has achieved level ([\d\.,]+)!$/, '$1 达到了等级 $2!'],
    [/^(.+) has achieved Gathering level ([\d\.,]+)!$/, '$1 达到了 采集 等级 $2!'],
    [/^(.+) has achieved Turn Hitting level ([\d\.,]+)!$/, '$1 达到了 回合命中 等级 $2!'],
    [/^(.+) has achieved Weaving level ([\d\.,]+)!$/, '$1 达到了 编织 等级 $2!'],
    [/^(.+) has achieved Cooking level ([\d\.,]+)!$/, '$1 达到了 烹饪 等级 $2!'],
    [/^(.+) has achieved Scavenging level ([\d\.,]+)!$/, '$1 达到了 拾荒 等级 $2!'],
    [/^(.+) has achieved Adventurer level ([\d\.,]+)!$/, '$1 达到了 冒险家 等级 $2!'],
    [/^(.+) has achieved Alchemy level ([\d\.,]+)!$/, '$1 达到了 炼金 等级 $2!'],
    [/^(.+) has achieved Lumberjacking level ([\d\.,]+)!$/, '$1 达到了 伐木 等级 $2!'],
    [/^(.+) has achieved Fishing level ([\d\.,]+)!$/, '$1 达到了 钓鱼 等级 $2!'],
    [/^(.+) has achieved Slaying level ([\d\.,]+)!$/, '$1 达到了 杀戮 等级 $2!'],
    [/^(.+) has achieved Woodworking level ([\d\.,]+)!$/, '$1 达到了 木头加工 等级 $2!'],
    [/^(.+) has achieved Crafting level ([\d\.,]+)!$/, '$1 达到了 制作 等级 $2!'],
    [/^(.+) has achieved Forging level ([\d\.,]+)!$/, '$1 达到了 锻造 等级 $2!'],
    [/^(.+) has achieved Prospecting level ([\d\.,]+)!$/, '$1 达到了 勘探 等级 $2!'],
    [/^(.+) has achieved Idling level ([\d\.,]+)!$/, '$1 达到了 挂机 等级 $2!'],
    [/^(.+) has achieved Bravery level ([\d\.,]+)!$/, '$1 达到了 勇敢 等级 $2!'],
    [/^(.+) online players! A new high count for the day!$/, '$1 在线玩家! 创下了今天的新高！'],
    [/^(.+) has left!$/, '$1 离开了!'],
    [/^(.+) class changed to become a Marksman!$/, '$1 转职变成了 神射手 ！'],
    [/^(.+) class changed to become a Vampire!$/, '$1 转职变成了 吸血鬼 ！'],
    [/^A new player has logged online!$/, '一个新玩家登录上线了'],
    [/^A player has logged online!$/, '一个新玩家登录上线了'],
    [/^(.+) paid (.+) Gold Coins.$/, '$1 付了 $2 金币。'],
    [/^(.+) has won Capture Square!$/, '$1 赢得了捕获广场!'],
    [/^(.+) has logged online!$/, '$1 登录上线了！'],
    [/^(.+) Level ([\d\.,]+) Samurai$/, '$1 等级 $2 武士'],
    [/^(.+) has completed a Gatherer Mission for (.+) Experience!$/, '$1 完成了一个 采集 任务，获得 $2 经验值！'],
    [/^(.+) has completed a Gem Mission for (.+) Experience!$/, '$1 完成了一个 宝石 任务，获得 $2 经验值！'],
    [/^(.+) has completed a Skill Mission for (.+) Experience!$/, '$1 完成了一个 技能 任务，获得 $2 经验值！'],
    [/^(.+) has completed a Worm Mission for (.+) Experience!$/, '$1 完成了一个 蠕虫 任务，获得 $2 经验值！'],
    [/^(.+) has completed a Hunting Mission for (.+) Experience!$/, '$1 完成了一个 狩猎 任务，获得 $2 经验值！'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();