// ==UserScript==
// @name         Modern Conflict 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.19
// @description  网页游戏 Modern Conflict (https://modern-conflict.ca/register.php?ref=266a8b5d55) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Modern Conflict.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @license      MIT
// @include      *https://modern-conflict.ca/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/modern-conflict-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/modern-conflict-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/06/15 21:19
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Choose Your Commander Portrait": "选择你的指挥官肖像",
    "Register": "注册",
    "Register New Commander": "注册新指挥官",
    "🚪 Logout": "🚪 登出",
    "Account Verification": "账号验证",
    "Load:": "加载:",
    "Resource": "资源",
    "Research": "研究",
    "Scores": "分数",
    "Support": "支持",
    "Success": "成功",
    "Verification Code": "验证代码",
    "Registration successful! Welcome to Modern Conflict.": "注册成功！欢迎来到现代冲突。",
    "We emailed you a verification code—enter it on your dashboard to verify your account.": "我们通过电子邮件向您发送了验证码，请在仪表板上输入验证码以验证您的帐户。",
    "Pro Tip": "高级提示",
    "Population": "人口",
    "Overview": "概览",
    "Oil": "石油",
    "Oil Systems": "石油系统",
    "Welcome to Modern Conflict": "欢迎来到现代冲突",
    "Money": "金钱",
    "Modern Conflict": "现代冲突",
    "Networth": "净值",
    "Misc": "杂项",
    "Time Remaining": "剩余时间",
    "Manual": "手册",
    "Main": "主界面",
    "Diamonds": "钻石",
    "Defense": "防御",
    "Commander": "指挥官",
    "Commanders": "指挥官",
    "Combat Bonuses": "战斗加成",
    "Cancel": "取消",
    "City Snapshot": "城市快照",
    "Atk Time": "攻击时间",
    "Attack": "攻击",
    "% Bonus": "% 加成",
    "Item / World Effects": "物品 / 世界效果",
    "Items": "物品",
    "Metal": "金属",
    "Military": "军队",
    "Military Barracks": "军营",
    "nit Information": "单位信息",
    "Build Land": "建造土地",
    "Economy": "经济",
    "Anti-Bomber": "反轰炸机",
    "Income & Bonuses": "收入 & 加成",
    "Incoming Attacks": "攻击来袭",
    "Alliance HQ": "联盟总部",
    "Alliance": "联盟",
    "Action": "动作",
    "Admin Notes": "管理员提醒",
    "Map View": "地图视图",
    "Max Population": "最大人口",
    "Land": "土地",
    "Join the official Discord": "加入官方 Discord",
    "Battle Quick View": "战斗快速视图",
    "Peace Treaty (3 Days)": "和平条约 (3天)",
    "+25% Money, Metal, Oil, Population, Survey, and Research production.": "+25%货币，金属，石油，人口，调查和研究生产。",
    "+50% City Defense strength while the bonus lasts.": "持续期间，城防力提升50%。",
    "50% reduction to march times for all outgoing attacks.": "所有外出攻击的行军时间减少50%。",
    "Diamonds Storefront": "钻石商店",
    "Enjoy accelerated growth while your settlement establishes itself.": "享受加速增长，同时你的定居点建立自己。",
    "Enter the code sent to your email to complete verification.": "输入发送到您的电子邮件的代码以完成验证。",
    "Est. Metal Income": "金属收入",
    "Est. Money Income": "金钱收入",
    "Est. Net Oil Income": "石油净收益",
    "Est. Population Income": "人口收入",
    "for real-time updates.": "以获取实时更新。",
    "Mobilize Faster": "更快调动",
    "New City Development Bonus": "新城市发展加成",
    "No incoming attacks.": "没有来犯的攻击。",
    "No outgoing marches.": "没有外出行军",
    "Operations": "操作",
    "Outgoing Marches": "出征行军",
    "Panavia Tornado ADV": "帕纳维亚龙卷风ADV",
    "Projected values based on your current infrastructure and active modifiers.": "基于当前基础结构和活动修饰符的预测值。",
    "Secure your account to unlock the full experience.": "保护您的帐户以解锁完整的体验。",
    "Stack this boost with treaties, items, and alliance research for explosive growth.": "将此强化与条约、物品和联盟研究叠加以获得爆炸性增长。",
    "State Name": "州名",
    "Stay connected with fellow commanders and the latest announcements.": "与其他指挥官保持联系，了解最新消息。",
    "Survey": "调查",
    "Turbocharge your first seven days": "给你的前七天增加动力",
    "Turrets": "炮塔",
    "Verify": "验证",
    "Password": "密码",
    "Global": "全局",
    "New recruit?": "新兵？",
    "Net Worth": "净价值",
    "Launch Console": "启动控制台",
    "Register Here": "点此注册",
    "Current Season": "当前赛季",
    "Real-Time Ops": "实时操作",
    "Leaderboard (Top 10)": "排行榜 (前 10)",
    "Active War Rooms": "现役作战室",
    "Alliance Warfare": "联盟战争",
    "Begin Deployment": "开始部署",
    "Command the battlefield. Forge your empire.": "指挥战场。打造你的帝国。",
    "Coordinate strikes, espionage, and supply lines with live intel updates.": "协调打击，间谍活动和补给线，实时更新情报。",
    "Double earth attack tounge hinge": "双土攻舌铰链",
    "Forge treaties or wage total war in seasonal campaigns with global players.": "与全球玩家在季节性战役中缔结条约或发动全面战争。",
    "Player Driven Economy": "玩家驱动的经济",
    "Real-Time Ops": "实时行动",
    "Remember this device": "记住这个装置",
    "Seasonal events, escalating skirmishes, and economic tides all collide here. Gear up with quick-hit intel before you deploy.": "季节性事件、不断升级的小规模冲突和经济潮流都在这里碰撞。部署前准备好快速情报。",
    "Secure Login": "安全登录",
    "Supply Lines Online": "在线供应线",
    "Tactical Briefing": "战术简报",
    "Tech Superiority": "科技优势",
    "Territory": "领土",
    "Track the commanders setting tonight's meta. Net worth recalculates live as wars unfold.": "追踪指挥官设置今晚的超能力者。随着战争的展开，净值会重新计算。",
    "Unlock advanced doctrines to shift the meta and dominate the leaderboards.": "解锁高级教义，改变元数据，称霸排行榜。",
    "Username or Email": "用户名或电子邮箱",
    "View Top Commanders": "查看最高指挥官",
    "Dynamic": "动态",
    "Please fill in both fields.": "请填写这两个字段。",
    "Black Ops": "黑色行动",
    "Message Centre": "消息中心",
    "Unit Information": "单位信息",
    "City Alerts": "城市警报",
    "Compose Message": "撰写消息",
    "Date": "日期",
    "Delete All": "删除全部",
    "Game News": "游戏新闻",
    "Help Requests": "帮助请求",
    "Mail": "邮件",
    "Message": "消息",
    "Messages": "消息",
    "News": "新闻",
    "Purchases": "购买",
    "Send Message": "发送消息",
    "Subject": "主题",
    "➕ Create": "➕ 创建",
    "⬅ Back to Dashboard": "⬅ 返回仪表板",
    "🎯 Referral Program": "🎯 推荐计划",
    "👤 Account Profile": "👤 账号资料",
    "Copy": "复制",
    "Create New City": "创建新城市",
    "Current password": "当前密码",
    "Gold": "黄金",
    "Enter City": "进入城市",
    "Email:": "电子邮箱:",
    "Locked": "未解锁",
    "Progress": "进度",
    "Recruits:": "招募人数:",
    "Diamond": "钻石",
    "Delete City": "删除城市",
    "New password": "新密码",
    "Next:": "下一个:",
    "Silver": "白银",
    "Status": "状态",
    "Tier": "段位",
    "Threshold": "门槛",
    "Username:": "用户名:",
    "Your Cities": "你的城市",
    "Your referral link": "你的邀请链接",
    "Update Password": "更新密码",
    "Current Tier:": "当前段位:",
    "Copied!": "已复制!",
    "Confirm new password": "确认新密码",
    "Bronze": "青铜",
    "Change Password": "修改密码",
    "Tiers & Rewards": "段位 & 奖励",
    "Elite": "精英",
    "300 Diamonds, achievement \"Scout\" (season), 10 shards for default commander": "300钻石，成就“侦察兵”（赛季），默认指挥官 10 个碎片",
    "Platinum": "铂金",
    "No recruits yet — share your link to start earning rewards!": "还没有招募 - 分享你的链接开始赚取奖励！",
    "Share this link with friends. When they register, they’ll be linked to you.": "与朋友分享这个链接。当他们注册时，他们会与你绑定。",
    "Unlock a tier to enable claiming. Choose a destination city and press Claim to receive your rewards.": "解锁一个段位后可领取。选择目的地城市，点击领取按钮即可领取奖励。",
    "Use at least 8 characters for a strong password.": "使用至少8个字符作为强密码。",
    "land.": "土地.",
    "Oil Pump": "油泵",
    "money,": "金钱,",
    "Owned": "已拥有",
    "You currently have": "你当前有",
    "Building": "建筑",
    "Buildings": "建筑",
    "Amount": "数量",
    "Cost per land:": "每块土地成本:",
    "metal.": "金属.",
    "Max": "最大",
    "Market": "市场",
    "Metal Refinery": "金属精炼厂",
    "Military Base": "军事基地",
    "Max Land:": "最大土地:",
    "Mine": "矿山",
    "Missile Silo": "导弹发射井",
    "✅ Build": "✅ 建造",
    "🔒 Locked": "🔒 未解锁",
    "🗑️ Demolish": "🗑️ 拆除",
    "📋 View Full Queue": "📋 查看完整队列",
    "1 active survey at a time.": "每次1个主动调查。",
    "Air Base": "空军基地",
    "before queue).": "在排队之前)。",
    "build slot(s).": "建造槽位",
    "free land\n                (": "空闲土地\n                 (",
    "Intelligence Agency": "情报机构",
    "Land to survey:": "待调查土地：",
    "Mobile View": "移动视图",
    "Oil Station": "石油站",
    "POTL": "地块",
    "Queue slots:": "队列槽位：",
    "Queued": "排队中",
    "Residence": "居住地",
    "Start Survey": "开始调查",
    "Survey Land": "调查土地",
    "Turret Station": "炮塔站",
    "Use surveys to uncover additional land on the outskirts of your territory.": "使用调查来发现你的领土外围的额外土地。",
    "You can afford to build on": "你可以负担得起",
    "You can afford to survey up to": "你可以负担得起调查到",
    "Surveyed": "已调查",
    "of": "/",
    "building": "建筑",
    "Building Queue": "建筑队列",
    "In Progress": "进行中",
    "general": "常规",
    "› Economic Bonuses": "› 经济加成",
    "› Military Bonuses": "› 军队加成",
    "› Bot Combat": "› 机器人战斗",
    "› Aircraft": "› 飞机",
    "› Bombers": "› 轰炸机",
    "› Defense": "› 防御",
    "› Generals": "› 将军",
    "› Production": "› 生产",
    "› Tanks": "› 坦克",
    "› Queue Slots": "› 队列槽位",
    "bonus": "加成",
    "Name": "名称",
    "Speed Up": "加速",
    "Survey Mastery": "调查精通",
    "Tank Damage": "坦克伤害",
    "Tank General": "坦克将军",
    "unit": "单位",
    "Open Slots": "解锁槽位",
    "Queue Usage": "队列使用",
    "Oil Production": "石油生产",
    "Coordinate breakthroughs, manage your queue, and keep progress moving.": "协调突破，管理队列，保持进步。",
    "Attack Boost": "攻击提升",
    "Barracks Queue": "兵营队列",
    "Bomber Damage": "轰炸机伤害",
    "Bomber General": "轰炸机将军",
    "Bot Damage Bonus": "机器人伤害加成",
    "Bot Defense Bonus": "机器人防御加成",
    "active": "活跃",
    "Active Research": "进行中的研究",
    "Air General": "空军将军",
    "Aircraft Damage": "飞机伤害",
    "Anti-Air Defense": "防空防御",
    "Bot Land Bonus": "机器人土地奖励",
    "Completed Discoveries": "完成的发现",
    "Completed Research": "完成的研究",
    "Defense Boost": "防御提升",
    "Description": "描述",
    "Economic Boost": "经济增长",
    "Metal Efficiency": "金属效率",
    "Mk IV Panzer": "Mk IV型装甲",
    "No speed-up items in inventory.": "库存中没有加速道具。",
    "Panavia Tornado": "帕纳维亚龙卷风",
    "Population Growth": "人口增长",
    "Research Center": "研究中心",
    "Research Optimization": "研究优化",
    "Research Queue": "研究队列",
    "Show All Research": "展示所有研究",
    "Showing available research only.": "只显示可用的研究。",
    "Speed up active research or finish projects to free slots.": "加速正在进行的研究或完成项目可以释放槽位",
    "Time (with bonuses)": "时间（有加成）",
    "Track your full research history from the completed list.": "从完成的列表中跟踪您的完整研究历史。",
    "Unlocks a second air general.": "解锁第二个空军将军。",
    "Unlocks a second bomber general.": "解锁第二个轰炸机将军。",
    "Unlocks a second concurrent barracks (unit training) queue slot.": "解锁第二个兵营（单位训练）队列。",
    "Unlocks a second concurrent research slot.": "解锁第二个并发研究槽。",
    "Unlocks a second simultaneous building queue slot.": "解锁第二个同时建造的队列槽。",
    "Unlocks a second tank general.": "解锁第二个坦克将军。",
    "Unlocks B-52 Stratofortress bomber.": "解锁B-52同温层堡垒轰炸机",
    "Unlocks Metal Refinery to generate metal.": "解锁金属精炼厂生成金属。",
    "Unlocks Mk IV Panzer tank.": "解锁Mk IV坦克。",
    "Unlocks Oil Station to generate oil.": "解锁油站生成石油。",
    "Unlocks Panavia Tornado aircraft.": "解锁帕纳维亚旋风飞机。",
    "Unlocks Turret Station for city defense.": "解锁城市防御的炮塔站。",
    "Empty research slot available": "空研究槽可用",
    "Unlocks F-16 Falcon aircraft.": "解锁F-16猎鹰战机。",
    "No active research at the moment. Start a new discovery below.": "目前没有进行中的研究。在下面开始一个新的发现。",
    "Category": "类型",
    "Completed At": "完成于",
    "Merkava": "梅卡瓦",
    "Show Available Only": "仅显示可用",
    "Showing all research including locked items.": "显示所有研究成果，包括未解锁的物品。",
    "Unlocks a fourth air general.": "解锁第四个空军将军。",
    "Unlocks a fourth bomber general.": "解锁第四名轰炸机将军。",
    "Unlocks a fourth tank general.": "解锁第四名坦克将军。",
    "Unlocks a third air general.": "解锁第三个空军将军。",
    "Unlocks a third bomber general.": "解锁第三名轰炸机将军。",
    "Unlocks a third concurrent barracks (unit training) queue slot.": "解锁第三个兵营（单位训练）队列。",
    "Unlocks a third concurrent research slot.": "解锁第三个并发研究槽。",
    "Unlocks a third simultaneous building queue slot.": "解锁第三个同时构建队列槽。",
    "Unlocks a third tank general.": "解锁第三个坦克将军。",
    "Unlocks B-2 Spirit stealth bomber.": "解锁B-2幽灵隐形轰炸机",
    "Unlocks F-22 Raptor aircraft.": "解锁F-22猛禽战机。",
    "Unlocks F-35 Lightning aircraft.": "解锁F-35闪电战机。",
    "Unlocks Leopard 2 tank.": "解锁豹2坦克。",
    "Unlocks M1A2 Abrams tank.": "解锁M1A2艾布拉姆斯坦克。",
    "Unlocks Merkava tank.": "解锁梅卡瓦坦克。",
    "Unlocks MiG-35 aircraft.": "解锁米格-35飞机。",
    "Unlocks T-54 tank.": "解锁T-54坦克。",
    "Warning": "警告",
    "No research slots available.": "暂无可用的研究槽位。",
    "World Map": "世界地图",
    "Reset": "重置",
    "Go": "前往",
    "Drag to pan. Hover to see coordinates. Click tiles for actions.": "拖动以移动。悬停查看坐标。点击地块进行操作。",
    "oil": "石油",
    "Owner:": "拥有者:",
    "-- Select Mission --": "-- 选择任务 --",
    "Territory:": "领土:",
    "Cost/unit:": "成本/单位:",
    "Away / Reserved (count toward cap):": "离场 / 预留（计入上限）：",
    "Basic Scan": "基础扫描",
    "Black Ops missions allow you to send trained covert units to perform special operations on target cities.\n            Missions consume “runs” and units travel over time.": "黑色行动任务允许你派遣训练有素的秘密部队在目标城市执行特别行动。任务消耗“跑动”，单位随时间移动。",
    "Black Ops Operations": "秘密行动",
    "Buildings Scan": "建筑扫描",
    "Coord": "坐标",
    "Coord Y": "坐标 Y",
    "Coordinates stay filled in after each mission until you change them.": "每次任务完成后，坐标一直保持不变，直到你改变它们。",
    "ETA:": "预计到达时间：",
    "Kill Crew": "击杀兵团",
    "Launch Black Ops Mission": "启动黑色行动",
    "Launch Mission": "启动任务",
    "Looking up target…": "寻找目标…",
    "metal,": "金属,",
    "Military Ops Scan": "军事行动扫描",
    "Military Scan": "军事扫描",
    "Mission Type": "任务类型",
    "Networth:": "净值：",
    "No missions": "暂无任务",
    "No valid target at those coords.": "这些区域没有有效目标。",
    "Oil Systems Scan": "石油系统扫描",
    "Queued Missions": "排队的任务",
    "Research Scan": "研究扫描",
    "Runs remaining:": "运行剩余：",
    "Space available:": "可用空间:",
    "Steal Metal": "偷金属",
    "Steal Money": "偷钱",
    "Steal Oil": "偷油",
    "Steal Population": "偷人口",
    "Total Capacity:": "总容量:",
    "Total cost:": "总成本:",
    "Train Black Ops Units": "训练黑色行动部队",
    "Train Units": "训练单位",
    "Units available (at home):": "可用单位（在家里）：",
    "Your Black Ops Overview": "你的黑色行动概述",
    "Rewards": "奖励",
    "unlocked": "已解锁",
    "User": "用户",
    "Next Achievements": "下一个成就",
    "Earn Oil": "获得石油",
    "Earn Money": "获得金钱",
    "Earn Metal": "获得金属",
    "Earn Land": "获得土地",
    "Date Earned": "获得日期",
    "City": "城市",
    "City Achievements": "城市成就",
    "⚠️ Negative oil may cripple your city’s performance!": "⚠️ 负面的石油可能会削弱你的城市的表现！",
    "🛢️ Oil Systems": "🛢️ 石油系统",
    "Critical Resource": "关键资源",
    "Deficit": "亏损",
    "Turrets will come online in 3 cycles.": "炮塔将在3个周期后上线。",
    "Net Oil Production:": "净产油量：",
    "Military Usage": "军事用途",
    "Metal Refineries": "金属精炼厂",
    "Infrastructure": "基础设施",
    "Gross Production:": "生产总值:",
    "Queue Your First Research": "队列的第一个研究",
    "Gather Cabal Intel": "收集阴谋集团情报",
    "Movement": "移动",
    "Qty:": "数量:",
    "Use": "使用",
    "Use on Map": "在地图上使用",
    "Your Items": "你的物品",
    "Speed Ups": "加速",
    "Targeted Teleport": "定向传送",
    "Teleports your city to a random location on the map.": "将你的城市传送到地图上的一个随机位置。",
    "Teleports your city to coordinates of your choice.": "传送你的城市到你选择的坐标。",
    "Bot Spawners": "机器人制造者",
    "Spawns a large Cabal agent near your city.": "在你的城市附近生成一个大型阴谋集团特工。",
    "Spawns a medium Cabal agent near your city.": "在你的城市附近生成一个中型阴谋集团特工。",
    "Spawns a small Cabal agent near your city.": "在你的城市附近生成一个小型阴谋集团特工。",
    "Buffs": "增益",
    "Search filters items in all tabs by item name.": "搜索根据项目名称过滤所有选项卡中的项目。",
    "Random Teleport": "随机传送",
    "No items match your search.": "没有符合你搜索的项目。",
    "Small Cabal Decloaker": "小型阴谋揭露者",
    "Medium Cabal Decloaker": "中型阴谋揭露者",
    "Large Cabal Decloaker": "大型阴谋揭露者",
    "Clear": "清除",
    "Grants peace for 1 day, preventing attacks.": "获得和平状态，持续1天，不会受到攻击。",
    "Increase defensive strength by 5% for 1 hour.": "增加防御力量5%，持续1小时。",
    "Inflate reported military strength by 25% when spied upon for 1 hour.": "被监视1小时后，将报告的军事力量提高25%。",
    "Inflate reported military strength by 50% when spied upon for 4 hours.": "被监视4小时后，将报告的军事力量提高50%。",
    "Enter a quantity > 0 for at least one building.": "输入数量 > 0表示至少一个建筑。",
    "Error": "错误",
    "7-Day Premium": "7天会员",
    "Battlefront Pack": "前线礼包",
    "Cabal Overseer": "阴谋集团监督者",
    "Buy with PayPal": "使用 PayPal 购买",
    "Buy Shards": "购买碎片",
    "Buy Income with Diamonds": "用钻石购买收入",
    "City Diamonds:": "城市钻石:",
    "Cost:": "成本:",
    "Diamonds:": "钻石:",
    "Population:": "人口:",
    "Price:": "价格:",
    "Oil:": "石油:",
    "Purchase": "购买",
    "Scholar Pack": "学者礼包",
    "Special Item Packs": "特殊道具礼包",
    "Total Available:": "总可用:",
    "Traveler Pack": "旅人礼包",
    "Wallet Diamonds:": "钱包钻石:",
    "Greater Scholar Pack": "大学者礼包",
    "Premium Subscription": "会员订阅",
    "Quartermaster Vega": "维加军需官",
    "Research speed buffs.": "研究速度增益。",
    "City Diamonds stay with this city while Wallet Diamonds are shared across all cities. Purchases spend City Diamonds first and use Wallet Diamonds if needed.": "城市钻石留在这个城市，而钱包钻石在所有城市共享。购买优先消耗城市钻石，必要时使用钱包钻石。",
    "Each city receives: 5× 1h Research Speedups, 5× 1d Peace Treaties, 10× Epic Wild Shards, and 5,000 Diamonds.": "每个城市获得：5× 1小时研究加速，5× 1天和平条约，10×史诗野生碎片和5000颗钻石。",
    "Grants resource bonuses, items and Diamonds for each city.": "为每个城市提供资源奖励，物品和钻石。",
    "Large set of research speed ups.": "大量的研究加速。",
    "Move around the world.": "环游世界。",
    "Offense, defense and decoys.": "进攻，防守和诱饵。",
    "Peace and Prosperity Pack": "和平与繁荣礼包",
    "Peace treaties and economy boosts.": "和平条约和经济增长。",
    "+5% Attack and Defense bonuses while premium is active.": "激活加成时+5%攻击和防御加成。",
    "+10% Money, Metal, Oil, Population, Survey, and Research production in every city.": "每个城市+10%的货币，金属，石油，人口，调查和研究生产。",
    "Defense:": "防御:",
    "Shards:": "碎片:",
    "Exp:": "经验值:",
    "Attack:": "攻击:",
    "Lvl:": "等级:",
    "Build slot:": "建造槽位:",
    "Common": "普通",
    "Epic": "史诗",
    "Legendary": "传说",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Warlord Aegis": "战神宙斯盾",
    "Your Commanders": "你的指挥官",
    "Refinery Chief Noor": "炼油厂主管努尔",
    "Research slots:": "研究槽位:",
    "Chief Scientist Reyes": "首席科学家雷耶斯",
    "Attack time reduction:": "攻击时间缩短：",
    "Available Commanders": "可用的指挥官",
    "Captain Stone": "斯通队长",
    "Enjoy accelerated growth for free—no extra steps needed while your settlement establishes itself.": "免费享受加速增长-当您的定居建立自己时，不需要额外的步骤。",
    "No active effects at the moment.": "暂无生效的效果。",
    "Fortress Marshal Hana": "要塞元帅哈娜",
    "Operative Kestrel": "红隼特工",
    "Prospector Inez": "探勘者伊内兹",
    "Survey bonus:": "调查加成:",
    "Training queue:": "训练队列:",
    "\"Turns sludge into lifeblood for the war machine.\"": "“把污泥变成战争机器的命脉。”",
    "\"The original leader of every new city.\"": "“每个新城市最初的领导者。”",
    "\"Shields the line, then breaks theirs.\"": "“挡住对方的线，然后打断对方的线。”",
    "\"Knits theory and steel into breakthroughs.\"": "“将理论和钢铁编织成突破。”",
    "\"Keeps the ledgers tight and the convoys on time.\"": "“保持账本的紧凑和车队的准时。”",
    "\"Front-line commander with an iron grin.\"": "“带着铁腕笑容的前线指挥官。”",
    "\"Finds ore where maps insist there’s none.\"": "“在地图上没有的地方找到矿石。”",
    "\"Builds walls you only breach once.\"": "“筑起你只能攻破一次的高墙。”",
    "\"An implacable machine tactician of the Cabal.\"": "“阴谋集团中不可调和的机器战术家。”",
    "\"Airframe whisperer who speeds every sortie.\"": "“飞机上的耳语者，每次起飞都加速。”",
    "🏆 Game Scores": "🏆 游戏分数",
    "🤖 Bot": "🤖 机器人",
    "Achievement Score": "成就分数",
    "Active": "活跃",
    "Largest Bots": "最大的机器人",
    "Strongest Bots": "最强大的机器人",
    "Largest Cities": "最大的城市",
    "Strongest Cities": "最强大的城市",
    "Largest Alliances": "最大的联盟",
    "Strongest Alliances": "最强大的联盟",
    "Location": "位置",
    "Next": "下一页",
    "Prev": "上一页",
    "Top Achievement Scores": "最高成就分数",
    "Rows per page:": "每页显示数量:",
    "Rank": "排名",
    "Alliance Command": "联盟指挥部",
    "Alliance Directory": "联盟目录",
    "Alliance News": "联盟新闻",
    "Alliance Research": "联盟研究",
    "Alliance Roster": "联盟名单",
    "Alliance Treasury": "联盟宝库",
    "Alliance Name": "联盟名称",
    "Alliance Rallies": "联盟集结",
    "Alliance created successfully.": "联盟创建成功。",
    "Applications": "申请",
    "Apply to Alliance": "申请加入联盟",
    "No applications submitted.": "暂未提交申请。",
    "No invitations waiting.": "暂无等待中的邀请。",
    "Invitations": "邀请",
    "Create Alliance": "创建联盟",
    "HQ": "总部",
    "HQ Y": "总部 Y",
    "HQ X": "总部 X",
    "Select alliance": "请选择联盟",
    "Tag": "标签",
    "Vulnerability Block": "局况块",
    "Members": "成员",
    "Slug (optional)": "弹头（可选）",
    "Short identifier shown alongside the alliance name.": "联盟名称旁边显示的短标识符。",
    "Submit Application": "提交申请",
    "You are not currently in an alliance. Join one below or create your own.": "你目前没有加入联盟。加入下面的一个或创建你自己的。",
    "Closed": "未开放",
    "HQ Garrison": "总部驻军",
    "Joined": "已加入",
    "HQ Vulnerability Window": "总部局况窗口",
    "leader": "领导者",
    "Manage Alliance": "管理联盟",
    "Leave Alliance": "离开联盟",
    "Opens in": "距离开放",
    "Role": "角色",
    "Your Role": "你的角色",
    "Times in UTC": "UTC时间",
    "Achievement": "成就",
    "Achievements & Rewards": "成就 & 奖励",
    "Attack the Cabal": "攻击阴谋集团",
    "Build Black Ops": "建立黑色行动",
    "Celebrate your progress, revisit your recent unlocks, and preview the rewards waiting for your next milestones.": "庆祝你的进步，回顾你最近的解锁，预览奖励等待你的下一个里程碑。",
    "Account-wide achievements that stay unlocked forever.": "账户范围内的成就永远保持解锁状态。",
    "Complete Research": "完成研究",
    "Finish First": "完成第一",
    "Finish Top 10": "完成前十",
    "Loot Drop": "战利品掉落",
    "lay Seasons": "游玩赛季",
    "Achieve a research‐derived net worth of 10,000.": "达到10,000的研究所得净值。",
    "Achieve a research‐derived net worth of 100,000.": "达到10万的研究所得净资产。",
    "City Achievements Completed": "城市成就",
    "Construct 100 buildings in your city.": "在你的城市建造100座建筑。",
    "Destroy Networth": "摧毁净值",
    "Destroy the highest net worth.": "摧毁最高净值。",
    "End a season in first place.": "赛季结束时排名第一",
    "End a season ranked in the top 10.": "赛季结束时排名前10",
    "Launch an offensive strike against the Cabal.": "对阴谋集团发动攻势。",
    "Lifetime Achievements": "终身成就",
    "Participate in five seasons.": "参与5个赛季。",
    "Participate in one season.": "参与一个赛季。",
    "Put a research project into your queue.": "把一个研究项目放到你的队列中。",
    "Recent Achievements": "近期成就",
    "Run a basic black ops mission on a bot.": "用机器人执行一次基本的黑色行动。",
    "Scope": "适用范围",
    "Seasonal objectives that reset each new war.": "赛季目标，重置每场新战争。",
    "Seasonal onboarding milestones for your city.": "所在城市的赛季登录里程碑",
    "Strength Through Research": "通过研究获得优势",
    "Top Destroyer": "顶级驱逐舰",
    "Train 100 Tanks": "训练100辆坦克",
    "Train 100 tanks in your military.": "在你的军队中训练100辆坦克。",
    "Tutorial": "教程",
    "Tutorial Achievements": "教程成就",
    "Tutorial Achievements Completed": "完成教程成就",
    "Upcoming": "即将到来",
    "User Achievements Completed": "用户完成成就",
    "User rewards grant ~1.5× diamonds.": "用户奖励授予1.5×钻石。",
    "Play Seasons": "游玩赛季",
    "Aircraft": "飞机",
    "Aircraft:": "飞机:",
    "Bomber": "轰炸机",
    "Bomber:": "炸弹:",
    "Enemy": "敌人",
    "Enter coordinates to view target info": "输入坐标查看目标信息",
    "Friendly": "友好",
    "Initiate Rally": "发起集结",
    "Launch an Attack": "发起攻击",
    "Launch Attack": "发起攻击",
    "No attacks": "暂无攻击",
    "No enemy rallies are targeting your alliance.": "当前没有针对本联盟的敌方集结",
    "No friendly rallies are forming.": "暂无友军集结",
    "Queued Attacks": "排队的攻击",
    "Rallies always deploy tanks and target your alliance HQ coordinates.": "集结总是部署坦克并以你的联盟总部坐标为目标。",
    "Send": "发送",
    "Tank": "坦克",
    "Tank:": "坦克:",
    "The last coordinates you enter will stay filled in until you change them.": "您输入的最后一个坐标将保持填充状态，直到您更改它们。",
    "Unit": "单位",
    "Welcome to the Attack Center": "欢迎来到攻击中心",
    "You can place attacks on other cities, or garrison troops on empty tiles or friendly cities to defend.": "你可以攻击其他城市，或者在空地块或友军城市驻军。",
    "All messages deleted": "已删除所有消息",
    "Disable Metal Refineries": "禁用金属精炼厂",
    "Disable Turrets": "禁用炮塔",
    "Surplus": "盈余",
    "View Alliance": "查看联盟",
    "Launch Rally": "发起集结",
    "Scout HQ": "侦察总部",
    "Establish Alliance HQ Here": "在此建立联盟总部",
    "Empty Tile": "空地块",
    "Teleport (requires item)": "传送（需要道具）",
    "Refresh": "刷新",
    "Select a ticket from the left to view the conversation.": "从左侧选择一个票据来查看对话。",
    "No tickets yet — create one below.": "还没有票据 - 在下面创建一个。",
    "New Ticket": "新票据",
    "Billing": "账单",
    "Bug Report": "报告错误",
    "Suggestion": "建议",
    "Support Tickets": "支持票据",
    "Technical": "技术",
    "Your Tickets": "你的票据",
    "Describe your issue": "描述你的问题",
    "Your current resources, land, networth and other key statistics are shown at\n            the top of each page. Achievements and scores help measure your growth\n            against other commanders.": "你目前的资源，土地，净资产和其他关键统计数据显示在每页的顶部。成就和分数有助于衡量你与其他指挥官的成长。",
    "page to launch assaults on rival cities. Choose the\n            units you wish to send, then select a target. Offensive power is compared to\n            your opponent’s defenses to determine the outcome.": "页面对敌对城市发动攻击。选择你想发送的单位，然后选择一个目标。进攻力量与你对手的防御能力相比较来决定胜负。",
    "Develop your city, train units, research new technologies and expand your\n            territory. Use the dashboard to access construction, research, and military\n            actions.": "发展你的城市，训练单位，研究新技术和扩大你的领土。使用仪表板访问建设，研究和军事行动。",
    "Attacking": "攻击",
    "– fuels vehicles and aircraft; also used for\n                certain black ops.": "-为车辆和飞机提供燃料；也用于某些秘密行动。",
    "– overall strength calculated from all\n                units, buildings, and resources you own.": "-综合力量计算从所有单位，建筑和资源你拥有。",
    "– population available to operate buildings\n                and vehicles.": "-可操作建筑物及车辆的人口。",
    "– primary currency for training units and\n                maintaining your empire.": "-主要货币训练单位和维持你的帝国。",
    "– required for advanced buildings and heavy\n                military units.": "-高级建筑和重型军事单位所需。",
    "Balance resource production with military strength.": "平衡资源生产和军事实力。",
    "Black ops are covert missions aimed at disrupting opponents without open war.\n            Train spies and research espionage technologies to unlock these actions.": "黑色行动是指在没有公开战争的情况下，以破坏对手为目的的秘密任务。训练间谍和研究间谍技术来解锁这些行动。",
    "Black Ops Missions": "黑色行动任务",
    "buildings expand unit capacity and defense.": "建筑扩大单位容量和防御。",
    "Commander bonuses and research can sway battle results.": "指挥官加成和研究可以影响战斗结果。",
    "Commanders can boost attacks – keep them trained and ready.": "指挥官可以提高攻击-保持他们的训练和准备。",
    "Common missions include reconnaissance, sabotage, and resource theft.": "常见的任务包括侦察、破坏和资源盗窃。",
    "Construct buildings on available land to grow your city. Each structure offers\n            specific benefits and often unlocks new capabilities.": "在可用的土地上建造建筑来发展你的城市。每种结构都提供了特定的好处，并且通常会解锁新的功能。",
    "Crew": "兵团",
    "Economic": "经济",
    "Economic buildings like factories and refineries produce money and\n                metal.": "像工厂和精炼厂这样的经济建筑生产金钱和金属。",
    "facilities unlock advanced technologies.": "设施解锁先进的技术。",
    "Failed missions may reveal your identity to the target.": "失败的任务可能会暴露你的身份给目标。",
    "Game Manual": "游戏手册",
    "Gameplay": "游戏玩法",
    "General Tips": "一般建议",
    "Higher level buildings generally cost more but offer greater rewards.": "更高级别的建筑通常成本更高，但提供的奖励也更多。",
    "Income & Economy": "收入与经济",
    "Income is generated each tick from your buildings and research bonuses. Keep\n            a positive flow to support expansion and upkeep costs.": "收入是由你的建筑和研究奖励产生的。保持正流量以支持扩展和维护成本。",
    "Key Definitions": "关键定义",
    "Oil fields provide the fuel needed for vehicles and aircraft.": "油田为车辆和飞机提供所需的燃料。",
    "Research and commanders can boost income or reduce upkeep.": "研究和指挥官可以增加收入或减少维护。",
    "Research upgrades early to gain strategic advantages.": "尽早研究升级，获取战略优势。",
    "Stats & Progression": "统计和进展",
    "structures increase resource production.": "建筑增加资源生产。",
    "Success chances depend on spy strength versus enemy security.": "成功的机会取决于间谍的力量和敌人的安全。",
    "Successful attacks can seize land, resources, or destroy enemy assets.": "成功的攻击可以夺取土地、资源或摧毁敌人的资产。",
    "Train units in the Barracks before attacking.": "在进攻前训练兵营中的单位。",
    "Use the": "使用",
    "Welcome to Modern Conflict! This manual provides a brief overview of how to\n            build your empire, track your progress, and survive the war for supremacy.": "欢迎来到现代冲突！这本手册提供了一个简要的概述，如何建立你的帝国，跟踪你的进展，并生存的战争霸权。",
    "Airspace Used:": "使用空域：",
    "Available Crew:": "可用成员：",
    "Barracks": "军营",
    "Bombers": "轰炸机",
    "Capacity Overview": "容量概述",
    "Cost per Crew:": "每个成员成本：",
    "Crew Space Used:": "已使用成员空间：",
    "Disband Units": "解散单位",
    "Fighters": "战斗机",
    "Free Crew Space:": "剩余成员空间：",
    "Max Trainable:": "最大可训练：",
    "Qty": "数量",
    "Tanks": "坦克",
    "Train": "训练",
    "Train Crew": "训练成员",
    "Train Max": "训练上限",
    "Train Military Units": "训练军事单位",
    "Training Batches:": "训练批次：",
    "Turret Space:": "炮塔空间:",
    "Descriptions are irrelevant": "描述无关紧要",
    "HQ Coordinates": "总部坐标",
    "HQ Last Moved": "总部最近移动",
    "Details": "详情",
    "Peace": "和平",
    "View World Map": "查看世界地图",
    "Roster": "名单",
    "Build Queue": "建造队列",
    "Processed": "进度",
    "Quantity": "数量",
    "Remaining": "剩余",
    "Survey Queue": "调查队列",
    "tiles.": "地块.",
    "Bolster city defenses with coordinated planning.": "通过协调规划加强城市防御。",
    "Boost alliance members' offensive strength.": "提高联盟成员的进攻力量。",
    "Coordinated Assault": "协同攻击",
    "Daily help allowance per city:": "每个城市每日帮扶津贴：",
    "Each help reduces the timer by 00h 10m 00s.": "每个帮助将计时器减少00小时10分钟00秒。",
    "Effect per Level": "每级效果",
    "Fortified Bastion": "坚固的堡垒",
    "Helps remaining today": "今日剩余帮助次数",
    "Improve economic throughput across all member cities.": "提高所有成员城市的经济吞吐量。",
    "Level": "等级",
    "Next Level ETA": "下一级预计时间",
    "No alliance research is running. Choose a project below to begin.": "没有任何联盟研究在运行。选择下面的一个项目开始。",
    "No help actions have been logged yet.": "尚未记录任何帮助操作。",
    "No help contributions recorded yet.": "尚未记录任何帮助贡献。",
    "Recent Help": "近期帮助",
    "Research Tree": "研究树",
    "Shared Bonuses": "分享加成",
    "Shared Industry": "共享产业",
    "Top Helpers": "最高的帮手",
    "Help effect: 00h 10m 00s per assist": "帮助效果：每次帮助 00小时 10分钟 00秒",
    "Provide Help": "提供帮助",
    "Researching": "正在研究",
    "Helps": "帮助",
    "Time Reduced": "时间减少",
    "Select city": "选择城市",
    "Save Changes": "保存更改",
    "Save Window": "保存窗口",
    "Update": "更新",
    "No invites have been issued.": "暂未发出邀请。",
    "Actions": "动作",
    "Alliance Profile": "联盟资料",
    "Use the world map to pick a tile quickly.": "使用世界地图快速选择一个地块。",
    "Select the 4-hour window when your HQ can be attacked.": "选择你的总部可以被攻击的4小时窗口期。",
    "Outstanding Invites": "未完成的邀请",
    "Message (optional)": "消息 (可选)",
    "Roster Management": "名单管理",
    "Player": "玩家",
    "Send Invite": "发送邀请",
    "Leader": "领导者",
    "Send Invitation": "发送邀请",
    "Manage the alliance vulnerability block in the section below.": "在下面部分管理联盟脆弱块。",
    "Alliance HQ Garrison": "联盟总部驻军",
    "Alliance HQ not yet placed.": "联盟总部尚未设立。",
    "Place your alliance HQ on the world map to enable defensive garrisons.": "在世界地图上放置你的联盟总部以启用防御驻军。",
    "Your City": "你的城市",
    "Current Balances": "当前余额",
    "Deposit to Treasury": "存入宝库",
    "Contribute Resources": "贡献资源",
    "All alliance members (equal distribution)": "所有联盟成员（平均分配）",
    "Enter the quantity to contribute from your city.": "输入您所在城市的捐献数量。",
    "Deposits shown above axis, withdrawals below.": "上面是存入，下面是取出。",
    "Funds move directly to the selected city or to every member when distributing to all.": "资金直接转移到选定的城市，或者在分配给所有成员时转移到每个成员。",
    "Most recent 25 entries": "最近的25条记录",
    "No treasury transactions have been recorded yet.": "目前还没有资金交易记录。",
    "Recent Transactions": "最近的交易",
    "Recipient": "接受者",
    "Selecting all members sends the entered amount to each city (total cost equals amount × member count).": "选择所有成员将输入的金额发送到每个城市（总成本等于金额×成员数）。",
    "Totals this period:": "本期合计：",
    "Withdraw Resources": "提取资源",
    "Withdraw to City": "提取到城市",
    "Activity (Last 7 Days)": "动态（过去7天）",
    "When": "时间",
    "deposit money": "存入金钱",
    "Alliance Rally Coordination": "联盟集结协调",
    "Coordinate multi-city offensives and defensive garrisons for your alliance.": "为你的联盟协调多城市的进攻和防御驻军。",
    "Monitor alliance offensives and coordinate defensive garrisons.": "监视联盟的进攻并协调防御驻军。",
    "New rallies are now initiated from the": "新的集结现在从",
    "No friendly rallies are currently forming.": "暂无友军集结",
    "page. Coordinate with your team there to stage a rally, then return here to monitor participation.": "页面。与那里的队伍协调，进行集结，然后返回这里监控参与情况。",
    "Donation": "捐献",
    "HQ Window": "总部窗口",
    "HQ Movement": "总部移动",
    "Open Treasury": "打开宝库",
    "Rally": "集结",
    "Research Help": "研究帮助",
    "System": "系统",
    "Trade": "交易",
    "Treasury": "宝库",
    "Unit Training Queue": "单位训练队列",
    "Move Alliance HQ Here": "将联盟总部搬到这里",
    "Manage HQ Garrison": "管理总部驻军",
    "No missions queued.": "没有任务排队。",
    "Quick Apply Speed-Ups": "快速应用加速",
    "Build": "建造",
    "Build Turrets": "建造炮塔",
    "Cost per Turret:": "每个炮塔建造成本:",
    "Free Slots:": "空闲槽位:",
    "Max Buildable Now:": "现在最大可建:",
    "Not enough crew.": "没有足够的兵团。",
    "Mark All Read": "全部标记为已读",
    "All messages marked as read": "所有消息已标记为已读",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Git游戏.": "Git游戏.",
    "GIT": "GIT",
    "M4 Sherman": "M4谢尔曼",
    "MiG-21F": "MiG-21F",
    "M1A2 Abrams": "M1A2 轰炸机",
    "T-54": "T-54",
    "MiG-35": "MiG-35",
    "Leopard 2": "猎豹 2",
    "B-52 Stratofortress": "B-52 同温层堡垒",
    "B-2 Spirit": "B-2 精灵",
    "F-16 Falcon": "F-16 猎鹰",
    "F-22 Raptor": "F-16 猛禽",
    "F-35 Lightning": "F-16 闪电",
    "Gityx": "Gityx",
    "G8hh": "G8hh",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "⚙️": "⚙️",
    "🌐": "🌐",
    "👥": "👥",
    "💎": "💎",
    "💰": "💰",
    "📈": "📈",
    "🛢️": "🛢️",
    "•": "•",
    "—": "—",
    "#": "#",
    "likexaizai@qq.com": "likexaizai@qq.com",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "End: ": "结束于: ",
    "Start: ": "开始于: ",
    "Leader: ": "领导者: ",
    "Networth: ": "净值: ",
    "Advanced Economic Boost ": "高级经济提升 ",
    "Advanced Metal Efficiency ": "高级金属效率 ",
    "Advanced Oil Production ": "高级石油生产 ",
    "Advanced Population Growth ": "高级人口增长 ",
    "Advanced Research Optimization ": "高级研究优化 ",
    "Advanced Survey Mastery ": "高级调查精通 ",
    "Units (Max: ": "单位 (最大: ",
    "Diamonds +": "钻石 +",
    "Land +": "土地 +",
    "Metal +": "金属 +",
    "Money +": "金钱 +",
    "Oil +": "石油 +",
    "Raw Land: ": "未开垦土地: ",
    "Tanks: ": "坦克: ",
    "Aircraft: ": "飞机: ",
    "Count: ": "数量: ",
    "Buildings: ": "建筑: ",
    "Bombers: ": "轰炸机: ",
    "Blackops: ": "黑色行动: ",
    "Enabling Refineries": "启用炼油厂",
    "Enabling Turrets": "启用炮塔",
    "Achievement Unlocked: ": "成就已解锁: ",
    "Common: ": "普通: ",
    "Epic: ": "史诗: ",
    "Legendary: ": "传说: ",
    "Rare: ": "稀有: ",
    "Uncommon: ": "罕见: ",
    "Specific: ": "特异性: ",
    "Metal:": "金属:",
    "Money:": "金钱:",
    "Active daily from ": "每日活跃于 ",
    "Opens at ": "开放于 ",
    "Vulnerability block: Block ": "弱点块: 格挡 ",
    "Loot Pool: ": "战利品池: ",
    "Population +": "人口 +",
    "Coords: ": "坐标: ",
    "Land: ": "土地: ",
    "Tag: ": "标签: ",
    "Shared technology for ": "共享技术 ",
    "Ends ": "结束于 ",
    "Fortified Bastion — Level ": "坚固的堡垒 - 等级 ",
    "Helps left today: ": "今日剩余帮助次数：",
    "Time remaining: ": "时间剩余: ",
    "Helped ": "帮助了 ",
    "You are logged in as leader of ": "你登录的省份是领导者 ",
    "Shared resources for ": "分享资源给 ",
    "Balance Metal: ": "金属余额: ",
    "Balance Money: ": "金钱余额: ",
    "Balance Oil: ": "石油余额: ",
    "Balance Population: ": "人口余额: ",
    "Last viewed: ": "最后查看：",
    "Shared activity for ": "共享活动对于 ",
    " queued.": " 在排队.",
    "Alliance profile updated. Alliance HQ established at ": "联盟简介更新。联盟总部设立在",
    "HQ relocation available in ": "距离下次总部搬迁可用还剩 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " (rare)": " (稀有)",
    " (epic)": " (史诗)",
    " (uncommon)": " (罕见)",
    " (legendary)": " (传说)",
    " (common commander)": " (普通指挥官)",
    "Total Usage:": "总计使用:",
    " shards - Cost:": " 碎片 - 成本:",
    " used": " 已使用",
    " left)": " 剩余)",
    " — defensive capacity overview.": "— 防御能力概述。",
    " (You)": " (你)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^\$([\d\.]+) CAD$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^X: ([\d\.,]+), Y: ([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\(([\d\.,]+), ([\d\.,]+)\)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+) 💎$/,
    /^([\d\.,]+)\-([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Contributed (.+) oil to the alliance treasury.$/, '为联盟金库捐献了 $1 石油.'],
    [/^Contributed (.+) metal to the alliance treasury.$/, '为联盟金库捐献了 $1 金属.'],
    [/^Contributed (.+) population to the alliance treasury.$/, '为联盟金库捐献了 $1 人口.'],
    [/^Contributed (.+) money to the alliance treasury.$/, '为联盟金库捐献了 $1 金钱.'],
    [/^Deposits \—\n(.+)Money: (.+),(.+)Metal: (.+),(.+)Oil: (.+),(.+)Population: (.+)$/, '存入 —\n$1金钱: $2,$3金属: $4,$5石油: $6,$7人口: $8'],
    [/^Withdrawals \—\n(.+)Money: (.+),(.+)Metal: (.+),(.+)Oil: (.+),(.+)Population: (.+)$/, '取出 —\n$1金钱: $2,$3金属: $4,$5石油: $6,$7人口: $8'],
    [/^Research sped up by (.+)h (.+)m (.+)s. Helps left today: (.+).$/, '研究速度加快了 $1小时 $2分钟 $3秒。今日剩余帮助次数：$4。'],
    [/^Alliance members have shaved (.+)h (.+)m (.+)s off this research across (.+) help.$/, '联盟成员通过 $4 次帮助将这项研究的时间缩短了 $1小时 $2分钟 $3秒。'],
    [/^Alliance members have shaved (.+)h (.+)m (.+)s off this research across (.+) helps.$/, '联盟成员通过 $4 次帮助将这项研究的时间缩短了 $1小时 $2分钟 $3秒。'],
    [/^Alliance research \"Fortified Bastion\" level (.+) has begun. Estimated completion in (.+)d (.+)h (.+)m (.+)s.$/, '联盟研究\“坚固的堡垒” $1 级已经开始。预计完成时间 $2天 $3小时 $4分钟 $5秒。'],
    [/^Accumulate (.+) units of metal.$/, '累计 $1 单位 金属.'],
    [/^Accumulate (.+) units of population.$/, '累计 $1 单位 人口.'],
    [/^Accumulate (.+) units of land.$/, '累计 $1 单位 土地.'],
    [/^Accumulate (.+) units of money.$/, '累计 $1 单位 金钱.'],
    [/^Accumulate (.+) units of oil.$/, '累计 $1 单位 石油.'],
    [/^Build (.+) bombers$/, '建造 $1 轰炸机'],
    [/^Build (.+) tanks$/, '建造 $1 坦克'],
    [/^Build (.+) aircraft$/, '建造 $1 飞机'],
    [/^Construct (.+) aircraft.$/, '建造 $1 飞机.'],
    [/^Construct (.+) bombers.$/, '建造 $1 轰炸机.'],
    [/^Construct (.+) tanks.$/, '建造 $1 坦克.'],
    [/^Construct (.+) black_ops.$/, '建造 $1 黑色行动.'],
    [/^Finish (.+) research projects.$/, '完成 $1 研究项目.'],
    [/^Grants peace for (.+) days, preventing attacks.$/, '获得和平状态，持续$1天，不会受到攻击。'],
    [/^Reduces active research time by (.+) day.$/, '主动研究时间减少 $1 天。'],
    [/^Reduces active research time by (.+) days.$/, '主动研究时间减少 $1 天。'],
    [/^Reduces active research time by (.+) minute.$/, '主动研究时间减少 $1 分钟。'],
    [/^Reduces active research time by (.+) minutes.$/, '主动研究时间减少 $1 分钟。'],
    [/^Reduces active research time by (.+) hour.$/, '主动研究时间减少 $1 小时。'],
    [/^Reduces active research time by (.+) hours.$/, '主动研究时间减少 $1 小时。'],
    [/^Increase offensive strength by (.+) for (.+) hour.$/, '增加 进攻力量 $1 持续 $2 小时。'],
    [/^Increase offensive strength by (.+) for (.+) hours.$/, '增加 进攻力量 $1 持续 $2 小时。'],
    [/^Increase research speed by (.+) for (.+) hour.$/, '增加 研究速度 $1 持续 $2 小时。'],
    [/^Increase research speed by (.+) for (.+) hours.$/, '增加 研究速度 $1 持续 $2 小时。'],
    [/^Increase money income by (.+) for (.+) hour.$/, '增加 金钱 收入 $1 持续 $2 小时。'],
    [/^Increase money income by (.+) for (.+) hours.$/, '增加 金钱 收入 $1 持续 $2 小时。'],
    [/^Increase metal income by (.+) for (.+) hour.$/, '增加 金属 收入 $1 持续 $2 小时。'],
    [/^Increase metal income by (.+) for (.+) hours.$/, '增加 金属 收入 $1 持续 $2 小时。'],
    [/^Increase population income by (.+) for (.+) hour.$/, '增加 人口 收入 $1 持续 $2 小时。'],
    [/^Increase population income by (.+) for (.+) hours.$/, '增加 人口 收入 $1 持续 $2 小时。'],
    [/^Increase oil income by (.+) for (.+) hour.$/, '增加 石油 收入 $1 持续 $2 小时。'],
    [/^Increase oil income by (.+) for (.+) hours.$/, '增加 石油 收入 $1 持续 $2 小时。'],
    [/^Increase defensive strength by (.+) for (.+) hours.$/, '增加 防守力量 $1 持续 $2 小时。'],
    [/^Queued (.+) Turret Station.$/, '$1 炮塔站 已加入队列。'],
    [/^Queued (.+) Metal Refinery.$/, '$1 金属精炼厂 已加入队列。'],
    [/^Queued (.+) Mine.$/, '$1 矿山 已加入队列。'],
    [/^Queued (.+) Military Base.$/, '$1 军事基地 已加入队列。'],
    [/^Queued (.+) Air Base.$/, '$1 空军基地 已加入队列。'],
    [/^Queued (.+) Oil Station.$/, '$1 石油站 已加入队列。'],
    [/^Play (.+) Season$/, '玩 $1 赛季'],
    [/^Play (.+) Seasons$/, '玩 $1 赛季'],
    [/^Earn (.+) land$/, '获得 $1 土地'],
    [/^Earn (.+) metal$/, '获得 $1 金属'],
    [/^Earn (.+) money$/, '获得 $1 金钱'],
    [/^Earn (.+) population$/, '获得 $1 人口'],
    [/^Earn (.+) oil$/, '获得 $1 石油'],
    [/^Build (.+) black_ops$/, '建造 $1 黑色行动'],
    [/^Build (.+) Structures$/, '建造 $1 结构'],
    [/^Complete (.+) Research Projects$/, '完成 $1 研究项目'],
    [/^Survey started for (.+) land.$/, '开始对 $1 块土地进行调查。'],
    [/^Estimated build cost: (.+) money, (.+) metal for (.+) land$/, '预计建造成本：$1 金钱，$2 金属，$3 土地'],
    [/^at\n(.+)recruits\n(.+)\((.+) to go\)$/, '需要招募\n$1 人\n$2(还需 $3 人)'],
    [/^Your Recruits \((.+) total, (.+) qualified\)$/, '你的招募（总共 $1 人，$2 人合格）'],
    [/^Approximately (.+) hrs remaining$/, '大约剩余 $1 小时'],
    [/^Welcome back, Commander (.+)!$/, '欢迎回来，$1 指挥官！'],
    [/^✅ Research started! Will finish in (.+)h (.+)m (.+)s.$/, '✅ 研究开始了！将在 $1小时 $2分 $3秒 后完成。'],
    [/^✅ Login successful. Welcome back, (.+)!$/, '✅ 登录成功. 欢迎回来, $1！'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Population \+([\d\.]+)\% \(([\d\.]+)h\)$/, '人口 +$1% ($2小时)'],
    [/^Offense \+([\d\.]+)\% \(([\d\.]+)h\)$/, '进攻 +$1% ($2小时)'],
    [/^Research \+([\d\.]+)\% \(([\d\.]+)h\)$/, '研究 +$1% ($2小时)'],
    [/^Research \+([\d\.]+)\% \(([\d\.]+)h\) x([\d\.]+)$/, '研究 +$1% ($2小时) x$3'],
    [/^Defense \+([\d\.]+)\% \(([\d\.]+)h\) x([\d\.]+)$/, '防御 +$1% ($2小时) x$3'],
    [/^Offense \+([\d\.]+)\% \(([\d\.]+)h\) x([\d\.]+)$/, '进攻 +$1% ($2小时) x$3'],
    [/^Population \+([\d\.]+)\% \(([\d\.]+)h\) x([\d\.]+)$/, '人口 +$1% ($2小时) x$3'],
    [/^Research Speed Up \(([\d\.]+)h\) x([\d\.]+)$/, '研究加速 ($1小时) x$2'],
    [/^Research Speed Up \(([\d\.]+)d\) x([\d\.]+)$/, '研究加速 ($1天) x$2'],
    [/^Research Speed Up \(([\d\.]+)m\) x([\d\.]+)$/, '研究加速 ($1分钟) x$2'],
    [/^Defense \+([\d\.]+)\% \(([\d\.]+)h\)$/, '防御 +$1% ($2小时)'],
    [/^([\d\.]+)\% \(([\d\.]+)h\)$/, '$1% ($2小时)'],
    [/^([\d\.]+)\% \(([\d\.]+)h\) x([\d\.]+)$/, '$1% ($2小时) x$3'],
    [/^Military Decoy ([\d\.]+)\% \(([\d\.]+)h\)$/, '军事诱饵 $1% ($2小时)'],
    [/^Military Decoy ([\d\.]+)\% \(([\d\.]+)h\) x([\d\.]+)$/, '军事诱饵 $1% ($2小时) x$3'],
    [/^Research Speed Up \(([\d\.]+)h\)$/, '研究加速 ($1小时)'],
    [/^Research Speed Up \(([\d\.]+)m\)$/, '研究加速 ($1分钟)'],
    [/^Research Speed Up \(([\d\.]+)d\)$/, '研究加速 ($1天)'],
    [/^Peace Treaty \(([\d\.]+) Days\)$/, '和平条约 ($1天)'],
    [/^Peace Treaty \(([\d\.]+) Day\)$/, '和平条约 ($1天)'],
    [/^Peace Treaty \(([\d\.]+) Day\) x([\d\.]+)$/, '和平条约 ($1天) x$2'],
    [/^\+([\d\.]+)\% Attack$/, '+$1% 攻击'],
    [/^\+([\d\.]+)\% Defense$/, '+$1% 防御'],
    [/^\+([\d\.]+)\% Economy$/, '+$1% 经济'],
    [/^\+([\d\.]+)\% land survey yield.$/, '+$1% 土地调查产出。'],
    [/^\+([\d\.]+)\% population growth.$/, '+$1% 人口增长。'],
    [/^\+([\d\.]+)\% Oil Production.$/, '+$1% 石油生产。'],
    [/^\+([\d\.]+)\% land survey yield.$/, '+$1% 土地调查产出。'],
    [/^\+([\d\.]+)\% land per bot attack.$/, '+$1% 土地来自每次机器人攻击。'],
    [/^\+([\d\.]+)\% vs. aircraft.$/, '+$1% 对于飞机。'],
    [/^\+([\d\.]+)\% money production.$/, '+$1% 金钱生产。'],
    [/^\+([\d\.]+)\% metal production.$/, '+$1% 金属生产。'],
    [/^\+([\d\.]+)\% attack bonus.$/, '+$1% 攻击加成。'],
    [/^\+([\d\.]+)\% defense bonus.$/, '+$1% 防御加成。'],
    [/^\+([\d\.]+)\% research speed.$/, '+$1% 研究速度。'],
    [/^\+([\d\.]+)\% bomber damage.$/, '+$1% 轰炸机伤害。'],
    [/^\+([\d\.]+)\% aircraft damage.$/, '+$1% 飞机伤害。'],
    [/^\+([\d\.]+)\% tank damage.$/, '+$1% 坦克伤害。'],
    [/^\+([\d\.]+)\% damage vs bots.$/, '+$1% 对机器人的伤害。'],
    [/^\+([\d\.]+)\% defense vs bots.$/, '+$1% 对机器人的防御。'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) money,\n(.+) metal.$/, '$1 金钱,\n$2 金属.'],
    [/^(.+)\(base (.+) × multiplier ×(.+) \+ flat (.+)\).$/, '$1（基数 $2 × 乘数 ×$3 + 平 $4）。'],
    [/^([\d\.,]+) of ([\d\.,]+) slots filled$/, '$1 / $2 槽位已用'],
    [/^Enabling in ([\d\.,]+) cycles…$/, '$1 个周期后开启…'],
    [/^On cost: ([\d\.,]+) each \| Off cost: ([\d\.,]+) each$/, '开启成本: $1 每个 | 关闭成本: $2 每个'],
    [/^([\d\.,]+) total • Page ([\d\.,]+) of ([\d\.,]+)$/, '总计 $1 • 页 $2 / $3'],
    [/^([\d\.,]+) tiles$/, '$1 地块'],
    [/^([\d\.,]+) Loot Drops$/, '$1 战利品掉落'],
    [/^([\d\.,]+) remaining$/, '剩余 $1'],
    [/^([\d\.,]+) Income Cycle$/, '$1 收入循环'],
    [/^([\d\.,]+) more to claim.\n(.+)$/, '$1 待领取。\n$2'],
    [/^([\d\.,]+) oil$/, '$1 石油'],
    [/^([\d\.,]+) members$/, '$1 成员'],
    [/^([\d\.,]+) turrets built.$/, '已建造 $1 炮塔。'],
    [/^([\d\.,]+) Crew$/, '$1 兵团'],
    [/^([\d\.,]+) Metal$/, '$1 金属'],
    [/^([\d\.,]+) Money$/, '$1 金钱'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Income Cycles$/, '$1 收入周期'],
    [/^([\d\.,]+) Diamonds$/, '$1 钻石'],
    [/^([\d\.,]+) crew trained.$/, '已训练 $1 成员。'],
    [/^([\d\.,]+)h ([\d\.,]+)m$/, '$1 小时 $2 分'],
    [/^([\d\.,]+) Diamonds, ([\d\.,]+) wild shards$/, '$1 钻石, $2 狂野碎片'],
    [/^([\d\.,]+) Cities Mobilized$/, '$1 动员城市'],
    [/^Research Net Worth ([\d\.,]+)$/, '研究净值 $1'],
    [/^Random Teleport x([\d\.,]+)$/, '随机传送 x$1'],
    [/^Targeted Teleport x([\d\.,]+)$/, '定向传送 x$1'],
    [/^Need ([\d\.,]+) more$/, '还需要 $1'],
    [/^Start Level ([\d\.,]+)$/, '开始等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^(.+) \(Lvl ([\d\.,]+)\)$/, '$1 (等级 $2)'],
    [/^Money \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Money \+(.+)\% \((.+)h\) ×(.+)$/, '金钱 +$1% ($2小时) ×$3 • 金钱 +$4% ($5小时) ×$6'],
    [/^Money \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+)$/, '金钱 +$1% ($2小时) ×$3'],
    [/^Oil \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Oil \+(.+)\% \((.+)h\) ×(.+)$/, '石油 +$1% ($2小时) ×$3 • 石油 +$4% ($5小时) ×$6'],
    [/^Oil \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+)$/, '石油 +$1% ($2小时) ×$3'],
    [/^Metal \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Metal \+(.+)\% \((.+)h\) ×(.+)$/, '金属 +$1% ($2小时) ×$3 • 金属 +$4% ($5小时) ×$6'],
    [/^Metal \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+)$/, '金属 +$1% ($2小时) ×$3'],
    [/^Population \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+)$/, '人口 +$1% ($2小时) ×$3'],
    [/^Targeted Teleport ×(.+) • Peace Treaty \((.+) Day\) ×(.+)$/, '定向传送 ×$1 • 和平条约 ($2 天) ×$3'],
    [/^Offense \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Defense \+(.+)\% \((.+)h\) ×(.+)$/, '进攻 +$1% ($2小时) ×$3 • 防御 +$4% ($5小时) ×$6'],
    [/^Peace Treaty \(([\d\.,]+) Days\) ×(.+) • Research \+(.+)\% \((.+)h\) ×(.+)$/, '和平条约 ($1天) ×$2 • 研究 +$3% ($4小时) ×$5'],
    [/^Research Speed Up \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Research \+(.+)\% \((.+)h\) ×(.+)$/, '研究加速 +$1% ($2小时) ×$3 • 研究 +$4% ($5小时) ×$6'],
    [/^Research Speed Up \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Peace Treaty \+(.+)\% \((.+)h\) ×(.+)$/, '研究加速 +$1% ($2小时) ×$3 • 和平条约 +$4% ($5小时) ×$6'],
    [/^Research Speed Up \(([\d\.,]+)h\) ×(.+) • Research \+(.+)\% \((.+)h\) ×(.+)$/, '研究加速 ($1小时) ×$2 • 研究 +$3% ($4小时) ×$5'],
    [/^Research Speed Up \(([\d\.,]+)m\) ×(.+) • Research \+(.+)\% \((.+)h\) ×(.+)$/, '研究加速 ($1分钟) ×$2 • 研究 +$3% ($4小时) ×$5'],
    [/^Research Speed Up \(([\d\.,]+)d\) ×(.+) • Peace Treaty \((.+) Days\) ×(.+)$/, '研究加速 ($1天) ×$2 • 和平条约 ($3 天) ×$4'],
    [/^([\d\.,]+) draws \— Military Decoy ([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Defense \+(.+)\% \((.+)h\) ×(.+)$/, '$1 平局 - 军事诱饵 $2% ($3小时) ×$4 • 防御 +$5% ($6小时) ×$7'],
    [/^([\d\.,]+) draws \— Military Decoy ([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Offense \+(.+)\% \((.+)h\) ×(.+)$/, '$1 平局 - 军事诱饵 $2% ($3小时) ×$4 • 攻击 +$5% ($6小时) ×$7'],
    [/^([\d\.,]+) draws \— Research Speed Up \(([\d\.,]+)d\) ×(.+) • Peace Treaty \((.+) Days\) ×(.+)$/, '$1 平局 - 研究加速 ($2天) ×$3 • 和平条约 ($4天) ×$5'],
    [/^([\d\.,]+) draws \— Peace Treaty \(([\d\.,]+) Days\) ×(.+) • Targeted Teleport ×(.+)$/, '$1 平局 - 和平条约 ($2天) ×$3 • 定向传送  ×$4'],
    [/^Military Decoy \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Defense \+(.+)\% \((.+)h\) ×(.+)$/, '军事诱饵 +$1% ($2小时) ×$3 • 防御 +$4% ($5小时) ×$6'],
    [/^Military Decoy ([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+) • Defense \+(.+)\% \((.+)h\) ×(.+)$/, '军事诱饵 $1% ($2小时) ×$3 • 防御 +$4% ($5小时) ×$6'],
    [/^Military Decoy \+([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+)$/, '军事诱饵 +$1% ($2小时) ×$3'],
    [/^Military Decoy ([\d\.,]+)\% \(([\d\.,]+)h\) ×(.+)$/, '军事诱饵 $1% ($2小时) ×$3'],
    [/^Pack of ([\d\.,]+) Diamonds$/, '$1 钻石包'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) contributed to the treasury: (.+) Metal.$/, '$1 捐献了 $2 金属 到联盟宝库。'],
    [/^(.+) contributed to the treasury: (.+) Money.$/, '$1 捐献了 $2 金钱 到联盟宝库。'],
    [/^(.+) contributed to the treasury: (.+) Population.$/, '$1 捐献了 $2 人口 到联盟宝库。'],
    [/^(.+) contributed to the treasury: (.+) Oil.$/, '$1 捐献了 $2 石油 到联盟宝库。'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Cabal Sentry (.+)$/, 'Cabal Sentry $1'],
    [/^Block (.+)$/, '块 $1'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();