// ==UserScript==
// @name         Rocky Idle 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.20
// @description  网页游戏 Rocky Idle (https://rockyidle.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Rocky Idle.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://rockyidle.com/favicon.ico
// @license      MIT
// @include      *https://rockyidle.com/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/rocky-idle-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/rocky-idle-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/12/05 18:09
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Continue as Guest": "以游客身份试玩",
    "JOIN US ON": "加入我们在",
    "or": "或",
    "Rocky Idle": "洛奇放置",
    "Sign in": "登录",
    "Start Benchmark (": "开始基准测试 (",
    "WISHLIST ON": "加入愿望单",
    "Add New Character": "添加新角色",
    "Bank Available": "银行可用",
    "Character #": "角色 #",
    "Character Avatar": "角色头像",
    "Character Mode": "角色模式",
    "Character Name": "角色名称",
    "Character Overview": "角色概览",
    "City": "城市",
    "City Mode": "城市模式",
    "Countryside": "乡村",
    "Countryside Mode": "乡村模式",
    "Create Character": "创建角色",
    "Create your character": "创建你的角色",
    "In City Mode players can buy all items in the shop": "在城市模式中，玩家可以在商店中购买所有的道具",
    "In Countryside Mode players needs to get all items themselves": "在乡村模式中，玩家需要自己获得所有道具",
    "In Wilderness Mode players has no bank and needs to get all items themselves": "在荒野模式中，玩家没有银行，需要自己获得所有道具",
    "Limited Shop": "有限商店",
    "Login": "登录",
    "Shop Available": "商店可用",
    "Upload": "上传",
    "Wilderness": "荒野",
    "Wilderness Mode": "荒野模式",
    "To pick up a draggable item, press the space bar.\n    While dragging, use the arrow keys to move the item.\n    Press space again to drop the item in its new position, or press escape to cancel.": "要拿起一个可拖动的物品，按空格键。\n拖动过程中，使用方向键移动物品。\n再次按空格键将物品放到新的位置，或按Escape键取消。",
    "Account Overview": "帐户简介",
    "Bank": "银行",
    "Boosts": "提升",
    "Chests": "宝箱",
    "Collection Log": "收藏品日志",
    "Combat": "战斗",
    "Destroy anyways": "无论如何都要摧毁",
    "Drop warning shows if the item is untradeable or its price exceeds:": "掉落警告显示物品是否不可交易或其价格超过：",
    "I am a Noob": "我是一个新手",
    "Landing page": "登录页",
    "Last cloud save:": "最后一次云保存：",
    "Monster": "怪物",
    "Monsters": "怪物",
    "No Cloud save": "无云保存",
    "No Current Processes": "当前无进度",
    "Quests": "任务",
    "Sell": "出售",
    "Shops": "商店",
    "Skilling": "技能",
    "Slayer": "杀手",
    "This will destroy the item forever, and you will not be able to pick it up again.": "这将永远销毁该物品，并且您将无法再次拾取它。",
    "Warning": "警告",
    "You died!": "你挂了!",
    "Accuracy": "精准",
    "Attack": "攻击",
    "Attack potion": "攻击药水",
    "arrows": "箭",
    "Coins": "金币",
    "Damage": "伤害",
    "G8tess": "G8tess",
    "Go to Account overview page": "进入账户概述页面",
    "Hitpoints": "生命值",
    "Level Req:": "等级要求：",
    "Magic": "魔法",
    "Magic Damage": "魔法伤害",
    "Ranged Damage": "远程伤害",
    "minnow": "鲦鱼",
    "Strength": "力量",
    "Strength potion": "力量药水",
    "Wind sigil": "风之印记",
    "Wooden staff": "木杖",
    "Alchemy": "炼金术",
    "Arcanery": "奥术",
    "Cooking": "烹饪",
    "Crafting": "制作",
    "Defence": "防御",
    "Farming": "农业",
    "Fishing": "钓鱼",
    "Fletching": "造箭",
    "Go to landing page": "转到登录页",
    "Mining": "采矿",
    "Next level at:": "下一级：",
    "Open bank": "打开银行",
    "Prayer": "祈祷",
    "Ranged": "远程",
    "Remaining XP:": "剩余经验:",
    "Remaining xp:": "剩余经验:",
    "Smithing": "锻造",
    "Thieving": "偷窃",
    "Woodcutting": "伐木",
    "XP:": "经验值：",
    "Last saved:": "上次保存：",
    "Local save": "本地保存",
    "Lv:": "等级：",
    "No cloud save": "无云保存",
    "now": "现在",
    "Play": "玩游戏",
    "Save to cloud": "保存到云",
    "Xp:": "经验值：",
    "Copy Local": "复制本地存档",
    "Delete Local": "删除本地存档",
    "Delete local": "删除本地存档",
    "Download Local": "下载本地存档",
    "Copied": "已复制",
    "Delete account": "删除账号",
    "Logout": "登出",
    "Refresh cloud saves": "刷新云存储",
    "This will delete the account & ALL Cloud saves forever. THIS CAN NOT BE UNDONE.": "这将永久删除帐户和所有云存储。这是不可撤销的。",
    "Saves refreshed successfully!": "保存刷新成功!",
    "Cloud save is up to date": "云保存是最新的",
    "In sync": "同步中",
    "Are you sure you want to delete this local slot?": "您确定要删除这个本地槽位吗？",
    "Set": "套装",
    "Sea Dmg Bonus": "海洋伤害加成",
    "Slayer Dmg Bonus": "杀手伤害加成",
    "Dmg Bonus": "伤害加成",
    "Mine Dmg Bonus": "采矿伤害加成",
    "Market Dmg Bonus": "市场伤害加成",
    "Forest Dmg Bonus": "森林伤害加成",
    "Field Dmg Bonus": "农田伤害加成",
    "Market Dmg Bonus": "市场伤害加成",
    "Range": "远程",
    "Range Set": "远程套装",
    "Magic Set": "魔法套装",
    "Magic Defence": "魔法防御",
    "Magic Accuracy": "魔法精准",
    "Melee Defence": "近战防御",
    "Melee Accuracy": "近战精准",
    "Ranged Defence": "远程防御",
    "Ranged Accuracy": "远程精准",
    "Melee": "近战",
    "Melee Set": "近战套装",
    "Other Bonuses": "其他加成",
    "Gear sets & stats": "装备套装 & 属性",
    "Melee": "近战",
    "Hit chance": "命中率",
    "Accuracy Bonus": "精确度加成",
    "Activate Set": "激活的套装",
    "Attack speed": "攻击速度",
    "Block chance": "格挡几率",
    "Combat Level:": "战斗等级：",
    "Damage Bonus": "伤害加成",
    "Defence Bonus": "防御加成",
    "Gear stats": "装备属性",
    "Max hit": "最大攻击",
    "Account created:": "帐户创建于:",
    "Downgrade": "降级",
    "Downgrade to": "降级为",
    "Edit Amount": "编辑数量",
    "In game time:": "游戏内时间：",
    "Ruin account": "毁了账户",
    "This will downgrade your account to Countryside Mode. THIS CAN NOT BE UNDONE.": "这将降低你的帐户到乡村模式。这是不可撤销的",
    "This will remove the Countryside Mode status forever. THIS CAN NOT BE UNDONE.": "这将永久解除乡村模式状态。这是不可撤销的",
    "Delete Account": "删除账户",
    "Upload Save": "上传存档",
    "No response from server. Check your connection.": "服务器没有响应。请检查你的连接。",
    "Show": "显示",
    "Cloud save": "云存储",
    "Hide": "隐藏",
    "Newest Save": "最新存档",
    "Save to local": "保存到本地",
    "Overwrite cloud": "覆盖云存档",
    "Local save will overwrite cloud save": "本地存档将覆盖云存档",
    "book": "书",
    "Level": "等级",
    "Other": "其它",
    "Read the": "读",
    "Spells": "法术",
    "A blast of lightning": "一个爆炸的闪电",
    "A burst of nature's wrath": "大自然的暴怒",
    "A burst of shadowy energy": "一股神秘的能量爆发",
    "A freezing blast of ice": "一阵冰冷的寒冰",
    "A powerful earth pulse": "一个强大的地球脉冲",
    "A powerful fire pulse": "一个强大的火脉冲",
    "A powerful freezing burst of ice": "强大的寒冰爆发",
    "A powerful water pulse": "一个强大的水脉冲",
    "A powerful wind pulse": "一个强大的风脉冲",
    "A quick strike of lightning": "闪电的快速打击",
    "A strong earth spell": "强大的土系法术",
    "A strong fire spell": "强大的火系法术",
    "A strong water spell": "强力水系法术",
    "A strong wind spell": "强风法术",
    "A wave of nature's fury": "大自然的愤怒之波",
    "A wave of shadowy flames": "一波阴影般的火焰",
    "Arcane Touch": "奥术之触",
    "Battle Focus": "战斗专注",
    "Celestial Marksman": "天神射手",
    "Divine Augury": "神圣预兆",
    "Eagle Spirit": "鹰之灵识",
    "Earth burst": "大地爆发",
    "Earth pulse": "地球脉冲",
    "Fire burst": "火焰爆发",
    "Fire pulse": "火焰脉冲",
    "Holy Ferocity": "神圣的凶猛",
    "Ice blast": "冰爆炸",
    "Ice burst": "冰爆发",
    "Lightning blast": "雷暴",
    "Lightning strike": "雷击",
    "Magic prayer unlock": "魔法祈祷解锁",
    "Melee prayer unlock": "近战祈祷解锁",
    "Mystic Veil": "神秘面纱",
    "Nature burst": "自然爆发",
    "Nature wave": "自然波",
    "Prayers": "祈祷者",
    "Ranged prayer unlock": "远程祈祷解锁",
    "Shadow burst": "暗影爆发",
    "Shadow flame": "暗影火焰",
    "Starbound Ward": "星界结界",
    "Strike Aura": "打击光环",
    "Titan Aspect": "泰坦相位",
    "True Sight": "真实视觉",
    "Void Vigil": "虚空守夜",
    "Water burst": "突水",
    "Water pulse": "水脉冲",
    "Wind burst": "风爆",
    "Wind pulse": "风脉冲",
    "Birds nest": "鸟巢",
    "Chest count:": "宝箱数量：",
    "Easy mystery chest": "初级神秘宝箱",
    "Expert mystery chest": "专家神秘宝箱",
    "Fire sigil": "火之印记",
    "Geodes": "晶洞",
    "Hard mystery chest": "上级神秘宝箱",
    "Medium mystery chest": "中级神秘宝箱",
    "Open": "打开",
    "Oyster": "牡蛎",
    "Pine log": "松树原木",
    " token": "代币",
    "Arcanery token": "奥术代币",
    "Baobab log": "猴面包树原木",
    "Barkwraith token": "树皮幽灵代币",
    "Beech log": "山毛榉原木",
    "Birch log": "桦木原木",
    "Bone grave": "骨墓",
    "Cherry blossom log": "樱花原木",
    "Crop basket": "作物篮",
    "Earth sigil": "大地印记",
    "Easy mystery key": "简易神秘钥匙",
    "Ebony log": "乌木原木",
    "Eucalyptus log": "桉树原木",
    "Expert mystery key": "专家神秘钥匙",
    "Farming token": "农业代币",
    "Fishing token": "钓鱼代币",
    "Gem golem token": "宝石魔像代币",
    "Glyph case": "象形文字箱",
    "Hard mystery key": "困难的神秘钥匙",
    "Harley token": "哈雷代币",
    "Ice sigil": "寒冰印记",
    "Infernal dragon token": "地狱龙代币",
    "Lightning sigil": "闪电印记",
    "Medium mystery key": "中级神秘钥匙",
    "Mining token": "采矿代币",
    "Nature sigil": "自然印记",
    "Oak log": "橡木原木",
    "Raw carp": "生鲤鱼",
    "Raw catfish": "生鲶鱼",
    "Raw lobster": "生龙虾",
    "Raw mahi mahi": "生鲯鳅鱼",
    "Raw octopus": "生章鱼",
    "Raw red snapper": "生红鲷鱼",
    "Raw silver minnow": "生银鲦鱼",
    "Raw tuna": "生金枪鱼",
    "Rock fragment": "岩石碎块",
    "Scroll bottle": "卷轴瓶",
    "Sea snake token": "海蛇代币",
    "Shadow sigil": "暗影印记",
    "Thieving token": "偷窃代币",
    "Water sigil": "水之印记",
    "Woodcutting token": "伐木代币",
    "Lv": "等级",
    "Lv.": "等级",
    "Loot": "战利品",
    "XP": "经验值",
    "You are now level": "你现在是等级",
    "Total:": "总计:",
    "Tier:": "层级:",
    "Upgrades": "升级",
    "Start Quest": "开始任务",
    "Silver": "银",
    "Speed": "速度",
    "Rock": "岩石",
    "Rock Hammer": "岩石锤",
    "Rock Pickaxe": "岩石镐",
    "Ruby": "红宝石",
    "Points": "点数",
    "Medium": "中等",
    "Hard": "困难",
    "Mining boss": "采矿Boss",
    "Mining Legend": "采矿传说",
    "Level:": "等级:",
    "Level Up,": "升级了,",
    "Gold": "黄金",
    "hours": "小时",
    "Easy": "简单",
    "Buy": "购买",
    "Continue": "继续",
    "Completed Quests": "已完成任务",
    "Crop Master": "作物大师",
    "Diamond": "钻石",
    "Difficulty": "难度",
    "Duration:": "持续时间:",
    "- Next unlock in": " - 距离下一个解锁还需",
    "~1s": "~1秒",
    "Bronze": "青铜",
    "Skilling level up": "技能升级了",
    "Skilling Points": "技能点数",
    "Skilling Completed": "已完成技能",
    "Ore Kings": "矿石之王",
    "Ore Master": "矿石大师",
    "Offline progress": "离线进度",
    "Ocean Explorer": "海洋探索者",
    "No boost": "无提升",
    "Platinum": "铂金",
    "Jade": "玉石",
    "Quest Completed": "任务已完成",
    "Quest Points": "任务点数",
    "Quest Points:": "任务点数:",
    "Process Level Up!": "加工升级了!",
    "Emerald": "翡翠",
    "Expert": "专家",
    "A Fishy Start": "一个可疑的开始",
    "A Seafood Story": "一个海鲜的故事",
    "Activate skilling Boost": "激活技能加成",
    "Add to Shortcuts": "添加到快捷方式",
    "Agricultural Master": "农业大师",
    "Battle Champion": "战斗冠军",
    "Defender Training": "守军训练",
    "Depths of Fire": "火焰深度",
    "Easy mystery scroll": "简单神秘卷轴",
    "Farm Fresh": "农场生鲜",
    "Fertile Grounds": "肥沃的土壤",
    "Field Guardian": "野外守护者",
    "First Anvil": "第一个铁砧",
    "Forest Guardian": "森林守护者",
    "Fortress Sentinel": "要塞哨兵",
    "Fortune’s Edge": "财富的边缘",
    "Gemrock": "宝石",
    "Master": "大师",
    "Harvest Hero": "收获英雄",
    "Heist of the Century": "世纪大盗",
    "In depth offline progress": "深度离线进展",
    "Into the Forest": "走进森林",
    "Loot multiplier": "战利品乘数",
    "Loot multipliers": "战利品乘数",
    "Lord of the Depths": "深海之王",
    "Mariner's Wisdom": "水手的智慧",
    "Master the art of mining and smithing by working with precious metals.": "通过与贵重金属打交道，精通采矿和锻造的艺术。",
    "Mystic Adept": "神秘能手",
    "Rites of the Eternal": "永恒的仪式",
    "Rooted Troubles": "根深蒂固的问题",
    "Sapphire": "蓝宝石",
    "Serpent Hunt": "猎蛇",
    "Show Completed Quests": "显示已完成的任务",
    "Show Incompletable Quests": "显示未完成的任务",
    "Sigil of Power": "力量之印",
    "Silver and Secrets": "银与秘密",
    "Since you were gone": "自从你离开后",
    "Sparring Basics": "拳击基础知识",
    "Speed multiplier for the process based on your tier.": "根据您的段位，流程的速度倍率。",
    "Stronghold Tactician": "要塞战术家",
    "The Apprentice’s Lockpick": "学徒的开锁器",
    "The Gilded Path": "镀金之路",
    "The Stolen Scales": "被盗的鳞片",
    "This action will cancel the ongoing quest and forfeit any\n          provided items.": "此操作将取消正在进行的任务并没收所提供的物品。",
    "Tide's Tribute": "潮水的献礼",
    "Warlord Legend": "战神传说",
    "Wilderness Wisdom": "荒野智慧",
    "Woodland Master": "林地大师",
    "You died! ....Eat cooked food I my suggestion": "你挂了! ...我建议吃熟食",
    "(Lv.": "(等级",
    "and Secrets": "和秘密",
    "Amount": "数量",
    "Bank mode:": "银行模式:",
    "Sea": "海洋",
    "Pets": "宠物",
    "Name": "名称",
    "Reset": "重置",
    "Reset anyway": "无论如何都要重置",
    "Rock Rod": "岩石鱼竿",
    "Rod": "鱼竿",
    "Tasks": "任务",
    "Temple": "寺庙",
    "Undead": "亡灵",
    "Weight": "重量",
    "Your Bank": "你的银行",
    "Get Task": "获取任务",
    "Kill count:": "击杀数量:",
    "Market": "市场",
    "Melee Damage": "近战伤害",
    "Insert": "放入",
    "Forest": "森林",
    "Fishing boss": "钓鱼Boss",
    "Fields": "田地",
    "Field": "田地",
    "Current task:": "当前任务:",
    "Every task:": "每个任务:",
    "Drop Tables": "掉落表",
    "Drop tables": "掉落表",
    "Custom amount": "自定义数量",
    "Create": "创建",
    "Deposit Inventory": "存放库存",
    "All-1": "全部-1",
    "Swap": "交换",
    "Mystery Scrolls": "神秘卷轴",
    "Quantity:": "数量:",
    "Difficulties": "难度",
    "Points:": "点数:",
    "Rewards:": "奖励:",
    "Rewards": "奖励",
    "Streak:": "连击:",
    "Cancel Clue": "取消线索",
    "Cancel Mystery Scroll →": "取消神秘卷轴→",
    "Choose a custom amount to deposit": "选择要存入的自定义数量",
    "Mine": "矿山",
    "Minions": "仆从",
    "This will remove the current clue and all progress made on it. Are you sure?": "这将删除当前的线索和所有的进展。你确定吗？",
    "This will reset your slayer streak back to 0, and remove your current slayer task.": "这将重置你的杀手连击为0，并删除你当前的杀手任务。",
    "You don't have the required level": "等级不足",
    " Clue": "线索",
    "Woodcutting boss": "伐木Boss",
    "Tuna": "金枪鱼",
    "Pet bag": "宠物袋",
    "Oak": "橡树",
    "New Item:": "新物品:",
    "Not enough items": "物品不足",
    "Items": "物品",
    "Key ring": "钥匙扣",
    "Fortress": "要塞",
    "Pine": "松树",
    "Quest item": "任务物品",
    "Quest in progress": "进行中的任务",
    "Quest Completed!": "任务已完成!",
    "Can't sell": "不能出售",
    "Buy Anyways": "无论如何都要购买",
    "Bows": "弓",
    "All Shops": "所有商店",
    "Achievement": "成就",
    "(Total time:": "(总时间:",
    "(90% Buy Price)": "(90% 购买价格)",
    "Choose a custom amount to BUY": "选择一个自定义的购买数量",
    "Empty": "空",
    "Field boots": "田地提升",
    "Field shoes": "田地鞋",
    "Forest boots": "森林提升",
    "Forest shoes": "森林鞋",
    "Market shoes": "市场鞋",
    "Market boots": "市场提升",
    "Mine shoes": "矿山鞋",
    "Mine boots": "矿山提升",
    "Sea shoes": "海洋鞋",
    "Sea boots": "海洋提升",
    "shoes": "鞋",
    "boots": "靴",
    "Sell all": "全部出售",
    "Sell All Anyway": "无论如何都全部出售",
    "Rock Axe": "岩石斧",
    "Rock Knife": "岩石刀",
    "Stop Quest": "停止任务",
    "Catfish": "鲶鱼",
    "Achieve mastery over all gemstones and become the ultimate miner by preparing gear for a whole army.": "通过为整个军队准备装备，掌握所有宝石并成为终极矿工。",
    "Baobab": "猴面包树",
    "Baobab bow": "猴面包树弓",
    "Become a legend of the mines by mastering the deepest and most dangerous caves.": "通过掌握最深和最危险的洞穴，成为矿山的传奇。",
    "Beech": "山毛榉",
    "Beech bow": "山毛榉弓",
    "Birch": "桦树",
    "Birch bow": "桦弓",
    "Carp": "鲤鱼",
    "Cherry Blossom": "樱花",
    "Claim reward inside quests page": "在任务页面中领取奖励",
    "Collection log": "收集日志",
    "Craft the most potent sigil using rare materials and masterful techniques to channel divine energy.": "使用稀有的材料和高超的技术制作最强大的印记来引导神圣的能量。",
    "Current Upgrade": "当前升级",
    "Discover the hidden ways of thievery and learn basic crafting techniques to aid your adventures.": "发现隐藏的偷窃方式，学习基本的制造技术，帮助你的冒险。",
    "Ebony": "乌木",
    "Ebony bow": "乌木弓",
    "Eucalyptus": "桉树",
    "Food sack": "食物袋",
    "Get into the deepest mines and forge equipment from the strongest material.": "进入最深的矿井，用最坚硬的材料锻造设备。",
    "Hone your defensive skills and prepare for more challenging battles in the fortress.": "磨练你的防御技能，准备在堡垒中进行更具挑战性的战斗。",
    "Learn the fundamentals of combat and basic weapon handling in the fortress arena.": "学习基本的战斗和基本武器操作在堡垒竞技场。",
    "Learn to cut wood in the forest and craft your first bow.": "学习在森林里砍木头，制作你的第一把弓。",
    "Learn to fish in the shallow coastal waters and prepare your first catch.": "学会在浅水区钓鱼，准备好第一次钓到的鱼。",
    "Learn to mine basic ores and smelt your first bars.": "学会开采基础矿石并熔炼你的第一个金属锭。",
    "Lobster": "龙虾",
    "Magic cape": "魔法披风",
    "Mahi Mahi": "鲯鳅鱼",
    "Melee cape": "近战披风",
    "Mine the rarest ores and craft legendary equipment from precious metals.": "开采最稀有的矿石，用贵金属制作传奇装备。",
    "Minnow": "鲦鱼",
    "Octopus": "章鱼",
    "Offer bones to the temple and you will get rewarded.": "把骨头献给寺庙，你就会得到奖励。",
    "Ore sack": "矿石袋",
    "Pan": "平底锅",
    "Quest Points Required:  ": "任务点数要求：",
    "Ranged cape": "远程披风",
    "Red Snapper": "红鲷鱼",
    "Rock Pan": "岩石平底锅",
    "Seed sack": "种子袋",
    "Sigil sack": "符印袋",
    "Slingshot ammo": "弹弓弹药",
    "This will make you buy for over 1m, are you sure you want to spend that much?": "这会让你花100多万买，你确定要花那么多钱吗？",
    "This will sell all items in the inventory for cold cash.": "这将出售库存中的所有物品以获得现金。",
    "Total Quest Points:": "任务总点数：",
    "Unlock the arcane secrets of the fortress and train to become a competent magic user.": "解锁要塞的神秘秘密，训练自己成为一名合格的魔法使用者。",
    "Weak magic cape": "弱魔法披风",
    "Weak melee cape": "弱近战披风",
    "Weak ranged cape": "弱远程披风",
    "Wood sack": "木头袋",
    "Trees": "树",
    "Tiny bones": "极小骨头",
    "Small bones": "小骨头",
    "Stop Run": "停止运行",
    "Categories": "类别",
    "Boost": "提升",
    "Claim All": "全部领取",
    "Claim Reward": "领取奖励",
    "DESTROY": "摧毁",
    "DESTROY All": "全部摧毁",
    "Blue ring": "蓝戒指",
    "seeds": "种子",
    "Bla": "黑莓",
    "Blu": "蓝莓",
    "bush": "灌木",
    "Bongo": "邦戈",
    "Bob": "邦戈鼓",
    "Hp": "生命值",
    "HP": "生命值",
    "Goo": "醋栗",
    "Gooseberries": "醋栗",
    "Food": "食物",
    "Drops": "掉落",
    "Drop on Ground": "掉在地上",
    "Fight": "战斗",
    "Thieving boss": "偷窃Boss",
    "Farming boss": "农业Boss",
    "Giant bones": "巨骨",
    "Man": "男人",
    "Magic Gear": "魔法装备",
    "Magic potion": "魔法药水",
    "Necklaces": "项链",
    "Open Lamp": "打开灯",
    "One Click Plant": "一键种植",
    "One Click Harvest": "一键收割",
    "Ores table": "矿石表",
    "Ores drop table": "矿石掉落表",
    "points)": "点数)",
    "Rings": "戒指",
    "Ranged potion": "远程药水",
    "Ranged Gear": "远程装备",
    "Run Away": "逃跑",
    "Str": "草莓",
    "Strawberry": "草莓",
    "Up to:": "最多:",
    "Xp": "经验值",
    "What you see is what you get.": "所见即所得。",
    "Allows you to harvest all crops with a single click.": "一键采集所有农作物",
    "Allows you to plant all seeds with a single click.": "一键种下所有种子",
    "Always Drops": "总是掉落",
    "Arcanery boss": "奥术boss",
    "Auto Eat": "自动进食",
    "Auto Loot": "自动战利品",
    "Auto Potion": "自动药水",
    "Automatically consumes boosted potions when needed.": "在需要时自动消耗强化药水。",
    "Automatically eats food when health is low.": "生命值较低时自动进食",
    "Barkwraith Token drop table": "树皮幽灵代币掉落表",
    "Barkwraith Token table": "树皮幽灵代币表",
    "Box of goods": "货物箱",
    "Bush seeds drop table": "灌木种子掉落表",
    "Bush seeds table": "灌木种子表",
    "Bushes": "灌木",
    "Chisel": "凿子",
    "Crosier": "权杖",
    "Deposit items to inventory": "将物品存入库存",
    "Easy clue drop table": "简单线索掉落台",
    "Easy clue table": "简单线索表",
    "Hybrid": "混合",
    "Jiggy": "吉格",
    "Lock Pick": "开锁器",
    "Long Boi weeding": "龙柏除草",
    "Many boxes of goods": "许多箱货物",
    "Massive bones": "巨大的骨头",
    "Monster Drops": "怪物掉落",
    "Monster info": "怪物信息",
    "Mortar & Pestle": "研钵和研杵",
    "Nothing to claim yet": "暂无可领取",
    "Pearl stall": "珍珠摊位",
    "Pick a skill to get xp in": "选择一个技能来获得经验值",
    "Pick any skill above lv": "任意选择1级以上的技能",
    "Pine seeds": "松树的种子",
    "Pliers": "钳子",
    "Provides a +10% bonus to all Slayer tasks and +4% damage to all area monsters.": "为所有杀手任务提供+10%的加成，对所有区域怪物造成+4%的伤害。",
    "Provides a +15% bonus to all Slayer tasks and  +8% damage to all area monsters.": "为所有杀手任务提供+15%的加成，对所有区域怪物造成+8%的伤害。",
    "Provides a +5% bonus to all Slayer tasks.": "为所有杀手任务提供+5%的加成。",
    "Rock Chisel": "岩石凿子",
    "Rock Crosier": "岩石权杖",
    "Rock Lock Pick": "岩石开锁器",
    "Rock Mortar & Pestle": "岩石研钵和研杵",
    "Rock Pliers": "岩石钳子",
    "Rock Spade": "岩石铲子",
    "Rock stall": "岩石摊位",
    "stall": "摊位",
    "Rootmuncher": "食根者",
    "Scale stall": "鳞片摊",
    "Seed stall": "种子摊位",
    "Sigil stall": "符印摊位",
    "Sigils": "符印",
    "Skeleton Monk": "骷髅僧",
    "Spade": "铲子",
    "Strong Attack potion": "强力攻击药水",
    "Strong Magic potion": "强力魔法药水",
    "Strong Ranged potion": "强力远程药水",
    "Strong Strength potion": "强力力量药水",
    "This will DESTROY all items on the ground.": "这将摧毁地面上的所有物品。",
    "This will destroy the item forever.": "这将永远破坏该物品。",
    "This will lose all progress and the item rewards.": "这将失去所有的进度和道具奖励。",
    "Ores": "矿石",
    "No Gear upgrades": "无装备升级",
    "Easy clue": "简单线索",
    "Expert clue": "专家线索",
    "Hard clue": "困难线索",
    "Common fish": "普通鱼",
    "Common logs": "普通原木",
    "Rare fish": "稀有鱼",
    "Rare ores": "稀有矿石",
    "Rare logs": "稀有原木",
    "Combat Sets": "战斗套装",
    "Loot:": "战利品:",
    "Level Required": "等级要求",
    "Progress": "进度",
    "Process Required": "加工要求",
    "Medium clue": "中级线索",
    "Max Hit": "最大攻击",
    "Gem Golem Token": "宝石魔像代币",
    "Gear upgrade": "装备升级",
    "Gear upgrades": "装备升级",
    "Combat Boosts": "战斗提升",
    "Bush seeds": "灌木种子",
    "Active boost": "激活提升",
    "Sea Snake Token": "海蛇代币",
    "Quest Required": "任务要求",
    "Prayer Books": "祈祷之书",
    "Speed:": "速度:",
    "Tier info": "层级信息",
    "Tree seeds": "树木种子",
    " Token": "代币",
    "Barkwraith Token": "树皮幽灵代币",
    "chainbody": "链甲",
    "Combat Points Unlocks": "战斗点数解锁",
    "Face the ancient spirits of the forest and craft powerful weapons from rare logs.": "面对森林的古老灵魂，用稀有的原木制作强大的武器。",
    "Harley": "哈雷",
    "Harley Token": "哈雷代币",
    "Herbwarden": "草属植物",
    "Infernal Dragon": "地狱龙",
    "Infernal Dragon Token": "地狱龙代币",
    "Learn to grow your first crops and harvest the fruits of your labor.": "学会种植你的第一批庄稼，收获你劳动的果实。",
    "Master the art of woodcutting and fletching by creating bows and arrows.": "通过制作弓箭，掌握木刻和制箭的艺术。",
    "Medium mystery scroll": "中级神秘卷轴",
    "Monster Required": "怪物需求",
    "No Beserker boosts": "暂无狂战士加成",
    "Serpia": "蛇鹈",
    "Sigil Guardian": "符印守护者",
    "Skilling Boosts": "技能提升",
    "Skilling Points Unlocks": "技能点解锁",
    "Steel-Back Lizard": "钢背蜥蜴",
    "Combat level up": "战斗升级了",
    "Destroy": "摧毁",
    "Rolls": "投掷",
    "Combat Completed": "战斗已完成",
    "Put items in inventory": "把物品放入库存",
    "Wield": "挥舞",
    "Not enough or incorrect type of ammunition": "弹药不足或弹药种类不正确",
    "Activate combat Boost": "激活战斗提升",
    "Giants": "巨人",
    "difficulty": "难度",
    "Deposit all items from inventory to the bank": "将库存中的所有物品存入银行",
    "No quests found": "未发现任务",
    "of": "是",
    "with": "给予",
    "XP rewards": "经验奖励",
    "You are dead...": "你已经挂了...",
    "Drop rolls, and kill count multiplier based on your tier(will roll if its not a round number)": "掉落投掷，并杀死基于你的层数乘数（将投掷，如果它不是一个整数）",
    "Delete mode": "删除模式",
    "Kill count": "击杀数量",
    "Destroy all items": "摧毁所有物品",
    "Puts all drops on the ground": "把所有的掉落都放到地上",
    "Puts drops directly into the inventory": "将掉落物品直接放入库存中",
    "Search item drops": "搜索掉落物品",
    "Puts drops on the floor if its not in the inventory": "把掉落的东西放在地上，如果它不在库存中",
    "Empty flask": "空瓶",
    "Done": "完成",
    "Claim": "领取",
    "Blueberries": "蓝莓",
    "Run Completed!": "运行已结束!",
    "Strawberries": "草莓",
    "Start all runs": "开始所有运行",
    "Achieve mastery over all agricultural arts and grow the most exotic crops.": "精通所有农艺，种植最奇异的作物。",
    "Become a hero of the harvest by growing rare crops and managing complex fields.": "通过种植稀有作物和管理复杂的田地，成为收获的英雄。",
    "Become the ultimate guardian of the fields by mastering all farming arts and protecting the sacred harvest grounds.": "通过掌握所有的农业艺术和保护神圣的收获土地，成为田地的终极守护者。",
    "Cultivate the most fertile grounds and grow the finest crops with advanced techniques.": "用先进的技术培育最肥沃的土地，种植最好的作物。",
    "Master the art of farming by growing diverse crops and managing your fields.": "通过种植不同的作物和管理你的田地，掌握农业的艺术。",
    "Snapper": "鲷鱼",
    "Clue": "线索",
    "Reward:": "奖励:",
    "Total Completed:": "总计完成:",
    "Mystery Scroll Completed!": "神秘卷轴已完成！",
    "Auto eat when at 0hp or below": "在生命值为0或以下时自动进食",
    "Prove your skill by gathering a variety of sea creatures and preparing them into a delicious meal.": "通过收集各种海洋生物并将它们准备成美味的一餐来证明你的技能。",
    " Mystery Scroll →": " 神秘卷轴 →",
    "Auto use potions when its about to expire": "药水即将过期时自动使用",
    "Deepen your connection with the divine by offering more substantial bones and receiving greater blessings.": "通过提供更坚实的骨骼和接受更大的祝福来加深你与神的联系。",
    "Ebony seeds": "乌木种子",
    "Eucalyptus seeds": "桉树种子",
    "Explore the deeper ocean waters and discover rare sea treasures.": "探索更深的海洋水域，发现稀有的海洋宝藏。",
    "Not enough inventory space": "没有足够的库存空间",
    "Offer the finest catches to appease the sea spirits and gain their favor.": "献上最好的渔获来安抚海神，赢得他们的青睐。",
    "Prove yourself as master of the ocean by catching the rarest fish.": "抓住最稀有的鱼，证明你是海洋的主人。",
    "Venture into treacherous waters to catch rare and exotic sea creatures. Beware the giant stingray lurking beneath the waves.": "冒险进入危险的水域，捕捉稀有和外来的海洋生物。小心潜伏在海浪下的巨大黄貂鱼。",
    "You haven't completed the required quest": "未完成指定任务",
    "You need to have completed the diary": "你需要完成日记",
    "scale top": "鳞片上衣",
    "scale bottom": "鳞片下衣",
    "scale feather hat": "鳞片皮帽",
    "Pine tree": "松树",
    "Eucalyptus tree": "桉树",
    "Baobab tree": "猴面包树",
    "Ebony tree": "乌木树",
    "Bosses": "Boss",
    "Blue scales": "蓝色鳞片",
    "Ammo": "弹药",
    "Neck": "脖子",
    "top": "上衣",
    "Shield": "盾牌",
    "Cape": "披风",
    "Blackberries": "黑莓",
    "Baobab seeds": "猴面包树种子",
    "Achieve legendary status in combat by mastering advanced techniques across all disciplines.": "通过掌握所有学科的先进技术，在战斗中获得传奇地位。",
    "Achieve mastery over the elemental balance by offering the most sacred bones and receiving wisdom.": "通过提供最神圣的骨头和接受智慧，实现对元素平衡的掌握。",
    "Achieve perfect balance between all elemental forces through sacred rituals.": "通过神圣的仪式达到所有元素力量之间的完美平衡。",
    "Become a legendary master of both crafting and thieving, achieving feats that few dare attempt.": "成为一个传奇的大师，在制造和偷窃，实现壮举，很少有人敢尝试。",
    "Become the ultimate guardian of the forest by mastering all woodcutting and fletching arts, and face the ancient forest spirits.": "掌握一切木雕技艺，成为森林的终极守护者，直面古老的森林精灵。",
    "Become the ultimate sentinel, mastering all combat arts and defending the fortress against the greatest threats.": "成为最终的哨兵，掌握所有的战斗艺术，捍卫堡垒对抗最大的威胁。",
    "Bring together the most powerful sacred offerings and perform the ultimate ritual to unlock massive rewards.": "汇集最强大的神圣祭品并执行终极仪式以解锁大量奖励。",
    "Get on a daring mission to recover precious crafted items while honing your stealth and skill.": "执行一项大胆的任务，在磨练你的潜行和技能的同时恢复珍贵的精心制作的物品。",
    "Hard mystery scroll": "困难神秘卷轴",
    "Lead a grand heist to secure rare materials, testing both your thieving prowess and crafting expertise.": "领导一场大抢劫，以确保稀有材料，测试你的偷窃能力和制作专业知识。",
    "Learn battlefield strategy and advanced combat skills to dominate the fortress arena.": "学习战场战略和先进的战斗技能，主宰堡垒竞技场。",
    "Loot multiplier for the run based on your tier.": "战利品乘数的运行基于你的层级。",
    "No more slot available": "没有可用的插槽",
    "Protect the forest from the invasive Burmese pythons, watch out for the twenty-footer.": "保护森林免受缅甸蟒蛇的入侵，小心那些20英尺长的蟒蛇。",
    "Prove yourself as a master of combat, excelling in strength, defense, and magic.": "证明自己是一个战斗大师，在力量，防御和魔法方面都很出色。",
    "Rise to prominence by mastering rare crafting and thieving techniques.": "通过掌握稀有的工艺和偷窃技巧来提升声望。",
    "Scale treasure": "鳞片宝藏",
    "Search monsters": "搜索的怪物",
    "Seek the ancient wisdom of the forest guardians and fletch the strong ranged gear.": "寻找森林守护者的古老智慧，并获得强大的远程装备。",
    "Sharpen your thieving skills and learn to craft useful tools for stealthy operations.": "磨砺你的偷窃技巧，并学习制作有用的工具，为隐形行动。",
    "Withdraw items from bank": "从银行提取物品",
    "XP multiplier for the run based on your tier.": "经验乘数的运行基于你的层级。",
    "yesterday": "昨天",
    "Failed to fetch user profile": "获取用户资料失败",
    "Runs tiers": "符文层级",
    "Skilling tiers": "技能层级",
    "Speedup": "加速",
    "Spell": "法术",
    "Xp & Loot": "经验值 & 战利品",
    "Streak :": "连击 :",
    "task completed": "任务已完成",
    "No spell selected.": "未选择法术。",
    "pearl": "珍珠",
    "x kills =": "x 击杀 =",
    "Ebony bark": "乌木树皮",
    " Token table": "代币表",
    "Baobab bark": "猴面包树树皮",
    "Eucalyptus bark": "桉树皮",
    "Fisher boy staff": "渔童杖",
    "Pine bark": "松树皮",
    "Sea Snake Token drop table": "海蛇代币掉落表",
    "Sea Snake Token table": "海蛇代币表",
    "Change Avatar": "更改头像",
    "Amethyst": "紫水晶",
    "Blue pearl": "蓝珍珠",
    " Token drop table": "代币掉落表",
    "Gem Golem": "宝石魔像",
    "Common": "普通",
    "Expert mystery scroll": "专家神秘卷轴",
    "Amethyst": "紫水晶",
    "Blue topaz": "蓝色黄玉",
    "claws": "爪子",
    "Mahi mahi": "鲯鳅鱼",
    "Slingshot": "弹弓",
    "snapper": "鲷鱼",
    "Already Unlocked": "已解锁",
    "Barkwraith": "树皮幽灵",
    "Combat Points": "战斗点数",
    "Eat": "吃",
    "Golem": "魔像",
    "Sea Snake": "海蛇",
    "Wraith": "幽灵",
    "You cannot kill this monster offline, since you have less hitpoints than 2x their max hit.": "你不能离线杀死这个怪物，因为你的生命值少于他们最大生命的2倍。",
    "You died! ....Eat cooked food is my suggestion": "你挂了!...我的建议是吃熟食",
    "Last played:": "最近游戏:",
    "SUPPORT ME ON": "支持作者在",
    "- Available on Steam and Web(Available for purchase on Steam at launch.)": "-可在Steam和Web上使用（可在Steam上发行时购买。）",
    "I cannot 100% promise that your game progress will be saved when the final version is released.": "我不能100%保证在最终版本发布时一定会保存您的游戏进度。",
    "This game is currently in DEMO": "这个游戏目前还处于DEMO阶段",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "club": "棍棒",
    "blade": "刀刃",
    "pickaxe": "镐",
    "apron": "围裙",
    "plate body": "板甲",
    "legs": "腿",
    "hat": "帽子",
    "tunic": "束腰外衣",
    "quiver": "箭筒",
    "bow": "弓",
    "bottom": "下衣",
    "feather hat": "皮帽",
    "hood": "兜帽",
    "necklace": "项链",
    "staff": "杖",
    "Vs": "Vs",
    "AS": "AS",
    "Har": "困难",
    "Exp": "专家",
    "Pin": "松树",
    "Amet": "紫水晶",
    "Bao": "猴面包树",
    "Ebo": "乌木",
    "Euc": "桉树",
    "scales": "鳞片",
    "ring": "戒指",
    "Shoes": "鞋子",
    "Sandals": "凉鞋",
    "Boots": "靴子",
    "Staffs": "杖",
    "Arrows": "箭头",
    "Axe": "斧",
    "Knife": "刀",
    "helm": "头盔",
    "platelegs": "板腿",
    "scimitar": "弯刀",
    "dagger": "匕首",
    "chain body": "链甲",
    "bar": "锭",
    "helmet": "盔",
    "plate legs": "板腿",
    "shield": "盾",
    "Hammer": "锤",
    "Pickaxe": "镐",
    "ore": "矿石",
    "Eas": "简单",
    "Med": "中等",
    "QP": "任务点数",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "DISCORD": "DISCORD",
    "s)": "s)",
    "STEAM": "STEAM",
    "❯": "❯",
    "/": "/",
    "Gityx": "Gityx",
    "↓": "↓",
    "~": "~",
    "!": "!",
    "✓": "✓",
    "x)": "x)",
    "&": "&",
    "GitPan": "GitPan",
    "PATREON": "PATREON",
    "KO-FI": "KO-FI",
    "⚠️": "⚠️",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    ">>": ">>",
    ">": ">",
    "<<": "<<",
    "<": "<",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Total XP:": "总经验值:",
    "Amount: ": "数量: ",
    "Speed Multiplier: ": "速度乘数: ",
    "Bronze ": "青铜",
    "Silver ": "银",
    "Platinum ": "铂金",
    "Gold ": "黄金",
    "Diamond ": "金刚石",
    "Jade ": "玉石",
    "Elemental Harmony": "元素和谐",
    "Cancel": "取消",
    "Xp Multiplier: ": "经验乘数: ",
    "Slayer ": "杀手",
    "Loot Multiplier: ": "战利品乘数: ",
    "Blackberry ": "黑莓",
    "Blueberry ": "蓝莓",
    "Gooseberry ": "醋栗",
    "Gooseberries ": "醋栗",
    "Strawberry ": "草莓",
    "Purple ": "紫色",
    "Green ": "绿色",
    "Red ": "红色",
    "Forest Guy": "森林人",
    " pet": "宠物",
    "wraith pet": "幽灵宠物",
    "Arcanery pet": "奥术宠物",
    "Wraith": "幽灵",
    "Golem": "魔像",
    "Fishing pet": "钓鱼宠物",
    "Mining pet": "采矿宠物",
    "Thieving pet": "偷窃宠物",
    "Woodcutting pet": "伐木宠物",
    "Farming pet": "农业宠物",
    "Harley pet": "哈雷宠物",
    "Infernal dragon pet": "地狱龙宠物",
    "Rock golem pet": "岩石魔像宠物",
    "Serpia pet": "蛇鹈宠物",
    "Deposit-": "存入-",
    "Withdraw-": "取出-",
    "Drop Rolls ": "掉落投掷",
    "Sproutling": "幼苗",
    "Total: ": "总计: ",
    "This Tier: ": "这个层级: ",
    "Hp:": "生命值:",
    "Blue scale ": "蓝鳞",
    "Blue topaz ": "蓝黄玉",
    "Emerald ": "翡翠",
    "Ruby ": "红宝石",
    "Angel ": "天使",
    "Amethyst ": "紫水晶",
    "Bark ": "树皮",
    "Lizard ": "蜥蜴",
    "Root ": "树根",
    "Monk ": "僧侣",
    "Temple ": "寺庙",
    "Dragon stone ": "龙石",
    "Gemstone ": "宝石",
    "Jiggy's ": "吉格的",
    "Harley's ": "哈雷的",
    "Rocky's ": "洛奇的",
    "Serpia's ": "蛇鹈",
    "Bongo's ": "邦戈",
    "Amet's ": "紫水晶",
    "Antique lamp": "古董灯",
    // 怪物
    "Bob": "鲍勃",
    "Shardling": "碎片幼体",
    "Fisher Boy": "渔童",
    "Angela": "安吉拉",
    "Bongo Sr.": "邦戈Sr.",
    "Little Rocky": "小洛奇",
    "Moss Golem": "苔藓魔像",
    "Moss ": "苔藓",
    "Steve": "史蒂夫",
    "Thorn": "荆棘",
    "Final Version Coming ": "最终版本将发布于 ",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " (Easy)": " (简单)",
    " (EASY)": " (简单)",
    " (HARD)": " (困难)",
    " Token drop table": "代币掉落表",
    " Token table": "代币表",
    " logs drop table": "原木掉落表",
    " logs table": "原木表",
    " fish drop table": "鱼掉落表",
    " fish table": "鱼表",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^可拖动(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^ ([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\(([\d\.,]+)\)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Draggable item (.+) was dropped over droppable area (.+)$/, '可拖动物品 $1 被拖动在可拖动区域 $2 上'],
    [/^Draggable item (.+) was moved over droppable area (.+).$/, '可拖动物品 $1 被移动在可拖动区域 $2 上'],
    [/^Draggable item (.+) is no longer over a droppable area.$/, '可拖动物品 $1 已不在可拖动区域上方。'],
    [/^Draggable item (.+) was dropped.$/, '可拖动物品 $1 被拖动了。'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)sec$/, '$1 秒'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% Speed$/, '+$1% 速度'],
    [/^\+([\d\.]+)\% Xp \+ Loot$/, '+$1% 经验值 + 战利品'],
    [/^\+([\d\.]+)\% Magic$/, '+$1% 魔法'],
    [/^\+([\d\.]+)\% Ranged$/, '+$1% 远程'],
    [/^\+([\d\.]+)\% Ranged and \+([\d\.]+)\% Defence$/, '+$1% 远程 和 +$2% 防御'],
    [/^\+([\d\.]+)\% Magic and \+([\d\.]+)\% Defence$/, '+$1% 魔法 和 +$2% 防御'],
    [/^\+([\d\.]+)\% Attack and \+([\d\.]+)\% Strength$/, '+$1% 攻击 和 +$2% 力量'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)h ([\d\.]+)s$/, '$1 小时 $2 秒'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)xp$/, '$1 经验值'],
    [/^([\d\.,]+) minutes and ([\d\.,]+) seconds$/, '$1 分钟 $2 秒'],
    [/^([\d\.,]+) minutes$/, '$1 分钟'],
    [/^([\d\.,]+) minute$/, '$1 分钟'],
    [/^([\d\.,]+) hour$/, '$1 小时'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^([\d\.,]+) minute ago$/, '$1 分钟前'],
    [/^([\d\.,]+) minutes ago$/, '$1 分钟前'],
    [/^([\d\.,]+) second ago$/, '$1 秒前'],
    [/^([\d\.,]+) seconds ago$/, '$1 秒前'],
    [/^([\d\.,]+) day ago$/, '$1 天前'],
    [/^([\d\.,]+) days ago$/, '$1 天前'],
    [/^([\d\.,]+) hour ago$/, '$1 小时前'],
    [/^([\d\.,]+) hours ago$/, '$1 小时前'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.,]+)s boost duration$/, '+$1 秒提升持续时间'],
    [/^\(Lv.([\d\.,]+)\)$/, '(等级 $1)'],
    [/^\-([\d\.,]+) elves$/, '-$1 精灵'],
    [/^Data saved to cloud in slot ([\d\.,]+)!$/, '数据已保存到 云存储插槽 $1!'],
    [/^Sacred Offerings ([\d\.,]+)$/, '神圣的祭品 $1'],
    [/^Out of time after ([\d\.,]+)s$/, '$1 秒后超时'],
    [/^Out of time after ([\d\.,]+)h ([\d\.,]+)m ([\d\.,]+)s$/, '$1小时 $2分钟 $3秒 后超时'],
    [/^Game saved successfully to slot ([\d\.,]+)!$/, '游戏已成功保存到槽位 $1!'],
    [/^Every ([\d\.,]+)th:$/, '每 $1:'],
    [/^Auto eat when at ([\d\.,]+)hp or below$/, '当生命值降低至 $1 或更低时，自动吃食物'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\(([\d\.,]+)xp\)\(([\d\.,]+)lv\)$/, '($1 经验值)($2 级)'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();