// ==UserScript==
// @name         Ragnarok Oblivion Idle 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.13
// @description  Ragnarok Oblivion Idle (https://roidle.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Ragnarok Oblivion Idle.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://roidle.com/assets/images/icons/favicon.ico
// @license      MIT
// @include      *https://roidle.com/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/roidle-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/roidle-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/02/13 16:00
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "This is a fan / hobby made game, done by a team of 2 with the help of the community and is currently in Open Beta access (Phase 1).\nBeta means that the core gameplay is done, but the game might still change, only not drastically.": "这是一款粉丝/业余爱好制作的游戏，由一个2人团队在社区的帮助下完成，目前处于公测阶段（第一阶段）。公测意味着核心玩法已经完成，但游戏可能仍然会改变，只是不会太大。",
    "Forgot password": "忘记密码",
    "Join our discord": "加入我们的Discord",
    "Legal and Usage of assets": "法律和使用资源文件",
    "Partial assets used under license from Gravity, the original creator of Ragnarok Online.": "部分资产在Gravity授权下使用，《诸神黄昏》的最初创造者。",
    "Register account": "注册账号",
    "Sign In": "登录",
    "Skip registration and play now": "跳过注册，立即开始游戏",
    "Terms and Conditions": "条款与条件",
    "Wall of Fame": "名人墙",
    "Close": "关闭",
    "Register": "注册",
    "Request password": "请求密码",
    "Match not found, try different combination": "没有找到匹配，请尝试不同的组合",
    "Set party name/user name": "设置队伍名称/用户名",
    "You need to set your party name. Please keep in mind this is your user name and will be used all around the game when you will be referenced or how other players can look at your profile": "你需要设置你的队伍名称。请记住，这是你的用户名，当你被引用或其他玩家查看你的个人资料时，它将在游戏中被使用",
    "Name missing": "名称不能为空",
    "Sorry, username is already taken": "对不起，用户名已被占用",
    "System": "系统",
    "Battle Log": "战斗日志",
    "Create character": "创建角色",
    "Fame Shop": "声望商店",
    "Game": "游戏",
    "Garden": "花园",
    "Refinement station": "精炼站",
    "Next": "下一个",
    "Shop": "商店",
    "Tomato": "西红柿",
    "Tutorial": "教程",
    "Hey there, you seem to be new here! Welcome to the world of Ragnarok Oblivion. This game is strongly inspired by the old MMORPG Ragnarök Online, as well as DnD and many other fantasy games. It is sort of a continuation of the story, exploring what would have happened after the Ragnarok, the War of the Gods. Let me quickly show you around so you do not get lost from the very beginning.": "嘿，你好像是新来的！欢迎来到诸神黄昏湮灭的世界。这款游戏的灵感来自于旧的MMORPG Ragnarök Online，以及DnD和许多其他幻想游戏。这是故事的延续，探索诸神之战，诸神之战之后发生的事情。让我快速带你四处看看，这样你就不会一开始就迷路了。",
    "Blue": "蓝色",
    "Patch notes": "更新日志",
    "Processing Station": "加工站",
    "Progress:": "进度:",
    "Mail": "邮件",
    "Market": "市场",
    "Mark all as read": "一键已读",
    "Log out": "登出",
    "Login into the game during Beta Test": "在Beta测试期间登录游戏",
    "Help": "帮助",
    "Characters AI": "角色AI",
    "Hunt": "狩猎",
    "Hunt Log": "狩猎日志",
    "Classes": "职业",
    "Info Center": "信息中心",
    "Install the game": "安装游戏",
    "Skills": "技能",
    "Socials": "社交",
    "Beta Tester": "Beta测试者",
    "and Title of Beta Tester, Icon of Beta Tester": "和Beta测试者的标题，Beta测试者的图标",
    "Preview": "预览",
    "Characters": "角色",
    "Welcome gift": "欢迎礼物",
    "Register or connect your account with an email": "用电子邮件注册或连接您的帐户",
    "Waypoint": "路标",
    "Inventory": "库存",
    "Infinity": "无限",
    "Tavern": "酒馆",
    "Estate": "庄园",
    "Enchantment Station": "附魔站",
    "Enchantment station": "附魔站",
    "Laboratory": "实验室",
    "Leaderboards": "排行榜",
    "Armory": "军械库",
    "Bestiary": "图鉴",
    "Cancel": "取消",
    "This is your very first character. He or she will be the main character in the main story progression. Think wisely on the gender of who will it be, as you will not be able to change it later on. Name and appearance can be changed at any time.": "这是你的第一个角色。他或她将成为主要故事进程中的主角。明智地考虑这个人的性别，因为你以后将无法改变它。名称和外观可以随时更改。",
    "Male": "男性",
    "Female": "女性",
    "This is a character screen, and you seem to have created your first character. Let's break this page down.": "这是一个角色界面，你似乎已经创建了你的第一个角色。让我们详细分析一下这一页。",
    "This is a list of your characters, where you can create new ones or switch the view for each of them.": "这是您的角色列表，您可以在其中创建新的角色或为每个角色切换视图。",
    "This is where you will see all the attributes of your characters. Allocating stats, changing equipment and switching the active class of a character will update this table immediately.": "在这里你可以看到角色的所有属性。分配属性，改变装备和切换角色的活动职业将立即更新此表。",
    "If you don't like the name you have given to your character, you can always change it here.": "如果你不喜欢你给你的角色起的名字，你可以在这里更改。",
    "hide the chat": "隐藏聊天",
    "Here you see the list of available equipment slots. Clicking them will let you equip your characters with weapons, armor and accessories. In order to do that, you need to make sure the piece of equipment is in your inventory, not in your storage (more on that later). You have started with some basic equipment, so go ahead and equip those items in your right hand and torso.": "在这里你可以看到可用装备插槽的列表。点击它们，你就可以为你的角色装备武器、盔甲和配件。为了做到这一点，你需要确保你的装备在你的库存中，而不是在你的仓库中（稍后会详细介绍）。你已经开始了一些基本的装备，所以继续在你的右手和躯干装备这些物品。",
    "See these buttons? \"Outfits\" allows you to change a character's style, like skins, headgears, masks, colors, etc. Visuals in ROIdle are unlockables tied to your account, that means as soon as it's unlocked, it can be applied to any of your characters with no limitations and changed at will. You can get more visuals from the Fame Shop.": "看到这些按钮了吗？“时装”可以改变角色的风格，如皮肤、头饰、面具、颜色等。《ROIdle》中的视觉效果是与你的账户绑定在一起的，这意味着一旦它被解锁，它就可以无限制地应用于你的任何角色，并且可以随意改变。你可以从声望商店获得更多的视觉效果。",
    "You're back from the character screen, I see. Let me show you around a bit more. This is the main screen, and here is where the main action happens. In this game your party will hunt to level up and get materials in order to craft items and become stronger. As you do quests and adventure through the land, you will uncover the history of what happened to the world of Ragnarok Oblivion.": "你从角色屏幕上回来了。让我再带你四处看看。这是主屏幕，这里是主要动作发生的地方。在这款游戏中，你的团队将通过狩猎来升级并获得材料，从而制作道具并变得更强大。当你在这片土地上进行任务和冒险时，你将揭开 诸神黄昏湮灭 世界发生的历史。",
    "The \"Stats\" button allows you to distribute stat points to your character. They will strengthen different combat capabilities, so think well where you spend them. You can read about what each stat does by clicking the left icon of each. If you're interested in formulas, you can click on the question mark that will navigate you to our wiki. You can reset your stats at any time, but keep in mind that it will cost you some zeny. There are however \"free reset weekends\" that happen on the first week of the month, when you can then do it free of charge.": "“属性”按钮允许你分配属性点给你的角色。它们将加强不同的战斗能力，所以要考虑好你把它们花在哪里。你可以通过点击左边的图标来了解每个属性的作用。如果你对公式感兴趣，你可以点击问号进入我们的wiki。你可以随时重置你的属性，但要记住，这将花费你一些金币。然而，每个月的第一周有“免费重置周末”，你可以免费重置。",
    "The \"Switch class\" button allows you to change the class of your character as much as you want. That's right, there is no permanent class selection in this game! Keep in mind that a class can be selected by only one character of your party at any given moment, no duplicates. But don't worry, in time you will unlock many more classes that will allow you to create unique combinations and combos. For more information on classes, click the \"Classes\" link from the main menu.": "“切换职业”按钮可以让你随心所欲地改变角色的职业。没错，在这个游戏中没有永久的职业选择！请记住，一个职业在任何时候只能由你队伍中的一个角色选择，不能重复。但别担心，你会解锁更多的职业，让你创造独特的组合和连击。有关职业的更多信息，请点击主菜单中的“职业”链接。",
    "Your estate is where you upgrade facilities that will allow you to craft items, have bigger storage and process construction materials. In order to get materials you need to farm raw materials from the hunts, by enabling material gathering and then process them into construction materials. When it comes to money, you can get them by selling raw materials to NPC shop, completely bounty quests or sell crafted items on the market to other players.": "你的庄园是你升级设施的地方，这将允许你制作物品，有更大的存储空间和加工建筑材料。为了获得材料，你需要从狩猎中获得原材料，通过收集材料，然后将其加工成建筑材料。说到钱，你可以通过向NPC商店出售原材料、完成悬赏任务或在市场上向其他玩家出售精心制作的物品来获得金钱。",
    "\"Hunt\" is one of the main features of the game. It allows you to send your party to hunt monsters in the wild, or delve into dungeons for better loot, but also more dangerous foes. Before doing that, make sure that your characters are properly set up, with the correct classes, equipment and battle scripts (more on that later as well).": "“狩猎”是这个游戏的主要功能之一。它允许你派遣你的队伍在野外追捕怪物，或者深入地下城寻找更好的战利品，但也会遇到更危险的敌人。在此之前，确保你的角色设置正确，拥有正确的职业，装备和战斗脚本（稍后也会详细介绍）。",
    "A place for your party to rest and recover HP and MP. It is faster if you are willing to spend a little bit. Here you also fing bounty quests, which rewards you exp and Zeny, as well as sometimes materials. They are strongly recommended for newer players to get going in the game.": "一个供你的队伍休息和恢复HP和MP的地方。如果你愿意花一点钱，它会更快。在这里，你还会遇到悬赏任务，奖励你的经验和金币，有时还会有材料。强烈建议新玩家进入游戏。",
    "For now, this is it. Those are the basics. Other tutorial windows will popup when you open the related area of the game for the first time. Don't forget to submit your ideas to us in our": "现在，就是这样了。这些是最基本的。当你第一次打开游戏的相关区域时，会弹出其他教程窗口。不要忘记把你的想法提交给我们",
    "Here you can sell and buy items from NPC's, use the Market to trade with other players and the Fame Shop to buy cool visual upgrades to flex to other players.": "在这里，你可以出售和购买NPC的物品，使用市场与其他玩家交易，并使用声望商店购买酷炫的视觉升级以向其他玩家展示。",
    "Player ID": "玩家 ID",
    "Slayer": "杀手",
    "Smithy": "铁匠铺",
    "Battle Behavior": "战斗行为",
    "Add script": "添加脚本",
    "Copy": "复制",
    "Export/Import": "导出/导入",
    "View/Edit": "查看/编辑",
    "Warrior": "战士",
    "Scout": "侦察兵",
    "Rename": "重命名",
    "Apprentice": "学徒",
    "Select character": "选择角色",
    ". You may change your script before or during battle. Once you finish your settings, click the save button at the bottom and your new setting will take effect in the next turn of combat.": "。你可以在战斗前或战斗中修改你的脚本。一旦你完成了你的设置，点击底部的保存按钮，你的新设置将在下一轮战斗中生效。",
    "done": "完成",
    "dex": "灵巧",
    "Script configuration saved": "脚本配置已保存",
    "Item info": "物品信息",
    "Reconnect": "重连",
    "Disconnected from the server.": "与服务器断开连接。",
    "HP Potion": "生命药水",
    "MP Potion": "法力药水",
    "Potions": "药水",
    "Progression": "发展",
    "Select item": "选择物品",
    "Selected item": "已选择物品",
    "Simple Bandage": "简易绷带",
    "Price for using station": "站点使用价格",
    "Pharmacy": "药店",
    "Output per success": "每次成功输出",
    "Name": "名称",
    "Max out classes": "职业已满",
    "Max": "最大",
    "Time required": "需要时间",
    "Success Chance": "成功几率",
    "Required Lvl": "要求等级",
    "Craft time": "制作用时",
    "Amount": "数量",
    "Min": "最小",
    "Here is the heart of the game. If you are a new player, please do not skip this tutorial. This section allows you to send your party to hunt monsters or delve into dungeons where you will find exclusive loot. Before doing that, make sure that your characters are properly geared and set up.": "这是游戏的核心。如果您是新玩家，请不要跳过本教程。这个部分允许你派你的队伍去猎杀怪物或深入地下城，在那里你会找到专属的战利品。在此之前，确保你的角色是适当的调整和设置。",
    "Different Areas contain different categories of monsters that you can hunt. Each has their own monsters and materials that you can farm, and in order to conquer them all you will have to find the best party composition and equipment for each type of challenge. The last category in this window is Dungeon, which unlike normal hunt areas contains a boss that has a low chance to drop legendary items.": "不同的区域包含不同类型的怪物，你可以猎杀。每个都有自己的怪物和材料，你可以种植，为了征服他们，你必须找到最好的团队组成和装备，每种类型的挑战。在这个窗口的最后一个类别是地下城，不同于普通的狩猎区域，它包含一个有低几率掉落传说物品的Boss。",
    "You can select which characters are actually going to participate in the hunt by clicking on the character portraits above. After the hunt has started, your characters border will turn red, indicating they are busy. But you can always add more characters into an active hunt. They will join the hunt, but will only start helping in the next battle.": "你可以通过点击上面的人物肖像来选择哪些角色真正要参加狩猎。狩猎开始后，你的角色边界会变成红色，表示他们很忙。但你总是可以添加更多的角色到一个积极的狩猎。它们会加入狩猎，但只会在下一场战斗中开始帮忙。",
    "Time - how long you want your party to hunt. To keep your characters safe, on lower levels it is advisable to send your characters for shorter amounts of time, so they won't die without consumables and more refined battle scripts. Very long hunt times are available for supporters of the game (check the Patreon logo in the \"burger\" menu).": "时间-你希望你的队伍狩猎多长时间。为了保证角色的安全，在较低的关卡中，最好让角色停留较短的时间，这样他们就不会在没有消耗品和更完善的战斗脚本的情况下死亡。对于游戏的支持者来说，很长的狩猎时间是可用的（检查“汉堡”菜单中的Patreon徽标）。",
    "This toggles if you want your party to hunt safely and have only 1-2 enemies at a time, or to go YOLO and fight a bunch at once: 5 enemies.": "如果你想让你的队伍安全狩猎，一次只对付1-2个敌人，或者一次性对付一群敌人（5个敌人），你就可以切换这个选项。",
    ". Meanwhile, we are working on a new and updated version of this guide.": "．与此同时，我们正在制作这个指南的一个新的更新版本。",
    "A very important part of the game, as it controls the behaviour of your party. Right now there are 3 basic scripts available, one for each starting class. Configuring them correctly will sharply affect how well your party fights. If you played games like FF12 or Pilars of Eternity, scripting will be familiar to you. But don't worry, try playing with it to get the hang of how it works. Since it is very hard to explain everything of how scripts work, there is a cool guide created by one of the players explaning it on": "这是游戏中非常重要的一部分，因为它控制着玩家的行为。现在有3个基本的脚本可用，每个初始职业一个。正确配置它们将极大地影响你的团队战斗。如果你玩过《FF12》或《永恒之柱》之类的游戏，你就会对脚本很熟悉。但别担心，试着玩一下它，了解它是如何工作的。因为很难解释脚本是如何工作的，所以有一个由玩家创建的很酷的指南来解释它",
    "Allows you to toggle if you want material nodes to appear in your hunt or not. It is a good idea to have it on, as materials sell for higher and enables crafting, unless you're concentrating on power leveling.": "允许你切换，如果你想要的材料节点出现在你的狩猎或不。这是一个好主意，因为材料可以卖得更高，并且可以制作，除非你专注于力量升级。",
    "Capital": "首都",
    "Dungeons": "地下城",
    "Mountains": "山脉",
    "Select characters": "选择角色",
    "Choose area": "选择区域",
    "Desert": "沙漠",
    "Forest": "森林",
    "Locked": "未解锁",
    "Time": "时间",
    "Battle Config": "战斗配置",
    "YOLO hunt": "YOLO狩猎",
    "Safe hunt": "安全狩猎",
    "Materials gathering off": "收集材料 关",
    "Materials gathering on": "收集材料 开",
    "Your second character. In the main story progression he or she will play a role of a best friend of your main character.": "你的第二个角色。在主要故事进程中，他或她将扮演主角最好的朋友的角色。",
    "Character name is too short, must be more than 3 characters": "角色名称太短，必须超过3个字",
    "View profile": "查看个人资料",
    "Send mail": "发送邮件",
    "Message": "消息",
    "Mention": "提到@",
    "Duel": "决斗",
    "Show:": "显示:",
    "On desktop you can use Alt+Click or Option+Click to move items ignoring the preview functionality.": "在桌面上，你可以使用 Alt + 点击（PC）或 Option + 点击（Mac）来移动物品，而忽略预览功能。",
    "Weight:": "重量:",
    "Deposit": "存入",
    "Withdraw": "取出",
    "No items found": "暂无物品",
    "No messages": "暂无消息",
    "Bounty Quests": "悬赏任务",
    "Raw Material": "原材料",
    "Approve": "同意",
    "Crops": "作物",
    "Growth progress": "生长进度",
    "Actions": "操作",
    "This is a beautiful garden located on your estate. Here you can grow any plants you feel will benefit your team.": "这是你庄园里的一个美丽的花园。在这里，你可以种植任何你认为对你的团队有益的植物。",
    "You are currently using": "您当前正在使用",
    "With your current garden development you can have a maximum of": "以你现在的花园发展进度，你最多可以有",
    "Login servers are down or closed at the moment, probably because of a server restart. Please wait for 5 minutes and try again.": "当前登录服务器已关闭，可能是由于服务器重新启动。请等待5分钟后再试。",
    "Client and server version mismatch. Please refresh the page by pressing Ctrl + F5 on Windows or Linux, Cmd + R on Macbook or Pull to refresh on mobile phone. Make sure the cache is cleared. If the error persists, please reach out to the admins on": "客户端和服务器版本不匹配。Windows或Linux请按Ctrl + F5， Macbook请按Cmd + R，手机请按拉刷新。确保缓存已被清除。如果错误仍然存在，请联系管理员",
    "Refresh": "刷新",
    "Notification settings": "通知设置",
    "Player settings": "玩家设置",
    "Disable UI animations": "禁用界面动画",
    "Disable weather effects": "禁用天气效果",
    "Disable online players list (will require refresh)": "禁用在线玩家列表（将需要刷新）",
    "Game settings": "游戏设置",
    "Battle log settings": "战斗日志设置",
    "Account settings": "账号设置",
    "Ambience": "氛围",
    "Sound": "声音",
    "Restart done": "重启完成",
    "Player Icon": "玩家图标",
    "Player Title": "玩家头衔",
    "Registered devices": "注册设备",
    "Off": "关闭",
    "On": "开启",
    "General notifications": "一般通知",
    "This is a configuration setting that can deliver push messages (notifications) to your mobile or desktop devices": "这是一个可配置设置，可以向移动设备或桌面设备发送推送消息（通知）",
    "Change Password": "修改密码",
    "Connect Patreon": "连接 Patreon",
    "Open Statistics": "打开统计",
    "Update your password": "更新你的密码",
    "Gear": "装备",
    "P.Atk": "物理攻击",
    "P.Def": "物理防御",
    "M.Atk": "法术攻击",
    "M.Def": "法术防御",
    "MP Regen": "法力回复",
    "MP": "法力",
    "R-hand": "右手",
    "Skin style": "皮肤样式",
    "Skin colors": "皮肤颜色",
    "Speed": "速度",
    "Switch class": "切换职业",
    "True Damage": "真实伤害",
    "Wis Healing": "智慧治愈",
    "C.Atk": "暴击攻击",
    "C.Def": "暴击防御",
    "C.Chance": "暴击几率",
    "C.Negate": "暴击抵挡",
    "Counter Atk": "反击",
    "S.Atk": "S.攻击",
    "S.Def": "S.防御",
    "": "",
    "": "",
    "Bleed Chance": "流血几率",
    "Stats": "属性",
    "Level": "等级",
    "agi:": "敏捷:",
    "dex:": "灵巧:",
    "Dex Healing": "灵巧治愈",
    "int:": "智力:",
    "Hit": "命中",
    "HP": "生命值",
    "Eva": "闪避",
    "Outfits": "服装",
    "Hair style": "头发样式",
    "Mouth pieces": "嘴饰",
    "Face pieces": "脸饰",
    "Head pieces": "头饰",
    "Hair colors": "头发颜色",
    "You haven't unlocked this skin yet. To unlock the skin you need to level up the respective class to level 25.": "你还没有解锁这个皮肤。要解锁皮肤，你需要将相应的职业升级到25级。",
    "Empty": "空",
    "This is a list of all classes in the game you can switch to, at the beginning you only have 3 classes available to you. If you create all 3 characters, each of them will take over those 3 classes as duplicates not allowed. You need to level up classes in order to unlock Tier 2 classes and eventually Tier 3 classes. Go to Classes page to see your progress. First 3 classes are straightforward. Warrior - your physical damage dealer / tank. Scout - your nimble dagger, sword or bow user. Apprentice - your magical damage dealer / healer of the party.": "这是游戏中你可以切换的所有职业列表，一开始你只有3个职业可供你选择。如果你创建了所有3个角色，他们中的每一个都将接管这3个职业，因为不允许重复。你需要升级职业才能解锁第2层职业，最终解锁第3层职业。去职业页面查看你的进度。前3个类很简单。战士——你的物理伤害制造者/坦克。侦察兵-你的敏捷匕首，剑或弓使用者。学徒-你的魔法伤害制造者/治疗者的队伍。",
    "While you can give any equipment you like to your characters it is prefered to give strong weapon and Heavy Armor to Warrior": "虽然你可以给你的角色任何你喜欢的装备，但最好给战士提供强大的武器和重甲",
    "Acolyte first, since I really want some more healing...": "首先是侍僧，因为我真的想要更多的治疗…",
    "And Wands with Light armor to the Apprentice.": "还有带着轻甲的魔杖给学徒。",
    "Dagger, swords or range weapon with Medium Armor to Scout.": "匕首，剑或中等护甲的远程武器用于侦察兵。",
    "BE CAREFUL! You're about to start the hunt without a weapon equipped on one of your characters. This is not safe. Please select the \"helmet\" icon labeled \"Characters\" on the side menu or click the character icon on the right. On your character page, click on R-hand equipment slot to equip at least a dagger. It will make your attacks stronger. It is best if you equip at least one piece of body armor as well, as it will increase your defenses and give you additional HP.": "小心!你将在角色身上没有装备武器的情况下开始狩猎。这是不安全的。请选择侧边菜单上标有\“角色\”的\“头盔\”图标或单击右侧的角色图标。在角色页面，点击右手装备槽，至少装备一把匕首。它会使你的攻击更强。最好你至少装备一件护甲装备，因为它会增加你的防御能力，给你额外的生命值。",
    "Start anyway": "无论如何都要开始",
    "No items to equip": "没有可装备的物品",
    "head": "头部",
    "hands": "手部",
    "L-hand": "左手",
    "torso": "躯干",
    "robe/accessory": "长袍/配饰",
    "feet": "脚部",
    "Reset stats": "重置属性",
    "str:": "力量:",
    "wis:": "智慧:",
    "vit:": "活力:",
    "Wisdom (WIS)": "智慧 (WIS)",
    "Vitality (VIT)": "活力 (VIT)",
    "Strength (STR)": "力量 (STR)",
    "Agility (AGI)": "敏捷 (AGI)",
    "Dexterity (DEX)": "灵巧 (DEX)",
    ": This stat affects the character's accuracy (HIT). It confronts the enemy's Evasion (EVA) to check if a hit will strike or miss. Additionally this stat is responsible for Speed by a small amount, as well as physical (P.Atk), status (S.Atk), critical attack (C.Atk) and DEX Healing.": "：此属性影响角色的命中。它面对敌人的闪避（EVA）来检查攻击是否命中。此外，这个属性还负责少量的速度，以及物理（P.Atk），状态（S.Atk），暴击（C.Atk）和灵巧治愈。",
    ": This stat affects the character's evasion (EVA) and speed parameters. Evasion gets factored with the incoming attacker's HIT to determine if your character will dodge a blow. Speed defines how fast you complete tasks (like resting in the tavern), as well as getting added in the initiative roll before a new battle starts. Additionally AGI add critical chance (C.Chance)": "：此属性影响角色的闪避（EVA）和速度参数。闪避会与攻击者的HIT相结合来决定你的角色是否会闪避。速度决定了你完成任务的速度（注释：如在酒馆休息），以及在新战斗开始前加入主动投掷。另外敏捷增加暴击几率（C.Chance）",
    ": This stat affects the character's healing capabilities, magical defense (M.Def), maximum mana (MP), mana regeneration (MP Regen) and physical defense (P.Def) by a small amount and WIS Healing": "：此属性影响角色的治疗能力，魔法防御（M.Def），法力值（MP），法力回复（MP Regen）和物理防御（P.Def）少量和智慧治愈",
    ": This stat affects the character's physical defense (P.Def) and total life (HP), and is an important stat for protectors. It also increases status defense (S.Def) and magical defense (M.Def) by a small amount, and it is a reasonable choice on any class.": "：此属性影响角色的物理防御（P.Def）和总生命（HP），是保护者的重要属性。它还可以增加少量的状态防御和魔法防御，对任何职业来说都是一个合理的选择。",
    ": This stat affects the character's physical power (P.Atk), both melee and ranged.": "：此属性影响角色的物理攻击（P.Atk），包括近战和远程。",
    "Game restart in 10min, will be releasing new patch, again mostly bugfixes.": "游戏将于10分钟后重启，会发布新的补丁，大部分还是bug修复。",
    "Language (will require refresh)": "语言（需要刷新）",
    "Change": "更改",
    "Your mailbox is empty": "你的信箱是空的",
    "Mailbox": "信箱",
    "Gift Box": "礼盒",
    "Upgrade": "升级",
    "Next Upgrade Cost": "下一升级成本",
    "Grind Stone": "磨石",
    "Gym": "健身房",
    "Storage": "仓库",
    "Mail Box": "信箱",
    "Anvil": "铁砧",
    "Monster Altar": "怪物祭坛",
    "Salamander's Beacon": "火蜥蜴灯塔",
    "Library": "图书馆",
    "Shop efficiency": "商店效率",
    "Sawmill": "锯木厂",
    "Workbench": "工作台",
    "Stonemill": "石磨",
    "Forge": "锻炉",
    "Specify script name to add new script": "指定脚本名称以添加新脚本",
    "This is where you configure the behavior of your characters in battle by creating \"scripts\". It might take you some time playing around with it before you get it right. Don't be discouraged and try to reach out to other players in our Global Chat or #scripts channel in our": "在这里，您可以通过创建“脚本”来配置角色在战斗中的行为。你可能要花一些时间才能弄明白。不要气馁，试着在我们的全球聊天或#脚本频道中与其他玩家联系",
    "Refinement station, where great Blacksmithing minds figured out a way on how to make already powerful weapons even more powerful.": "精炼站，在那里伟大的铁匠们想出了一种方法，使已经强大的武器变得更加强大。",
    "To refine the weapon you need to have materials, correct facility level and money to use the refining station. Price and materials depend on level of weapon/armor.": "为了精炼武器，你需要有材料，正确的设施等级和金钱来使用精炼站。价格和材料取决于武器/护甲的等级。",
    "You see a lot of fellow Blacksmiths in the building, all silently hammering, grinding, and polishing weapons and armors.": "你可以在建筑中看到许多铁匠同伴，他们都在默默地敲打、打磨和抛光武器和盔甲。",
    "Confirm hunt": "确认狩猎",
    "Chance increase": "几率提高",
    "Chance to successfully refine item": "几率成功精炼物品",
    "Class levels are separate from character levels": "职业等级与角色等级是分开的",
    "Desert Cactus Elder (Lv: 43), Desert Parasand (Lv: 45), Colossal Snake (Lv: 47), Colossal Scorpion (Lv: 48)": "沙漠仙人掌接骨木（等级: 43），沙漠寄生虫 (等级: 45)，巨蛇（等级: 47），巨蝎（等级: 48）",
    "Desert Colossus (Lv: 50), Ancient Cactus (Lv: 52), Sand Tentacles (Lv: 54), Mummy (Lv: 55)": "沙漠巨像（等级: 50），远古仙人掌（等级: 52），沙触须（等级: 54），木乃伊（等级: 55）",
    "Feral Rats (Lv: 25), Slime (Lv: 25), Slime Warrior (Lv: 26), Slime Mage (Lv: 27)": "野鼠（等级: 25），史莱姆（等级: 25），史莱姆战士（等级: 26），史莱姆法师（等级: 27）",
    "Gnoll Warrior (Lv: 16), Gnoll Spearfighter (Lv: 17), Gnoll Archer (Lv: 19)": "豺狼人战士 (等级: 16), 豺狼人枪兵 (等级: 17), 豺狼人射手 (等级: 19)",
    "Ghost Sphynx (Lv: 56), Eldritch Fire Slime (Lv: 57), Arcana Skeleton (Lv: 58), Elder Mummy (Lv: 59)": "幽灵斯芬克斯（等级: 56），魔火史莱姆（等级: 57），奥秘骷髅（等级: 58），木乃伊长老（等级: 59）",
    "Lesser Spheria (Lv: 20), Sea Turtle (Lv: 21), Baby Octi (Lv: 22), Juvenile Shark (Lv: 24)": "小鳞鲨（等级: 20），海龟（等级: 21），章鱼宝宝（等级: 22），幼鲨（等级: 24）",
    "Baby Fox (Lv: 1), Baby Tiger (Lv: 2)": "幼狐（等级: 1），幼虎（等级: 2）",
    "Slime Healer (Lv: 28), Slime Warlock (Lv: 29), Slime Berserker (Lv: 29), Slime Archer (Lv: 29)": "史莱姆治疗师（等级: 28），史莱姆术士（等级: 29），史莱姆狂战士（等级: 29），史莱姆射手（等级: 29）",
    "Sunscale Chromis (Lv: 12), Sea Horse (Lv: 13), Crimson Snapper (Lv: 14)": "阳麟彩人（等级: 12），海马（等级: 13），赤鲷（等级: 14）",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Mineral Vein I, Boulder": "矿脉 I，巨石",
    "Mineral Vein V, Boulder": "矿脉 V，巨石",
    "Mineral Vein VI, Boulder": "矿脉 VI，巨石",
    "Mineral Vein IV, Boulder": "矿脉 IV，巨石",
    "Mineral Vein II, Tree": "矿脉 II，树",
    "Mineral Vein III, Plant III, Boulder": "矿脉 III，植物 III，巨石",
    "Mineral Vein III, Tree III, Boulder": "矿脉 III，树 III，巨石",
    "Mineral Vein VII, Tree VII, Plant VII, Skinnable Body VII, Boulder": "矿脉 VII，树 VII，,植物 VII, 可剥皮的身体 VII, 巨石",
    "Plainstrider (Lv: 8), Spiderling (Lv: 10)": "平原骑士（等级: 8），幼蛛（等级: 10）",
    "Sand Serpent (Lv: 35), Desert Cactus Renegade (Lv: 38), Earth Wisp (Lv: 37), Desert Lizard (Lv: 40), Sand Scorpid (Lv: 42)": "沙蛇（等级: 35），沙漠仙人掌叛变者（等级: 38），大地精灵（等级: 37），沙漠蜥蜴（等级: 40），沙蝎（等级: 42）",
    "Sand Slime (Lv: 31), Desert Cactus (Lv: 32), Desert Horned Rabbit (Lv: 34), Sand Serpent (Lv: 35)": "沙史莱姆（等级: 31），沙漠仙人掌（等级: 32），沙漠角兔（等级: 34），沙蛇（等级: 35）",
    "Sea Urchin (Lv: 4), Beach Crawler (Lv: 5), Sea Lurker (Lv: 6)": "海胆（等级: 4），沙滩爬行者（等级: 5），海洋潜伏者（等级: 6）",
    "Skinnable Body": "可剥皮的身体",
    "I, Boulder": "  I，巨石",
    "VI, Plant": "  VI，植物",
    "VI, Boulder": "  VI，巨石",
    "IV, Plant": "  IV，植物",
    "V, Plant": "  V，植物",
    "IV, Boulder": "  IV，巨石",
    "II, Plant II, Boulder": "  II, 植物 II，巨石",
    "III, Plant III, Boulder": "  III, 植物 III，巨石",
    "Recent achievements": "最近获得的成就",
    "Summary": "总览",
    "Quests": "任务",
    "Quests points collected:": "收集的任务点数：",
    "Progression points collected:": "收集的进展点数：",
    "Achievement points collected:": "收集的成就点数：",
    "Dungeons points collected:": "收集的地下城点数：",
    "General points collected:": "收集的常规点数：",
    "General": "常规",
    "Alpha Tester": "阿尔法测试者",
    "Claim": "收集",
    "Collecting junk like it's a hobby! Get at least one stack of 29,999 items in your storage.": "在你的仓库中至少有一堆29,999件物品。",
    "Bag of Holding": "手提袋",
    "Login into the game during Alpha Test": "在Alpha测试期间登录游戏",
    "Reach level 100 in Enlarge Backpack. I wish I had a bag of holding... before!": "背包放大等级达到100级。我希望我有一个袋子……之前!",
    "Achieved on": "达成于",
    "You've done 50 of bounty quests already, it seems like you're enjoying it. Or just rewards.": "你已经完成了50个悬赏任务，看起来你很享受。或者只是为了奖励。",
    "Adventurer": "冒险家",
    "Assassin, Skin of Assassin job from original Ragnarok Online": "刺客，原《诸神黄昏Online》中 刺客 的工作皮肤",
    "Avatar, Skin of Wizard job from original Ragnarok Online": "头像，原《诸神黄昏Online》中 术士 的工作皮肤",
    "Book Worm": "书虫",
    "Chronicler, Skin of Wizard job from original Ragnarok Online": "编年史家，原《诸神黄昏Online》中 术士 的工作皮肤",
    "BowMaster": "弓箭大师",
    "Cleric, Skin of Acolyte job from original Ragnarok Online": "牧师，原《诸神黄昏Online》中 侍僧 的工作皮肤",
    "Infiltrator": "潜入者",
    "Healer": "治疗者",
    "Enchanter": "附魔者",
    "Knight Protector": "Knight Protector",
    "Grinder": "研磨者",
    "Student": "学生",
    "Facility": "设施",
    "Level:": "等级:",
    "Planning Hall": "策划大厅",
    "Runic Battle Codex": "符文战斗法典",
    "Study": "研究",
    "Valkyrie's Shrine": "女武神的神殿",
    "Stonemine Detector": "石矿探测器",
    "Tannery": "制革厂",
    "Leatherworking": "皮革加工",
    "Metallurgy": "冶金",
    "Type:": "类型:",
    "You are about to make a request to start construction of": "你正在请求开始建造",
    "to level": "到等级",
    "Materials that will be required to start construction.": "开始建造将会消耗下列的材料。",
    "When all materials are gathered": "当所有的材料都收集齐，然后等待",
    "will be required to finish construction": "即可完成建造",
    "Confirm": "确认",
    "Found new monster:": "发现新怪物:",
    "Found new monsters:": "发现新怪物:",
    "Level Up!": "升级!",
    "Hunt started": "狩猎已开始",
    "Hunt finished": "狩猎已完成",
    "Battle finished.": "战斗已结束。",
    "All enemies were defeated": "已击败所有敌人",
    "Statistics from hunt:": "狩猎统计",
    "Battle stopped": "战斗结束",
    "casts": "施放了",
    "dealt damage to": "造成伤害对",
    "Elemental Bolt": "元素弩箭",
    ", it turns into the": "，它变成了",
    "air": "气",
    "was knocked out": "被击倒了",
    "Initiative order:": "行动顺序:",
    "(Free weekend)": "（免费周末）",
    "Champion": "冠军",
    "GM": "游戏管理员",
    "Beta Tester": "Beta测试者",
    "God of War": "战神",
    "Chronicler": "编年史家",
    "Guardian": "守护者",
    "Master Warrior": "战士大师",
    "Student": "学生",
    "Sword for Hire": "雇佣之剑",
    "Wanderer": "流浪者",
    "Sage": "贤者",
    "Grinder": "研磨者",
    "You need to have a Mail Box facility in your estate to use this feature": "您需要在您的庄园中有一个邮箱设施才能使用此功能",
    "There are no harvests growing at the moment": "目前没有收成",
    "Harvest all my crops": "收获我所有的作物",
    "beds.": "苗圃。",
    "garden beds planted at the same time. After your crops are ready, you have 1 month to collect them before they wither.": "苗圃可以同时种植。作物成熟后，你有1个月的时间在枯萎前收集它们。",
    "Plant": "种植",
    "What do you want to plant?": "你想种植什么植物？",
    "Angel Bloom Seeds": "天使之花种子",
    "Birch Tree Seeds": "桦树种子",
    "Cherry Tree Seeds": "樱桃树种子",
    "Devil Cress Seeds": "魔鬼水芹种子",
    "Ivory Lavender Seeds": "象牙薰衣草种子",
    "Mandrake Seeds": "曼德拉草种子",
    "Nochia Grass Seeds": "夜蛾草种子",
    "Peace Blossom Seeds": "和平之花种子",
    "Ruby Angelica Seeds": "红宝石当归种子",
    "Dreaming Glory Seeds": "梦想荣耀种子",
    "Nightmare Thistle Seeds": "梦魇蓟种子",
    "Oak Tree Seeds": "橡树种子",
    "Tree Seeds": "树种子",
    "You start with 3 initial classes. You will unlock additional classes when you reach the necessary level on prerequisite classes.": "你从3个初始职业开始。当前置职业达到所需等级后，可解锁额外职业。",
    "For every 10 class levels, summed up between all classes, each one of your characters will receive +1 stat points that you can allocate. This bonus will apply to any additional character created.": "每10个职业等级，将所有职业相加，你的每个角色将获得+1属性点，你可以分配。这个奖励将适用于任何创建的额外角色。",
    "Leveling up the first class to level 25 will unlock character slot #4, and the second class that reaches level 25 will unlock character slot #5.": "第一个职业升级到25级将解锁角色槽4，第二个职业升级到25级将解锁角色槽5。",
    "Accept all Bounty Quests": "接受所有悬赏任务",
    "Tavern's Bounty Quests is a place where you can do tasks to earn some money, experience and fame. Bounties are repeatable tasks that you can do in a timespan of 7 days. After completing the quest you will receive the rewards and the quest will be available again after the reset at 4AM UTC timezone.": "酒馆的悬赏任务是一个你可以通过完成任务来赚取金钱，经验和声望的地方。奖励是可重复的任务，你可以在7天内完成。完成任务后，您将获得奖励，任务将在UTC时区凌晨4点重置后再次可用。",
    "Show only recommended bounties": "只显示推荐的悬赏任务",
    "End discussion": "完成任务",
    "- Baby Foxes are a nuisance in our farmlands! They steal our chickens and scare our sheep. Please get rid of them!": "- 小狐狸在我们的农田里是个讨厌的东西！他们偷我们的鸡，吓唬我们的羊。请把他们处理掉！",
    "'s level has increased!": "的等级提升了！",
    "*Signed*": "*已签名*",
    "*Looking at the Bounty board in the Quest Bureau*": "*查看任务局的赏金板*",
    "LFA (Local Farmers Association)": "LFA (当地农民协会)",
    "Re-runs": "重复",
    "Available to Patreon Supporters": "仅对Patreon支持者开放",
    "Bat (Lv: 8), Biofish (Lv: 8), Goo (Lv: 9), Water Butterfly (Lv: 9)": "蝙蝠（等级: 8），生物鱼（等级: 8），粘性物（等级: 9），水蝴蝶（等级: 9）",
    "Bug Centipede (Lv: 36), Underground Worm (Lv: 37), Death Worm (Lv: 38), Beetle Soldier (Lv: 39), Dweller Worm (Lv: 39), Black Ant Assassin (Lv: 39)": "虫蜈蚣（等级: 36）、地下虫（等级: 37）、死虫（等级: 38）、甲虫兵（等级: 39）、居虫（等级: 39）、黑蚁刺客（等级: 39）",
    "Ghost Ship": "幽灵船",
    "Ghostoid (Lv: 61), Piranos (Lv: 62), Ghost Puppet (Lv: 63), Dark Starfish (Lv: 64), Spider Crab (Lv: 64)": "幽灵（等级: 61）、海盗（等级: 62）、幽灵木偶（等级: 63）、暗海星（等级: 64）、蜘蛛蟹（等级: 64）",
    "Slime Warrior (Lv: 26), Slime Mage (Lv: 27), Slime Healer (Lv: 28), Slime Warlock (Lv: 29), Slime Berserker (Lv: 29), Slime Archer (Lv: 29)": "史莱姆战士（等级: 26），史莱姆法师（等级: 27），史莱姆治疗者（等级: 28），史莱姆术士（等级: 29），史莱姆狂战士（等级: 29），史莱姆射手（等级: 29）",
    "Mountain Harpy (Lv: 35), Earth Wisp (Lv: 37), Mountain Snail (Lv: 38), Mountain Goat (Lv: 40), Mountain Greathorn (Lv: 42)": "山妖（等级: 35），地精（等级: 37），山螺（等级: 38），山羊（等级: 40），山棘（等级: 42）",
    "Mountain Rabbit (Lv: 31), Mountain Bat (Lv: 32), Mountain Wolf (Lv: 34), Mountain Harpy (Lv: 35)": "山兔（等级: 31），山蝙蝠（等级: 32），山狼（等级: 34），山鹰（等级: 35）",
    "Mountain Scorpion (Lv: 43), Mountain Warthog (Lv: 45), Mountain Black Wolf (Lv: 47), Mountain Owl (Lv: 48)": "山蝎（等级: 43），山疣猪（等级: 45），山黑狼（等级: 47），山猫头鹰（等级: 48）",
    "Sunken Ruins": "沉没废墟",
    "Underground Bugs Nest": "地下虫巢",
    "Dire Frostwolf (Lv: 50), Mountain Bear (Lv: 52), Earth Snake (Lv: 54)": "巨霜狼（等级: 50），山熊（等级: 52），土蛇（等级: 54）",
    "Earth Bull (Lv: 56), Earth Turtle (Lv: 57), Earth Spawn (Lv: 58), Hunter Hawk (Lv: 59)": "土牛（等级: 56），土龟（等级: 57），土怪（等级: 58），猎鹰（等级: 59）",
    "Fangrot (Lv: 43), Forest Fox (Lv: 45), Forest Spora (Lv: 47), Onyx Griffin (Lv: 48)": "方罗（43级），林狐（45级），森林孢子（47级），缟玛瑙狮鹫（48级）",
    "Forest Spider (Lv: 35), Catermoth (Lv: 37), Deer (Lv: 38), Treant (Lv: 40), King Parrot (Lv: 42)": "森林蜘蛛（等级: 35），毛虫（等级: 37），鹿（等级: 38），树蚁（等级: 40），王鹦鹉（等级: 42）",
    "Forest Sprite (Lv: 31), Grasshopper (Lv: 32), Baby Fawn (Lv: 34), Forest Spider (Lv: 35)": "森林精灵（等级: 31），蚱蜢（等级: 32），小鹿（等级: 34），森林蜘蛛（等级: 35）",
    "Goblin Pillager (Lv: 50), Goblin Scout (Lv: 52), Goblin Shaman (Lv: 54), Goblin Sniper (Lv: 55)": "哥布林掠夺者（等级: 50），哥布林侦察兵（等级: 52），哥布林萨满（等级: 54），哥布林狙击手（等级: 55）",
    "Goblin Rider (Lv: 56), Red Spider (Lv: 57), Hell Mantis (Lv: 58), Goblin Beastmaster (Lv: 59)": "哥布林骑士（等级: 56），红蜘蛛（等级: 57），地狱螳螂（等级: 58），哥布林兽王（等级: 59）",
    "Imfamouse bestow upon everyone his blessing and brought knowledge to the world (EXP gain buff increased by 30 minutes)": "Imfamouse 祝福了每个人并给世界带来知识（经验增益Buff增加了30分钟）",
    "Updates every 3 hours": "每3小时更新一次",
    "Top Level": "等级排行榜",
    "Most deaths (weekly)": "死亡次数排行榜 (按周)",
    "Monsters killed (1-29 Lv / weekly)": "怪物击杀排行榜 (1-29 级 / 按周)",
    "Monsters killed (30-59 Lv / weekly)": "怪物击杀排行榜 (30-59 级 / 按周)",
    "Monsters killed (60-70 Lv / weekly)": "怪物击杀排行榜 (60-70 级 / 按周)",
    "Quests (weekly)": "任务排行榜 (按周)",
    "Richest parties": "队伍财富排行榜",
    "Rank": "排名",
    "Zeny": "金币",
    "Crafts": "制作",
    "Deaths": "死亡",
    "Monsters killed": "击杀怪物数量",
    "Craftsman points (weekly)": "工匠点数（按周）",
    "of Alpha Tester, Icon of Alpha Tester": " 阿尔法测试者, 阿尔法测试者图标",
    "of Beta Tester, Icon of Beta Tester": " Beta测试者, Beta测试者图标",
    "Master of War": "战争大师",
    "Master Apprentice": "宗师学徒",
    "Master Warrior": "宗师战士",
    "Master Warrior, Skin of Swordsman job from original Ragnarok Online": "宗师战士，原《诸神黄昏Online》中 剑客 的工作皮肤",
    "Refine First Item": "精炼第一件物品",
    "Refine 100 items - welcome to the never-ending quest for shinier stuff!": "精炼100件物品 - 欢迎来到永不停歇的寻找更闪亮物品的任务！",
    "Refine 20 items - because nothing says perfection like tinkering endlessly": "精炼20件物品 - 因为没有什么比无休止地修补更能说明完美了",
    "Recon Specialist, Skin of Thief job from original Ragnarok Online": "侦察专家，原《诸神黄昏Online》中 盗贼 的工作皮肤",
    "Reached level 10 in armor crafting. Suit up!": "达到防具制作10级。穿上装备！",
    "Reached level 10 in gardening. Sowing seeds of success!": "达到10级园艺。播下成功的种子！",
    "Reached level 10 in pharmacy. Stirring up trouble!": "达到药剂学10级。挑起事端！",
    "Reached level 10 in weapon crafting. Just the tip of the spear!": "达到10级武器制作。只是矛尖！",
    "Reached level 30 in armor crafting. We've got you covered!": "达到30级防具制作。我们会掩护你的！",
    "Reached level 30 in gardening. Nature's ally!": "达到30级园艺。大自然的盟友!",
    "Reached level 30 in pharmacy. Brew master in training!": "达到药剂学30级酿造大师在培训！",
    "Reached level 30 in weapon crafting. Cutting edge skills!": "达到30级武器制作。尖端技能！",
    "Reached level 50 in armor crafting. Heavy metal!": "达到50级防具制作。重金属!",
    "Reached level 50 in gardening. Growing greatness!": "达到50级园艺。日益增长的伟大!",
    "Reached level 50 in pharmacy. Mixing it up!": "达到药剂学50级。混在一起！",
    "Reached level 50 in weapon crafting. Hammer time!": "达到50级武器制作。锤击时间！",
    "Reached level 70 in armor crafting. Unbreakable!": "达到70级护甲制作。牢不可破!",
    "Reached level 70 in gardening. King of the jungle!": "达到70级园艺。丛林之王！",
    "Reached level 70 in pharmacy. You've cracked it!": "达到药剂学70级。你成功了！",
    "Reached level 70 in weapon crafting. For the glory!": "达到70级武器制作。为了荣耀！",
    "Hoarder Extraordinaire": "非凡囤积者",
    "Materials requirements": "材料要求",
    "Details": "详情",
    "Tier": "层级",
    "Craft Weapon": "制作武器",
    "Start craft": "开始制作",
    "Brick": "砖块",
    "Leather": "皮革",
    "Metal Beam": "金属梁",
    "": "",
    "Plank": "板材",
    "Plank IV (Birch)": "板材 IV (桦木)",
    "Plank IV (Cherry)": "板材 IV (樱桃木)",
    "Plank V (Maple)": "板材 V (枫木)",
    "Plank V (Pine)": "板材 V (松木)",
    "Plank VI (Oak)": "板材 VI (橡木)",
    "Plank VI (Willow)": "板材 VI (柳木)",
    "Plank VII (Walnut)": "板材 VII (胡桃木)",
    "Plank VII (Mahogany)": "板材 VII (红木)",
    "Sort by name": "按名称排序",
    "Sort by tier": "按层级排序",
    "Material": "材料",
    "consumable": "消耗品",
    "Consumables": "消耗品",
    "Equipment": "装备",
    "etc.": "其他",
    "Construction Material": "建筑材料",
    "Items available to buy": "可购买的物品",
    "Items available for buy back": "可买回的物品",
    "Meat Scraps": "碎肉",
    "Jellopy": "杰洛皮",
    "Cooling Salve": "冷却药水",
    "Crafting Components": "制作组件",
    "Elixirs": "万灵药",
    "Enchantment": "附魔",
    "Transmutation": "变化",
    "Candy": "糖果",
    "Average Bedroll": "普通的铺盖",
    "Comfortable Bedroll": "舒适的铺盖",
    "Low Grade Bedroll": "低级的铺盖",
    "Luxurious Bedroll": "豪华的铺盖",
    "Empty Bottle": "空瓶",
    "Soul Shard": "灵魂碎片",
    "Frostbite Dust": "冻伤尘埃",
    "Special": "特殊",
    "Reasonable Haircut": "合理的发型",
    "Very Cheap Haircut": "非常廉价的发型",
    "Cheap Haircut": "廉价的发型",
    "Affordable Haircut": "价格合理的发型",
    "Fashionable Haircut": "时尚的发型",
    "Decent Haircut": "得体的发型",
    "Budget Haircut": "预算的发型",
    "Cosmetics": "装饰品",
    "Dye Color": "染色颜色",
    "Hair Color": "头发颜色",
    "Clown Nose": "Clown Nose",
    "Big Ribbon": "大丝带",
    "Ribbon": "丝带",
    "Bucket Hat": "桶帽",
    "Bunny Ears": "兔耳朵",
    "Crown": "王冠",
    "(face slot)": "(脸部槽位)",
    "(mouth slot)": "(嘴部槽位)",
    "(head slot)": "(头部槽位)",
    "Battle Manual": "战斗手册",
    "Bone Helm": "骨盔",
    "Dungeon Chest": "地下城宝箱",
    "Riches Manual": "富有手册",
    "You are about to obtain": "你即将获得",
    "at the cost of": "成本为",
    "fame points.": "声望点数。",
    "Nut Shell": "坚果壳",
    "Poker Face": "扑克脸",
    "Pinguin Hat": "企鹅帽",
    "Pirate Hat": "海盗帽",
    "Poo Poo Hat": "粑粑帽",
    "Poring Hat": "钻孔帽",
    "Puppy Headband": "小狗头巾",
    "Shortbow": "短弓",
    "Simple Glasses": "简约眼镜",
    "Sold some leather": "卖掉一些皮革",
    "Battle basics": "战斗基础",
    "Battle is the main feature of ROIdle, all of your progress revolves around it.": "战斗是《ROIdle》的主要特色，所有的进程都围绕着战斗展开。",
    "Currently there are also random weather effects, primarily rain and sandstorm that can trigger 5% chance effect of making the battlefield wet or make everyone receive blind status effect.": "目前也有一些随机的天气效果，主要是雨和沙尘暴，它们可以触发5%的几率使战场变湿或使每个人都获得失明状态的效果。",
    "Game have an extensive": "游戏有一个广泛的",
    "Status Effects": "状态效果",
    "from our wiki.": "通过我们的Wiki。",
    "that you can read all about in our wiki.": "你可以在我们的Wiki上读到。",
    "Stat points:": "属性点:",
    "Sub-type:": "子类型:",
    "Initiate Apprentice": "初始学徒",
    "Initiate Scout": "初始侦察兵",
    "Initiate Warrior": "初始战士",
    "Toggle Battle Log": "切换战斗日志",
    "Toggle Hunt Log": "切换狩猎日志",
    "Tree I, Plant": "树 I, 植物",
    "Ore": "矿石",
    "Stone": "石头",
    "Hide": "兽皮",
    "Log": "原木",
    "Fibers": "纤维",
    "Tome": "卷轴",
    "XP:": "经验值:",
    "Boulder": "巨石",
    "You can start getting to know about": "你可以开始了解关于",
    "View": "查看",
    "The Grinder is a tool that allows the Stonemill to produce bricks with high efficiency, using the rock to its fullest. It decreases the time and amount of stone neccessary to produce bricks.": "磨床是一种工具，可以使石磨厂以高效率生产砖，充分利用岩石。它减少了制砖所需的时间和石头的数量。",
    "Extend hunt": "延长狩猎",
    "Interrupt hunt": "中断狩猎",
    "Found new gathering node:": "发现新的采集节点：",
    "Found new gathering nodes:": "发现新的采集节点：",
    "Quest complete": "任务已完成",
    "Circling Strike": "盘旋打击",
    "Mineral Vein": "矿脉",
    "hide": "兽皮",
    "raw material": "原材料",
    "can be processed in the tannery into a leather": "可以在制革厂加工成皮革",
    "can be processed in the forge into a metal beam": "可以在锻炉中加工成金属梁",
    "can be processed in sawmill into a plank": "可以在锯木厂加工成板材",
    "Used in craft mostly for light armors": "用于制造轻甲",
    "ore": "矿石",
    "log": "原木",
    "Item from an era long forgotten, only good to be sold to Merchants. A small crystallization created by some monsters.": "来自一个早已被遗忘的时代的物品，只适合卖给商人。是一些怪物创造的小结晶。",
    "loot": "战利品",
    "healing": "治疗",
    "Parameters:": "参数:",
    "Used for healing and recovering HP": "用于治疗和恢复生命值",
    "can be processed in the stonemill into a brick": "可以在石磨中加工成砖块",
    "Specify script name to rename the script": "指定脚本名称以重命名脚本",
    "You have not unlocked this class yet": "您还没有解锁这个职业",
    "This class is already in use by another of your characters": "这个职业已经被你的另一个角色使用了",
    "- Is it done? Good. The Farmer Association already left your reward here. Please, take it.": "- 完成了吗？好。农民协会已经把你的奖赏留在这里了。请收下吧。",
    "*Arriving at the Quest Bureau desk, you show proof of the finished task*": "*到达任务局的服务台，出示完成任务的证明*",
    "water": "水",
    "Tree": "树",
    "missed": "未命中",
    "moves forward": "向前移动",
    "fire": "火",
    "Beach Crawler": "沙滩爬行者",
    "Potato": "土豆",
    "Urchin": "胆",
    "earth": "地",
    "and": "并",
    "failed": "未能",
    "applied": "成功",
    "to apply Pinned effect on": "施加 定身 效果到",
    "to apply Provoking Howl effect on": "施加 挑衅嚎叫 效果到",
    "is idling (mana recovery increased)": "挂机中（法力恢复增加）",
    "and applied positive effect(s) on allies": "并对生存的队友产生积极影响",
    "Provoking Howl effect on": "挑衅嚎叫效果到",
    "Pause auto switching to different battle log": "暂停自动切换不同战斗日志",
    "Fish Hook": "鱼钩",
    "Flight Feather": "飞羽",
    "Flax Fibers": "Flax Fibers",
    "Gas Mask": "防毒面具",
    "Geek Glasses": "极客眼镜",
    "Gel": "凝胶",
    "Glasses": "眼镜",
    "Handwraps": "手巾",
    "Goblin Mask": "哥布林面具",
    "Gold Gift Box": "黄金礼盒",
    "Gleipnir's Arcane Powder": "列普尼尔的奥术粉末",
    "Husky Fang": "哈士奇牙",
    "Husky Claw": "哈士奇爪",
    "Husky Claw": "哈士奇骨",
    "HP Potion (Alchemist)": "生命药水（炼金术士）",
    "Item": "物品",
    "Duration": "剩余时间",
    "My Orders": "我的订单",
    "Price": "价格",
    "Refinement": "精炼",
    "Arcane Knowledge": "奥术知识",
    "Adept Warrior": "熟练的战士",
    "Adept Scout": "熟练的侦察兵",
    "Adept Apprentice": "熟练的学徒",
    "Your class level has increased!": "你的职业等级提升了！",
    "Hunt time was extended": "狩猎时间已延长",
    "First Bounty": "第一笔赏金",
    "Snagged your first prize!": "获得了你的第一次奖赏！",
    "- Done? Fishermen will be happy they can work again.": "- 搞定了？渔民会很高兴他们可以再次工作。",
    "- Fishing can now resume. Nicely done.": "- 现在可以恢复钓鱼了。干得漂亮。",
    "- What is that smell coming from the bag? Raw meat?! Our clients sometimes go crazy with their requests, but if they are paying, who cares, right?": "- 袋子里的味道是什么？生肉? !我们的客户有时会疯狂地提出要求，但如果他们付钱了，谁在乎呢？",
    "Facility can't have higher level than your estate": "设施的等级不能高于你的庄园",
    "EXP gain is increased by x2 until the timer ends": "经验增益增加x2，直到计时器结束",
    "Drop rates of all items from monsters is increased by x2 until the timer ends": "所有来自怪物的物品掉落概率增加2倍，直到计时器结束",
    "All of your characters are with 0 health, you need to have at least one character with health to start the hunt": "你所有的角色生命值都是0，你需要至少有一个生命值的角色才能开始狩猎",
    "The party was almost wiped and barely escaped": "这支队伍几乎全军覆没，勉强逃过一劫",
    "Double Attack": "双倍攻击",
    "Drop chances:": "掉落几率:",
    "Dungeon Overlord": "地下城领主",
    "Dungeon Dweller": "地下城居民",
    "Eagle Eyes": "鹰眼",
    "Earth Bolt": "大地螺栓",
    "box": "箱子",
    "Someone logged in to the account from another source. Session lost.": "有人从别的地方登录了这个账户。会话丢失。",
    "- Woah, those are some large and rather smelly fishes... with hook and all. I will send the good news to the fishermen right away!": "- 哇，那是一些又大又臭的鱼…带着钩子什么的。我马上把这个好消息发给渔民！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 怪物
    "Baby Fox": "幼狐",
    "Baby Tiger": "幼虎",
    "Crab King (Lv: 65)": "蟹王 (等级: 65)",
    "Devourer (Lv: 40)": "吞噬者 (等级: 40)",
    "Old Automaton (Lv: 10)": "旧人偶 (等级: 10)",
    "Slime King (Lv: 30)": "史莱姆之王 (等级: 30)",
    "Lurker": "潜伏者",
    "Magic Darts": "魔法飞镖",
    "Spiderling": "幼蛛",
    "Plainstrider": "扁黾",
    "Gnoll Archer": "豺狼人弓箭手",
    "": "",
    "": "",
    "": "",
    "": "",
    "Healing Touch": "治愈之触",
    "War Cry": "战吼",
    "element": "元素",
    "Bash": "猛击",
    "Provoking Howl": "挑衅嚎叫",
    "Tactical Positioning": "战术定位",
    "First Aid": "急救",
    "Efficient Spellcasting": "高效施法",
    "Focused Shot": "集中射击",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Shirt": "衬衫",
    "Hammer": "锤",
    "Oak Staff": "橡木法杖",
    "Flail": "连枷",
    "Tower Shield": "塔盾",
    "Helmet": "头盔",
    "Gloves": "手套",
    "Magicast": "施法",
    "Magician Hat": "魔术师帽",
    "Staffs": "法杖",
    "Stiletto": "细高跟鞋",
    "Vulcanite Stiletto": "硫化细高跟鞋",
    "Crossbows": "弩",
    "Refinement Tools": "精炼工具",
    "Light Armors": "轻型防具",
    "Medium Armors": "中型防具",
    "Heavy Armors": "重型防具",
    "Tomes": "卷轴",
    "Wands": "权杖",
    "Daggers": "匕首",
    "Bows": "弓",
    "Shields": "盾牌",
    "agnarok Oblivion": "诸神黄昏: 湮灭",
    "Leather Brigandine": "皮衣",
    "Leather Boots": "皮靴",
    "Leather Gloves": "皮手套",
    "Leather Helmet": "皮头盔",
    "Leg": "腿",
    "Legs": "腿",
    "Buckler": "圆盾",
    "Bucklers": "圆盾",
    "Sabatons": "铠靴",
    "Sabaton": "铠靴",
    "Dagger": "匕首",
    "Daggers": "匕首",
    "Gauntlet": "长手套",
    "Gauntlets": "长手套",
    "Mace": "狼牙棒",
    "Maces": "狼牙棒",
    "Sword": "剑",
    "Swords": "剑",
    "Spear": "矛",
    "Spears": "矛",
    "Hat": "帽子",
    "Hats": "帽子",
    "Helm": "头盔",
    "Helms": "头盔",
    "Breastplate": "胸甲",
    "Breastplates": "胸甲",
    "Axe": "斧",
    "Axes": "斧",

    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "Copyright © 2019-2024 Maxo. All game logic and game play rights reserved.": "Copyright © 2019-2024 Maxo. All game logic and game play rights reserved.",
    "|": "|",
    "Reddit": "Reddit",
    "Patreon": "Patreon",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    "Gityx": "Gityx",
    "Gz": "Gz",
    "O": "O",
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "[": "[",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Private chat ": "私人聊天 ",
    "Global chat ": "全局聊天 ",
    "System chat ": "系统聊天 ",
    "Trade chat ": "交易聊天 ",
    "Fame points: ": "声望点数: ",
    "Dimensional Storage Lv ": "次元仓库 等级 ",
    "You've put Nochia Grass": "你把 夜蛾草",
    "You've put Sticky Mucus": "你把 黏液",
    "You've put Straw Fibers": "你把 稻草纤维",
    "You've put Kelp": "你把 海藻",
    "You've put Elm Log": "你把 榆木原木",
    "You've put Copper Dagger": "你把 铜匕首",
    "You've put Shredded Leather Brigandine": "你把 破碎的皮衣布",
    "New Year ": "新年 ",
    "Scripts ": "脚本 ",
    "Tin ": "锡 ",
    "Copper ": "铜 ",
    "Steel ": "钢 ",
    "Stonestrand ": "石柱 ",
    "Straw ": "稻草 ",
    "Titansteel ": "泰坦钢 ",
    "Wraithsteel ": "幽灵钢 ",
    "Sea ": "海 ",
    "Willow ": "柳木 ",
    "Warped ": "弯曲 ",
    "Walnut ": "胡桃木 ",
    "Tundra ": "苔原 ",
    "Teak ": "柚木 ",
    "Starmetal ": "星铁 ",
    "Smooth ": "光滑 ",
    "Bronze ": "青铜 ",
    "Slime ": "史莱姆 ",
    "Skywire ": "天线 ",
    "Pine ": "松木 ",
    "Poplar ": "杨木 ",
    "Mahogany ": "红木 ",
    "Maple ": "枫木 ",
    "Minor ": "迷你的 ",
    "Lesser ": "更小的 ",
    "Mithril ": "秘银 ",
    "Nidhogg's ": "尼德霍格的 ",
    "Mountain ": "山脉 ",
    "Sand ": "沙 ",
    "Dusk ": "幽暗的 ",
    "Forest ": "森林 ",
    "Elm ": "榆木 ",
    "Electrum ": "银金矿 ",
    "Drake ": "公鸭 ",
    "Desert ": "沙漠 ",
    "Hemp ": "麻类 ",
    "Green ": "绿色 ",
    "Red ": "红色 ",
    "Blue ": "蓝色 ",
    "Pink ": "粉色 ",
    "Orange ": "橙色 ",
    "Blonde ": "金色 ",
    "Light Blue ": "浅蓝色 ",
    "Neon Green ": "霓虹绿 ",
    "Neon Pink ": "霓虹粉 ",
    "Neon Purple ": "霓虹紫 ",
    "Brown ": "棕色 ",
    "Purple ": "紫色 ",
    "White ": "白色 ",
    "Refining ": "精炼 ",
    "Mirevine ": "米尔烯 ",
    "Grass ": "草 ",
    "Black ": "黑色 ",
    "Yggdrasil Infused ": "宇宙树灌注 ",
    "Pristine ": "原始 ",
    "Adamant ": "坚硬的 ",
    "Sisal ": "剑麻 ",
    "Vulcanite ": "硬胶 ",
    "Iron ": "铁 ",
    "Potent ": "强力",
    "Gathering: ": "收集: ",
    "Monsters: ": "怪物: ",
    "(Min level ": "(最低等级 ",
    "Rest in the tavern hall - ": "在酒馆大厅休息 - ",
    "Hot meal and a bed - ": "热饭和床 - ",
    "Client version: ": "客户端版本: ",
    "Server version: ": "服务器版本: ",
    "Apprentice (Lv: ": "学徒 (等级: ",
    "Arcane Mage (Lv: ": "奥术法师 (等级: ",
    "Archer (Lv: ": "弓箭手 (等级: ",
    "Berserker (Lv: ": "狂战士 (等级: ",
    "Mercenary (Lv: ": "雇佣兵 (等级: ",
    "Priest (Lv: ": "海盗 (等级: ",
    "Warrior (Lv: ": "战士 (等级: ",
    "Wizard (Lv: ": "术士 (等级: ",
    "Sorcerer (Lv: ": "男巫 (等级: ",
    "Sniper (Lv: ": "狙击手 (等级: ",
    "Scout (Lv: ": "侦察兵 (等级: ",
    "Rogue (Lv: ": "盗贼 (等级: ",
    "Mage (Lv: ": "法师 (等级: ",
    "Knight (Lv: ": "骑士 (等级: ",
    "Assassin (Lv: ": "刺客 (等级: ",
    "Acolyte (Lv: ": "侍僧 (等级: ",
    "Arcane Mage": "奥术法师",
    "Archer": "弓箭手",
    "Berserker": "狂战士",
    "Mercenary": "雇佣兵",
    "Priest": "海盗",
    "Warrior": "战士",
    "Wizard": "术士",
    "Sorcerer": "男巫",
    "Sniper": "狙击手",
    "Scout": "侦察兵",
    "Rogue": "盗贼",
    "Mage": "法师",
    "Knight": "骑士",
    "Assassin": "刺客",
    "Acolyte": "侍僧",
    "Shredded ": "破碎的",
    "Limit ": "上限 ",
    "Buy": "购买",
    "Sell": "出售",
    "You claimed achivement ": "收集了奖励来自成就 ",
    "and Title ": "和头衔 ",
    "Value: ": "价值: ",
    "Weight: ": "重量: ",
    "Tier: ": "层级: ",
    "Battle started on ": "战斗开始于 ",
    "Battles won: ": "战斗胜利: ",
    "XP: ": "经验值: ",
    "EXP: ": "经验值: ",
    "You don't have any of ": "你没有任何 ",
    "Recommended level: ": "推荐等级：",
    "Quest progress ": "任务进度 ",
    "BOUNTY] Securing Mountains ": "悬赏] 守护高山 ",
    "BOUNTY] Securing Forest ": "悬赏] 守护森林 ",
    "BOUNTY] Securing Desert ": "悬赏] 守护沙漠 ",
    "BOUNTY] Securing Capital ": "悬赏] 守护王城 ",
    "[BOUNTY] Securing Mountains ": "[悬赏] 守护高山 ",
    "[BOUNTY] Securing Forest ": "[悬赏] 守护森林 ",
    "[BOUNTY] Securing Desert ": "[悬赏] 守护沙漠 ",
    "[BOUNTY] Securing Capital ": "[悬赏] 守护王城 ",
    "Rewards: ": "奖励: ",
    "Reward Fame Points: ": "奖励声望点数: ",
    "Use torch when stack reaches ": "使用 火炬 当堆叠达到 ",
    "Use bedroll when stack reaches ": "使用 铺盖 当堆叠达到",
    "Dungeon run time: ~": "地下城运行时间 ~",
    "BOSS: ": "BOSS: ",
    "Get one of your characters to level ": "让你的一个角色升级到等级 ",
    "Get level ": "达到等级 ",
    "Lv: ": "等级: ",
    "Barrens Bloom ": "贫瘠之花 ",
    "Blighted Cotton ": "枯萎的棉花 ",
    "(Hit chance: ": "(命中率: ",
    "You've put Meat Scraps ": "你放置了 碎肉 ",
    "You've put Jellopy ": "你放置了 杰洛皮 ",
    "You've put Tin Ore ": "你放置了 锡矿石 ",
    "You've put Copper Ore ": "你放置了 铜矿石 ",
    "You've put Stone I ": "你放置了 石头 I ",
    "You've put Feather ": "你放置了 羽毛 ",
    "You've put Shredded Hide ": "你放置了 碎皮 ",
    "Boulder I ": "巨石 I ",
    "Thick Leather ": "厚皮 ",
    "Tanned Leather ": "鞣制皮 ",
    "Scaly Leather ": "鳞皮 ",
    "Crude Leather ": "粗皮 ",
    "Jute ": "黄麻 ",
    "Linen ": "亚麻 ",
    "received healing of +": "获得了治疗 +",
    "Battlefield Weather: ": "战场天气: ",
    "Lv. ": "等级 ",
    "Raw material, ": "原材料，",
    "HEALING: ": "治愈: ",
    "Plant ": "植物 ",
    "Skinnable Body ": "可剥皮的身体 ",
    "Elixir of Evasion": "闪避药水",
    "Elixir of Cunningness": "狡猾药水",
    "Elixir of Fortitude": "坚韧药水",
    "Elixir of Luck": "幸运药水",
    "Elixir of Magic": "魔法药水",
    "Elixir of Might": "实力药水",
    "Elixir of Perception": "洞察药水",
    "Elixir of Willpower": "意志药水",
    "Elixir of Accuracy": "精准药水",
    "Required Level: ": "要求等级: ",
    "Metal x": "金属 x",
    "Bark x": "树皮 x",
    "Yggdrasil Arcane Powder x": "宇宙树奥术粉末 x",
    "Log x": "原木 x",
    "Hide x": "皮 x",
    "Ore x": "矿石 x",
    "Oak Log x": "橡树原木 x",
    "Adamantite Ore x": "金刚石矿石 x",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " in your backpack": " 放进了你的背包里",
    " (FREE)": " (免费)",
    " Z": " 金币",
    ". Log": ". Log",
    " available for you to plant": " 可供您种植",
    " with Arcane Mage class": " 奥术法师 职业",
    " with Archer class": " 弓箭手 职业",
    " with Berserker class": " 狂战士 职业",
    " with Mercenary class": " 雇佣兵 职业",
    " with Priest class": " 海盗 职业",
    " with Warrior class": " 战士 职业",
    " with Wizard class": " 术士 职业",
    " with Sorcerer class": " 男巫 职业",
    " with Sniper class": " 狙击手 职业",
    " with Scout class": " 侦察兵 职业",
    " with Rogue class": " 盗贼 职业",
    " with Mage class": " 法师 职业",
    " with Knight class": " 骑士 职业",
    " with Assassin class": " 刺客 职业",
    " with Acolyte class": " 侍僧 职业",
    "Apprentice class and grasp the basics of magic.": "学徒职业，掌握魔法的基础知识。",
    "Scout class and blend into the shadows.": "侦察兵职业，隐身于暗处。",
    "Warrior class and sharpen your skills": "战士职业，磨砺技能",
    "Acolyte class and mend with grace.": "侍僧职业，修得优雅。",
    "Archer class and roam with precision.": "弓箭手职业，精准漫游。",
    "Knight class and defend with honor.": "骑士职业，以荣誉防守。",
    "Mage class and delve into arcane studies.": "法师职业，钻研奥术研究。",
    "Mercenary class and venture beyond the horizon.": "雇佣兵职业，远涉天际。",
    "Rogue class and master the art of stealth.": "盗贼职业，掌握潜行的艺术。",
    "Sorcerer class and cast powerful spells.": "男巫职业，能施放强大的法术。",
    "Apprentice class and master your craft.": "学徒职业，掌握你的手艺。",
    "Scout class and become the silent predator.": "侦察兵职业，成为沉默的掠夺者。",
    "Warrior class and dominate the battlefield.": "战士职业，称霸战场。",
    "Acolyte class and guide with divine light.": "侍僧职业，神光指引。",
    "Archer class and hit every target.": "弓箭手职业，击中每一个目标。",
    "Knight class and rule with your blade.": "骑士职业，用你的剑统治。",
    "Mage class and record your magical prowess.": "法师职业，记录自己的魔法实力。",
    "Mercenary class and become the ultimate warrior for hire.": "雇佣兵职业，成为受雇的终极战士。",
    "Rogue class and outwit all foes.": "盗贼职业，智胜所有敌人。",
    "Sorcerer class and become a fountain of wisdom.": "男巫职业，成为智慧之泉。",
    "Apprentice class and begin your magical learning.": "学徒职业，开始你的魔法学习。",
    "Scout class and start your stealthy journey.": "侦察兵职业，开始你的隐秘之旅。",
    "Warrior class and find your inner fighter": "战士职业，找到你内心的战士",
    " Mastery skill level has increased!": " 精通技能等级提升了！",
    " skill level has increased!": " 技能等级提升了！",
    " have been completed": " 已完成",
    "]": "]",
    "!!": "!!",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\-([\d\.]+) \(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^\- Another job well done\? Perfect, (.+). Farmer (.+) will be very pleased.$/, '- 又完成了一项工作？很好，$1。农夫 $2 会很高兴的。'],
    [/^Damage dealt: (.+), Damage received: (.+)$/, '造成的伤害: $1, 受到的伤害: $2'],
    [/^received (.+) experience points$/, '获得了 $1 经验值'],
    [/^used Meat Scraps and restored (.+) HP (.+)  to$/, '使用了碎肉，恢复 $1 生命值 $2 到'],
    [/^You\'ve received (.+) fame points$/, '你获得了 $1 名誉点数'],
    [/^(.+) bribed the gods to increase the wealth in the world \(Drop gain buff increased by (.+) minutes\)$/, '$1 贿赂众神增加世界的财富（掉落增益Buff增加 $2 分钟）'],
    [/^(.+) bestow upon everyone his blessing and brought knowledge to the world \(EXP gain buff increased by (.+) minutes\)$/, '$1 祝福了所有人并为世界带来知识（经验增益增加 $2 分钟）!'],
    [/^(.+)\'s level has increased!$/, '$1 的等级提升了!'],
    [/^(.+) \(Lvl. ([\d\.,]+)\)$/, '$1 (等级 $2)'],
    [/^([\d\.,]+) min \(([\d\.,]+) Z\)$/, '$1 分钟（$2 钱）'],
    [/^([\d\.,]+) Jan ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Feb ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Mar ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Apr ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) May ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Jun ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Jul ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Aug ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Sep ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Oct ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Nov ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Dec ([\d\.,]+) ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1 日 $3:$4:$5'],
    [/^([\d\.,]+) Jan \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '1 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Feb \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '2 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Mar \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '3 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Apr \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '4 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) May \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '5 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Jun \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '6 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Jul \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '7 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Aug \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '8 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Sep \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '9 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Oct \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '10 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Nov \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '11 月 $1 日 \- $2:$3:$4'],
    [/^([\d\.,]+) Dec \- ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '12 月 $1 日 \- $2:$3:$4'],
    [/^\(([\d\.,]+) Jan ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '1 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Feb ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '2 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Mar ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '3 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Apr ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '4 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) May ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '5 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Jun ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '6 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Jul ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '7 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Aug ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '8 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Sep ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '9 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Oct ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '10 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Nov ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '11 月 $1 日 $2:$3:$4'],
    [/^\(([\d\.,]+) Dec ([\d\.,]+):([\d\.,]+):([\d\.,]+)\)$/, '12 月 $1 日 $2:$3:$4'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) min$/, '$1 分钟'],
    [/^([\d\.]+) hours$/, '$1 小时'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1 小时 $2 分'],
    [/^([\d\.]+)h ([\d\.]+)s$/, '$1 小时 $2 秒'],
    [/^([\d\.]+)d ([\d\.]+)m ([\d\.]+)s$/, '$1天 $2分钟 $3秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) rerun$/, '$1 重复'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Exp$/, '$1 经验值'],
    [/^([\d\.,]+) EXP, ([\d\.,]+) Z, ([\d\.,]+) Fame$/, '$1 经验值, $2 金币, $3 声望'],
    [/^You looted Vial of Spider Venom x([\d\.,]+)$/, '你获得了 小瓶蜘蛛毒液 x$1'],
    [/^You looted Shredded Hide x([\d\.,]+)$/, '你获得了 碎皮 x$1'],
    [/^You looted Molted Feather x([\d\.,]+)$/, '你获得了 蜕羽 x$1'],
    [/^You looted Common Spider Silk x([\d\.,]+)$/, '你获得了 普通蜘蛛丝 x$1'],
    [/^You looted Bug Leg x([\d\.,]+)$/, '你获得了 虫腿 x$1'],
    [/^You looted Feather x([\d\.,]+)$/, '你获得了 羽毛 x$1'],
    [/^You looted Jellopy x([\d\.,]+)$/, '你获得了 杰洛皮 x$1'],
    [/^You\'ve looted Sticky Mucus x([\d\.,]+)$/, '你获得了 黏液 x$1'],
    [/^You\'ve looted Nochia Grass x([\d\.,]+)$/, '你获得了 夜蛾草 x$1'],
    [/^You\'ve looted Elm Log x([\d\.,]+)$/, '你获得了 榆树原木 x$1'],
    [/^You\'ve looted Tin Ore x([\d\.,]+)$/, '你获得了 锡矿石 x$1'],
    [/^You\'ve looted Copper Ore x([\d\.,]+)$/, '你获得了 铜矿石 x$1'],
    [/^You\'ve looted Straw Fibers (.+) x([\d\.,]+)$/, '你获得了 稻草纤维 $1 x$2'],
    [/^You\'ve looted Vial of Spider Venom (.+) x([\d\.,]+)$/, '你获得了 小瓶蜘蛛毒液 $1 x$2'],
    [/^You\'ve looted Fine Sand (.+) x([\d\.,]+)$/, '你获得了 细沙 $1 x$2'],
    [/^You\'ve looted Kelp (.+) x([\d\.,]+)$/, '你获得了 海藻 $1 x$2'],
    [/^You\'ve looted Stone (.+) x([\d\.,]+)$/, '你获得了 石头 $1 x$2'],
    [/^You\'ve looted Shredded Hide x([\d\.,]+)$/, '你获得了 碎皮 x$1'],
    [/^You\'ve looted Feather x([\d\.,]+)$/, '你获得了 羽毛 x$1'],
    [/^You\'ve looted Bug Leg x([\d\.,]+)$/, '你获得了 虫腿 x$1'],
    [/^You\'ve looted Common Spider Silk x([\d\.,]+)$/, '你获得了 普通蜘蛛丝 x$1'],
    [/^You\'ve looted Molted Feather x([\d\.,]+)$/, '你获得了 蜕羽 x$1'],
    [/^You\'ve looted Jellopy x([\d\.,]+)$/, '你获得了 杰洛皮 x$1'],
    [/^You\'ve looted Meat Scraps x([\d\.,]+)$/, '你获得了 碎肉 x$1'],
    [/^You looted Meat Scraps x([\d\.,]+)$/, '你获得了 碎肉 x$1'],
    [/^You looted Copper Ore x([\d\.,]+)$/, '你获得了 铜矿石 x$1'],
    [/^You looted Tin Ore x([\d\.,]+)$/, '你获得了 锡矿石 x$1'],
    [/^You looted Stone (.+) x([\d\.,]+)$/, '你获得了 石头 $1 x$2'],
    [/^\(Lvl: ([\d\.,]+)\)$/, '(等级: $1)'],
    [/^\(Lvl: ([\d\.,]+)\) and$/, '(等级: $1) 和'],
    [/^Desert ([\d\.,]+)$/, '沙漠 $1'],
    [/^Round ([\d\.,]+)$/, '回合 $1'],
    [/^Capital ([\d\.,]+)$/, '首都 $1'],
    [/^recovered \+([\d\.,]+) MP$/, '回复了 \+$1 法力值'],
    [/^Collect Gnoll Necklace x([\d\.,]+)$/, '收集 豺狼人项链 x$1'],
    [/^Collect Fish Hook x([\d\.,]+)$/, '收集 鱼钩 x$1'],
    [/^Collect Meat Scraps x([\d\.,]+)$/, '收集 碎肉 x$1'],
    [/^Kill Mountain Warthog x([\d\.,]+)$/, '击杀 高山疣猪 x$1'],
    [/^Kill Mountain Wolf x([\d\.,]+)$/, '击杀 高山狼 x$1'],
    [/^Kill Mountain Owl x([\d\.,]+)$/, '击杀 高山猫头鹰 x$1'],
    [/^Kill Mountain Snail x([\d\.,]+)$/, '击杀 高山蜗牛 x$1'],
    [/^Kill Mountain Greathorn x([\d\.,]+)$/, '击杀 高山巨兽 x$1'],
    [/^Kill Mountain Bat x([\d\.,]+)$/, '击杀 高山蝙蝠 x$1'],
    [/^Kill Treant x([\d\.,]+)$/, '击杀 树人 x$1'],
    [/^Kill Juvenile Shark x([\d\.,]+)$/, '击杀 幼鲨 x$1'],
    [/^Kill Lesser Spheria x([\d\.,]+)$/, '击杀 小球蛋白 x$1'],
    [/^Kill Feral Rats x([\d\.,]+)$/, '击杀 野鼠 x$1'],
    [/^Kill Fangrot x([\d\.,]+)$/, '击杀 牙怪 x$1'],
    [/^Kill Earth Snake x([\d\.,]+)$/, '击杀 土蛇 x$1'],
    [/^Kill Earth Bull x([\d\.,]+)$/, '击杀 土牛 x$1'],
    [/^Kill Dire Frostwolf x([\d\.,]+)$/, '击杀 可怕的霜狼 x$1'],
    [/^Kill Desert Parasand x([\d\.,]+)$/, '击杀 沙漠寄生虫 x$1'],
    [/^Kill Desert Horned Rabbit x([\d\.,]+)$/, '击杀 沙漠角兔 x$1'],
    [/^Kill Desert Cactus Renegade x([\d\.,]+)$/, '击杀 沙漠仙人掌叛变者 x$1'],
    [/^Kill Colossal Scorpion x([\d\.,]+)$/, '击杀 巨蝎 x$1'],
    [/^Kill Beach Crawler x([\d\.,]+)$/, '击杀 沙滩爬行者 x$1'],
    [/^Kill Baby Fox x([\d\.,]+)$/, '击杀 幼狐 x$1'],
    [/^Kill Baby Tiger x([\d\.,]+)$/, '击杀 幼虎 x$1'],
    [/^Kill Arcana Skeleton x([\d\.,]+)$/, '击杀 奥秘骷髅 x$1'],
    [/^Kill Catermoth x([\d\.,]+)$/, '击杀 毛虫 x$1'],
    [/^Kill Ancient Cactus x([\d\.,]+)$/, '击杀 远古仙人掌 x$1'],
    [/^Kill Plainstrider x([\d\.,]+)$/, '击杀 扁黾 x$1'],
    [/^Kill Gnoll Warrior x([\d\.,]+)$/, '击杀 豺狼人战士 x$1'],
    [/^Kill Mummy x([\d\.,]+)$/, '击杀 木乃伊 x$1'],
    [/^Kill Hunter Hawk x([\d\.,]+)$/, '击杀 猎鹰 x$1'],
    [/^Kill Ghost Sphynx x([\d\.,]+)$/, '击杀 幽灵斯芬克斯 x$1'],
    [/^Kill Goblin Pillager x([\d\.,]+)$/, '击杀 哥布林掠夺者 x$1'],
    [/^Kill Goblin Sniper x([\d\.,]+)$/, '击杀 哥布林狙击手 x$1'],
    [/^Kill Hell Mantis x([\d\.,]+)$/, '击杀 地狱螳螂 x$1'],
    [/^Kill Sea Urchin x([\d\.,]+)$/, '击杀 海胆 x$1'],
    [/^Kill Slime Mage x([\d\.,]+)$/, '击杀 史莱姆法师 x$1'],
    [/^Kill Slime Warrior x([\d\.,]+)$/, '击杀 史莱姆战士 x$1'],
    [/^Kill Slime Healer x([\d\.,]+)$/, '击杀 史莱姆治疗者 x$1'],
    [/^Kill Slime Berserker x([\d\.,]+)$/, '击杀 史莱姆狂战士 x$1'],
    [/^Kill Slime Archer x([\d\.,]+)$/, '击杀 史莱姆射手 x$1'],
    [/^Kill Forest Spider x([\d\.,]+)$/, '击杀 森林蜘蛛 x$1'],
    [/^Kill Forest Spora x([\d\.,]+)$/, '击杀 森林孢子 x$1'],
    [/^Kill Forest Sprite x([\d\.,]+)$/, '击杀 森林精灵 x$1'],
    [/^Kill Red Spider x([\d\.,]+)$/, '击杀 红蜘蛛 x$1'],
    [/^Kill Sand Scorpid x([\d\.,]+)$/, '击杀 沙蝎 x$1'],
    [/^Kill Sand Slime x([\d\.,]+)$/, '击杀 沙史莱姆 x$1'],
    [/^Kill Sunscale Chromis x([\d\.,]+)$/, '击杀 阳麟彩人 x$1'],
    [/^Kill Plainstrider x([\d\.,]+), bring Meat Scraps x([\d\.,]+)$/, '击杀 扁黾 x$1，携带 肉屑 x$2'],
    [/^Kill Sunscale Chromis x([\d\.,]+), bring Fish Hook x([\d\.,]+)$/, '击杀 阳麟彩人 x$1，携带 鱼钩 x$2'],
    [/^Kill Sunscale Chromis x([\d\.,]+) and bring Fish Hook x([\d\.,]+) to Capital$/, '击杀 阳麟彩人 x$1 并 携带 鱼钩 x$2 到首都'],
    [/^Kill Gnoll Warrior x([\d\.,]+), bring Gnoll Necklace x([\d\.,]+)$/, '击杀 豺狼人战士 x$1，携带 豺狼人项链 x$2'],
    [/^(.+)\(等级 3\)$/, '$1（等级 $2）'],
    [/^Simple drops turned into rain making everyone soaked. It rains on battle field for ([\d\.,]+) rounds$/, '简单的雨滴变成了雨，让每个人都湿透了。在战场上下了 $1 回合雨'],
    [/^Level ([\d\.,]+) \- \+([\d\.,]+) slots$/, '等级 $1 - \+$2 槽位'],
    [/^Level ([\d\.,]+) \- ([\d\.,]+) scripts slots$/, '等级 $1 - $2 脚本槽位'],
    [/^Level ([\d\.,]+) \- decreases craft time and resources by (.+).$/, '等级 $1 - 减少制作时间和资源 $2。'],
    [/^Level ([\d\.,]+) \- unlocks an additional time slot$/, '等级 $1 - 解锁一个附加时间槽位'],
    [/^Mountains ([\d\.,]+)$/, '高山 $1'],
    [/^Rain ([\d\.,]+) rounds$/, '下雨 $1 回合'],
    [/^for ([\d\.,]+) rounds$/, '持续 $1 回合'],
    [/^Level ([\d\.,]+)!$/, '等级 $1!'],
    [/^Lv ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Quest expires in ([\d\.,]+) days$/, '任务将在 $1 天内到期'],
    [/^Mineral Vein I ([\d\.,]+)$/, '矿脉 I $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();