// ==UserScript==
// @name         Spacelar 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.16
// @description  Spacelar (https://spacelar.queslar.com/#/ref/543) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Spacelar.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://spacelar.queslar.com/favicon.ico
// @license      MIT
// @include      *https://spacelar.queslar.com/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/spacelar-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/spacelar-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/01/08 23:06
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "禁言",
    "Unmute": "播放",
    "Username": "用户名",
    "Forge your destiny: assemble a powerful mining fleet to unearth the galaxy's riches, command a fearsome armada to dominate the stars, or cultivate vast agricultural worlds to sustain your empire. The galaxy awaits your ambition—shape it as you see fit.": "锻造你的命运：组建一支强大的采矿舰队去挖掘银河系的财富，指挥一支可怕的舰队去统治星际，或者培育广阔的农业世界来维持你的帝国。银河系等待着你的雄心壮志——以你认为合适的方式塑造它。",
    "Establish and upgrade a formidable home base with specialized buildings, each offering unique capabilities to bolster your power. Harness the vast resources of space by mining asteroids for precious minerals, then refine them into essential materials to fuel your expansion. Whether you're managing a high-tech ship hangar, enhancing your forger for crafting superior modules, or expanding your academy to train elite crew members, every decision brings you closer to ruling the stars.": "用专门的建筑建立和升级一个强大的基地，每个建筑都提供独特的能力来增强你的力量。利用巨大的空间资源，开采小行星的珍贵矿物，然后将它们提炼成必要的材料，为你的扩张提供燃料。无论你是在管理一个高科技的飞船机库，增强你的锻造厂以制作高级模块，还是扩大你的学院以训练精英船员，每一个决定都会让你更接近统治星空。",
    "Embark on a journey through vast star systems, uncovering new planets, asteroid belts, pirate lairs or hidden expeditions. Each star system you explore offers unique resources to gather and challenges to conquer, pushing your strategic and survival skills to the limit as you navigate the mysteries of the cosmos.": "踏上穿越浩瀚星系的旅程，发现新的行星，小行星带，海盗巢穴或隐藏的探险。你探索的每一个星系都提供了独特的资源来收集和征服挑战，当你在宇宙的奥秘中航行时，将你的战略和生存技能推向极限。",
    "Discover the limitless possibilities of crafting with Aetherium, a rare cosmic substance that transforms ordinary items into legendary gear. Merge, recraft, and enhance your equipment using various types of Aetherium to boost stats, create hybrid items, and perfect your build. With every expedition, collect and harness Aetherium to forge a path to greatness among the stars.": "使用光晶（一种罕见的宇宙物质，可将普通物品转变为传奇装备）探索制作的无限可能性。合并，锻造，并增强您的装备使用各种类型的光晶来提高属性，创建混合物品，并完善您的构建。在每一次探险中，收集和利用光晶，在星际中开辟一条通往伟大的道路。",
    "Engage in intense battles against pirates and rival players. Equip and customise your fleet with a variety of offensive and defensive modules to gain the upper hand in galactic warfare. Tailor your strategy by enhancing weapon accuracy, disabling your enemy sensors, dodge incoming attacks or any of the other 50+ stats our combat engine offers, in order to dominate your enemies and expand your influence across the stars.": "参与与海盗和对手玩家的激烈战斗。用各种进攻和防御模块装备和定制你的舰队，以在银河战争中占据上风。通过提高武器精度，使敌人传感器失效，躲避来袭攻击或我们的战斗引擎提供的任何其他50+属性来定制您的策略，以主宰您的敌人并扩大您在星际的影响力。",
    "Unite with allies and dominate the galaxy in epic fleet battles! Form powerful alliances, strategize your fleet composition, and take on formidable enemies together. Combine your resources and strengths to conquer star systems, defend your territory, and rise to supremacy in the cosmos.": "与盟友联合起来，在史诗般的舰队战斗中统治银河系！组建强大的联盟，制定舰队组成战略，共同对抗强大的敌人。结合你的资源和力量来征服星系，保卫你的领土，并在宇宙中崛起。",
    "© 2024 Blah Games. All rights reserved.": "©2024 Blah Games。版权所有。",
    "Alliance Fleet Domination": "联盟舰队统治",
    "Beta available below!": "测试版如下！",
    "Build Your Empire": "建立你的帝国",
    "Choose Your Profession": "选择你的职业",
    "Craft Superior Ships": "制造高级船舶",
    "Dynamic Crafting System": "动态制作系统",
    "Explore the Galaxy": "探索银河系",
    "Forgot Password?": "忘记密码？",
    "Game Features": "游戏功能",
    "Join the adventure and build your empire in the vastness of space.": "加入冒险，在浩瀚的太空中建立你的帝国。",
    "Login": "登录",
    "New player? Click here!": "新玩家？点击这里!",
    "Password": "密码",
    "Please enable JavaScript to continue using this application.": "请启用JavaScript以继续使用此应用程序。",
    "Spacelar": "宇宙之星",
    "Strategic Combat": "战略作战",
    "For the ultimate challenge, Hardcore Ironman mode combines the solitude of Ironman with the high-stakes intensity of Hardcore. No trading, no allies, and permanent ship loss ensure only the most resilient captains survive.": "对于终极挑战，硬核铁人模式结合了铁人的孤独和硬核的高风险强度。没有贸易，没有盟友，永久的船只损失确保只有最具弹性的船长才能生存。",
    "Step into the Ironman mode and test your self-reliance in the vast expanse of space. With no trading and a strict solo play rule, this mode challenges your strategy and resourcefulness like never before.": "进入铁人模式，在浩瀚的太空中考验你的自立能力。没有交易和严格的单人游戏规则，这个模式前所未有地挑战你的策略和机智。",
    "Embark on the ultimate space-faring adventure with the Standard mode. Experience a balanced gameplay designed for exploration, fleet management, and galactic conquest. This is the default experience where the galaxy is yours to discover at your own pace.": "在标准模式中踏上终极太空冒险之旅。体验为探索，舰队管理和银河征服而设计的平衡玩法。这是默认的体验，银河系是你的，你可以按照自己的节奏去发现。",
    "By clicking sign up you agree to and have read our privacy policy terms and chat rules.": "通过点击注册，您同意并已阅读我们的隐私政策条款和聊天规则。",
    "Create Character": "创建角色",
    "Create New Character": "创建新角色",
    "Hardcore Ironman": "高难度铁人",
    "Ironman": "铁人",
    "Sign Up": "注册",
    "Your Characters": "你的角色",
    "Character name": "角色名称",
    "Create character": "创建角色",
    "Select Character": "选择角色",
    "Your character has been created": "你的角色已创建",
    "View Full Inventory": "查看完整库存",
    "Void": "虚空",
    "Wheat": "小麦",
    "Whispers": "私聊",
    "Titanium": "钛",
    "Trading Depot": "交易站",
    "Train and recruit crew members for your ships.": "为你的船只训练和招募船员。",
    "The heart of your base. Upgrading this unlocks new buildings and higher levels for other structures. Buildings cannot be upgraded higher than your main hub": "你基地的核心。升级这个可以解锁新的建筑和其他结构的更高级别。建筑物不能升级到高于你的主要枢纽",
    "Loading ...": "加载中 ...",
    "Logout": "登出",
    "Log": "日志",
    "Start Actions": "开始行动",
    "Starting Ship": "初始飞船",
    "Suggest Features": "建议功能",
    "Academy": "学院",
    "Action Confirmation Settings": "行动确认设置",
    "Account": "账号",
    "Accuracy": "精准",
    "Access the galactic market to trade resources and rare items.": "进入银河市场交易资源和稀有物品。",
    "Access the armory and equip your character with galaxy wide boosting items": "进入军械库，为你的角色装备银河范围内的提升道具",
    "Chat Settings": "聊天设置",
    "Delete Fleet": "删除舰队",
    "Dark Matter": "暗物质",
    "Crafting": "制作",
    "Colors": "颜色",
    "Clock type": "时钟类型",
    "Chat Rules": "聊天规则",
    "Chat": "聊天",
    "Display emotes": "显示表情",
    "Disband": "解散",
    "Gold Ore": "金矿石",
    "Gold Ore Tax": "金矿石税",
    "Gold Tax": "黄金税",
    "Iron Bar": "铁锭",
    "Item Recovery": "物品恢复",
    "Items": "物品",
    "Number formatting": "数字格式",
    "Platinum Ore Tax": "铂矿石税",
    "Personal Alliance Tax Settings": "联盟个人税设置",
    "platinum": "铂",
    "Platinum": "铂",
    "Sign up here!": "在这里注册！",
    "Stats Tracker": "统计跟踪器",
    "Upgrade": "升级",
    "Upgrade Stacking": "升级叠加",
    "Uranium Tax": "铀税",
    "Privacy Policy": "隐私政策",
    "Popup duration (seconds)": "弹出窗口持续时间（秒）",
    "Profile": "个人资料",
    "Move Fleet": "移动舰队",
    "My Tools": "我的工具",
    "My": "我的",
    "New": "新",
    "Menu": "菜单",
    "Menus": "菜单",
    "Join or create an alliance to collaborate with other players.": "加入或创建一个联盟与其他玩家合作。",
    "Merge channels": "合并频道",
    "Misc": "杂项",
    "Main Hub": "主枢纽",
    "Game Rules": "游戏规则",
    "General": "常规",
    "General galaxy": "常规星系",
    "Galaxy": "星系",
    "Adamantite": "金刚石",
    "Accel": "加速",
    "Craft advanced modules for your ships.": "为你的飞船制作高级模块。",
    "Credits": "信用点",
    "Docs": "文档",
    "Essence": "精华",
    "Eternity": "永恒",
    "Expedition Center": "远征中心",
    "Fleet": "舰队",
    "Farm": "农场",
    "Fuel": "燃料",
    "Forger": "锻造厂",
    "Flux": "通量",
    "Gold": "黄金",
    "Hide chat": "隐藏聊天",
    "Manage": "管理",
    "Market": "市场",
    "News": "新",
    "No alliance": "暂无联盟",
    "Obsidium": "黑曜石",
    "Produces essential food resources to sustain your crew.": "生产基本的食物资源来维持你的船员。",
    "Rankings": "排行榜",
    "Recruit": "招募",
    "Refine raw ores into valuable bars used for crafting and upgrading.": "将原始矿石提炼成有价值的锭，用于制作和升级。",
    "Report Bugs": "报告Bug",
    "Send": "发送",
    "Scrap Metal": "废金属",
    "Research Lab": "研究实验室",
    "Reforge": "重铸",
    "Send fleets on expeditions to discover uncharted space and rare resources.": "派遣舰队去探索未知的空间和稀有的资源。",
    "Shard": "碎片",
    "Ship Hangar": "飞船机库",
    "Shipyard": "船厂",
    "Staff Tracker": "人员追踪器",
    "Stasis": "停滞",
    "Stats": "统计",
    "Trade": "交易",
    "You do not have enough Iron Ore for this": "你没有足够的铁矿石来做这个",
    "You need to upgrade your main hub first": "你需要先升级你的主枢纽",
    "You need to upgrade your alliance post to use this feature.": "你需要升级你的联盟邮局来使用这个功能。",
    "You need to upgrade your trading depot to use this feature.": "你需要升级你的交易仓库才能使用这个功能。",
    "Alliance": "联盟",
    "Alliance Outpost": "联盟前哨",
    "Aetherium": "光晶",
    "Armory": "军械库",
    "Bar": "锭",
    "Bars": "锭",
    "Catalyst": "催化剂",
    "Cancel": "取消",
    "Chrono": "编年史",
    "Commands": "命令",
    "Command Center": "指挥中心",
    "Confirm": "确认",
    "Core": "核心",
    "Construct new ships to add to your fleet.": "建造新的船只并添加到你的舰队。",
    "Copper": "铜",
    "EcoDrive Complex": "生态驱动综合体",
    "Excavator": "挖掘机",
    "Expands your total ship capacity, allowing you to command more ships. Essential for galactic dominance. Upgradeable every 5 Main Hub levels.": "扩大你的总船只容量，让你可以指挥更多的船只。对银河系的统治至关重要。每5级主枢纽可升级一次。",
    "Habitat Dome": "栖息地圆顶",
    "Help": "帮助",
    "Harmony": "和谐",
    "Iron": "铁",
    "Iron Ore": "铁矿石",
    "Me": "我",
    "Main": "主频道",
    "New Fleet -": "新舰队 -",
    "Neutronium": "中子态",
    "Purification Plant": "净化厂",
    "Refinery": "精炼厂",
    "Spaceport": "太空港",
    "Structures": "结构",
    "Uninhabited": "无人居住",
    "View Location": "查看位置",
    "Create Account": "创建账号",
    "Confirm Password": "确认密码",
    "Each tool type has its own related base attack speed and modifier. Attack speed is also different between action types.\n\n    Combat speed: 5000ms\n    Farming speed: 30000ms\n    Mining speed: 30000ms\n    Drilling speed: 30000ms": "每种工具类型都有自己相关的基础攻击速度和修改值。攻击速度在不同的动作类型之间也是不同的。\n\n战斗速度：5000ms\n耕作速度：30000ms\n采矿速度：30000ms\n钻探速度：30000ms\n",
    "Critical Strike Multiplier": "暴击乘数",
    "Critical Strike Chance": "暴击几率",
    "Crew": "船员",
    "Drilling Speed": "钻探速度",
    "Filters": "过滤器",
    "Email": "邮箱",
    "Health": "生命值",
    "Health Regen": "生命值回复",
    "Icons": "图标",
    "Idle": "空闲",
    "Ignition Chance": "点燃几率",
    "Inventory": "库存",
    "Mining Amount": "采矿数量",
    "Mining Speed": "采矿速度",
    "Location:": "位置:",
    "Link in chat": "聊天链接",
    "Modules": "模块",
    "Movement Speed": "移动速度",
    "Navigation": "导航",
    "New Fleet": "新舰队",
    "new fleet": "新舰队",
    "Offensive": "攻击",
    "Referrals": "邀请",
    "Shield": "护盾",
    "Shield Recharge Rate": "护盾充能速率",
    "Ship Inventory": "飞船库存",
    "Sign up!": "注册!",
    "Titles": "称号",
    "Sound Notifications": "声音通知",
    "Referral ID - Did anyone refer you? Ask for their ID!": "推荐人ID - 有人推荐你吗？输入他们的ID！（若没有请输入我的: 543）",
    "If you want to save your progress, make sure to sign up.": "如果你想保存你的游戏进度，请务必注册。",
    "Hey! I hope you are enjoying the game.": "嘿!我希望你喜欢这个游戏。",
    "Coordinate your fleets and combine ship units into powerful formations. Upgradeable every 10 Main Hub levels.": "协调你的舰队，并将舰船单位组合成强大的编队。每10级主枢纽可以升级一次。",
    "Conduct research to boost your technologies": "进行研究来提升你的技术",
    "Cerulium": "铈",
    "Alliance Post": "联盟邮局",
    "Account Overview": "账号概览",
    "Account Name": "账号名称",
    "Active Sessions": "活动会话",
    "Armour": "装甲",
    "Armour Penetration": "装甲穿透",
    "Attack Damage": "攻击伤害",
    "Block Chance": "格挡几率",
    "Block Effect": "格挡效果",
    "Browser": "浏览器",
    "Change Password": "修改密码",
    "Change password": "修改密码",
    "Change Email": "修改邮箱",
    "Change email": "修改邮箱",
    "Confirm new email": "确认新邮箱",
    "Confirm new password": "确认新密码",
    "Current password": "当前密码",
    "Defensive": "防御",
    "Emp Chance": "电磁脉冲几率",
    "Emp Duration Boost": "电磁脉冲持续时长提升",
    "Fleets": "舰队",
    "Generate 2FA": "生成2FA",
    "Harvesting Speed": "收割速度",
    "Harvesting Amount": "收割数量",
    "IP Address": "IP地址",
    "Laser Damage": "激光伤害",
    "Last seen": "最近在线",
    "Location": "位置",
    "New password": "新邮箱",
    "New email": "新邮箱",
    "Open Slot": "打开槽位",
    "Signed up": "已注册",
    "Stats Tracker Settings": "统计跟踪器设置",
    "Thanks for signing up. Welcome!": "感谢您注册。欢迎！",
    "Tools": "工具",
    "Two Factor Authentication": "双因素身份验证",
    "UI Customization": "UI定制",
    "View location": "查看位置",
    "Fleet Overview": "舰队概览",
    "Ore": "矿石",
    "Ores": "矿石",
    "Food": "食物",
    "Uranium": "铀",
    "Last action, your fleet harvested": "最近行动，你的舰队收割了",
    "Last action, your fleet mined": "最近行动，你的舰队开采了",
    "Lasers have a base attack speed of 5s, and have the ability to charge damage": "激光的基础攻击速度为5秒，并且具有充能伤害的能力",
    "Laser Resistance Penetration": "激光防御穿透",
    "Limit reached, multiplier is capped": "已达上限，乘数已达上限",
    "Location X": "位置 X",
    "Location Y": "位置 Y",
    "Mining": "采矿",
    "Misc Module Efficiency": "杂项模块效率",
    "Move to fleet": "移动到舰队",
    "Name": "名称",
    "Harvesting": "收割",
    "No items were found.": "没有发现任何物品。",
    "No fleets available at ship location": "飞船所在位置暂无可用舰队",
    "Remove from fleet": "从舰队中移除",
    "Rename fleet": "重命名舰队",
    "Staff messages": "员工消息",
    "Staff list": "员工列表",
    "Transit": "运输",
    "The server could not be reached. The server is either down, the game is updating, or you have lost your connection. Hang tight!": "无法连接到服务器。要么服务器坏了，要么游戏在更新，要么你失去了连接。坚持住！",
    "Total Generation:": "总计生成：",
    "Unequip all": "卸下全部",
    "Unequip all crew": "卸下全部船员",
    "Unequip all modules": "卸下全部模块",
    "Unequip all tools": "卸下全部工具",
    "Waiting for action...": "等待行动…",
    "Wire": "发送",
    "You do not have enough Gold for this": "黄金不足，无法进行此操作",
    "Your fleet and crew has now started harvesting": "你的舰队和船员已经开始收割了",
    "Your fleet and crew has now started mining": "你的舰队和船员已经开始采矿了",
    "Your fleet has been queued and will start moving when its action is complete": "您的舰队已进入队列，行动完成后将开始移动",
    "Your fleet is currently not idling. Do you wish to cancel the ongoing activity?": "您的舰队当前正忙。您希望取消正在进行的行动吗？",
    "Extractors provide additional income from mining": "萃取器在采矿中提供额外的收入",
    "Fleet full": "舰队已满",
    "Fleet Name": "舰队名称",
    "Hydroponic Farm": "水培农场",
    "Increases the ability to penetrate laser resistance.": "提升激光穿透防御的能力。",
    "Increases the efficiency of defensive modules, improving their effectiveness.": "提升防御模块的效率，提高其效能。",
    "Increases the flat amount of resources gathered while drilling.": "提升钻探时采集的平面资源数量",
    "Increases the flat amount of resources gathered while harvesting.": "提升收割时采集的平面资源数量",
    "Increases the flat amount of resources gathered while mining.": "提升采矿时采集的平面资源数量",
    "Increases the flat damage dealt by laser weapons.": "提升激光武器造成的平面伤害。",
    "Increases the number of misc modules that can be equipped.": "增加可装备的杂项模块的数量。",
    "Increases the speed at which the ship harvests resources.": "提升飞船收割资源的速度",
    "Assign to Harvesting": "分配到收割",
    "Assign to Mining": "分配到采矿",
    "Character Screen": "角色界面",
    "Clear Filters": "重置过滤器",
    "Command Center -": "指挥中心 -",
    "Common": "普通",
    "Create New Fleet": "创建新舰队",
    "Custom filters": "自定义过滤器",
    "Delete fleet": "删除舰队",
    "Diggers provide additional income from harvesting": "挖掘机从收割中提供额外的收入",
    "Do you want new fleet to stop?": "你想让新舰队停下来吗？",
    "Do you want to assign new fleet to harvesting?": "你想指派新舰队去收割吗？",
    "Do you want to assign new fleet to mining?": "你想指派新舰队去采矿吗？",
    "Drilling Amount": "钻探数量",
    "Drills provide additional income from drilling": "钻机提供了额外的钻探收入",
    "Do you wish create a new fleet? Please input the following": "你想创建一个新的舰队吗？请输入以下内容",
    "Extra action": "额外行动",
    "Active": "活动",
    "My Crew": "我的船员",
    "Amount to Smelt": "熔炼数量",
    "Confirm Smelting": "确认熔炼",
    "Generation / hour": "生成 / 小时",
    "My Modules": "我的模块",
    "Not enough ores": "没有足够的矿石",
    "Upkeep / hour": "消耗 / 小时",
    "Workers": "工人",
    "workers assigned": "工人已分配",
    "You do not have enough Iron Bar, Adamantite Bar for this": "你没有足够的铁锭，金刚石锭来做这个",
    "Your Shipyard has been upgraded": "你的 船厂 已升级",
    "Your Farm has been upgraded": "你的 农场 已升级",
    "Your Forger has been upgraded": "你的 锻造厂 已升级",
    "Your Main Hub has been upgraded": "你的 主枢纽 已升级",
    "Your Refinery has been upgraded": "你的 精炼厂 已升级",
    "Income": "收入",
    "inhabitants": "居民",
    "Recall": "召回",
    "Spending": "支出",
    "Unless anything else has been stated, custom channels are not moderated by the Spacelar staff for anything but illegal activity. For clarifications casino channels such as the roulette chat or poker room chat are not custom channels.": "除非另有说明，否则自定义频道不会受到Spacelar工作人员的审核，除非是非法活动。需要澄清的是，赌·场频道（如轮盘赌聊天或扑克室聊天）不是自定义频道。",
    "Posting any not safe for work content must include a tag. It is recommended to use [NSFW]. If you are unsure whether or not a post may be not safe for work, contact a staff member. For the action against this, read dealing with chat offenses at the bottom of the chat rules.": "张贴任何不安全的工作内容必须包含标签。建议使用[NSFW]。如果你不确定某个职位是否适合工作，请联系工作人员。关于这种行为，请阅读聊天规则底部的处理聊天违规。",
    "Posting other peoples private information is not allowed without their explicit permission. For the action against this, read dealing with chat offenses at the bottom of the chat rules.": "未经他人明确许可，不得发布他人的私人信息。关于这种行为，请阅读聊天规则底部的处理聊天违规。",
    "Respect the intention of channels, may it be official or custom channels. For example the trade channel must only contain messages related to trading, the recruiting channel must only contain messages related to any kind of recruiting, and no trolling is allowed in the help channel. For the action against this, read dealing with chat offenses at the bottom of the chat rules.": "尊重频道的意向，可能是官方渠道，也可能是客户渠道。例如，交易频道必须只包含与交易相关的消息，招聘频道必须只包含与任何招聘相关的消息，帮助频道不允许恶意攻击。关于这种行为，请阅读聊天规则底部的处理聊天违规。",
    "Spam is not allowed. Spam is a quite subjective definition, and will be loosely defined to many sentences in a short amount of seconds. For the action against this, read dealing with chat offenses at the bottom of the chat rules.": "垃圾邮件是不允许的。垃圾邮件是一个非常主观的定义，在很短的时间内会被松散地定义为许多句子。关于这种行为，请阅读聊天规则底部的处理聊天违规。",
    "If someone has ignored you, or you have been muted, it is not allowed to evade this. There is a reason why this action has been done against you. For the action against this, read dealing with chat offenses at the bottom of the chat rules.": "如果有人忽略了你，或者你被禁言了，是不允许回复的。对你采取这种行动是有原因的。关于这种行为，请阅读聊天规则底部的处理聊天违规。",
    "Trading currencies or items for other game currencies or items must under no circumstance happen in any official channel managed by the Spacelar staff, both inside and outside the game of Spacelar, may it be Discord, Reddit or other chatting services. If you wish to trade between games, the facilitation must be done somewhere else. For the action against this, read dealing with chat offenses at the bottom of the chat rules.": "交易货币或物品的其他游戏货币或物品在任何情况下都不得发生在任何由Spacelar工作人员管理的官方渠道，无论是在Spacelar的游戏内外，可能是Discord， Reddit或其他聊天服务。如果你希望在游戏间进行交易，那么必须在其他地方进行撮合。关于这种行为，请阅读聊天规则底部的处理聊天违规。",
    "Any first chat offense will be receive a one hour mute. 2nd offense 1 day mute, 3rd offense 1 week mute, 4th offense 1 month mute, and 5th offense indefinitely mute. If you proceed to find ways to break chat rules after receiving a indefinite mute, your account involved will be indefinitely banned. A warning will be given before the first chat offense, a first warning will not be given for a cross-trading or spam offenses.": "第一次聊天犯规将被罚禁言一小时。第二次犯规1天禁言，第三次犯规1周禁言，第四次犯规1个月禁言，第五次犯规无限期禁言。如果您在收到无限期禁言后继续寻找违反聊天规则的方法，您的帐户将被无限期封禁。第一次聊天违规前将给予警告，交叉交易或垃圾邮件违规不给予第一次警告。",
    "Any hate speech (sexist, racist, homophobic etc), harassing, threatening, or stalking other players is not allowed. Examples of sentences not allowed is calling other players for 'retarded, faggots or niggers'. For the action against this, read dealing with chat offenses at the bottom of the chat rules.": "任何仇恨言论（性别歧视，种族歧视，同性恋等），骚扰，威胁，或跟踪其他球员是不允许的。不允许的句子的例子是称其他球员为“智障，同性恋或黑鬼”。关于这种行为，请阅读聊天规则底部的处理聊天违规。",
    "Channels": "渠道",
    "Cross-trading": "交叉交易",
    "Custom Channels": "自定义频道",
    "Dealing with chat offenses": "处理聊天违规行为",
    "Evading Mutes / Ignores": "逃避禁言/忽视",
    "Impersonating Staff": "冒充工作人员",
    "Impersonating staff members is not allowed. For the action against this, read dealing with chat offenses at the bottom of the chat rules.": "不允许冒充员工。关于这种行为，请阅读聊天规则底部的处理聊天违规。",
    "Offensive Speech": "攻击性言论",
    "Personal Information": "个人信息",
    "Spam": "垃圾邮件",
    "Amount": "数量",
    "24 Hour Clock": "24小时时钟",
    "12 Hour Clock": "12小时时钟",
    "Auctions in trade": "拍卖交易",
    "Buy Currency": "购买货币",
    "Buy Items": "购买物品",
    "Copy your ref code to your clipboard": "复制你的邀请链接的哦啊剪贴板",
    "Crafting outcome defaults": "制作结果默认值",
    "Donate": "捐赠",
    "Deletions": "删除",
    "Equip": "装备",
    "Hidden": "隐藏",
    "Hold Shift": "按下 Shift",
    "Hold Control": "按下 Ctrl",
    "Hold Control + Shift": "按下 Ctrl + Shift",
    "Invites": "邀请",
    "Items per page:": "每页显示数量:",
    "Kick": "踢掉",
    "Leave": "离开",
    "Local": "本地",
    "On": "开",
    "Off": "关",
    "Ore Tax": "矿石税",
    "Player Name": "玩家名称",
    "Recovery": "恢复",
    "Remove Item Listing": "移除物品清单",
    "Resets": "重置",
    "Reverse Chat": "翻转聊天",
    "Sell": "出售",
    "Sell Currency": "出售货币",
    "Server": "服务器",
    "Sort": "排序",
    "Tax": "税",
    "Visible": "可见",
    "Timezone": "时区",
    "Wires": "发送",
    "Your referral link:": "你的邀请链接:",
    "All Rarities": "所有稀有度",
    "Crew level": "船员等级",
    "Crew Recruiting": "船员招募",
    "Epic": "史诗",
    "Rare": "稀有",
    "Refresh list": "刷新列表",
    "Scrap": "垃圾",
    "Unique": "独特",
    "Use your gold to roll for new recruitable crew members.": "使用你的黄金可刷新出新的可招募船员。",
    "active ships": "活动飞船",
    "Craft a New Item": "制作一个新物品",
    "Crafting Overview": "制作概览",
    "Critical Strike Reduction": "暴击减免",
    "Durability Penalty Reduction": "耐久惩罚减免",
    "Energy Distortion Chance": "能量畸变几率",
    "Forge History": "锻造历史",
    "Farm Log": "农场日志",
    "Gives a chance to gain invulnerability for a certain number of attacks when the shield is destroyed.": "当护盾被摧毁时，有一定几率在一定次数的攻击后获得无敌。",
    "Gives a chance to reduce the attack speed of enemies.": "有一定几率降低敌人的攻击速度。",
    "You receive active workers from upgrading your refinery, forger or farm. These can be assigned to each activity both here from, the full overview of all worker activites, but also in each individual view.": "升级精炼厂、锻造厂或农场可以获得活跃的工人。这些可以在这里分配给每个活动，所有工人活动的全面概述，也可以在每个单独的视图中分配。",
    "Gives turrets a chance to fire a double shot.": "让炮塔有几率进行双发射击。",
    "Hangar -": "机库 -",
    "Hourly Food Upkeep": "每小时食物维护成本",
    "Increases the amount of resources gathered while mining by a percentage.": "以一定百分比增加采矿时收集的资源数量。",
    "Increases the chance of landing a critical strike.": "增加暴击的几率。",
    "Increases the chances of finding rare resources while mining.": "增加采矿时发现稀有资源的概率",
    "Increases the duration of EMP effects on the target.": "增加对目标电磁脉冲的持续时间的影响。",
    "Increases the hourly food upkeep when active": "活动时增加每小时的食物维护成本",
    "Item merging unlocks after unlocking your expedition center in your main hub": "物品合并，需要在您的主要枢纽里面解锁远征中心",
    "Item recrafting unlocks after unlocking your expedition center in your main hub": "物品重铸，需要在您的主要枢纽里面解锁远征中心",
    "Merge Items": "合并物品",
    "Mining Rarity Multiplier": "采矿稀有度倍率",
    "Module": "模块",
    "No ongoing crafts.": "没有正在进行的制作。",
    "Ongoing Crafts": "正在进行的制作",
    "Recraft Items": "重制物品",
    "Reduces the damage taken from critical strikes by a percentage.": "降低暴击造成的伤害百分比。",
    "Reduces the penalties incurred from low durability.": "减少因耐久过低而受到的惩罚。",
    "Refinery Log": "精炼厂日志",
    "Select Item Type": "选择物品类型",
    "Shield Destruction Invulnerability Chance": "护盾损毁后的无敌几率",
    "Start Crafting": "开始制作",
    "Toggle workers idle when out of ore": "当矿石耗尽时切换工人状态为空闲",
    "Tool": "工具",
    "Turret Double Shot": "炮塔双炮",
    "Upkeep:": "维护成本：",
    "Workers get faster with every upgrade of their relevant building, make sure to keep an eye on the upkeep costs though!": "随着相关建筑的每次升级，工人们的速度会更快，但一定要注意维护成本！",
    "You have no recent forges": "你没有最近的锻造",
    "You have received a new set of recruits": "你有了一批新成员",
    "Base Hull": "基础船体",
    "Gives a chance to ignite the target, dealing damage over time and reducing health regeneration.": "有一定几率点燃目标，造成持续伤害并降低生命回复。",
    "Gives a chance to trigger an EMP effect, reducing the enemy’s accuracy.": "有一定几率触发电磁脉冲效果，降低敌人的精度。",
    "Hull": "船体",
    "Improves the accuracy of all weapons.": "提升所有武器的命中。",
    "Increases the damage multiplier when a critical strike is achieved.": "暴击时增加伤害乘数。",
    "Increases the flat rate of health regeneration.": "增加生命值的平面回复率。",
    "Increases the ship’s maximum shield by a flat amount.": "增加飞船的最大护盾以一个平面数量。",
    "Increases the ship’s maximum health by a flat amount.": "增加飞船的最大生命值以一个平面数量。",
    "a cadent extractor": "一个有节奏的萃取器",
    "a depraved drill": "一个堕落的钻机",
    "a wonted digger": "一个习惯的挖掘机",
    "Additional Misc Modules": "其他杂项模块",
    "Allows attacks to ignore a portion of the enemy’s armor.": "攻击时可以忽略敌人的部分护甲。",
    "an unshorn laser": "一个未剪短的激光器",
    "Auction all filtered": "拍卖全部已过滤",
    "Delete all filtered": "删除全部已过滤",
    "Do you wish to equip a depraved drill to Starting Ship": "你想在出发船上装备一个堕落的钻机吗",
    "Extra actions": "额外的行动",
    "Lock (prevents destroying)": "锁定（防止误操作）",
    "Sell all filtered": "出售全部已过滤",
    "Wire all filtered": "发送全部已过滤",
    "You have no available tool slots": "您没有可用的工具槽",
    "Fire": "解雇",
    "Ships": "飞船",
    "Income is 50% effective due to being out of gold": "由于没有黄金，收入效率只有50%",
    "Smugglers Stash": "走私者藏匿处",
    "Your fleet and crew has now stopped mining": "你的舰队和船员已经停止采矿",
    "Assign to Pirates": "指派为海盗",
    "Attacks": "攻击",
    "Current": "当前",
    "Defeats": "战败",
    "Effects": "效果",
    "extractor": "萃取器",
    "laser": "激光",
    "missed the attack on": "未命中",
    "Pirate Level": "海盗等级",
    "Regen": "回复",
    "regenerates": "再生",
    "Your fleet and crew has now started pirates": "你的舰队和船员现在已经成为海盗了",
    "Do you wish to unequip Adam Deconti from Starting Ship": "",
    "all tools has been unequipped from Starting Ship": "所有工具都已从初始飞船上卸下",
    "has been destroyed": "已经被摧毁了",
    "Move to": "移动到",
    "Pirates": "海盗",
    "Unequip": "卸下",
    "Infused Wheat": "灌浆小麦",
    "Action": "行动",
    "Daily": "日常",
    "Deaths": "死亡",
    "Drilling": "钻探",
    "Expedition": "探索",
    "Expeditions": "远征",
    "Hourly": "每小时",
    "Kills": "击杀",
    "Total": "总计",
    "Ore used:": "使用矿石：",
    "Cannon": "大炮",
    "cannon": "大炮",
    "found a pirate!!!": "发现了一个海盗！！",
    "found no pirates nearby.": "附近没有海盗。",
    "turret": "炮塔",
    "All Types": "全部类型",
    "Allocate Additional Resources": "增加额外资源",
    "Digger": "挖掘机",
    "Drill": "钻机",
    "Extractor": "萃取器",
    "Increasing resource allocation improves the chance of high tier module rolls.": "增加资源分配可以提高高级模块出现的几率。",
    "Increasing resource allocation improves the chance of high tier tool rolls.": "增加资源分配可以提高高级工具出现的几率。",
    "Laser": "激光",
    "Miscellaneous": "杂项",
    "One worker must be available to start a craft": "必须有一个工人可以开始一项制作",
    "Select Aetherium": "选择光晶",
    "Select Rarity": "选择稀有度",
    "Select Level": "选择等级",
    "Select Tool Type": "选择工具类型",
    "Select Module Type": "选择模块类型",
    "You do not have enough Iron Bar for this": "你没有足够的铁锭",
    "Turret": "炮塔",
    "Your fleet and crew has now stopped fighting pirates": "你的舰队和船员现在已经停止和海盗战斗了",
    "Accuracy:": "精准度：",
    "Additional Modifiers": "附加词缀",
    "Armour:": "护甲：",
    "Build Ship": "建造船",
    "Cannons": "大炮",
    "Copied to clipboard": "复制到剪贴板",
    "Default tool type": "默认工具类型",
    "Equipables are your crew and modules placed on the ship. Using more equipables increases production costs as well as the ongoing maintenance of fuel/minute and durability repairing": "装备是你的船员和放置在船上的模块。使用更多的装备会增加生产成本，以及持续的燃料/分钟维护和耐久度修复",
    "Health Regen:": "生命回复：",
    "Health:": "健康:",
    "Hull Level": "船体等级",
    "Increase Drop Rarity (%)": "增加掉落稀有度（%）",
    "Increases the amount of random modifiers and base hull level": "增加随机词缀和基础船体等级",
    "Increases the drop rarity chance, improving the weightings on tier rolls.": "增加掉落的稀有几率，提高层级掷出的权重。",
    "Laser Damage:": "激光伤害：",
    "Lasers": "激光",
    "Log out of session": "退出会话",
    "Movement Speed:": "移动速度:",
    "Put in inventory": "放入库存",
    "Reset inputs": "重置输入",
    "Select Fleet": "选择舰队",
    "Shields:": "护盾：",
    "Ship Name": "飞船名称",
    "The overview shows the worst possible rolls, if everything rolls T12": "概览显示了最坏的可能的掷出结果，如果所有掷出T12",
    "Turrets": "炮塔",
    "You need to equip at least one equipable": "你需要装备至少一件装备",
    "Your ship has been built": "你的飞船已经完成建造",
    "You do not have enough resources to build this ship": "你没有足够的资源来建造这艘船",
    "New Ship": "新飞船",
    "Drop rarity increases the weightings on tier rolls.": "掉落稀有度增加了层级投掷的权重。",
    "New module": "新模块",
    "Workers:": "工人:",
    "a nimbused extractor": "一个灵动萃取器",
    "a scary laser": "一个可怕的激光",
    "Cannon Damage:": "大炮伤害:",
    "Cannons have a base attack speed of 8s, and have the ability to AoE attack.": "大炮的基础攻击速度为8秒，并具有AoE（范围攻击效果）攻击能力。",
    "Copy crafting inputs": "复制制作输入",
    "Drilling Amount:": "钻探数量:",
    "Mining Amount:": "采矿数量:",
    "Harvesting Amount:": "收割数量:",
    "Increases the damage dealt by laser weapons by a percentage.": "使激光武器造成的伤害增加一定百分比。",
    "Iron Amount": "铁数量",
    "No old items.": "没有旧物品。",
    "Show Output": "显示输出",
    "Turret Damage:": "炮塔伤害:",
    "Turrets have a base attack speed of 6s, and have the ability to shoot twice": "炮塔的基础攻击速度为6秒，并且可以射击两次",
    "Your active ships are at capacity": "你活跃的飞船已达上限",
    "A fleet without ships cannot do an activity": "没有船只的舰队是不能活动的",
    "Instant": "瞬间",
    "Invalid activity_level": "无效的 activity_level",
    "Ion Damage": "离子伤害",
    "Laser Resistance": "激光抗性",
    "Lavona Scronce": "",
    "Owned by:": "所有者：",
    "A fleet without ships cannot do an activity": "没有船的舰队不能进行任何活动",
    "Alton Retzlaff": "奥尔顿·瑞兹拉夫",
    "An Loa": "安洛安",
    "Anglea Tzeng": "曾安琪",
    "Are you sure you want to unequip  all from 采矿1?": "你确定要从采矿1全部解除装备吗？",
    "Astral Force Knights": "星力骑士",
    "Belva Blew": "贝尔瓦·布鲁",
    "Burton Maylone": "伯顿·梅隆",
    "Cannon Explosion Size": "大炮爆炸范围",
    "Cannon Resistance Penetration": "大炮抗性穿透",
    "Carola Froehlich": "卡罗拉·弗洛里奇",
    "Debbi Ruck": "黛比·拉克",
    "Decreases the fuel consumption during travel.": "减少旅行燃料消耗。",
    "Drop Rarity Multiplier": "掉落稀有度乘数",
    "Emp Avoidance": "电磁脉冲躲避",
    "Energy Distortion Reduction": "减少能量扭曲",
    "Forest Saluan": "森林萨鲁安",
    "Fuel Efficiency": "燃料效率",
    "Ignition Duration Boost": "点燃持续时间增加",
    "Increases damage dealt to shields by a percentage.": "以一定百分比增加对护盾造成的伤害。",
    "Increases the ability to penetrate cannon resistance.": "增加大炮穿透防御的能力。",
    "Increases the ability to penetrate turret resistance.": "增加炮塔穿透防御的能力。",
    "Increases the amount of resources gathered while drilling by a percentage.": "增加钻探时收集的资源的百分比。",
    "Increases the amount of resources gathered while harvesting by a percentage.": "以一定百分比增加收获时收集的资源数量。",
    "Increases the chances of finding rare items as drops.": "增加掉落稀有物品的几率。",
    "Increases the damage dealt by turrets by a percentage.": "以一定百分比增加炮塔的伤害。",
    "Increases the duration of ignition effects on the target.": "增加对目标的点燃效果的持续时间。",
    "Increases the duration of invulnerability after shield destruction.": "增加护盾被摧毁后的无敌持续时间。",
    "Increases the size of cannon explosions, affecting a larger area.": "增加大炮爆炸的范围，影响更大的区域。",
    "Raguel Spane": "拉盖尔·斯班",
    "Raymundo Dedeke": "雷蒙多·德德克",
    "Reduces the chance of being affected by EMP attacks.": "减少被电磁脉冲攻击影响的几率。",
    "Reduces the damage taken from laser attacks.": "减少受到激光攻击的伤害。",
    "Reduces the damage taken from turret attacks.": "减少炮塔攻击造成的伤害。",
    "Reduces the impact of energy distortion effects that slow down attack speed.": "减少降低攻击速度的能量扭曲效果的影响。",
    "Shield Destruction Invulnerability Duration": "护盾破坏无敌持续时间",
    "Starting Ship is no longer in a fleet": "起始船已不在舰队中",
    "The tool is already equipped to this ship": "这个工具已经装备在这艘船上了",
    "Tiny Bremme": "小布雷姆",
    "Turret Damage": "炮塔伤害",
    "Turret Resistance": "炮塔抗性",
    "Turret Resistance Penetration": "炮塔抗性穿透",
    "Valene Shekels": "瓦伦·谢克尔",
    "Vi Chough": "维·乔",
    "Wally Waldrope": "沃利·沃尔德罗普",
    "Wilburn Frock": "威尔连衣裙",
    "Lucky Dice Efficiency": "幸运骰子效率",
    "My Equipment": "我的装备",
    "Abraham Gauci": "亚伯拉罕·高齐",
    "an earthen and battered module": "一个土制的破旧模块",
    "Boosts the damage of lasers based on their charge duration.": "根据激光的持续时间增加激光的伤害。",
    "Decreases the durability loss from combat.": "减少战斗造成的耐久损失。",
    "Denny Peloso": "丹尼·佩洛索",
    "Durability Efficiency": "耐久效率",
    "Franchesca Schwinn": "弗兰切斯卡·施文",
    "Hobert Ohlmacher": "霍伯特·欧马赫",
    "Ignition": "点燃",
    "Increases the efficiency of lucky dice modifiers applied to this ship": "提高幸运骰子词缀效率应用到这艘船",
    "Laser Charge Boost": "激光充能加成",
    "Leonard Draine": "伦纳德·德雷恩",
    "Logan Brownell": "洛根·布朗内尔",
    "Palmira Lambuth": "帕尔米拉·兰布斯",
    "Shaina Rosario": "谢娜·罗萨里奥",
    "The percentage of damage dealt over time when the target is ignited.": "当目标被点燃时，在一段时间内造成的伤害百分比。",
    "You do not have enough Adamantite Bar for this": "你没有足够的金钢锭来做这个",
    "Your Academy has been upgraded": "你的学院已经升级了",
    "Please click here to refresh": "请点击这里刷新",
    "A new version is available.": "有一个新版本可用。",
    "A fleet cannot be deleted while containing ships": "舰队中有船只时不能被删除",
    "a shaven Gravity Boots": "剃光的重力靴",
    "Add Stat": "添加属性",
    "Are you sure you want to remove New Ship from its fleet?": "你确定要把新船从舰队中移除吗？",
    "Assists in successful expeditions.": "协助远征成功",
    "Boosts efficiency at the farm.": "提升农场效率",
    "Chance Generate Infused Wheat": "有概率生成灌注小麦",
    "Chance to generate infused wheat during farming.": "耕种有概率产出灌注小麦",
    "Enhances efficiency for ships.": "提升舰船效率",
    "Equipment": "装备",
    "Equipment Overview": "装备概述",
    "Gravity Boots": "重力靴",
    "Level 4 gravity boots equipment": "四级重力靴装备",
    "Lucky Charm": "幸运符",
    "Lucky Dice": "幸运骰子",
    "Magnetic Gloves": "磁性手套",
    "Navigation Scanner": "导航扫描仪",
    "Nothing equipped": "暂无装备",
    "Optimizes processes in the refinery.": "优化精炼厂的流程。",
    "Oxygen Tank": "氧气罐",
    "Provides boosts for academy operations.": "为学院运营提供助力。",
    "Provides galaxy wide performance.": "提供银河系范围的性能。",
    "Remove Stat": "移除属性",
    "Space Helmet": "太空头盔",
    "Space Suit": "太空服",
    "Supports productivity in the forger.": "支持锻造厂的生产效率。",
    "Upgrade Stat": "升级属性",
    "Cancel Adding": "取消添加",
    "Cancel Removing": "取消移除",
    "Cancel Upgrading": "取消升级",
    "Select a stat": "选择一个属性",
    "You do not own this": "您未拥有该物品",
    "Unlock (prevents destroying)": "解锁（防止破坏）",
    "Here you can set a personal tax value between 0 and 100. The % of currency earned will automatically be donated to your alliance. Be aware that the highest number between your personal value, and the tax value of your current alliance role will be used.": "在这里，您可以在0到100之间设置个人税额。所赚取的货币百分比将自动捐赠给您的联盟。请注意，您的个人价值和您当前联盟角色的税收价值之间的最高数字将被使用。",
    "Hide": "隐藏",
    "Test": "测试",
    "Link": "链接",
    "Import Theme": "导入主题",
    "Here you can add a link to a soundfile and adjust the volume between 0 and 100. The soundfile must be in a valid MP4 or WAV format. The default sound file is: https://spacelar.queslar.com/assets/sounds/bell.mp3": "在这里你可以添加到声音文件的链接，并在0到100之间调节音量。声音文件必须是有效的MP4或WAV格式。默认声音文件为：https://spacelar.queslar.com/assets/sounds/bell.mp3",
    "Enable": "启用",
    "Volume": "音量",
    "Sound Settings": "声音设置",
    "Premium Store": "会员商店",
    "Tier Color Settings": "层级颜色设置",
    "Timezone display": "时区显示",
    "Travel Completion": "旅行完成",
    "All Filters": "所有过滤器",
    "Coming soon :)": "敬请期待：)",
    "Crafting Completion": "制作完成",
    "Create New Theme": "创建新主题",
    "Currency Color Settings": "货币颜色设置",
    "Current Active Filters": "当前活跃过滤器",
    "Default filter": "默认过滤器",
    "Default sound": "默认声音",
    "Delete theme": "删除主题",
    "Display auctions in trade": "展示交易中的拍卖",
    "Expedition Completion": "出征完成",
    "Galaxy Map Color Settings": "星系地图颜色设置",
    "Here you can customize the amount of upgrades you can do at once when holding down various keys such as CTRL or SHIFT. Your UI displays will update accordingly": "在这里，你可以自定义你可以在按住CTRL或SHIFT等不同键时一次性完成的升级数量。您的UI显示将相应地更新",
    "Here you can customize your bottom left navigation menu with additional quick buttons to specific content, split the UI into 2 columns and change the order of buttons": "在这里，你可以用额外的快速按钮来定制左下角的导航菜单，将UI分成两列，并更改按钮的顺序",
    "Here you can toggle displayed statistics to be shown in the top left \"Stats\" menu": "在这里，您可以切换显示的统计数据，显示在左上角的“统计”菜单中",
    "Here you can toggle on various sound notifications when they occur, and make them use use your inputted files from the \"Sound Settings\" menu.": "在这里，你可以切换各种声音通知时，他们发生，并使他们使用使用您输入的文件从“声音设置”菜单。",
    "Here you can toggle whether or not you wish to receive a confirmation popup on specific clicks/actions to prevent accidental clicks": "在这里，你可以切换是否希望收到一个确认弹出在特定的点击/操作，以防止意外点击",
    "My Expeditions": "我的征途",
    "Navigation Columns": "导航栏",
    "Navigation Options": "导航选项",
    "Navigation Views": "导航视图",
    "Notification Settings": "通知设置",
    "Rarity Color Settings": "稀有颜色设置",
    "Select a template": "选择模板",
    "Settings impacting various displays in your chat window": "影响聊天窗口中各种显示的设置",
    "Theme Color Settings": "主题颜色设置",
    "These are general theme colors used throughout the game impacting backgrounds, names and general text": "这些是游戏中使用的影响背景、名称和一般文本的一般主题颜色",
    "These are the colors used for items with rarities. Most general item types have a rarity modules and crew.": "这些是稀有物品的颜色。大多数一般的道具类型都有稀有模块和船员。",
    "These are the colors used for showing your currencies. These are used at any point throughout the game where the currency is mentioned.": "这些是用来显示货币的颜色。在游戏中提到货币的任何时刻都可以使用这些工具。",
    "These are the colors used stats with tiers, such as stat rolls on equipment, crew or modules.": "这些是不同等级使用的属性颜色，比如装备、乘员或模块的属性滚动。",
    "These are the main color settings used inside the galaxy screen": "这些是银河屏幕内部使用的主要颜色设置",
    "Various miscellaneous settings that has minor display inpacts on your UI.": "各种各样的设置对UI的显示影响很小。",
    "0.36% chance to multiply food as Iron Bar": "0.36%概率将食物倍增为铁条",
    "Academy Costs": "学院成本",
    "Additional Defensive Modules": "额外防御模块",
    "Additional Workers": "额外的工人",
    "Buy +1 max nodes": "购买节点上限+1",
    "Cannon Damage": "大炮伤害",
    "Cannon Speed": "大炮速度",
    "Chance Additional Item": "几率额外物品",
    "Chance Higher Module": "几率更高模块",
    "Chance Instant Craft": "几率瞬间制造",
    "Chance Multiply Bar As Adamantite": "几率将金属锭乘以金刚石",
    "Chance Multiply Bar As Gold": "几率将金属锭乘以黄金",
    "Chance Multiply Bar As Iron": "几率将金属锭乘以铁",
    "Chance Multiply Bar As Platinum": "几率将金属锭乘以铂金",
    "Chance Multiply Bar As Titanium": "几率将金属锭乘以钛",
    "Chance No Aetherium": "几率没光晶",
    "Chance to craft a module 1 level higher than selected.": "有几率制造一个比选择的高1级的模块。",
    "Chance to craft an additional item.": "有几率制作一个额外的物品。",
    "Chance to forge without using any aetherium.": "有几率在不使用光晶的情况下锻造。",
    "Chance to instantly forge an item.": "有几率立即锻造一件物品。",
    "Chance to multiply bar as adamantite.": "几率将金属锭乘以金刚石。",
    "Chance to multiply bar as gold.": "几率将金属锭乘以黄金。",
    "Chance to multiply bar as iron.": "几率将金属锭乘以铁。",
    "Chance to multiply bar as platinum.": "几率将金属锭乘以铂金。",
    "Chance to multiply bar as titanium.": "几率将金属锭乘以钛。",
    "Crew Drop Rarity": "船员掉落稀有度",
    "Crew Rarity": "船员稀有度",
    "Damage Reduction": "伤害减免",
    "Decreased Farm Upkeep Costs": "减少农场维护成本",
    "Decreased Refinery Upkeep Costs": "减少精炼厂维护成本",
    "Decreases the cost of academy upgrades.": "降低学院升级的成本。",
    "Decreases the cost of forging items.": "降低锻造物品的成本。",
    "Decreases the time required for forging items.": "减少锻造物品所需的时间。",
    "Decreases upkeep costs for the farm.": "减少农场的维护成本。",
    "Decreases upkeep costs in the refinery.": "降低精炼厂的维护成本。",
    "Do you want to increase your max amount of skill points by 1 ?": "你想把你的技能点数上限提高1点吗？",
    "Effective Refinery Level": "有效精炼厂等级",
    "Farm Efficiency": "农场效率",
    "Forging Costs": "锻造成本",
    "Forging Time": "锻造时间",
    "Galactic Overlord": "银河领主",
    "Gives a chance to temporarily increase attack speed.": "有一定几率暂时提高攻击速度。",
    "Ignition Avoidance": "避免点燃",
    "Increases": "增加",
    "Increases farm efficiency.": "提高农场效率。",
    "Increases flat damage dealt to shields.": "增加对护盾的伤害。",
    "Increases the amount of damage you block from incoming attacks": "提高自身抵挡攻击的伤害",
    "Increases the chance of detecting pirates during travel.": "增加在旅途中发现海盗的几率。",
    "Increases the damage dealt by cannons by a percentage.": "增加大炮造成的一定百分比伤害。",
    "Increases the effective bar output level of the refinery.": "增加精炼厂的有效金属锭产量。",
    "Increases the efficiency of offensive modules, improving their effectiveness.": "增加攻击模块的效率，提高他们的有效性。",
    "Increases the firing speed of cannons.": "增加大炮的射击速度。",
    "Increases the flat damage dealt by turrets.": "增加炮塔造成的平面伤害。",
    "Increases the flat damage of all attacks.": "增加所有攻击的伤害。",
    "Increases the likelihood of being targeted by enemies.": "增加被敌人攻击的可能性。",
    "Increases the max amount of pirates normal combat can contain at once": "增加普通战斗一次可以容纳的海盗的最大数量",
    "Increases the number of defensive modules that can be equipped.": "增加可以装备的防御模块的数量。",
    "Increases the number of rolls available in academy.": "增加学院的人数。",
    "Increases the number of workers available.": "增加可用工人的数量。",
    "Increases the percentage rate of health regeneration.": "增加生命回复的百分比。",
    "Increases the rarity of dropped crew during expeditions.": "增加远征时掉落船员的稀有度。",
    "Increases the rarity of recruited crew members.": "增加招募船员的稀有度。",
    "Increases the rarity of stat rolls in module forging": "增加模组锻造中掷出属性的稀有度",
    "Increases the ship’s movement speed.": "增加船的移动速度。",
    "Module Drop Rarity": "模块掉落稀有度",
    "No nodes allocated": "未分配节点",
    "Nodes allocated": "已分配节点数",
    "Offensive Module Efficiency": "进攻模块效率",
    "Pirate Detection Chance": "海盗发现几率",
    "Reduces the chance of being ignited by enemy attacks.": "减少被敌人攻击点燃的几率。",
    "Reduces the overall damage taken by a percentage.": "减少一定百分比的整体伤害。",
    "You can only assign nodes that are connected to previous unlocked nodes": "您只能分配连接到先前未锁定节点的节点",
    "You have reached the maximum number of points. Upgrade your research lab to unlock more points.": "你已经达到了最大点数。升级你的研究实验室解锁更多的点数。",
    "Your max amount of skill points has been increased by 1.": "你的最大技能点数增加了1。",
    "Overclock Chance": "超频几率",
    "Overview": "概述",
    "Pirate Max": "海盗上限",
    "Reset skill tree. For now this is free, but will later cost a droppable pirate currency :)": "重置技能树。目前这是免费的，但稍后将花费可掉落的海盗货币：)",
    "Rolls Per Academy": "每所学院的学生人数",
    "Starting Point": "起点",
    "Targeting Preference": "目标偏好",
    "The research lab offers multiplicative boosts to various modifiers": "该研究实验室为各种词缀提供了成倍的提升",
    "5% Mining Rarity Multiplier": "5% 采矿稀有度乘数",
    "Ship Mining": "飞船采矿",
    "You have already assigned the maximum amount of skill points. Upgrade your research lab to assign more skill points.": "你已经分配了最大数量的技能点。升级你的研究实验室来分配更多的技能点。",
    "You have assigned a skill point into Mining Rarity Multiplier.": "",
    "Buy": "购买",
    "Buy Orders": "购买订单",
    "Decreases the cost of academy rerolls.": "降低了重新学习的成本。",
    "Increases the rarity of stat rolls from crew": "增加船员属性滚动的稀有度",
    "My Orders": "我的订单",
    "No buy orders": "暂无购买订单",
    "No listings": "暂无上架订单",
    "No sell orders": "暂无出售订单",
    "Price": "价格",
    "Quantity": "数量",
    "Sell Orders": "出售订单",
    "Total:": "总计：",
    "a fleecy Magnetic Gloves": "羊毛磁性手套",
    "a fozy Oxygen Tank": "一个氧气罐",
    "a frosty Space Suit": "冰冷的太空服",
    "a frumpish Oxygen Tank": "破旧的氧气罐",
    "a hoggish Space Helmet": "一个笨重的太空头盔",
    "a largest Space Suit": "最大的太空服",
    "a pesky Magnetic Gloves": "讨厌的磁性手套",
    "a plucky Gravity Boots": "勇敢的万有引力靴子",
    "a wrier Gravity Boots": "作家重力靴",
    "an ingrain Magnetic Gloves": "磁性手套",
    "Auction": "拍卖",
    "Chance Multiply Bar As Uranium": "将Bar乘以铀",
    "Chance to forge a module 1 level higher than selected.": "有机会锻造一个比选择高1级的模块。",
    "Chance to multiply bar as uranium.": "有机会将bar乘以铀。",
    "Increases the rarity of stat rolls in tools forging": "增加工具锻造中属性卷的稀有性",
    "Level 14 space suit equipment": "14级太空服装备",
    "Level 18 magnetic gloves equipment": "18级磁性手套装备",
    "Level 24 space helmet equipment": "24级太空头盔装备",
    "Level 25 magnetic gloves equipment": "25级电磁手套装备",
    "Level 30 oxygen tank equipment": "30层氧气罐设备",
    "Level 31 gravity boots equipment": "31级重力靴装备",
    "Level 31 magnetic gloves equipment": "31级电磁手套装备",
    "Level 31 oxygen tank equipment": "31层氧气罐设备",
    "Level 31 space suit equipment": "31级太空服装备",
    "Mine": "采矿",
    "Tool Drop Rarity": "工具掉落稀有度",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Marshall Tukuafa": "Marshall Tukuafa",
    "Mario Retterath": "Mario Retterath",
    "Malka Bost": "马尔卡·博斯特",
    "Malinda Vasta": "Malinda Vasta",
    "Lavona Scronce": "拉沃娜·斯克鲁丝",
    "for": "造成",
    "Major Paley": "佩利少校",
    "Flavia Dedicke": "弗蕾维亚·肯迪克",
    "Emeline Colder": "埃米琳·科尔",
    "Adam Deconti": "亚当·德康提",

    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "API": "API",
    "CN": "CN",
    "NSFW": "NSFW",
    "restore": "restore",
    "attacks": "攻击",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    "Gityx": "Gityx",
    "Gz": "Gz",
    "O": "O",
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Upgrade x": "升级 x",
    "Build x": "建造 x",
    "Move fleets to ": "移动舰队到 ",
    "Increases your travel speed to this planet by ": "提高你到这个星球的旅行速度 ",
    "Increases your mining multiplier on this planet by ": "提高你在这个星球的 采矿 乘数 ",
    "Increases your harvesting multiplier on this planet by ": "提高你在这个星球的 收割 乘数 ",
    "Increases your effectiveness of inhabitants on this planet by ": "提高你在这个星球的 居民效能 ",
    "Increases your fuel efficiency when travelling to this planet by ": "提高你旅行到这个星球的 燃料效率 ",
    "Increases the global planet inhabitants by ": "增加全局星球居民 ",
    "Increases the global maximum inhabitant capacity of this planet by ": "增加这个星球的全局居住容量上限 ",
    "Attack speed: ": "攻击速度: ",
    "Last seen: ": "最近在线: ",
    "Cerulium ": "铈",
    "Copper ": "铜",
    "Aetherium ": "光晶",
    "Neutronium ": "中子态",
    "Platinum ": "铂",
    "Titanium ": "钛",
    "Uranium ": "钛",
    "new fleet - ": "新舰队 - ",
    "Status: ": "状态: ",
    "Docked at ": "停靠在 ",
    "Adamantite ": "金刚石",
    "Obsidium ": "黑曜石 ",
    "Increases your gold multiplier on this planet by ": "增加你在这个星球上的黄金乘数 ",
    "health is now ": "当前生命值是 ",
    "shield is now ": "当前护盾是 ",
    "Wheat costs/hour: ": "小麦 成本/小时: ",
    "- Level ": "- 等级 ",
    "Completed: ": "完成: ",
    "Rarity: ": "稀有度: ",
    "Started: ": "开始于: ",
    "You have recruited ": "你招募了 ",
    "Theme ID: ": "主题ID: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " - Mining": " - 采矿",
    " - Pirates": " - 海盗",
    " - Idle": " - 空闲",
    " shield.": " 护盾.",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\[([\d\.]+)\]$/,
    /^([\d\.,]+) \- ([\d\.,]+) \[T([\d\.]+)\]$/,
    /^\[([\d\.]+):([\d\.]+)\]:$/,
    /^\[([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+)\]$/,
    /^\$([\d\.]+)$/,
    /^\-\> ([\d\.]+)x$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^等级(.+)$/,
    /^解锁(.+)$/,
    /^成本(.+)$/,
    /^(.+) \(([\d\.,]+), ([\d\.,]+), ([\d\.,]+)\)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+)\% \(\+([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)ms$/,
    /^\[T([\d\.,]+)\]$/,
    /^([\d\.,]+) \/$/,
    /^\(([\d\.,]+)\)$/,
    /^([\d\.,]+) \(\+([\d\.,]+)\)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have gained (.+)  Gold$/, '你得到了 $1 黄金'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You have renamed (.+)$/, '你已经重新命名了 $1'],
    [/^Do you wish to transfer (.+)$/, '你是否想转移 $1'],
    [/^(.+) has been moved to (.+)$/, '$1 已经转移到 $2'],
    [/^You have assigned a skill point into (.+).$/, '你已经为 $1 分配了一个技能点。'],
    [/^Do you want to assign a skill point into (.+)\?$/, '你想给 $1 分配一个技能点吗？'],
    [/^Do you wish to rename a (.+) digger. Input a new tool name$/, '是否要重新命名一个 $1 挖掘机？请输入新的工具名称'],
    [/^Do you wish to rename (.+). Input a new ship name$/, '是否要重新命名 $1？请输入新的飞船名称'],
    [/^Do you wish to equip a cadent extractor to (.+)$/, '你想在 $1 上装备一个有节奏的萃取器吗'],
    [/^Do you wish to move (.+) to (.+)$/, '你想把 $1 移到 $2 吗'],
    [/^Estimated: (.+) minutes remaining$/, '预计剩余: $1 分钟'],
    [/^You have started crafting a unique level (.+) misc module. (.+) worker has been assigned.$/, '你已经开始制作一个独特的 $1 级杂项模块。已分配 $2 名工人。'],
    [/^Do you want to build (.+)\? A laser tool ship with (.+) crew slots, (.+) offensive, (.+) defensive, and (.+) misc modules\?$/, '你想建造 $1 吗？一艘激光工具船，有 $2 船员插槽，$3 个进攻模块，$4 个防御模块和 $5 个杂项模块？'],
    [/^Do you want to build (.+)\? A extractor tool ship with (.+) crew slots, (.+) offensive, (.+) defensive, and (.+) misc modules\?$/, '你想建造 $1 吗？一艘萃取器工具船，有 $2 船员插槽，$3 个进攻模块，$4 个防御模块和 $5 个杂项模块？'],
    [/^Do you want to craft a unique level (.+) offensive module?$/, '你想制作一个独特的 $1 级攻击模块吗？'],
    [/^Do you wish to wire Copper Ore to another player\? You must pay a (.+) trading tax$/, '你想把铜矿石发送给另一个玩家吗？您必须交纳 $1 的交易税'],
    [/^Are you sure you want to remove (.+) from its fleet\?$/, '你确定要从它的舰队中移除 $1 吗？'],
    [/^takes (.+) ion damage to shields. Current$/, '护盾受到 $1 离子伤害。当前'],
    [/^regenerates (.+) health. Current$/, '回复 $1 生命值。当前'],
    [/^Do you wish to equip (.+)\?.$/, '您是否要装备 $1？'],
    [/^Do you wish to rename (.+). Input a new equipment name$/, '您是否希望重命名 $1。输入新的装备名称'],
    [/^(.+) is no longer in a fleet$/, '$1 已不在舰队中了'],
    [/^(.+) has been deleted$/, '$1 已删除'],
    [/^(.+) has been unequipped from Starting Ship$/, '$1 已从初始飞船上卸下'],
    [/^Do you wish to rename (.+). Input a new fleet name$/, '您希望重新命名 $1 吗？请输入一个新的舰队名称'],
    [/^attack (.+) Ship \- ([\d\.,]+) for$/, '攻击 $1 飞船 - $2 造成'],
    [/^attacks (.+) Ship \- ([\d\.,]+) for$/, '攻击 $1 飞船 - $2 造成'],
    [/^(.+) Ship \- ([\d\.,]+)$/, '$1 飞船 - $2'],
    [/^(.+) Ship \- ([\d\.,]+) attacks$/, '$1 飞船 - $2 攻击'],
    [/^(.+) Ship \- ([\d\.,]+) missed the attack on$/, '$1 飞船 - $2 未命中'],
    [/^(.+) Ship \- ([\d\.,]+) regenerates (.+) health. Current$/, '$1 飞船 - $2 恢复 $2 生命值。当前'],
    [/^(.+) Ship \- ([\d\.,]+) takes (.+) ion damage to shields. Current$/, '$1 飞船 - $2 恢复 $2 护盾受到 $3 离子伤害。当前'],
    [/^Do you want (.+) to stop\?$/, '你想让 $1 停下来吗？'],
    [/^Do you wish to equip (.+) to (.+)$/, '你想把 $1 装备到 $2 上吗'],
    [/^Do you wish to unequip (.+) from (.+)$/, '你想从 $2 卸下 $1 吗'],
    [/^Do you wish to unequip (.+) to (.+)$/, '你想把 $2 从 $1 卸下吗'],
    [/^Are you sure you want to unequip all tools from (.+)\?$/, '你确定要从 $1 中移除所有工具吗？'],
    [/^(.+) from refinery\n    (.+) from farm\n    (.+) from forger\n    (.+) from additional worker modifiers$/, '$1 来自精炼厂\n $2来自农场\n $3来自锻造厂\n $4来自额外的工人词缀'],
    [/^Are you sure you want to upgrade your Hydroponic Farm from level ([\d\.,]+) to ([\d\.,]+)$/, '你确定要把你的 水培农场 从 $1 级升级到 $2级吗'],
    [/^Are you sure you want to upgrade your Habitat Dome from level ([\d\.,]+) to ([\d\.,]+)$/, '你确定要把你的 栖息地圆顶 从 $1 级升级到 $2级吗'],
    [/^Are you sure you want to upgrade your Bar from level ([\d\.,]+) to ([\d\.,]+)$/, '你确定要把你的 金属锭 从 $1 级升级到 $2级吗'],
    [/^Are you sure you want to upgrade your Spaceport from level ([\d\.,]+) to ([\d\.,]+)$/, '你确定要把你的 太空港 从 $1 级升级到 $2级吗'],
    [/^Are you sure you want to upgrade your Purification Plant from level ([\d\.,]+) to ([\d\.,]+)$/, '你确定要把你的 净化厂 从 $1 级升级到 $2级吗'],
    [/^Are you sure you want to upgrade your Smugglers Stash from level ([\d\.,]+) to ([\d\.,]+)$/, '你确定要把你的 走私者藏匿处 从 $1 级升级到 $2级吗'],
    [/^Are you sure you want to upgrade your EcoDrive Complex from level ([\d\.,]+) to ([\d\.,]+)$/, '你确定要把你的 生态驱动综合体 从 $1 级升级到 $2级吗'],
    [/^Are you sure you want to upgrade your Excavator from level ([\d\.,]+) to ([\d\.,]+)$/, '你确定要把你的 挖掘机 从 $1 级升级到 $2级吗'],
    [/^Do you want to move new fleet from (.+) to (.+)\?$/, '您是否希望将新舰队从 $1 移动到 $2\?'],
    [/^Do you want to move (.+) from (.+) to (.+)\?$/, '您是否希望将 $1 从 $2 移动到 $3\?'],
    [/^Do you want to assign (.+) to mining\?$/, '您是否想分配 $1 去采矿\?'],
    [/^Do you want to assign (.+) to pirates\?$/, '您是否想分配 $1 去打海盗\?'],
    [/^Do you want upgrade Farm from level (.+) to level (.+)\?$/, '您是否想要升级 农场 从等级 $1 到等级 $2\?'],
    [/^Do you want upgrade Academy from level (.+) to level (.+)\?$/, '您是否想要升级 学院 从等级 $1 到等级 $2\?'],
    [/^Do you want upgrade Shipyard from level (.+) to level (.+)\?$/, '您是否想要升级 船厂 从等级 $1 到等级 $2\?'],
    [/^Do you want upgrade Forger from level (.+) to level (.+)\?$/, '您是否想要升级 锻造厂 从等级 $1 到等级 $2\?'],
    [/^Do you want upgrade Refinery from level (.+) to level (.+)\?$/, '您是否想要升级 精炼厂 从等级 $1 到等级 $2\?'],
    [/^Do you want upgrade Main Hub from level (.+) to level (.+)\?$/, '您是否想要升级 主枢纽 从等级 $1 到等级 $2\?'],
    [/^Do you wish to delete (.+)$/, '你是否要删除 $1'],
    [/^\+(.+) equipment effect (.+)$/, '+$1 装备效果 $2'],
    [/^\+(.+) max size fleet (.+)$/, '+$1 舰队规模上限 $2'],
    [/^\+(.+) max ship equipables (.+)$/, '+$1 可装备飞船上限 $2'],
    [/^\+(.+) max unlockable skill nodes (.+)$/, '+$1 可解锁技能节点上限 $2'],
    [/^\+(.+) max selectable module level (.+)$/, '+$1 可选模块等级上限 $2'],
    [/^\+(.+) max selectable crew level (.+)$/, '+$1 可选船员等级上限 $2'],
    [/^\+(.+) max level of all buildings\* (.+)$/, '+$1 所有建筑上限 $2'],
    [/^\+(.+) max active\/queued expeditions (.+)$/, '+$1 活跃/排队探险上限 $2'],
    [/^\+(.+) max active ships (.+)$/, '+$1 活跃飞船上限 $2'],
    [/^\+(.+) progress hour\/worker (.+)$/, '+$1 进度 小时/工人 $2'],
    [/^\+(.+) bars hour\/worker (.+)$/, '+$1 金属锭 小时/工人 $2'],
    [/^\+(.+) food hour\/worker (.+)$/, '+$1 食物 小时/工人 $2'],
    [/^\+(.+) food upkeep hour\/worker (.+)$/, '+$1 食物消耗 小时/工人 $2'],
    [/^\+(.+) gold upkeep hour\/worker (.+)$/, '+$1 黄金消耗 小时/工人 $2'],
    [/^\+(.+) worker (.+)$/, '+$1 工人 $2'],
    [/^\+(.+) alliance effects (.+)$/, '+$1 联盟效果 $2'],
    [/^\+(.+) equipment effects (.+)$/, '+$1 装备效果 $2'],
    [/^\+(.+) Additional Random Modifiers$/, '+$1 附加随机词缀'],
    [/^\+(.+) Drop Rarity$/, '+$1 掉率'],
    [/^\+(.+) Mining multiplier on planet$/, '+$1 星球上的采矿乘数'],
    [/^\+(.+) Harvesting multiplier on planet$/, '+$1 星球上的收割乘数'],
    [/^\+(.+) Gold multiplier on planet$/, '+$1 星球上的黄金乘数'],
    [/^\+(.+) from ship hangar$/, '+$1 从飞船机库'],
    [/^\-(.+) trading taxes (.+)$/, '-$1 交易税 $2'],
    [/^(.+) fuel\/minute$/, '$1 燃料/分钟'],
    [/^all has been unequipped from (.+)$/, '已经从 $1 全部卸下'],
    [/^(.+) has been unequipped from (.+)$/, '$1 已经被从 $2 卸下'],
    [/^(.+) has been unlocked$/, '$1 已解锁'],
    [/^(.+) has been locked$/, '$1 已锁定'],
    [/^(.+) has been equipped$/, '$1 已装备'],
    [/^(.+) has been equipped to (.+)$/, '$1 已经被装备到 $2'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/([\d\.,]+) workers$/, '$1\/$2 工人'],
	[/^([\d\.,]+) \/ ([\d\.,]+) Inhabitants$/, '$1 \/ $2 居民'],
	[/^([\d\.,]+) \/ ([\d\.,]+) durability$/, '$1 \/ $2 耐久'],
	[/^([\d\.,]+) \/ ([\d\.,]+) equipables used$/, '$1 \/ $2 可装备已使用'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Time \(([\d\.]+) worker\): ([\d\.]+) minutes$/, '时间 ($1 工人): $2 分钟'],
    [/^([\d\.]+)x repair cost$/, '$1x 修理成本'],
    [/^([\d\.,]+) \/h$/, '$1 \/小时'],
    [/^\-([\d\.,]+) \/h$/, '\-$1 \/小时'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Players Online$/, '$1 玩家在线'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) gold$/, '$1 黄金'],
    [/^([\d\.,]+) damage$/, '$1 伤害'],
    [/^([\d\.,]+) ship spots remaining$/, '剩余 $1 船位'],
    [/^Forger \(([\d\.,]+) workers\) \-$/, '锻造厂 ($1 工人) -'],
    [/^Farm \(([\d\.,]+) workers\) \-$/, '农场 ($1 工人) -'],
    [/^([\d\.,]+) in fleet (.+)\n      ([\d\.,]+) in fleet (.+)$/, '$1 在舰队 $2\n      $3 在舰队 $4'],
    [/^([\d\.,]+) in fleet (.+)$/, '$1 在舰队 $2'],
    [/^([\d\.,]+) max level crew member$/, '$1 最高等级船员'],
    [/^([\d\.,]+) assigned to refinery\n    ([\d\.,]+) assigned to farm\n    ([\d\.,]+) assigned to forger$/, '$1 分配到精炼厂\n    $2 分配到农场\n    $3分配到锻造厂'],
    [/^Unlocks at Main Hub Level ([\d\.,]+)$/, '解锁于主枢纽等级 $1'],
    [/^Level ([\d\.,]+) misc module$/, '$1 级 杂项 模块'],
    [/^Level ([\d\.,]+) laser tool$/, '$1 级 激光 工具'],
    [/^Level ([\d\.,]+) drill tool$/, '$1 级 钻探 工具'],
    [/^Level ([\d\.,]+) extractor tool$/, '$1 级 萃取器 工具'],
    [/^Level ([\d\.,]+) digger tool$/, '$1 级 挖掘机 工具'],
    [/^You can only refresh your crew up to level ([\d\.,]+)$/, '你目前能刷新出的最大船员等级为 $1'],
    [/^Level ([\d\.,]+) crew$/, '$1 级 船员'],
    [/^Level ([\d\.,]+) effective farm$/, '$1 级 农场 效率'],
    [/^Level ([\d\.,]+) effective refinery$/, '$1 级 精炼厂 效率'],
    [/^Do you want to craft a unique level ([\d\.,]+) misc module\?$/, '你想制作一个独特的 $1 级杂项模块吗？'],
    [/^Do you want to craft a unique level ([\d\.,]+) offensive module\?$/, '你想制作一个独特的 $1 级攻击模块吗？'],
    [/^Refinery \(([\d\.,]+) workers\) -$/, '精炼厂 ($1 工人) \-'],
    [/^Hull Level ([\d\.,]+)$/, '船体等级 $1'],
    [/^Crew Slot ([\d\.,]+)$/, '船员槽位 $1'],
    [/^Column ([\d\.,]+)$/, '列 $1'],
    [/^level ([\d\.,]+)$/, '等级 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Unique level ([\d\.,]+) misc module$/, '独特等级 $1 杂项模块'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();