// ==UserScript==
// @name         torn-chs
// @namespace    https://www.g8hh.com/
// @version      0.0.46
// @description  Torn（https://www.torn.com/）游戏汉化脚本 - 锅巴汉化出品
// @author       麦子、JAR、小蓝、好阳光的小锅巴
// @include      *https://www.torn.com/*
// @grant        none
// @website      https://www.gityx.com
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/torn-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/torn-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2023/02/24 17:52.
 * Author: guoba
 * View: http://www.gityx.com
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    "Save": "保存",
    "Export": "导出",
    "Import": "导入",
    "Milking": "挤奶",
    "Loading...": "加载中...",
    "Open user menu": "打开用户菜单",
    "Chat": "聊天",
    "Battle": "战斗",
    "Close": "关闭",
    "Dismiss": "解雇",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "        \n        \n        \n        Pay loan fees\n        ": "\n \n \n 支付贷款费用\n",
    "            \n            \n            \n            Before you can adjust your current loan of": "在您可以调整您当前的贷款之前",
    "you must pay the": "你必须支付",
    "Pay fees:": "支付费用：",
    "of your loan) every week\n": "你的贷款）每周\n",
    "in fees that are owed using the box below.\n            ": "所欠的费用使用下面的框。\n个",
    "Had enough yet? I can keep this up so long as yous got blood in your bones. Pay what you owe.": "吃饱了吗？ 只要你的骨头里还有血，我就能坚持下去。 支付你所欠的。",
    "Credit Card": "信用卡",
    "Casino Tokens": "堵场代币",
    "Gaining cash comes easy for some people. Crimes, Jobs, the Casino. Why not try your hand at making your own?": "对某些人来说，获得现金很容易。 犯罪、工作、赌场。 为什么不自己动手做呢？",
    "Bomb a Government Building": "炸毁正府大楼",
    "Bomb a Factory": "炸毁工厂",
    "Explosives": "炸药",
    "Feeling destructive? Certain people have a desire to see a building destroyed, are you up to the task?": "感觉具有破坏性？ 某些人希望看到建筑物被毁，您能胜任吗？",
    "Hack": "黑客",
    "Hack into a Bank Mainframe": "黑掉银行大型机",
    "Hack the F.B.I Mainframe": "黑掉 F.B.I 大型机",
    "Today everything is electronic. Lucky for you, this includes wire transfers. If you are looking for a lot of money you should try your hand at hacking!": "今天一切都是电子的。 幸运的是，这包括电汇。 如果你正在寻找很多钱，你应该试试黑客！",
    "Looking for a way to make some great money? Transport some arms for the local dealers!": "寻找赚大钱的方法？ 为当地经销商运输一些武器！",
    "Woman": "女人",
    "Undercover Cop": "警察卧底",
    "Mayor": "市长",
    "Looking for a rewarding challenge? Kidnapping is a risky business that is not for everyone. If you can manage to kidnap the target you will be highly rewarded.": "寻找有益的挑战？ 绑架是一项高风险的业务，并不适合所有人。 如果你能设法绑架目标，你将获得丰厚的回报。",
    "You will have enough nerve in ": "你会有足够的勇气在 ",
    "You need to wait for your nerve to increase before you can attempt this crime.": "你需要等到你的胆子大起来之后才能尝试这种犯罪。",
    "No one seems to be home so you break in.": "家里好像没人，所以你闯了进来。",
    "You see some valuable candle sticks so you decide to take them.": "你看到一些有价值的烛台，所以你决定拿走它们。",
    "Unfortunately there's a guard dog behind you. You slowly put down the candlesticks and jump out the window!": "不幸的是你身后有一只看门狗。 你慢慢放下烛台，跳出窗外！",
    "You walk along the street and see a mansion.": "你走在街上，看到一座豪宅。",
    "You walk down a busy street and look for a Lawyer to pickpocket from. They should have quite a bit of cash on them!": "你走在一条繁忙的街道上，想找一个律师来扒窃。 他们身上应该有不少现金！",
    "You see a man in an expensive suit buy a paper from a vendor. That's your target!": "你看到一个穿着昂贵西装的男人从供应商那里买一份报纸。 那是你的目标！",
    "A police officer saw what happened and chases after you. You panic and drop the briefcase and run out of the park before you are caught.": "一名警察看到发生了什么事并追赶你。 你惊慌失措，丢下公文包，在被抓到之前跑出了公园。",
    "Pick pocketing can be both easy and hard, it all depends on whom you steal from.": "扒窃既容易又困难，这完全取决于你从谁那里偷东西。",
    "You follow him until he gets to a quiet area in a park. You lean over to grab his briefcase from him.": "你跟着他，直到他到达公园的一个安静区域。 你俯身从他手里抢过他的公文包。",
    "Lawyer": "律师",
    "Businessman": "商人",
    "Kid": "儿童",
    "Hobo": "流浪汉",
    "Person": "目标人物",
    "Police:": "警察:",
    "My Faction": "我的帮会",
    "Old Woman": "老女人",
    "Make 10 hits within 5 minutes to start a chain": "5 分钟内命中 10 次即可开始连击",
    "Larceny basically means taking an item from someone which is their property. Below is a list of properties you can break into. Remember some properties will have better security so be careful!": "盗窃基本上意味着从某人那里拿走属于他们财产的物品。 以下是您可以闯入的属性列表。 请记住，某些属性会有更好的安全性，所以要小心！",
    "You notice there's a polished desk in the living room. Pretty nice to be honest, very expensive!": "你注意到客厅里有一张抛光的桌子。 老实说，非常好，非常昂贵！",
    "You break the back window as quietly as you can and sneak in to look around.": "你尽可能悄悄地打破后窗，偷偷溜进去四处看看。",
    "You walk along the street and see a small apartment.": "你走在街上，看到一间小公寓。",
    "The St Patrick's Day event has begun. All alcohol provides 2x nerve, and Green Stout may appear on your city map.": "圣帕特里克节活动已经开始。 所有的酒精都能提供 2 倍的勇气，而 绿色烈性黑啤酒 可能会出现在您的城市地图上。",
    "You didn't realize you made too big of a noise while breaking the back window and the cops were called. Just as the cops come round the corner, you leave the desk and make a run for it. Luckily you outrun them.": "你没有意识到你在打破后窗时发出的声音太大了，于是警察就被叫来了。 就在警察从拐角处过来时，你离开办公桌逃跑了。 幸运的是你跑得比他们快。",
    "Office": "办公室",
    "Mansion": "豪宅",
    "Detached House": "独立式住宅",
    "Apartment": "公寓",
    "Building": "建筑",
    "All alcohol items will provide twice the usual nerve until noon on the 18th while the St Patrick's event is active.": "直到 18 日中午，圣帕特里克节活动期间，所有酒类商品都会提供两倍于平时的勇气。",
    " Armed Robberies": "武装抢劫",
    "Chain": "连击",
    "Chain inactive": "连击无效",
    "You are going to need a coat hanger to pick the locks of the cars!": "您将需要一个衣架来撬开汽车的锁！",
    "To keep your Torn account protected, use a password that you haven't used on any other website. Click here to change your password!": "为保护您的 Torn 帐户，请使用您未在任何其他网站上使用过的密码。 单击此处更改您的密码！",
    "Stealing a car, aka Grand theft auto can be very dangerous but will hopefully get you a nice car to sell at the docks or collect in your garage. There are three ways you can steal a car... You could steal a parked car, just break the door open and you're off! Or maybe you want to skip the trouble of unlocking it, and hijack one! Or, the obviously much harder option would be to steal one from a car shop. Some of the most expensive cars can be found in the car shop, but the more expensive they get, the harder they are to unlock.": "偷车，又名侠盗猎车手，可能非常危险，但希望能为您带来一辆好车，以便在码头出售或在您的车库中收集。 您可以通过三种方式偷车...您可以偷一辆停着的车，只需打开车门就可以了！ 或者，也许您想跳过解锁它的麻烦，并劫持一个！ 或者，显然更难的选择是从汽车商店偷一辆。 一些最昂贵的汽车可以在汽车商店找到，但它们越贵，就越难解锁。",
    "Steal Car from Showroom": "从展厅偷车",
    "Steal a Parked Car": "偷一辆停着的车",
    "Don't forget to check the city map for a Bottle of Green Stout, because St Patrick's Day is now underway!": "不要忘记在城市地图上查看一瓶绿色烈性黑啤酒，因为圣帕特里克节现在正在进行中！",
    "George tutorials:": "乔治教程：",
    "General settings": "常规设置",
    "General Discussion": "常规讨论",
    "Friends & faction": "朋友 & 帮派",
    "Forum Signature": "论坛签名",
    "Forum signature": "论坛签名",
    "Faction Forum": "帮派论坛",
    "Faction Controls": "帮派控制",
    "Faction Armory": "帮派军械库",
    "Drag and drop areas between the two columns to customize sidebar links.": "拖放两列之间的区域以自定义侧边栏链接。",
    "Display this information in my profile": "在我的个人资料中显示此信息",
    "BEGIN SELF-EXCLUSION": "开始自我排除",
    "Are you sure you want to self-exclude yourself from the casino for": "您确定要将自己排除在堵场之外吗？",
    "This action cannot be reversed": "此操作无法撤消",
    "Travel Agency": "旅行社",
    "two factor authentication": "双重身份验证",
    "Unarmed": "徒手",
    "Unsubscribed": "取消订阅",
    "Use kick": "使用脚踢",
    "Use fists": "使用拳头",
    "Your Profile": "你的个人资料",
    "Would you like to change your gender?": "你想改变你的性别吗？",
    "Weapon Mods": "武器模组",
    "Tools": "工具",
    "Spin the Wheel": "旋转轮盘",
    "Flash & sound": "闪光 & 声音",
    "Flash notifier": "闪光通知",
    "Enabled": "Enabled",
    "Disabled": "Disabled",
    "Anyone can initiate chat with you": "任何人都可以发起与您的聊天",
    "Profile Tutorial": "个人资料教程",
    "Private Island": "私人岛屿",
    "Unranked": "未上榜",
    "UPDATE": "更新",
    "RANK:": "排名:",
    "Include your Battle Stats with your application": "在您的应用程序中包含您的战斗统计数据",
    "Provides a 3% passive bonus to crime EXP": "为犯罪经验提供 3% 的被动加成",
    "City Center": "城市中心",
    "City map": "城市地图",
    "City map tab": "城市地图标签",
    "Full territory view is currently enabled.": "目前已启用全域视图。",
    "Here you can view all of the locations available to you in Torn City. The number of places can be quite overwhelming at first, but you should be able to find your way around in no time. Feel free to visit the areas and nose around. As you go up levels, you will unlock new areas.": "在这里，您可以查看 Torn City 中所有可用的位置。 一开始，地方的数量可能会让人不知所措，但您应该很快就能找到自己的出路。 随意参观这些区域并四处张望。 随着级别的提高，您将解锁新的区域。",
    "Yes": "是",
    "No": "否",
    "report": "举报",
    "Are you sure you want to": "你确定要",
    "this room": "此房间",
    "Connecting to the server...": "正在连接到服务器...",
    "Ignoring Staff Warnings": "无视员工警告",
    "Compromising Security": "破坏安全",
    "Obscene Content": "淫秽内容",
    "Extreme Flaming": "极端燃烧",
    "Harassment": "骚扰",
    "Discrimination": "歧视",
    "SCRIPTING ABUSE:": "脚本滥用：",
    "MULTIPLE ACCOUNTS:": "多个帐户：",
    "business interruption;": "业务中断;",
    "BUG / EXPLOIT ABUSE:": "BUG/利用滥用：",
    "Acceptable Use Policy": "可接受的使用政策",
    "Acceptable use": "可接受的用途",
    "Access to information": "信息获取",
    "ACCOUNT SHARING:": "账号分享：",
    "ACCOUNT TRADING:": "账号交易：",
    "REAL MONEY TRADING:": "真实货币交易：",
    "PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING THIS SITE": "请在使用本网站前仔细阅读这些条款和条件",
    "PLEASE CAREFULLY READ TORN'S RULES AND ACCEPT THEM AT THE BOTTOM OF THE PAGE": "请仔细阅读 TORN 的规则并在页面底部接受它们",
    "Torn's bug bounty program": "Torn 的漏洞赏金计划",
    "Torn rules": "Torn 规则",
    "Torn Rules": "Torn 规则",
    "TORN'S GAME OFFENSES AND PUNISHMENTS": "TORN 的游戏违规行为和处罚",
    "You can always end your contract with us.": "您可以随时终止与我们的合同。",
    "Asking someone for their login information, phishing or scraping private information, or purposefully giving away your account details to anyone else.": "询问某人的登录信息、网络钓鱼或抓取私人信息，或故意将您的帐户详细信息泄露给其他任何人。",
    "Disregarding a request or warning made to you by a staff member via any medium to cease a particular action which may not specifically exist in these Social Guidelines.": "无视工作人员通过任何媒体向您提出的要求或警告，要求您停止本社会准则中可能没有具体规定的特定行为。",
    "Pornographic, sexually explicit or graphically violent material generally deemed unsuitable for minors in imagery or depicted in text. This includes bypassing filters with offensive language.": "色情、性暴露或图形暴力材料通常被认为不适合未成年人的图像或文字描述。 这包括使用冒犯性语言绕过过滤器。",
    "Unfiltered offensive profanity or severe slanderous name-calling taken offensively by the victim. For example, bypassing a swear filter or hateful insults with real-world connotations.": "未经过滤的冒犯性亵渎或严重的诽谤性辱骂被受害者冒犯。 例如，绕过脏话过滤器或带有现实世界内涵的仇恨侮辱。",
    "Causing the distress of a player while using the personal information or potential appearance of them, their family or their friends. This includes real-world threats and repeated verbal cyberbullying of which the victim is unable to avoid with the block / ignore features.": "在使用玩家、他们的家人或朋友的个人信息或潜在外表时造成玩家的困扰。 这包括现实世界的威胁和重复的口头网络欺凌，受害者无法通过阻止/忽略功能来避免这些威胁。",
    "Customer Data": "客户数据",
    "Hate speech and direct or indirect derogatory words / slurs regarding ethnic origin, religion, gender identity, sexual orientation, disability, misogyny or misandry. This includes any text, imagery or flags displayed in support of discrimination, real-world terrorism or Nazism.": "关于民族血统、宗教、性别认同、性取向、残疾、厌女症或厌女症的仇恨言论和直接或间接的贬损词/诽谤词。 这包括为支持歧视、现实世界的恐怖主义或纳粹主义而展示的任何文字、图像或旗帜。",
    "This list of social guidelines covers all of our rules for all user-created content (typed, shared or uploaded) across the entirety of Torn. This includes the forums, private messages, chat, discord, profiles, events, signatures, newspaper adverts and player names. When an offense occurs, the offending content (if publicly viewable) will be edited or removed. A verbal warning, official warning, or ban of the area the content was published in will be issued. Extreme offenses can result in instant account deletion.": "这份社交准则列表涵盖了我们在整个 Torn 中针对所有用户创建的内容（键入、共享或上传）的所有规则。 这包括论坛、私人消息、聊天、不和谐、个人资料、事件、签名、报纸广告和玩家姓名。 当发生违规行为时，违规内容（如果可公开查看）将被编辑或删除。 将发布内容发布区域的口头警告、官方警告或禁令。 极端的违规行为可能会导致帐户立即被删除。",
    "The use of scripts, extensions, applications or any other kind of software is allowed only if it uses data from our API or a page you have loaded manually and are currently viewing. They cannot make additional non-API requests to Torn, scrape pages that you're not currently viewing, or attempt to bypass the captcha. If the software you're using makes non-API requests that are not manually triggered by you, it is not allowed and can be tracked. Furthermore, releasing software which has malicious or undisclosed abilities is forbidden.": "仅当使用来自我们的 API 或您手动加载且当前正在查看的页面的数据时，才允许使用脚本、扩展程序、应用程序或任何其他类型的软件。 他们无法向 Torn 发出额外的非 API 请求、抓取您当前未查看的页面或试图绕过验证码。 如果您使用的软件发出非您手动触发的非 API 请求，则不允许并且可以对其进行跟踪。 此外，禁止发布具有恶意或未公开功能的软件。",
    "All accounts must be operated exclusively by the original account creator. Sharing your login details with anyone else or having someone initiate processes on your behalf is strictly prohibited and can put your account at risk. Staff have a decade of experience in this field and can easily spot the signs of account sharing. All benefits gained from sharing any account will be removed and bans start at 7 days, but can vary depending on the severity.": "所有账户必须由原始账户创建者独家运营。 严禁与任何其他人共享您的登录详细信息或让他人代表您启动流程，这可能会使您的帐户面临风险。 工作人员在该领域拥有十年的经验，可以轻松发现帐户共享的迹象。 共享任何帐户获得的所有好处都将被删除，禁令从 7 天开始，但可能因严重程度而异。",
    "Users are permitted to own only one Torn account and should never register a duplicate for any reason whatsoever. Using more than one account can give someone an unfair advantage, so Torn staff aggressively monitor suspected abuse using a huge array of tools developed over the last decade. A first-time multiple account offense will result in a game ban or deletion depending on the severity, with all illegal gains being removed.": "用户只能拥有一个 Torn 帐户，不得以任何理由重复注册。 使用多个帐户会给某人带来不公平的优势，因此 Torn 的工作人员使用过去十年开发的大量工具积极监控可疑的滥用行为。 首次多账号违规将根据严重程度导致游戏禁赛或删除，并删除所有非法所得。",
    "Although every aspect of Torn is tested strenuously before release, unintentional exploits are sometimes possible. Every action and gain in Torn is logged with timestamps often going back years in the past, so exploiting a bug / glitch / hack is impossible to get away with. If you find an abusable exploit, do not share it with others. Report it to the developers immediately, it may even be eligible for": "尽管 Torn 的每个方面在发布前都经过了严格的测试，但有时可能会出现无意的攻击。 Torn 中的每一个动作和收获都记录了时间戳，这些时间戳通常可以追溯到过去几年，因此利用错误/故障/黑客攻击是不可能逃脱的。 如果您发现可滥用的漏洞，请不要与他人分享。 立即报告给开发商，它甚至有资格获得",
    "To protect the integrity and fairness of Torn all players must build their own accounts up from registration. Whoever first registered an account is deemed its true owner, meaning the original registrant can still use the Account Recovery system to forcefully gain control again, even after selling the account or giving it away to someone else. Torn staff constantly hunt for account sellers and monitor websites outside of Torn. Tracing illegally sold / given away accounts is simple, and any accounts involved will be terminated on the first offense without warning.": "为了保护 Torn 的完整性和公平性，所有玩家都必须从注册开始建立自己的帐户。 第一个注册帐户的人被视为其真正的所有者，这意味着原始注册人仍然可以使用帐户恢复系统强制重新获得控制权，即使在出售帐户或将其赠予他人之后也是如此。 Torn 的员工不断寻找帐户卖家并监控 Torn 以外的网站。 追踪非法出售/赠送的账户很简单，任何涉及的账户将在第一次犯罪时被终止，恕不另行通知。",
    "The exchange of currency or assets on Torn for real-world money or services (including assets from other games) is strictly prohibited. Real money trading directly affects Torn's economy and donation levels, while exposing our users to fraudulent activities. Staff proactively seek out buyers and sellers both on-site and externally, and no warnings are given for the first offense. Buyers will have their purchased goods removed and be subject to a lengthy game ban, whereas sellers will be banned permanently without recourse.": "严禁用 Torn 上的货币或资产交换现实世界的货币或服务（包括来自其他游戏的资产）。 真钱交易直接影响 Torn 的经济和捐赠水平，同时让我们的用户暴露在欺诈活动中。 工作人员主动在现场和外部寻找买卖双方，初犯不予警告。 买家将移除他们购买的商品并受到长期游戏禁令，而卖家将被永久禁止，没有追索权。",
    "SOCIAL VIOLATIONS:": "社会违规行为：",
    "Selected third parties including:": "选定的第三方包括：",
    "Rules about linking to our site": "关于链接到我们网站的规则",
    "Promote violence.": "宣扬暴力。",
    "Postal address:": "个人地址:",
    "player report": "玩家报告",
    "Player name": "玩家名称",
    "Where we do moderate an interactive service, we will normally provide you with a means of contacting the moderator, should a concern or difficulty arise.": "在我们主持互动服务的地方，如果出现疑虑或困难，我们通常会为您提供联系主持人的方式。",
    "Where we are required to collect personal data by law, or under the terms of the contract between us and you do not provide us with that data when requested, we may not be able to perform the contract (for example, to deliver goods or services to you). If you don't provide us with the requested data, we may have to cancel a product or service you have ordered but if we do, we will notify you at the time.": "如果法律要求我们收集个人数据，或根据我们与您之间的合同条款，您未按要求向我们提供该数据，我们可能无法履行合同（例如，交付商品或服务 给你）。 如果您不向我们提供所要求的数据，我们可能不得不取消您订购的产品或服务，但如果我们这样做，我们会及时通知您。",
    "EXP": "经验",
    "Hide": "隐藏",
    "Events": "事件",
    "Announcement": "公告",
    "Help": "帮助",
    "Logout": "登出",
    "here": "这里",
    "Events": "事件",
    "Job": "工作",
    "Jail": "监狱",
    "Information": "信息",
    "Messages": "消息",
    "Missions": "任务",
    "New Players": "新玩家",
    "Rules": "规则",
    "this week": "本周",
    "Item Market": "物品市场",
    "Home": "家",
    "Skill Levels": "技能等级",
    "Speed": "速度",
    "Skip to content": "跳转到内容",
    "Skip to navigation menu": "跳转到导航菜单",
    "Strength": "力量",
    "to learn more.": "了解更多。",
    "Total": "总计",
    "Trade": "交易",
    "Tutorial": "教程",
    "View Profile": "查看个人资料",
    "Working Stats": "工作统计",
    "You do not have any special skills currently": "您目前没有任何特殊技能",
    "TORN uses cookies to ensure you get the best experience. Go": "TORN 使用 cookie 来确保您获得最佳体验。 去",
    "TORN uses cookies to ensure you get the best experience. Please see our": "TORN 使用 cookie 来确保您获得最佳体验。 请查看我们的",
    "This is your home, you can get here at any time by clicking it on the navigation panel. It shows most of your details, for instance your attacking stats and the property you are living in. If you ever need information about yourself, here's where to come.": "这是您的家，您可以随时在导航面板上点击它到达这里。 它显示了您的大部分详细信息，例如您的攻击统计数据和您居住的房产。如果您需要有关您自己的信息，请点击这里。",
    "Settings": "设置",
    "Auto theft": "汽车盗窃",
    "Casino": "堵场",
    "City": "城市",
    "Cost": "费用",
    "Defense": "防御",
    "Dexterity": "敏捷",
    "Drug deals": "面粉交易",
    "Enemies": "敌人",
    "Energy": "能量",
    "energy": "能量",
    "every": "每",
    "Education": "教育",
    "Education:": "教育:",
    "Endurance": "耐力",
    "Criminal Record": "犯罪记录",
    "Computer crimes": "计算机犯罪",
    "Company": "公司",
    "Forums": "论坛",
    "Hospital": "医院",
    "Hall of Fame": "名人堂",
    "Recruit Citizens": "招募市民",
    "Dark Mode": "深色模式",
    "Age": "年龄",
    "Battle Stats": "战斗统计",
    "Casino points": "堵场积分",
    "Calendar": "日历",
    "Areas": "区域",
    "Crimes": "犯罪",
    "Days in faction": "帮派天数",
    "Dealer": "经销商",
    "Desktop View": "桌面视图",
    "Equipped Weapons & Armor": "装备的武器和盔甲",
    "Faction": "帮派",
    "Fees": "费用",
    "Faction Information": "帮派信息",
    "FULL": "已满",
    "Fraud crimes": "诈骗",
    "Gain access to Advanced Search, a Notebook and an Exclusive Forum by becoming a donator today. Click here!": "立即成为捐赠者，获得对高级搜索、笔记本和独家论坛的访问权限。 点击这里！",
    "General Information": "常规信息",
    "Gym": "健身房",
    "Happy": "幸福度",
    "Help Torn thrive by becoming a donator! Help us pay for our servers, hosting fees, developers, and advertising.": "成为捐赠者，帮助 Torn 茁壮成长！ 帮助我们支付服务器费用、托管费用、开发人员费用和广告费用。",
    "It's nearly time for St Patrick's Day, when all alcohol effects are doubled and Green Stout spawns on the city map.": "快到圣帕特里克节了，届时所有酒精效果都会翻倍，并且城市地图上会出现绿色烈性黑啤酒。",
    "Items": "物品",
    "Job Information": "工作信息",
    "Intelligence": "智力",
    "Level": "等级",
    "Life": "生命值",
    "Lists": "列表",
    "Loan Shark": "高利贷",
    "Log": "日志",
    "Money": "现金",
    "Marital status": "婚姻状况",
    "Manual labor": "体力劳动",
    "Murder": "谋杀",
    "Name": "名称",
    "Name:": "姓名:",
    "Networth": "净资产",
    "Other": "其它",
    "News Ticker": "新闻行情",
    "None": "无",
    "Properties": "房产",
    "Rank": "段位",
    "Server:": "服务器:",
    "Shack": "棚屋",
    "Theft": "盗窃",
    "User's Name / ID": "用户名 / ID",
    "was posted": "已发布",
    "Text based RPG - TORN": "基于文字的RPG - TORN",
    "Single": "单身",
    "Become a subscriber today to gain donator status, points, and special monthly rewards! Click here!": "立即成为订阅者以获得捐赠者身份、积分和特别月度奖励！ 点击这里！",
    "Credits": "鸣谢",
    "Home Tutorial": "家园教程",
    "Illegal products": "违禁品",
    "minutes": "分钟",
    "Newspaper": "报纸",
    "Forum posts": "论坛帖子",
    "Friends": "好友",
    "Income": "收入",
    "increased by": "提高",
    "Latest Attacks": "最近攻击",
    "Latest Messages": "最近消息",
    "Latest Events": "最近事件",
    "life": "生命值",
    "Merits": "优点",
    "Personal stats": "个人统计",
    "Places": "位置",
    "Points": "积分",
    "privacy policy": "隐私政策",
    "Property": "房产",
    "Refills": "重填",
    "Property Information": "房产信息",
    "Staff": "人员",
    "If you have an issue and you're not sure who to contact, please follow": "如果您遇到问题并且不确定与谁联系，请关注",
    "In Training": "训练中",
    "Need more points?": "需要更多积分？",
    "Quality Assurance": "质量保证",
    "Moderating User Content": "审核用户内容",
    "Staff Members": "工作人员",
    "A donator pack will give you 50 points on top of other great benefits. Buy now!": "捐赠者礼包除了其他好处外，还会为您提供 50 点积分。 立即购买！",
    "Below are the staff of Torn City. There are": "以下是 Torn City 的工作人员。 有",
    "Assisting users / Public moderation": "协助用户/公共审核",
    "All": "全部",
    "All Events": "全部事件",
    "ALL EVENTS (": "全部事件 (",
    "attacked and hospitalized you [": "攻击了你并让你住院 [",
    "attacked you [": "攻击了你 [",
    "attacked you but lost [": "攻击了但是输了 [",
    "Cancel": "取消",
    "Check All": "全选",
    "Delete": "删除",
    "Delete selected": "删除所选",
    "Events Tutorial": "事件教程",
    "Here you can view your events. Events are things that have happened to you, for instance if someone attacks you, a notification will be displayed here. You can share your events with others by sending them, you can also save events so they are never deleted in the future.": "在这里您可以查看您的事件。 事件是发生在你身上的事情，例如如果有人攻击你，这里会显示一条通知。 您可以通过发送事件与他人分享您的事件，您还可以保存事件，这样它们就不会在将来被删除。",
    "Please allow up to 5 seconds...": "请最多等待 5 秒...",
    "Please enable Cookies and reload the page": "请启用 Cookie 并重新加载页面",
    "Redirecting...": "重定向…",
    "This process is automatic. Your browser will redirect to your requested content shortly.": "这个过程是自动的。 您的浏览器将很快重定向到您请求的内容。",
    "Checking your browser before accessing www.torn.com.": "在访问 www.torn.com 之前检查您的浏览器。",
    "error code: 1020": "错误代码: 1020",
    "Nerve": "勇气",
    "OVER": "超出",
    "RECEIVED (": "收到的 (",
    "Save selected": "保存已选择",
    "SAVED (": "已保存 (",
    "SEND": "发送",
    "Send Event": "发送事件",
    "Uncheck All": "反选全部",
    "User ID:": "用户 ID:",
    "view": "查看",
    "You have full": "你有完整的",
    "Use your Refills": "使用你的重填",
    "Use your Merits": "使用你的优点",
    "You have over full": "你已经满了",
    "Here you can self-exclude yourself from the Casino. This will prevent you from being able to\naccess any casino games, or use any Lottery Voucher items. Longer self-exclusion durations\nwill become available to you after the completion of previous sessions. This should still\nonly be used as a last resort, and will not affect the missions you receive, which can still\nbe related to the Casino.": "在这里，您可以自行将自己排除在堵场之外。 这将阻止您\n访问任何堵场游戏，或使用任何彩票代金券物品。 在完成之前的会话后，\n您将可以使用更长的自我排除期限。 这仍应\n用作最后的手段，并且不会影响您收到的任务，这些任务仍\n可能与堵场有关。",
    "Honor Names:": "荣誉称号：",
    "Manage Bazaar": "管理集市",
    "Manage Display Case": "管理陈列柜",
    "Melee": "肉搏",
    "mobile phone number": "手机号码",
    "more day until 0.": "更多天，直到 0。",
    "No one": "没有人",
    "NO": "否",
    "Off": "关闭",
    "Ok": "是",
    "Organized Crimes": "有组织的犯罪",
    "Pawn Shop": "当铺",
    "Personal Stats": "个人统计",
    "Personal Details": "个人详细信息",
    "Personal details": "个人详细信息",
    "Pharmacy": "药店",
    "Please, provide valid link properties": "请提供有效的链接属性",
    "Lottery": "抽奖",
    "Jewelry Store": "珠宝店",
    "Job Listings": "工作清单",
    "Insert": "插入",
    "Icon placement:": "图标摆放：",
    "Icon settings": "图标设置",
    "Go to": "前往",
    "?\nThis is irreversible.": "?\n这是不可逆的。",
    ".\nWe highly recommend you keep this information up to date in order to ensure the security of your account, and the ability to recover it if you should ever\nlose access.": ".\我们强烈建议您保持此信息为最新，以确保您的帐户安全，并在您失去访问权限时能够恢复它。",
    "[use]": "[使用]",
    "Blackjack": "二十一点",
    "Bookie": "堵徒",
    "Bugs & Issues": "错误&问题",
    "Casino self-exclusion": "堵场自我排除",
    "Change email": "更改邮箱",
    "CHANGE EMAIL ADDRESS": "更改电子邮件地址",
    "Change gender": "更改性别",
    "Change password": "更改密码",
    "Change name": "更改名称",
    "Change your navigation settings": "更改您的导航设置",
    "Christmas Town": "圣诞小镇",
    "Chronicle Archives": "编年史档案",
    "City Bank": "城市银行",
    "City Hall": "市政厅",
    "City:": "城市:",
    "Community Events": "社区活动",
    "Company Forum": "公司论坛",
    "Company Funds": "公司资金",
    "Competitions": "比赛",
    "Country:": "国家：",
    "Craps": "掷骰子",
    "Current Links": "当前链接",
    "date of birth": "生日",
    "Cyber Force": "网军",
    "Default order anchored": "锚定的默认订单",
    "Docks": "码头",
    "Emails will be sent to:": "电子邮件将发送至：",
    "Email subscriptions": "电子邮件订阅",
    "Edit": "编辑",
    "Format": "格式",
    "You have finished the education course you were taking! Click": "您已经完成了正在学习的教育课程！ 点击",
    "You have no recent attacks.": "你没有最近的攻击。",
    "You have no recent messages.": "你没有最近的消息。",
    "Dealer at the Casino": "堵场的经销商",
    "Male": "男",
    "Strength: (I.e. Power) Increases the damage you make to your opponent by adding pure power to your melee & fist blows, and toughening up your stance with guns for clean & precise hits.": "力量：（即力量）通过为近战和拳击增加纯粹的力量来增加你对对手造成的伤害，并用枪支加强你的姿态以获得干净和精确的命中。",
    "! You walk into the gym and begin browsing the exercises available.": "！ 您走进健身房，开始浏览可用的练习。",
    "Ability to evade an attack": "躲避攻击的能力",
    "Ability to withstand damage": "承受伤害的能力",
    "available to use.": "可用。",
    "Chance of hitting opponent": "击中对手的几率",
    "Damage you make on impact": "你在击中时造成的伤害",
    "energy per train": "能量每次训练",
    "Gym Tutorial": "健身房教程",
    "nerve": "勇气",
    "of total": "总计",
    "You have": "你有",
    "Premier Fitness": "高级健身",
    "St Patrick's Day begins at noon on the 16th, providing a 2x boost to the nerve gains from Alcohol.": "圣帕特里克节从 16 日中午开始，提供 2 倍的酒精刺激神经增益。",
    "TRAIN": "训练",
    "Training your stats in Torn is imperative. They strongly influence your success during attacking, and a player with higher stats is more feared.\nTo unlock new gyms all you have to do is train. You'll slowly gain gym EXP which will allow you to access new and better gyms. The next gym will be available for you to join once you have the required gym EXP.": "在 Torn 中训练您的属性势在必行。 它们会极大地影响您在进攻过程中的成功率，并且更害怕具有更高统计数据的球员。\n要解锁新道馆，您所要做的就是训练。 您将慢慢获得健身房 经验，这将使您能够使用新的更好的健身房。 拥有所需的健身房 经验 后，您就可以加入下一个健身房。",
    "Welcome to": "欢迎来到",
    "What would you like to train today?": "你今天想训练什么？",
    "Membership cost - $": "会员费用 - $",
    "per train": "每次训练",
    "Silver Gym": "银级健身房",
    "Woody's Workout Club": "伍迪健身俱乐部",
    "Energy usage -": "能量消耗 -",
    "Lightweight": "轻量级",
    "Prepare yourself for the forthcoming St Patrick's Day event, which will double the effects of all Alcohol items.": "为即将到来的圣帕特里克节活动做好准备，这将使所有酒类物品的效果翻倍。",
    "rise in value up to": "价值上升到",
    "You do not have enough energy left": "你没有足够的能量了",
    "You managed to complete 1 minute in a beginners boxing session throwing 1 punch": "您成功完成了 1 分钟的初学者拳击训练，打出了 1 拳",
    "Back": "返回",
    "Biology": "生物学",
    "Here you can take courses in the local college to increase your working stats. Some courses even allow you to do new crimes, unlock new areas, provide unique skills, and make special abilities available. Courses will often take several weeks to complete and cost money.": "在这里，您可以参加当地大学的课程，以提高您的工作统计数据。 有些课程甚至允许您进行新的犯罪活动、解锁新的区域、提供独特的技能并提供特殊能力。 课程通常需要数周才能完成并且需要花钱。",
    "Business": "商业",
    "Combat Training": "战斗训练",
    "Computer Science": "计算机科学",
    "Education Tutorial": "教育教程",
    "General Studies": "通识教育",
    "Health & Fitness": "健康与健身",
    "History": "历史",
    "just defeated": "刚刚被击败",
    "Law": "法律",
    "Mathematics": "数学",
    "NNGO Blood Money": "非政府组织血钱",
    "Pod1": "Pod1",
    "Points see a": "分看一个",
    "Psychology": "心理学",
    "Self Defense": "自卫",
    "Sports Science": "运动学",
    "The Red Knights": "红色骑士团",
    "to secure the Gold I rank in a gruelling 3 day war involving 5,700 attacks": "在一场涉及 5,700 次攻击的艰苦 3 天战争中获得金牌 I 排名",
    "This area is unavailable while you're in hospital.": "当您在医院时，该区域不可用。",
    "Here you can view all of the items you own. You can look up information about the items, use them or send them to people. If one of your items is a weapon or armor, you can equip it by clicking the relevant icon next to it. You can use up to four different types of weapons when attacking, Primary (A rifle or big gun), Secondary (A pistol, smaller gun or specialist launcher), Melee (A hand-to-hand weapon) and Temporary (Throwable or Utility item).": "在这里您可以查看您拥有的所有物品。 您可以查找有关这些物品的信息、使用它们或将它们发送给其他人。 如果你的其中一件物品是武器或盔甲，你可以通过点击它旁边的相关图标来装备它。 攻击时最多可以使用四种不同类型的武器，主要武器（步枪或大枪）、次要武器（手枪、小型枪支或专用发射器）、近战武器（徒手武器）和临时武器（可投掷或实用） 物品）。",
    "                                              Equip": "装备",
    "                                              Unequip": "脱下",
    "                                            Equip": "装备",
    "                                            this\n                                        Item": "这个\n物品",
    "                                            Unequip": "脱下",
    "            Open": "打开",
    "            Sell": "出售",
    "            Send": "发送",
    "            Take": "拿走",
    "            Trash": "丢垃圾",
    "            Use": "使用",
    "All tab is full": "所有选项卡已满",
    "Ammo": "弹药",
    "Bag of Bon Bons": "一袋糖果",
    "Bag of Chocolate Kisses": "一袋巧克力之吻",
    "Baseball Bat": "棒球棒",
    "Bolt Cutters": "断线钳",
    "Box of Sweet Hearts": "一盒甜心",
    "Dagger": "匕首",
    "Ecstasy": "迷魂药",
    "First Aid Kit": "急救箱",
    "Gold Watch": "金表",
    "Item іMarket": "物品市场",
    "Items Tutorial": "物品教程",
    "Jewelry": "珠宝",
    "Leather Pants": "皮裤",
    "Load more All items": "加载更多 全部物品",
    "Loadout #1": "装载 #1",
    "Lollipop": "棒棒糖",
    "Lottery Voucher": "彩票代金券",
    "Pack of Cuban Cigars": "一包古巴雪茄",
    "Primary": "初级",
    "Ruger 57": "Ruger 57",
    "Small First Aid Kit": "小型急救箱",
    "this Item": "这个物品",
    "Trades": "交易",
    "Trainers": "运动鞋",
    "Xanax": "Xanax",
    "Your items -": "您的物品 -",
    "Equip this Item": "装备此物品",
    "Send this Item": "送出此物品",
    "Supply Packs": "补给包",
    "Take": "拿走",
    "Trash this Item": "丢弃此物品",
    "Use": "使用",
    "All Properties": "所有房产",
    "Happiness": "幸福度",
    "Here you are able to control what happens to your houses. You may wish to sell them to someone else by putting them on the real estate market, or rent them out to someone for a set price and length by clicking 'Lease'. You can also upgrade and furnish your houses by buying a swimming pool, or filling it with plasma screen TVs by upgrading the interior. You can only customize your house if you are the owner and living in it. You can not upgrade or share shacks. If you rent a property or your spouse owns properties, they will appear on the list below, you will have to move in to them to actually live in them.": "在这里，您可以控制房屋发生的事情。 您可能希望通过将它们投放到房地产市场来将它们出售给其他人，或者通过单击“租赁”以固定价格和期限将它们出租给某人。 您还可以通过购买游泳池来升级和装修您的房屋，或者通过升级内部装饰来装满等离子电视。 只有当您是业主并居住在其中时，您才能定制您的房子。 您不能升级或共享棚屋。 如果您租用房产或您的配偶拥有房产，它们将出现在下面的列表中，您必须搬进去才能真正居住。",
    "Market price": "市场价",
    "Property Tutorial": "房产教程",
    "Owner": "拥有者",
    "You are living here": "你住在这里",
    "Upkeep": "保养",
    "Staff cost": "员工成本",
    "Upkeep is charged daily and can be paid via the upkeep panel on each property. You will only be charged upkeep if the property is in use. For example, if you are living in it, or your spouse is living in a property you own; you will be charged the upkeep.": "维护费用每天收取，可通过每处房产的维护面板支付。 只有在使用中，您才需要支付维护费用。 例如，如果您住在其中，或者您的配偶住在您拥有的房产中； 您将被收取维修费用。",
    "Hospitalized by": "把你打进医院的人是 ",
    "Hospital Tutorial": "医院教程",
    "This is the hospital. People who get attacked or fail a crime may be sent here to recover. If you train hard in the medical profession and reach the top job rank, you earn the ability to revive people from hospital.": "这是医院。 被袭击或犯罪失败的人可能会被送到这里康复。 如果你在医疗行业刻苦训练并达到最高职位，你将获得从医院救人的能力。",
    "You are in hospital for another": "你还需要在医院待 ",
    "You better stay and rest.": "你最好留下来休息。",
    "People are": "人在",
    "Time": "时间",
    "Reason": "原因",
    "Overdosed on Xanax": "过量服用 Xanax",
    "Everyone": "所有人",
    "Members": "成员",
    "Full": "满",
    "Create": "创建",
    "Create a Faction": "创建一个帮派",
    "Faction Name": "帮派名称",
    "Factions": "帮派",
    "You will meet the criteria for more factions as you increase your battle stats": "随着战斗属性的增加，您将满足更多帮派的标准",
    "": "",
    "It will cost": "花费",
    "Please enter faction name below:": "请在下方输入帮派名称：",
    "to": "去",
    "to make a Faction.": "去创建一个帮派。",
    "Factions looking for members": "正在招人的帮派",
    "You've not applied to this faction yet": "你还没有申请加入这个帮派",
    "View": "查看",
    "Applied": "状态",
    "10% bonus to museum point rewards": "10% 的博物馆积分奖励",
    "A variety of different Easter eggs will appear at random throughout Torn. Pick them up to add them into your inventory, then consume them at your leisure to receive their powerful effects.": "各种不同的复活节彩蛋将在整个 Torn 中随机出现。 捡起它们将它们添加到您的库存中，然后在闲暇时食用它们以获得它们的强大效果。",
    "Alcohol effects are doubled & Green Stout appears in city": "酒精效果加倍，绿色黑啤酒出现在城市",
    "Black Friday": "黑色星期五",
    "Awareness Awareness Week": "提高认识周",
    "Citizens compete in our annual popularity contest to see who can gain the most votes and be crowned Mr and Ms Torn.  Upvote your favourites or enter your own image and cripple your self-confidence using the judgement of strangers": "公民们参加我们一年一度的人气竞赛，看谁能获得最多的选票并加冕为 Torn 先生和 Torn 女士。 给你最喜欢的人投票或输入你自己的形象，用陌生人的判断削弱你的自信",
    "Dress up and attack others to fill your basket with treats": "装扮并攻击他人，用零食装满你的篮子",
    "Double racing points & racing skill": "双倍赛车积分和赛车技巧",
    "Dog Tags": "狗牌",
    "Beer items are five times more effective": "啤酒产品的功效高出五倍",
    "Valentine's Day": "情人节",
    "Tourism Day": "旅游日",
    "International Beer Day": "国际啤酒日",
    "Job points received tripled & training effects tripled": "工作积分获得三倍 & 培训效果三倍",
    "EXP gained while attacking is doubled": "攻击时获得的经验值翻倍",
    "Energy drink effects are doubled": "能量饮料效果加倍",
    "Counterfeiting": "伪造",
    "Crimes Tutorial": "犯罪教程",
    "Crime": "犯罪",
    "Doing crimes can earn you money and items. The more crimes you do, the more experience you will gain, making it easier for you to do harder crimes. Make sure you understand that being caught for your crimes could greatly reduce your crime experience, making it even harder to do crimes. As you advance, you will be able to do even more crimes, earning you big money.": "犯罪可以为您赚取金钱和物品。 你犯的罪越多，你获得的经验就越多，让你更容易犯下更严重的罪行。 确保您了解因犯罪被捕会大大减少您的犯罪经历，使犯罪更加困难。 随着您的进步，您将能够犯下更多罪行，从而赚取大笔金钱。",
    "So, you're in need of some quick cash? You sit down and begin thinking of ways you could get a little richer.\nThe more crimes you do, the easier you will be able to do them. The crimes are listed in order from easy to hard.\nDon't try the hard ones too quickly or you could find yourself in jail!": "所以，你需要一些快速的现金？ 您坐下来开始思考可以变得更富有的方法。\n您犯罪的次数越多，您就越容易犯下这些罪行。 罪行按从易到难的顺序列出。\n不要太快尝试困难的罪行，否则你可能会进监狱！",
    "NEXT STEP": "下一步",
    "Grand Theft Auto": "侠盗猎车手",
    "Hacking": "黑客攻击",
    "Kidnapping": "绑架",
    "Larceny": "偷窃",
    "Pickpocket Someone": "扒窃",
    "Search for Cash": "搜索现金",
    "Plant a Computer Virus": "植入计算机病毒",
    "Shoplift": "商店0元购",
    "Sell Copied Media": "出售盗版媒体",
    "Transport Drugs": "运输药品",
    "Bombings": "爆炸",
    "Assassination": "暗杀",
    "Arson": "纵火",
    "Arms Trafficking": "武器贩运",
    "Armed Robberies": "武装抢劫",
    "Faction Description": "帮派介绍",
    "You successfully initiated a raid against": "您成功发起了针对",
    "Type in your application below to send a request to the leadership of SMTH - Trisolary.": "在下方输入您的申请，向 SMTH - Trisolary 的领导层发送请求。",
    "Version changes can only enjoy bonuses and use items 72 hours after joining factions.": "改版只能在加入帮派72小时后才能享受加成和使用道具。",
    "VIEW APPLICATION": "查看申请",
    "Travel capacity - max number of items you can bring back increased by 9": "旅行容量 - 您可以带回的最大物品数量增加 9",
    "Toleration": "容忍度",
    "We do not accept applications!": "我们不接受申请！",
    "No active chain": "无活跃连击",
    "New rule: after 3 days of inactivity, we will kick you. Exceptions are made, case by case.": "新规则：3 天不活动后，我们将踢你。 有例外，视情况而定。",
    "Our little faction try to treat everyone equally. We don't care if you have your own Private Island with maxed out banking with spare cash in vaults and offshore accounts... or if you just starting playing a few months ago and are still learning the ropes. You will be a welcomed members, we can learn from each other. When it is time to upgrade, we always ask our group what direction they want to take and pursue a common course.": "我们的小帮派试图平等对待每个人。 我们不在乎您是否拥有自己的私人岛屿，银行业务和离岸账户中的备用现金已用完……或者您是否几个月前才开始玩游戏并且仍在学习技巧。 你将是一个受欢迎的成员，我们可以互相学习。 当需要升级时，我们总是询问我们的团队他们想要采取什么方向并追求共同的路线。",
    "Reduces drug addiction gain by 50%": "减少 50% 的吸毒成瘾",
    "Reduces the side effects of drugs and increases addiction mitigation by 30%": "减少药物的副作用并增加 30% 的成瘾缓解",
    "RESPECT:": "",
    "SUBMIT FACTION APPLICATION": "提交帮派申请",
    "THIS FACTION IS NOT IN A WAR": "这个帮派不在战争中",
    "[upgrade]": "[升级]",
    "Advertise here": "在此处投放广告",
    "Daily Dime": "每日硬币",
    "There are no bounties up at this time": "目前没有悬赏",
    "Unicorn": "独角兽",
    "Tell your story": "讲述你的故事",
    "Newspaper Tutorial": "报纸教程",
    "The newspaper offers access to a wide range of useful areas and is also the hub for news delivered by Torn's community reporters.": "该报纸提供了对广泛有用领域的访问，也是 Torn 社区记者发布新闻的中心。",
    "An Illustrated Weekly Newspaper": "插图周报",
    "Casino Tutorial": "堵场教程",
    "Holy Grail": "圣杯",
    "This is the Torn City Casino, where you can gamble your money and hope to win big! As you level higher, even more casino games become available to you. Have a play around with a few of the games and see which ones you get lucky on! You are given 75 casino tokens every day to use here. A token will be used every time you play against a casino dealer, however Poker, Russian Roulette and the Bookie will not use tokens.": "这是 Torn City 堵场，您可以在这里堵博并希望赢得大奖！ 随着您级别的提高，您可以玩更多的堵场游戏。 试玩几款游戏，看看您在哪些游戏中走运！ 您每天会获得 75 个堵场代币，可以在这里使用。 每次与堵场荷官对战时都会使用代币，但扑克、俄罗斯轮盘和庄家不会使用代币。",
    "LOCKED": "未解锁",
    "HIGH-LOW": "高 - 低",
    "CRAPS": "掷骰子",
    "LOTTERY": "彩票",
    "RUSSIAN ROULETTE": "俄罗斯轮盘堵",
    "POKER": "扑克",
    "SLOTS": "老虎机",
    "SPIN THE WHEEL": "旋转轮盘",
    "BLACKJACK": "二十一点",
    "football match": "足球比赛",
    "at the bookie today after SSC Napoli won in the": "在 SSC Napoli 赢得比赛后，今天在菠菜公司",
    "has won": "赢了",
    "Level Up": "升级",
    "Increase life to": "增加生命值到",
    "Article": "文章",
    "Double Crime, Paddy's Time!": "双倍犯罪，帕迪的时间！",
    "SILVER HAND REACHES DIAMOND RANK!": "白银之手达到钻石等级！",
    "Tear Gas": "催泪弹",
    "The forum thread": "论坛主题",
    "The market value of": "市值",
    "was published": "发表了",
    "Basic Information": "基础信息",
    "Civilian": "平民",
    "Country": "国家",
    "Awards": "奖励",
    "A combined": "一个组合",
    "Actions": "动作",
    "Competition Status": "比赛状态",
    "Last action": "最后动作",
    "Okay": "好的",
    "Medals": "奖牌",
    "Personal Information": "个人信息",
    "Nudist": "裸体主义者",
    "Now": "现在",
    "Status": "状态",
    "Real name": "真实姓名",
    "Profile pages show everything about a player including name, player ID, level, rank, age, gender and current status. From this page you can choose to attack, message, chat with, send money to, and trade with them.": "个人资料页面显示有关玩家的所有信息，包括姓名、玩家 ID、级别、排名、年龄、性别和当前状态。 在此页面上，您可以选择攻击、消息、聊天、汇款和交易。",
    "Role": "角色",
    "There is no active competition": "没有活跃的竞争",
    "uploaded images": "上传的图片",
    "User Information": "用户信息",
    "What would you like to do?": "你想做什么？",
    "Faction Warfare": "帮战",
    "successfully revived you.": "成功将你复活。",
    "There are no events on this page": "此页面上没有事件",
    "Are you sure you want to quit your job?": "你确定要辞掉你的工作吗？",
    "Casino Points:": "堵场积分:",
    "Casino President": "堵场总裁",
    "Casino Manager": "堵场经理",
    "Casino Points to upgrade.": "堵场积分去升级。",
    "Choose Collect tips": "选择收集提示",
    "Collect tips": "收集提示",
    "Count cards": "算牌",
    "daily.": "每天。",
    "DO SPECIAL": "做特别的",
    "endurance and": "耐力和",
    "Endurance:": "耐力:",
    "Gaming Consultant": "菠菜顾问",
    "Get Promoted": "获得晋升",
    "Having a job in Torn City is one of the easiest ways to make money. Jobs use your working stats (Manual labor, intelligence and endurance), increasing them will allow you to progress through the job ranks to earn more money and get extra bonuses. Sometime later in life, you may wish to join a person's company or even create your own. Working stats will make you work better in companies, pleasing your employer.": "在 Torn City 找到一份工作是最简单的赚钱方式之一。 工作使用您的工作统计数据（体力劳动、智力和耐力），增加这些数据将使您在工作等级中取得进步，从而赚取更多的钱并获得额外的奖金。 在以后的生活中，您可能希望加入某人的公司，甚至创建自己的公司。 工作统计数据将使您在公司中工作得更好，取悦您的雇主。",
    "Income:": "收入:",
    "intelligence,": "智力，",
    "Intelligence:": "智力:",
    "Job Tutorial": "工作教程",
    "Jobs": "工作",
    "Manual Labor:": "体力劳动：",
    "manual labor,": "体力劳动",
    "Manual:": "手动:",
    "No, go back.": "不，回去。",
    "Marketing Manager": "市场经理",
    "Pocket tokens": "袖珍代币",
    "per day": "每天",
    "point": "积分",
    "Quit Job": "退出工作",
    "Rank & Benefits": "职级与福利",
    "Rank:": "职级:",
    "Revenue Manager": "营收经理",
    "Specials": "特殊",
    "Stats Needed": "属性要求",
    "Stats Needed:": "属性要求:",
    "Steal cash": "偷现金",
    "Yes, quit!": "是的，退出！",
    "You also get": "你也得到了",
    "You currently work at the Casino. You receive": "您目前在堵场工作。 你收到",
    "You have enough working stats to be promoted to Gaming Consultant! It will cost": "您有足够的工作属性可以晋升为菠菜顾问！ 这将花费",
    "casino": "堵场",
    "casino points.": "堵场积分。",
    "MAN:": "人:",
    "Real Madrid v Liverpool": "皇家马德里 v 利物浦",
    "Type in the amount of casino points you would like to use on collecting tips.": "输入您想用于收集小费的堵场积分数。",
    "You currently have": "你当前有",
    "points": "积分",
    "has decreased by": "减少了",
    "Choose Pocket tokens": "选择口袋代币",
    "/ INT:": "/ 智力:",
    "/ END:": "/ END:",
    "Speed up recovery times and boost your maximum energy bar to 150. Buy a donator pack here!": "加快恢复时间并将您的最大能量条提高到 150。在这里购买捐赠包！",
    "You have enough working stats to be promoted to Marketing Manager! It will cost": "您有足够的工作属性可以晋升为营销经理！ 这将花费",
    "Low Energy?": "低能量？",
    "You have enough working stats to be promoted to Revenue Manager! It will cost": "您有足够的工作属性可以晋升为收益经理！ 这将花费",
    "Continue": "继续",
    "casino points!": "堵场积分！",
    "Choose Steal cash": "选择窃取现金",
    "in high stakes craps using": "在高额堵注中使用",
    "You managed to convince several players to tip you": "你设法说服了几个玩家给你小费",
    "in": "在",
    "Average Joes": "匀速慢跑",
    "Beach Bods": "沙滩有氧",
    "Description:": "描述：",
    "Biology Modules": "生物学模块",
    "It will cost you": "这将花费你",
    "It's time to start learning about the world of medicine, when to use it, how to administer it, and finally its synthesis.": "是时候开始了解医学世界了，什么时候使用它，如何管理它，最后是它的合成。",
    "JOIN COURSE": "加入课程",
    "Parameters:": "参数：",
    "Prerequisites:": "先决条件：",
    "Are you sure you want to join the": "您确定要加入",
    "Are you the missing link? At the end of this course you'll know more about Neanderthal man than the Discovery Channel.": "你是缺失的一环吗？ 在本课程结束时，您将比探索频道更了解尼安德特人。",
    "Back to Education": "返回教育",
    "You are ready to take this course.": "您已准备好学习本课程。",
    "You have completed this course!": "您已完成本课程！",
    "You do not meet the requirements for this course. Please complete the prerequisites first.": "您不符合本课程的要求。 请先完成先决条件。",
    "You've seen it on TV. Now find out how to do it in real life.": "你在电视上看到过。 现在找出如何在现实生活中做到这一点。",
    "We don't just wear them. Learn about their chemical structure and composition here.": "我们不只是穿它们。 在这里了解它们的化学结构和成分。",
    "We all know how to strike a nerve with someone. Here you'll learn which nerve will have your opponent on the floor crying like a 5 year old girl.": "我们都知道如何激怒某人。 在这里，您将了解哪条神经会让您的对手在地板上哭得像一个 5 岁的女孩。",
    "Vaginal Didelphys to start, followed by a course of DNA synthesis, finished off with a crash course in mitosis. The most exciting introduction in science.": "Vaginal Didelphys 开始，接着是 DNA 合成课程，最后是有丝分裂速成课程。 科学界最激动人心的介绍。",
    "to join and will take": "加入并接受",
    "to complete.": "以完成。",
    "The foot bone is connected to the ankle bone, The ankle bone is connected to the leg bone, The leg bone is connected to the hip bone, and so on...": "脚骨与踝骨相连，踝骨与腿骨相连，腿骨与髋骨相连，等等……",
    "Starting with the dark world of narcotics and the recreational use of drugs, and finishing with making your own pain killers, you'll learn all there is to know about medicine.": "从药品的黑暗世界和药品的消遣性使用开始，到自制止痛药结束，您将学到有关医学的所有知识。",
    "Put that fear of needles behind you by learning how to successfully administer a blood transfusion.": "通过学习如何成功地进行输血，消除对针头的恐惧。",
    "Gain a 1% damage bonus to all weapons": "所有武器获得 1% 的伤害加成",
    "Gain a 10% damage increase when hitting an opponent's throat": "击中对手喉咙时伤害增加 10%",
    "Gain a 3% chance increase of achieving a critical hit": "获得暴击的几率增加 3%",
    "Gain a bonus of 10% to medical item effectiveness": "获得 10% 的医疗物品效果加成",
    "Gain a further 10% bonus to medical item effectiveness": "获得额外 10% 的医疗物品效果加成",
    "Gain the ability to equip steroids in your temporary slot and unlock the pharmacy": "获得在临时插槽中装备类固醇并解锁药房的能力",
    "in Achievements has received": "在成就中获得",
    "Learning outcomes:": "学习成果：",
    "SIGN ME UP!": "我要报名！",
    "To end your degree in biology you will learn about hormones and neurotransmitters.": "为了结束您的生物学学位，您将了解激素和神经递质。",
    "course?": "课程？",
    "Increase of working stats": "提高工作属性",
    "Back to Crimes": "回到犯罪",
    "Criminal record": "犯罪记录",
    "DO CRIME": "犯罪",
    "Search the Bins": "搜索垃圾桶",
    "Search the Dumpsters": "搜索垃圾箱",
    "Search the Movie Theater": "搜索电影院",
    "Search the Train Station": "搜索火车站",
    "Search the Water Fountain": "搜索喷泉",
    "Search Under the Old Bridge": "搜索旧桥下",
    "Searching the streets for cash? Not the quickest way of making money, but that depends on the place you search!": "满大街找钱？ 不是最快的赚钱方式，但这取决于您搜索的地方！",
    "Result": "结果",
    "The share price of": "股价",
    "Torn & Shanghai Banking": "Torn & 上海银行",
    "TRY AGAIN": "再试一次",
    "CHANGE CRIME": "改变罪行",
    "Selling copied media may be easy, but making a large profit all depends on what the people like. If you copy a good type of media on to a CD or DVD, more people are going to buy it!": "出售复制媒体可能很容易，但要赚大钱全看人们喜欢什么。 如果您将一种好的媒体复制到 CD 或 DVD 上，就会有更多人购买！",
    "Genres": "类型",
    "You begin recording copies of the movie you are going to sell at the local market.": "您开始录制要在当地市场上出售的电影的副本。",
    "You buy a pack of recordable DVDs to rip the latest action movie on to and hop on your PC.": "您购买一包可刻录的 DVD，将最新的动作片翻录到您的 PC 上。",
    "You set up the stall and wait for customers.": "您设置摊位并等待顾客。",
    "Which shop would you like to shoplift at? Make your choice wisely as different shops are harder than others!": "你想在哪家商店行窃？ 明智地做出选择，因为不同的商店比其他商店更难！",
    "Clothes Shop": "服装店",
    "Sweet Shop": "糖果店",
    "has increased by": "增加了",
    "Jewelry Shop": "珠宝店",
    "Market Stall": "市场摊位",
    "Shops": "商店",
    "Which item would you like to steal from the clothes shop?": "你想从服装店偷什么东西？",
    "Tank Top": "背心",
    "Jacket": "夹克",
    "Item": "物品",
    "You see police enter the main door, you drop the clothing and run for the back door. Luckily you get out and escape the police.": "你看到警察进入正门，你脱下衣服跑向后门。 幸运的是你逃脱了警察的追捕。",
    "You head down to the TC clothes shop and walk through the door.": "您前往 TC 服装店，然后走进门。",
    "You grab a jacket from the shelf and begin taking off the tag.": "从架子上拿了一件夹克，开始取下标签。",
    "A guard spots you on the cameras and alerts the police.": "名警卫在摄像机上发现了您并通知了警察。",
    "in the last 24 hours": "在过去的 24 小时内",
    "chain has just reached": "连击刚刚触发了",
    "hit against": "撞到",
    "Electronics Stall": "电器摊位",
    "Music Stall": "音乐摊位",
    "Which market stall would you like to steal from?": "你想从哪个市场摊位偷东西？",
    "Computer Stall": "电脑摊位",
    "You grab the first pack of CDs you see and run your ass off.": "你拿起看到的第一包 CD 就跑掉了。",
    "You look back to see if anyone is chasing you and run straight home with the pack of music CDs!": "你回头看看有没有人追你，拿着一包音乐CD直奔回家！",
    "You walk down to the market place and begin browsing for the music stall. You see it and begin walking over to it.": "你走到市场，开始浏览音乐摊位。 你看到它，然后开始走向它。",
    "Which item would you like to steal from the Jewelry shop?": "你想从珠宝店偷哪件物品？",
    "Watch": "手表",
    "Ring": "戒指",
    "Stall": "摊位",
    "Necklace": "项链",
    "A police officer spots you and arrests you, you try to escape but the overpowering officer holds you to the ground.": "一名警察发现并逮捕了你，你试图逃跑，但强大的警察将你按在地上。",
    "You go over to the watch stand and begin browsing for a decent watch.": "你走到表架前，开始浏览一块像样的手表。",
    "You head down to the jewelry store and walk through the door.": "你低头走向珠宝店，走进门。",
    "You notice that the easiest watch to grab would be the plastic watch, you take it, and run!": "你注意到最容易抓住的手表是塑料手表，你拿着它就跑！",
    "happy": "幸福度",
    "Low Life": "低生命值",
    "Loan": "贷款",
    "Hospitalized by someone": "被某人打到住院",
    "Revenue Manager at the Casino": "堵场收益经理",
    "Bring a Friend": "邀请好友",
    "COPY TO CLIPBOARD": "复制到剪切板",
    "Days Donator Status": "捐助者身份天数",
    "Exit fullscreen": "退出全屏",
    "Feel free to use our banners in any form anywhere on the web. You can either download and host them independently, or use them directly\nfrom our servers. You'll need to add your referral URL link to them if you're not using the code supplied at the bottom.": "您可以在网络上的任何地方以任何形式随意使用我们的横幅广告。 您可以单独下载和托管它们，也可以直接从我们的服务器\n使用它们。 如果您不使用底部提供的代码，则需要将您的推荐 URL 链接添加到它们。",
    "Fit to screen": "适应屏幕",
    "Following code snippet includes your referral URL:": "以下代码段包含您的邀请链接：",
    "For every 10 levels gained by a player you've brought to the game, you'll receive...": "对于您带入游戏的玩家每升 10 级，您将获得...",
    "Here is the URL to your personal referral page. Anyone who signs up on a computer which has visited this page will be automatically referred by you.\nGive this to your friends and you will receive the great benefits below.": "这是您的个人推荐页面的 URL。 任何在访问过此页面的计算机上注册的人都将被您自动推荐。\n将此分享给您的朋友，您将获得以下巨大好处。",
    "Here we've provided some personalised dynamic signatures for you to use anywhere on the web. They'll display live statistics about your\nTorn account, and people who click them will be referred by you. They should make a great addition to any online forum signature or profile.": "在这里，我们提供了一些个性化的动态签名供您在网络上的任何地方使用。 它们将显示有关您的\nTorn 帐户的实时统计信息，点击它们的人将被您推荐。 他们应该成为任何在线论坛签名或个人资料的重要补充。",
    "HTML link (includes your referral URL):": "HTML 链接（包括您的推荐 URL）：",
    "If you're having trouble viewing some of the banners. Please disable your advert blocker and refresh this page.": "如果您在查看某些横幅时遇到问题。 请禁用您的广告拦截器并刷新此页面。",
    "Invite Your Friends": "邀请你的朋友",
    "Link copied!": "链接已复制！",
    "Please select a size and then a signature to generate code.": "请选择尺寸，然后选择签名以生成代码。",
    "Please select one of the userbars or signatures below to generate code.": "请选择以下用户栏或签名之一以生成代码。",
    "Preview Banner": "预览横幅",
    "Promote on Forums": "在论坛上推广",
    "Promote on Signatures": "在签名上推广",
    "Promote on Social Media": "在社交媒体上推广",
    "Promote on Your Website": "在您的网站上推广",
    "Real size view": "实际尺寸视图",
    "Share Torn on your social media feeds by clicking the buttons below. Adding some personal text about Torn to coax your friends in can make them far\nmore successful - perhaps asking them to train up so they can later join your faction or company. Anyone who signs up via your share will be referred by you.": "点击下面的按钮，在您的社交媒体上分享 Torn。 添加一些关于 Torn 的个人文字来吸引你的朋友加入可以让他们\n更加成功 - 也许要求他们接受培训以便他们以后可以加入你的派系或公司。 通过您的分享注册的任何人都将由您推荐。",
    "Social Butterfly": "社交蝴蝶",
    "Special Items": "特殊物品",
    "static": "静态",
    "Static banners (JPG)": "静态横幅 (JPG)",
    "Three's a Crowd": "三人成群",
    "Two's Company": "二人相伴",
    "Userbars & Forums Signatures": "用户栏和论坛签名",
    "We do not condone spamming of other forums / comment sections on the web with your referral link. However, there may be relevant places where\nyou're able to start active discussions about Torn or text based games in general. Many players have been very successful promoting Torn through\nthese channels by starting intelligent and interesting threads which include their referral links, but please be mindful of the rules set on\nthese websites.": "我们不容忍使用您的推荐链接向网络上的其他论坛/评论部分发送垃圾邮件。 但是，您可能会在相关的地方\n开始积极讨论 Torn 游戏或一般基于文本的游戏。 许多玩家通过启动包括他们的推荐链接在内的智能和有趣的线程，通过这些渠道\n成功地推广了 Torn，但请注意\n这些网站上设置的规则。",
    "You have not referred anyone to Torn": "您没有将 Torn 推荐给任何人",
    "Honors are unlocked by referring players that go on to reach level 10": "推荐玩家升到 10 级即可解锁荣誉",
    "Refer one friend to Torn (Uncommon)": "将一位朋友推荐给 Torn（不常见）",
    "Refer two friends to Torn (Limited)": "将两个朋友推荐给 Torn（有限）",
    "BBCode link (includes your referral URL):": "BBCode 链接（包括您的推荐 URL）：",
    "successfully busted you out of jail.": "功把你救出监狱。",
    "Defensive": "防御性",
    "Pack of Music CDs": "一包音乐 CD",
    "Medical": "医疗",
    "Viruses": "病毒",
    "Special": "特殊",
    "Secondary": "次要",
    "Sell this Item": "出售此物品",
    "Temporary": "临时",
    "Unequip this Item": "脱下此物品",
    "Plushies": "毛绒玩具",
    "Miscellaneous": "杂项",
    "Last message:": "最近消息：",
    "Flowers": "花",
    "Enhancer": "强化剂",
    "Energy Drink": "能量饮料",
    "Eat": "食物",
    "Electronics": "电子产品",
    "Drugs": "药品",
    "Collectibles": "收藏品",
    "Clothing": "服装",
    "Cars": "车",
    "Candy": "糖果",
    "Books": "书籍",
    "Boosters": "增强剂",
    "Armor": "护甲",
    "Artifacts": "神器",
    "Alcohol": "酒类",
    "Estate Agents": "房地产经纪人",
    "Player Committee": "玩家委员会",
    "Quick Links": "快捷链接",
    "Real Estate": "房地产",
    "Red-Light": "红灯",
    "Super Store": "超市",
    "Residential": "住宅",
    "Type": "类型",
    "West Side": "西边",
    "Shopping": "购物",
    "Points Market": "积分市场",
    "Popularity": "人气",
    "Post Office": "邮局",
    "Premier Fitness Gym": "顶级健身房",
    "Your Shack": "你的窝棚",
    "Application expires:": "申请到期：",
    "Leader:": "帮主:",
    "Co-leader:": "副帮主:",
    "Members:": "帮众:",
    "Best chain:": "最佳连击：",
    "Good": "好",
    "User List": "用户列表",
    "User Status Icons": "用户状态图标",
    "Search": "搜索",
    "Showing records 1 through 25": "显示 1 到 25 条记录",
    "No users found": "未找到用户",
    "APPLY TO THIS FACTION": "申请加入",
    "SMTH is a neutral faction but we like to make friends and will help who are friendly to us.": "SMTH 是一个中立的帮派，但我们喜欢交朋友，并且会帮助对我们友好的人。",
    "Territories:": "领土：",
    "Until you surrend.": "直到你投降。",
    "Treaties:": "协定：",
    "Champion": "冠军",
    "Scavenger": "拾荒者",
    "You are currently in hospital": "你目前在医院",
    "Easter Egg Hunt": "寻找复活节彩蛋",
    "Candy effects are tripled": "糖果效果增加3倍",
    "Attack other players to steal their dog tags and accrue enough points to be named the Dog Tag champion, with the strongest players holding the most valuable tags of all. Just make sure you keep hold of your own": "攻击其他玩家以窃取他们的狗牌并积累足够的积分以成为狗牌冠军，最强的玩家持有最有价值的牌。 只要确保你掌握自己的",
    "CaffeineCon 2023": "咖啡因大会 2023",
    "Cannabis effects are tripled": "天麻效果增加3倍",
    "Elimination": "消除",
    "Employee Appreciation Day": "员工感谢日",
    "Hospital times reduced by 75%": "住院时间减少 75%",
    "Hunting experience is increased by x5": "狩猎经验增加x5",
    "Increased awareness for one week": "意识提高一星期",
    "Life and cooldown penalties for drawing blood are halved": "抽血的生命值和冷却时间惩罚减半",
    "Love Juice reduces the energy cost of attacking & reviving": "爱心果汁减少攻击和恢复的能量消耗",
    "Museum Day": "博物馆日",
    "Slash Wednesday": "砍杀星期三",
    "St Patrick's Day": "圣帕特里克节",
    "Token Shop": "代币商店",
    "Torn Anniversary": "Torn周年纪念日",
    "Torn's very own festive theme park opens its doors to the public, with citizens able to scour both official and player-created maps to search for treasure and avoid traps!": "Torn 自己的节日主题公园向公众敞开大门，市民可以浏览官方和玩家创建的地图来寻找宝藏并避开陷阱！",
    "Torn's yearly dollar sale sees many bazaars listing goods for $1": "Torn 的年度美元促销活动让许多集市以 1 美元的价格列出商品",
    "Travel capacity doubled for flights leaving during this event": "在此活动期间离开的航班的旅行容量翻了一番",
    "Trick or Treat": "不给糖就捣蛋",
    "Twelve teams enter. One team survives. Be prepared to fight against friends and foes in this daily battle for survival which sees teams of 1,000 players eliminated one by one until a victor is crowned": "十二支队伍入场。 一个团队幸存下来。 准备好在这场每天的生存之战中与朋友和敌人作战，1000 名玩家组成的队伍被一一淘汰，直到获胜者加冕",
    "Weekend Road Trip": "周末公路旅行",
    "World Blood Donor Day": "世界献血者日",
    "World Diabetes Day": "世界糖尿病日",
    "World Population Day": "世界人口日",
    "World Tiger Day": "世界老虎日",
    "accept mission": "接受任务",
    "Anonymous": "匿名",
    "Are you sure you want to decline this mission?": "您确定要拒绝此任务吗？",
    "Are you sure you want to buy this item for": "您确定要购买此商品花费",
    "Available Rewards": "可用奖励",
    "Bonne journee": "再会",
    "BUY": "购买",
    "George": "乔治",
    "His nom de plume is The Duke, and whilst in his employ you shall find his tasks demeaning, disturbing, yet financially rewarding. He has three assignments ready for your special attention in this moment, and will provide regular engagements should you so desire. Deliver this gentleman from his concerns, and perhaps we shall converse on more substantial matters in future.": "他的笔名是 The Duke，在他任职期间，您会发现他的任务有辱人格、令人不安，但在经济上却很有回报。 此时此刻，他已准备好三项任务供您特别注意，如果您愿意，他会定期提供服务。 把这位先生从他的担忧中解脱出来，也许我们将来会谈更实质性的事情。",
    "Locked": "未解锁",
    "locked": "未解锁",
    "So, to my reason for our correspondence. I see quality in you, but first you must bring bread to the table before you may dine. I have dealings with a businessman, a financier for the poor, and he requires a mind such as yours. A problem solver allowing him to remain clean; at least, as clean as that filthy little man ever could be.": "所以，我的通信原因。 我看到了你的品质，但首先你必须先把面包端上桌，然后才能用餐。 我和一位商人打交道，他是一位为穷人服务的金融家，他需要像你这样的头脑。 一个问题解决者，让他保持干净； 至少，像那个肮脏的小男人一样干净。",
    "The following will be credited upon successful completion of the contract:": "成功完成合同后将记入以下款项：",
    "Who is allowed to initiate chat with you?": "谁可以发起与您的聊天？",
    "Traveling": "旅行中",
    "Room sound": "房间声音",
    "Private": "私密",
    "Only people you know or have met": "只有你认识或见过的人",
    "Jail & Hospital": "监狱 & 医院",
    "Competition": "竞赛",
    "PAY": "支付",
    "Heavy Metal CDs": "重金属 CD",
    "Horror DVDs": "恐怖片 DVD",
    "in the last week": "在上周",
    "job": "工作",
    "Rock CDs": "摇滚乐 CD",
    "Romance DVDs": "爱情片 DVD",
    "Sci Fi DVDs": "科幻片 DVD",
    "Thriller DVDs": "惊悚片 DVD",
    "You begin recording the horror DVDs you are going to sell at the local market.": "您开始录制准备在当地市场出售的恐怖 DVD。",
    "You buy a pack of recordable DVDs to rip the latest horror movie on to and hop on your PC.": "您购买了一包可刻录的 DVD，在你的 电脑 上将最新的恐怖电影进行翻录。",
    "You will have enough nerve in ": "你会有足够的勇气在 ",
    "You are currently taking an education course already. This course must be completed before you can start another.": "您目前已经在上教育课程。 必须先完成本课程，然后才能开始另一门课程。",
    "You are currently taking this course.": "您目前正在学习这门课程。",
    "You have started the": "您已经开始",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "January": "1月",
    "February": "2月",
    "March": "3月",
    "April": "4月",
    "May": "5月",
    "June": "6月",
    "July": "7月",
    "August": "8月",
    "September": "9月",
    "October": "10月",
    "November": "11月",
    "December": "12月",
    "Wed": "三",
    "Mon": "一",
    "Tue": "二",
    "Thu": "四",
    "Sun": "日",
    "Sat": "六",
    "Fri": "五",
    "": "",
    "#3 Inexperienced Nudist": "#3 经验不足的裸体主义者",

    //原样
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "                            ": "                            ",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "              ",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "\n": "\n",
    "You have logged on ": "你当前登录的用户名是 ",
    "Personal Perks ": "个人特权 ",
    "Someone mugged you and stole $": "有人抢劫了你并偷走了 $",
    "Outstanding loan of $": "未偿还的贷款 $",
    "Congratulations! You upgraded your level to ": "恭喜！ 你升级了你的等级到 ",
    "mugged you and stole $": "抢劫了你并偷走了 $",
    "with the message: ": "带有消息：",
    "Length: ": "时长: ",
    "Cost: $": "成本: $",
    "Tier: ": "阶段: ",
    "You search the train station from top to bottom and find $": "您从上到下搜索了火车站并找到 $",
    "You search under the old bridge and surprisingly find $": "你在旧桥下搜索，意外地找到了 $",
    "You search the bins and surprisingly find $": "你搜索了垃圾桶，意外地找到了 $",
    "You search in the dumpster and manage to find $": "你搜索了垃圾箱，并设法找到了 $",
    "You search the lucky water fountain find $": "你搜索了幸运喷泉，找到了 $",
    "Someone attacked and hospitalized you [": "有人袭击你并使你住院了 [",
    "Enabling full territory will download the map ": "启用全域将下载地图 ",
    "Increases maximum nerve by ": "提高勇气上限 ",
    "Type in your application below to send a request to the leadership of ": "在下面输入您的申请，向领导层发送请求 ",
    "Give some money to ": "送一点钱给 ",
    "Initiate a chat with ": "发起聊天 和 ",
    "Initiate a trade with ": "发起交易 和 ",
    "Place a bounty on ": "悬赏 ",
    "Introduction: ": "介绍：",
    "Width (": "宽度 (",
    "Height (": "高度 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\t": "\t",
    "\n                      \n                      ": "\n                      \n                      ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Congratulations! You have been promoted to Gaming Consultant!": "恭喜！ 您已晋升为菠菜顾问！",
    "You have enough working stats to be promoted to Marketing Manager!  It will cost": "您有足够的工作属性可以晋升为营销经理！ 这将花费",
    "Congratulations! You have been promoted to Marketing Manager!": "恭喜！ 您已晋升为营销经理！",
    "You have enough working stats to be promoted to Revenue Manager!  It will cost": "您有足够的工作属性可以晋升为收益经理！ 这将花费",
    "Congratulations! You have been promoted to Revenue Manager!": "恭喜！ 您已晋升为收益经理！",
    "Oh, Sorry. You are unable to be promoted at this time as you do not have the correct stats.": "噢，抱歉。 您目前无法晋升，因为您没有正确的属性。",
    "Ability to withdraw and deliver blood": "抽取和输送血液的能力",
    "Advanced Biochemistry": "高级生物化学",
    "Evolution": "进化",
    "Bachelor of Biology": "生物学学士",
    "Chromosomes and Gene Functions": "染色体和基因功能",
    "Forensic Science": "法医学",
    "Fundamentals of Neurobiology": "神经生物学基本原理",
    "Intermediate Biochemistry": "中级生物化学",
    "Intravenous Therapy": "静脉注射疗法",
    "Introduction to Biochemistry": "生物化学概论",
    "Anatomy": "解剖学",
    "'s Profile": " 的 个人资料",
    " has no items in their display cabinet": " 的陈列柜里没有任何物品",
    "s bazaar is closed": " 的集市已关闭",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^(.+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+) \- ([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^(.+) ([\d\.]+):([\d\.]+):([\d\.]+) \- ([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^([\d\.,]+) $/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^BI([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数���的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Patch list \#(.+)$/, '补丁列表 #$1'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) casino tokens and a current streak of$/, '您有 $1 堵场代币并且当前连续赢了'],
    [/^Welcome back! You've received (.+) special refills for your (.+) days of inactivity!$/, '欢迎回来！ 由于 $2 天不事件，您已收到 $1 次特别补充！'],
    [/^Your loan fees have increased by (.+) to a total of (.+). You can pay them by visiting the$/, '您的贷款费用增加了 $1，总计 $2。 您可以通过访问'],
    [/^You managed to complete (.+) minute in a beginners boxing session throwing (.+) punches$/, '您成功完成了 $1 分钟的初学者拳击训练，打出了 $2 拳'],
    [/^You managed to complete (.+) minutes in a beginners boxing session throwing (.+) punches$/, '您成功完成了 $1 分钟的初学者拳击训练，打出了 $2 拳'],
    [/^You managed to complete (.+) minute in a spinning class at resistance level: (.+)$/, '您成功完成了 $1 分钟的的动感单车课程，阻力级别是: $2'],
    [/^You managed to complete (.+) minutes in a spinning class at resistance level: (.+)$/, '您成功完成了 $1 分钟的的动感单车课程，阻力级别是: $2'],
    [/^You managed to complete (.+) move in a yoga class at level (.+) difficulty$/, '您在 $2 级难度的瑜伽课程中成功完成了 $1 个动作'],
    [/^You managed to complete (.+) bicep curls using the (.+) dumbbells$/, '您成功地使用 $1 的哑铃完成了 $2 个二头肌弯举'],
    [/^You were sent (.+)x Small First Aid Kit from$/, '您收到了 $1x 小型急救箱 来自'],
    [/^has been rewarded to (.+) lucky citizens when Real Madrid won in the$/, '皇马夺冠已奖励 $1 位幸运市民'],
    [/^You need (.+) to start this course. You only have (.+).$/, '您需要 $1 才能开始这门课程。 你当前只有 $2。'],
    [/^You scrounge around the movie theatre and find a total of (.+) under the seats!$/, '你在电影院里四处寻找，发现座位下面总共有 $1！'],
    [/^Your application for  (.+) has been updated.$/, '您的 $1 申请已更新。'],
    [/^Add (.+) to your friend list$/, '添加 $1 到你的 好友 列表'],
    [/^Add (.+) to your enemy list$/, '添加 $1 到你的 敌人 列表'],
    [/^You were sent (.+) from$/, '你获得了 $1 来自'],
    [/^View (.+)\'s personal statistics$/, '查看 $1 的个人统计'],
    [/^Send (.+) a message$/, '给 $1 发消息'],
    [/^Torn turns (.+) years old$/, 'Torn 年满 $1 岁'],
    [/^Report (.+) to staff$/, '举报 $1 给官方人员'],
    [/^Bonjour Monsieur (.+), I have been watching you for some time now; the way you carry yourself, the methods you employ, the \"activities\" you engage yourself with. You have a little of the je ne sais quoi about you, a sense of elan one rarely observes in those beating an opponent into a fine pulp. For this reason...you intrigue me.\nI myself abhor conflict, for I am a peaceful man in a vicious world, an orchid floating behind the violent might of a tidal wave. I involve myself in, how you say, quasi-moralistic endeavours, solely as a means of entertainment. I have no need of reward, no desire for bourgeois materialistic gain. For me, this is merely sport, albeit a sport I am deeply enchanted with.$/, '早上好 $1，我已经关注你一段时间了； 你的行为方式，你使用的方法，你参与的“活动”。 你有一点je ne sais quoi，一种在将对手打得精疲力尽的人中很少观察到的活力。 出于这个原因……你激起了我的兴趣。\n我自己厌恶冲突，因为我是一个邪恶世界中的和平人，一朵漂浮在狂暴浪潮后面的兰花。 我参与，你怎么说，准道德的努力，只是作为一种娱乐方式。 我不需要报酬，也不需要资产阶级的物质利益。 对我来说，这只是一项运动，尽管是一项让我深深着迷的运动。'],
    [/^You gained (.+) strength$/, '你获得了 $1 力量'],
    [/^You gained (.+) speed$/, '你获得了 $1 速度'],
    [/^You gained (.+) dexterity$/, '你获得了 $1 敏捷'],
    [/^You gained (.+) defense$/, '你获得了 $1 防御'],
    [/^has put a bounty on you with a (.+) reward. This cost has been added to your fees.$/, '已悬赏 $1 给您。 此费用已添加到您的费用中。'],
    [/^\$(.+) per day$/, '\$ $1 每天'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You manage to sell (.+) earning you (.+)!$/, '您成功卖出了 $1，赚取 $2！'],
    [/^Gain ([\d\.,]+) endurance upon completion$/, '完成时获得 $1 耐力'],
    [/^Gain ([\d\.,]+) intelligence upon completion$/, '完成时获得 $1 智力'],
    [/^Gain ([\d\.,]+) manual labor upon completion$/, '完成时获得 $1 体力劳动'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) hours, ([\d\.]+) minutes and ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $2 秒'],
    [/^([\d\.]+) days, ([\d\.]+) hours and ([\d\.]+) minutes$/, '$1 天 $2 小时 $2 分钟'],
    [/^([\d\.]+) minutes and ([\d\.]+) seconds$/, '$1 分钟 $2 秒'],
    [/^Decrease an opponent's stealthiness by ([\d\.]+)$/, '降低对手的隐蔽性 $1'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+ ([\d\.]+)\% damage$/, '+$1% 伤害'],
    [/^\-([\d\.]+) Nerve$/, '-$1 勇气'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) casino points \& (.+)$/, '$1 堵场积分 和 $2'],
    [/^([\d\.,]+) casino point$/, '$1 堵场积分'],
    [/^([\d\.,]+) casino tokens$/, '$1 堵场代币'],
    [/^([\d\.,]+) minutes ago$/, '$1 分钟前'],
    [/^([\d\.,]+) Mission credits$/, '$1 任务分'],
    [/^([\d\.,]+) Mission credits\?$/, '$1 任务分?'],
    [/^([\d\.,]+) Day$/, '$1 天'],
    [/^([\d\.,]+) likes$/, '$1 赞'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^([\d\.,]+) days$/, '$1 天'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                            transTaskMgr.doTask();
                        }
                    }
                }
            }
        }
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();