// ==UserScript==
// @name         Trade Craft 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.1
// @description  网页游戏 Trade Craft (https://www.xxxxx.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Trade Craft.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://www.zed.city/icons/favicon.svg
// @license      MIT
// @include      *https://playtradecraft.com*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/trade-craft-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/trade-craft-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/11/13 14:43
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Sell what you produce in the market or trade purely by buying from the market and reselling without producing. With limit/market orders and a live order book, prices move constantly.": "在市场上出售你生产的东西，或者纯粹从市场上购买，然后不生产就转售。有了限价/市价订单和实时订单簿，价格就会不断变动。",
    "Learn More": "了解更多",
    "Go to Game": "前往游戏",
    "Features": "功能",
    "English": "英语",
    "Play Now": "立即开玩",
    "Play Free": "免费开玩",
    "Sign In": "登录",
    "Sign In / Register": "登录 / 注册",
    "Boost capacity, cut costs, reduce carbon; borrow and complete quests.": "提高产能，降低成本，减少碳排放；借还贷款并完成任务。",
    "Build farms, mines and factories": "建造农场、矿山和工厂",
    "Build Your Production Empire": "建立你的生产帝国",
    "Carbon, credit, quests & research": "碳，信用，任务和研究",
    "Copyright © 2025 TradeCraft | Business and Trade Simulation Game": "Copyright © 2025 TradeCraft | Business and Trade Simulation Game",
    "Daily Output": "日产量",
    "Deep economy with realistic supply chains, dynamic markets, credit and research systems.": "深层经济，有现实的供应链、动态的市场、信用和研究体系。",
    "Dynamic Market & Orders": "动态市场与订单",
    "In-Game Screenshots": "游戏截图",
    "Limit & market orders; depth and fee by execution": "限价和市价订单；深度和执行费用",
    "Limit/market orders, NPC demand and player competition constantly move prices.": "限价/市场订单、NPC需求和玩家竞争不断影响价格。",
    "live": "实时",
    "Live market with NPC & player orders": "实时市场与NPC和玩家的订单",
    "Manage raw flows from farm to factory; handle by-products and bottlenecks.": "管理从农场到工厂的原始流程；处理副产品和瓶颈。",
    "Market & Trading": "市场与交易",
    "Market Cap": "市值",
    "Privacy": "隐私",
    "Production → inventory → sales loop": "生产→库存→销售循环",
    "Pure buy–sell trading for profit": "纯粹为了盈利的买卖交易",
    "Realistic Production Chains": "逼真的生产链",
    "Research, Quests, Credit": "研究，任务，荣誉",
    "See how your production empire looks in action, from farms to factories.": "看看你的生产帝国是如何运作的，从农场到工厂。",
    "Terms of Service": "服务条款",
    "TradeCraft": "贸易工艺",
    "Türkçe": "土耳其语",
    "units": "单位",
    "Already have an account?": "已经有账户了吗？",
    "Build your economy, scale production, manage markets.": "建立你的经济，规模化生产，管理市场。",
    "Company Name": "公司名称",
    "Create Account": "创建账户",
    "Dynamic markets & orders": "动态市场和订单",
    "Email": "电子邮件",
    "Join us and build your production empire!": "加入我们，建立您的生产帝国！",
    "No account?": "没有帐户?",
    "Password": "密码",
    "Privacy Policy": "隐私政策",
    "Quests, credit system, carbon footprint": "任务，信用系统，碳足迹",
    "Realistic production chains": "真实的生产链",
    "Sign in": "登录",
    "Sign in with Google": "使用谷歌登录",
    "Sign up": "注册",
    "Sign Up": "注册",
    "Success": "成功",
    "Registration successful!": "注册成功！",
    "OK": "确定",
    "Creating account...": "正在创建账号...",
    "Invalid email or password": "无效的邮箱或密码",
    "Signing in...": "登录中...",
    "Warning": "警告",
    "This company name is already taken": "这个公司名已存在",
    "/h": "/小时",
    "‹ Previous": "‹ 向前",
    "Egg": "鸡蛋",
    "XP": "经验值",
    "Working": "工作中",
    "Wool": "羊毛",
    "Start / Stop": "开始 / 停止",
    "Log": "日志",
    "Log Out": "登出",
    "LIMIT": "上限",
    "Lettuce": "生菜",
    "Lettuce Seed": "生菜种子",
    "Lemon": "柠檬",
    "Glass": "玻璃",
    "Grape": "葡萄",
    "Gold": "黄金",
    "Flour": "面粉",
    "Day (Max:7)": "天数 (最大:7)",
    "Day": "天",
    "Date": "日期",
    "None": "无",
    "Apple": "苹果",
    "Apple Juice": "苹果汁",
    "BUY": "购买",
    "Butter": "黄油",
    "Bread": "面包",
    "Bottle": "瓶子",
    "Active": "活跃",
    "Average:": "平均:",
    "Cheese": "奶酪",
    "City": "城市",
    "Coal": "煤",
    "Close": "关闭",
    "Clear": "清除",
    "Claim Daily Reward": "领取每日奖励",
    "Copper": "铜",
    "Copper Wire": "铜线",
    "Corn": "玉米",
    "Corn Seed": "玉米种子",
    "Cotton Seed": "棉花种子",
    "Cotton": "棉花",
    "Enable In-Game Music": "启用游戏音乐",
    "Enable In-Game sound effects": "启用游戏音效",
    "Enable Sounds": "启用声音",
    "Energy Cost": "能源成本",
    "Factory": "工厂",
    "Farm": "农场",
    "Fertilizer": "肥料",
    "Game Language Selection": "选择游戏语言",
    "Help Center": "帮助中心",
    "Input": "输入",
    "Honey": "蜂蜜",
    "Hourly Production": "小时生产",
    "Iron Ore": "铁矿石",
    "Inventory": "库存",
    "Last day:": "最近一天:",
    "Limit $": "上限 $",
    "Language": "语言",
    "Leather": "皮革",
    "Max": "最大",
    "Meat": "肉",
    "Market Quick View": "市场快速预览",
    "Market Orders": "市场订单",
    "Market Value": "市场价值",
    "MARKET": "市场",
    "Next ›": "向后 ›",
    "New Password": "新密码",
    "Notebook": "笔记本",
    "No records": "无记录",
    "Notifications": "通知",
    "Orange": "橙子",
    "Orange Juice": "橙汁",
    "Pay": "支付",
    "Pencil": "铅笔",
    "Player": "玩家",
    "Please wait": "请稍后",
    "Price Mode": "价格模式",
    "Price": "价格",
    "Processing…": "处理中",
    "Product": "产品",
    "Rice": "大米",
    "Rice Seed": "大米种子",
    "Wheat Seed": "小麦种子",
    "SELL": "出售",
    "Sheep": "羊",
    "Tree": "树",
    "Wallet": "钱包",
    "Wheat": "小麦",
    "Withdraw": "提现",
    "Tasks": "任务",
    "Task / Suggestion": "任务 / 建议",
    "T-shirt": "T恤衫",
    "Sugar": "糖",
    "🏭 Depot Inventory": "🏭仓库库存",
    "📦 Transfer to Main Storage": "📦转移到主存储器",
    "5-Day Forecast": "五日天气预报",
    "All current quantities of all products in the warehouse:": "仓库内所有产品的当前所有数量：",
    "All Effects": "所有影响",
    "All Land Types": "所有土地类型",
    "All Products": "所有产品",
    "All Regions": "所有地区",
    "Animations": "动画",
    "Asset": "资产",
    "Aurelia": "奥瑞利亚",
    "Auto Raw Material": "自动原料",
    "Badges": "徽章",
    "Barley": "大麦",
    "Barley Seed": "大麦种子",
    "Beeswax": "蜂蜡",
    "Bottle": "瓶子",
    "Broiler": "肉鸡",
    "By-products": "副产品",
    "Cancel": "取消",
    "Carbon": "碳",
    "Carbon Emission": "碳排放",
    "Cardboard": "纸板",
    "Cash": "现金",
    "Cash Flow": "现金流",
    "Caviar": "鱼子酱",
    "Cement": "水泥",
    "Change Password": "更改密码",
    "Change your current user password": "更改当前用户密码",
    "Cheddar Cheese": "切达干酪",
    "Cherry": "樱桃",
    "Chicken": "鸡",
    "Chocolate": "巧克力",
    "Choose Avatar": "选择头像",
    "Circuit": "电路",
    "Cocoa": "可可",
    "Computer": "计算机",
    "Configure": "配置",
    "Corn Chips": "玉米片",
    "Corn Silage": "玉米青贮",
    "Cow": "牛",
    "Crude Oil": "原油",
    "Current Avatar": "当前头像",
    "Current Password": "当前密码",
    "Daily Expenses": "日常支出",
    "Daily Production": "日常生产",
    "Daily Profit Board": "每日利润表",
    "Daily reward is ready. Collect it!": "每日奖励准备好了。收集它!",
    "Demolish": "拆除",
    "Depot": "仓库",
    "Do not show again": "不再显示",
    "Equinox": "伊奎诺克斯",
    "Fabric": "布料",
    "French Fries": "炸薯条",
    "Fried Chicken": "炸鸡",
    "Fruit Concentrate": "浓缩水果",
    "Furniture": "家具",
    "Glue": "胶水",
    "Graphite": "石墨",
    "Green Bean Seed": "青豆种子",
    "Green Beans": "青豆",
    "Hamburger": "汉堡",
    "Hello player! We'll take you on a short tour to show the basics: buying land, starting production, handling orders, the marketplace, and the credit system...": "你好，玩家！我们将带您进行一次简短的旅行，向您展示基础知识：购买土地，开始生产，处理订单，市场和信用体系……",
    "Interface loading…": "界面加载中…",
    "Iron Profile": "铁型材",
    "Kestrel": "凯斯特雷尔",
    "Lab/Tick:": "实验室/Tick：",
    "Land Configuring...": "土地配置中…",
    "Land Type": "土地类型",
    "Lemonade": "柠檬水",
    "Lithium": "锂",
    "Lithium Battery": "锂电池",
    "Loading…": "加载中...",
    "Lumber": "木材",
    "Microchip": "微芯片",
    "Milk": "牛奶",
    "Mine": "矿洞",
    "Missing: All — Affected: All tile": "缺失：全部-影响：全部贴图",
    "Missing: undefined — Affected: undefined tile": "缺失：未定义-影响：未定义瓷砖",
    "My Inventory": "我的库存",
    "My Orders": "我的订单",
    "Nail": "钉子",
    "Net Worth": "净资产",
    "New here? There's a farming gap in Africa — start with low costs.": "新来的？非洲存在农业缺口——从低成本开始。",
    "Nickel": "镍",
    "Nordheim": "诺德海姆",
    "Olive": "橄榄",
    "Olive Oil": "橄榄油",
    "Onion": "洋葱",
    "Onion Seed": "洋葱种子",
    "Open Loans": "公开贷款",
    "Order": "订单",
    "Pants": "裤子",
    "Paper": "纸",
    "Pasta": "意大利面",
    "Performance": "性能",
    "Plastic": "塑料",
    "Potato": "土豆",
    "Potato Chips": "薯片",
    "Precipitation": "降水",
    "Preparing resources": "准备资源",
    "Product Guide": "产品指南",
    "Production Graph": "生产图",
    "Production Increase": "生产增加",
    "Production issue: No Main Depot": "生产问题：没有主仓库",
    "Production Scheme": "生产计划",
    "Production Setting": "生产设置",
    "Profit": "利润",
    "Quantity": "数量",
    "Quartz Sand": "石英砂",
    "Refresh": "刷新",
    "Repay Loan": "偿还贷款",
    "Research Laboratory": "研究实验室",
    "RP:": "rp：",
    "Sand": "沙子",
    "Scoreboard": "记分板",
    "Seed Potato": "种子土豆",
    "Select a topic from the left.": "从左侧选择一个主题。",
    "Select Land Type": "选择土地类型",
    "Select the avatar that will appear on your profile.": "选择将出现在您的个人资料中的头像。",
    "Selected Product": "选择产品",
    "Shirt": "衬衫",
    "Shoes": "鞋子",
    "Show:": "显示:",
    "Smartphone": "智能手机",
    "Sneakers": "运动鞋",
    "Soap": "肥皂",
    "Soft Drink": "软饮",
    "Soybean": "大豆",
    "Soybean Seed": "大豆种子",
    "Starch": "淀粉",
    "Status": "状态",
    "Steel": "钢",
    "Stock": "股票",
    "Storage Capacity": "存储容量",
    "Storage Usage": "存储使用情况",
    "Straw": "稻草",
    "Strawberry": "草莓",
    "Strawberry Seed": "草莓种子",
    "Sugar Beet": "甜菜",
    "Sugar Beet Seed": "甜菜种子",
    "Sugarcane": "甘蔗",
    "Sugarcane Seedling": "甘蔗幼苗",
    "Sunflower": "向日葵",
    "Sunflower Oil": "向日葵油",
    "Sunflower Seed": "向日葵的种子",
    "Sylvania": "西尔瓦尼亚",
    "Take Loan": "贷款",
    "Target amount:": "目标金额:",
    "Temperature": "温度",
    "This name will appear as your in-game company.": "此名称将显示为您在游戏中的公司。",
    "Tile Bilgisi": "瓷砖Bilgisi",
    "Title": "称号",
    "Total Assets": "总资产",
    "Transfer": "转移",
    "Transfer Amount": "转移金额",
    "Transfer to Main Storage": "转移到主仓库",
    "Trout": "鳟鱼",
    "Turkish": "土耳其",
    "Turn On Music": "打开音乐",
    "Turnover": "营业额",
    "Type": "类型",
    "Update Password": "更新密码",
    "Üretimi Durdur": "Uretimi Durdur",
    "Value increase/decrease micro animation": "值增加/减少微动画",
    "Vesperia": "维斯特利亚",
    "Volatility:": "波动性：",
    "Walnut": "核桃",
    "Water Saving": "节约用水",
    "Welcome to TradeCraft!": "欢迎来到 贸易工艺！",
    "When this product operates, the following by-products are produced as bonuses.": "当此产品运行时，下列副产品将作为奖励产生。",
    "Yarn": "纱线",
    "You can set a separate price mode and limit for each input below. If the checkbox is “Active”, the rule on that row is enabled.": "您可以为下面的每个输入设置单独的价格模式和限制。如果复选框是“活动的”，则启用该行中的规则。",
    "For example, you can process the wheat you produce on your wheat farm into flour at a flour factory. Then, process that flour in a bakery to produce bread. Explore the production chain and create more valuable products!": "例如，你可以在面粉厂把你在小麦农场生产的小麦加工成面粉。然后，在面包店加工面粉来制作面包。探索生产链，创造更有价值的产品！",
    "From taking your first loan, to starting your first production, making your first sale, and setting up auto-trade rules — complete each mission to both learn the system and earn rewards.": "从获得你的第一笔贷款，到开始你的第一次生产，第一次销售，以及设置自动交易规则-完成每个任务来学习系统并获得奖励。",
    "Welcome": "欢迎",
    "Depo": "存款",
    "As you complete missions, new ones will unlock, allowing you to explore the world of TradeCraft step by step!": "当你完成任务时，新的任务将被解锁，让你一步一步地探索 贸易工艺 的世界！",
    "As you produce goods, carbon emissions are released into the environment.": "当你生产商品时，碳排放被释放到环境中。",
    "Buy and sell products on the market, place limit orders, and keep your inventory balanced using auto-buy rules.": "在市场上买卖产品，下限价订单，并使用自动购买规则保持库存平衡。",
    "Carbon Emissions and Environmental Impact": "碳排放和环境影响",
    "Choose your first plot of land and decide, will you build a farm or start a mine?": "选择你的第一块土地并决定，你将建立一个农场还是开始一个矿山？",
    "City Sales and Customer Demand": "城市销售和客户需求",
    "Customers in the city have demand for specific products. Keep an eye on these demands, stock popular goods, and boost your sales!": "城市里的顾客对特定的产品有需求。密切关注这些需求，储备热门商品，提高销量！",
    "Enable in-game sound effects": "启用游戏音效",
    "Factories, mines, and transportation increase this effect — players with high emission levels may face penalties in the future.": "工厂、矿山和交通运输增加了这种影响——高排放水平的参与者可能在未来面临惩罚。",
    "If you build your store in the right place, your products will sell like hotcakes!": "如果你把你的商店建在正确的地方，你的产品会像热饼一样畅销！",
    "In the world of TradeCraft, some products are raw materials for others!": "在贸易技术的世界里，有些产品是其他产品的原材料！",
    "In TradeCraft, you don’t just produce raw materials — you can also open markets, fast-food restaurants, or stores in city centers to sell directly to customers.": "在《贸易工艺》中，你不只是生产原材料，你还可以在城市中心开设市场、快餐店或商店，直接向客户销售。",
    "It’s Time to Begin!": "是时候开始了！",
    "Lands and Production": "土地与生产",
    "Market & Orders": "市场与订单",
    "Missions and Rewards": "任务和奖励",
    "Missions are ready to guide you through the game!": "任务已经准备好引导你完成游戏！",
    "Need Some Help?": "需要帮助吗？",
    "Production Chain and Processing Facilities": "生产链和加工设施",
    "Purchase empty land from the map, build a farm, mine, or factory, and choose your product. Use start/stop to control production.": "从地图上购买空地，建造农场、矿山或工厂，并选择你的产品。使用启动/停止控制生产。",
    "Remember, each region has its own unique resources and advantages. Define your strategy and claim your place in the world of trade!": "记住，每个地区都有自己独特的资源和优势。确定您的策略，并在贸易世界中占有一席之地！",
    "Remember, sustainable production is important not only for the planet but also for your business!": "请记住，可持续生产不仅对地球很重要，对您的业务也很重要！",
    "Remember: the help system never leaves you alone!": "记住：帮助系统永远不会离开你！",
    "Remember: those who build their production chains wisely stand out in the market!": "记住：那些明智地建立生产链的人在市场上脱颖而出！",
    "There are 6 different regions waiting for you in the world of TradeCraft.": "在《贸易工艺》的世界里有6个不同的区域等着你。",
    "There, you’ll find useful guides on everything from production and market orders to missions and carbon emissions.": "在那里，你会发现从生产和市场订单到任务和碳排放的一切有用的指南。",
    "We wish you success, good luck and have fun!": "我们祝你成功，好运，玩得开心！",
    "Whenever you get stuck in the game, click the Help button in the top-left corner to open the help window.": "当你在游戏中卡住时，点击左上角的帮助按钮打开帮助窗口。",
    "Successful": "成功",
    "You have no land in this region": "你在这片地区没有土地",
    "Daily reward has already been collected today.": "今日已领取过每日奖励。",
    "Operation Failed": "操作失败",
    "The market is active. Try switching to a new product to diversify.": "市场很活跃。试着换一种新产品来实现多样化。",
    "Price Mode:": "价格模式:",
    "wheat": "小麦",
    "Your": "你的",
    "X axis (time):": "X 轴 (时间):",
    "Y axis (price):": "Y 轴 (价格):",
    "Water (💧):": "水 (💧):",
    "Water": "水",
    "Wallet:": "钱包:",
    "Wallet (last day):": "钱包 (最近一天):",
    "Type:": "类型:",
    "type and status": "类型和状态",
    "Type & Status:": "类型 & 状态:",
    "Trader": "商人",
    "Tomorrow": "明天",
    "Top bar:": "顶部栏:",
    "Tips": "提示",
    "Storm": "风暴",
    "Stop:": "停止:",
    "status,": "状态,",
    "status.": "状态.",
    "Start/Upgrade": "开始/升级",
    "Sold:": "出售:",
    "start": "开始",
    "Start Production": "开始生产",
    "Seeds": "种子",
    "Save:": "保存:",
    "Rewards": "奖励",
    "Region": "地区",
    "Red": "红色",
    "red": "红色",
    "products": "产品",
    "Price:": "价格:",
    "panel.": "面板.",
    "or": "或者",
    "no tax": "无税",
    "Missions": "任务",
    "Missing": "缺失",
    "mining:": "采矿:",
    "mine": "矿山",
    "MINE": "矿山",
    "Market Sell:": "市场出售:",
    "Market:": "市场:",
    "Market Order": "市场订单",
    "Market Orders Screen": "市场订单屏幕",
    "market orders": "市场订单",
    "MARKET Order:": "市场订单:",
    "Market Order:": "市场订单:",
    "locked": "未解锁",
    "Confirm": "确认",
    "Reward could not be received": "无法领取奖励",
    "to purchase land. Do you confirm?": "购买土地。你确定吗？",
    "Yes, buy": "是的, 购买",
    "You are about to spend": "你将要花费",
    "Before you can start producing, you need to build a depot. It’s where all your goods will be safely stored.": "在你开始生产之前，你需要建造一个仓库。你所有的货物都会安全地存放在那里。",
    "Build a factory and make it operational. Factories process raw materials into valuable products.": "建造一座工厂，让它运转起来。工厂把原材料加工成有价值的产品。",
    "Build a Wheat Farm!": "建造一个小麦农场！",
    "Build Your First Depot!": "建立你的第一个仓库！",
    "Build Your First Market!": "建立你的第一个市场！",
    "Complete a Research Project": "完成一项研究项目",
    "Contribute to a Global Mission": "为全球使命做出贡献",
    "Enter at least one limit buy order in the market. Limit orders let you buy at your desired price.": "在市场上输入至少一个限价买单。限价订单让你以你想要的价格买入。",
    "Enter at least one limit sell order on the market. This is how you start trading with other players.": "在市场上输入至少一个限价卖单。这是你开始与其他玩家交易的方式。",
    "Expand your production, grow your wealth, and reach a quarter million in total assets.": "扩大你的生产，增加你的财富，总资产达到25万。",
    "Increase your cash and inventory value above $50,000 to show solid financial growth.": "将你的现金和存货价值增加到5万美元以上，以显示稳健的财务增长。",
    "Let your farm run and produce at least 100 kilograms of wheat. Keep an eye on your production stats!": "让你的农场运转起来，至少生产100公斤小麦。密切关注你的生产统计数据！",
    "Locked": "未解锁",
    "Make Your First City Sale": "完成你的第一次城市销售",
    "Move your produced wheat into the main storage. Storing goods is the first step before selling or processing.": "把你生产的小麦移到主仓库。储存货物是销售或加工前的第一步。",
    "offered": "提供",
    "Open the research lab, start a research, and finish it. Technology makes your company more efficient!": "打开研究实验室，开始一项研究，然后完成它。科技让你的公司更有效率！",
    "Participate in a global mission to support the community and earn unique rewards.": "参与全球任务，支持社区，获得独特的奖励。",
    "Place Your First Buy Order": "下你的第一个购买订单",
    "Place Your First Sell Order": "下你的第一个销售订单",
    "Repay part of your borrowed money. Maintaining credit reputation is key to long-term success.": "还一部分你借的钱。保持信誉是长期成功的关键。",
    "Repay Your Loan": "偿还贷款",
    "Run Your First Factory": "经营你的第一家工厂",
    "Sell your first batch of goods at your city market. Real trade begins now!": "在城市市场上销售你的第一批货物。真正的贸易从现在开始！",
    "Set Up Auto Raw Material Purchase": "设置原材料自动购买",
    "Start your first real production by building a wheat farm on an empty plot. Wheat is the foundation of your economy.": "在一块空地上建造一个小麦农场，开始你的第一个真正的生产。小麦是你们经济的基础。",
    "Take Mission": "接受任务",
    "Take Out a Loan": "申请贷款",
    "Time to complete your production chain. Build a city market to sell your goods directly.": "是时候完成你的生产链了。建立一个城市市场，直接销售你的商品。",
    "To keep production running smoothly, create at least one AutoTrade rule. This automates raw material buying.": "为了保证生产的顺利运行，至少创建一条自动交易规则。这使原材料采购自动化。",
    "Transfer 100 Kg of Wheat to Main Storage": "将100公斤小麦转移到主仓库",
    "Use the loan system to strengthen your capital. Smart borrowing can accelerate your expansion.": "利用贷款系统来增强你的资本。明智的借贷可以加速你的扩张。",
    "active": "活跃",
    "Big Storage Depot": "大型仓库",
    "Claim Reward": "领取奖励",
    "Click on an empty plot to build your first depot!": "点击一个空的地块，建立你的第一个仓库！",
    "Empty": "空",
    "Mission could not be taken": "任务无法接取",
    "Mission taken": "执行任务",
    "Product selection changed — Not effective until saved": "产品选择已更改-保存前不生效",
    "Required (at least one)": "必填（至少一个）",
    "Select Product": "选择产品",
    "Small Storage Depot": "小型仓库",
    "You already have an active mission.": "你已经有了一个正在执行的任务。",
    "• Product setup/change:": "• 产品设置/更改：",
    "Approve": "批准",
    "claimed": "已领取",
    "Confirm Configuration": "确认配置",
    "Land configured": "已配置土地",
    "piece": "件",
    "Reward claimed": "奖励已领取",
    "Stopped": "已停止",
    "The amount will be deducted from the treasury upon confirmation.": "该金额将于确认后从国库扣除。",
    "Total:": "总计：",
    "Market": "市场价",
    "Limit": "限价",
    "• Land type setup:": "•土地类型设置：",
    "Auto-buy rules updated": "已更新自动购买规则",
    "Missing: Wheat Seed, Fertilizer — Affected: 1 tile": "缺失：小麦种子，肥料 - 影响：1 地块",
    "Net Effect (per 1 unit):": "净效果（每1个单位）：",
    "No active production on this land": "该地块暂无生产活动",
    "Wheat Seed:": "小麦种子:",
    "🎯 Mission Completed!": "🎯 任务已完成!",
    "Expenses could not be loaded.": "费用无法负担。",
    "Server unreachable": "服务器无法访问",
    "The mission \"Build a Wheat Farm!\"": "任务\“建造一个小麦农场！”",
    "Build a Wheat Farm!": "建造一个小麦农场！",
    "Set Up Auto Raw Material Purchase": "设置自动购买原材料",
    "No Main Depot": "没有主仓库",
    "Required": "必选",
    "Stop": "停止",
    "Stopping": "停止中",
    "The mission \"Set Up Auto Raw Material Purchase\"": "任务“设置自动原材料购买”",
    "Running": "运行中",
    "Run": "运行",
    "Idle": "空闲",
    "Help": "帮助",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "kg(s)": "kg",
    "G8hh": "G8hh",
    "Credit": "信贷",
    "kg": "kg",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "‹": "‹",
    "›": "›",
    "✕": "✕",
    "•": "•",
    "#": "#",
    "×": "×",
    "▼": "▼",
    "▾": "▾",
    "⚡": "⚡",
    "—": "—",
    ".. · ..": ".. · ..",
    ".. — ..": ".. — ..",
    "💧": "💧",
    "v—": "v—",
    "undefined": "undefined",
    "Yık": "Yık",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "~ $": "~ $",
    "⚡ $": "⚡ $",
    "💧 $": "💧 $",
    "SELL • ": "出售 • ",
    "BUY • ": "购买 • ",
    "Demand: ": "需求: ",
    "Active: ": "活跃: ",
    "Page ": "页码 ",
    "Reach Total Assets of $": "总资产达到 $",
    "EMPTY : ": "空 : ",
    "Production issue: ": "生产问题：",
    "Regions: ": "地区：",
    "FARM : ": "农场 : ",
    "Area #": "区域 #",
    "Mission completed: ": "任务已完成: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " (last N days)": " (最近 N 天)",
    " (last day)": " (最近天数)",
    " (all regions)": " (全部地区)",
    " (all)": " (全部)",
    " (Repeat)": " (重复)",
    " — Spring": " — 春季",
    "°C · Partly": "°C · 部分",
    " (blue)": " (蓝色)",
    " (N Days):": " (N 天):",
    " (missing)": " (缺失)",
    " kg(s))": " kg)",
    " has been completed — you can now claim your reward!": " 已完成 - 你现在可以领取你的奖励了！",
    " • FARM — Working": " • 农场 — 工作中",
    ". Claim your reward!": ". 领取你的奖励!",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)kg$/,
    /^([\d\.]+),([\d\.]+)kg$/,
    /^([\d\.]+) kg$/,
    /^([\d\.]+) kg\(s\)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(\+ ([\d\.]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+) \/ ([\d\.,]+) kg\(s\)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Produce (.+) Kg of Wheat$/, '生产 $1 Kg 小麦'],
    [/^Total: (.+) \| Completed: (.+)\n(.+)\| New offer ready$/, '总计：$1 | 已完成：$2\n$3| 新报价准备就绪'],
    [/^Total: (.+) \| Completed: (.+)\n(.+)\| Active:$/, '总计：$1 | 已完成：$2\n$3| 活跃:'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) XP$/, '$1 经验值'],
    [/^([\d\.]+)s ago$/, '$1 秒前'],
    [/^([\d\.]+)min ago$/, '$1 分钟前'],
    [/^([\d\.]+)h ago$/, '$1 小时前'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Last ([\d\.,]+) Days$/, '最近 $1 天'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) kg\(s\) • (.+)$/, '$1 kg • $2'],
    [/^(.+) L\(s\) • (.+)$/, '$1 L • $2'],
    [/^(.+) lt\(s\) • (.+)$/, '$1 lt • $2'],
    [/^(.+) piece\(s\) • (.+)$/, '$1 片 • $2'],
    [/^(.+) pair\(s\) • (.+)$/, '$1 对 • $2'],
    [/^(.+) ton\(s\) • (.+)$/, '$1 吨 • $2'],
    [/^(.+) meter\(s\) • (.+)$/, '$1 米 • $2'],
    [/^(.+) spool\(s\) • (.+)$/, '$1 卷 • $2'],
    [/^(.+) pack\(s\) • (.+)$/, '$1 包 • $2'],
    [/^(.+) ounce\(s\) • (.+)$/, '$1 盎司 • $2'],
    [/^(.+) barrel\(s\) • (.+)$/, '$1 桶 • $2'],
    [/^(.+) m³ • (.+)$/, '$1 m³ • $2'],
    [/^(.+) m² • (.+)$/, '$1 m² • $2'],
    [/^(.+): \$(.+) \+ (.+) XP$/, '$1: \$ $2 + $3 经验值'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();