// ==UserScript==
// @name         Wealth Wings 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.11
// @description  网页游戏 Wealth Wings (https://www.wealthwings.biz/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Wealth Wings.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://www.wealthwings.biz/favicon.ico
// @license      MIT
// @include      *https://www.wealthwings.biz/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/wealth-wings-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/wealth-wings-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/06/15 21:19
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Multiplayer Economy": "多人游戏经济",
    "Play Now": "马上开玩",
    "Play Now - It's Free": "马上开玩 - 免费",
    "Play now to get listed here": "现在开始游戏，在这里列出",
    "Press Kit": "宣传资料包",
    "Support": "支持",
    "Tutorial": "教程",
    "Updates": "更新",
    "View Full Leaderboard": "查看完整排行榜",
    "Virtual GDP": "虚拟GDP",
    "Watch Gameplay": "观看游戏玩法",
    "Wealth": "财富",
    "Wings": "之翼",
    "Started streaming this game and my viewers are really interested. The visuals are great and there's always something happening. Perfect for content creation!": "开始直播这个游戏，我的观众很感兴趣。视觉效果很棒，总有一些事情发生。完美的内容创作！",
    "Subscribe": "订阅",
    "Stay Updated": "保持更新",
    "100% profit margin for 3 months": "100%的利润率持续3个月",
    "5-Star Reviews": "五星评价",
    "About": "关于",
    "Active Companies": "活跃公司",
    "Active Players": "活跃玩家",
    "Advanced charts, predictive analytics, and market intelligence to make informed business decisions.": "高级图表、预测分析和市场情报，以做出明智的商业决策。",
    "AI-Powered Market": "AI驱动市场",
    "All servers operational": "所有服务器运行正常",
    "And this is just the beginning...": "而这仅仅是个开始...",
    "App Rating": "App评分",
    "As an econ student, I appreciate how the market dynamics work. Still learning the ropes but the tutorial was helpful. Looking forward to building my first factory chain!": "作为一名经济学专业的学生，我理解市场动态是如何运作的。还在学习，但教程是有帮助的。期待建立我的第一个工厂链！",
    "Available": "可用",
    "Be the First to Lead!": "做第一个领导者！",
    "Blog": "博客",
    "Best business sim ever!": "最好的商业模拟游戏！",
    "Bronze": "青铜",
    "Bug Report": "报告Bug",
    "Build & Manufacture": "建造 & 制造",
    "Business Owner": "企业主",
    "Build your empire from scratch. Trade, manufacture, and dominate the market in the most realistic business simulator ever created.": "从零开始建立你的帝国。在最逼真的商业模拟器中进行贸易、制造和支配市场。",
    "Buy low, sell high. Master the art of trading across global markets with real-time supply and demand.": "低买高卖。掌握全球市场实时供求交易的艺术。",
    "By signing up, you agree to our Terms of Service and Privacy Policy": "注册即表示您同意我们的服务条款和隐私政策",
    "Careers": "职位",
    "Casual Player": "休闲玩家",
    "Coming Soon": "敬请期待",
    "Community": "社区",
    "Companies Built": "公司建立",
    "Company": "公司",
    "FAQ": "常见问题",
    "Events": "活动",
    "Diamond": "钻石",
    "Cookie Policy": "Cookie策略",
    "Contact Us": "联系我们",
    "Game": "游戏",
    "Gameplay": "玩法",
    "Google": "Google",
    "Gold": "黄金",
    "Join Discord": "加入 Discord",
    "Legendary": "传说",
    "Leaderboard": "排行榜",
    "Market Leader": "市场领导者",
    "Platinum": "铂金",
    "Playing Now": "开始游戏",
    "Players Online": "在线玩家",
    "Perfect Quarter": "完美季节",
    "Join now and get": "马上加入并获得",
    "Compete and collaborate with millions of players in a living, breathing global economy.": "在一个活生生的全球经济中与数百万玩家竞争和合作。",
    "Competitive Player": "竞技选手",
    "Construct factories, optimize production lines, and create products from raw materials to finished goods.": "建设工厂，优化生产线，创造从原材料到成品的产品。",
    "Countries": "国家",
    "David Kim": "大卫·金",
    "Dominate 50% of any market": "占据50%的市场份额",
    "Earn your first million in revenue": "赚取你的第一个百万收入",
    "Economics Student": "经济学专业的学生",
    "Educational and fun!": "既有教育意义又有趣！",
    "Emma Rodriguez": "艾玛·罗德里格斯",
    "Empire Builder": "帝国建设者",
    "Endless Possibilities": "无尽的可能性",
    "Every second counts. React to market changes instantly and stay ahead of the competition.": "每一秒都很重要。及时对市场变化作出反应，保持竞争优势。",
    "Experience the depth of a true business simulation where every decision matters and every strategy leads to unique outcomes.": "体验真实商业模拟的深度，其中每个决策都很重要，每个策略都会导致独特的结果。",
    "Explore All Features": "探索所有功能",
    "Features": "功能",
    "First Million": "第一个百万",
    "Form corporations, join trade unions, and build strategic partnerships to maximize profits.": "成立公司，加入工会，建立战略合作伙伴关系，以实现利润最大化。",
    "Forums": "论坛",
    "Found this game yesterday and already spent hours on it. The interface is clean and the concept is really engaging. Excited to see where this goes!": "昨天发现了这个游戏，已经在上面玩了好几个小时了。界面很干净，概念也很吸引人。很高兴看到这一切的发展！",
    "Free to play forever": "永久免费游戏",
    "from 100s of reviews": "从上百条评论中",
    "Get the latest news, updates, and exclusive offers delivered to your inbox.": "获得最新的新闻，更新和独家优惠交付到您的收件箱。",
    "Global Expansion": "全球扩张",
    "Have questions?": "有问题吗?",
    "Help Center": "帮助中心",
    "Incredibly addictive!": "令人难以置信的上瘾！",
    "Innovation Master": "创新大师",
    "Instant access to all features": "即时访问所有功能",
    "Join the growing community of players discovering the next generation of business simulation": "加入不断增长的玩家社区，探索下一代商业模拟",
    "Joined Today": "今日加入",
    "Just started playing last week and I'm already hooked. The mechanics are surprisingly deep for a browser game. Can't wait to see how this develops!": "我上周才开始玩，就已经迷上了。对于一款网页游戏来说，它的机制非常有深度。迫不及待地想看看这是如何发展的！",
    "Limited Time Bonus": "限时奖励",
    "Lisa Thompson": "丽莎·汤普森",
    "Live Game Statistics": "实时游戏统计",
    "Live Markets": "活跃的市场",
    "Love the competitive aspect! Even though it's early days, I can see the potential for great player interaction. The trading system is really well thought out.": "喜欢竞争的一面！尽管还处于早期阶段，但我已经看到了玩家互动的潜力。这个交易系统是经过深思熟虑的。",
    "Loved by Players Worldwide": "受到全世界玩家的喜爱",
    "Marcus Johnson": "马库斯·约翰逊",
    "Market Analytics": "市场分析",
    "Markets Available": "市场开放",
    "No credit card required": "不需要信用卡",
    "No email or account needed! Play instantly, but we recommend signing up for cloud saves.": "不需要电子邮件或帐户！立即玩，但我们建议注册云保存。",
    "Or continue with": "或者继续",
    "Own 100+ factories worldwide": "在全球拥有100多家工厂",
    "Perfect for streaming!": "非常适合流媒体！",
    "plus exclusive founder rewards!": "加上独家创始人奖励！",
    "potential progress loss": "潜在进度损失",
    "Privacy Policy": "隐私政策",
    "Reach $1 Billion net worth": "净资产达到10亿",
    "Real-Time Action": "实时行动",
    "Realistic and practical!": "实事求是！",
    "Reddit": "Reddit",
    "Research all technologies": "研究所有技术",
    "Running a small business IRL and this game captures some interesting aspects of supply chain management. Fun way to unwind after work!": "经营一家小型企业，这个游戏抓住了供应链管理的一些有趣方面。工作之余放松的好方法！",
    "Sarah Williams": "莎拉·威廉姆斯",
    "Satisfaction": "满意度",
    "Save your game frequently!": "经常保存你的游戏！",
    "Silver": "白银",
    "Sophisticated AI ensures realistic market behavior, creating endless opportunities and challenges.": "成熟的人工智能保证了现实的市场行为，创造了无尽的机遇和挑战。",
    "Start local, go global. Expand your empire across continents and dominate international markets.": "从本地开始，走向全球。在各大洲扩张你的帝国，主宰国际市场。",
    "Start Playing Instantly": "立即开始游戏",
    "Start Playing Now": "现在开始玩",
    "Start Your Empire Today": "今天开始你的帝国",
    "Strategic Alliances": "战略联盟",
    "Strategy Gamer": "策略游戏玩家",
    "Streamer": "网络主播",
    "System Status": "系统状态",
    "Terms of Service": "服务条款",
    "The Ultimate Business Simulation Experience": "终极商业模拟体验",
    "The ultimate business simulation game. Build, trade, and dominate the global market.": "终极商业模拟游戏。建设、贸易和主导全球市场。",
    "This game is in active development. Expect frequent updates, bugs, and": "这个游戏正在积极开发中。期待频繁的更新、bug和",
    "Thrilling competition!": "激动人心的竞争!",
    "Today's Top Tycoons": "当今的顶级大亨",
    "Trade & Commerce": "贸易与商业",
    "Transactions/Hour": "交易/小时",
    "Tycoon": "大亨",
    "Unlock Epic Achievements": "解锁史诗成就",
    "Begin as a guest and create your business": "以游客身份开始，开创自己的事业",
    "Choose how to start your business empire": "选择如何开始你的商业帝国",
    "Cloud saves enabled": "启用云存储",
    "Continue as Guest": "以游客身份继续",
    "Continue with Discord": "继续使用Discord",
    "Continue with Google": "继续使用谷歌",
    "Continue your business empire with cloud saves": "用云存储继续你的商业帝国",
    "Create an account to save your progress to the cloud.": "创建一个帐户，将您的进度保存到云端。",
    "Create New Account": "创建新帐户",
    "Don't have an account? Sign up": "没有账户？注册",
    "Email": "电子邮件",
    "Full features unlocked": "全部功能解锁",
    "Password": "密码",
    "Quick start - upgrade anytime": "快速启动-随时升级",
    "Sign In": "登录",
    "Sign in to enable cloud saves and sync across devices": "登录以启用云存储和跨设备同步",
    "Sign In to Existing Account": "登录到现有帐户",
    "Sign up to enable cloud saves from the start": "注册以从一开始就启用云存储",
    "Start New Game": "开始新游戏",
    "Tip: You can start as a guest and create an account later without losing progress": "提示：您可以以游客身份开始，稍后创建帐户，但不会丢失进度",
    "Welcome to WealthWings": "欢迎来到财富之翼",
    "Create Account": "创建账户",
    "Already have an account? Sign in": "已有账户？登录",
    "Firebase: Error (auth/network-request-failed).": "Firebase：错误（认证/网络请求失败）。",
    "Welcome back! Sign in to continue your empire.": "欢迎回来！登录并继续你的帝国。",
    "Back": "返回",
    "Step": "步骤",
    "of": "/",
    "Next": "下一步",
    "Capital & Strategy": "资本与战略",
    "Choose a memorable name and slogan for your company": "为你的公司选择一个令人难忘的名字和口号",
    "Company Identity": "公司形象",
    "Company Logo": "公司的标志",
    "Company Name": "公司名称",
    "Company Slogan": "公司口号",
    "Create Your Empire": "创建你的帝国",
    "Industry & Location": "行业及位置",
    "Loading your game data...": "正在加载游戏数据…",
    "Returning player? Log in": "回归玩家？登录",
    "Review & Launch": "审查和发布",
    "Signed in as guest! Note: Guest progress will be lost if you sign out.": "以客人身份登录！注意：如果您退出，来宾进度将会丢失。",
    "City": "城市",
    "Easy": "简单",
    "Hard": "困难",
    "Forest": "森林",
    "Midnight": "午夜",
    "Normal": "正常",
    "Ocean Wave": "海浪",
    "Mining": "矿业",
    "Preview": "预览",
    "Rose Gold": "玫瑰金",
    "\"Entrepreneur\" badge": "“企业家”徽章",
    "\"Investor Backed\" badge": "“投资者支持”徽章",
    "Access to all tutorials": "访问所有教程",
    "Acquisition Focused": "专注于收购",
    "Aerospace": "航空航天",
    "Aggressive Growth": "积极成长型",
    "Arctic": "北极",
    "Aviation and space technology": "航空和空间技术",
    "Balanced Approach": "平衡方法",
    "Balanced progression": "平衡进展",
    "Banking and investments": "银行和投资",
    "Blue Steel": "蓝钢",
    "Build factories and produce goods": "建立工厂，生产商品",
    "Business Strategy": "商业策略",
    "Choose Color Scheme": "选择配色方案",
    "Choose Icon": "选择图标",
    "Choose Your Logo": "选择你的Logo",
    "Choose your starting industry and headquarters": "选择你的起步产业和总部",
    "Comfortable starting position": "舒适的起始位置",
    "Conservative": "保守派",
    "Consumer goods and services": "消费品和服务",
    "Country": "国家",
    "Crimson Fire": "赤焰",
    "Develop software and hardware": "开发软件和硬件",
    "Eco-Conscious": "环保",
    "Emerald Dream": "翡翠之梦",
    "Energy": "能源",
    "Entertainment": "娱乐",
    "Entrepreneur": "企业家",
    "Exclusive \"Rising Star\" badge": "独家“新星”徽章",
    "Exclusive \"Self-Made Tycoon\" badge": "独家“白手起家的大亨”徽章",
    "Faster early growth": "早期成长更快",
    "Finance": "金融",
    "Food & Beverage": "食品饮料",
    "Global Domination": "称霸全球",
    "Golden Sunrise": "金色日出",
    "Green business practices": "绿色商业实践",
    "Growth through buyouts": "通过收购实现增长",
    "Headquarters Location": "总部位置",
    "Headquarters Location:": "总部位置：",
    "Healthcare": "医疗保健",
    "High risk, high reward": "高风险，高回报",
    "Innovation First": "创新至上",
    "International expansion": "国际扩张",
    "Investor Backed": "投资者支持",
    "Logistics": "物流",
    "Manufacturing": "制造业",
    "Media and gaming": "媒体与游戏",
    "Minimal funding, maximum challenge": "资金最少，挑战最大",
    "More room for experimentation": "更多的实验空间",
    "Pharmaceutical and medical services": "医药和医疗服务",
    "Please select an industry": "请选择一个行业",
    "Power generation and utilities": "发电及公用事业",
    "Premium Brand": "高档品牌",
    "Property development and management": "物业发展及管理",
    "Quality over quantity": "质量重于数量",
    "Real Estate": "房地产",
    "Resource extraction": "资源开采",
    "Restaurants and food production": "餐饮业及食品生产",
    "Retail": "零售",
    "Rising Star": "后起之秀",
    "Royal Purple": "蓝紫色",
    "Select an icon and color scheme for your company": "为你的公司选择一个图标和配色方案",
    "Select Industry": "选择行业",
    "Select your starting capital and business strategy": "选择你的启动资金和商业策略",
    "Self-Made Tycoon": "白手起家的大亨",
    "Slow and stable growth": "缓慢稳定增长",
    "Standard achievement points": "标准成就点",
    "Start small, grow organically": "从小处开始，有机成长",
    "Starting Capital": "启动资金",
    "Starting Resources": "启动资源",
    "State/Province (Optional)": "州/省(可选)",
    "Steady and sustainable": "稳健可持续",
    "Sunset": "日落",
    "Technology": "科技",
    "Technology and R&D focused": "专注于技术和研发",
    "Transportation and delivery": "运输与交付",
    "Your company slogan": "你的公司口号",
    "⚠️ EARLY ACCESS:": "⚠️ 抢先体验：",
    "⭐ Rising Star": "⭐ 后起之秀",
    "🏆 Self-Made Tycoon": "🏆 白手起家的大亨",
    "💼 Investor Backed": "💼 投资者支持",
    "📈 Entrepreneur": "📈 企业家",
    "Brand prestige": "品牌声望",
    "Capital preservation": "资本保全",
    "Currency trading": "货币交易",
    "Diversification": "多元化",
    "ESG focus": "环境、社会和治理重点",
    "Exclusive markets": "专属市场",
    "Fast expansion": "快速扩张",
    "Global supply chain": "全球供应链",
    "Green tech": "绿色科技",
    "Heavy investment": "巨额投资",
    "High margins": "高额利润",
    "Long-term focus": "长期关注",
    "M&A strategy": "并购战略",
    "Market consolidation": "市场整合",
    "Market disruption": "市场混乱",
    "Measured growth": "计量增长",
    "Minimal debt": "最低债务",
    "Multi-market": "多元市场",
    "Patent focus": "专利集中",
    "R&D investment": "研发投资",
    "Risk management": "风险管理",
    "Strategy Traits:": "战略特征:",
    "Sustainability bonuses": "可持续发展加成",
    "Synergy seeking": "协同寻求",
    "Tech advancement": "科技进步",
    "Game Settings": "游戏设置",
    "Done": "完成",
    "Chat": "聊天",
    "or": "或",
    "Name:": "名称:",
    "Money": "资金",
    "Market": "市场",
    "Not logged in": "未登录",
    "Locked": "未解锁",
    "Locked (Pro)": "未解锁 (会员)",
    "Manage inventory": "管理库存",
    "Launch Empire": "运行帝国",
    "Map": "地图",
    "Map Information": "地图信息",
    "Manage your buildings": "管理你的建筑",
    "Water": "水",
    "Water Reservoir": "水库",
    "Welcome Bonus:": "欢迎加成:",
    "You will earn:": "你将获得:",
    "Warehouse": "仓库",
    "Tomorrow: $": "明日: $",
    "Today's Reward": "今日奖励",
    "Power Plant": "发电厂",
    "Power": "电力",
    "Claim Bonus": "领取奖励",
    "Buy and sell resources": "购买和出售资源",
    "Company Overview": "公司概览",
    "Company headquarters": "公司总部",
    "Daily Login Bonus!": "日常登录奖励!",
    "Headquarters:": "总部:",
    "Industry:": "行业:",
    "Slogan:": "口号:",
    "Pro Subscription": "会员订阅",
    "Ready to Launch!": "准备运行!",
    "Communicate with players": "与玩家交流",
    "Display active contract progress overlay on the map view": "在地图视图上显示活动合同进度",
    "Empty Plot": "空地",
    "Join Discord Community": "加入Discord社区",
    "Never": "从未",
    "Loading your empire...": "正在加载帝国…",
    "More settings coming soon...": "更多的设置即将到来…",
    "Plot": "土地",
    "Production chains guide": "生产链指南",
    "Production Map": "生产地图",
    "Review your empire configuration": "查看帝国配置",
    "Show Active Contracts on Map": "在地图上显示有效合约",
    "Start your daily streak!": "开始你的每日连胜吧！",
    "Starting Capital:": "启动资金:",
    "Strategy:": "策略:",
    "Available:": "可用:",
    "Streak Rewards": "连胜奖励",
    "This exclusive badge will be displayed on your profile forever!": "这个专属徽章将永远显示在您的个人资料上！",
    "You'll receive $100,000 extra starting capital as a new player!": "作为新玩家，您将获得 100,000 的额外启动资金！",
    "Cloud Saves": "云存储",
    "Account Status": "账号状态",
    "Guest": "游客",
    "Guest Account": "游客账户",
    "Disabled": "禁用",
    "Player": "玩家",
    "Profile": "个人资料",
    "Sign Out": "登出",
    "Upgrade to Full Account": "升级为完整账户",
    "Reset All Progress": "重置所有进度",
    "Member Since": "加入日期",
    "⚠️ You're playing as a guest. Create an account to enable cloud saves and sync across devices.": "⚠️ 您将以游客身份进行游戏。建议创建一个帐户，以启用云存储和跨设备同步。",
    "Account upgraded successfully! Your progress is now saved.": "帐号升级成功！你的进度现在被保存了。",
    "Cancel": "取消",
    "Confirm Password": "确认密码",
    "Create a permanent account to save your progress and access your game from any device.": "创建一个永久帐户来保存你的进度，并从任何设备访问你的游戏。",
    "Email Address": "电子邮件地址",
    "Enabled": "启用",
    "Standard Account": "标准帐户",
    "Unverified": "未验证",
    "Upgrade Account": "升级帐户",
    "Upgrade Your Account": "升级您的帐户",
    "Upgrading...": "升级中...",
    "🛒 Retail": "🛒 零售",
    "🌾 Production": "🌾 生产",
    "⚡ Utilities": "⚡ 公用事业",
    "⚙️ Processing": "⚙️ 加工",
    "s per cycle": " 每个周期",
    "Bakery": "面包房",
    "Bakes bread and other baked goods": "烘焙面包和其他烘焙食品",
    "Cheese Factory": "奶酪工厂",
    "Choose a building for Plot": "为地块选择一个建筑",
    "Collects and purifies water for industrial use": "收集和净化工业用水",
    "Creates prepared foods from multiple ingredients": "用多种原料制作预制食品",
    "Dairy Farm": "奶牛场",
    "Deli": "熟食店",
    "Farm": "农场",
    "Generates electricity for your industrial empire": "为你的工业帝国发电",
    "Grocery Store": "杂货店",
    "Grows crops and produces agricultural products": "种植农作物，生产农产品",
    "likexiazai@qq.com": "likexiazai@qq.com",
    "Mill": "磨机",
    "Power Plants require water to operate, while Water Reservoirs need power. Build both to create a sustainable production chain!": "发电厂需要水来运行，而水库需要电力。共同打造可持续发展的生产链！",
    "Processes cattle into various meat products": "将牛加工成各种肉制品",
    "Processes grain into flour": "把谷物加工成面粉",
    "Processes milk into cheese and butter": "将牛奶加工成奶酪和黄油",
    "Produces:": "生产:",
    "Production Chain Tip:": "生产链提示：",
    "Raises cattle for meat production": "养牛生产肉类",
    "Raises cows and produces fresh milk": "养牛，产鲜奶",
    "Ranch": "牧场",
    "Requires:": "要求:",
    "Select Building": "选择建筑物",
    "Sells food products to consumers": "向消费者出售食品",
    "Slaughterhouse": "屠宰场",
    "Available: $": "可用: $",
    "Lv.": "等级",
    "Level": "等级",
    "Max:": "最大:",
    "Open Store": "打开商店",
    "power": "电力",
    "% faster": "% 更快",
    "% improvement)": "% 提升)",
    "water": "水",
    "water": "水",
    "Upgrades": "升级",
    "unused": "未使用",
    "Upgrade Cost:": "升级成本:",
    "Upgrade to Level": "升级到等级",
    "• Cancel anytime for a 50% refund of": "• 任何时候取消，将获得50%的退款",
    "• Production happens continuously at": "• 生产持续发生在",
    "• You can collect completed units anytime during production": "• 您可以在生产过程中随时收集完成的单位",
    "Benefits:": "好处:",
    "Building placed successfully!": "建筑物放置成功！",
    "Current Level": "当前等级",
    "Example: If you produce 50/100 units, you get back 25% of total resources (50% of the unused half)": "例如：如果你生产了50/100个单位，你将获得总资源的25%（未使用的一半的50%）。",
    "Expected Output": "预期产出",
    "Insufficient funds": "资金不足",
    "Producing": "生产中",
    "Production": "生产",
    "Production Quantity": "生产数量",
    "resources": "资源",
    "Resources Required": "所需资源",
    "seconds per unit": "秒每单位",
    "Select Product": "选择产品",
    "Set to Maximum (": "设置为最大值 (",
    "Start Production": "开始生产",
    "Total Production Time": "总生产时间",
    "units": "单位",
    "Vegetables": "蔬菜",
    "Your Inventory": "你的库存",
    "Sell": "出售",
    "your products to customers": "你的产品给消费者",
    "Sandwich": "三明治",
    "s per unit": " 每单位",
    "Producing:": "生产:",
    "fruits": "水果",
    "Fruits": "水果",
    "Flour": "面粉",
    "/unit": "/单位",
    "Available for Sale": "可供出售",
    "Bread": "面包",
    "Burger": "汉堡",
    "Cattle": "牛",
    "Cheese": "奶酪",
    "Choose what": "选择什么",
    "Collect": "收集",
    "grain": "粮食",
    "Grain": "粮食",
    "Insufficient resources": "资源不足",
    "Milk": "牛奶",
    "No stock available": "没有可用的库存",
    "Sales Tip:": "销售提示：",
    "Selling products requires 1 power per transaction. Keep your power plants running to maintain sales operations!": "销售产品每笔交易需要 1 电力。保持您的发电厂运行，以维持销售业务！",
    "should produce": "应该产出",
    "% complete": "% 完成",
    "Units": "单位",
    "Target": "目标",
    "Total Produced": "总计生产",
    "Time Remaining": "剩余时间",
    "Ready to Collect": "就绪待收集",
    "Production in progress": "生产进度",
    "Overall Progress": "总体进度",
    "Current Product": "当前产品",
    "Cancel Production (50% Refund of Unused)": "取消生产（未使用部分退款50%）",
    "→ Bakery →": "→ 面包房 →",
    "→ Mill →": "→ 磨机 →",
    "Sign in to enable cloud saves": "登录以启用云保存",
    "(Click any row to buy)": "(点击任意行以购买)",
    "Currently producing:": "当前生产中:",
    "kL/cycle": "kL/周期",
    "MW/cycle": "MW/周期",
    "Power Production": "电力生产",
    "Water Production": "水生产",
    "butter": "黄油",
    "burger": "汉堡",
    "beef": "牛肉",
    "bread": "面包",
    "cheese": "奶酪",
    "flour": "面粉",
    "milk": "牛奶",
    "Progress": "进度",
    "Special": "特殊",
    "Seller": "卖家",
    "Saving...": "保存中...",
    "Save Now": "立即保存",
    "Total": "总计",
    "Time": "时间",
    "Total Items": "总物品数",
    "Total net worth": "总净价值",
    "Track your progress": "追踪你的进度",
    "Track your progress and earn rewards": "追踪你的进度并获得奖励",
    "Unlocked": "已解锁",
    "Unlocked:": "已解锁:",
    "vegetables": "蔬菜",
    "View Contracts": "查看合同",
    "View Achievements": "查看成就",
    "View Research": "查看研究",
    "Water Works": "供水系统",
    "Contracts": "合同",
    "Completion": "完成",
    "Dairy Products": "乳制品",
    "Meat Products": "肉制品",
    "My Orders": "我的订单",
    "Mastery": "精通",
    "listings": "清单",
    "Industry": "行业",
    "Inventory Value": "行业价值",
    "Headquarters": "总部",
    "ground beef": "碎牛肉",
    "Human Resources": "人力资源",
    "Final Products": "最终产品",
    "Filters": "过滤器",
    "Dough": "面团",
    "dough": "面团",
    "Daily Expenses": "日常开支",
    "Daily Revenue": "日常收入",
    "Dedicated Player": "忠实玩家",
    "Complete all achievements": "完成所有成就",
    "City Builder": "城市建设者",
    "Auto-save enabled (every 10 minutes)": "自动保存启用 (每 10 分钟)",
    "• Sell products at the": "• 出售产品在",
    "All Resources": "所有资源",
    "Basic Resources": "基础资源",
    "• No storage limits - produce as much as you want!": "•无存储限制——想生产多少就生产多少！",
    "• Products are automatically stored here after production": "•产品生产后自动存储在这里",
    "Accept and complete contracts": "接受并完成合同",
    "Baker Apprentice": "面包师学徒",
    "Bread Baron": "面包大王",
    "Bread Empire": "面包帝国",
    "Breaking Ground": "破土动工",
    "Capital Credits": "资本积分（CC）",
    "cattle": "牛",
    "Check for Completed Achievements": "查看已完成成就",
    "cheese platter": "奶酪拼盘",
    "Cloud Save": "云存储",
    "Company Level": "公司级别",
    "Company Value": "公司价值",
    "Dedicated Tycoon": "敬业的大亨",
    "Early Bird": "早起者",
    "Earn your first $1,000": "赚到你的第一笔 $1000",
    "Expansion": "扩展",
    "for profit": "为了利润",
    "Founded": "成立",
    "Global Market": "全球市场",
    "Industrial Complex": "工业园区",
    "Land Owner": "土地所有者",
    "Manage employees": "管理员工",
    "Manage your company operations": "管理公司运营",
    "Manual save to cloud": "手动保存到云端",
    "Market Listings": "市场列表",
    "Master Baker": "烘焙大师",
    "Millionaire": "百万富翁",
    "Next auto-save in:": "距离下次自动保存：",
    "No cloud save found": "没有找到云保存",
    "No listings found": "没有找到清单",
    "Perfectionist": "完美主义者",
    "Place your first building": "放置你的第一座建筑",
    "Power Provider": "电力供应商",
    "Price/Unit": "价格/单位",
    "Processed Goods": "加工产品",
    "Produce your first bread": "制作你的第一个面包",
    "Product Types": "产品类型",
    "Production Chain Guide": "生产链指南",
    "Production Inventory": "生产库存",
    "Quantity": "数量",
    "Raw Materials": "原材料",
    "Real-time trading with dynamic price discovery": "实时交易与动态价格发现",
    "Research & Development": "研究与开发",
    "Resource": "资源",
    "sandwich": "三明治",
    "Save manually anytime or wait for auto-save": "手动保存随时或等待自动保存",
    "Try adjusting your filters": "试着调整你的过滤器",
    "Ultimate Tycoon": "终极大亨",
    "Unlock all available plots": "解锁所有可用的地块",
    "Unlock new technologies": "解锁新技术",
    "Your production inventory": "你的生产库存",
    "% Production Speed": "% 生产速度",
    "% Resource Consumption": "% 资源消耗",
    "Enhanced Automation": "增强自动化",
    "enhanced_automation": "增强自动化",
    "Basic Automation": "基础自动化",
    "basic_automation": "basic_automation",
    "Cost:": "成本:",
    "Efficiency": "效率",
    "Full Automation": "完全自动化",
    "OR": "或",
    "Product Value": "产品价值",
    "Research": "研究",
    "Soon": "敬请期待",
    "Automation": "自动化",
    "Configure automation by clicking the settings icon on individual buildings in the Map view": "通过点击地图视图中单个建筑上的设置图标来配置自动化",
    "Active Research Effects": "主动研究效果",
    "Advanced Automation": "高级自动化",
    "All buildings consume 10% less resources": "所有建筑消耗的资源减少10%",
    "All buildings consume an additional 10% less resources": "所有建筑消耗的额外资源减少10%",
    "All buildings produce 10% faster": "所有建筑生产速度提高10%",
    "All buildings produce an additional 15% faster": "所有建筑的生产速度增加15%",
    "Auto-Start Slot": "自动开始槽位",
    "Auto-Start Slots Used": "使用的自动开始槽位",
    "Economics": "经济学",
    "Industrial Automation": "工业自动化",
    "Innovation": "创新",
    "Insufficient Funds": "资金不足",
    "Production Efficiency": "生产效率",
    "Production Speed": "生产速度",
    "Basic Automation!": "基础自动化！",
    "Enhanced Automation!": "增强自动化！",
    "Resource Cost": "资源成本",
    "Resource Optimization": "资源优化",
    "Unlock new technologies and improvements": "解锁新技术和改进",
    "Auto-Start Production": "自动开始生产",
    "Automation disabled": "已关闭自动化",
    "Automation enabled": "已启用自动化",
    "Automation Slots": "自动化槽位",
    "Building": "建筑",
    "Building Automation": "家族自动化",
    "Currently automated buildings:": "当前自动化建筑：",
    "Disable Automation": "禁用自动化",
    "Enable Automation": "启用自动化",
    "Enable to automatically restart production when completed": "开启后，完成后自动重启生产",
    "No Available Slots": "无可用槽位",
    "This building will automatically restart production when completed": "此建筑将在完成后自动重新开始生产",
    "Game saved to cloud!": "游戏进度已保存到云存储!",
    "Load from Cloud": "从云存储加载进度",
    "Restore your saved game": "恢复你的云存储进度到本地",
    "Just now": "刚刚",
    "• All achievements will be reset": "• 所有成就将被重置",
    "• All buildings and plots will be cleared": "• 所有建筑物和地块将被清除",
    "• All contracts will be removed": "• 所有合同将被移除",
    "• All R&D research will be lost": "• 所有研发成果将会丢失",
    "• Market data will be cleared": "• 市场数据将被清理",
    "• Resources will reset to starting amounts": "• 资源将重置为初始数量",
    "⚠️ This action cannot be undone!": "⚠️ 此操作无法撤消！",
    "✓ Your company name and settings from the setup wizard will be preserved": "✓ 您的公司名称和设置向导中的设置将被保留",
    "Reset All Progress?": "重置所有进度？",
    "Reset Everything": "重置所有",
    "This action will reset your entire game progress:": "这个操作将重置你的整个游戏进度：",
    "Channels": "频道",
    "General": "常规",
    "General discussion": "常规讨论",
    "Global Channel": "全球频道",
    "Send": "发送",
    "Trading": "交易",
    "Share tips and strategies": "分享技巧和策略",
    "Loading messages...": "正在加载消息...",
    "Strategies": "策略",
    "Alliances": "联盟",
    "Online (": "在线 (",
    "Form business partnerships": "建立商业伙伴关系",
    "No messages yet. Start the conversation!": "还没有消息。开始对话吧！",
    "Please log in to send messages": "请登录以发送消息",
    "Market deals and trades": "市场交易和交易",
    "Users": "玩家",
    "Direct Messages": "直接消息",
    "Private conversation": "私聊",
    "All Chains": "全链",
    "Balance your production chains - having too much of one product and not enough of another wastes resources": "平衡你的生产链——一种产品过多而另一种产品不足会浪费资源",
    "Beef": "牛肉",
    "Bread Production Chain": "面包生产链",
    "Burger Production Chain": "汉堡生产链",
    "Check the market regularly for price fluctuations and selling opportunities": "定期查看市场价格波动和卖出机会",
    "Complete contracts to earn Capital Credits (CC) for research upgrades": "完成合同以获得资本积分（CC）用于研究升级",
    "Complete guide to all production chains and resource flows in WealthWings": "财富之翼的所有生产链和资源流的完整指南",
    "Complex production chains require more investment but offer higher profit margins": "复杂的生产链需要更多的投资，但也提供了更高的利润率",
    "Dairy & Meat": "乳制品和肉类",
    "Dairy Production Chain": "乳制品生产链",
    "EmpireBuilder": "EmpireBuilder",
    "Food Production": "粮食生产",
    "Fruit Production Chain": "水果生产链",
    "General Gameplay Tips": "常规玩法提示",
    "Ground Beef": "牛肉",
    "IndustryKing": "IndustryKing",
    "Inputs": "输入",
    "Join the global chat to trade with other players and share strategies": "加入全球聊天与其他玩家交易和分享策略",
    "MarketShark": "MarketShark",
    "Meat Production Chain": "肉类生产链",
    "Output": "输出",
    "Power Generation": "发电",
    "Production Wiki": "生产Wiki",
    "Research automation upgrades early to maximize efficiency while you're offline": "尽早研究自动化升级，以便在离线时最大限度地提高效率",
    "Sandwich Production Chain": "三明治生产链",
    "Stages:": "阶段:",
    "Start with utility buildings (Power Plant & Water Reservoir) to establish your resource foundation": "从公用事业建筑（发电厂和水库）开始建立你的资源基础",
    "Total Profit:": "总利润:",
    "Total Time:": "总时间:",
    "TycoonMaster": "TycoonMaster",
    "Upgrade your buildings to higher levels for better production multipliers": "将你的建筑升级到更高的等级，以获得更好的生产倍率",
    "Utilities": "公用事业",
    "Vegetable Production Chain": "蔬菜生产链",
    "Water Collection": "收集水",
    "1H": "1小时",
    "1W": "1周",
    "1D": "1天",
    "Tax (5%):": "税 (5%):",
    "Total Cost": "总成本",
    "Buy": "购买",
    "available)": "可用)",
    "Max Price": "最高价格",
    "Min Price": "最低价格",
    "No sell orders": "暂无出售订单",
    "No buy orders": "暂无买入订单",
    "No price data available": "暂无可用的价格数据",
    "Buy Cheese Platter": "购买奶酪拼盘",
    "BUY ORDERS": "买入订单",
    "Clear all filters": "清除所有过滤器",
    "Current Market Price": "当前市场价格",
    "No order book data available": "没有可用的订单簿数据",
    "Order Book": "订单簿",
    "Place Buy Order": "发布买入订单",
    "Price": "价格",
    "Price Chart": "价格图表",
    "Price per Unit": "单价",
    "Price per unit:": "单价：",
    "Prices will appear once trading begins": "交易一开始，价格就会显示出来",
    "Quantity:": "数量:",
    "Select a resource to view orders": "选择一个资源来查看订单",
    "SELL ORDERS": "出售订单",
    "Spread:": "传播:",
    "Subtotal:": "小计:",
    "Cancelling a sell order will return the resources to your inventory. Cancelling a buy order will not result in any penalties. Partially filled orders can be cancelled for the remaining quantity.": "取消一个卖单将返回资源到您的库存。取消买入订单不会产生任何处罚。部分已完成的订单可以取消剩余数量。",
    "Buy Orders (": "买入订单(",
    "Important": "重要",
    "My Market Activity": "我的市场活动",
    "No active buy orders": "没有活跃的买入订单",
    "No active sell orders": "没有活跃的卖出订单",
    "Orders (": "订单(",
    "Your listings will appear here": "你的清单将出现在这里",
    "Your orders will appear here": "您的订单将出现在这里",
    "Create Listing": "创建挂单",
    "Listing Fee (2%):": "挂单费用（2%）：",
    "You Receive": "你将收到",
    "Please sign in to trade": "请先登录才能交易",
    "Processing...": "正在处理...",
    "Signed in successfully!": "登录成功!",
    "Signed out successfully": "登出成功",
    "Not available": "不可用",
    "Not signed in": "未登录",
    "Community →": "社区 →",
    "Game features →": "游戏功能 →",
    "How to play →": "玩法 →",
    "System requirements →": "系统要求 →",
    "Welcome back!": "欢迎回来!",
    "Game loaded from cloud!": "从云存储加载进度成功!",
    "24h Volume": "24小时 成交量",
    "24h Low": "24小时 最低价",
    "24h High": "24小时 最高价",
    "Available Stock:": "可用库存:",
    "Current Price": "当前价格",
    "Buying From": "购买 从",
    "Price per unit": "单价",
    "Busy": "繁忙",
    "Currently selling:": "当前正在出售:",
    "Selling...": "出售中...",
    "Started selling!": "开始出售!",
    "Please select a product to produce first!": "请先选择要生产的产品！",
    "Mid Price:": "中位价格:",
    "% speed bonus": "% 速度加成",
    "A local farm co-op needs grain for livestock": "当地的农场合作社需要谷物喂养牲畜",
    "A nearby community center needs water supplies": "附近的社区中心需要供水",
    "A supermarket chain needs bread and flour": "一家连锁超市需要面包和面粉",
    "Accept Contract": "接受合同",
    "Active (": "进行中 (",
    "Active Contracts": "活跃的合同",
    "All Difficulties": "所有难度",
    "Available (": "可用 (",
    "Bakery Bulk Order": "面包房批量订单",
    "Beginner": "新手",
    "City Hospital": "城市医院",
    "City planning department needs utilities": "城市规划部门需要公用事业",
    "City Planning Dept.": "城市规划部",
    "Community Center": "社区中心",
    "Complete contracts to earn money and Capital Credits": "完成合同以赚取金钱和资本积分",
    "Contracts Board": "合同委员会",
    "Emergency Power Supply": "应急电源",
    "Expert": "专家",
    "Farm Co-op": "农业合作社",
    "GlobalCorp": "环球公司",
    "Grain Shipment": "谷物装运",
    "Infrastructure Support": "基础设施支持",
    "Intermediate": "中级",
    "Major corporation needs massive supplies": "大公司需要大量的供应",
    "Mega Corporation Deal": "大公司交易",
    "MegaMart": "超级艺术",
    "No contracts found in this category": "此类别中未找到合同",
    "Requirements:": "要求:",
    "Rewards:": "奖励:",
    "The local hospital needs emergency power supplies": "当地医院需要应急电源",
    "Time limit:": "时间限制:",
    "Total Earned": "累计获得",
    "Water for the Community": "为社区供水",
    "remaining": "剩余",
    "Ready!": "就绪!",
    "Speed bonus applied! 🚀": "速度加成生效！🚀",
    "Complete!": "完成!",
    "Claim Rewards!": "领取奖励!",
    "Claim Reward": "领取奖励",
    "Active": "活跃",
    "Butter": "黄油",
    "Contracts (": "合同 (",
    "✅ Ready to claim!": "✅ 就绪待领取!",
    "✅ Claimed": "✅ 已领取",
    "Automation Enabled": "自动化已启用",
    "• Expand your production capacity": "•扩大你的生产能力",
    "• Increase your revenue potential": "•增加你的收入潜力",
    "• Unlock a new building slot": "•解锁一个新的建筑槽位",
    "Auto-saving...": "自动保存中…",
    "Balance:": "余额：",
    "Balance: $": "余额：$",
    "Cash": "现金",
    "Choose your unlock method:": "选择你的解锁方式：",
    "Corp Creds": "公司信用",
    "Instant access": "即时访问",
    "Unlock Plot": "解锁地块",
    "Unlock this and all premium plots": "解锁这个和所有的高级地块",
    "WealthWings Pro": "财富之翼会员",
    "View": "查看",
    "(Click to buy)": "(点击购买)",
    "Complete tasks": "完成任务",
    "Construction": "建筑",
    "Dairy": "乳制品",
    "Chemicals": "化学品",
    "chees": "奶酪",
    "Employees": "员工",
    "Equipment": "设备",
    "Essentials": "生活必需品",
    "Food Products": "食品",
    "fruit": "水果",
    "Imperial Steel": "",
    "iron": "铁",
    "coal": "煤",
    "steel": "钢",
    "stone": "石头",
    "Track progress": "追踪进度",
    "Unlock new tech": "解锁新科技",
    "Oil & Gas": "石油 & 天然气",
    "Agriculture": "农业",
    "Livestock": "牲畜",
    "cattl": "牛",
    "butte": "黄油",
    "crude": "原油",
    "diese": "柴油",
    "diesel": "柴油",
    "Orders": "订单",
    "limestone": "石灰岩",
    "limes": "石灰岩",
    "sandw": "三明治",
    "veget": "蔬菜",
    "burge": "汉堡",
    "Collapse all": "全部折叠",
    "Expand all": "全部展开",
    "plast": "塑料",
    "plastic products": "塑料制品",
    "groun": "碎牛肉",
    "plastic pellets": "塑料颗粒",
    "natural gas": "天然气",
    "natur": "天然气",
    "gasoline": "汽油",
    "gasol": "汽油",
    "industrial chemicals": "工业化学品",
    "indus": "工业化学品",
    "marbl": "大理石",
    "marble": "大理石",
    "grani": "花岗岩",
    "granite": "花岗岩",
    "marble tiles": "大理石瓷砖",
    "build": "建筑材料",
    "building materials": "建筑材料",
    "concr": "混凝土",
    "concrete": "混凝土",
    "steel beams": "钢板",
    "stone blocks": "石块",
    "containers": "容器",
    "conta": "容器",
    "elect": "电子元件",
    "electronic components": "电子元件",
    "circuit boards": "电路板",
    "circu": "电路板",
    "consu": "家用电器",
    "consumer appliances": "家用电器",
    "industrial equipment": "工业设备",
    "Pro": "会员",
    "Products": "产品",
    "Oil": "石油",
    "Level:": "等级:",
    "Overview": "概览",
    "Advanced Tips": "高级提示",
    "Basic": "基础",
    "Build Power Plant & Water Reservoir": "建造发电厂和水库",
    "Complex chains = better margins": "复杂的生产链 = 更好的利润",
    "Dev Corporation": "发展公司",
    "Empire of Wealth": "财富帝国",
    "Enhanced Crops": "增强作物",
    "Essential First Steps": "至关重要的第一步",
    "Expand to bread for profits": "扩展到面包以获取利润",
    "Getting Started": "入门",
    "Mining chains enable manufacturing": "采矿生产链使制造业成为可能",
    "Master all production chains and maximize your profits": "掌握所有生产链，实现利润最大化",
    "Start basic food production": "开始基础粮食生产",
    "Research automation early": "尽早研究自动化",
    "Chains": "生产链",
    "Complex": "复杂",
    "Food": "食物",
    "Adv": "高级",
    "Inter": "中级",
    "ADVANCED": "高级",
    "Coal": "煤",
    "Enhanced Power Generation": "增强发电能力",
    "Improved Power Plant": "改良发电厂",
    "Natural Gas": "天然气",
    "No chains found": "未找到生产链",
    "Out": "输出",
    "Setup: $": "设置: $",
    "stages •": "阶段 •",
    "BASIC": "基础",
    "Basic Power Generation": "基础发电",
    "Bread Production": "面包生产",
    "Building Materials": "建筑材料",
    "Chemical Plant": "化学工厂",
    "Chemical Production": "化工生产",
    "Circuit Boards": "电路板",
    "Coal Mine": "煤矿",
    "COMPLEX": "复杂",
    "Concrete": "混凝土",
    "Construction Plant": "建设工厂",
    "Consumer Appliances": "家用电器",
    "Crude Oil": "原油",
    "Electronic Components": "电子元件",
    "Electronics Factory": "电子工厂",
    "Electronics Manufacturing": "电子产品制造",
    "Electronics Store": "电子产品商店",
    "Fertilizer": "肥料",
    "Fuel Production": "燃料生产",
    "Fuel Station": "加油站",
    "Gasoline": "汽油",
    "In": "输入",
    "Industrial Chemicals": "工业化学品",
    "Industrial Equipment": "工业设备",
    "Industrial Supplier": "工业供应商",
    "INTERMEDIATE": "中级",
    "Iron Mine": "铁矿",
    "Iron Ore": "铁矿石",
    "Limestone": "石灰石",
    "Machinery Plant": "机械厂",
    "Mfg": "制造行业",
    "Natural Gas Well": "天然气井",
    "Oil Derrick": "井架",
    "Oil Refinery": "炼油厂",
    "Plastic Pellets": "塑料颗粒",
    "Plastic Products": "塑料制品",
    "Plastics Factory": "塑料工厂",
    "Smelter": "冶炼厂",
    "Steel": "钢",
    "Steel Beams": "钢梁",
    "Steel Production": "钢铁生产",
    "Stone Blocks": "石块",
    "Stone Quarry": "采石场",
    "Stone Workshop": "石头车间",
    "Vegetable Production": "蔬菜生产",
    "R&D": "研究 & 开发",
    "Cancelling a sell order will return the resources to your inventory. Cancelling a buy order will refund the escrowed money for unfilled portions. Partially filled orders can be cancelled for the remaining quantity.": "取消一个卖单将返回资源到您的库存。取消购买订单将退还未完成部分的托管资金。部分已完成的订单可以取消剩余数量。",
    "Volume:": "数量:",
    "Your money will be held in escrow until the order is filled or cancelled. The order will execute when sellers offer at or below your price.": "您的钱将保存在第三方托管，直到订单完成或取消。当卖方报价等于或低于你方价格时，订单将执行。",
    "Price:": "价格:",
    "Place Limit Order": "上架限价订单",
    "Order Type:": "订单类型:",
    "Set your own price and wait for matching sellers": "设定你自己的价格，等待匹配的卖家",
    "Advanced Buy Order -": "高级买入订单 -",
    "Buy immediately at best available prices": "立即以最优惠的价格购买",
    "Global": "全局",
    "Escrow Amount:": "托管金额:",
    "Market Order": "市场订单",
    "Max Price per unit:": "最高单价:",
    "Maximum Price per Unit": "最高单价",
    "Scarcity pricing active (low supply)": "稀缺性定价活跃（供应不足）",
    "Limit Order": "限价订单",
    "(Insufficient funds)": "(资金不足)",
    "Available quantity:": "可用的数量:",
    "Average price:": "平均价格:",
    "Calculating best prices...": "计算最优价格...",
    "Execute Market Order": "执行市场订单",
    "Price Breakdown": "价格明细",
    "No listings available": "暂无清单可用",
    "Total Cost:": "总成本:",
    "Order": "订单",
    "Order can be fulfilled": "订单可以完成",
    "Qty": "数量",
    "Cancelling...": "正在取消...",
    "View ratings & stats": "查看评分和统计",
    "Your business overview and ratings": "您的业务概况和评分",
    "Your credit rating determines your eligibility for Purchase Agreements with other companies. Maintain on-time deliveries to keep your rating high and unlock better contract terms.": "您的信用等级决定了您是否有资格与其他公司签订购买协议。保持准时交货，以保持你的评级高，解锁更好的合同条款。",
    "Rating": "评分",
    "Select Product to Sell": "选择要出售的产品",
    "Purchase Agreements will be available soon! Build relationships with other companies to secure exclusive resource deals.": "购买协议将很快推出！与其他公司建立关系，确保独家资源交易。",
    "Purchase Agreements": "采购协议",
    "Progress to": "进度到",
    "properties •": "物业 •",
    "products in bulk": "散装产品",
    "Perfect record - Maximum trust": "完美记录 - 最大信任",
    "No active Purchase Agreements": "暂无活跃的采购协议",
    "Net Worth": "净资产",
    "Missed Deliveries:": "错过交付:",
    "Inventory": "库存",
    "Established - Solid foundation": "已建立 - 坚实的基础",
    "in stock": "现货",
    "Credit Worthiness": "信用状况",
    "Credit": "信用",
    "Company Profile": "公司简介",
    "Buildings": "建筑",
    "Business": "业务",
    "% of net worth": "% 净资产",
    "About Credit": "关于信用",
    "Active Partnerships": "积极合作",
    "completed": "已完成",
    "Today": "今天",
    "• Sales happen continuously at": "• 销售持续发生在",
    "• You can collect revenue anytime during sales": "• 您可以在销售期间随时收取收入",
    "inventory": "库存",
    "Expected Revenue": "预期收入",
    "Inventory Required": "库存要求",
    "Sales Quantity": "出售数量",
    "Start Selling": "开始出售",
    "Total Sales": "总计出售",
    "Total Sales Time": "总计出售时间",
    "unsold": "未售出",
    "Cancel Sales (50% Refund)": "取消销售（50%退款）",
    "Selling": "出售中",
    "Total Sold": "总计售出",
    "units sold": "单位出售",
    "Sales": "出售",
    "Production cancelled with 50% refund!": "生产取消，退款50% ！",
    "Advanced - Strong performer": "高级 - 表现出色",
    "Check Progress": "检查进度",
    "Energy Tycoon": "能源大亨",
    "Expansion Master": "扩张大师",
    "Fast Starter": "快速入门",
    "First Purchase": "第一次购买",
    "First Sale": "第一次出售",
    "Fruit Merchant": "水果商人",
    "Half Million Club": "50万俱乐部",
    "HR": "HR",
    "Industrial Magnate": "工业巨头",
    "Land Baron": "土地领主",
    "Vegetable Vendor": "蔬菜供应商",
    "Make your first market purchase": "进行你的第一次市场购买",
    "Make your first market sale": "进行你的第一次市场销售",
    "Market Mogul": "市场巨头",
    "Market Regular": "市场常规",
    "Mega Factory": "超级工厂",
    "Multi-Millionaire": "千万富翁",
    "Orchard Baron": "果园男爵",
    "Orchard Owner": "果园主人",
    "Power Magnate": "电力巨头",
    "Premium Investor": "高级投资者",
    "Produce King": "生产大王",
    "Produce Master": "生产大师",
    "Production Empire": "生产帝国",
    "Retail Empire": "零售帝国",
    "Retail King": "零售大王",
    "Retail Manager": "零售经理",
    "Retail Rookie": "零售新秀",
    "Sales Expert": "销售专家",
    "Shopping Spree": "疯狂购物",
    "Six Figures": "六位数",
    "Sync Stats": "同步统计",
    "Trading Tycoon": "贸易大亨",
    "Veteran Tycoon": "资深大亨",
    "Water Empire": "水之帝国",
    "Week Warrior": "周常战士",
    "Bulk listing price restrictions applied": "批量上架价格限制",
    "(Insufficient resources)": "(资源不足)",
    "Total Value:": "总价值:",
    "Price/Unit:": "单价:",
    "more": "更多",
    "Empty": "空",
    "• Production buildings can produce multiple product types": "•生产建筑可以生产多种产品类型",
    "• Retail buildings generate money from selling products": "•零售建筑通过销售产品赚钱",
    "• Utilities: Power Plants need water, Water Reservoirs need power": "•公用事业：发电厂需要水，水库需要电力",
    "Advanced power generation using coal and natural gas": "利用煤和天然气的先进发电技术",
    "Assembles industrial equipment and consumer appliances": "组装工业设备和消费电器",
    "Cuts and shapes stone into blocks and tiles": "将石头切割成块状和瓦片",
    "Extracts crude oil from underground reserves": "从地下石油储备中提取原油",
    "Extracts iron ore from deep underground": "从地下深处开采铁矿石",
    "Extracts limestone, granite, and marble from the earth": "从泥土中提取石灰石、花岗岩和大理石",
    "Extracts natural gas from underground deposits": "从地下矿藏中提取天然气",
    "Manufactures plastic products and containers": "生产塑料制品和容器",
    "Mines coal for fuel and steel production": "开采煤炭用于燃料和钢铁生产",
    "Multiple options": "多种选择",
    "Processing": "加工",
    "Produces circuit boards and electronic components": "生产电路板和电子元件",
    "Produces concrete and building materials": "生产混凝土和建筑材料",
    "Produces fertilizers and industrial chemicals": "生产化肥和工业化学品",
    "Production Tips:": "生产建议:",
    "Refines crude oil into gasoline, diesel, and plastics": "将原油提炼成汽油、柴油和塑料",
    "Retail outlet for electronics and components": "电子产品和零部件零售店",
    "Sells equipment and building materials to businesses": "向企业销售设备和建筑材料",
    "Sells gasoline and diesel to consumers": "向消费者销售汽油和柴油",
    "Smelts ore into steel and processes metal products": "将矿石冶炼成钢铁并加工金属制品",
    "Building Type": "建筑物类型",
    "Demolish": "拆除",
    "Demolish Building": "拆除建筑",
    "Demolishing this building will permanently remove it from the plot. Any ongoing production will be lost.": "拆除这座建筑将使它永远离开这块土地。任何正在进行的生产都将丢失。",
    "Demolition Details": "拆除详情",
    "Original Cost": "原始成本",
    "Pro Tip:": "专业提示：",
    "Refund Amount": "退款金额",
    "Refund Rate": "退款率",
    "Remove": "移除",
    "Upgrade to Pro to get 75% refund instead of 50%": "升级到专业版可以获得75%的退款，而不是50%",
    "Warning": "警告",
    "Listing cancelled and resources returned to warehouse": "已取消上架，资源已返回仓库",
    "Advanced Automation!": "高级自动化!",
    "Industrial Automation!": "工业自动化!",
    "Limit buy order placed successfully. Money held in escrow.": "限价买入订单成功下单。资金已托管。",
    "Bid Price:": "收购单价:",
    "Pending": "待成交",
    "Cheese Platter": "奶酪拼盘",
    "Full Automation!": "完全自动化!",
    "ground_beef": "碎牛肉",
    "Claim!": "领取!",
    "Elite - Industry leader": "精英 - 行业领袖",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "stone_blocks": "石块",
    "plastic_products": "塑料制品",
    "resource_optimization_1": "资源优化 I",
    "advanced_automation": "高级自动化",
    "industrial_automation": "工业自动化",
    "production_efficiency_1": "生产效率 I",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "Partners": "Partners",
    "© 2025 WealthWings. All rights reserved.": "© 2025 WealthWings. All rights reserved.",
    "“": "“",
    "”": "”",
    "Alex Chen": "Alex Chen",
    "App": "App",
    "DK": "DK",
    "ER": "ER",
    "LT": "LT",
    "MJ": "MJ",
    "SW": "SW",
    "✓": "✓",
    "🎁": "🎁",
    "🎉": "🎉",
    "$": "$",
    "HQ": "HQ",
    "CC": "CC (资本积分)",
    "kL": "kL",
    "MW": "MW",
    "🗺️": "🗺️",
    "%": "%",
    "🏗️": "🏗️",
    "🏙️": "🏙️",
    "💎": "💎",
    "📜": "📜",
    "🥇": "🥇",
    "🥈": "🥈",
    "🥉": "🥉",
    "→": "→",
    ")/": ")/",
    "•": "•",
    "N/A": "N/A",
    "⚡": "⚡",
    "🌾": "🌾",
    "🏛️": "🏛️",
    "🏢": "🏢",
    "🏪": "🏪",
    "💧": "💧",
    "🚀": "🚀",
    "☁️": "☁️",
    "✅": "✅",
    "💰": "💰",
    "🏭": "🏭",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Claimed! ": "已领取! ",
    "Daily bonus claimed! ": "日常奖励已领取! ",
    "Display Settings": "显示设置",
    "🏆 Achievement Unlocked: ": "🏆 成就已解锁: ",
    "Resource Cost: ": "资源成本: ",
    "Production Speed:": "生产速度:",
    "Output: ": "输出: ",
    "Research completed: ": "研究已完成: ",
    "Last saved: ": "最近保存: ",
    "Direct Message: ": "直接消息: ",
    "Available balance: ": "可用余额: ",
    "Sell ": "出售",
    "Buy Power from ": "购买 电 从 ",
    "Buy Water from ": "购买 水 从 ",
    "Suggested: ": "建议: ",
    "Range: ": "范围: ",
    "Min: ": "最低: ",
    "Max: ": "最高: ",
    "Contract rewards claimed: ": "合同奖励已领取: ",
    "Contract accepted: ": "合同已接受: ",
    "Contract completed: ": "合同已完成: ",
    "Price too low. Minimum price is ": "价格太低了。最低价格为 ",
    "Water Reservoir upgraded to Level ": "水库 已升级到等级 ",
    "Power Plant upgraded to Level ": "发电厂 已升级到等级 ",
    "Bakery upgraded to Level ": "面包房 已升级到等级 ",
    "Mill upgraded to Level ": "磨机 已升级到等级 ",
    "Ranch upgraded to Level ": "牧场 已升级到等级 ",
    "Farm upgraded to Level ": "农场 已升级到等级 ",
    "Dairy Farm upgraded to Level ": "奶牛场 已升级到等级 ",
    "Cheese Factory upgraded to Level ": "奶酪工厂 已升级到等级 ",
    "Upgrade to Level ": "升级到等级 ",
    "Industrial Complex - ": "工业园区 - ",
    "Ten Thousand Club": "万人俱乐部",
    "First Thousand": "首个1000",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " starting capital": " 启动资金",
    " Rating": " 评分",
    " characters": " 字符",
    " (Guest)": " (游客)",
    " (no email)": " (无邮箱)",
    "! Click to claim rewards.": "! 点击以领取奖励.",
    " I!": " I!",
    " II!": " II!",
    " (Free)": " (免费)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^building\-(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^\+\$$/,
    /^\+([\d\.,]+)\$$/,
    /^\-([\d\.,]+)\$$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Successfully placed buy order for (.+) Grain$/, '成功下单购买了 $1 粮食'],
    [/Buy Grain from (.+)$/, '从 $1 那里购买 粮食'],
    [/Limit buy order placed for (.+) Grain$/, '发布限价订单收购 $1 粮食'],
    [/Purchased (.+) grain for (.+) \(includes (.+) tax\)$/, '花费 $1 购买了 $2 粮食 (包含了 $3 税费)'],
    [/^Plot (.+) unlocked successfully!$/, '地块 $1 已成功解锁！'],
    [/^Your price is (.+) above the lowest market price$/, '你方价格比最低市场价格高出 $1'],
    [/^Price is (.+) above 24h high$/, '价格比24小时内最高价高出 $1'],
    [/^Price exceeds (.+) above 24h high \((.+)\). Max allowed: (.+)$/, '价格超过24小时最高价（$2）的 $1。最高价限制：$3'],
    [/^Started selling (.+) units!$/, '开始出售 $1 单位!'],
    [/^Listed (.+) bread for sale \((.+) listing fee\)$/, '上架出售 $1 面包（$2 上架费）'],
    [/^Listed (.+) water for sale \((.+) listing fee\)$/, '上架出售 $1 水（$2 上架费）'],
    [/^Successfully listed (.+) Water for sale$/, '成功上架 $1 水 出售'],
    [/^Successfully listed (.+) Bread for sale$/, '成功上架 $1 面包 出售'],
    [/^Streak Day (.+) \- Keep it going!$/, '连续登录 $1 天 - 继续保持!'],
    [/^Price too high compared to market. Current lowest: (.+), max allowed: (.+)$/, '与市场价格相比，价格太高。目前最低：$1，最高允许：$2'],
    [/^Automatically restart production for (.+) building when completed$/, '建造完成后，自动重启 $1 座建筑的生产'],
    [/^Automatically restart production for (.+) buildings when completed$/, '建造完成后，自动重启 $1 座建筑的生产'],
    [/^Not enough water! Need (.+) for (.+) units, have (.+). Max producible: (.+)$/, '没有足够的水! $1 单位需要 $2, 拥有 $3. 最大可生产: $4'],
    [/^Not enough grain! Need (.+) for (.+) units, have (.+). Max producible: (.+)$/, '没有足够的谷物! $1 单位需要 $2, 拥有 $3. 最大可生产: $4'],
    [/^Not enough power! Need (.+) for (.+) units, have (.+). Max producible: (.+)$/, '没有足够的电力! $1 单位需要 $2, 拥有 $3. 最大可生产: $4'],
    [/^Not enough milk! Need (.+) for (.+) units, have (.+). Max producible: (.+)$/, '没有足够的牛奶! $1 单位需要 $2, 拥有 $3. 最大可生产: $4'],
    [/^Earn (.+) in your first day$/, '在你的第一天赚取 $1'],
    [/^Unlock all (.+) premium plots$/, '解锁全部 $1 会员地块'],
    [/^Unlock all (.+) plots$/, '解锁全部 $1 地块'],
    [/^Make (.+) market sales$/, '达成 $1 市场出售'],
    [/^Make (.+) market purchases$/, '达成 $1 市场购买'],
    [/^Complete (.+) retail sales$/, '完成 $1 零售销售'],
    [/^Collected (.+) units!$/, '收集了 $1 单位!'],
    [/^Started production of (.+) units!$/, '已开始生产 $1 单位!'],
    [/^Reach (.+) in total wealth$/, '达到 $1 总财富'],
    [/^Generate (.+) power$/, '生成 $1 电'],
    [/^Generate (.+) water$/, '生成 $1 水'],
    [/^Produce (.+) bread$/, '生产 $1 面包'],
    [/^Earn (.+) total$/, '总共赚取 $1'],
    [/^Place and manage your production buildings$/, '放置和管理您的生产建筑'],
    [/^Place (.+) buildings$/, '放置 $1 建筑'],
    [/^Play for (.+) consecutive days$/, '连续玩游戏 $1 天'],
    [/^Play for (.+) days$/, '玩游戏 $1 天'],
    [/^Play for (.+) consecutive days$/, '连续玩游戏 $1 天'],
    [/^Join (.+) players worldwide$/, '加入全球 $1 玩家的行列'],
    [/^Level (.+) • View Profile$/, '等级 $1 • 查看个人资料'],
    [/^Millionaire \- (.+) \| (.+) CC$/, '百万富翁 - $1 | $2 CC'],
    [/^Land Owner \- (.+) \| (.+) CC$/, '土地所有者 - $1 | $2 CC'],
    [/^City Builder \- (.+) \| (.+) CC$/, '城市建设者 - $1 | $2 CC'],
    [/^Breaking Ground \- (.+) \| (.+) CC$/, '破土动工 - $1 | $2 CC'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^Jan ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '1 月 $1 日 $2:$3'],
    [/^Feb ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '2 月 $1 日 $2:$3'],
    [/^Mar ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '3 月 $1 日 $2:$3'],
    [/^Apr ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '4 月 $1 日 $2:$3'],
    [/^May ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '5 月 $1 日 $2:$3'],
    [/^Jun ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '6 月 $1 日 $2:$3'],
    [/^Jul ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '7 月 $1 日 $2:$3'],
    [/^Aug ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '8 月 $1 日 $2:$3'],
    [/^Sep ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '9 月 $1 日 $2:$3'],
    [/^Oct ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '10 月 $1 日 $2:$3'],
    [/^Nov ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '11 月 $1 日 $2:$3'],
    [/^Dec ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '12 月 $1 日 $2:$3'],
    [/^Jan ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1 日 $3:$4'],
    [/^Feb ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1 日 $3:$4'],
    [/^Mar ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1 日 $3:$4'],
    [/^Apr ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1 日 $3:$4'],
    [/^May ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1 日 $3:$4'],
    [/^Jun ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1 日 $3:$4'],
    [/^Jul ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1 日 $3:$4'],
    [/^Aug ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1 日 $3:$4'],
    [/^Sep ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1 日 $3:$4'],
    [/^Oct ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1 日 $3:$4'],
    [/^Nov ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1 日 $3:$4'],
    [/^Dec ([\d\.,]+), ([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1 日 $3:$4'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^January ([\d\.,]+), ([\d\.,]+)$/, '$2 年 1 月 $2 日'],
    [/^February ([\d\.,]+), ([\d\.,]+)$/, '$2 年 2 月 $2 日'],
    [/^March ([\d\.,]+), ([\d\.,]+)$/, '$2 年 3 月 $2 日'],
    [/^April ([\d\.,]+), ([\d\.,]+)$/, '$2 年 4 月 $2 日'],
    [/^May ([\d\.,]+), ([\d\.,]+)$/, '$2 年 5 月 $2 日'],
    [/^June ([\d\.,]+), ([\d\.,]+)$/, '$2 年 6 月 $2 日'],
    [/^July ([\d\.,]+), ([\d\.,]+)$/, '$2 年 7 月 $2 日'],
    [/^August ([\d\.,]+), ([\d\.,]+)$/, '$2 年 8 月 $2 日'],
    [/^September ([\d\.,]+), ([\d\.,]+)$/, '$2 年 9 月 $2 日'],
    [/^October ([\d\.,]+), ([\d\.,]+)$/, ' $2 年 10 月 $2 日'],
    [/^November ([\d\.,]+), ([\d\.,]+)$/, ' $2 年 11 月 $2 日'],
    [/^December ([\d\.,]+), ([\d\.,]+)$/, ' $2 年 12 月 $2 日'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)x achievement points$/, '$1x 成就点'],
    [/^([\d\.]+)x experience gain$/, '$1x 经验增益'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Auto Slots$/, '$1 自动槽位'],
    [/^([\d\.,]+) slots available$/, '$1 槽位可用'],
    [/^([\d\.,]+) fruits$/, '$1 水果'],
    [/^([\d\.,]+) Gasoline$/, '$1 汽油'],
    [/^([\d\.,]+) Milk$/, '$1 牛奶'],
    [/^([\d\.,]+) Crude Oil$/, '$1 原油'],
    [/^([\d\.,]+) Steel Beams$/, '$1 钢板'],
    [/^([\d\.,]+) Coal$/, '$1 煤'],
    [/^([\d\.,]+) Natural Gas$/, '$1 天然气'],
    [/^([\d\.,]+) Consumer Appliances$/, '$1 家用电器'],
    [/^([\d\.,]+) Industrial Chemicals$/, '$1 工业化学品'],
    [/^([\d\.,]+) Industrial Equipment$/, '$1 工业设备'],
    [/^([\d\.,]+) Plastic Pellets$/, '$1 塑料颗粒'],
    [/^([\d\.,]+) Limestone$/, '$1 石灰岩'],
    [/^([\d\.,]+) Circuit Boards$/, '$1 电路板'],
    [/^([\d\.,]+) Concrete$/, '$1 混凝土'],
    [/^([\d\.,]+) Cattle$/, '$1 面包'],
    [/^([\d\.,]+) Bread$/, '$1 面包'],
    [/^([\d\.,]+) Cheese$/, '$1 奶酪'],
    [/^([\d\.,]+) Cattle$/, '$1 牛'],
    [/^([\d\.,]+) Grain$/, '$1 谷物'],
    [/^([\d\.,]+) Flour$/, '$1 面粉'],
    [/^([\d\.,]+) vegetables$/, '$1 蔬菜'],
    [/^([\d\.,]+) Plastic Products$/, '$1 塑料制品'],
    [/^([\d\.,]+) kL Water$/, '$1 kL 水'],
    [/^([\d\.,]+) MW Power$/, '$1 MW 电力'],
    [/^([\d\.,]+) Sandwich$/, '$1 三明治'],
    [/^([\d\.,]+) Fertilizer$/, '$1 肥料'],
    [/^([\d\.,]+) Dough$/, '$1 面团'],
    [/^([\d\.,]+) Steel$/, '$1 钢'],
    [/^([\d\.,]+) Iron Ore$/, '$1 铁矿石'],
    [/^([\d\.,]+) Slots$/, '$1 槽位'],
    [/^([\d\.,]+) Stone Blocks$/, '$1 石块'],
    [/^([\d\.,]+) Beef$/, '$1 牛肉'],
    [/^\+([\d\.,]+) Gasoline$/, '\+$1 汽油'],
    [/^\+([\d\.,]+) Milk$/, '\+$1 牛奶'],
    [/^\+([\d\.,]+) Crude Oil$/, '\+$1 原油'],
    [/^\+([\d\.,]+) Steel Beams$/, '\+$1 钢板'],
    [/^\+([\d\.,]+) Concrete$/, '\+$1 混凝土'],
    [/^\+([\d\.,]+) Coal$/, '\+$1 煤'],
    [/^\+([\d\.,]+) Natural Gas$/, '\+$1 天然气'],
    [/^\+([\d\.,]+) Consumer Appliances$/, '\+$1 家用电器'],
    [/^\+([\d\.,]+) Industrial Chemicals$/, '\+$1 工业化学品'],
    [/^\+([\d\.,]+) Industrial Equipment$/, '\+$1 工业设备'],
    [/^\+([\d\.,]+) Plastic Pellets$/, '\+$1 塑料颗粒'],
    [/^\+([\d\.,]+) Plastic Products$/, '\+$1 塑料制品'],
    [/^\+([\d\.,]+) Dough$/, '\+$1 面团'],
    [/^\+([\d\.,]+) Limestone$/, '\+$1 石灰岩'],
    [/^\+([\d\.,]+) Circuit Boards$/, '\+$1 电路板'],
    [/^\+([\d\.,]+) Fertilizer$/, '\+$1 肥料'],
    [/^\+([\d\.,]+) Cattle$/, '\+$1 面包'],
    [/^\+([\d\.,]+) Bread$/, '\+$1 面包'],
    [/^\+([\d\.,]+) Cheese$/, '\+$1 奶酪'],
    [/^\+([\d\.,]+) Cattle$/, '\+$1 牛'],
    [/^\+([\d\.,]+) Grain$/, '\+$1 谷物'],
    [/^\+([\d\.,]+) Flour$/, '\+$1 面粉'],
    [/^\+([\d\.,]+) vegetables$/, '\+$1 蔬菜'],
    [/^\+([\d\.,]+) kL Water$/, '\+$1 kL 水'],
    [/^\+([\d\.,]+) MW Power$/, '\+$1 MW 电力'],
    [/^\+([\d\.,]+) Sandwich$/, '\+$1 三明治'],
    [/^\+([\d\.,]+) Steel$/, '\+$1 钢'],
    [/^\+([\d\.,]+) Iron Ore$/, '\+$1 铁矿石'],
    [/^\+([\d\.,]+) Slots$/, '\+$1 槽位'],
    [/^\+([\d\.,]+) Stone Blocks$/, '\+$1 石块'],
    [/^\+([\d\.,]+) Beef$/, '\+$1 牛肉'],
    [/^([\d\.,]+) slot available$/, '$1 槽位可用'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) seconds ago$/, '$1 秒前'],
    [/^([\d\.,]+) second ago$/, '$1 秒前'],
    [/^([\d\.,]+) minutes ago$/, '$1 分钟前'],
    [/^([\d\.,]+) minute ago$/, '$1 分钟前'],
    [/^([\d\.,]+) hour ago$/, '$1 小时前'],
    [/^([\d\.,]+) hours ago$/, '$1 小时前'],
    [/^([\d\.,]+)h ([\d\.,]+)m$/, '$1 小时 $2 分钟'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();