/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    "Achievements": "成就",
    "About": "关于",
    "About Warzone": "关于战区",
    "Activision is suing us!": "动视起诉我们！",
    "Blog": "博客",
    "Change History": "更新日志",
    "Chat": "聊天",
    "Clan Wars": "部落战",
    "Clans": "氏族",
    "Community": "社区",
    "Community Events": "社区活动",
    "Community Levels": "社区等级",
    "Contact": "联系",
    "Create Game": "创建游戏",
    "Custom Game": "自定义游戏",
    "Dashboard": "仪表盘",
    "Forum": "论坛",
    "Frequently Asked Questions (FAQ": "常见问题（FAQ",
    "Help": "帮助",
    "Idle": "放置",
    "If you like Hasbro's RISK® game, you'll love Warzone! Play alone or with friends.\n           ": "如果您喜欢孩之宝的 RISK® 游戏，那么您一定会喜欢 Warzone！ 单独或与朋友一起玩。\n",
    "Ladders": "梯子",
    "Map of the Week": "本周地图",
    "Maps": "地图",
    "Multi-Player": "多人游戏",
    "Multiplayer Strategy Game": "多人策略游戏",
    "My Levels": "我的等级",
    "Open Games": "开放游戏",
    "Past Games": "过去的比赛",
    "Play": "开始",
    "Play Now": "开始游戏",
    "Player Search": "玩家搜索",
    "Quickmatch": "快速匹配",
    "Recent Games": "最近的游戏",
    "RISK® is a registered trademark of Hasbro, Inc.  Warzone is not affiliated with Hasbro.\n       ": "RISK® 是 Hasbro, Inc. 的注册商标。Warzone 不隶属于 Hasbro。\n",
    "Sign In": "登录",
    "Single-Player": "单人游戏",
    "Skill Game": "技能游戏",
    "Terms of Service": "服务条款",
    "Tournaments": "锦标赛",
    "Wiki": "Wiki",
    "You won!": "你赢了！",
    "You've reached the army cap": "你已经达到了军帽",
    "Next Level": "下一级",
    "No messages": "没有消息",
    "No-Split Mode": "无分割模式",
    "North Africa": "北非",
    "Northern Europe": "北欧",
    "Now click Northern Europe.": "现在单击北欧。",
    "Now click on Ukraine to order your armies to attack there.": "现在点击乌克兰命令你的军队攻击那里。",
    "Now, let's tell those armies to attack Ukraine.  First click Scandinavia.": "现在，让我们告诉那些军队攻击乌克兰。首先单击斯堪的纳维亚。",
    "Okay": "确定",
    "Opponent's Cards": "对手牌",
    "Orders": "命令",
    "Pause": "暂停",
    "Pending surrender": "等待投降",
    "Perspective: All": "透视：全部",
    "Players": "玩家",
    "Please pick the green territories you wish to start with.": "请选择您希望开始的绿色区域。",
    "Points": "积分",
    "PointsEarnedText": "获得积分文本",
    "Preparing game...": "准备比赛...",
    "Press to commit": "按提交",
    "Private": "私人的",
    "Proceed to Level 1": "进入第 1 级",
    "Public": "上市",
    "QuickmatchLabel": "快速匹配标签",
    "Rate this Map": "评价这张地图",
    "Rematch!": "复赛！",
    "Remove Ads": "移除广告",
    "Resume": "恢复",
    "Run": "跑",
    "Run+Commit": "运行+提交",
    "Scandinavia": "斯堪的纳维亚",
    "Select a territory or bonus to learn more about it": "选择一个地区或奖励以了解更多信息",
    "Select a territory or bonus to link into your message": "选择一个地区或奖励以链接到您的消息中",
    "Select a territory you own to build a city there.": "选择你拥有的领土，在那里建造一座城市。",
    "Send Message": "发信息",
    "Sending orders...": "发送命令...",
    "Set slider to 4": "将滑块设置为 4",
    "Share on Facebook": "分享到Facebook",
    "Show All": "显示所有",
    "Since we are done issuing attacks, click Commit.": "既然我们已经完成了攻击，请点击 提交。",
    "Since we are done issuing attacks, click the Commit button.": "由于我们已完成发出攻击，请单击“提交”按钮。",
    "Since we only attacked Northern Europe with four, we still have five armies in Ukraine that are not doing anything.  Click Ukraine again.": "由于我们只用四人袭击了北欧，我们在乌克兰仍有五支军队无所作为。再次单击乌克兰。",
    "Skip": "跳过",
    "Skip Tutorial": "跳过教程",
    "South Africa": "南非",
    "Southern Europe": "欧洲南部",
    "Static": "静止",
    "Statistics": "统计",
    "Stats": "统计",
    "Surrender": "投降",
    "Take over from AI": "接替 AI",
    "Team": "团队",
    "Team A": "队伍 A",
    "Text": "文本",
    "The first step of every turn is deploying your new armies.  Click on Scandinavia five times to deploy all five armies.": "每一个回合的第一步都是部署你的新军队。点击斯堪的纳维亚五次以部署所有五支军队。",
    "There are no remaining armies to attack from this territory": "没有剩余的军队可以从这片领土进攻",
    "These gray territories are neutral.  In this tutorial, you will conquer these lands to expand your empire.": "这些灰色地带是中立的。在本教程中，您将征服这些土地以扩展您的帝国。",
    "These green territories are yours.": "这些绿色领域是你的。",
    "This \"3\" next to Europe indicates that it is a bonus that is worth three extra armies per turn.  Click it to highlight the bonus.": "欧洲旁边的这个“3”表示这是一个奖励，每回合可以增加三支军队。单击它以突出显示奖励。",
    "This game has been archived and can no longer receive new chat": "此游戏已存档，无法再接收新聊天",
    "This win contributed towards earning your clan a territory on the Clan War map!  Visit the Clan Wars page to see all territories your clan has earned as well as their progress to the next one.": "这场胜利有助于为您的氏族赢得氏族战争地图上的领土！访问部落战争页面，查看您的部落获得的所有领地以及他们在下一个领地中的进度。",
    "Tooltip": "工具提示",
    "Tournament": "比赛",
    "Transfer mode: Attack or Transfer": "转移方式：攻击或转移",
    "Treat Teammates as Enemies": "将队友视为敌人",
    "Try Again": "再试一次",
    "Turn x of y": "回合 x / y",
    "Turns": "回合",
    "Tutorial": "教程",
    "Ukraine": "乌克兰",
    "Use the history button to see what happened behind the fog.": "使用历史按钮查看迷雾背后发生了什么。",
    "Victory!": "胜利！",
    "Viewing Teammate Orders": "查看队友命令",
    "Vote to End": "投票结束",
    "Voted to end the game": "投票结束比赛",
    "Watch": "手表",
    "Welcome to Warzone!  Yellow boxes like this one will show you how to play.": "欢迎来到战区！像这样的黄色盒子会告诉你怎么玩。",
    "Western Europe": "西欧",
    "Winner!\n11 armies per turn": "赢家！\n每回合 11 支军队",
    "Winner!\n8 armies per turn": "获胜者！\n每回合 8 支军队",
    "WinSaveText": "保存文本",
    "You": "你",
    "You cannot issue an attack or transfer of 0 armies": "您不能发起攻击或转移 0 军队",
    "You control all of Europe except for these two territories.  Once you capture them, you will control the entire bonus and receive an additional three armies per turn.": "你控制了除这两个领土之外的整个欧洲。 占领它们后，您将控制整个奖励并每回合额外获得三支军队。",
    "You have got the basics down now.  If you want more practice, you can keep playing and capture Africa.  Otherwise, you can skip straight to Level 1, where there will be opponents to fight against.": "你现在已经掌握了基础知识。 如果您想要更多练习，您可以继续玩并占领非洲。 否则，您可以直接跳到 1 级，那里会有对手要对抗。",
    "Build Cities": "建造城市",
    "Cancel": "取消",
    "Capture Africa": "占领非洲",
    "Check the ladder page to see where you stand on this ladder.": "检查梯子页面以查看您在此梯子上的位置。",
    "Check the tournament page for up-to-date tournament standings.": "查看锦标赛页面以获取最新的锦标赛排名。",
    "Clear Orders": "清除命令",
    "Click Begin to start": "点击开始开始",
    "Click Commit": "单击提交",
    "Click Northern Europe": "点击北欧",
    "Click Okay": "单击确定",
    "Click Okay to attack with four armies.": "单击确定以四支军队攻击。",
    "Click Okay to confirm the order and attack with all five armies. When attacking, you usually want to attack with at least twice as many armies as the defending territory has.": "单击“确定”以确认命令并与所有五支军队一起进攻。进攻时，你通常希望用至少两倍于防御领土的军队进行进攻。",
    "Click Okay to order the attack of Southern Europe.": "单击“确定”命令进攻南欧。",
    "Click on a territory you own and then on one of its neighbors.": "单击您拥有的领土，然后单击其邻居之一。",
    "Click Scandinavia": "点击斯堪的纳维亚",
    "Click Southern Europe": "点击南欧",
    "Click the 3": "点击 3",
    "Click Ukraine": "点击乌克兰",
    "Click Ukraine.": "点击乌克兰。",
    "Close": "关闭",
    "CoinsText": "硬币文本",
    "Commit": "提交",
    "Congo": "刚果",
    "Congratulations, you have now conquered the entire Europe bonus giving you three extra armies per turn!": "恭喜，您现在已经征服了整个欧洲奖励，每回合为您提供三支额外的军队！",
    "Congratulations, your armies successfully conquered Ukraine!": "恭喜，你的军队成功征服了乌克兰！",
    "Congratulations! You won in 6 turns.": "恭喜！你在 6 回合内获胜。",
    "Distributing": "分发",
    "Done Building": "完成建筑",
    "Downloading map \"Tutorial\"...": "正在下载地图“教程”...",
    "Each turn you receive new armies.  Right now, you are receiving five armies per turn.": "每回合你都会收到新的军队。现在，你每回合增加五个军队。",
    "East Africa": "东非",
    "Egypt": "埃及",
    "End": "结尾",
    "Enjoy this level? Reward the creator by giving them a like!": "享受这个级别？给创作者一个赞来奖励他们！",
    "Europe": "欧洲",
    "Exit History": "退出历史",
    "Export to YouTube": "导出到 YouTube",
    "Finish versus AI": "完成与 AI",
    "Game": "游戏",
    "Game Settings": "游戏设置",
    "Game Summary": "游戏总结",
    "Great Britain": "大不列颠",
    "Hide Teammate's Orders": "隐藏队友的命令",
    "Highest income": "最高收入",
    "History": "历史",
    "Iceland": "冰岛",
    "Ladder": "梯子",
    "Let's only attack with four armies so that we can send the others to Southern Europe.  Set the number of armies to four.": "让我们只用四支军队进攻，这样我们就可以把其他军队送到南欧。将军队的数量设置为四。",
    "Let's send them to Southern Europe so we can capture the rest of the bonus.": "让我们把他们送到南欧，这样我们就可以拿到剩下的奖励了。",
    "Let's start by conquering Northern Europe.  Deploy your new armies to Ukraine by clicking there five times.": "让我们从征服北欧开始吧。点击那里五次，将您的新军队部署到乌克兰。",
    "Level Select": "级别选择",
    "Like": "像",
    "Load Older Messages": "加载旧消息",
    "Loading game...": "游戏载入中...",
    "Loading history...": "载入历史...",
    "Madagascar": "马达加斯加",
    "Middle East": "中东",
    "Modify orders": "修改命令",
    "Move Order": "移动顺序",
    "Next": "下一步",
    "Next Game": "下一场比赛",
    "[picks]": "[挑选]",
    "* You": "* 你",
    "Attacks do not happen immediately after you issue them.  When you issue orders to your troops, they are stored in the orders list on the right.  Here you can modify your orders if you make a mistake.": "攻击不会在您发出后立即发生。 当您向部队发出命令时，它们会存储在右侧的命令列表中。 如果您搞错了，您可以在此处修改您的命令。",
    "AchievementsHeader": "成就标题",
    "Active Cards": "活动卡",
    "Africa": "非洲",
    "All Graphs": "所有图表",
    "Analyze": "分析",
    "Analyze Attack": "分析攻击",
    "armies": "军队",
    "Armies killed": "军队被杀",
    "Armies lost": "军队丢失",
    "Armies produced": "生产的军队",
    "Army Graph": "陆军图",
    "Attack by Percentage": "百分比攻击",
    "Attack or Transfer": "攻击或转移",
    "Autopilot": "自动驾驶仪",
    "Beginning": "开始",
    "Custom Scenario": "自定义场景",
    "No Fog": "无雾",
    "Quebec": "魁北克",
    "S. Europe": "南欧",
    "Siam": "暹",
    "Siberia": "西伯利亚",
    "South America": "南美洲",
    "Template: Time to take a risk": "模板：是时候冒险了",
    "This win has been saved to your device.  If you create an account, your wins will be saved to your account.": "此胜利已保存到您的设备中。如果您创建一个帐户，您的奖励将保存到您的帐户中。",
    "Time to take a risk": "是时候冒险了",
    "Ural": "乌拉尔",
    "Venezuela": "委内瑞拉",
    "W. Europe": "W. 欧洲",
    "Western Australia": "澳大利亚西部",
    "Western United States": "美国西部",
    "Yakutsk": "雅库茨克",
    "You have already issued an attack or transfer between these territories.  Changes you make here will override your previous order.": "您已经在这些地区之间发起了攻击或转移。您在此处所做的更改将覆盖您之前的订单。",
    "You start on the verge of capturing the Europe bonus.  You should capture Europe and then march into Australia and eliminate the enemy.  Good luck!": "您即将获得欧洲红利。你应该占领欧洲，然后进军澳大利亚，消灭敌人。祝你好运！",
    "Downloading map \"Small Earth Board Map\"...": "正在下载地图“小地球板图”...",
    "Eastern Australia": "东澳大利亚",
    "Eastern United States": "美国东部",
    "Eliminated": "被淘汰",
    "Fog level is No Fog": "雾级别为无雾",
    "Full Settings": "完整设置",
    "Greenland": "格陵兰",
    "India": "印度",
    "Indonesia": "印度尼西亚",
    "Irkutsk": "伊尔库茨克",
    "Japan": "日本",
    "Kamchatka": "堪察加",
    "Kazakhstan": "哈萨克斯坦",
    "MessageFromHost": "来自主机的消息",
    "Mexico": "墨西哥",
    "Mongolia": "蒙古",
    "N. Europe": "北欧洲",
    "New Guinea": "新几内亚",
    "North America": "北美",
    "Northwest Territory": "西北地区",
    "Oceania": "大洋洲",
    "Ontario": "安大略省",
    "Peru": "秘鲁",
    "AI was eliminated!": "AI被淘汰了！",
    "Alaska": "阿拉斯加州",
    "Alberta": "阿尔伯塔",
    "Argentina": "阿根廷",
    "Asia": "亚洲",
    "Brazil": "巴西",
    "China": "中国",
    "Coins": "硬币",
    "Congratulations! You won in 12 turns.": "恭喜！您在 12 回合内获胜。",
    "Custom scenario: Each player receives pre-determined starting territories": "自定义场景：每个玩家都会收到预先确定的起始区域",
    "Kill or be killed": "杀或被杀",
    "kleintje off 11% def 91": "kleintje 折扣 11% def 91",
    "Korean War": "朝鲜战争",
    "kronos": "克罗诺斯",
    "landing": "降落",
    "ldb": "数据库",
    "Live by the sword...": "以剑为生……",
    "lol": "哈哈",
    "Luck be a lady": "幸运的是一位女士",
    "Medieval Japan": "中世纪的日本",
    "Mehikonien & Aergard 3-Way": "Mehikonien & Aergard 三通",
    "Mind Games": "智力游戏",
    "Monkey in the Middle..Harder Version": "中间的猴子..更难的版本",
    "Mound of War": "战争之丘",
    "Navy Battle 12 Player": "海军战斗 12 玩家",
    "Now you see me...": "现在你看到我...",
    "Outer Space": "外太空",
    "outrageous v3": "离谱的v3",
    "Patience is a Virtue": "耐心是一种美德",
    "Peloponnesian War": "伯罗奔尼撒战争",
    "Petrol": "汽油",
    "Pirate Trouble": "海盗麻烦",
    "pirates!": "海盗！",
    "Playing favorites": "播放收藏夹",
    "Please do not post ridiculous games": "请不要发布荒谬的游戏",
    "Prowl in Old Town": "在老城区徘徊",
    "Quick Challenge": "快速挑战",
    "Race to the middle": "跑到中间",
    "Revolution": "革命",
    "Rise of Assyria": "亚述崛起",
    "Rise of Fascist Romania P1": "法西斯罗马尼亚崛起 P1",
    "Rome - Partha vs Spain vs Italy": "罗马 - 帕塔vs西班牙vs意大利",
    "Schleswig-Holstein": "石勒苏益格-荷尔斯泰因",
    "Serfs up": "奴役",
    "Siege of Feldmere": "围攻费尔德米尔",
    "Sinister water": "险恶的水",
    "Six Pack": "六包",
    "Skull Island - 1935 Venture Expedition": "骷髅岛 - 1935 年的冒险探险",
    "Snowflakes 3-Way": "雪花三通",
    "Someone stole my oil": "有人偷了我的油",
    "Sri Lankan Hastiness": "斯里兰卡的仓促",
    "Stuck together": "粘在一起",
    "support your AI": "支持你的人工智能",
    "Surprise! (5": "惊喜！ （5",
    "survival strategy": "生存策略",
    "Survive and Thrive": "生存和发展",
    "Take the Castle": "拿下城堡",
    "Team Work": "团队合作",
    "Thani`s Stand": "塔尼的立场",
    "The Asteroid": "小行星",
    "The best defense...": "最好的防守...",
    "The Coliseum": "体育馆",
    "The Concordia Duel": "康科迪亚决斗",
    "The Frenzy Lumberjack Duo": "疯狂的伐木工人二人组",
    "The Harbor": "海港",
    "The Italian Hunt": "意大利狩猎",
    "The Mischievous Neighbours": "恶作剧的邻居",
    "The Yeti": "雪人",
    "Three blind mice": "三只盲鼠",
    "three front war - one at a time": "三线战争——一次一场",
    "Time to take a risk but something is wrong here": "是时候冒险了，但这里出了点问题",
    "Top of the plateau": "高原之巅",
    "Tricky Europe V2": "棘手的欧洲 V2",
    "Triple Threat": "三重威胁",
    "Vietnam War": "越南战争",
    "Viking Battle in the Bork Land": "博克地的维京人之战",
    "Viking landing": "维京登陆",
    "Volcano mayhem": "火山混乱",
    "War for Zargos (advanced": "扎戈斯之战（高级",
    "War of Ages": "世纪之战",
    "Warzone": "战区",
    "who owns the moon?": "谁拥有月亮？",
    "Win in 7 turns to earn a gold star!": "在 7 回合内获胜即可获得金星！",
    "Wizard's lightning": "巫师的闪电",
    "World War 2320": "2320年世界大战",
    "World War Pixel": "世界大战像素",
    "Wrath of the Aliens pt.4": "外星人的愤怒 pt.4",
    "x-factor": "x因子",
    "X, Y and Z": "X、Y 和 Z",
    "You won in 12 turns.": "您在 12 回合内获胜。",
    "You won in 6 turns.": "你在 6 回合内获胜。",
    "Your only ally": "你唯一的盟友",
    "zapper": "灭霸",
    "Zodiac Czar": "十二生肖沙皇",
    "1 weak and 1 useless allied": "1个弱者和1个无用的盟友",
    "5 guys for the Mosslands": "莫斯兰兹 的 5 人",
    "A Battle in Jerusalem (LD": "耶路撒冷之战（LD",
    "A different approach": "不同的方法",
    "A New World": "新世界",
    "A Ride Through Hell": "穿越地狱",
    "Aklog Island": "阿克洛岛",
    "Alaska Medium 3-Way": "阿拉斯加中型三通",
    "and a skip will become available": "并且跳过将变得可用",
    "Around Black Sea Total WAAAR": "黑海周边地区 Total WAAAR",
    "Battle": "战斗",
    "Battle Arena": "战斗竞技场",
    "Battle of the Elements": "元素之战",
    "Battle of the Nations 1813": "1813年万国之战",
    "Battle Perfection: Artifical Intelligence I": "完美战斗：人工智能 I",
    "Beginner Level (7": "初级（7",
    "Better to give": "最好给",
    "Biomes - they swing both ways": "生物群系——它们双向摆动",
    "Blind man's game": "盲人的游戏",
    "Break the bank": "打破银行",
    "Caesar's challenge": "凯撒的挑战",
    "Calling all reinforcements": "召集所有援军",
    "castle": "城堡",
    "Castles battle to conquer Far Land": "城堡为征服边境之地而战",
    "Chaos": "混乱",
    "China teams": "中国队",
    "Civilisation Wars": "文明战争",
    "Complex Complex": "复杂的",
    "con": "骗局",
    "Conquer the island": "征服岛屿",
    "Conquest of the Solar System Part 1": "征服太阳系第 1 部分",
    "Corridor War": "走廊战争",
    "Crossword puzzle": "填字游戏",
    "Deadly Trio": "致命三人组",
    "Defender": "后卫",
    "Defense of Numenor": "努门诺尔保卫战",
    "Dog fight": "狗打架",
    "Doom is Nigh - 4": "末日来临 - 4",
    "Eight Bridges": "八桥",
    "FAST WD #1": "快速 WD #1",
    "Feeling Blue": "情绪低落",
    "Finding the limit": "寻找极限",
    "Fisher Island": "费希尔岛",
    "Floating Skills": "浮动技能",
    "Forest Wars, Episode V - The Empire Strikes Back": "森林战争，第五集 - 帝国反击",
    "Frustrated with a level? Try hard": "对等级感到沮丧？努力",
    "Get a clue": "得到一条线索",
    "Getting Commercial": "商业化",
    "Getting Strategic": "获得战略性",
    "Gungy 6": "冈吉 6",
    "Hadrian's Wall": "哈德良长城",
    "Half and half": "一半一半",
    "Ham or Turkey": "火腿或火鸡",
    "Hard to get": "很难得到",
    "hard to get it": "很难得到",
    "Help the Priestess of Psion": "帮助心灵术士的女祭司",
    "Hiding Place": "藏身之地",
    "Hirilia 3-Way": "Hirilia 三通",
    "Hold the line": "守住线",
    "Hopscotch": "跳房子",
    "How many turns do you need?": "你需要转几圈？",
    "Impossible Intervention Challenge": "不可能的干预挑战",
    "Inchmeal": "寸粉",
    "Interesting WW1 Game": "有趣的一战游戏",
    "Island Hopping": "跳岛游",
    "Island War B": "岛屿战争 B",
    "Isthmus 3-Way": "地峡 3 路",
    "Italian Free For All": "意大利语免费",
    "Italo Turkish War": "伊塔洛土耳其战争",
    "keep the north": "保持北方",
    "Kill 'em all!!!": "杀光他们！！！",
    "Level 1 -\nReveals how much ore or armies an upgrade to a mine or army camp will give if you purchase it.\n\nReveals where your armies and money came from.  Tap/hover over the armies/money sliders in the top right corner.\n\nReveals how many armies hospitals and the Joint Strike advancement have saved you in the current level.\n\n- Level 2 -\nEnables the Modifiers dialog that lists all effects you have enabled.\n\nReveals how much ore you're generating per second of each ore type.  Look at the top of the mines tab.\n\nReveals how long you've been playing the current level, both in real-world time and in-game time.  Tap/hover over the army slider in the top right corner.\n\n- Level 3 -\nReveals stats about recipes you've found.  Shows the cost of its ingredients, profit, profit per second, number you have the resources to make, how many of your smelters/crafters are already working on that recipe, and how many are needed for all un-purchased techs that you can see.\n\n - Level 4 -\nReveals all techs included in your current level and their requirements.\n\nReveals stats about each level: How many times you've played it, won it, what powers you've earned from it, how much AP you've earned from it.\n\nReveals how many armies are visible on unconquered territories on the map.": "1 级 -\n显示如果您购买矿井或军营升级后将获得多少矿石或军队。\n\n显示您的军队和金钱的来源。点击/悬停在右上角的军队/金钱滑块上。\n\n显示在当前关卡中有多少军队医院和联合打击进阶拯救了你。\n\n- 关卡 2 -\n启用修改器对话框列出您已启用的所有效果。\n\n显示每种矿石类型每秒生成的矿石量。查看地雷选项卡的顶部。\n\n显示您在当前关卡中玩了多长时间，无论是在现实世界时间还是在游戏时间。点击/悬停在右上角的军队滑块上。\n\n- 第 3 级 -\n显示您找到的食谱的统计数据。显示其原料成本、利润、每秒利润、您有多少资源可以制造、有多少冶炼厂/工匠已经在研究该配方，以及您可以看到的所有未购买的技术需要多少.\n\n - 第 4 级 -\n显示您当前级别中包含的所有技术及其要求。\n\n显示有关每个级别的统计信息：您玩过多少次，赢过多少次，您获得了哪些能力它，你从中获得了多少 AP。\n\n显示在地图上未征服的领土上可以看到多少军队。",
    "Unlock by spending 1,000 more AP in phase 1": "在第 1 阶段花费 1,000 更多 AP 即可解锁",
    "Update All": "全部更新",
    "Upgrade\n": "升级\n",
    "Upgrade\n1200": "升级\n1200",
    "Use armies, represented by the symbol ₳, to conquer territories.  Select Argentina now to conquer it.": "使用以符号₳表示的军队来征服领土。现在选择阿根廷来征服它。",
    "View": "看法",
    "View All": "查看全部",
    "View on Wikipedia": "在维基百科上查看",
    "Warzone Idle": "战区放置",
    "Welcome to Warzone Idle!": "欢迎来到战区空闲！",
    "You acquired a mine named Gaspo!  It produces the following resources and can be upgraded to produce more": "您获得了一个名为 Gaspo 的矿山！它生产以下资源，并且可以升级以生产更多",
    "You captured South America!  It earns you ￦1 money per second": "你占领了南美！它每秒为您赚取 ￦1 钱",
    "You found a cache!": "你找到了一个宝藏！",
    "Unclaimed Powers": "无人认领的权力",
    "Unlock": "解锁",
    "Sell Resources": "出售资源",
    "Sell the ore your mine generates for extra money (￦": "出售您的矿山产生的矿石以赚取额外收入（￦",
    "Skip Level": "跳过级别",
    "Smelters": "冶炼厂",
    "Steal a bunch of resources from a market of your choice": "从您选择的市场中窃取大量资源",
    "Store": "店铺",
    "Super Ascend": "超级登高",
    "SuperCamp": "超级营",
    "Supercharge Army Camp": "增压军营",
    "Supercharge Mine": "增压矿山",
    "SuperchargedLabel": "增压标签",
    "Superpowers": "超级大国",
    "Tap a territory to conquer it if you have enough armies": "如果你有足够的军队，点击一个领土来征服它",
    "TargetTypeLabel": "目标类型标签",
    "Techs": "技术",
    "Territories": "领土",
    "South America": "南美",
    "Bonuses": "奖励",
    "Bonuses that include Middle East": "包括中东的奖励",
    "BundleName": "捆绑名称",
    "Cache": "宝藏",
    "Caches award 10% more money.  Upgradable to 100% in 5% increments.": "Caches 奖励 10% 更多的钱。以 5% 的增量可升级到 100%。",
    "Can see the location of the first 3 mines.  Upgradable to 66 in increments of 3.": "可以看到前3个地雷的位置。以 3 为增量可升级到 66。",
    "Can start one level higher on the main menu than you currently can": "可以在主菜单上比您当前可以启动更高一级",
    "Can't find territories?": "找不到领土？",
    "Capture South America": "占领南美",
    "Captured Bonus": "获取的奖励",
    "Challenges": "挑战",
    "Challenges are played using your advancements and artifacts only.  No interaction is allowed.  They can be attempted once you unlock Auto-Conquer (phase 2 advancement": "挑战仅使用您的进阶和神器进行。不允许交互。解锁自动征服后可以尝试它们（第 2 阶段进展）",
    "Claim Artifact!": "索取神器！",
    "Clan Requests": "氏族请求",
    "Connection Arrows": "连接箭头",
    "Connections List": "连接列表",
    "Continue conquering territories and see what you can discover!": "继续征服领土，看看你能发现什么！",
    "Continue on your own": "继续自己",
    "Copper": "铜",
    "Crafters": "工匠",
    "Current value: 300": "当前值：300",
    "Decreases the amount of time it takes to smelt things by 10%.  Upgradable to 50% in 5% increments.": "熔炼物品所需的时间减少 10%。可按 5% 的增量升级到 50%。",
    "Dig Sites": "挖掘站点",
    "DigHeaderLabel": "挖掘头标签",
    "DigLocationLabel": "挖掘位置标签",
    "DigStatusLabel": "挖掘状态标签",
    "Discounted Mine Upgrades": "折扣矿山升级",
    "Dismiss All": "关闭所有",
    "Double": "双倍的",
    "Find": "寻找",
    "Finish Now": "立即完成",
    "Fog Buster": "雾克星",
    "fogged": "雾化的",
    "Free Cache": "免费宝藏",
    "Gaspo": "加斯波",
    "generated": "生成",
    "Get AP (advancement points) when you win a level": "赢得关卡时获得 AP（进阶点数）",
    "Get Coins": "获得金币",
    "Gislic": "吉斯利奇",
    "Hospitals": "医院",
    "Increase Smelters Speed": "提高冶炼厂速度",
    "Increased Army Camp Production": "增加军营生产",
    "Increased Cache Money": "增加宝藏资金",
    "Increased Copper Production": "铜产量增加",
    "Increased Idle Time": "空闲时间增加",
    "Increased Iron Production": "增加铁产量",
    "Increased Ore Sell Values": "增加矿石销售价值",
    "Increased Tin Production": "锡产量增加",
    "Increases armies received from all army camps by 10%. Upgradable to 500% in 10% increments.": "从所有军营接收的军队增加 10%。以 10% 的增量可升级到 500%。",
    "Increases the maximum amount of idle time you can accrue at once by 30 minutes.  Unlimited upgrades in 30 minute increments.": "将您一次可以累积的最大空闲时间增加 30 分钟。以 30 分钟为增量无限升级。",
    "Increases the number of armies available in mercenary camps by 10%.  Upgradable to 150% in 2.5% increments.": "雇佣军营地中可用的军队数量增加 10%。以 2.5% 的增量可升级到 150%。",
    "Inspire Mercenaries": "激励雇佣兵",
    "Instantly get a free cache of money, resources, and armies": "立即获得免费的宝藏资金、资源和军队宝藏",
    "Instantly hire all mercenaries from one mercenary camp of your choice for free": "立即从您选择的一个雇佣兵营地免费雇佣所有雇佣兵",
    "Items/Alloys": "物品/合金",
    "Join Battle": "加入战斗",
    "Joint Strike": "联合罢工",
    "Level Stats": "等级统计",
    "Levels": "级别",
    "Market Raid": "市场突袭",
    "Markets": "市场",
    "Mercenary Camps": "佣兵营地",
    "Middle East Connections": "中东连接",
    "Mine upgrades cost 5% less.  Upgradable to 25% in 2% increments.": "矿山升级成本降低 5%。可按 2% 的增量升级到 25%。",
    "Mine Visibility": "矿山能见度",
    "Gaspo": "加斯波",
    "Mines": "矿山",
    "Modifiers": "修饰符",
    "Multi Level": "多层次",
    "NameLabel": "名称标签",
    "Next Action: 3s": "下一步行动：3s",
    "No Battles available right now.  Check back later.": "目前没有可用的战斗。过一会再来检查。",
    "Now capture the rest of South America": "现在占领南美洲其他地区",
    "Ore": "矿石",
    "Ores sell for 10% more money.  Upgradable to 100% in 5% increments.": "矿石售价高出 10%。以 5% 的增量可升级到 100%。",
    "per second\n4 territories": "每秒\n4 个地区",
    "Permanent upgrades": "永久升级",
    "Play another level simultaneously!": "同时玩另一个关卡！",
    "Powerful abilities to propel your empire forward": "强大的能力推动你的帝国前进",
    "Powers": "权力",
    "Purchase": "购买",
    "Receive 10% more Copper from mines.  Upgradable to 200% in 5% increments.": "从矿山中获得的铜增加 10%。以 5% 的增量可升级到 200%。",
    "Receive 10% more Iron from mines.  Upgradable to 200% in 5% increments.": "从矿山中获得的铁量增加 10%。以 5% 的增量可升级到 200%。",
    "Receive 10% more Tin from mines.  Upgradable to 200% in 5% increments.": "从矿山中获得的锡量增加 10%。以 5% 的增量可升级到 200%。",
    "Reset Spent AP": "重置消耗的 AP",
    "Reveals 150 fogged territories": "揭示 150 个迷雾区域",
    "Reveals additional statistics about your empire.  Upgradable to 4.": "显示有关您的帝国的其他统计数据。可升级到4。",
    "Rewards": "奖励",
    "Select": "选择",
    "Select a Resource": "选择资源",
    "A mine of your choice produces 20x resources for 10 minutes": "您选择的矿山 10 分钟产生 20 倍的资源",
    "Abort Level": "中止级别",
    "Activate": "启用",
    "Additional Mercenaries": "额外雇佣兵",
    "Advance time by one hour": "提前一小时",
    "Advancements": "进阶",
    "An army camp of your choice produces 20x armies for 5 minutes": "您选择的军营在 5 分钟内产生 20 倍军队",
    "ArmiesPerSecondLabel": "军队每秒标签",
    "Army camp": "军营",
    "Army Camps": "军营",
    "Artifacts": "神器",
    "Ascend": "转生",
    "Attack": "攻击",
    "Create an account!": "创建一个帐户！",
    "E-Mail": "电子邮件",
    "Email address": "电子邮件地址",
    "Facebook": "Facebook",
    "false": "错误",
    "Forgot Password": "忘记密码",
    "Keep me signed in": "保持登录状态",
    "New to Warzone? ": "新来的战区？",
    "OR -": "或者 -",
    "Password": "密码",
    "Sign in with Facebook": "使用 Facebook 登录",
    "That page requires a free account. Please sign-in first.": "该页面需要一个免费帐户。 请先登录。",
    "Warzone respects your privacy. Nothing will be posted to your Facebook account unless you explicitly request it.": "Warzone 尊重您的隐私。 除非您明确要求，否则不会将任何内容发布到您的 Facebook 帐户。",
    "Your WarLight credentials work here!": "您的 WarLight 凭证在这里有效！",
    "Time away": "时间离开",
    "Time Warp": "时间扭曲",
    "Tin": "锡",
    "to conquer": "征服",
    "to conquer\n": "征服\n",
    "To unlock...": "去解锁...",
    "Totals": "总计",
    "Welcome Back": "欢迎回来",
    "You acquired a mine named Hopesonen!  It produces the following resources and can be upgraded to produce more": "您获得了一个名为 霍普索宁 的矿山！ 它生产以下资源，并且可以升级以生产更多",
    "Your armies were training hard while you were away": "你不在的时候，你的军队正在刻苦训练",
    "Armies trained while you were away": "你不在时训练的军队",
    "Army Camp: Gislic\n": "军营: 吉斯利奇\n",
    "Bonus: Oceania": "奖励：大洋洲",
    "Bonuses that include North Africa": "包括北非的奖励",
    "Cache\n": "宝藏\n",
    "Hopesonen": "霍普索宁",
    "Max idle time": "最长放置时间",
    "Mine: Hopesonen": "矿山：霍普索宁",
    "Money earned while you were away": "你不在时赚到的钱",
    "North Africa Connections": "北非连接",
    "Oceania Territories": "大洋洲领土",
    "per second": "每秒",
    "Purchase Coins": "购买金币",
    "Tin Bar": "锡锭",
    "Open": "打开",
    "each": "每个",
    "Freadwels": "弗里德韦尔",
    "Inactive": "不活跃",
    "available for": "可用于",
    "Change\nRecipe": "更改\n配方",
    "Copper Bar": "铜锭",
    "- Inactive -\nSelect Change Recipe to activate": "- 不活动 -\n选择更改配方以激活",
    "/ sec": "/ 秒",
    "25% bonus active (3:33:33": "25% 奖励活跃 (3:33:33",
    "5% of your armies are retained when conquering a territory you control two or more connections to.  Upgradable to 25% in 2% increments.": "征服您控制两个或更多连接的领土时，保留 5% 的军队。 可按 2% 的增量升级到 25%。",
    "available for purchase for": "可供购买",
    "maxed": "最大",
    "Mercenary Camp": "雇佣兵营地",
    "Bonuses that include India": "包括印度在内的奖励",
    "Bonuses that include Siberia": "包括西伯利亚在内的奖励",
    "Recipe for Copper Bar": "铜锭配方",
    "Recipe for Tin Bar": "锡锭配方",
    "Smelter": "冶炼厂",
    "South America Territories": "南美洲领土",
    "Ukraine Connections": "乌克兰连接",
    "Armies": "军队",
    "camp doesn't have this many armies": "营地没有这么多军队",
    "Deactivate": "停用",
    "Deactivate Smelter": "停用冶炼厂",
    "for": "",
    "Loading level...": "加载等级...",
    "Money": "金钱",
    "Pick Recipe": "选择配方",
    "Waiting for Resources": "等待资源",
    "Your armies and resources accumulate over time, even when you're offline.  So if you find things are moving too slow, take a break and come back later.  Warzone Idle is meant to be played in small bursts throughout your day, not in one sitting.  Have fun!": "即使您处于离线状态，您的军队和资源也会随着时间的推移而积累。 因此，如果您发现事情进展得太慢，请休息一下，稍后再回来。 战区放置 旨在在您的一天中以小批量播放，而不是一次播放。 玩得开心！",
    "You captured West Path!  It earns you ￦5 money per second": "你占领了西路！ 它每秒为您赚取 ￦5 钱",
    "West Path Territories": "西路领地",
    "Woods": "木头",
    "Village Path": "乡村小径",
    "West Path": "西径",
    "The West": "西部",
    "Riverside Path": "河畔小径",
    "Resource Cache": "资源宝藏",
    "Let's go": "我们走吧",
    "Money Cache": "金钱宝藏",
    "Hut Territories": "小屋领土",
    "Courtyard West": "西庭院",
    "Downloading map \"Huruey's Castle\"...": "正在下载地图“Huruey的城堡”...",
    "Drafting": "起草",
    "Edit": "编辑",
    "Faster Smelters": "更快的冶炼厂",
    "Getting map...": "获取地图...",
    "Huruey's Castle": "Huruey的城堡",
    "Hut": "小屋",
    "Castle Entrance": "城堡入口",
    "Castle Gate": "城堡门",
    "Castle Steps": "城堡台阶",
    "Bridge Territories": "桥梁领土",
    "Campfire": "营火",
    "Campfire Territories": "营火领土",
    "Can draft extra armies from your territories.  Tap the icon when you see it to draft.": "可以从您的领土征召额外的军队。 看到草稿时点击图标。",
    "Castle": "城堡",
    "Castle Bridge": "城堡大桥",
    "Balcony": "阳台",
    "Barehand Mining": "徒手采矿",
    "Basic Marketing": "基础营销",
    "Bridge": "桥",
    "All mines produce 10% more ore": "所有矿山的矿石产量增加 10%",
    "Army Cache": "军队宝藏",
    "Army Cache\n": "军队缓存\n",
    "Back Path": "返回路径",
    "Castle Wall": "城墙",
    "Gaspo\n": "加斯彭\n",
    "Ladder East": "楼梯东",
    "Path": "小路",
    "Path Territories": "路径区域",
    "Resource Cache\n": "资源宝藏\n",
    "The West Territories": "西领地",
    "Tower East": "东塔",
    "Tower North": "北塔",
    "Village": "村庄",
    "You captured Woods!  It earns you ￦100 money per second": "你占领了木头！ 它每秒为您赚取 ￦100 钱",
    "You found a cache of resources!": "您找到了资源宝藏！",
    "Total armies earned": "获得的军队总数",
    "Total money earned": "赚取的总金额",
    "Money Stats": "金钱统计",
    "Money per second": "金钱每秒",
    "Army Stats": "军队统计",
    "You'll find attacks on the map.  Click the Attack button to launch these attacks at another player, which does things like destroy their army camps, mines, and more.  You can only hold one attack at a time, so if you pick up a second one without using the first it will immediately launch the second attack at another player.  Note that an attack cannot destroy the army camp you start with, so it's never possible to get completely stuck.": "你会在地图上找到攻击。 单击“攻击”按钮以向另一名玩家发起这些攻击，这会破坏他们的军营、地雷等。 您一次只能进行一次攻击，因此如果您在没有使用第一次的情况下拿起第二次攻击，它将立即对另一名玩家发动第二次攻击。 请注意，攻击无法摧毁您开始的军营，因此永远不可能完全卡住。",
    "The artifacts you have equipped when starting the battle will be the only ones you can use during the battle, so make sure to arrange your artifacts before joining.  Since time runs at an accelerated rate, you can likely activate artifacts multiple times during a single battle.": "开始战斗时装备的神器将是战斗中唯一可以使用的神器，因此请务必在加入前安排神器。 由于时间以加速的速度运行，您可能会在一场战斗中多次激活神器。",
    "All of your advancements can be used during the battle.  Auto-advancements, such as auto-conquer, don't count as actions and therefore are very valuable.  For this reason, owning the auto-conquer advancement is required to join a battle.": "你所有的进步都可以在战斗中使用。 自动推进，例如自动征服，不算作行动，因此非常有价值。 因此，加入战斗需要拥有自动征服进度。",
    "AD 1045: Roads of Silk and Iron": "公元 1045 年：丝绸之路和钢铁之路",
    "Afro-Eurasia Gargantuan": "非洲-欧亚大陆巨人",
    "All players involved in the battle play the same idle level at the same time.  You can see thumbnails of each player's progress on the right side of your screen to compare how you're doing.": "参与战斗的所有玩家同时玩相同的空闲级别。您可以在屏幕右侧查看每个玩家进度的缩略图，以比较您的表现。",
    "Asia: Population Density": "亚洲：人口密度",
    "Australia": "澳大利亚",
    "Battles require a solid internet connection to play without getting disconnected.": "战斗需要稳固的互联网连接才能玩而不会断开连接。",
    "Battles run at an accelerated rate, which allows completing an entire idle level in just a few minutes.": "战斗以更快的速度进行，这允许在短短几分钟内完成整个空闲级别。",
    "Breaking Green": "打破绿色",
    "Copper Creek Castle": "铜溪城堡",
    "Drakemor's World": "德雷克莫的世界",
    "Europe 1066 AD": "公元 1066 年的欧洲",
    "Europe Huge": "欧洲巨大",
    "Far Land": "遥远之地",
    "Final Earth": "最终地球",
    "Floating Rocks": "浮石",
    "Fort Harbor": "堡港",
    "Geopolitics": "地缘政治",
    "K-PX": "K-PX",
    "locked": "锁定",
    "Netherlands": "荷兰",
    "Old Town": "老镇",
    "Orbis Veteribus Notus": "Orbis Veteribus Notus",
    "Play Idle in a competitive multi-player battle royale with up to 30 players!": "在多达 30 名玩家的竞争性多人大逃杀中玩 放置！",
    "Reconquest 1065": "重新征服 1065",
    "Resume Huruey's Castle": "恢复 Huruey 的城堡",
    "Rise and Fall of the Roman Empire": "罗马帝国的兴衰",
    "Scandinavia and the Nordic Countries": "斯堪的纳维亚和北欧国家",
    "Sengoku : Rise of Oda Nobunaga": "战国：织田信长的崛起",
    "The Siege of Feldmere": "费尔德米尔围城战",
    "Triskelion": "三叉戟",
    "United States": "美国",
    "Ursa:Luna": "大熊座：月神",
    "War Of The Worlds": "世界大战",
    "You can only take an action every 4 seconds.  Actions can be things like conquering territories, upgrading an asset, drafting, activating an artifact, etc.": "您只能每 4 秒执行一次操作。行动可以是征服领土、升级资产、起草、激活神器等。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Small Earth Board Map": "小地球板图",
    //原样
    "v0.1.24-b49a4a4": "v0.1.24-b49a4a4",
    "Gityx": "Gityx",
    'ID': 'ID',
    'h': 'h',
    'm': 'm',
    'AI': 'AI',
    'R': 'R',
    'T': 'T',
    'C': 'C',
    'X': 'X',
    'U': 'U',
    'A': 'A',
    '': '',
    '': '',
    '': '',

}

//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    ": ": "： ",
    "\n           ": "\n           ",
    "\n          ": "\n          ",
    "\n         ": "\n         ",
    "\n        ": "\n        ",
    " ": "",
    "↓  ": "↓  ",
    "Fog level: ": "雾气等级: ",
    "Map: ": "地图: ",
    "Territory: ": "领土：",
    "Bonus: ": "奖励：",
    "Mine: ": "矿山：",
    "Copper Bar (": "铜锭 (",
    "Tin Bar (": "锡锭 (",
    "Woods ": "木头 ",
    "Back Path ": "后路 ",
    "Bridge ": "桥 ",
    "Castle Bridge ": "城堡大桥 ",
    "Castle Wall ": "城墙 ",
    "Courtyard ": "庭院 ",
    "Hut ": "小屋 ",
    "Ladder West ": "阶梯西 ",
    "Passage ": "通道 ",
    "River Path ": "河道 ",
    "Tower East ": "东塔 ",
    "Village ": "村庄 ",
    "West Path ": "西路 ",
    "Steps ": "步骤 ",
    "Increases sell price of all ores by ": "将所有矿石的售价提高 ",
    "Increases speed of all smelters by ": "提高所有冶炼厂的速度 ",
    "Bonuses that include Hut ": "奖励在小屋 ",
    "Bonuses that include Village ": "奖励在村庄 ",
    "Bonuses that include River Path ": "奖励在河道 ",
    "Ladder East": "楼梯东",
    "Tower North": "北塔 ",
    "Tower West": "西塔 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    " ": " ",
    " armies captured Alaska from Kamchatka": "军队从 堪察加 夺取 阿拉斯加",
    " army captured Western Australia from Indonesia": " 军队从 印度尼西亚 夺取 西澳大利亚",
    " armies captured Western Australia from Indonesia": " 军队从 印度尼西亚 夺取 西澳大利亚",
    " armies captured Siam from Indonesia": " 军队从 印度尼西亚 夺取 暹罗",
    " armies captured Middle East from Ukraine": " 军队从 乌克兰 夺取 中东",
    " army captured Indonesia from New Guinea": " 军队从 新几内亚 夺取 印度尼西亚",
    " army captured Middle East from India": " 军队从 印度夺取 中东",
    " army captured Mongolia from Japan": " 军队从 日本 夺取 蒙古",
    " armies captured China from Siam": " 军队从 暹罗 夺取 中国",
    " armies captured Ural from China": " 军队从 中国 夺取 乌拉尔",
    " armies captured Yakutsk from Irkutsk": " 军队从 伊尔库茨克 夺取 雅库茨克",
    " armies captured India from Siam": " 军队从 暹罗 夺取 印度",
    " armies captured Indonesia from Siam": " 军队从 暹罗 夺取 印度尼西亚",
    " armies captured Japan from Mongolia": " 军队从 蒙古 夺取 日本",
    " armies captured Kamchatka from Mongolia": " 军队从 蒙古 夺取 堪察加半岛",
    " armies captured Kazakhstan from Ural": " 军队从 乌拉尔 夺取 哈萨克斯坦",
    " armies captured Mongolia from Siberia": " 军队从 西伯利亚 夺取 蒙古",
    " armies captured New Guinea from Western Australia": " 军队从 西澳大利亚 占领 新几内亚",
    " armies captured Siberia from Yakutsk": " 军队从 雅库茨克 占领 西伯利亚",
    " armies captured Western Australia from New Guinea": " 军队从 新几内亚 占领 西澳大利亚",
    " armies captured Argentina from Brazil": " 军队从 巴西 夺取了阿根廷",
    " armies captured Brazil from North Africa": " 军队从 北非 占领 巴西",
    " armies captured East Africa from Egypt": " 军队从 埃及 夺取 东非",
    " armies captured Eastern Australia from Western Australia": " 军队从 西澳大利亚 占领 东澳大利亚",
    " armies captured Eastern United States from Quebec": " 军队从 魁北克 占领 美国东部",
    " armies captured Irkutsk from Mongolia": " 军队从 蒙古 占领 伊尔库茨克",
    " armies captured Irkutsk from Siberia": " 军队从 西伯利亚 夺取 伊尔库茨克",
    " armies captured Japan from Kamchatka": " 军队从 堪察加 夺取 日本",
    " armies captured Kamchatka from Mongolia": " 军队从 蒙古 占领 堪察加半岛",
    " armies captured Kazakhstan from Middle East": " 军队从 中东 占领 哈萨克斯坦",
    " armies captured Mexico from Venezuela": " 军队从 委内瑞拉 夺取 墨西哥",
    " armies captured Middle East from S. Europe": " 军队从 南欧 占领 中东",
    " armies captured Middle East from Ukraine": " 军队从 乌克兰 夺取 中东",
    " armies captured Mongolia from China": " 军队从 中国 夺取 蒙古",
    " armies captured Mongolia from Irkutsk": " 军队从 伊尔库茨克 占领 蒙古",
    " armies captured North Africa from W. Europe": " 军队从 西欧 占领 北非",
    " armies captured Peru from Brazil": " 军队从 巴西 夺取 秘鲁",
    " armies captured Quebec from Greenland": " 军队从 格陵兰 占领 魁北克",
    " armies captured Siam from China": " 军队从 中国 夺取 暹罗",
    " armies captured Siberia from Ural": " 军队从 乌拉尔 夺取 西伯利亚",
    " armies captured Southern Europe from Ukraine": " 军队从 乌克兰 夺取 南欧",
    " armies captured Ukraine from S. Europe": " 军队从 南欧 夺取 乌克兰",
    " armies captured Ural from Siberia": " 军队从 西伯利亚 夺取 乌拉尔",
    " armies captured Ural from Ukraine": " 军队从 乌克兰 夺取 乌拉尔",
    " armies captured Venezuela from Peru": " 军队从 秘鲁 夺取 委内瑞拉",
    " armies captured Western Australia from Indonesia": " 军队从 印度尼西亚 占领 西澳大利亚",
    " armies captured Western United States from Mexico": " 军队从 墨西哥 占领 美国西部",
    " armies captured Yakutsk from Irkutsk": " 军队从 伊尔库茨克 夺取 雅库茨克",
    " armies captured Yakutsk from Siberia": " 军队从 西伯利亚 夺取 雅库茨克",
    " armies captured Alberta from Ontario": " 军队从 安大略省 夺取 阿尔伯塔省",
    " armies captured China from Kazakhstan": " 军队从 哈萨克斯坦 夺取 中国",
    " armies captured Egypt from S. Europe": " 军队从 南欧 夺取 埃及",
    " armies captured Greenland from Iceland": " 军队从 冰岛 占领格陵兰",
    " armies captured India from Middle East": " 军队从 中东 占领 印度",
    " armies captured Indonesia from New Guinea": " 军队从 新几内亚 夺取 印度尼西亚",
    " armies captured New Guinea from Eastern Australia": " 军队从 东澳大利亚 占领 新几内亚",
    " armies captured Siberia from China": " 军队从 中国 夺取 西伯利亚",
    " armies captured Indonesia from New Guinea": " 军队从 新几内亚 夺取 印度尼西亚",
    " armies captured Kazakhstan from India": " 军队从 印度 夺取 哈萨克斯坦",
    " armies captured Northwest Territory from Greenland": " 军队从 格陵兰 占领 西北地区",
    " armies captured Ontario from Eastern United States": " 军队从 美国东部 占领 安大略",
    " armies captured Middle East from Kazakhstan": " 军队从 哈萨克斯坦 占领 中东",
    " armies from Western Australia will attack/transfer New Guinea": " 来自西澳大利亚的军队将攻击/转移新几内亚",
    " armies from Ukraine will attack/transfer Middle East": " 来自乌克兰的军队将攻击/转移中东",
    " armies from Indonesia will attack/transfer Western Australia": " 来自印度尼西亚的军队将攻击/转移西澳大利亚",
    " armies from Siberia will attack/transfer Yakutsk": " 来自西伯利亚的军队将攻击/转移雅库茨克",
    " armies from India will attack/transfer Kazakhstan": " 印度军队将攻击/转移哈萨克斯坦",
    " armies from Iceland will attack/transfer Greenland": " 来自冰岛的军队将攻击/转移格陵兰",
    " armies from Kamchatka will attack/transfer Alaska": " 堪察加的军队将攻击/转移阿拉斯加",
    " armies from Kazakhstan will attack/transfer China": " 哈萨克斯坦军队将进攻/转移中国",
    " armies from Middle East will attack/transfer India": " 来自中东的军队将攻击/转移印度",
    " armies from New Guinea will attack/transfer Indonesia": " 来自新几内亚的军队将攻击/转移印度尼西亚",
    " armies from Ontario will attack/transfer Alberta": " 来自安大略的军队将攻击/转移阿尔伯塔",
    " armies from S. Europe will attack/transfer Egypt": " 来自南欧的军队将攻击/转移埃及",
    " armies from Yakutsk will attack/transfer Siberia": " 来自雅库茨克的军队将进攻/转移西伯利亚",
    " armies from Eastern United States will attack/transfer Ontario": " 来自美国东部的军队将攻击/转移安大略",
    " armies from Greenland will attack/transfer Northwest Territory": " 格陵兰的军队将攻击/转移西北地区",
    " armies from Brazil will attack/transfer Argentina": " 来自巴西的军队将攻击/转移阿根廷",
    " armies from Brazil will attack/transfer Peru": " 来自巴西的军队将攻击/转移秘鲁",
    " armies from China will attack/transfer Siam": " 来自中国的军队将攻击/转移暹罗",
    " armies from Egypt will attack/transfer East Africa": " 来自埃及的军队将攻击/转移东非",
    " armies from Greenland will attack/transfer Quebec": " 格陵兰的军队将攻击/转移魁北克",
    " armies from Indonesia will attack/transfer Western Australia": " 来自印度尼西亚的军队将攻击/转移西澳大利亚",
    " armies from Irkutsk will attack/transfer Mongolia": " 伊尔库茨克的军队将进攻/转移蒙古",
    " armies from Irkutsk will attack/transfer Yakutsk": " 来自伊尔库茨克的军队将进攻/转移雅库茨克",
    " armies from Kamchatka will attack/transfer Japan": " 堪察加的军队将攻击/转移日本",
    " armies from Mexico will attack/transfer Western United States": " 来自墨西哥的军队将攻击/转移美国西部",
    " armies from Middle East will attack/transfer Kazakhstan": " 来自中东的军队将攻击/转移哈萨克斯坦",
    " armies from Mongolia will attack/transfer Irkutsk": " 蒙古军队将进攻/转移伊尔库茨克",
    " armies from Mongolia will attack/transfer Kamchatka": " 来自蒙古的军队将攻击/转移堪察加半岛",
    " armies from North Africa will attack/transfer Brazil": " 来自北非的军队将攻击/转移巴西",
    " armies from North Africa will attack/transfer Congo": " 来自北非的军队将攻击/转移刚果",
    " armies from Peru will attack/transfer Venezuela": " 来自秘鲁的军队将攻击/转移委内瑞拉",
    " armies from Quebec will attack/transfer Eastern United States": " 来自魁北克的军队将攻击/转移美国东部",
    " armies from S. Europe will attack/transfer Middle East": " 来自南欧的军队将进攻/转移中东",
    " armies from S. Europe will attack/transfer Ukraine": " 来自南欧的军队将攻击/转移乌克兰",
    " armies from Siam will attack/transfer Indonesia": " 来自暹罗的军队将攻击/转移印度尼西亚",
    " armies from Siberia will attack/transfer Mongolia": " 来自西伯利亚的军队将攻击/转移蒙古",
    " armies from Siberia will attack/transfer Ural": " 来自西伯利亚的军队将攻击/转移乌拉尔",
    " armies from Siberia will attack/transfer Yakutsk": " 来自西伯利亚的军队将攻击/转移雅库茨克",
    " armies from Ukraine will attack/transfer Middle East": " 来自乌克兰的军队将攻击/转移中东",
    " armies from Ukraine will attack/transfer Ural": " 来自乌克兰的军队将攻击/转移乌拉尔",
    " armies from Ural will attack/transfer Siberia": " 乌拉尔的军队将进攻/转移西伯利亚",
    " armies from Venezuela will attack/transfer Mexico": " 来自委内瑞拉的军队将攻击/转移墨西哥",
    " armies from W. Europe will attack/transfer North Africa": " 来自西欧的军队将攻击/转移北非",
    " armies from Western Australia will attack/transfer Eastern Australia": " 来自西澳大利亚的军队将攻击/转移东澳大利亚",
    " armies from Yakutsk will attack/transfer Irkutsk": " 来自雅库茨克的军队将进攻/转移伊尔库茨克",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)\:(\d+)\:(\d+)$/,
    /^(\d+)$/,
    /^L(\d+)$/,
    /^(.+) PM$/,
    /^(.+) PM$/,
    /^(.+) AM$/,
    /^欢迎 (.+) 来到 放置大陆！$/,
    /^\[(\d+),(\d+)\]$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\-([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^₳([\d\.]+)K$/,
    /^￦([\d\.]+)K$/,
    /^₳([\d\.]+)$/,
    /^￦([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^￦([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Current\:(.+) \/ Next\: (.+)$/, '当前\: $1 \/ 下一个\: $2'],
    [/^spent (.+) gold here!$/, '在这里花了 $1 金币！'],
    [/^(\d+) Scroll\(s$/, '$1 卷轴'],
    [/^(\d+) Copper$/, '$1 铜'],
    [/^Currently have ([\d\.]+) AP \(advancement points$/, '目前有 $1 AP（进阶点数'],
    [/^(\d+) armie$/, '$1 军队'],
    [/^(\d+) minutes$/, '$1 分钟'],
    [/^Next victory is worth (.+) AP$/, '下一场胜利价值 $1 AP'],
    [/^The Time Warp power costs (.+) coins but you only have (.+)$/, '时间扭曲力量需要 $1 金币，但你只有 $2'],
    [/^You found a cache of (.+) armies!$/, '你找到了 $1 军队的宝藏！'],
    [/^Your best time is (.+) hour (.+) minutes\nNext victory is worth (.+) AP$/, '你的最佳时间是 $1 小时 $2 分钟\n下一场胜利价值 $3 AP'],
    [/^per second\n(\d+) territories$/, '每秒\n$1 领土'],
    [/^(\d+) upgrades available$/, '$1 升级可用'],
    [/^Phase (\d+)$/, '阶段 $1'],
    [/^\n(\d+) territories$/, '\n$1 领土'],
    [/^₳(\d+) armies$/, '₳$1 军队'],
    [/^₳(\d+)K armies$/, '₳$1K 军队'],
    [/^₳(\d+)M armies$/, '₳$1M 军队'],
    [/^₳(\d+)B armies$/, '₳$1B 军队'],
    [/^￦(\d+) Money$/, '￦$1 金钱'],
    [/^￦([\d\.]+) money$/, '￦$1 金钱'],
    [/^￦([\d\.]+)K money$/, '￦$1K 金钱'],
    [/^￦([\d\.]+)M money$/, '￦$1M 金钱'],
    [/^￦([\d\.]+)B money$/, '￦$1B 金钱'],
    [/^￦([\d\.]+) money\/sec$/, '￦$1 金钱\/秒'],
    [/^￦([\d\.]+) money per second$/, '￦$1 金钱每秒'],
    [/^￦([\d\.]+)K money per second$/, '￦$1K 金钱每秒'],
    [/^￦([\d\.]+)M money per second$/, '￦$1M 金钱每秒'],
    [/^￦([\d\.]+)B money per second$/, '￦$1B 金钱每秒'],
    [/^₳([\d\.]+) \(([\d\.]+)\/sec$/, '₳$1 \($2\/秒'],
    [/^₳([\d\.]+)K \(([\d\.]+)\/sec$/, '₳$1K \($2\/秒'],
    [/^₳([\d\.]+)M \(([\d\.]+)\/sec$/, '₳$1M \($2\/秒'],
    [/^₳([\d\.]+)B \(([\d\.]+)\/sec$/, '₳$1B \($2\/秒'],
    [/^￦([\d\.]+) \(([\d\.]+)\/sec$/, '￦$1 \($2\/秒'],
    [/^￦([\d\.]+)K \(([\d\.]+)\/sec$/, '￦$1K \($2\/秒'],
    [/^(\d+) upgrade available$/, '$1 升级可用'],
    [/^([\d\.]+) Copper \/ second$/, '$1 铜 \/ 秒'],
    [/^(\d+) armies$/, '$1 军队'],
    [/^(\d+) armies per turn$/, '$1 军队每回合'],
    [/^(\d+) territories for (\d+) armies per turn$/, '每回合 $2 军队获得 $1 领土'],
    [/^(\d+) gold$/, '$1 黄金'],
    [/^You have (\d+) coins$/, '你有 $1 金币'],
    [/^Sell (\d+)\nfor$/, '出售 $1\n获得'],
    [/^Sell ([\d\.]+)K\nfor$/, '出售 $1K\n获得'],
    [/^Sell ([\d\.]+)M\nfor$/, '出售 $1M\n获得'],
    [/^Sell ([\d\.]+)B\nfor$/, '出售 $1B\n获得'],
    [/^Sell ([\d\.]+)\nfor ([\d\.]+)$/, '出售 $1\n获得 $2'],
    [/^Unlock\n(\d+) AP$/, '解锁\n$1 AP'],
    [/^Winner!\n(\d+) armies per turn$/, '获胜者！\n每回合 $1 军队'],
    [/^(\d+) armies captured Egypt from North Africa$/, '$1 军队 从 北非 占领 埃及'],
    [/^(\d+) armies captured Northern Europe from Ukraine$/, '$1 军队 从 乌克兰 占领 北欧'],
    [/^(\d+) armies captured Madagascar from East Africa$/, '$1 军队 从 东非 占领 马达加斯加'],
    [/^(\d+) armies captured East Africa from Middle East$/, '$1 军队 从 中东 占领 东非'],
    [/^(\d+) armies captured Middle East from Southern Europe$/, '$1 军队 从 南欧 占领 中东'],
    [/^(\d+) armies captured North Africa from Western Europe$/, '$1 军队 从 西欧 占领 北非'],
    [/^(\d+) armies captured South Africa from Congo$/, '$1 军队 从 刚果 占领 南非'],
    [/^(\d+) armies captured South Europe from Ukraine$/, '$1 军队 从 乌克兰 占领 南欧'],
    [/^(\d+) armies captured Congo from North Africa$/, '$1 军队 从 北非 占领 刚果'],
    [/^(\d+) armies captured Ukraine from Scandinavia$/, '$1 军队 从 斯堪的纳维亚半岛 占领 乌克兰'],

    [/^(\d+) armies from East Africa will attack\/transfer Madagascar$/, '$1 军队 从 东非 出发将 进攻\/移动到 马达加斯加'],
    [/^(\d+) armies from North Africa will attack\/transfer Egypt$/, '$1 军队 从 东非 出发将 进攻\/移动到 埃及'],
    [/^(\d+) armies from Ukraine will attack\/transfer Northern Europe$/, '$1 军队 从 乌克兰 出发将 进攻\/移动到 北欧'],
    [/^(\d+) armies from Middle East will attack\/transfer East Africa$/, '$1 军队 从 中东 出发将 进攻\/移动到 东非'],
    [/^(\d+) armies from Congo will attack\/transfer South Africa$/, '$1 军队 从 刚果 出发将 进攻\/移动到 南非'],
    [/^(\d+) armies from Scandinavia will attack\/transfer Ukraine$/, '$1 军队 从 斯堪的纳维亚半岛 出发将 进攻\/移动到 乌克兰'],
    [/^(\d+) armies from Southern Europe will attack\/transfer Middle East$/, '$1 军队 从 南欧 出发将 进攻\/移动到 中东'],
    [/^(\d+) armies from Ukraine will attack\/transfer Southern Europe$/, '$1 军队 从 乌克兰 出发将 进攻\/移动到 南欧'],
    [/^(\d+) armies from  Western Europe will attack\/transfer North Africa$/, '$1 军队 从 西欧 出发将 进攻\/移动到 北非'],
    [/^(\d+) armies from  North Africa will attack\/transfer Congo$/, '$1 军队 从 北非 出发将 进攻\/移动到 刚果'],

    [/^(\d+) armies have orders.  You can issue orders to the remaining armies.$/, '$1 军队 有命令。您可以向剩余的军队发出命令。'],
    [/^([\d\.,]+) \/ ([\d\.,]+) armies deployed$/, '$1 \/ $2 军队已部署'],
    [/^Deploy ([\d\.,]+) to Great Britain$/, '部署 $1 到 英国'],
    [/^Deploy ([\d\.,]+) to Middle East$/, '部署 $1 到 中东'],
    [/^Deploy ([\d\.,]+) to Ukraine\nPlayer: You$/, '部署 $1 到 乌克兰\n玩家：你'],
    [/^Deploy ([\d\.,]+) to Middle East$/, '部署 $1 到 中东'],
    [/^Deploy ([\d\.,]+) to Scandinavia$/, '部署 $1 到 斯堪的纳维亚'],
    [/^Deploy ([\d\.,]+) to Western Europe$/, '部署 $1 到 西欧'],
    [/^Deploy ([\d\.,]+) to North Africa$/, '部署 $1 到 北非'],
    [/^Deploy ([\d\.,]+) to Southern Europe$/, '部署 $1 到 南欧'],
    [/^Deploy ([\d\.,]+) to Scandinavia$/, '部署 $1 到 斯堪的纳维亚'],
    [/^Deploy ([\d\.,]+) to Ukraine$/, '部署 $1 到 乌克兰'],
    [/^Deploy ([\d\.,]+) to Irkutsk$/, '部署 $1 到 伊尔库茨克'],
    [/^Deploy ([\d\.,]+) to Kazakhstan$/, '部署 $1 到 哈萨克斯坦'],
    [/^Deploy ([\d\.,]+) to W. Europe$/, '部署 $1 到 西欧'],
    [/^Deploy ([\d\.,]+) to Siberia$/, '部署 $1 到 西伯利亚'],
    [/^Deploy ([\d\.,]+) to Yakutsk$/, '部署 $1 到 雅库茨克'],
    [/^Deploy ([\d\.,]+) to China$/, '部署 $1 到 中国'],
    [/^Deploy ([\d\.,]+) to S. Europe$/, '部署 $1 到 南欧'],
    [/^Deploy ([\d\.,]+) to Kamchatka$/, '部署 $1 到 堪察加'],
    [/^Deploy ([\d\.,]+) to Congo$/, '部署 $1 到 刚果'],
    [/^Deploy ([\d\.,]+) to Mongolia$/, '部署 $1 到 蒙古'],
    [/^Deploy ([\d\.,]+) to India$/, '部署 $1 到 印度'],
    [/^Deploy ([\d\.,]+) to Indonesia$/, '部署 $1 到 印度尼西亚'],
    [/^Deploy ([\d\.,]+) to Alaska$/, '部署 $1 到 阿拉斯加'],
    [/^Deploy ([\d\.,]+) to Japan$/, '部署 $1 到 日本'],
    [/^Deploy ([\d\.,]+) to Mexico$/, '部署 $1 到 墨西哥'],
    [/^Deploy ([\d\.,]+) to Peru$/, '部署 $1 到 秘鲁'],
    [/^Deploy ([\d\.,]+) to Quebec$/, '部署 $1 到 魁北克'],
    [/^Deploy ([\d\.,]+) to Ural$/, '部署 $1 到 乌拉尔'],
    [/^Deploy ([\d\.,]+) to Venezuela$/, '部署 $1 到 委内瑞拉'],
    [/^Deploy ([\d\.,]+) to Brazil$/, '部署 $1 到 巴西'],
    [/^Deploy ([\d\.,]+) to Siam$/, '部署 $1 到 暹罗'],
    [/^Deploy ([\d\.,]+) to Greenland$/, '部署 $1 到 格陵兰'],
    [/^Deploy ([\d\.,]+) to Iceland$/, '部署 $1 到 冰岛'],
    [/^Deploy ([\d\.,]+) to Ontario$/, '部署 $1 到 安大略'],
    [/^Deploy ([\d\.,]+) to Eastern United States$/, '部署 $1 到 美国东部'],
    [/^Deploy ([\d\.,]+) to Western United States$/, '部署 $1 到 美国西部'],
    [/^Deploy ([\d\.,]+) to New Guinea$/, '部署 $1 到 新几内亚'],
    [/^Deploy ([\d\.,]+) to East Africa$/, '部署 $1 到 东非'],
    [/^Deploy ([\d\.,]+) to Eastern Australia$/, '部署 $1 到 澳大利亚东部'],
    [/^Deploy ([\d\.,]+) to Western Australia$/, '部署 $1 到 澳大利亚西部'],
    [/^([\d\.,]+) armies transferred to India from Siam$/, '$1 军队从 暹罗 移动到 印度'],
    [/^([\d\.,]+) armies transferred to Indonesia from Western Australia$/, '$1 军队从 澳大利亚西部 移动到 印度尼西亚'],
    [/^([\d\.,]+) armies transferred to Mongolia from Japan$/, '$1 军队从 日本 移动到 蒙古'],
    [/^([\d\.,]+) armies transferred to Siam from Indonesia$/, '$1 军队从 印度尼西亚 移动到 暹罗'],
    [/^([\d\.,]+) armies transferred to Yakutsk from Kamchatka$/, '$1 军队从 堪察加 移动到 雅库茨克'],
    [/^([\d\.,]+) armies transferred to China from Ural$/, '$1 军队从 乌拉尔 移动到 中国'],
    [/^([\d\.,]+) armies transferred to East Africa from Middle East$/, '$1 军队从 中东 移动到 东非'],
    [/^([\d\.,]+) armies transferred to Egypt from Middle East$/, '$1 军队从 中东 移动到 埃及'],
    [/^([\d\.,]+) armies transferred to Kazakhstan from China$/, '$1 军队从 中国 移动到 哈萨克斯坦'],
    [/^([\d\.,]+) armies transferred to S. Europe from Middle East$/, '$1 军队从 中东 移动到 南欧'],
    [/^([\d\.,]+) armies transferred to Kazakhstan from India$/, '$1 军队从 印度 移动到 哈萨克斯坦'],
    
    [/^([\d\.,]+) army failed to take Siberia from Yakutsk$/, '$1 军队 未能从 雅库茨克 夺取 西伯利亚'],
    [/^([\d\.,]+) army failed to take Ukraine from Kazakhstan$/, '$1 军队 未能从 哈萨克斯坦 夺取 乌克兰'],
    [/^([\d\.,]+) armies failed to take Siam from Indonesia$/, '$1 军队 未能从 印度尼西亚 夺取 暹罗'],
    [/^([\d\.,]+) armies failed to take Kamchatka from Alaska$/, '$1 军队 未能从 阿拉斯加 夺取 堪察加'],
    [/^([\d\.,]+) armies failed to take Yakutsk from Siberia$/, '$1 军队 未能从 西伯利亚 夺取 雅库茨克'],
    [/^([\d\.,]+) armies failed to take Irkutsk from Yakutsk$/, '$1 军队 未能从 雅库茨克 夺取 伊尔库茨克'],
    [/^([\d\.,]+) armies failed to take Siam from Indonesia$/, '$1 军队 未能从 印度尼西亚 夺取 暹罗'],
    [/^([\d\.,]+) armies failed to take Siberia from Yakutsk$/, '$1 军队 未能从 雅库茨克 夺取 西伯利亚'],
    [/^([\d\.,]+) armies failed to take Ural from Ukraine$/, '$1 军队 未能从 乌克兰 夺取 乌拉尔'],
    [/^([\d\.,]+) armies failed to take Kazakhstan from India$/, '$1 军队 未能从 印度 夺取 哈萨克斯坦'],
    [/^([\d\.,]+) armies failed to take Eastern Australia from Western Australia$/, '$1 军队 未能从 澳大利亚西部 夺取 澳大利亚东部'],
    [/^([\d\.,]+) armies failed to take Kazakhstan from China$/, '$1 军队 未能从 中国 夺取 哈萨克斯坦'],
    [/^([\d\.,]+) armies failed to take Siberia from Mongolia$/, '$1 军队 未能从 蒙古 夺取 西伯利亚'],
    [/^([\d\.,]+) armies failed to take Yakutsk from Siberia$/, '$1 军队 未能从 西伯利亚 夺取 雅库茨克'],
    
    

    [/^Turn (\d+)$/, '回合 $1'],
    [/^Kills (\d+)$/, '杀死 $1'],
    [/^Watch Turn (\d+)$/, '观看回合 $1'],
    [/^(\d+) hours$/, '$1 小时'],
    [/^(\d+) Recipe$/, '$1 配方'],
    [/^Touched (\d+) times$/, '触碰 $1 次'],
    [/^CON \+(\d+)$/, '体质 \+$1'],
    [/^HP \+(\d+)$/, '生命值 \+$1'],
    [/^INT \+(\d+)$/, '智力 \+$1'],
    [/^STR \+(\d+)$/, '力量 \+$1'],
    [/^GOLD \+(\d+)$/, '金币 \+$1'],
    [/^You have (.+) ILP$/, '你有 $1 ILP'],
    [/^Buy for (.+) gold$/, '购买需要 $1 金币'],
    [/^(.+) has (.+) stamina$/, '$1 有 $2 耐力'],
    [/^Generalize \((\d+) Stamina$/, '一般化 \($1 耐力'],
    [/^Current\: (\d+) ILP \/ Next\: (\d+) ILP$/, '当前\: $1 ILP / 下一个\: $2 ILP'],
    [/^Current\: (\d+)q \/ Next\: (\d+)q$/, '当前\: $1q / 下一个\: $2q'],
    [/^Current\: (.+)s \/ Next\: (.+)s$/, '当前\: $1s / 下一个\: $2s'],
    [/^Current\: (\d+) Lv. \/ Next\: (\d+) Lv.$/, '当前\: $1 级 / 下一个\: $2 级'],
    [/^Current\: (.+)\% \/ Next\: (.+)$/, '当前\: $1\% \/ 下一个\: $2'],
    [/^You can make a guild for (.+) gold.$/, '您可以花费 $1 金币建立1个公会。'],
]);

//2.采集新词
//20190320@JAR

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({
                text,
                itemgroup,
                dsc: "不识别的标签" + i
            })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function (text, node) {

    if (typeof (text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof (cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof (cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({
                    text: i,
                    cnitem: cnItems[i],
                    node
                });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function (a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function (node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function () {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function () {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function (e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                            transTaskMgr.doTask();
                        }
                    }
                }
            }
        }
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
}();